import { Flame, Waves, Globe, Layers, Zap } from 'lucide-react'
import { BRAND } from '@/lib/brand'
import type { Lesson } from './types'

const galileanMoons: Lesson = {
  id: 'astr-101-1-3-2',
  title: `Jupiter\'s Galilean Moons: Io, Europa, Ganymede, and Callisto`,
  track: 'ast',
  trackName: 'Planetary Science',
  level: 'Beginner',
  duration: '13 min',
  xpReward: 140,
  description: `The four large moons Galileo discovered in 1610 — a volcanically hyperactive world, a hidden global ocean, the Solar System\'s largest moon with its own magnetic field, and a geologically frozen relic — each shaped by where it sits in Jupiter\'s tidal grip.`,
  sources: [
    { org: 'NASA', title: 'NASA Galileo Legacy Mission', url: 'https://solarsystem.nasa.gov/missions/galileo/overview/' },
    { org: 'NASA', title: 'NASA Europa Clipper Mission', url: 'https://science.nasa.gov/mission/europa-clipper' },
    { org: 'NASA', title: `NASA Solar System Exploration — Jupiter\'s Moons`, url: 'https://solarsystem.nasa.gov/moons/jupiter-moons/overview/' },
    { org: 'OpenStax', title: 'Astronomy 2e — Satellites of Jupiter and Saturn (CC-BY 4.0)', url: 'https://openstax.org/books/astronomy-2e/pages/12-1-the-galilean-moons-of-jupiter' },
    { org: 'ESA', title: 'ESA JUICE Mission — Jupiter Icy Moons Explorer', url: 'https://www.esa.int/Science_Exploration/Space_Science/Juice' },
  ],
  sections: [
    {
      type: 'intro',
      title: 'Four worlds that changed everything',
      body: `In January 1610, Galileo Galilei trained his telescope on Jupiter over four consecutive nights and watched four small points of light shift position in ways that could only be explained by one thing: they were orbiting Jupiter, not Earth. The discovery of Io, Europa, Ganymede, and Callisto — now known collectively as the Galilean moons — was the first direct observational proof that not everything in the cosmos revolves around Earth, providing crucial empirical support for the Copernican heliocentric model. Four centuries later, spacecraft have shown these four worlds to be among the most scientifically extraordinary objects in the Solar System.

The Galilean moons display a striking outward density gradient that mirrors their formation environment. Io (mean density 3,528 kg/m³) is a rocky, ice-free world smothered in active volcanoes. Europa (2,989 kg/m³) is encased in a water-ice shell overlying a global saltwater ocean. Ganymede (1,936 kg/m³) is a large icy moon that is — remarkably — the only moon in the Solar System with its own internally generated magnetic field. Callisto (1,851 kg/m³) is a heavily cratered, ancient, apparently undifferentiated body that tells us as much by its inactivity as the others tell us by their dynamism. This density gradient reflects a radial heating gradient: the inner moons are subject to far stronger gravitational tides from Jupiter, which generate heat through tidal flexing.

The mechanism that powers the inner moons is the Laplace resonance: the orbital periods of Io, Europa, and Ganymede are locked in a precise 1:2:4 ratio. Every time Ganymede completes one orbit, Europa completes exactly two, and Io completes exactly four. This resonance prevents the orbits from circularising — instead, it continually forces each moon\'s orbit to remain slightly elliptical. Because Jupiter\'s gravitational pull on an elliptical orbit varies with distance, each moon is rhythmically squeezed and released like a rubber ball. The friction from this tidal flexing generates enormous heat: Io alone radiates approximately 100 TW of tidal heat — more than double Earth\'s entire internal heat output of ~47 TW — making it the most volcanically active body in the Solar System. Europa receives less tidal heating but enough to maintain a liquid ocean. All four moons are tidally locked to Jupiter, permanently presenting the same face toward the planet, just as our Moon always shows the same face toward Earth.`,
      keyTerms: [
        {
          term: 'Tidal heating',
          def: `The generation of heat within a moon or planet through the periodic deformation caused by a varying gravitational field. When a moon orbits in a non-circular (elliptical) orbit, its distance from the parent planet changes continuously; the planet\'s gravitational pull therefore varies in strength and direction throughout each orbit, causing the moon\'s solid body to flex. This periodic flexing is resisted by friction in the rock or ice, converting mechanical energy into heat. The power generated scales steeply with orbital eccentricity and inversely with the orbital period and the rigidity of the body. Tidal heating is the dominant energy source for Io (~100 TW) and a critical heat source for Europa and Ganymede, and operates wherever orbital resonances prevent eccentricity from being damped to zero.`,
        },
        {
          term: 'Laplace resonance',
          def: `A three-body orbital mean-motion resonance in which the orbital periods of Io, Europa, and Ganymede are in the exact ratio 1:2:4, maintained by mutual gravitational interactions between the three moons. Named for Pierre-Simon Laplace, who analysed it mathematically in the 1780s. The resonance is self-sustaining: any tendency for one moon\'s orbit to circularise (and thus reduce tidal heating and eccentricity) is countered by gravitational kicks from the other resonant moons, which re-excite the eccentricity. The practical consequence is that Io\'s orbital eccentricity (~0.0041) and Europa\'s (~0.0094) are maintained indefinitely despite tidal dissipation, ensuring continuous tidal heating of both worlds. The resonance is sometimes written as the Laplace relation: the mean longitudes satisfy λ_Io − 3λ_Europa + 2λ_Ganymede = 180°.`,
        },
        {
          term: 'Cryovolcanism',
          def: `Volcanic activity in which the erupted material is a volatile-rich fluid — typically water, ammonia, methane, or brine — rather than silicate lava. On icy moons, tidal or radiogenic heating can melt ice or brine in subsurface reservoirs; if the pressure is sufficient, this material erupts through fractures or vents to the surface. Cryovolcanism is distinct from classical (silicate) volcanism but serves the same geological function: resurfacing and releasing internal heat. Active cryovolcanic plumes have been confirmed on Saturn\'s moon Enceladus (by the Cassini spacecraft) and are suspected on Europa (Hubble Space Telescope detected possible water-vapour plumes in 2012–2013, though not yet definitively confirmed). Cryovolcanism on icy moons is a key mechanism for transporting subsurface ocean material — potentially including organic molecules or biosignatures — to the surface where spacecraft could sample it.`,
        },
        {
          term: 'Europa\'s subsurface ocean',
          def: `A global layer of liquid saltwater beneath Europa\'s water-ice shell, estimated to be approximately 100 km deep with a total volume roughly twice that of all of Earth\'s oceans combined. Evidence comes from multiple independent lines: (1) NASA\'s Galileo spacecraft detected a time-variable induced magnetic field at Europa, which requires an electrically conductive layer — interpreted as a salty ocean — to explain; (2) Europa\'s surface is covered in chaos terrain (blocks of older ice rafted into new positions), lineae (long linear fractures from tidal stresses), and possible cryovolcanic features, all indicating an ice shell that is not rigidly frozen throughout; (3) Hubble Space Telescope observations in 2012–2013 detected possible water-vapour plumes above the south polar region. The ocean is maintained against freezing by tidal heating from the Laplace resonance. Because the ocean floor is likely rocky and may host hydrothermal vents, Europa is considered the top priority in the search for extraterrestrial life within our Solar System.`,
        },
        {
          term: 'Ganymede\'s magnetic field',
          def: `An internally generated (intrinsic) magnetic dipole field surrounding Ganymede, making it the only moon in the Solar System known to possess its own active dynamo. Discovered by the Galileo spacecraft in 1996 using its magnetometer instrument. The field is oriented nearly parallel to Jupiter\'s magnetic field and has a surface strength of approximately 720 nT at the equator — roughly 1% as strong as Earth\'s field. The field is generated by convection of liquid iron in Ganymede\'s differentiated iron core, analogous to Earth\'s geodynamo, and creates a small magnetosphere embedded within Jupiter\'s vast magnetosphere. Galileo also detected an induced magnetic field at Ganymede in addition to the intrinsic one — implying that an electrically conductive layer (a subsurface saline ocean between ice layers) is present, meaning Ganymede has both an intrinsic dynamo field and an ocean-generated induced field simultaneously.`,
        },
      ],
    },
    {
      type: 'concept',
      title: 'Four worlds, four destinies: volcanism, oceans, magnetism, and ancient ice',
      body: `**Io: tidal heating taken to its logical extreme.** Io is a world unlike any other in the Solar System. Its surface is resurfaced at a rate of approximately 10 cm per year by volcanic deposition — so fast that there are effectively no impact craters: every crater that forms is buried by lava flows and sulfurous deposits before it can be preserved in the geological record. The first direct evidence of active volcanism came from Voyager 1 in 1979, when engineer Linda Morabito noticed a crescent-shaped plume rising 300 km above the limb in a navigation image — the first active volcano ever discovered beyond Earth. The NASA Galileo spacecraft (1995–2003) followed up with detailed compositional measurements, confirming Io\'s surface chemistry: SO₂ frost (yellow-white), elemental sulfur (red-orange), and silicate lava flows (black and grey). Pele, one of Io\'s largest volcanic centres, drives sulfur plumes rising up to 300 km, creating a distinctive red ring of sulfur droplets around the vent. The Galileo NIMS (Near Infrared Mapping Spectrometer) measured hot-spot temperatures reaching 1,600°C — hotter than any measured terrestrial volcanic eruption, implying that Io\'s lavas may be ultramafic (iron- and magnesium-rich komatiitic compositions similar to those erupted on early Earth). Mountains on Io reach impressive heights: Boösaule Montes stands approximately 18,500 m — taller than Mount Everest — but these mountains are not volcanic constructs; they are formed by compressional tectonics as the volcanic crust is thickened and buckled. The continuous resurfacing by ~10 cm/yr of volcanic material means Io is effectively renewing itself on a timescale of millions of years.

**Europa: the case for a habitable ocean world.** Europa\'s surface is the smoothest in the Solar System — a global expanse of water ice with very few impact craters, indicating a young surface of at most a few tens of millions of years. The ice is not static. Galileo imagery revealed chaos terrain: regions where older surface ice appears to have broken up into polygonal blocks (reminiscent of Arctic sea ice) that have been rafted apart, rotated, and refrozen in new configurations — a process that requires underlying warm ice or liquid water to enable ice block mobility. Long linear features called lineae crosscut the surface at all orientations: these are tidal stress fractures opened and closed repeatedly as Europa\'s slightly elliptical orbit brings it alternately closer to and farther from Jupiter, creating periodic tidal flexing. The key astrobiology evidence is Galileo\'s magnetometric detection of an induced magnetic field at Europa. Jupiter rotates every 10 hours, and its tilted magnetic dipole sweeps through Europa like a varying external field; a conductor in this varying field will have currents induced in it. The induction signal at Europa requires an electrically conductive layer very close to the surface — dry ice cannot conduct electricity, but salty liquid water can. Models require a conducting layer at least a few kilometres thick and with the electrical conductivity of a dilute salt solution, consistent with a global ocean directly beneath the ice shell. The ocean itself is estimated at ~100 km depth, with a rocky seafloor that could plausibly host hydrothermal vents — an environment analogous to Earth\'s mid-ocean ridge hydrothermal systems, which support thriving chemosynthetic ecosystems without sunlight. NASA\'s Europa Clipper spacecraft, launched in October 2024, will perform approximately 50 close flybys of Europa beginning in 2030, measuring the moon\'s gravitational field, magnetic induction signal, surface composition, and searching for active plume activity.

**Ganymede and Callisto: a tale of two outcomes from similar starting materials.** Ganymede is the Solar System\'s largest moon: at 5,268 km in diameter it exceeds the planet Mercury in size (though not in mass). It is a fully differentiated world — an iron core, a silicate mantle, a thick ice shell, and a probable subsurface ocean sandwiched between layers of ice. The Galileo spacecraft discovered Ganymede\'s intrinsic magnetic field in 1996, the only moon in the Solar System with one. The field is generated by convective fluid motion in Ganymede\'s liquid iron core and produces a small but distinct magnetosphere embedded within Jupiter\'s enormous one, observable as bright auroral ovals in Hubble ultraviolet images. The same Galileo magnetometry that found the intrinsic field also detected an induced component — evidence for a subsurface salty ocean in addition to the active dynamo. ESA\'s JUICE (Jupiter Icy Moons Explorer) spacecraft, launched in April 2023, will arrive at the Jupiter system in 2031 and ultimately enter orbit around Ganymede — the first spacecraft to orbit any moon other than our own. Callisto, in stark contrast, tells the story of what happens in the absence of tidal heating. Despite being nearly the same size and bulk composition as Ganymede, Callisto is completely undifferentiated: its interior is a homogeneous mixture of rock and ice that never separated into distinct layers. Its surface is the most heavily cratered of any solid body in the Solar System — an ancient ice-and-rock landscape dating back to the Late Heavy Bombardment ~4 billion years ago, with essentially no geological activity since. Callisto does show a weak induced magnetic field signal, suggesting a thin salty ocean layer may exist, but it is geologically dead compared to its resonant siblings. The Ganymede–Callisto contrast — two similarly sized, similarly composed worlds that ended up radically different — is the clearest demonstration in the Solar System of how orbital position and tidal heating history determine planetary evolution.`,
      cards: [
        {
          name: 'Io — The Most Volcanically Active Body in the Solar System',
          icon: Flame,
          color: BRAND.ruby,
          desc: `400+ active volcanoes; no impact craters (resurfaced at ~10 cm/yr by volcanic deposition). Pele volcano: sulfur plumes 300 km high. Surface chemistry: SO₂ frost (yellow-white), elemental sulfur (red-orange), silicate lava flows (black). Tidal heating mechanism: Laplace resonance forces orbital eccentricity; Jupiter\'s gravity varies with orbital distance → periodic tidal flexing → frictional heat → ~100 TW total heat output (compare: Earth interior ~47 TW). Galileo NIMS measured hot-spot temperatures up to 1,600 °C — hotter than any known terrestrial volcanic eruption; implies ultramafic (komatiitic) lava compositions. Boösaule Montes: ~18,500 m tall compressional mountain, exceeding Everest, formed by crustal thickening not volcanism. Voyager 1 (1979): first discovery of active extraterrestrial volcanism. No magnetic field intrinsic to Io (but induced field detected — possible magma ocean).`,
          examples: `Pele: sustained sulfur plume 300 km altitude; red SO₂ ring ~1,200 km in diameter · Tvashtar: captured by New Horizons (2007) in visible-light movie; 330 km tall lava curtain · NIMS hot spots: 14 eruption sites exceeding 700 °C; Pillan Patera reached >1,600 °C · Io plasma torus: volcanic SO₂ is ionised by Jupiter\'s radiation belts, forming a donut-shaped plasma torus along Io\'s orbit that pumps ~1 tonne/sec of sulfur and oxygen ions into Jupiter\'s magnetosphere`,
        },
        {
          name: 'Europa — Beneath the Ice',
          icon: Waves,
          color: BRAND.accent,
          desc: `Water ice shell ~10–30 km thick over global saltwater ocean ~100 km deep (total volume ~2× Earth\'s oceans). Evidence for ocean: (1) Galileo induced magnetic field — requires electrically conductive salty liquid below; (2) chaos terrain — ice blocks rafted in new positions, require mobile substrate; (3) lineae — tidal stress fractures indicating dynamic ice shell; (4) Hubble water-vapour plumes 2012–2013 (not unambiguously confirmed). Surface temperature: ~−160 °C at equator. High albedo (~0.67) keeps surface cold. Ocean maintained by Laplace resonance tidal heating — less than Io but enough to prevent freezing. Rocky seafloor plausible from gravity and magnetic data → potential hydrothermal vents → energy source for chemosynthetic life. Europa Clipper (NASA, launched October 2024): ~50 flybys beginning 2030; will measure induced field, surface composition, gravity, and hunt for plumes.`,
          examples: `Conamara Chaos: textbook chaos terrain — ice blocks 10–20 km across rafted apart and refrozen; older surface disrupted from below by warm ice or liquid · Lineae: tidal crack network following predicted stress patterns from Jupiter\'s varying tidal pull; Galileo mapped >100 major lineae · Galileo induced field: amplitude ~250 nT, phased with Jupiter\'s rotation period (9.9 hr) — requires conducting layer within ~100 km of surface, conductivity consistent with ~0.1 M NaCl solution · Hubble 2013 plume: ~200 km altitude water-vapour feature near Europa\'s south pole; detection not reproduced in all subsequent observations`,
        },
        {
          name: 'Ganymede and Callisto — Icy Worlds Apart',
          icon: Globe,
          color: BRAND.amethyst,
          desc: `Ganymede: largest moon in Solar System (5,268 km — larger than Mercury); fully differentiated (iron core, silicate mantle, ice shell + ocean); ONLY moon with intrinsic magnetic field (~720 nT equatorial; ~1% of Earth\'s) generated by iron core dynamo — confirmed 1996 by Galileo magnetometer; also has induced field component implying salty subsurface ocean; Hubble UV auroral ovals confirm active magnetosphere. JUICE (ESA, launched 2023) will orbit Ganymede from 2034. Callisto: 4,821 km diameter; undifferentiated (rock-ice mix throughout); most heavily cratered body in Solar System; geologically dead; slight induced magnetic field suggests thin salty ocean possible; outside Laplace resonance entirely → no significant tidal heating → interior too cold to differentiate. Ganymede–Callisto contrast: same size, same bulk composition, radically different interiors — demonstrates that orbital position in the resonance (and resulting tidal heating) is the dominant factor in internal evolution.`,
          examples: `Ganymede magnetic field: Galileo flybys 1996–1997; field oriented ~176° to Jupiter\'s dipole axis; 1,300 km magnetosphere radius; auroral footprint mapped by Hubble · Ganymede Hubble aurorae (2015): rocking of aurora ovals with Jupiter\'s field period constrains ocean thickness to ~100 km and salinity to ~3–6% MgSO₄ · Callisto cratering: Valhalla multi-ring impact basin 3,800 km total diameter — one of largest impact structures in Solar System; surface ~4 Ga; no resurfacing · Callisto induced field: ~150 nT amplitude; weaker than Europa\'s; consistent with thin ocean or electrically conducting layer`,
        },
      ],
    },
    {
      type: 'visualization',
      title: 'Tidal energy flow through the Galilean moon system',
      body: `Jupiter\'s gravitational field is the engine that drives the entire Galilean moon system. The Laplace resonance converts Jupiter\'s gravity into orbital eccentricity, orbital eccentricity into tidal flexing, and tidal flexing into heat — heat that manifests differently in each moon depending on its distance from Jupiter. Follow the energy pathway from Jupiter\'s gravity through each moon and see how the same tidal mechanism produces an active volcano world, a habitable ocean world, a magnetised ice giant, and a geologically dead relic.`,
      interaction: {
        type: 'flow-simulator' as const,
        description: `The tidal energy pathway through Jupiter\'s Galilean moon system, from gravitational forcing through the Laplace resonance to the diverse geological outcomes on each moon`,
        nodes: [
          {
            id: 'jupiter',
            label: `Jupiter\'s Gravity`,
            description: `Jupiter\'s immense mass (318× Earth\'s) generates an extremely strong and rapidly varying gravitational field. Its 9.9-hour rotation rate means its slightly non-spherical mass distribution sweeps a varying field past each moon repeatedly. This is the ultimate energy source for all tidal heating in the system.`,
            color: BRAND.gold,
          },
          {
            id: 'resonance',
            label: 'Laplace Resonance (1:2:4)',
            description: 'Mutual gravitational interactions between Io, Europa, and Ganymede lock their orbital periods in the ratio 1:2:4. The resonance prevents tidal dissipation from circularising the orbits — instead it continuously pumps eccentricity back in, sustaining permanently elliptical orbits. Callisto lies outside the resonance and receives no such forcing.',
            color: BRAND.amethyst,
          },
          {
            id: 'io',
            label: 'Io — Tidal Heating 100 TW → Volcanism',
            description: `Io\'s orbital eccentricity (~0.0041), maintained by the resonance, causes tidal flexing of its rocky interior at the ~1.77-day orbital period. Friction converts ~100 TW of mechanical energy to heat — more than twice Earth\'s interior heat output. The result is 400+ active volcanoes, no impact craters, hot-spot temperatures up to 1,600 °C, and sulfur plumes rising 300 km.`,
            color: BRAND.ruby,
          },
          {
            id: 'plasma_torus',
            label: 'Io Plasma Torus',
            description: `Io\'s volcanic emissions of SO₂ are ionised by Jupiter\'s intense radiation belts, creating a donut-shaped torus of sulfur and oxygen plasma along Io\'s orbit. The torus pumps ~1 tonne/second of ions into Jupiter\'s magnetosphere and is the dominant source of mass in Jupiter\'s magnetospheric plasma system.`,
            color: BRAND.ruby,
          },
          {
            id: 'europa',
            label: 'Europa — Tidal Heating → Subsurface Ocean → Habitability',
            description: `Europa\'s eccentricity (~0.0094) drives moderate tidal heating — less than Io\'s but sufficient to maintain a global liquid-water ocean ~100 km deep beneath a 10–30 km ice shell. Galileo\'s induced magnetic field detection and chaos terrain confirm the ocean. A rocky seafloor with potential hydrothermal vents makes Europa the highest-priority target for the search for extraterrestrial life.`,
            color: BRAND.accent,
          },
          {
            id: 'ganymede',
            label: 'Ganymede — Moderate Tidal + Radiogenic Heating → Ocean + Magnetic Field',
            description: 'Ganymede is at the outer edge of the Laplace resonance and receives moderate tidal heating — enough to power early differentiation into an iron core, silicate mantle, and ice layers. The iron core remains partially molten and generates the only known intrinsic lunar magnetic field. An additional induced field signal implies a subsurface saline ocean.',
            color: BRAND.amethyst,
          },
          {
            id: 'callisto',
            label: 'Callisto — No Tidal Heating → Geologically Dead, Ancient Surface',
            description: 'Callisto orbits outside the Laplace resonance and has received no significant tidal heating. With only slow radiogenic decay warming its interior, its ice-rock mixture never reached melting temperatures, and the body never differentiated. Its ancient, cratered surface records ~4 billion years of Solar System bombardment history with no geological overprinting.',
            color: BRAND.jade,
          },
        ],
        edges: [
          { from: 'jupiter',   to: 'resonance',    label: 'gravitational interactions maintain 1:2:4 orbital period lock' },
          { from: 'resonance', to: 'io',            label: 'eccentricity forcing → tidal flexing → 100 TW frictional heat' },
          { from: 'io',        to: 'plasma_torus',  label: 'volcanic SO₂ ionised by radiation belts → magnetospheric plasma' },
          { from: 'resonance', to: 'europa',        label: 'moderate eccentricity → tidal heating → ocean maintained' },
          { from: 'resonance', to: 'ganymede',      label: 'outer resonance member → moderate early heating → differentiation' },
          { from: 'jupiter',   to: 'callisto',      label: 'no resonance → no tidal forcing → radiogenic heating only' },
          { from: 'ganymede',  to: 'callisto',      label: 'same size/composition — divergent outcomes from tidal heating difference' },
        ],
      },
    },
    {
      type: 'quiz',
      questions: [
        {
          q: `Io is roughly the same size and mass as Earth\'s Moon, yet the Moon is geologically dead while Io is the most volcanically active body in the Solar System. What is the fundamental physical mechanism responsible for this difference, and why does it operate on Io but not on the Moon?`,
          a: [
            'Io is heated by tidal flexing driven by the Laplace resonance: its orbital period is locked in a 1:2:4 resonance with Europa and Ganymede, which continuously maintains its orbital eccentricity (~0.0041); the resulting variation in Jupiter\'s gravitational pull as Io moves closer and farther in each orbit causes Io\'s solid body to flex by ~100 m, generating ~100 TW of frictional heat; the Moon has no comparable orbital resonance and its orbit is nearly circular, so tidal dissipation is negligible and it is geologically dead',
            'Io is heated by radioactive decay of uranium, thorium, and potassium in its rocky interior; its higher density (~3,528 kg/m³ vs. the Moon\'s ~3,346 kg/m³) reflects a higher concentration of radioactive elements; the Moon has a lower radiogenic heat budget because it formed from Earth\'s mantle material, which had already lost much of its heat-producing isotopes to the core',
            'Jupiter\'s intense radiation belts continuously bombard Io\'s surface with high-energy charged particles, heating the surface and interior through radiation energy deposition; the Moon orbits Earth, whose radiation environment is far weaker, so the Moon receives insufficient radiative energy to power geological activity',
            'Io is actively accreting material from Jupiter\'s rings and the Io plasma torus, releasing gravitational potential energy as infalling debris strikes the surface; the Moon is not accreting significant material, so it lacks this continuous heat source',
          ],
          correct: 0,
          explain: `Option A correctly identifies the mechanism. The key distinction between Io and the Moon is orbital eccentricity maintained by resonance. All solid bodies experience tidal heating when they orbit a massive body on an eccentric orbit — the tidal dissipation rate scales as (e²/Q), where e is orbital eccentricity and Q is the tidal quality factor (rigidity). Io\'s eccentricity of ~0.0041 seems small, but it is continuously forced by the Laplace resonance: every time Ganymede completes one orbit, Europa completes two, and Io completes four; this 1:2:4 commensurability means the three moons repeatedly apply gravitational kicks to each other at the same orbital phases, pumping eccentricity back up as fast as tidal dissipation tries to damp it. The Moon\'s situation is different in two critical ways: (1) the Moon has essentially zero orbital eccentricity (~0.055, and decreasing), because there is no resonance with any massive body to maintain it; tidal dissipation has nearly circularised the Moon\'s orbit over 4.5 billion years; (2) Earth is far less massive than Jupiter, so even at the same eccentricity the tidal force gradient — and hence the heating — would be far smaller. Option B is factually wrong: Io\'s radiogenic heating budget is comparable to the Moon\'s or Earth\'s, far too small (~10¹² W) to account for the ~10¹⁴ W (100 TW) of observed heat flow; density reflects iron content, not radiogenic element concentration. Option C is incorrect: radiation bombardment heats only the outermost skin of the surface and contributes negligibly to interior heating or volcanism. Option D has no physical basis: the accretion rate of plasma torus material onto Io\'s surface is negligible in energy terms compared to tidal heating.`,
        },
        {
          q: `The Galileo spacecraft detected an induced magnetic field at Europa. Explain the difference between an induced magnetic field and an intrinsic (dynamo) magnetic field, and describe specifically what the detection of an induced field at Europa proves about Europa\'s interior — and what remains uncertain.`,
          a: [
            'An intrinsic field is generated by convective motion of electrically conductive fluid in a moon\'s interior (a dynamo); an induced field is generated by electrical currents that an external time-varying magnetic field drives through a conductive layer inside the moon. At Europa, Jupiter\'s rotating, tilted magnetic dipole creates a varying external field at Europa\'s location; the detection of a field at Europa that oscillates in phase with Jupiter\'s 9.9-hour rotation period proves that a highly electrically conductive layer exists close to Europa\'s surface — dry ice cannot produce this signal, but a global salty liquid-water ocean can. What remains uncertain is the exact thickness, depth, and salinity of the ocean, and whether hydrothermal activity is occurring on its floor.',
            'An intrinsic field is any magnetic field detected at a moon\'s surface; an induced field is a field generated inside the moon by heat-driven convection; the detection at Europa proves the interior is warm enough to sustain fluid motion in its rocky core, confirming geothermal activity at the seafloor; uncertainty remains about whether the convecting layer is liquid water or molten silicate rock.',
            'An induced field and an intrinsic field are physically identical — the distinction is only observational: intrinsic fields are steady in strength and direction, while induced fields oscillate; the oscillation at Europa\'s rotation period proves Europa itself is spinning faster than it appears from the surface, creating an internal dynamo from differential rotation between ice layers; the ocean is inferred as the lubricating layer between these counter-rotating shells.',
            'An induced magnetic field at Europa is generated by the continuous solar wind interaction with Europa\'s thin exosphere; an intrinsic field would require a metallic core; the Galileo detection proves Europa has a substantial exosphere with sufficient ion density to deflect Jupiter\'s magnetospheric plasma, but tells us nothing about Europa\'s interior liquid state.',
          ],
          correct: 0,
          explain: `Option A correctly describes the physics of magnetic induction. Jupiter\'s magnetic dipole axis is tilted ~10° from its rotation axis; as Jupiter rotates every 9.9 hours, this tilted dipole sweeps past each Galilean moon, alternately increasing and decreasing the local magnetic field strength. Faraday\'s law of electromagnetic induction states that a time-varying magnetic flux through a conducting loop induces an electromotive force and, if the loop has finite resistance, an electrical current — which in turn generates its own magnetic field (the induced field). For this to work, the conductor must be extensive (global), close to the surface, and have sufficient electrical conductivity. Dry water ice (resistivity ~10¹⁵ Ω·m) is an essentially perfect insulator and cannot carry the required currents. Liquid saltwater (resistivity ~0.2–2 Ω·m, depending on salinity) conducts readily and is the only plausible material that fits the Galileo induction observations at Europa. The signal phase locks precisely to Jupiter\'s rotation period (not Europa\'s orbital period), which is the key diagnostic. Galileo also detected induced fields at Callisto and Ganymede — suggesting oceans at both — and Ganymede additionally has an intrinsic dynamo field, making its magnetic environment the most complex of the four. What remains uncertain at Europa includes: ice shell thickness (10–30 km range, poorly constrained), ocean salinity and pH, seafloor geology, and whether liquid water ever reaches the surface as cryovolcanic plumes. Option B conflates the induction mechanism with thermal convection, which is incorrect physics. Option C describes a non-existent differential-rotation dynamo mechanism. Option D incorrectly attributes the induction signal to exospheric plasma interactions, which have a different signature and strength.`,
        },
        {
          q: `Ganymede is the only moon in the Solar System with its own intrinsic magnetic field. What internal structure does this require, and why does Earth\'s Moon — despite being a large rocky body that also orbits a planet — lack a comparable magnetic field today?`,
          a: [
            'Ganymede\'s intrinsic field requires an active iron-core dynamo: convective motion of liquid iron in a differentiated iron core generates the field via magnetohydrodynamic (MHD) processes, analogous to Earth\'s geodynamo. Ganymede\'s iron core is partially molten — maintained by a combination of residual primordial heat and moderate tidal heating from its position in the Laplace resonance — sustaining active convection. The Moon has a small iron core (~20% of its radius) but it is essentially fully solidified, eliminating convective motion and shutting down the dynamo; the Moon\'s orbit also has very low eccentricity (no resonance to maintain tidal heating), so no tidal energy supplement is available to keep the core partially molten.',
            'Ganymede\'s field arises from permanent ferromagnetic magnetisation of iron minerals in its rocky mantle, acquired when Ganymede cooled through the Curie temperature early in Solar System history; the Moon has an equivalent ferromagnetic remanence but it is oriented randomly due to impacts, preventing a net dipole field from emerging; impact demagnetisation is the primary reason the Moon lacks a global field today.',
            'Ganymede\'s field is generated by convection in its subsurface salty ocean, not by a metallic core; the rotating salty ocean acts as a natural MHD generator, and Ganymede\'s rapid spin relative to Jupiter\'s magnetic field drives this ocean dynamo; the Moon has no subsurface ocean and therefore cannot generate this type of field.',
            'Ganymede\'s intrinsic field is inherited from Jupiter\'s field: because Ganymede orbits within Jupiter\'s magnetosphere, Jupiter\'s field permanently magnetises Ganymede\'s interior over billions of years; the Moon is magnetised by Earth\'s field in the same way but at a much lower level because Earth\'s field is weaker than Jupiter\'s by orders of magnitude.',
          ],
          correct: 0,
          explain: `Option A accurately describes the physics of planetary dynamos and the reasons for the Moon\'s absence of a field. A self-sustaining magnetic dynamo requires three conditions: (1) a sufficiently large volume of electrically conductive fluid; (2) convective motion within that fluid; (3) rotation to organise the convection into a coherent dynamo. Ganymede satisfies all three: its internal differentiation (enabled by early tidal heating and radiogenic decay) produced a metallic iron core, portions of which remain liquid today — the liquid fraction maintained by residual heat and the mild tidal pumping Ganymede receives as the outer member of the Laplace resonance. The liquid iron core has sufficient electrical conductivity (~10⁶ S/m), convects due to temperature and compositional buoyancy (as the inner core slowly freezes out), and Ganymede rotates (synchronously with its orbital period of ~7.15 days). The Moon\'s situation differs critically: its iron core has a radius of only ~240–300 km (about 20% of the Moon\'s radius), and paleomagnetic evidence from Apollo samples shows the Moon did have a dynamo ~4.2–3.56 Ga ago, but it subsequently shut down — likely because the small core cooled to complete solidification faster than Earth\'s much larger core. Without a liquid core, no convective MHD dynamo can operate. The Moon\'s orbit is also nearly circular (~0.055 eccentricity, and the Moon is not in any tidal resonance), so there is no tidal heating to keep core material molten. Option B describes remanent magnetisation, which is real (Apollo samples are indeed magnetised) but does not produce a global ordered dipole field — remanent magnetisation is fossilised and random, not a coherent ongoing dynamo. Option C incorrectly attributes Ganymede\'s field to ocean convection; ocean-generated induced fields exist at Ganymede, but Galileo\'s magnetometry distinguished this from the dominant intrinsic dynamo field. Option D has no physical basis: external magnetisation (induction) does not produce permanent ferromagnetic memory in liquid metal cores at dynamo temperatures, which are far above Curie temperatures for iron.`,
        },
        {
          q: `Europa\'s surface displays distinctive "chaos terrain" — regions where older, rafted blocks of ice appear to have broken apart, moved, and refrozen in new positions. What process creates this geology, and what does it imply about the state of Europa\'s ice shell?`,
          a: [
            'Chaos terrain forms when warm, buoyant ice or liquid water rises from below, disrupts and melts through the overlying ice shell, and allows older surface blocks to float apart on a temporarily mobile substrate before refreezing in new positions; the process is driven by tidal heating, which produces warm-ice diapirs (analogous to terrestrial salt diapirs) or direct melt pockets rising from the ocean below; chaos terrain proves the ice shell is not statically frozen throughout — it is thermally active and overturning on geological timescales, meaning the surface is geologically young and the ice-ocean interface is dynamic.',
            'Chaos terrain is created by large meteorite impacts that partially melt the ice shell, producing liquid water pools that briefly exist at the surface before refreezing; the blocks are ejecta from the impact that settled into the melt pool and were frozen in place; the distribution of chaos terrain therefore maps the impact history of Europa over the last ~50 million years.',
            'Chaos terrain forms exclusively at the antipodal points of large impacts elsewhere on Europa\'s surface: focused seismic energy from distant impacts converges at the antipode and shatters the ice from within; the mechanism is identical to Mercury\'s "weird terrain" at the Caloris Basin antipode, and the block pattern reflects the seismic wavelengths involved.',
            'Chaos terrain is a sublimation-driven process: Europa\'s ice sublimates preferentially at warmer low-latitude regions, reducing ice thickness until the surface fractures under its own weight; the blocks represent thick ice slabs that settled downward as the surrounding ice thinned; this process requires no liquid water and is consistent with a fully frozen ice shell throughout.',
          ],
          correct: 0,
          explain: `Option A correctly identifies the two non-exclusive models for chaos terrain formation, both of which require a thermally active ice shell. The diapir model proposes that buoyant warm ice rises through the ice shell from near the ocean interface, in a manner analogous to salt diapirs rising through sedimentary sequences on Earth or mantle plumes ascending through the lithosphere. Where a warm-ice diapir reaches the base of the brittle surface ice, it can cause partial melting, destabilise the overlying ice, and allow blocks of older surface material to raft laterally before refreezing. The direct through-melting model proposes that in some locations the ice shell is thin enough for oceanic water or warm liquid to directly reach the surface. Both models require the same key constraint: the ice shell cannot be fully solid and rigid at depth — it must be warm and ductile or partially liquid, which requires continuous heat input from tidal dissipation within the ice shell itself. This makes chaos terrain powerful geological evidence for a non-static, thermally active ice shell — and indirectly for the subsurface ocean — because without a heat source to produce warm ice or liquid, the entire shell would freeze rigid and no block mobility would be possible. The young age of Europa\'s surface (~50–80 million years) inferred from the very low crater density is consistent with this ongoing geological activity. Option B (impact origin) is inconsistent with the geographic distribution and morphology of chaos: chaos regions are too numerous, too large, and lack the impact-related morphological features (central peaks, ejecta blankets) that would be expected if they were impact melt pools; Conamara Chaos alone covers ~1,600 km² — far larger than any plausible impact melt zone. Option C (antipodal seismic focusing) is the mechanism for Mercury\'s weird terrain but is not applicable to Europa: seismic focusing requires a very large impact at a specific antipodal location, and chaos terrain is distributed widely across Europa\'s surface at latitudes and longitudes uncorrelated with known large impact structures. Option D (sublimation) cannot create rafted block morphology and is inconsistent with Europa\'s low surface temperatures (~−160 °C) and the block motion evidence.`,
        },
        {
          q: 'Despite being almost identical in size and bulk composition to Ganymede, Callisto is the most heavily cratered solid body in the Solar System and shows no evidence of internal differentiation — its rock and ice remain thoroughly mixed throughout. What explains this stark contrast between the two moons?',
          a: [
            'The Ganymede–Callisto contrast is explained by their positions relative to the Laplace resonance: Ganymede is the outermost resonant member (orbital period ratio 4:2:1 with Europa and Io) and received moderate tidal heating early in Solar System history — sufficient to melt and differentiate its interior into iron core, silicate mantle, and ice layers; Callisto lies completely outside the resonance and received no significant tidal heating; with only slow radiogenic decay as a heat source, Callisto\'s interior temperature never reached the melting point of ice mixed with rock, so differentiation never initiated; its ancient, heavily cratered surface records ~4 billion years of uninterrupted bombardment history because no geological process has ever resurfaced it.',
            'Callisto formed later than Ganymede, after much of the short-lived radioactive isotope ²⁶Al (aluminium-26) had already decayed; ²⁶Al was the dominant early heat source for Solar System bodies; because Callisto accreted later, it had much less ²⁶Al and consequently much less early heating; Ganymede formed earlier and had abundant ²⁶Al heating, which drove its differentiation; tidal heating is negligible for both moons and plays no role in the contrast.',
            'Callisto\'s lack of differentiation is explained by its bulk composition: unlike Ganymede, which accreted from the ice-poor inner part of Jupiter\'s accretion disk and is therefore rock-dominated, Callisto accreted from the ice-rich outer disk and is ice-dominated; ice has much higher viscosity than rock and cannot convect efficiently, preventing the density sorting that drives differentiation; the difference in disk location, not tidal heating, produces the contrast.',
            'Both Ganymede and Callisto were initially differentiated, but Callisto was subsequently re-homogenised by a large impact early in its history — a disruption event ~4 billion years ago mixed the interior and reset the cratering record; the present heavily cratered surface was then acquired over the subsequent 4 billion years; Ganymede avoided such an impact and retained its differentiated structure.',
          ],
          correct: 0,
          explain: `Option A correctly explains what is now considered the leading model for the Ganymede–Callisto dichotomy, a problem that has fascinated planetary scientists since the Galileo mission. The critical observation is that two bodies of essentially identical size (~4,800–5,268 km diameter) and nearly identical uncompressed densities (~1,800 kg/m³) have radically different internal structures. Ganymede is fully differentiated (proved by its moment of inertia factor of ~0.31, close to Earth\'s differentiated value of 0.33, measured by Galileo\'s gravity field) and has an iron core generating a magnetic field. Callisto is remarkably undifferentiated (moment of inertia factor ~0.36, much closer to the homogeneous sphere value of 0.4), with rock and ice mixed throughout. The model proposed by Showman and Malhotra (1997) and subsequently supported by thermal evolution models invokes a tidal heating threshold: if an icy body receives enough tidal heat during its early history, ice melting initiates a runaway differentiation process — liquid water sinks rock downward, releasing gravitational potential energy, which generates more heat, accelerating differentiation. Ganymede\'s position in the Laplace resonance provided this threshold early heating; Callisto\'s position outside the resonance did not. Without the tidal trigger, Callisto\'s solely radiogenic heat was insufficient to raise its interior above the ice melting point at the pressures inside the moon, and differentiation never began. The ancient, pristine cratered surface of Callisto records the Late Heavy Bombardment essentially undisturbed — a unique geological archive. Option B incorrectly prioritises ²⁶Al decay as the key differentiator: both moons formed within the same Jovian sub-nebula on similar timescales (within a few million years of each other), so the ²⁶Al inventory would have been similar; the ²⁶Al hypothesis for the Ganymede–Callisto dichotomy is not supported by formation timeline constraints. Option C is factually wrong: Ganymede and Callisto have similar bulk ice-to-rock ratios (~50–60% rock by mass in both); the compositional explanation is not supported by density data. Option D has no observational support: no large impact structure is known that could have re-homogenised Callisto\'s entire interior, and thermal models show complete re-homogenisation after differentiation would require an implausibly energetic impact.`,
        },
      ],
    },
  ],
}

export default galileanMoons
