import { Telescope, Globe, Wind } from 'lucide-react'
import { BRAND } from '@/lib/brand'
import type { Lesson } from './types'

const mercuryAndVenus: Lesson = {
  id: 'astr-101-1-2-1',
  title: 'Mercury and Venus: Extremes of the Inner Solar System',
  track: 'ast',
  trackName: 'Planetary Science',
  level: 'Beginner',
  duration: '11 min',
  xpReward: 140,
  description: "A comparative study of the two innermost planets — Mercury's iron-rich composition and lobate scarp tectonics, and Venus's runaway greenhouse effect and volcanic resurfacing.",
  sources: [
    { org: 'NASA',     title: 'NASA Solar System Exploration — Mercury',                                                           url: 'https://solarsystem.nasa.gov/planets/mercury/overview/' },
    { org: 'NASA',     title: 'NASA Solar System Exploration — Venus',                                                             url: 'https://solarsystem.nasa.gov/planets/venus/overview/' },
    { org: 'NASA',     title: 'NASA MESSENGER Mission — Mercury Surface, Space Environment, GEochemistry, and Ranging',            url: 'https://messenger.jhuapl.edu/' },
    { org: 'OpenStax', title: 'Astronomy 2e — The Planets: A Brief Survey (CC-BY 4.0)',                                            url: 'https://openstax.org/books/astronomy-2e/pages/7-1-overview-of-our-planetary-system' },
    { org: 'AGI',      title: 'Glossary of Geology — Lobate Scarp, Runaway Greenhouse, Coronae, Retrograde Rotation',             url: 'https://www.americangeosciences.org/' },
  ],
  sections: [
    {
      type: 'intro',
      title: "Two worlds of extremes at the Sun's doorstep",
      body: `Of the four terrestrial planets, Mercury and Venus flank Earth's orbit on the sunward side, yet they could scarcely be more different from each other — or from Earth. Mercury, the smallest planet (radius 2,440 km (1516 mi)), is a geologically frozen, heavily cratered world whose anomalously dense iron interior has puzzled planetary scientists since the Mariner 10 flyby in 1974. It has no meaningful atmosphere, surface temperatures that swing from −180 °C (-292°F) at night to +430 °C (806°F) in the day, and a surface sculpted by billions of years of impacts and one extraordinary bout of global contraction. Venus, slightly smaller than Earth (0.95 R⊕), is cloaked in a thick CO₂ atmosphere at 92 bar — nearly 100× Earth's surface pressure — and roasts at a steady ~465 °C (869°F), hot enough to melt lead, hotter even than Mercury's sun-blasted dayside despite being farther from the Sun.

The extremes of these two planets are not mere curiosities. They bracket Earth in the inner Solar System and define the inner edge of the classical habitable zone. Understanding why Venus became a scorching inferno while Earth remained temperate — and whether Venus was ever habitable — is one of the central problems of comparative planetology. The **runaway greenhouse effect** that transformed Venus is not just an exotic planetary phenomenon; it is a cautionary end-state for any rocky planet that tips too far toward positive water-vapour and CO₂ feedbacks. Mercury, meanwhile, is a laboratory for understanding the early Solar System's violent phase: its enormous iron core preserves information about giant impacts and material sorting in the proto-solar disc.

Both planets have been targets of dedicated spacecraft exploration — Mercury by Mariner 10 (1974–1975), MESSENGER (2011–2015), and the ongoing BepiColombo mission (ESA/JAXA, arrival ~2025), and Venus by the Soviet Venera programme (1961–1984), NASA's Magellan radar mapper (1990–1994), and a coming fleet of 2030s missions (DAVINCI, VERITAS, EnVision). Each spacecraft generation has upended our picture of these worlds and deepened our understanding of what makes a planet habitable — or uninhabitable.`,
      keyTerms: [
        { term: 'Lobate scarp',             def: "A curved, cliff-like thrust fault on Mercury's surface, typically hundreds of kilometres long and up to 3 km (1.9 mi) high. Lobate scarps formed as Mercury's interior cooled and contracted, shrinking the planet's radius by approximately 7 km (4.3 mi). They crosscut craters of all ages, showing they formed throughout Mercury's geological history, not just early on. Hundreds of lobate scarps have been mapped by MESSENGER, making Mercury the only planet known to be actively contracting today (albeit very slowly)." },
        { term: 'Runaway greenhouse effect', def: "A self-reinforcing feedback loop in which rising temperatures cause increased evaporation of water (or other condensable greenhouse gas), which further warms the surface, driving more evaporation until all liquid water is vaporised. On Venus, greater solar insolation ~30% higher than Earth drove early ocean evaporation; water vapour is a powerful greenhouse gas, so warming accelerated; eventually the oceans were entirely lost to space through photodissociation of H₂O and hydrogen escape. Without liquid water, the silicate–carbonate weathering cycle cannot remove volcanic CO₂, which accumulated to 96.5% of the atmosphere at 92 bar." },
        { term: 'D/H ratio',                def: "The ratio of deuterium (²H, or D) to ordinary hydrogen (¹H, or H) in a water-bearing sample. Because deuterium is roughly twice as heavy as protium, it escapes to space at about half the rate of ¹H during hydrogen escape processes. A very high D/H ratio — Venus's is ~150× Earth's — therefore indicates that a large water inventory was gradually lost over geological time via preferential ¹H escape, leaving the remaining water (now as vapour) strongly enriched in deuterium. The Venus D/H ratio is the primary geochemical evidence for an ancient ocean." },
        { term: 'Caloris Basin',            def: "A multi-ring impact basin on Mercury approximately 1,550 km (963 mi) in diameter, among the largest impact structures in the Solar System. It formed ~3.9 billion years ago during the Late Heavy Bombardment when a large asteroid or comet struck Mercury. The enormous shock energy propagated around the entire planet, focusing at the antipodal point and creating a region of chaotic, hummocky terrain called 'weird terrain' directly opposite Caloris. The basin interior has been volcanically resurfaced and is filled with relatively young smooth plains." },
        { term: 'Coronae',                  def: "Oval to circular volcanic-tectonic features on Venus, ranging from ~100 to >2,600 km (1616 mi) in diameter, characterised by concentric fractures, ridges, and radial fracture systems surrounding a central volcanic region. Coronae form where a mantle plume head impinges on the crust from below, causes doming, then subsides, leaving a collapsed structure rimmed by compressional ridges. Over 500 coronae have been identified by Magellan radar data; they have no exact counterpart on Earth and may be the primary mechanism by which Venus loses internal heat in the absence of plate tectonics." },
      ],
      interaction: {
        type: 'scientific-diagram' as const,
        id: 'stellar-hr-diagram',
        caption: 'Hertzsprung–Russell diagram: luminosity vs. effective temperature for all stellar types. Main sequence (90% of stars), giant branch, supergiants, and white dwarfs are labelled with named stars.',
        credit: 'Hertzsprung (1911) · Russell (1914)',
      },
    },
    {
      type: 'concept',
      title: "Mercury's iron enigma, Venus's volcanic world, and a tale of two atmospheres",
      body: `**Mercury: density paradox and giant impact hypothesis.** Mercury presents planetary scientists with a fundamental puzzle: a small planet with a very high mean density. At 5,430 kg/m³, Mercury's bulk density is only slightly less than Earth's (5,515 kg/m³), but Earth's density is partly a result of gravitational self-compression of a large body. When corrected for internal pressure — compared at the same uncompressed density — Mercury is denser than any other planet, implying that its composition is dominated by iron to an extraordinary degree. Models suggest Mercury's core occupies approximately 85% of the planet's radius and roughly 70% of its total mass, compared to Earth's core at about 30% by mass.

Two major hypotheses explain this iron enrichment. The **giant impact hypothesis** proposes that proto-Mercury was struck by a large planetesimal in the early Solar System, stripping away most of the silicate mantle while the dense iron core remained gravitationally bound. This mirrors the proposed mechanism for the Moon's formation but at a more extreme scale — the impactor is estimated to have been roughly 1/6 Mercury's mass. Supporting evidence includes MESSENGER's discovery that Mercury's surface lavas are iron-poor and sulfur-rich, somewhat inconsistent with simple silicate mantle removal but consistent with a heterogeneous proto-Mercury. The alternative **photophoretic sorting** hypothesis suggests that intense early solar radiation preferentially pushed lighter silicate dust particles outward from the innermost proto-solar disc, concentrating refractory iron-rich material near the Sun — meaning Mercury formed iron-enriched from the start. Both hypotheses remain active research topics, and BepiColombo's gravity and compositional measurements are expected to provide sharper constraints.

**Mercury's remarkable surface: scarps, basins, and ice.** Despite its small size, Mercury's surface records a rich geological history spanning 4 billion years. The **Caloris Basin** (1,550 km (963 mi) diameter) dominates the northern hemisphere; its formation sent seismic energy around the planet to create chaotic "weird terrain" at the antipodal point. But the most geologically significant features are Mercury's **lobate scarps** — great thrust fault escarpments hundreds of kilometres long and up to 3 km (1.9 mi) high — that crosscut craters of all sizes and ages, demonstrating they formed throughout Mercury's geological history as the planet's interior slowly cooled and the entire planet contracted by approximately 7 km (4.3 mi) in radius. MESSENGER detected over 300 lobate scarps, and some appear geologically young enough to suggest contraction is ongoing. Paradoxically, permanently shadowed polar craters harbour radar-bright deposits interpreted as water ice, protected from the Sun by crater rims despite Mercury's extreme surface temperatures.

**Venus: greenhouse extreme and volcanic mystery.** Venus sits at the inner edge of the classical habitable zone, receiving ~1.9 times Earth's solar irradiance. Its surface temperature of ~465 °C (869°F) is maintained by one of the most powerful greenhouse effects in the Solar System — a 92-bar CO₂ atmosphere blanketing the surface and trapping outgoing infrared radiation. The mechanism of the runaway greenhouse is well understood theoretically: once insolation exceeds a critical threshold, water vapour feedback drives ocean evaporation to completion. Without liquid water, the silicate-carbonate thermostat (by which CO₂ is drawn down via rock weathering) ceases to function, and volcanic outgassing accumulates CO₂ in the atmosphere indefinitely. Venus's extreme retrograde rotation — one Venusian day of 243 Earth days, longer than its 225-day year — may itself be connected to the massive atmospheric angular momentum of the CO₂ envelope, though the original cause of the retrograde spin remains debated between a giant impact hypothesis and tidal evolution.

**Magellan's radar portrait of Venus and future missions.** Because Venus's atmosphere is perpetually cloudy at visual wavelengths, its surface was not imaged until Magellan's synthetic aperture radar mapped 98% of the planet between 1990 and 1994. The revelation was striking: Venus's surface looks geologically young, with a mean crater retention age of approximately 500–800 million years — far younger than Mercury, the Moon, or Mars. This youth means either a catastrophic planet-wide volcanic resurfacing event occurred ~700 Ma ago, burying all prior craters, or that ongoing distributed volcanism continuously repaves the surface. Magellan revealed vast volcanic plains, giant shield volcanoes (Maat Mons, 8 km (5.0 mi) high), over 500 coronae, and ancient tesserae highlands that may be the oldest surviving terrain. ESA's EnVision, NASA's DAVINCI and VERITAS missions — all targeting the 2030s — aim to measure current volcanic activity, constrain the resurfacing history, and determine whether Venus was ever habitable.`,
      cards: [
        {
          name: 'Mercury: A Shrunken World of Iron and Scarps',
          icon: Globe,
          color: BRAND.amethyst,
          desc: "Mercury (radius 2,440 km (1516 mi); mean density 5,430 kg/m³) has an iron core spanning ~85% of its radius and ~70% of its mass — more iron-dominated than any other planet. The giant impact hypothesis argues a large early impactor stripped the silicate mantle; photophoretic sorting proposes iron enrichment during accretion in the intense inner proto-solar disc. The Caloris Basin (1,550 km (963 mi)) is the dominant impact feature; its antipodal shock created 'weird terrain.' Lobate thrust scarps — hundreds of km long, up to 3 km (1.9 mi) high — document ~7 km (4.3 mi) of global contraction as Mercury cooled. MESSENGER (2011–2015) mapped the entire surface and detected water ice in permanently shadowed polar craters despite equatorial temperatures of +430 °C (806°F). BepiColombo (ESA/JAXA), currently en route, will make gravity field and geochemical measurements that should distinguish core size and composition hypotheses when it arrives ~2025.",
          examples: "Discovery Rupes: ~550 km (342 mi) lobate scarp, one of the largest, crosscutting craters of all ages · Caloris Basin antipodal weird terrain: chaotic hummocky terrain formed by converging seismic waves · MESSENGER MASCS instrument: UV-VIS spectroscopy confirming iron-poor, sulfur-rich surface lavas · Polar ice deposits: radar-bright material in permanently shadowed craters confirmed as water ice by MESSENGER neutron spectrometer",
        },
        {
          name: 'Venus: Runaway Greenhouse and Volcanic Enigma',
          icon: Telescope,
          color: BRAND.amethyst,
          desc: "Venus (0.95 R⊕, 0.81 M⊕) maintains a surface temperature of ~465 °C (869°F) sustained by a 92-bar CO₂ atmosphere (96.5% CO₂, 3.5% N₂) — hotter than Mercury's dayside. The runaway greenhouse mechanism: greater insolation caused early ocean evaporation → H₂O feedback → photodissociation and hydrogen escape → CO₂ accumulation with no liquid water to drive silicate-carbonate drawdown. Venus rotates retrograde: one Venusian day (243 Earth days) exceeds its year (225 days); no global magnetic field. Venera landers (1970–1984) measured surface composition; Magellan radar (1990–1994) mapped 98% of the surface revealing volcanic plains, Maat Mons (8 km (5.0 mi) high), >500 coronae, and tesserae highlands. Surface age ~500–800 Ma implies either catastrophic resurfacing ~700 Ma ago or ongoing episodic volcanism. DAVINCI, VERITAS (NASA) and EnVision (ESA), all targeting the 2030s, will search for active volcanism and ancient habitability signatures.",
          examples: "Magellan SAR imaging: revealed young-looking surface with ~1,000 impact craters total (Earth has thousands more despite similar size) · Venera 9 (1975): first surface images — blocky angular lava slabs implying geologically recent volcanism · Maat Mons: largest Venusian volcano, 8 km (5.0 mi) high, 400 km (249 mi) base, with lava flows extending hundreds of km · Tesserae highlands: heavily deformed terrain potentially preserving ancient crust older than the resurfacing event",
        },
        {
          name: 'Comparative Atmospheres and Habitability History',
          icon: Wind,
          color: BRAND.amethyst,
          desc: "Venus's D/H ratio is ~150× Earth's, indicating preferential ¹H escape left residual water strongly enriched in deuterium — requiring a large initial water inventory consistent with an ancient ocean. Way et al. (2016, 2020) climate models show a slowly rotating Venus with a liquid ocean could have maintained habitable surface temperatures for up to ~3 billion years, before increasing solar luminosity or volcanic CO₂ outgassing tipped it into runaway. Earth's ~33 °C (91°F) greenhouse effect (stable via silicate-carbonate thermostat), Venus's ~500 °C (932°F) greenhouse (runaway completed), and Mars's weak greenhouse (collapsed atmosphere) form a natural trilogy: three rocky planets at different orbital distances with diverging feedback histories. The inner edge of the habitable zone is partly defined by when the H₂O feedback becomes self-sustaining — Venus may have crossed that threshold only within the last 1–3 Gyr, not at formation.",
          examples: "D/H measurement: Venera 11–12 and Pioneer Venus mass spectrometers first detected the enrichment; confirmed by ground-based IR spectroscopy · Way et al. 2016 GRL model: slowly rotating Venus with shallow ocean stable 0–4 Gyr with pre-main-sequence solar luminosity · Mars comparison: Mars D/H ~5× Earth — much less water lost, consistent with a smaller initial inventory · Earth silicate thermostat: volcanic CO₂ balanced by carbonate weathering keeps CO₂ ~280 ppm pre-industrial",
        },
      ],
    },
    {
      type: 'quiz',
      questions: [
        {
          q: "Mercury's mean density (5,430 kg/m³) is nearly as high as Earth's (5,515 kg/m³), yet Mercury is far smaller. Uncompressed, Mercury would be significantly denser than Earth. Which explanation for Mercury's anomalous iron enrichment is most widely supported, and what evidence distinguishes it from competing hypotheses?",
          a: [
            "The giant impact hypothesis is most widely supported: an early large impactor stripped most of Mercury's silicate mantle, leaving a core-dominated remnant; supporting evidence includes the iron-poor, sulfur-rich surface lavas detected by MESSENGER that suggest differentiated mantle removal, and the similarity to the proposed lunar giant impact mechanism; alternative explanations such as photophoretic sorting or extreme nebular evaporation of silicates remain viable but are less directly supported by surface geochemistry",
            "The photophoretic sorting hypothesis is most widely supported: intense early solar radiation pushed lighter silicate particles away from the inner disc, leaving iron-rich material to accrete near the Sun; this explains Mercury's density without requiring a low-probability giant impact; MESSENGER surface data confirming a low-iron surface is fully consistent with this model, making giant impact unnecessary",
            "Mercury's anomalous density is explained by gravitational self-compression: as the innermost planet, Mercury experiences stronger solar tidal forces that continuously compress its interior to higher density; no giant impact or special formation scenario is required",
            "Mercury formed entirely from refractory iron-oxide compounds condensed close to the Sun in the solar nebula; no silicate mantle ever formed; MESSENGER detected no evidence for ancient silicate volcanism, consistent with this iron-oxide accretion scenario",
          ],
          correct: 0,
          explain: "The giant impact hypothesis (answer A) is the leading model for Mercury's iron enrichment, though it is not conclusively proven and competing hypotheses remain active. Photophoretic sorting (B) is a genuine alternative but faces difficulties explaining the full magnitude of the silicate depletion. The gravitational self-compression idea (C) is physically incorrect: tidal forces from the Sun are very weak and could not significantly compress Mercury's interior. Mercury has extensive evidence for ancient volcanic resurfacing, making the pure iron-oxide accretion model (D) factually wrong. The correct answer (A) accurately conveys that the giant impact scenario is preferred because it has analogy with the Moon-forming impact and because surface lavas are iron-poor, consistent with mantle removal — but also correctly notes that photophoretic sorting and nebular evaporation of silicates are active competing explanations.",
        },
        {
          q: "Venus's atmospheric D/H ratio is approximately 150 times higher than Earth's. A student argues: 'This just means Venus's water was delivered by different types of comets or asteroids than Earth's water — comets with naturally higher D/H ratios.' What is wrong with this interpretation, and what does the D/H ratio actually demonstrate about Venus's water history?",
          a: [
            "The student's argument confuses delivery source with fractionation history. Venus's D/H ratio is so extreme — ~150× Earth's — that it cannot be explained by the range of D/H values in known comets and asteroids; the only physical process that can fractionate hydrogen isotopes to this extreme degree is preferential escape of lighter ¹H to space over geological time; because ¹H escapes ~√2 times faster than ²H, the remaining water becomes progressively deuterium-enriched as the ¹H reservoir is depleted; the magnitude of enrichment requires a large initial water inventory consistent with a surface ocean",
            "The student is correct that cometary delivery explains the high D/H ratio; outer Solar System comets have D/H values of 3–30× SMOW, which aggregated over Venus's impact history could account for the 150× enrichment; the D/H ratio is therefore evidence for a different impactor population at Venus's location, not for ancient water loss",
            "The D/H ratio proves Venus never had liquid water: high-D/H environments are anhydrous because deuterium fractionates into dry minerals rather than water; the high D/H ratio in Venus's atmosphere therefore indicates that Venus accreted from water-poor, deuterium-enriched nebular material and never had an ocean",
            "The D/H ratio is only meaningful when combined with total water abundance; since Venus's total atmospheric water vapour content is extremely low (30 ppm), the high D/H ratio simply reflects that a very small amount of cometary water was delivered to an otherwise dry planet; it reveals nothing about ancient oceans",
          ],
          correct: 0,
          explain: "The student's comet-delivery argument (and option B) is physically plausible as a partial contribution but cannot account for the full 150× enrichment. Known cometary D/H values range from ~1× to ~30× Earth's SMOW value; reaching 150× by blending cometary sources is not supported by Solar System delivery models. Option C is scientifically backwards — deuterium does not fractionate into dry minerals in a way that would produce atmospheric enrichment in the described scenario. Option D contains a partially correct point, but analysis of escape rates and the known range of initial D/H values conclusively shows that an initial ocean-scale water inventory is required to produce the observed enrichment. The correct answer (A) explains the physics: hydrogen escape is mass-selective because thermal (Jeans) escape rates scale inversely with atomic mass. Over 4 billion years of UV-driven photodissociation and subsequent H escape, starting from a large water reservoir, produces exactly the extreme D/H enrichment observed.",
        },
        {
          q: "Magellan radar mapping revealed that Venus has approximately 1,000 impact craters with a relatively uniform spatial distribution and a mean surface age of ~500–800 million years. Earth has far more craters per unit area after erosion correction, and Mars has cratered highlands billions of years old. What does Venus's crater record imply about its geological history, and what are the competing interpretations?",
          a: [
            "Venus's young, uniform crater age distribution implies either a catastrophic global volcanic resurfacing event ~700 Ma ago that buried all older craters beneath lava flows (producing the near-random spatial distribution of post-resurfacing craters), or continuous episodic volcanism that statistically erases the crater record at a similar rate across the planet; both interpretations require that Venus loses its surface record on ~500–800 Myr timescales",
            "Venus's young crater age proves its surface is still being continuously reshaped by plate tectonics; the uniform distribution of young craters is the signature of subduction destroying old crust; Venus therefore has active plate tectonics comparable to Earth's but operating at a slower rate",
            "The scarcity of craters proves Venus's thick atmosphere destroys all incoming impactors before they reach the surface; none of the ~1,000 observed craters are real impact structures — they are endogenic features that resemble craters in radar images",
            "Venus's ~1,000 craters match what would be expected for a surface that has never been geologically modified; the young apparent age is an artefact of Magellan radar calibration errors; a correctly calibrated crater count would reveal surface ages of 3–4 Gyr comparable to Mercury's highlands",
          ],
          correct: 0,
          explain: "Option B is factually wrong — Venus shows no evidence of plate tectonics in Magellan data; there are no clear spreading ridges, no chains of arc volcanoes, no evidence of subduction. Option C is partially correct in that Venus's atmosphere does filter small impactors, producing a minimum crater diameter of ~3 km (1.9 mi), but this explains why small craters are absent, not why large craters are sparse and apparently young; Venus's ~1,000 observed craters are confirmed impact structures from crater morphology, ejecta patterns, and central peaks visible in Magellan data. Option D is not supported — Magellan's radar calibration is well-established and independently validated. The correct answer (A) accurately describes the two leading models: the catastrophic resurfacing model invokes a rapid global volcanic episode ~700 Ma ago, while the equilibrium resurfacing model proposes ongoing volcanism that keeps pace with crater production. Upcoming missions VERITAS and EnVision will seek to distinguish between these scenarios.",
        },
      ],
    },
  ],
}

export default mercuryAndVenus
