import { Globe, Layers, Mountain, Activity } from 'lucide-react'
import { BRAND } from '@/lib/brand'
import type { Lesson } from './types'

const stagnantLidTectonics: Lesson = {
  id: 'astr-201-1-3-3',
  title: 'Stagnant Lid Tectonics and Why Earth is Unique',
  track: 'ast',
  trackName: 'Planetary Geology',
  level: 'Intermediate',
  duration: '16 min',
  xpReward: 200,
  description: 'Why Earth is the only confirmed plate tectonic planet — the physical conditions that enable subduction, the stagnant lid regimes of Mars, Venus, Moon, and Mercury, and what comparative planetology reveals about the prerequisites for recycling planetary crusts.',
  sources: [
    { org: 'Nature',  title: 'Byrne et al. (2021) — A globally fragmented and mobile lithosphere on Mercury',                                   url: 'https://doi.org/10.1038/s41561-021-00720-1' },
    { org: 'Nature',  title: 'Smrekar et al. (2010) — Recent Hotspot Volcanism on Venus from VIRTIS Emissivity Data',                          url: 'https://doi.org/10.1126/science.1186785' },
    { org: 'JGR',     title: 'Phillips & Hansen (1998) — Geological observations bearing on the nature of the Venusian mantle',                url: 'https://doi.org/10.1029/98JE01763' },
    { org: 'Science', title: 'Sleep (1994) — Martian plate tectonics — a Noachian episode of plate tectonics',                                url: 'https://doi.org/10.1126/science.265.5173.799' },
  ],
  sections: [
    {
      type: 'intro',
      title: 'Why does only Earth have plate tectonics?',
      body: `Among all the rocky bodies in the solar system — Earth, Venus, Mars, Mercury, the Moon, and the dozens of mid-size moons of the outer planets — only Earth has unambiguous, ongoing plate tectonics. This is a remarkable fact. Earth-mass exoplanets orbiting other stars may be common, but there is no guarantee that any of them exhibit the same surface recycling that on Earth has regulated atmospheric CO2 through the carbonate-silicate cycle, refreshed the nutrients available to life, and prevented the atmospheric runaway that transformed Venus into a hellscape. Understanding why Earth has plate tectonics requires understanding why no other solar system body does — and what that implies about the conditions necessary to sustain a habitable planet over geological time.

**What plate tectonics requires.** The essential process is **subduction**: the descent of one lithospheric plate beneath another back into the mantle, driven by the negative buoyancy of cold, dense oceanic crust. For subduction to initiate and sustain, several physical conditions must be met simultaneously.

First, the subducting plate must be **denser than the underlying mantle** once it is cold. Oceanic crust (basalt, density ~2,900 kg/m³) transforms to eclogite (density ~3,600 kg/m³) under the elevated pressure of subduction, becoming substantially denser than the surrounding mantle peridotite (~3,300 kg/m³). This density inversion is the gravitational engine of subduction — the "slab pull" force that drags the plate down. Continental crust (granodiorite, density ~2,700 kg/m³) is too buoyant to subduct efficiently, which is why continents are not recycled into the mantle and preserve rocks billions of years old.

Second, the plate must be able to **bend and break** rather than resist subduction by viscous resistance. A plate that is too thick (extremely old and cold oceanic lithosphere) may resist bending; a plate that has too high a yield strength may not break where stresses concentrate at the subduction zone hinge. On Venus, the lithosphere may be simply too strong — too thick and too hot — to initiate subduction anywhere, even if a locally dense region existed.

Third, **water** plays a critical role. Water dissolved in the oceanic crust and in the hydrated minerals of the subducting slab is carried to depth, where it is released as the slab heats and minerals dehydrate. This water flux lowers the melting point of the overlying mantle wedge (flux melting), generating the arc magmatism that is the primary factory of new continental crust on Earth. More fundamentally, water trapped in the deep portions of oceanic plates **lowers the effective viscosity of the lithospheric mantle**, making the plate more ductile and less resistant to the bending required for subduction. A dry lithosphere — as on Venus, which lost its water early in its history — is far more rigid and resistant to subduction initiation.

Fourth, **adequate internal heat** is required to sustain the mantle convection that drives plate motion. All rocky planets are cooling over time; a body that cools too fast will develop a thick, immobile lid before plate tectonics can be established or sustained. A body too small (Mars, Moon) loses heat efficiently through conduction and becomes tectonically dead. The question for Mars is whether it ever had a brief episode of something resembling plate tectonics — Sleep (1994) proposed that Mars might have had a single hemisphere of subduction in the Noachian (~4.0–4.5 Ga), which could explain why the northern hemisphere is a low-standing basaltic plain while the southern hemisphere is ancient, heavily cratered highland terrain. This remains debated.

**Mars: the canonical stagnant lid.** Mars is the archetype of a stagnant-lid planet. Its entire surface is essentially one tectonic plate — never subducted, never recycled, just slowly buried under volcanic deposits and meteoritic impact regolith. The consequence of a fixed lithosphere over a fixed mantle hotspot is the extraordinary **Tharsis volcanic province**: a circular volcanic plateau approximately 4,000 km across, rising to 10 km above the Martian datum, hosting four of the largest volcanoes in the solar system (Olympus Mons at 22 km, Ascraeus Mons, Pavonis Mons, and Arsia Mons at 18–20 km). On Earth, a mantle hotspot produces a chain of volcanic islands as the plate moves over it — the Hawaiian chain, extending ~6,000 km northwest of the Big Island, records ~80 million years of plate motion at ~10 cm/year. On Mars, with no plate motion, the hotspot simply pumps material into one place for billions of years, constructing a volcanic plateau so massive that its weight has tilted the entire Martian lithosphere, creating the enormous extensional rift system of **Valles Marineris** (~4,000 km long, up to 7 km deep, 600 km wide) on Tharsis's eastern flank as the crust was pulled apart under the load.

**Venus: a planet in transition?** Venus is the most Earth-like planet in terms of size, mass, and inferred internal heat budget, making its tectonic history a critical question. Magellan radar mapping (1990–1994) revealed a surface dominated by volcanic plains, ~1,600 shield volcanoes, and the enigmatic **coronae** — roughly circular volcanic-tectonic structures 100–2,600 km across, interpreted as the surface expression of mantle plumes impinging on a non-mobile lid. The near-absence of impact craters smaller than ~3 km (below which the dense Venusian atmosphere destroys impactors) and the relatively uniform age of the visible surface (~500–800 Ma based on crater density) have been interpreted as evidence for **catastrophic global resurfacing**: an episode around 0.5–1 Ga in which massive volcanic flooding buried the pre-existing surface, erasing the impact record. Two competing models debate the mechanism: (1) **episodic overturn** — Venus alternates between long stagnant-lid episodes (during which heat accumulates) and brief catastrophic overturn events (during which the lid founders and is replaced by new surface); or (2) **continuous thin-lid** — Venus has been gradually resurfacing through thin-lid (sluggish) tectonics that is too slow to resemble Earth's plate tectonics but fast enough to have continuously renewed the surface over the past 500–800 Ma. ESA's **EnVision** mission and NASA's **VERITAS** mission (both approved, currently in development) will map Venus's surface and subsurface at far greater resolution than Magellan, potentially resolving this debate.

**The Moon: a one-plate planet.** The Moon has no tectonic activity today and, like Mars, operates as a single-plate body. Its most prominent internal geological feature is the near-side/far-side asymmetry: the near-side crust is ~8 km thinner than the far-side (GRAIL data), and the near-side hosts all of the major **mare** (basaltic plains) — Oceanus Procellarum, Mare Imbrium, Mare Serenitatis, and others — while the far-side is almost entirely ancient highland anorthosite. The asymmetry in volcanism mirrors the asymmetry in crustal thickness: lava erupted preferentially where the crust was thinner (near side), requiring less pressure to penetrate to the surface. The oldest mare basalts are ~3.9 Ga; the youngest well-documented eruptions are ~1.2 Ga; some evidence (Lunar Reconnaissance Orbiter) suggests very low volumes of eruption may have occurred as recently as ~50–100 Ma, though this is debated. There is no evidence of ongoing volcanism today.

**Io: volcanic but not tectonic.** Jupiter's innermost large moon, Io, is the most volcanically active body in the solar system — with over 400 active volcanic centres, surface heat flow of ~2–4 W/m², and resurfacing on a ~1 million year timescale by the prodigious output of its tidal-heating-powered eruptions. Yet Io has no plate tectonics: its extraordinary heat output escapes through volcanic centres rather than through plate recycling. Io demonstrates that volcanism and plate tectonics are not synonymous: very high internal heat can be vented through a stagnant lid if the volcanic output is sufficient. The absence of plates on Io may reflect its different heat source (tidal, not radiogenic/secular) and the unknown rheological properties of a continuously overturning volcanic surface rather than any analogy to Mars or Venus.

**Conditions for plate tectonics.** Assembling the comparative evidence, three conditions emerge as likely necessary (though perhaps not individually sufficient) for plate tectonics: (1) **water in the mantle** to lower lithospheric viscosity and enable the ductile bending required for subduction initiation; (2) **adequate internal heat** over geological time to sustain mantle convection without the lithosphere thickening to the point that subduction becomes impossible; and (3) the **right planet size** — large enough to retain internal heat over billions of years (ruling out Mercury and the Moon), but not so large that the lithosphere becomes too thick and buoyant under high gravity to subduct. Whether water is the critical variable — making Earth special because of its volatile-rich feeding zone during accretion — or whether the stochastic geometry of plate initiation (subduction must start somewhere, perhaps triggered by an impact or a weak zone in the lithosphere) is the key uncertainty, remains one of the most important open questions in planetary geodynamics.`,
      keyTerms: [
        {
          term: 'Stagnant lid',
          def: `A tectonic regime in which a planet\'s lithosphere forms a single unbroken shell — mechanically too strong to subduct or rift into mobile plates. Heat escapes primarily by conduction through the lid and by localised volcanism. The lid thickens over time as the planet cools. Mars, Venus (probably), Mercury, and the Moon are all stagnant-lid bodies. The stagnant lid regime is the solar system\'s norm; Earth\'s mobile plate regime is the exception. The lithosphere under a stagnant lid can still deform slowly over long timescales, but it does not recycle into the mantle.`,
        },
        {
          term: 'Subduction',
          def: 'The descent of one lithospheric plate beneath another into the mantle, driven by the negative buoyancy of cold, dense oceanic crust (which transforms to eclogite at depth, density ~3,600 kg/m³, denser than surrounding mantle ~3,300 kg/m³). The "slab pull" force from the sinking dense slab is the dominant driving force for plate motions on Earth. Subduction is unique to Earth in the solar system. It requires plates dense enough to sink (dense basaltic oceanic crust), ductile enough to bend (water lowers lithospheric viscosity), and a mantle convecting vigorously enough to drag the plate down.',
        },
        {
          term: 'Tharsis volcanic province',
          def: `A massive volcanic plateau on Mars, approximately 4,000 km in diameter and rising ~10 km above the Martian datum, hosting four of the solar system\'s largest shield volcanoes: Olympus Mons (22 km tall), Ascraeus Mons, Pavonis Mons, and Arsia Mons (~18–20 km). Tharsis is the direct consequence of stagnant lid tectonics: without plate motion, a mantle hotspot pumped volcanic material into one location for billions of years, constructing an edifice so massive that it deformed the global Martian lithosphere, generating the Valles Marineris rift system on its eastern flank.`,
        },
        {
          term: 'Coronae (Venus)',
          def: `Quasi-circular volcanic-tectonic features unique to Venus, ranging from 100 to 2,600 km in diameter, characterised by a central volcanic and uplifted region surrounded by concentric tectonic ridges and troughs. Interpreted as the surface expression of hot mantle plumes impinging on Venus\'s thick, non-mobile lithosphere. The plume thermally domes the overlying crust, generating concentric fractures, and volcanic material erupts at the centre. More than 500 coronae are identified on Venus from Magellan radar data. They represent the closest Venusian analogue to terrestrial plume-related tectonics, but without the plate recycling that on Earth would eventually subduct the affected crust.`,
        },
        {
          term: 'Episodic resurfacing (Venus)',
          def: `A proposed model for Venus\'s tectonic evolution in which the planet alternates between long quiescent stagnant-lid periods (during which interior heat accumulates because the lid prevents efficient loss) and brief catastrophic overturn events in which the lid founders and massive volcanism resurfaces the entire planet within ~100 Ma. The model is motivated by the relatively uniform age of Venus\'s current surface (~500–800 Ma based on crater density), which would be explained if the pre-existing surface was completely buried during the last overturn. The competing hypothesis is continuous gradual resurfacing by thin-lid (sluggish) tectonics. EnVision and VERITAS will discriminate between these models.`,
        },
      ],
    },
    {
      type: 'concept',
      title: 'Tectonic regimes across rocky bodies',
      body: `Planetary tectonics spans a continuum from Earth's uniquely active plate recycling to the completely inert fossil surfaces of the Moon and Mercury. Comparing specific bodies reveals why the conditions for plate tectonics are demanding and rarely met, and why the geologic record of each body — its volcanism, its crater age distribution, its topographic extremes — is a direct expression of its tectonic regime.`,
      cards: [
        {
          name: 'Mars: Stagnant Lid and Tharsis',
          icon: Mountain,
          color: BRAND.amethyst,
          desc: `Mars is the canonical stagnant-lid planet. With no plate motion to move the surface over hotspots, volcanic material accumulated in one location for billions of years to build the Tharsis bulge — 4,000 km wide, 10 km high, hosting Olympus Mons (22 km, the solar system\'s tallest volcano) and Valles Marineris (4,000 km long, 7 km deep, formed by extensional collapse of Tharsis\'s flanks). Mars may have had a short-lived partial subduction episode in the Noachian (~4.0–4.5 Ga), but it has been geologically stagnant since.`,
          examples: `Olympus Mons: 22 km tall, 600 km base, caldera 80 km wide · Compare: Earth\'s Mauna Kea 10.2 km from seafloor, 120 km base · Tharsis buildup: ~3.6×10⁹ km³ of volcanic material · Valles Marineris: 4,000 km long, 600 km wide, 7 km deep — outscales Grand Canyon by factor ~10 · Cerberus Fossae: young (<10 Ma) extensional fissures near InSight landing site — Mars not fully dead`,
        },
        {
          name: 'Venus: Coronae, Resurfacing, and Tesserae',
          icon: Globe,
          color: BRAND.gold,
          desc: 'Venus has >1,600 major volcanic features mapped by Magellan radar but no evidence of active plate subduction. Coronae (100–2,600 km, >500 identified) and tesserae (heavily deformed highland terrain — the oldest identifiable surface units) suggest a complex, partly mobile lid that is neither plate tectonics nor pure stagnant lid. The near-uniform surface age (~500–800 Ma) supports either episodic catastrophic resurfacing or continuous thin-lid volcanism. VERITAS and EnVision will discriminate.',
          examples: 'Maat Mons: 8 km tall shield volcano, VIRTIS detected anomalous emissivity suggesting fresh lava flows within years to decades · Aphrodite Terra: mountain belt possibly indicating transpressional tectonics · Tesserae: multiple deformation episodes recorded in ridge-belt and fracture patterns · Ishtar Terra: mountain belt at 11 km elevation (Maxwell Montes), possibly analogous to Earth collision zones · Surface age: ~500–800 Ma from crater density',
        },
        {
          name: 'Moon and Mercury: One-Plate Worlds',
          icon: Layers,
          color: BRAND.coral,
          desc: `Both Moon and Mercury are ancient one-plate bodies with no current tectonic or volcanic activity. The Moon\'s near-side basaltic mare reflect asymmetric crustal thickness — lava erupted preferentially where crust was thinnest. Mare volcanism ended ~1.2 Ga. Mercury has lobate scarps (global-scale thrust faults recording ~7 km of planetary radius shrinkage as the core cooled and contracted) and ancient smooth plains from an early volcanic episode. Both are fossil tectonic records of early solar system heating.`,
          examples: 'Moon mare volcanism: 3.9–1.2 Ga; youngest possibly ~50–100 Ma (LRO evidence, debated) · Mercury lobate scarps: discovered by Mariner 10 (1974), mapped globally by MESSENGER — record ~0.05% radius decrease · Mercury smooth plains: ~4.0–3.8 Ga, covering ~27% of the planet · MESSENGER: Mercury has globally fragmented, possibly slightly mobile lithosphere (Byrne et al. 2021) — unlike any other stagnant-lid body',
        },
        {
          name: 'Earth: The Plate Tectonics Prerequisite Set',
          icon: Activity,
          color: BRAND.jade,
          desc: `Earth\'s plate tectonics requires: (1) dense oceanic crust that transforms to eclogite at depth (negative buoyancy for slab pull); (2) water in the mantle and crust lowering lithospheric viscosity (enabling ductile bending for subduction initiation); (3) adequate internal heat for vigorous mantle convection; (4) the right planet size (large enough to retain heat, small enough for plates to form). Removing water from the mantle (hydration of subducting slabs is critical) or cooling the planet to thicken the lid beyond a critical thickness would shut down subduction.`,
          examples: 'Slab pull: subducted eclogite density ~3,600 kg/m³ vs mantle ~3,300 kg/m³ → 10% denser → strong negative buoyancy · Water: hydrated oceanic crust carries ~1–2 wt% H2O to depth; dehydration drives arc volcanism and mantle wedge melting · Hawaiian chain: 6,000 km of islands recording 80 Ma of Pacific plate motion at ~10 cm/yr over fixed hotspot · Comparison: same hotspot on Mars → Olympus Mons (no plate motion, volcanic piling)',
        },
      ],
    },
    {
      type: 'visualization',
      title: 'Tectonic regime spectrum: from plate tectonics to stagnant lid',
      body: `This flow diagram contrasts the physical conditions that lead to Earth\'s active plate tectonic regime versus the stagnant lid regimes of Mars, Venus, Moon, and Mercury — tracing how differences in water availability, internal heat, lithospheric strength, and planet size determine which branch of the tectonic regime spectrum each body occupies.`,
      interaction: {
        type: 'flow-simulator' as const,
        description: 'Tracing the divergence between plate tectonic and stagnant lid regimes: from shared planetary formation conditions through the critical branch points of water availability, lithospheric viscosity, and density contrast to either the Earth-like subduction cycle (oceanic crust formation, hydration, densification, slab pull, arc volcanism, and carbonate-silicate cycle regulation) or the stagnant lid outcome (thickening immobile lid, hotspot volcanism accumulation, no crustal recycling, and volcanic piling as on Tharsis)',
        nodes: [
          {
            id: 'rocky-planet-formation',
            label: 'Rocky Planet Formation',
            description: 'All rocky planets form by accretion of silicate and metal planetesimals. The initial conditions — planet size, volatile delivery, distance from the Sun, and the timing of giant impacts — determine internal heat budget, core size, volatile inventory, and starting lithospheric properties. Earth received a relatively large water delivery (both from local planetesimals and late-stage carbonaceous chondrite delivery from the outer solar system), Venus may have formed drier or lost its volatiles during an early runaway greenhouse, and Mars formed in a volatile-rich region but is too small to retain them efficiently over time.',
            color: BRAND.accent,
          },
          {
            id: 'water-question',
            label: 'Critical Branch: Water in the Mantle?',
            description: `Water is the pivotal variable distinguishing Earth\'s plate tectonics from the stagnant lid of other bodies. Water dissolved in olivine and other mantle minerals lowers their effective viscosity by orders of magnitude, enabling ductile flow and the bending required for subduction initiation. Without water, lithospheric mantle rheology is too stiff for the hinge bending needed to initiate and sustain a subduction zone. Venus appears to have lost its surface and mantle water early — possibly evaporated during a runaway greenhouse episode triggered by slightly higher solar luminosity at its closer orbital distance. A dry Venusian mantle would be too viscous to allow plate initiation even if a dense region existed.`,
            color: BRAND.amethyst,
          },
          {
            id: 'plate-tectonics-path',
            label: 'Plate Tectonics Conditions Met (Earth)',
            description: 'Earth meets all the conditions: water-rich mantle (water lowers viscosity, enables subduction bending), adequate internal heat from radiogenic decay and secular cooling for vigorous mantle convection, dense oceanic basalt (transforms to eclogite at depth — slab pull force), and the right planet size (large enough to sustain interior heat for 4.5 Ga, small enough for thin, mobile plates to form). The result: a globally cycling lithosphere that creates new crust at mid-ocean ridges, ages and densifies across ocean basins, and subducts at trenches, recycling volatiles and nutrients and regulating atmospheric CO2 through the carbonate-silicate cycle.',
            color: BRAND.jade,
          },
          {
            id: 'stagnant-lid-path',
            label: 'Stagnant Lid Conditions (Mars, Venus, Moon)',
            description: 'Planets that lack water in the mantle (Venus — dry rheology), have insufficient internal heat to sustain thin mobile plates (Moon, Mercury — too small), or may simply never have initiated subduction despite having the ingredients (Venus — insufficient Coriolis-driven convective overturn to thin the lid?) develop a stagnant single-plate lithosphere. The lid thickens progressively as the planet cools. Heat escapes by conduction through the lid and by localised volcanism. Without recycling, incompatible elements (K, U, Th, and other heat producers) accumulate in the crust rather than being returned to the mantle, progressively depleting the mantle and reducing long-term volcanic output.',
            color: BRAND.ruby,
          },
          {
            id: 'earth-consequences',
            label: 'Earth Plate Tectonics: CO2 Cycle and Habitability',
            description: `Plate tectonics is the physical mechanism underlying Earth\'s long-term carbonate-silicate climate regulation cycle. CO2 is removed from the atmosphere by weathering of silicate rocks (consuming CO2 and producing carbonate minerals), which are subducted with the oceanic crust. Subduction and arc volcanism release the stored CO2 back to the atmosphere. This geological thermostat has maintained Earth\'s surface temperature within a habitable range over ~4 Ga, even as solar luminosity increased ~30%. Without plate tectonics, the silicate weathering-subduction cycle breaks down, and other mechanisms must regulate climate — as evidenced by Venus\'s inability to maintain liquid water once its water was lost.`,
            color: BRAND.jade,
          },
          {
            id: 'stagnant-lid-consequences',
            label: 'Stagnant Lid: Volcanic Piling and Atmospheric Decay',
            description: 'Without plate tectonics, volcanic output concentrates over fixed hotspots, building giant volcanic constructs (Tharsis on Mars; Olympus Mons at 22 km). There is no silicate weathering-subduction CO2 cycle, so atmospheric CO2 is not regulated on geological timescales. Mars lost its atmosphere primarily to solar wind sputtering (with no magnetosphere after ~4 Ga) and to volatile sequestration in polar ice and regolith. Venus retained its CO2 as an unchecked greenhouse atmosphere because CO2 is not recycled through subduction but simply accumulates. The stagnant lid is stable but ultimately leads to a geologically dead world as cooling progresses.',
            color: BRAND.coral,
          },
        ],
        edges: [
          { from: 'rocky-planet-formation', to: 'water-question',          label: 'Initial volatile inventory, orbital distance, and giant impact history determine water content' },
          { from: 'water-question',         to: 'plate-tectonics-path',    label: 'Sufficient mantle water: lowers viscosity, enables ductile bending, subduction can initiate' },
          { from: 'water-question',         to: 'stagnant-lid-path',       label: 'Insufficient water, or planet too small/cool: rigid lid cannot subduct, thickens progressively' },
          { from: 'plate-tectonics-path',   to: 'earth-consequences',      label: 'Active plate recycling enables carbonate-silicate cycle, volcanic CO2 return, long-term habitability' },
          { from: 'stagnant-lid-path',      to: 'stagnant-lid-consequences', label: 'Fixed hotspot volcanism builds Tharsis-type structures; no CO2 cycle regulation; atmospheric decay' },
          { from: 'earth-consequences',     to: 'plate-tectonics-path',    label: 'Recycled water via subduction returns to mantle, sustaining low viscosity and ongoing plate motion' },
        ],
      },
    },
    {
      type: 'quiz',
      questions: [
        {
          q: `Olympus Mons on Mars (22 km tall, 600 km base) is approximately twice the height of Mauna Kea measured from the seafloor (10.2 km, ~120 km base), the largest volcano on Earth. What specific property of Mars\'s tectonic regime explains why a Martian volcano can grow so much larger than any Earth volcano, and what would happen to Olympus Mons if Mars suddenly acquired Earth-like plate tectonics?`,
          a: [
            'Olympus Mons is taller because Mars has lower gravity (0.38 g vs 1.0 g), allowing volcanic material to pile higher before gravitational collapse limits the edifice height; if plate tectonics began, Olympus Mons would remain unchanged because plate motion does not affect volcanic edifice height, only the distribution of volcanic centers',
            'Olympus Mons grew so large because Mars\'s stagnant lid means the surface never moves over the mantle hotspot: without plate motion, all volcanic output from one hotspot accumulates in one location for billions of years, building a colossal single edifice; in contrast, Earth\'s plate motion carries the surface over hotspots at ~10 cm/yr, distributing volcanic output as a chain of islands (e.g., Hawaiian chain) rather than concentrating it at one point; if Mars had plate tectonics, the same hotspot would produce a ~6,000 km chain of smaller volcanoes analogous to the Hawaiian-Emperor chain rather than one giant shield',
            'Olympus Mons is taller because Mars has a larger mantle plume flux than any Earth hotspot; the hotspot under Tharsis delivers magma at a rate ~100 times higher than the Hawaiian hotspot; plate tectonics would not change this flux, but it would cause the chain of volcanoes to form over the hotspot as plates moved, producing a chain of 22 km volcanoes rather than one',
            'Olympus Mons grew large because Mars has no oceans — on Earth, oceanic hotspot volcanoes are limited by isostatic subsidence below sea level once they grow heavy enough; on Mars, there is no ocean to subside into, so volcanic growth is unlimited; plate tectonics would not affect volcanic size on Mars because the limitation on Earth\'s volcanoes is entirely oceanic isostasy',
          ],
          correct: 1,
          explain: `The key to Olympus Mons\'s extraordinary size is the combination of stagnant lid tectonics and a persistent mantle hotspot. On Earth, the Pacific Plate moves over the Hawaiian hotspot at approximately 10 cm per year. As the plate moves, new volcanic islands form over the hotspot and older ones are carried away, erode, and eventually subside below sea level as seamounts. The hotspot eruption rate is finite: it produces a limited volume of magma per unit time, which is now spread along a 6,000 km chain of progressively older, progressively smaller and more eroded islands from the Big Island (active hotspot location) northwest to the ancient Emperor Seamounts. Each individual volcano grows for only ~1–2 million years before the plate carries it away from the hotspot; the Big Island\'s total height from seafloor is ~10.2 km, produced in ~1 Ma. On Mars, there is no plate motion. The mantle hotspot beneath Tharsis has been in the same position relative to the overlying crust for billions of years. Every cubic kilometre of magma produced by the hotspot has been delivered to the same surface location. Over ~3 billion years of accumulated eruption, the result is a volcanic pile 22 km high and 600 km across. The stagnant lid regime is thus not just a negative absence (no recycling) but has a positive consequence: it allows truly colossal volcanic constructs that are simply impossible in plate tectonic regimes where the surface moves past the hotspot. If Mars suddenly acquired plate tectonics, future eruptions would be dispersed along a chain; Olympus Mons itself would remain (lava is not retroactively removed) but would begin to erode and cool without ongoing eruption focused at that point. Answer A correctly notes Mars\'s lower gravity but incorrectly claims gravity is the primary height limitation — gravity does matter (on Mars, lower gravity means the lithosphere can support a taller load), but the primary factor is the fixed-hotspot piling under stagnant lid. Answer C incorrectly attributes the large size to a higher magma flux. Answer D introduces oceanic isostasy as the primary Earth limitation, which is a real factor but secondary to the hotspot-dwell-time effect.`,
        },
        {
          q: `Venus is nearly identical to Earth in size, mass, and bulk composition, yet shows no evidence of active plate tectonics. Among the proposed explanations — slow rotation, dry mantle rheology, and lithospheric strength — which physical mechanism is most directly implicated by Venus\'s lack of subduction, and what specific rock property would change if Venus had Earth\'s water budget?`,
          a: [
            'The most directly implicated mechanism is slow rotation; Venus\'s 243-day rotation generates insufficient Coriolis force to drive the mantle convection needed to pull plates apart at spreading centres; water budget is irrelevant because water only affects subduction trench dynamics, not spreading ridge dynamics',
            'The most directly implicated mechanism is dry mantle and lithospheric rheology; water dissolved in olivine and other mantle minerals lowers their viscosity (effective creep rate increases by orders of magnitude even at low water content); a dry Venusian lithospheric mantle is mechanically stiff and resists the ductile bending at subduction hinges that is required to initiate and sustain plate descent; if Venus had Earth\'s water budget, its mantle olivine and pyroxene would have significantly lower effective viscosity, making the lithosphere more ductile and allowing the plate bending necessary for subduction initiation',
            'The most directly implicated mechanism is lithospheric temperature; Venus\'s extreme surface temperature (465°C) heats the lithosphere from the outside, reducing its density contrast with the mantle so that oceanic crust cannot become denser than the mantle even when it cools; water budget changes would not address this fundamental density issue',
            'The most directly implicated mechanism is planet age; Venus is older than Earth (it formed closer to the Sun and therefore formed first from the solar nebula), so its interior has cooled further and mantle convection is too sluggish to drive plate motion; water content is secondary because even a wet mantle cannot produce plate tectonics when mantle convection vigor is below the threshold',
          ],
          correct: 1,
          explain: `While multiple factors likely contribute to Venus\'s lack of plate tectonics, the water (dry rheology) mechanism is the most directly implicated based on what we know about the physics of subduction initiation. The critical barrier to plate tectonics on Venus is not the absence of dense subductable material — Venus almost certainly has basaltic oceanic crust from its volcanic plains, and basalt transforms to eclogite at subduction pressures, becoming denser than the mantle. The problem is mechanical: initiating subduction requires bending the lithosphere at a hinge zone, which requires ductile deformation of the lower lithospheric mantle (the cold, strong layer of depleted peridotite beneath the crust). Laboratory experiments (Hirth & Kohlstedt 1996 and follow-up work) demonstrate that the effective viscosity of olivine (the dominant mineral in lithospheric mantle) decreases by 1–3 orders of magnitude when water concentration increases from anhydrous (~1 ppm H/Si) to water-saturated (hundreds to thousands of ppm H/Si). Earth\'s oceanic lithospheric mantle is hydrated primarily through serpentinisation of peridotite at fracture zones and slow-spreading ridges, making the base of the lithosphere significantly more ductile than a completely dry equivalent. Venus, having lost its water early in its history (the current Venusian atmosphere contains ~30 ppm H2O, compared to thousands of ppm in Earth\'s troposphere, and estimates suggest Venus\'s mantle water content may be <10% of Earth\'s), would have an extremely dry, rigid lithospheric mantle. Numerical simulations of subduction initiation consistently show that dry conditions dramatically increase the yield strength required to break the lithosphere and bend it into a subduction zone. If Venus had Earth\'s water budget, the olivine rheology in its lithospheric mantle would be orders of magnitude softer, enabling the ductile hinge deformation at incipient subduction zones. Answer A incorrectly attributes the primary role to rotation — rotation is critical for dynamo generation (irrelevant for plate tectonics per se) and modulates mantle convection patterns, but the Coriolis force is not the primary driver of subduction. Answer C correctly notes the surface temperature but incorrectly claims it prevents eclogite formation — surface temperature affects the shallow crust but not the deep (60–100 km) conditions where eclogite transformation occurs and density contrast develops. Answer D is incorrect: Venus and Earth are essentially the same age (both formed ~4.5 Ga), and age-related cooling differences are too small to explain the fundamental contrast.`,
        },
        {
          q: `Mars\'s Valles Marineris — ~4,000 km long, 600 km wide, and up to 7 km deep — is often misleadingly compared to the Grand Canyon (450 km long, 30 km wide, 1.8 km deep) in popular accounts. What is the correct geological formation mechanism of Valles Marineris, and how does this mechanism differ fundamentally from the fluvial erosion that formed the Grand Canyon?`,
          a: [
            'Valles Marineris formed by fluvial erosion, like the Grand Canyon, but on a much larger scale: early Mars had abundant liquid water and large rivers that carved the canyon system over several billion years; the comparison to the Grand Canyon is accurate in mechanism, just different in scale and duration',
            'Valles Marineris formed primarily by meteor impact: a very large asteroid struck the Martian surface obliquely, creating the elongated trench; the comparison to the Grand Canyon is misleading because impact craters bear no resemblance to river canyons, and Valles Marineris is not a canyon at all but an impact scar',
            'Valles Marineris is a tectonic rift: it formed by extensional crustal fracturing driven by the gravitational load and thermal expansion of the adjacent Tharsis volcanic province — as the enormous weight of Tharsis bulged the lithosphere upward on its western side, the eastern flank was pulled apart in tension, opening extensional faults that created the deep graben system; unlike the Grand Canyon (formed by the Colorado River downcutting through uplifted Colorado Plateau rock), Valles Marineris was not eroded by a river but was formed by crustal extension and subsequent collapse into the down-dropped graben blocks',
            'Valles Marineris is an ancient subduction zone: it marks the scar of the one brief episode of Martian plate tectonics (~4.5 Ga), where an ancient Martian oceanic plate subducted beneath the southern highlands, leaving a fossil trench that preserves the geometric record of the subduction hinge; this is fundamentally similar to the Grand Canyon in that both formed by material being removed — oceanic crust in the case of Valles Marineris, and sedimentary rock in the case of the Grand Canyon',
          ],
          correct: 2,
          explain: `Valles Marineris is one of the most commonly misrepresented geological features in solar system education. It is not a river canyon — there is no identified river system that could have carved a 4,000 km, 7 km deep trench with the geometry observed. Its formation is fundamentally tectonic, specifically extensional, driven by the gravitational loading effects of the Tharsis volcanic province. The Tharsis bulge — approximately 4,000 km across, rising ~10 km above the Martian datum — represents an enormous mass of volcanic material that has been accumulating on the Martian lithosphere for billions of years. The weight of this mass deflects the elastic lithosphere: the crust beneath Tharsis is compressed (loaded), and the crust on the flanks is placed in tension (flexure). On the eastern flank of Tharsis, this tensional stress has broken the crust along a series of parallel east-west-trending normal faults, creating a graben (down-dropped block between two normal faults) system of extraordinary proportions. The grabens coalesced and deepened over time to produce Valles Marineris. The fundamental difference from the Grand Canyon: the Grand Canyon is an erosional feature — a pre-existing plateau was uplifted by regional tectonics (the Colorado Plateau Laramide uplift), and the Colorado River subsequently incised downward through the rock layers, removing material by fluvial erosion over ~5–6 Ma. Valles Marineris was formed by the crust pulling apart — material was not removed by erosion but dropped down between faults, with the canyon walls being the exposed fault scarps. However, there is evidence that water and mass wasting (landslides) have substantially modified Valles Marineris\'s walls after the initial tectonic opening, so erosion has played a secondary role in shaping its current morphology. Answer A incorrectly attributes the primary formation mechanism to fluvial erosion. Answer B incorrectly identifies it as an impact feature — Valles Marineris has none of the morphological characteristics of impact craters (circular depression, central peak, ejecta blanket). Answer D proposes a subduction zone origin that is not supported by the structural geology of the feature.`,
        },
        {
          q: 'Scientists debate whether Venus has undergone episodic catastrophic global resurfacing or continuous thin-lid volcanism to explain the near-uniform crater age of its surface (~500–800 Ma). What observational evidence would allow VERITAS or EnVision to definitively distinguish between these two models, and what would each model predict about the subsurface stratigraphy and heat flow?',
          a: [
            'The two models predict identical observable surface features and subsurface structure; neither VERITAS nor EnVision can distinguish between them because both produce a similar 500–800 Ma surface age and similar volcanic landform distributions; only a landed seismometer network could resolve the debate by detecting present-day volcanic tremors',
            'The episodic resurfacing model predicts: (1) a sharp, globally synchronous unconformity in subsurface stratigraphy separating pre-resurfacing materials (potentially diverse in age) from a uniform post-resurfacing volcanic sequence; (2) spatially uniform, relatively low present-day heat flow (as the planet has been in a quiet inter-resurfacing phase for 500–800 Ma); (3) a bimodal crater age distribution (very old craters below the unconformity, none on top until the current crater population accumulates). The thin-lid model predicts: (1) a continuously gradational stratigraphy with older material preserved at greater depth in different regions; (2) spatially variable, locally elevated heat flow above active thin-lid volcanic regions; (3) a unimodal crater age distribution that reflects a slowly declining volcanic resurfacing rate rather than a sharp event. VERITAS\'s synthetic aperture radar and gravity mapping could detect the subsurface stratigraphy; both missions will constrain heat flow through thermal emission',
            'The episodic resurfacing model predicts high present-day volcanic activity (because Venus is near or at the start of the next overturn cycle), while the thin-lid model predicts low volcanic activity (because resurfacing has been continuous and gradual for 500–800 Ma); VERITAS will unambiguously discriminate between the models by detecting active lava flows via radar comparison with Magellan images',
            'The two models are distinguished only by the distribution of tesserae: the episodic resurfacing model predicts tesserae are globally uniformly distributed (having formed before the last resurfacing event), while the thin-lid model predicts tesserae are concentrated in one hemisphere (reflecting a long-term thin-lid convergence zone); VERITAS gravity mapping of crustal thickness will test this prediction',
          ],
          correct: 1,
          explain: `The two competing models for Venus\'s tectonic evolution make fundamentally different predictions about the planet\'s internal structure, thermal state, and subsurface stratigraphy — all of which VERITAS and EnVision are designed to probe. The **episodic catastrophic resurfacing model** envisions that Venus undergoes cycles of thermal accumulation and catastrophic overturn, potentially with a period of several hundred million years. During the quiescent stagnant-lid phase, interior heat builds up because conduction through the thick lid is inefficient. When the accumulated heat flux becomes sufficient, the lid becomes gravitationally unstable (denser from thermal contraction at the base) and founders catastrophically over ~10–100 Ma, replaced by fresh volcanic material from the upwelling mantle. If the last overturn occurred ~500–800 Ma ago, Venus is currently in a quiet inter-overturn phase: heat flow should be relatively uniform and low (comparable to or less than current Mars), and the subsurface should show a sharp stratigraphic unconformity separating pre-overturn material (which would be geochemically distinct from post-overturn lavas) from the ~500–800 Ma post-overturn sequence. The **thin-lid model** envisions continuous gradual resurfacing analogous to a very slow plate tectonics, in which the lid is never truly stagnant but slowly overturns material over long timescales. This model predicts continuously active volcanism, spatially variable heat flow (highest over thin-lid upwelling zones), and gradational rather than abrupt subsurface stratigraphy. VERITAS\'s key instruments — a synthetic aperture radar to image topography and surface deformation at 30 m resolution, an infrared radiometer to measure surface emissivity and detect fresh lava, and a gravity science experiment to map crustal thickness — can test these predictions. Subsurface returns from the radar could reveal stratigraphic layering; the gravity map will show whether crust thickness distribution is consistent with a globally synchronous volcanic event or regional variable resurfacing; and the thermal emission map could detect active volcanic centers predicted by the thin-lid model. Answer A incorrectly states the models are observationally indistinguishable from orbit. Answer C incorrectly characterises the episodic model as predicting high current activity — the model predicts the opposite (Venus is between overturns, in a quiet phase). Answer D mischaracterises tesserae distribution as the discriminating observable; tesserae distribution is relevant but is not the primary test of the global timing question.`,
        },
      ],
    },
  ],
}

export default stagnantLidTectonics
