import { Wind, Globe, Sun } from 'lucide-react'
import { BRAND } from '@/lib/brand'
import type { Lesson } from './types'

const greenhouseEffect: Lesson = {
  id: 'atmo-101-1-1-4',
  title: 'The Greenhouse Effect and Radiative Forcing',
  track: 'atm',
  trackName: 'Meteorology',
  level: 'Beginner',
  duration: '12 min',
  xpReward: 140,
  description: "The greenhouse effect has kept Earth habitable for 4 billion years. Understanding the physics behind it — and the concept of radiative forcing — explains how small changes in atmospheric composition produce large changes in climate.",
  sources: [
    { org: 'NOAA',     title: 'Climate.gov — The Greenhouse Effect',                       url: 'https://www.climate.gov/news-features/climate-qa/what-greenhouse-effect' },
    { org: 'NASA',     title: 'The Causes of Climate Change',                              url: 'https://climate.nasa.gov/causes/' },
    { org: 'OpenStax', title: 'Introduction to Atmospheric Science, Ch. 4 (CC-BY 4.0)',   url: 'https://openstax.org/books/introduction-oceanography' },
    { org: 'IPCC',     title: 'AR6 Working Group I — Physical Science Basis (2021)',       url: 'https://www.ipcc.ch/report/ar6/wg1/' },
    { org: 'NOAA',     title: 'Global Monitoring Laboratory — Radiative Forcing',         url: 'https://gml.noaa.gov/aggi/' },
  ],
  sections: [
    {
      type: 'intro',
      title: 'Earth\'s natural warming blanket',
      body: `If you removed every greenhouse gas from Earth's atmosphere overnight, the planet would cool by approximately 33°C — from its current average of +15°C to −18°C. The oceans would begin to freeze. Most of the liquid water on the surface would be locked into ice within decades. Complex life as we know it could not survive. The greenhouse effect is not a problem — it is the condition for life on Earth.

The greenhouse effect works because the atmosphere is not equally transparent to all types of electromagnetic radiation. Visible light from the sun (short wavelength, high energy) passes through the atmosphere with relatively little absorption, warming Earth's surface. The warm surface then emits infrared radiation (long wavelength, lower energy), but **greenhouse gases** — primarily water vapour, carbon dioxide, methane, and nitrous oxide — absorb this outgoing infrared radiation before it can escape to space. These gases re-emit the absorbed energy in all directions, including back toward the surface. The surface receives this additional downwelling radiation and must reach a higher temperature to achieve energy balance. This is the mechanism: selective transparency to shortwave radiation, selective opacity to longwave radiation, producing a warmer surface than an airless planet at the same distance from the sun would have.

The concept of **radiative forcing** quantifies how much any given change — in greenhouse gas concentration, solar output, volcanic aerosols, or land use — affects the flow of energy in the climate system, measured in watts per square metre. A positive forcing warms the planet; a negative forcing cools it. It is the common currency of climate science, allowing scientists to compare the climate effect of doubling CO₂ (a radiative forcing of +3.7 W m⁻²) against a volcanic eruption (negative forcing of −1 to −5 W m⁻²) against a change in solar output (small positive or negative forcing depending on the solar cycle). Understanding forcing and feedback — how the climate system responds to forcings — is essential to understanding both past climate changes and projections of future warming.`,
      keyTerms: [
        { term: 'Greenhouse gas (GHG)',    def: 'A gas that absorbs and re-emits infrared radiation, contributing to the greenhouse effect. Major greenhouse gases: H₂O (water vapour), CO₂, CH₄, N₂O, O₃, and synthetic halocarbons. N₂ and O₂ — the bulk of the atmosphere — are NOT greenhouse gases because they do not absorb IR radiation (symmetric diatomic molecules cannot vibrate in ways that interact with IR photons).' },
        { term: 'Radiative forcing',       def: 'The change in energy flux (in W m⁻²) at the top of the atmosphere caused by a perturbation (e.g., doubling CO₂, volcanic eruption, solar changes). Positive forcing = more energy enters than leaves = warming. Negative forcing = more energy leaves = cooling. Allows comparison of different climate drivers on a common scale. Doubling CO₂: +3.7 W m⁻²; 2023 total anthropogenic forcing: ~3.0 W m⁻².' },
        { term: 'Climate feedback',        def: 'A process that amplifies or dampens a forcing. Positive feedbacks amplify the original change (ice-albedo: warming melts ice → lower albedo → more warming; water vapour: warming increases H₂O → stronger GHE → more warming). Negative feedbacks dampen it (Planck/blackbody feedback: warmer Earth emits more IR → loses energy faster → limits warming). Net feedback determines climate sensitivity.' },
        { term: 'Climate sensitivity',     def: 'The equilibrium global mean surface temperature rise resulting from a doubling of CO₂. Estimated at 2.5–4.0°C (IPCC AR6 likely range), with a best estimate of ~3°C. Most of the uncertainty comes from cloud feedbacks. A 3°C equilibrium warming from CO₂ doubling includes all physical feedbacks (water vapour, ice-albedo, lapse rate) but not slow feedbacks (ice sheet collapse, permafrost carbon release).' },
        { term: 'Downwelling longwave radiation', def: 'Infrared radiation emitted by greenhouse gases and clouds downward toward Earth\'s surface — commonly called "back-radiation." Amounts to ~340 W m⁻² globally averaged, actually exceeding direct solar absorption at the surface. This downwelling IR is the direct heating mechanism of the enhanced greenhouse effect and is measurably increasing as greenhouse gas concentrations rise.' },
      ],
      interaction: {
        type: 'scientific-diagram' as const,
        id: 'atmospheric-circulation-cells',
        caption: 'Three-cell atmospheric circulation model per hemisphere: Hadley (equator–30°), Ferrel (30°–60°), and Polar (60°–90°). Surface wind belts and ITCZ position are shown at the boundaries.',
        credit: 'Hadley (1735) · Ferrel (1856) · NOAA',
      },
    },
    {
      type: 'concept',
      title: 'Physics of the greenhouse effect, feedbacks, and forcing',
      body: `**The molecular mechanism of the greenhouse effect.** Greenhouse gases absorb infrared radiation because their molecules can vibrate in ways that interact with specific IR wavelengths. Nitrogen (N₂) and oxygen (O₂) are symmetric diatomic molecules — they have no change in electric dipole moment when they vibrate, so they cannot interact with IR photons. Greenhouse gases are polyatomic or asymmetric molecules (CO₂, H₂O, CH₄, N₂O) with vibrational modes that do produce changing dipole moments, absorbing photons at specific wavelengths. CO₂, for example, absorbs strongly near 15 μm; water vapour has very broad absorption across many wavelengths; methane absorbs near 7.7 μm. After absorbing an IR photon, a greenhouse gas molecule re-emits a photon at the same or similar wavelength but in a random direction — approximately half back toward the surface, half toward space. This recycling of outgoing IR warms the surface.

**Why CO₂ matters so much.** Water vapour is actually a more powerful greenhouse gas than CO₂ in terms of total absorption. Yet CO₂ (not H₂O) is considered the master regulator of climate on geological timescales. The reason is that water vapour is controlled by temperature: a warmer atmosphere holds more water vapour (Clausius-Clapeyron relation), but if you removed CO₂ and Earth cooled, the atmosphere would lose water vapour too (as water condensed out), removing its greenhouse contribution. CO₂ persists in the atmosphere for hundreds to thousands of years regardless of temperature; it is the primary forcing agent, and water vapour is a feedback amplifier of CO₂-driven warming. On geological timescales, volcanic outgassing and silicate weathering control CO₂ concentration; on human timescales, fossil fuel combustion and deforestation control it.

**Radiative forcing: the climate balance sheet.** Radiative forcing is measured at the top of the troposphere (or top of the atmosphere) after stratospheric temperatures have adjusted. It is a flux (W m⁻²), positive when energy is added to the climate system and negative when energy is removed. Current (2023) total anthropogenic radiative forcing is approximately +3.0 W m⁻² above pre-industrial levels, driven primarily by CO₂ (+2.2 W m⁻²), CH₄ (+0.5 W m⁻²), N₂O (+0.2 W m⁻²), and halocarbons (+0.4 W m⁻²), offset partly by aerosol cooling (−1.0 to −2.0 W m⁻² from sulfate and organic aerosols). The uncertainty in aerosol forcing is the largest source of uncertainty in total anthropogenic forcing estimates.

**Feedbacks and climate sensitivity.** A radiative forcing alone does not determine how much the climate will warm — feedbacks determine the final temperature response. The **Planck feedback** (blackbody response) is the fundamental negative feedback: a warmer Earth emits more IR (Stefan-Boltzmann law), which partially offsets the forcing. Without any other feedbacks, a doubling of CO₂ (+3.7 W m⁻²) would produce ~1°C of warming. But the Earth system amplifies this through positive feedbacks. **Water vapour feedback**: warming increases atmospheric H₂O, which is itself a greenhouse gas; this roughly doubles the warming (~+1°C additional). **Ice-albedo feedback**: warming melts ice, reduces albedo, more solar energy absorbed (~+0.3°C additional in global mean). **Lapse rate feedback**: warming affects the vertical temperature profile differently in tropics vs. poles, a complex feedback. Together, these feedbacks raise the equilibrium temperature response to ~3°C for CO₂ doubling (climate sensitivity). The large uncertainty (2.5–4°C) is driven primarily by cloud feedbacks — which remain the most uncertain element of climate science.

**The enhanced greenhouse effect today.** The industrial-era increase in greenhouse gas concentrations has measurably altered Earth's radiation budget. Satellites detect less IR escaping to space at the specific wavelengths absorbed by CO₂ and CH₄ — direct observational evidence that greenhouse gases are trapping more energy. The downwelling longwave radiation measured at the surface has increased. These are not inferences from models; they are direct atmospheric measurements. The current ~+3.0 W m⁻² forcing has already produced ~1.2°C of global mean warming above pre-industrial levels (2023), and the system is still adjusting — additional warming of ~0.5°C is already "committed" even if emissions stopped today, because the ocean's large heat capacity means the surface has not yet fully warmed to its equilibrium level.`,
      cards: [
        {
          name: 'Greenhouse Gas Physics',
          icon: Sun,
          color: BRAND.gold,
          desc: 'GHGs absorb IR via molecular vibrations that change dipole moment: CO₂ (15 μm, bending mode), H₂O (6.3 μm and rotation bands, broadband), CH₄ (7.7 μm), N₂O (7.8 and 17 μm). N₂ and O₂: symmetric diatomics, no IR absorption. Re-emission is isotropic: ~50% back toward surface (downwelling IR), ~50% toward space. Surface must warm until it emits enough IR to close the energy budget despite greenhouse trapping.',
          examples: 'Atmospheric window: 8–12 μm, where atmosphere is relatively transparent → heat escapes to space. CO₂ and H₂O absorption features visible from space in satellite spectra. Clear nights: GHE reduced without clouds → frost more likely (radiative cooling to space through partially open window)',
        },
        {
          name: 'Radiative Forcing Values (2023)',
          icon: Wind,
          color: BRAND.accent,
          desc: 'CO₂: +2.2 W m⁻² (dominant driver, up from 0). CH₄: +0.5 W m⁻². N₂O: +0.2 W m⁻². Halocarbons: +0.4 W m⁻². Land use (albedo change): −0.15 W m⁻². Aerosols (sulfate, organic): −1.0 to −2.0 W m⁻² (cooling offset). Solar variability: +0.05 W m⁻² (small). Net anthropogenic forcing: ~+3.0 W m⁻². Resulting warming so far: ~+1.2°C. Committed additional: ~+0.5°C.',
          examples: 'Pinatubo 1991: −3–5 W m⁻² forcing, caused 0.5°C cooling over 1–3 years (short-lived aerosol) · 1.5°C Paris target corresponds to ~+2.7 W m⁻² total anthropogenic forcing · Arctic amplification: polar regions warming 3–4× faster due to ice-albedo and lapse rate feedbacks',
        },
        {
          name: 'Feedbacks and Climate Sensitivity',
          icon: Globe,
          color: BRAND.jade,
          desc: 'Without feedbacks: 2×CO₂ → +1°C (Planck feedback only). With all feedbacks: ~+3°C equilibrium climate sensitivity (ECS). Water vapour feedback: +~1°C (doubling alone). Ice-albedo feedback: +0.3°C. Lapse rate: positive at poles, negative in tropics (complex). Cloud feedback: still uncertain, likely slightly positive overall. IPCC AR6 ECS likely range: 2.5–4°C, best estimate 3°C. Uncertainty: primarily cloud feedbacks.',
          examples: 'Past climate evidence: last glacial maximum (~7 W m⁻² forcing from ice + CO₂) produced ~5–6°C global cooling → consistent with ~3°C/doubling · Paleocene-Eocene Thermal Maximum (PETM 56 Ma): rapid carbon injection → +5–8°C in <20,000 yr · Transient climate response (TCR): ~1.8°C — faster response, measured at time of CO₂ doubling before full equilibrium',
        },
      ],
    },
    {
      type: 'quiz',
      questions: [
        {
          q: "Water vapour is a more powerful greenhouse gas than CO₂ — it absorbs more infrared radiation across a wider range of wavelengths. Yet climate scientists consider CO₂, not water vapour, to be the master regulator of Earth's climate. Why?",
          a: [
            "CO₂ is more abundant than water vapour in the atmosphere, so despite its lower per-molecule absorption strength, the total CO₂ greenhouse contribution exceeds that of water vapour; reducing CO₂ is therefore more impactful than reducing water vapour",
            "Water vapour concentration is set by temperature — a warmer atmosphere holds more, a cooler one less (Clausius-Clapeyron relation). CO₂ persists in the atmosphere for centuries regardless of temperature. CO₂ therefore acts as the primary forcing: changes in CO₂ force temperature changes, which then amplify via water vapour feedback; water vapour amplifies but cannot initiate climate change on its own",
            "CO₂ absorbs radiation in the 8–12 μm 'atmospheric window' where water vapour does not, so CO₂ is uniquely positioned to trap energy that would otherwise escape; water vapour is redundant because its absorption bands are already saturated",
            "Atmospheric water vapour is removed by precipitation on a timescale of days, so even large increases in evaporation would not produce lasting atmospheric water vapour increase; CO₂, by contrast, lacks a rapid removal mechanism, allowing its atmospheric concentration to be easily altered",
          ],
          correct: 1,
          explain: "CO₂ is not more abundant than water vapour (A) — water vapour ranges 0–4% of the atmosphere, while CO₂ is only ~0.042% (422 ppm); H₂O is indeed more abundant and contributes roughly twice as much to the total greenhouse effect. CO₂ does not primarily absorb in the 8–12 μm window (C) — its main absorption band is centred near 15 μm, and the atmospheric window is indeed a gap in water vapour absorption; CO₂ absorption near 15 μm does interact with the window edge, but the framing is incorrect. While D correctly notes the short residence time of water vapour (~9 days), it incorrectly concludes that increased evaporation wouldn't increase atmospheric water vapour — it does, because the additional vapour is sustained by continuing evaporation as long as temperatures remain elevated. The correct answer is B: CO₂ concentration is controlled by geological and biological processes on long timescales (volcanic outgassing, weathering, ocean chemistry) and by human emissions on short timescales; it is not removed by temperature changes alone. Water vapour, however, is tightly coupled to temperature: if the planet warms, evaporation increases and the atmosphere holds more water vapour, amplifying the warming; if the planet cools, water vapour condenses out, reducing the greenhouse effect. This means water vapour cannot sustain elevated concentrations independently of temperature — it is a dependent variable. CO₂ is the independent variable: change CO₂, and temperature changes, which then changes water vapour. Water vapour is a powerful amplifier (roughly doubling the direct CO₂ warming) but not an initiator.",
        },
        {
          q: "A volcanic eruption injects 20 million tonnes of sulfur dioxide (SO₂) into the stratosphere, where it forms sulfate aerosols that persist for 2–3 years. Meanwhile, industrial emissions continue adding CO₂ to the atmosphere. How do the climate effects of these two forcings differ in magnitude, sign, and duration?",
          a: [
            "Both forcings produce warming — aerosols warm the stratosphere by absorbing solar radiation, and CO₂ warms the troposphere by absorbing infrared; the two effects are additive, and a major volcanic eruption would accelerate climate warming in the short term",
            "The volcanic aerosol forcing is strongly negative (cooling, −3 to −5 W m⁻²) but short-lived (2–3 year aerosol lifetime in the stratosphere, after which it settles out); CO₂ forcing is positive (warming, currently +2.2 W m⁻² for the industrial increase so far) and extremely long-lived (CO₂ persists for centuries to millennia); volcanoes produce short-term cooling punctuations while CO₂ drives long-term warming trend",
            "Volcanic aerosols and CO₂ both have positive radiative forcing effects, but the aerosol effect is larger and shorter; the large aerosol forcing temporarily overwhelms CO₂ warming, causing net cooling for several decades after a major eruption before CO₂ warming resumes",
            "Major volcanic eruptions and CO₂ emissions cancel each other out through a geochemical feedback: the SO₂ injected by volcanoes reacts with atmospheric CO₂ to form carbonates that precipitate out of the atmosphere, reducing both the sulfur aerosol and CO₂ burden simultaneously",
          ],
          correct: 1,
          explain: "Stratospheric aerosols (A) do warm the stratosphere (they absorb some IR from below and UV from above), but they produce net cooling at the surface because they primarily reflect incoming solar radiation; this is the opposite of warming, so the two forcings are not additive and certainly do not both warm the climate. Aerosol forcing is not positive warming (C) — it is negative (cooling); the statement is factually backwards. SO₂ does not react meaningfully with CO₂ in the atmosphere to form carbonates (D) — sulfate aerosols form from SO₂ + OH → H₂SO₄ (sulfuric acid); this reaction does not remove CO₂, and the quantities involved are incomparable: a Pinatubo-scale eruption (1991) injected ~20 Mt SO₂, while global CO₂ emissions are ~36,000 Mt CO₂/yr (9,800 Mt C/yr). The correct answer is B: stratospheric sulfate aerosols reflect incoming solar radiation, producing a negative (cooling) radiative forcing of −3 to −5 W m⁻² for a large eruption; this overwhelms the ongoing CO₂ forcing temporarily, producing 0.3–0.5°C global cooling as observed after Pinatubo (1991) and Tambora (1815, 'Year Without a Summer'). However, aerosols settle out of the stratosphere within 2–3 years, after which the cooling effect disappears entirely. CO₂, once emitted, persists in the atmosphere for 300–1,000 years; the forcing it produces is permanent on human timescales. Volcanoes are therefore irrelevant as a long-term counterbalance to CO₂ emissions — they provide temporary cooling punctuations that allow scientists to study climate sensitivity but do not offset the cumulative CO₂ forcing.",
        },
        {
          q: "The IPCC estimates that global average temperature would warm by approximately 3°C (equilibrium climate sensitivity) if CO₂ were to double from pre-industrial levels. However, the direct radiative forcing from CO₂ doubling alone would produce only ~1°C of warming. What accounts for the remaining ~2°C?",
          a: [
            "The remaining 2°C comes from the ocean heat uptake lag — the ocean absorbs heat slowly, so the atmosphere continues warming for decades after a forcing is applied; the 3°C estimate includes this future committed warming that has not yet occurred",
            "The additional 2°C comes from positive feedbacks that amplify the initial CO₂ forcing: primarily water vapour feedback (warmer air holds more H₂O, a potent greenhouse gas, roughly doubling the initial warming) and ice-albedo feedback (melting ice reduces reflectivity, increasing solar absorption); together these feedbacks amplify the initial ~1°C response to ~3°C",
            "The remaining 2°C reflects tipping point effects: at certain temperature thresholds, abrupt nonlinear changes in the climate system (permafrost thaw, Amazon dieback, AMOC collapse) release large additional amounts of greenhouse gases, producing extra warming beyond what physical feedbacks alone would predict; the 3°C estimate includes these tipping point contributions",
            "The remaining 2°C is produced by latent heat effects: as the climate warms, evaporation increases globally, releasing latent heat into the atmosphere when water vapour condenses in clouds and precipitation; this latent heat energy directly adds to the temperature above the initial CO₂ forcing",
          ],
          correct: 1,
          explain: "Ocean heat uptake lag (A) is real — the oceans slow the approach to equilibrium, and 'committed warming' means additional warming will occur even without further forcing; but ocean uptake does not create extra warming beyond equilibrium, it merely delays it. The equilibrium climate sensitivity of 3°C is the eventual equilibrium, not an overshoot due to lag. Tipping points (C) are a serious scientific concern at higher warming levels, but the ECS estimate of 3°C is derived from physical climate model feedbacks without including slow or abrupt tipping point responses; tipping points are considered additional risks beyond the ECS estimate, not included in it. Latent heat from condensation (D) is a genuine energy source within the atmosphere but represents energy transferred from the surface to the atmosphere by evaporation; it does not represent net additional energy input to the climate system — it is a redistribution of existing thermal energy. The correct answer is B: the ~1°C from the direct CO₂ radiative forcing is the 'Planck' response — the warming needed for the surface to emit enough additional IR to balance the 3.7 W m⁻² forcing, assuming everything else stays constant. But the climate system does not stay constant. The most important positive feedbacks are: (1) water vapour feedback — as the surface warms, more water evaporates, increasing atmospheric H₂O concentration, which is itself a powerful greenhouse gas, adding roughly +1.0–1.5°C; (2) ice-albedo feedback — warming melts snow and ice, reducing reflectivity, increasing solar absorption, adding ~+0.3°C in global mean; (3) lapse rate feedback (complex, slightly negative in tropics, positive at poles). These physical feedbacks together amplify the initial 1°C to approximately 3°C at equilibrium. This is why climate sensitivity cannot be much lower than ~2.5°C — these feedbacks are well-established physics, not speculative.",
        },
        {
          q: "Satellites measuring outgoing longwave radiation detect that Earth emits less infrared energy to space in the specific wavelength bands absorbed by CO₂ and CH₄ today compared to measurements made in the 1970s. Meanwhile, measurements at the surface show that downwelling longwave radiation has increased. What do these two independent observations together prove about the enhanced greenhouse effect, and why is this evidence more direct than temperature records alone?",
          a: [
            "These observations prove that the sun's output has decreased since the 1970s — less solar energy entering the system would cause less IR to be emitted at the specific CO₂ wavelengths; the increased surface downwelling radiation reflects the atmosphere compensating for reduced solar input by recycling more energy internally",
            "The reduction in outgoing IR at CO₂ and CH₄ wavelengths directly demonstrates that greenhouse gases are trapping more energy at those specific wavelengths — a fingerprint unique to the greenhouse mechanism; the simultaneous increase in surface downwelling longwave radiation confirms that this trapped energy is being re-emitted back toward the surface; together they constitute direct observational evidence of the enhanced greenhouse effect independent of surface temperature trends, which could in principle be influenced by other factors such as urban heat islands",
            "These measurements confirm that the atmosphere has become thicker and denser since the 1970s due to the accumulation of all air pollutants; a denser atmosphere absorbs more radiation at all wavelengths, including the CO₂ band, and also emits more back toward the surface; the effect is not specifically related to greenhouse gases but to the overall increase in atmospheric mass",
            "The reduction in outgoing IR at specific wavelengths simply reflects better satellite measurement precision; 1970s satellites could not accurately resolve the fine spectral structure of the CO₂ absorption band, so they overestimated outgoing radiation in those bands; modern instruments correctly measure lower values; there is no real change in outgoing radiation, only a correction of historical measurement error",
          ],
          correct: 1,
          explain: "Solar output changes (A) would affect all outgoing radiation broadly and would not produce a reduction specifically in the CO₂ and CH₄ absorption wavelengths; a weakening sun would reduce surface temperature and therefore reduce total IR emission, but the spectral pattern would not match the greenhouse fingerprint; in fact, solar output has been flat or slightly declining since 1980. Atmospheric mass has not measurably increased due to air pollutants — the mass of pollutants is trivial relative to the total atmospheric mass, and many pollutants are short-lived particulates, not gases that persist and thicken the atmosphere (C). Measurement artefacts (D) cannot explain both the satellite and surface observations simultaneously, and the satellite observations have been independently validated against radiative transfer models and against surface pyrgeometer measurements over decades. The correct answer is B: the spectral fingerprint of reduced outgoing IR in specific wavelength bands corresponding to CO₂ (~15 μm) and CH₄ (~7.7 μm) is a unique signature of increasing greenhouse gas concentrations — no other forcing (solar changes, aerosols, land use) would produce this specific spectral pattern. Observations by the Nimbus-4 satellite in 1970 compared to later IRIS and AIRS data show precisely this reduction at CO₂ wavelengths, matching radiative transfer model predictions. The increase in downwelling longwave radiation at the surface, measured directly by pyrgeometers at monitoring stations, demonstrates that the trapped energy is indeed being re-emitted toward the surface as the greenhouse mechanism requires. This two-sided observational confirmation — less IR escaping to space and more IR arriving at the surface in the exact predicted spectral bands — is more diagnostic than global mean temperature trends alone because it specifically identifies the physical mechanism responsible for the energy imbalance.",
        },
      ],
    },
  ],
}

export default greenhouseEffect
