import { Wind, Globe, Sun } from 'lucide-react'
import { BRAND } from '@/lib/brand'
import type { Lesson } from './types'

const weatherPrediction: Lesson = {
  id: 'atmo-101-1-3-4',
  title: 'Numerical Weather Prediction and Forecasting',
  track: 'atm',
  trackName: 'Meteorology',
  level: 'Beginner',
  duration: '12 min',
  xpReward: 140,
  description: "Modern weather forecasting is one of humanity's greatest computational achievements — transforming the atmosphere from an unpredictable mystery into a system we can reliably predict days in advance by applying physics, mathematics, and the power of Earth observation.",
  sources: [
    { org: 'NOAA',     title: 'National Centers for Environmental Prediction',              url: 'https://www.ncep.noaa.gov/' },
    { org: 'ECMWF',    title: 'European Centre for Medium-Range Weather Forecasts',         url: 'https://www.ecmwf.int/' },
    { org: 'OpenStax', title: 'Introduction to Atmospheric Science, Ch. 11 (CC-BY 4.0)',  url: 'https://openstax.org/books/introduction-oceanography' },
    { org: 'UCAR',     title: 'History of Weather Forecasting',                            url: 'https://scied.ucar.edu/learning-zone/weather' },
    { org: 'WMO',      title: 'World Meteorological Organization — Weather Prediction',    url: 'https://public.wmo.int/en' },
  ],
  sections: [
    {
      type: 'intro',
      title: 'Predicting the chaotic atmosphere',
      body: `In 1950, the first numerical weather forecast was computed on the ENIAC — the world's first general-purpose electronic computer — by a team that included the mathematician John von Neumann and meteorologist Jule Charney. The calculation took 24 hours of computation to produce a 24-hour forecast, and the forecast was crude compared to modern standards. Today, the European Centre for Medium-Range Weather Forecasts (ECMWF) produces a 10-day global forecast that is more accurate than a 24-hour forecast was in 1980, using a computer that performs quintillions of calculations per second. This is one of the most remarkable improvements in scientific prediction in human history.

Modern **numerical weather prediction (NWP)** is based on a simple but profound idea: the atmosphere obeys the laws of physics, and if we know its state at one moment (the initial conditions) and the governing physical laws, we can mathematically compute its future state. The governing equations — conservation of momentum, energy, and mass, combined with the equation of state for moist air — are well known. The challenge is that: (1) the initial conditions can never be perfectly observed; (2) the atmosphere is a chaotic system in which small initial errors grow exponentially over time, making forecasts inherently limited beyond about 2 weeks; and (3) processes smaller than the model grid (microphysics, turbulence) must be approximated (**parameterised**). These three challenges — observation, chaos, and parameterisation — define the frontier of modern meteorological science.

Despite these limitations, modern NWP is extraordinarily useful. 5-day forecasts are now as accurate as 3-day forecasts were in the 1980s. **Ensemble forecasting** — running dozens of slightly different model simulations to capture the range of possible outcomes — provides explicit uncertainty information alongside the forecast itself. Probabilistic forecasting (70% chance of rain) rather than binary yes/no prediction allows people and organisations to make better decisions under uncertainty. Weather forecasting saves tens of thousands of lives per year through hurricane evacuation orders, tornado warnings, winter storm alerts, and aviation hazard avoidance — making NWP one of the most societally valuable scientific endeavours in history.`,
      keyTerms: [
        { term: 'Numerical weather prediction (NWP)', def: 'The use of mathematical models of the atmosphere, solved numerically on computers, to produce weather forecasts. Atmospheric state is represented on a three-dimensional grid; the governing equations are integrated forward in time. Modern global NWP models run at resolutions of 5–10 km, with time steps of minutes. Key centres: ECMWF (Europe), NCEP/GFS (US), UKMET (UK), DWD (Germany).' },
        { term: 'Initial conditions',   def: 'The state of the atmosphere at the start of a forecast — temperatures, winds, moisture, and pressure on the model grid. Assembled through data assimilation, which blends all available observations (radiosondes, satellites, aircraft, ships, surface stations, radar) with the previous model output to create the best possible three-dimensional analysis. Errors in initial conditions are the primary source of forecast error on short time ranges.' },
        { term: 'Data assimilation',    def: 'The mathematical process of optimally combining model state estimates (background field) with new observations to produce an analysis (initial conditions for the next forecast). Modern systems (4D-Var, EnKF) account for observation errors, model errors, and the correlations between variables. Satellite data now dominates: ~90% of observations ingested into global NWP models come from satellites.' },
        { term: 'Chaos and the butterfly effect', def: 'The atmosphere is a chaotic dynamical system: infinitesimally small perturbations in initial conditions grow exponentially over time, eventually making the forecast completely unreliable. The fundamental predictability limit of weather is approximately 2–3 weeks. This is not a limitation of computing power or model quality — it is an intrinsic property of the atmosphere as described by chaos theory. Named after Edward Lorenz\'s 1963 discovery.' },
        { term: 'Ensemble forecasting', def: 'Running many (20–50+) slightly different model simulations from perturbed initial conditions or different parameterisation schemes, to produce a probability distribution of forecast outcomes rather than a single deterministic forecast. The spread among ensemble members reflects forecast uncertainty: tightly clustered ensembles = high confidence; widely spread = low confidence. ECMWF\'s Ensemble Prediction System (EPS) uses 51 members.' },
      ],
    },
    {
      type: 'concept',
      title: 'NWP principles, observing systems, and forecast products',
      body: `**The governing equations of the atmosphere.** Numerical weather prediction is possible because the atmosphere obeys well-established physical laws. The governing equations include: (1) the **equations of motion** (Newton's second law applied to a rotating Earth, giving the horizontal momentum equations with pressure gradient force, Coriolis force, friction); (2) **thermodynamic energy equation** (first law of thermodynamics — accounting for compression, expansion, radiation, and latent heat); (3) **continuity equation** (conservation of mass); (4) **water vapour equation** (conservation of moisture, including phase changes); (5) **equation of state** (ideal gas law relating pressure, temperature, and density). These six equations in six unknowns (u, v, w wind components; T temperature; ρ density; q specific humidity) are solved numerically on a grid covering the globe (or a limited regional domain). The model atmosphere is updated in time steps of minutes, effectively "running" the atmosphere forward in time at accelerated speed.

**The global observing system.** The NWP model initial conditions are assembled from a vast global observation network. **Radiosondes** (weather balloons) are released twice daily (00Z and 12Z) from ~900 stations worldwide, measuring temperature, humidity, and wind at all altitudes from the surface to ~30 km. **Satellite observations** now dominate global NWP data: polar-orbiting satellites (NOAA, MetOp, Suomi-NPP, JPSS) provide temperature, humidity, and wind soundings globally; geostationary satellites (GOES-East/West, Meteosat, Himawari) provide continuous cloud motion and water vapour imagery at 15-minute intervals over wide areas. **Weather radar** networks (NEXRAD in the US, OPERA in Europe) provide high-resolution precipitation and wind data within ~460 km of each station. **Aircraft** (AMDAR — Aircraft Meteorological Data Relay) report temperature and wind at cruise altitude automatically. **Surface stations**, ships, ocean buoys, and GPS sensors fill out the observing network. Approximately 10 million observations per day are assimilated into global NWP models.

**Forecast skill and its limits.** Modern NWP has improved dramatically: ECMWF's 7-day forecast of Northern Hemisphere large-scale flow is now as accurate as its 5-day forecast was in 1980. This improvement comes from better models (higher resolution, improved physics parameterisations), more satellite observations, and better data assimilation. However, forecast skill degrades with time due to chaos, and different weather phenomena have different predictability horizons. Large-scale phenomena (blocking patterns, major hurricane tracks) can be predicted up to 2 weeks in advance. Midlatitude cyclone track and intensity: 5–7 days. Precipitation location and amount: 3–5 days. Thunderstorm initiation: 0–24 hours. Tornado formation: 0–30 minutes (after the parent supercell is identified). These are fundamental limits, not technological failures, and improving predictability beyond the 2-week horizon requires understanding longer-term seasonal phenomena (ENSO, Arctic Oscillation, Madden-Julian Oscillation).

**Ensemble forecasting and probabilistic prediction.** The ensemble approach, pioneered in the early 1990s at ECMWF and NCEP, represents a conceptual breakthrough in weather forecasting. Rather than treating the atmosphere as a deterministic system that can be predicted exactly, ensemble forecasting acknowledges intrinsic uncertainty and quantifies it. Ensemble members are created by slightly perturbing the initial conditions within their estimated uncertainty bounds. Regions where ensemble members diverge rapidly (high spread) indicate areas of low predictability; where they remain clustered, the forecast is robust. The probabilistic outputs of ensemble systems — probability of precipitation exceeding a threshold, probability of wind exceeding a damaging threshold, probable hurricane track envelope — are directly actionable for emergency management, aviation routing, and energy demand forecasting. Modern forecast products from national weather services increasingly present probabilistic information to users rather than deterministic "point" forecasts.`,
      cards: [
        {
          name: 'How NWP Models Work',
          icon: Wind,
          color: BRAND.accent,
          desc: 'Six governing equations (momentum, thermodynamics, continuity, moisture, equation of state) solved numerically on 3D global grid. Global models: ECMWF IFS (~9 km), GFS (~13 km), ICON (~13 km). Regional: NAM, RAP/HRRR (3 km US). Time step: 5–10 minutes. Forecast runs: 4× daily at 00Z, 06Z, 12Z, 18Z using latest observations. ECMWF runs on one of the world\'s fastest supercomputers (>5 PetaFLOPS). 10-day global forecast: ~30 minutes to compute.',
          examples: 'ECMWF ensemble: 51 members, 15-day forecast. GFS: US model, free public access, 16-day. Spaghetti plots: ensemble tracks of a hurricane, showing the "cone" of uncertainty. Model "upgrade cycles": ECMWF improves model every 6 months; each upgrade saves ≈1 forecast day in skill',
        },
        {
          name: 'The Observing System',
          icon: Globe,
          color: BRAND.jade,
          desc: 'Radiosondes: 900 stations × 2 launches/day = ~1,800 vertical profiles/day (still backbone of NWP validation). Satellites: 90% of NWP observations; polar sounders (temperature/humidity profiles), geostationary imagery (cloud/wind). NEXRAD: 160 Doppler radars cover CONUS at 460 km range. Aircraft (AMDAR): 10,000s of obs/day at cruise altitude. Surface: 10,000+ ASOS stations, ocean buoys, GPS precipitable water. Total: ~10 million obs/day assimilated globally.',
          examples: 'Observing system experiments: removing all satellite data degrades 5-day GFS forecast to 2.5-day quality · GOES-16 (2016): 5× faster, 4× higher resolution than previous generation → dramatic hurricane intensity improvements · Dropsonde: GPS sonde dropped from aircraft through hurricane → critical eyewall observations for intensity forecasting',
        },
        {
          name: 'Chaos, Limits, and Ensemble Forecasting',
          icon: Sun,
          color: BRAND.gold,
          desc: 'Lorenz (1963): discovered chaos in simplified atmospheric equations; "butterfly effect" coined 1972. Predictability horizon: ~2 weeks for large-scale flow; 5–7 days for cyclone track; 3–5 days for precipitation; 0–24 hr for convective initiation. Cannot be extended by better computers — intrinsic chaos limit. Ensemble (1992–): 50 perturbed members → probability distribution of outcomes. Spaghetti ensemble tracks → "cone of uncertainty" for hurricane track.',
          examples: 'Lorenz attractor: iconic chaos figure, never repeats but stays in bounded phase space · Hurricane Sandy (2012): ECMWF ensemble predicted unprecedented left turn into NJ 7+ days in advance; GFS operational didn\'t; evacuations saved lives · Winter storm Jonas (2016): ensemble guidance correctly showed heavy Mid-Atlantic snowstorm 6 days in advance',
        },
      ],
    },
    {
      type: 'quiz',
      questions: [
        {
          q: "ECMWF's ensemble forecast for Hurricane Sandy (October 2012) showed a sharp left turn into New Jersey 7 days before landfall — a highly unusual track that the US GFS operational model initially failed to predict. Emergency managers had to decide whether to order evacuations based on a low-confidence ensemble signal. What is the physical meaning of ensemble spread in this context, and why does it provide actionable information even when spread is high?",
          a: [
            "Ensemble spread represents the range of possible model errors — a wide spread means the NWP model equations themselves have large errors; emergency managers should wait for the spread to narrow (model errors to be corrected) before acting; acting on a high-spread ensemble risks evacuating unnecessarily",
            "Ensemble spread represents the uncertainty in the atmospheric state that arises from imperfect initial conditions and chaotic error growth; even when spread is high, the ensemble provides probability information: if 80% of 51 ensemble members show a dangerous track and 20% show a less dangerous track, emergency managers can weigh the probability of the dangerous scenario against the cost of evacuation; a high-spread ensemble indicating a 40–60% probability of catastrophic impact demands action — the potential consequences dominate the probability",
            "A high-spread ensemble indicates that the numerical model has failed to converge on a solution; in this case, forecasters should ignore the ensemble and rely instead on older statistical climatology (historical hurricane track records) until the ensemble spread narrows; ensemble divergence is a signal of model breakdown, not forecast uncertainty",
            "Ensemble spread represents weather variability, not forecast uncertainty; high spread means the actual weather is expected to be highly variable day-to-day in the week ahead; it has no direct bearing on whether any specific track scenario is likely; managers should plan for average hurricane-track climatology rather than ensemble outlier tracks",
          ],
          correct: 1,
          explain: "Ensemble spread does not represent NWP equation errors (A) — the ensemble members all use the same equations (or very similar ones) and the spread comes from perturbed initial conditions, not from errors in the physics; waiting for spread to narrow means waiting until the event is nearly upon you, forfeiting the lead time that made the ensemble valuable. Model failure to converge (C) misunderstands ensemble methodology — the ensemble members do not attempt to converge on a single solution; they are designed to sample the space of possible atmospheric evolutions from slightly different starting points; divergence is the signal, not a failure. Ensemble spread as 'weather variability' (D) fundamentally misidentifies what an ensemble represents — each ensemble member is a complete forecast of the most probable single weather evolution starting from a slightly different atmospheric state, not a forecast of daily variability; the ensemble represents uncertainty in the deterministic forecast, not natural weather variability. The correct answer is B: the ensemble's physical meaning is that the atmosphere could legitimately evolve into any of the 51 (or however many) ensemble scenarios, each of which is equally consistent with available observations given their uncertainty. High spread means the atmosphere is sensitive to initial condition uncertainty — small changes in initial state produce very different outcomes. This does not mean the ensemble is wrong; it means the atmosphere is in a regime of high predictive uncertainty. For decision-making, what matters is the probability distribution: if even 20–30% of ensemble members show catastrophic impact, the expected value of pre-emptive action (evacuation, resource pre-positioning) typically exceeds the expected value of waiting. Hurricane Sandy caused ~$65 billion in damage and killed 233 people; even a 30% ensemble probability of that scenario justified aggressive preparedness. The ECMWF Sandy case is now a textbook example of the societal value of probabilistic forecasting.",
        },
        {
          q: "Numerical weather prediction has a fundamental predictability limit of approximately 2 weeks, beyond which forecast errors grow to the point where the forecast is no better than climatology. This limit is not a consequence of insufficient computing power or imperfect models. What is the underlying physical reason, and does this mean weather beyond 2 weeks is fundamentally unpredictable?",
          a: [
            "The 2-week predictability limit is caused by the finite speed of weather systems moving around the globe; beyond 2 weeks, a weather system would have circled the globe and interacted with itself, creating feedback loops that no model can capture; improving computing power could extend this limit by more accurately tracking long-range interactions",
            "The atmosphere is a chaotic dynamical system in which arbitrarily small errors in the initial state grow exponentially over time at a rate determined by the Lyapunov exponents of the system; this is not a measurement or computing limitation — it is an intrinsic mathematical property of the equations governing the atmosphere; beyond ~2 weeks, weather forecasting (day-by-day specifics) is inherently limited. However, predictability of longer-term statistics (seasonal anomalies, climate regimes) remains possible because some components of the climate system (ocean temperatures, snow cover) evolve slowly and influence the atmosphere's average state over months",
            "The 2-week predictability limit arises because current NWP models run at too coarse a resolution to capture the small-scale processes (turbulence, convection) that feed back on large-scale flow; with sufficient computing power to resolve all scales down to millimetres, forecast skill could be extended indefinitely; the limit is computational, not physical",
            "The predictability limit exists because weather balloons only cover ~900 locations globally; the vast unobserved regions of the atmosphere (especially the Southern Hemisphere oceans) introduce gaps in initial conditions that grow into forecast errors; the solution is more radiosondes, which would extend predictability to a month or more",
          ],
          correct: 1,
          explain: "Weather systems circling the globe (A) is not the source of the 2-week predictability limit; weather systems typically take days to weeks to traverse ocean basins but do not 'interact with themselves' in the way described; this mischaracterises atmospheric dynamics. Insufficient model resolution (C) is partially correct in that coarser resolution degrades skill, but even a perfect model with perfect resolution and perfect observations would still face the intrinsic chaos limit; Lorenz's mathematical analysis showed that the predictability horizon is set by the Lyapunov exponent (the rate of error growth), not by model quality; with infinite resolution and perfect physics, the limit would perhaps extend by days, not weeks. More radiosondes (D) would help reduce initial condition errors, but the point of chaos is that errors grow exponentially regardless of their initial magnitude; even if initial conditions were known to 99.99% accuracy (a 100× improvement on today), the forecast would still become useless by about 2 weeks because the remaining 0.01% error would double repeatedly until it dominates the signal. The correct answer is B: Edward Lorenz demonstrated in 1963 that simplified atmospheric equation systems exhibit sensitive dependence on initial conditions — arbitrarily small differences in starting states produce completely different long-term trajectories. This is deterministic chaos: the system is fully deterministic (no randomness in the equations) but practically unpredictable beyond a finite time horizon because perfect knowledge of initial conditions is physically impossible. The Lyapunov exponent of the atmosphere implies a doubling time for errors of approximately 2 days; after ~2 weeks (roughly 7 doublings), errors have grown to the climatological scale of variability, and the forecast provides no more information than knowing the climatological average. The crucial nuance is that longer-term statistics can still be predicted because the ocean, land surface, and sea ice evolve slowly and provide a boundary condition that influences the atmosphere's average properties over weeks to seasons — enabling seasonal climate forecasting even where daily weather prediction fails.",
        },
        {
          q: "In the 1950s, forecasting a 3-day weather forecast required a team of expert meteorologists several hours to produce, and it was often only marginally better than persistence (assuming tomorrow will be like today). Today, a computer generates a 7-day forecast in 30 minutes that is more accurate than the 1950s 3-day forecast. What specific technical advances made this improvement possible?",
          a: [
            "The primary advance was the development of weather satellites in the 1960s; before satellites, forecasters had almost no information about conditions over the ocean; with satellite coverage, the initial conditions became nearly perfect, and the improvement in forecast skill is almost entirely due to better initial conditions rather than better models or computers",
            "Three compounding advances drove modern NWP skill: (1) exponentially increasing computing power enabling higher resolution models that explicitly resolve mesoscale weather features rather than parameterising them; (2) the satellite observation revolution providing near-global coverage every 15 minutes, improving initial conditions especially over data-sparse oceans; and (3) improved data assimilation methods (4D-Var, ensemble Kalman filter) that more optimally blend observations with model background fields; all three components together — better models, better observations, better assimilation — compound to produce the overall improvement",
            "The main advance was the development of Doppler radar in the 1980s; Doppler radar provides detailed wind and precipitation information within 460 km of each station; before radar, forecasters had no way to track the movement and intensity of storm systems in real time; radar data now constitutes the majority of observations ingested into NWP models",
            "The improvement is primarily due to better meteorological theory; in the 1950s, physicists had not yet derived the correct equations governing atmospheric motion; the development of quasi-geostrophic theory, moist convection parameterisations, and boundary layer schemes in the 1960s–1980s provided the mathematical framework for accurate NWP; computing power was already sufficient in the 1950s, but the models were physically wrong",
          ],
          correct: 1,
          explain: "Satellites alone (A) cannot explain the full improvement — satellite coverage has been excellent since the 1970s and continues to improve, but forecast skill has improved continuously even as satellite coverage reached near-global saturation; model resolution and assimilation improvements continued to drive skill gains independent of additional satellite observations. Doppler radar (C) is valuable for short-range (nowcasting) forecasts but constitutes a tiny fraction of global NWP observation input; Doppler radar is used primarily for mesoscale weather monitoring, not for global model initial conditions. Physics improvements (D) are part of the story, but the claim that computing power was 'already sufficient in the 1950s' is false — ENIAC computed a 24-hour forecast in 24 hours of machine time; modern forecasts require compute capacity many orders of magnitude beyond 1950s capability, and the resolution improvements from increased computing power are a major driver of skill. The correct answer is B: the improvement in NWP skill since the 1950s reflects the compounding of three distinct technical domains. (1) Computing power: the number of calculations per second in NWP centres has increased by ~12 orders of magnitude since ENIAC, enabling model resolution to improve from ~600 km to ~9 km globally, explicitly resolving weather systems that were previously parameterised. (2) Observations: weather satellites began in 1960, and today provide microwave sounder profiles of temperature and humidity globally every few hours; GPS radio occultation provides high-accuracy atmospheric profiles; aircraft and buoy networks expanded dramatically; the data volume ingested has grown from millions to billions of observations per day. (3) Data assimilation: 4D-Var (four-dimensional variational assimilation) and ensemble Kalman filter methods, developed in the 1990s–2000s, far more optimally combine heterogeneous observations with model backgrounds than earlier methods. Each advance multiplied the gains from the others — higher resolution is worthless without observations to initialise it; better observations are wasted without good assimilation; better assimilation of poor observations yields limited gains.",
        },
        {
          q: "NWP models require parameterisation — simplified mathematical representations of physical processes too small to be resolved on the model grid, such as individual convective clouds, turbulence, and cloud microphysics. Why is parameterisation both unavoidable in global NWP and a significant source of forecast error, and what approach do modern centres use to partially account for the uncertainty it introduces?",
          a: [
            "Parameterisation is used only because of cost constraints; if NWP centres had unlimited computing budgets, they would resolve all physical processes explicitly at the molecular scale; the forecast errors from parameterisation are purely a resource problem and will disappear as computers become powerful enough to eliminate parameterisation entirely",
            "Parameterisation is unavoidable because the computationally feasible grid spacing of global models (5–13 km) is much larger than the scale of the processes being parameterised (individual clouds: 0.1–5 km; turbulent eddies: metres to hundreds of metres); parameterisation introduces forecast error because the simplified bulk representations of these processes cannot perfectly capture the timing, intensity, and spatial distribution of convection, boundary layer mixing, and microphysics; modern centres use **stochastic parameterisation schemes** and **multi-physics ensembles** — running ensemble members with different parameterisation choices — to sample the uncertainty introduced by parameterisation alongside the uncertainty from initial conditions",
            "Parameterisation errors are negligible compared to initial condition errors in determining forecast accuracy; parameterisation schemes have been so thoroughly validated against observations that they introduce no systematic bias; the remaining NWP forecast error is entirely attributable to unobserved initial conditions, not to parameterisation choices",
            "Parameterisation is used specifically for precipitation processes, which are the only sub-grid phenomenon in NWP; all other atmospheric processes (large-scale wind, temperature, pressure) are resolved explicitly at the model grid scale; improving precipitation parameterisation would therefore eliminate most remaining NWP forecast error",
          ],
          correct: 1,
          explain: "The claim that parameterisation is purely a resource problem resolvable by unlimited computing power (A) is incorrect for global NWP — even if a global model could resolve individual clouds at 100 m resolution, turbulent eddies (centimetres to metres) and molecular diffusion would still need to be parameterised; the scale gap between the finest resolved processes and the fundamental physics is not bridgeable by any foreseeable computer; additionally, the atmosphere is fundamentally stochastic at small scales, so exact deterministic representation at all scales is theoretically impossible. Parameterisation errors are not negligible (C) — ECMWF research consistently shows that parameterisation uncertainty accounts for a substantial fraction of medium-range forecast error, particularly for precipitation and boundary layer properties; systematic biases in convective parameterisation are documented in all global models, and removing data assimilation while keeping perfect initial conditions still produces large forecast errors after a few days due to parameterisation drift. Only precipitation processes are not parameterised (D) is false — boundary layer mixing and turbulence, radiation (sub-grid cloud fraction, aerosol), microphysics in grid-scale clouds, orographic drag from sub-grid terrain, and convection (in global models) all require parameterisation; these processes collectively account for the majority of sub-grid physical process representation in NWP. The correct answer is B: global NWP models run at 5–13 km grid spacing because resolving smaller scales globally would require ~100–1,000× more computing power per halving of grid spacing (3D scaling), which is not currently feasible for operational real-time forecasting. But critical weather-producing processes occur at scales far below this: individual convective cells (0.1–5 km), cloud microphysics (millimetres to micrometres), and boundary layer turbulence (metres to tens of metres) must all be represented through bulk statistical relationships (parameterisations) that estimate their aggregate effect on the grid-scale variables. These approximations are validated but imperfect, and different physically plausible parameterisation choices produce different forecast outcomes. Modern centres address this by: (1) running ensemble members with different stochastic perturbations to parameterisation tendencies (SPPT: stochastic perturbation of parameterised tendencies) to sample parameterisation uncertainty; (2) using multi-physics ensembles with different convection or boundary layer schemes; both complement the initial-condition perturbation approach and improve the ensemble's representation of total forecast uncertainty.",
        },
      ],
    },
  ],
}

export default weatherPrediction
