import { Wind, Globe, Sun } from 'lucide-react'
import { BRAND } from '@/lib/brand'
import type { Lesson } from './types'

const thunderstorms: Lesson = {
  id: 'atmo-101-1-2-3',
  title: 'Thunderstorms and Severe Weather',
  track: 'atm',
  trackName: 'Meteorology',
  level: 'Beginner',
  duration: '12 min',
  xpReward: 140,
  description: "A thunderstorm is the atmosphere's most efficient engine — a self-sustaining heat engine that can release more energy in an hour than an atomic bomb. Understanding how storms form, intensify, and produce their most dangerous hazards is essential to understanding extreme weather.",
  sources: [
    { org: 'NOAA',     title: 'National Severe Storms Laboratory — Thunderstorm Basics',   url: 'https://www.nssl.noaa.gov/education/svrwx101/thunderstorms/' },
    { org: 'NOAA',     title: 'Storm Prediction Center',                                   url: 'https://www.spc.noaa.gov/' },
    { org: 'OpenStax', title: 'Introduction to Atmospheric Science, Ch. 9 (CC-BY 4.0)',   url: 'https://openstax.org/books/introduction-oceanography' },
    { org: 'UCAR',     title: 'Thunderstorms and Severe Weather',                          url: 'https://scied.ucar.edu/learning-zone/storms/thunderstorms' },
    { org: 'AMS',      title: 'Glossary of Meteorology',                                  url: 'https://glossary.ametsoc.org/' },
  ],
  sections: [
    {
      type: 'intro',
      title: 'Nature\'s most energetic weather',
      body: `A mature thunderstorm contains updrafts moving at 160 km/h or faster, ice crystals and raindrops in constant collision, electric charges building to billions of volts, and hailstones growing to the size of grapefruits. All of this is powered by a single, elegant mechanism: the release of latent heat when water vapour condenses into liquid droplets and freezes into ice. When conditions are right — warm, moist, unstable air beneath a dry, stable cap — the energy stored in atmospheric moisture is released explosively. Each square kilometre of a deep thunderstorm updraft releases heat energy comparable to a nuclear weapon per hour. At any given moment, there are approximately 2,000 thunderstorms in progress on Earth, and about 100 lightning bolts strike the ground every second.

Thunderstorms are not all alike. The vast majority are **ordinary cell thunderstorms** — short-lived, disorganised convective cells that form on summer afternoons, produce a brief rain shower and perhaps a few lightning bolts, and dissipate within an hour. But under specific conditions of atmospheric wind shear and instability, storms can organise into far more powerful and dangerous forms: **supercells** — rotating thunderstorms capable of producing large hail, destructive winds, and the most violent tornadoes on Earth — and **mesoscale convective systems (MCSs)** — organised clusters of storms that produce widespread damaging winds, heavy rainfall, and flash flooding over hundreds of kilometres.

The study of severe convective weather is both scientifically fascinating and practically critical. Severe thunderstorm and tornado warnings save lives, but accurate warnings require understanding the physical processes that distinguish a supercell from an ordinary storm within minutes of development. Modern Doppler radar networks, dense surface observation networks, and high-resolution numerical weather models have transformed severe weather meteorology from a largely reactive discipline (observing what storms do) to a predictive one (anticipating what conditions will produce which hazards before storms form).`,
      keyTerms: [
        { term: 'CAPE',           def: 'Convective Available Potential Energy — the amount of energy available to an air parcel that is lifted above the level of free convection (LFC); it is the primary measure of atmospheric instability. Units: J/kg. Values >1,000 J/kg are considered moderate; >2,500 J/kg are high; >5,000 J/kg are extreme. High CAPE environments support strong, sustained updrafts. CAPE is calculated from thermodynamic soundings (weather balloons).' },
        { term: 'Wind shear',     def: 'The change in wind speed or direction with altitude. Vertical wind shear is critical to thunderstorm organisation: weak shear allows only ordinary cells (updraft and downdraft interfere, storm short-lived); strong directional shear (wind rotating with height) creates the rotating updraft (mesocyclone) necessary for supercell formation and tornadogenesis.' },
        { term: 'Supercell',      def: 'An organised, long-lived (hours) thunderstorm characterised by a persistent, rotating updraft (mesocyclone). Responsible for the majority of significant tornadoes (EF2+), very large hail (≥5 cm), and extreme wind speeds. Requires high CAPE and strong directional wind shear. Can travel hundreds of kilometres, maintaining its rotating structure. The most dangerous thunderstorm type.' },
        { term: 'Tornado',        def: 'A violently rotating column of air extending from a thunderstorm cumulonimbus cloud to the ground. Enhanced Fujita (EF) scale: EF0 (65–85 mph) to EF5 (>200 mph). Most tornadoes are weak (EF0–EF1); EF4–EF5 tornadoes cause the vast majority of tornado fatalities. The path of destruction can be a few metres to over 1.5 km wide and hundreds of kilometres long.' },
        { term: 'Mesoscale convective system (MCS)', def: 'An organised complex of thunderstorms with a contiguous precipitation area ≥100 km in scale, including squall lines, bow echoes, and mesoscale convective complexes (MCCs). MCSs can persist 12+ hours, travel 1,000 km, and produce widespread damaging winds (derecho), large hail, and flooding rainfall. Responsible for a large fraction of warm-season rainfall in the US Great Plains.' },
      ],
    },
    {
      type: 'concept',
      title: 'Thunderstorm types, supercells, tornadoes, and lightning',
      body: `**The thunderstorm life cycle.** An ordinary (single-cell) thunderstorm progresses through three stages. In the **cumulus stage**, a thermal (rising bubble of warm moist air) reaches the lifting condensation level (LCL) — the altitude at which the air has cooled enough for condensation to begin — and a cumulus cloud forms. If the atmosphere is sufficiently unstable (CAPE is positive), the thermal continues to rise, releasing latent heat as water vapour condenses, warming the rising air relative to its surroundings, and becoming more buoyant. This positive feedback drives the cloud upward through the troposphere to the tropopause in the **mature stage**, forming the characteristic cumulonimbus with its towering top and anvil spreading at the tropopause. The mature stage is the most intense: strong updrafts (40–160 km/h) coexist with precipitation-laden downdrafts. In the **dissipating stage**, the downdraft spreads through the entire cloud, cutting off the inflow of warm moist air, and the storm weakens over 15–30 minutes.

**Supercell formation: the role of wind shear.** Ordinary cells dissipate quickly because their downdraft cuts off their inflow. A supercell avoids this self-destruction through **wind shear**. When wind direction rotates with altitude (e.g., southerly at the surface, westerly at 5 km, northwesterly at 10 km), horizontal vorticity — tubes of spinning air aligned horizontally by wind shear — is tilted into the vertical by the storm's updraft. The result is a **mesocyclone**: a rotating updraft that can be 5–10 km in diameter and persist for hours. The rotating updraft separates the updraft (on the southern or southeastern flank in the NH) from the downdraft (on the northern and western flanks), allowing the storm to sustain itself without the downdraft choking the inflow. Supercells can maintain this rotating structure for 3–6 hours and travel hundreds of kilometres. The rotating updraft is visible on Doppler radar as a characteristic velocity couplet (approaching and receding velocities adjacent to each other), which is how severe weather meteorologists identify supercells in real time.

**Tornadogenesis.** Tornadoes form when the rotating updraft of a supercell descends toward the surface in a process called **tornadogenesis** that is still not fully understood at a mechanistic level despite decades of research. The **hook echo** — a hook-shaped appendage on the southwestern side of a supercell's radar reflectivity pattern — indicates the location of the wall cloud and the most likely area of tornado formation. Research initiatives (VORTEX, VORTEX2, VORTEX-SE) have used mobile Doppler radar, instrumented vehicles, and balloon soundings deployed around supercells to document the temperature, wind, and pressure structure of tornadic and non-tornadic supercells. Key findings suggest that a pool of relatively cool, buoyant air in the rear-flank downdraft (RFD) region may be important for concentrating vertical vorticity near the surface into a tornado.

**Lightning physics.** A lightning bolt is an electrical discharge driven by charge separation within a cumulonimbus cloud. The prevailing mechanism involves collisions between **graupel** (soft hail or ice pellets, which become negatively charged) and **ice crystals** (which become positively charged): updrafts carry light ice crystals upward while graupel falls downward, separating the charges. Positive charges accumulate in the upper cloud, negative charges in the middle to lower cloud (though the charge structure is complex). When the electric field becomes large enough (~1 million V/m), the air ionises and a lightning bolt propagates — typically from the negative charge centre down toward the ground (negative cloud-to-ground lightning) or between charge centres within the cloud (intracloud lightning, ~70% of all lightning). The return stroke visible as a flash heats the air channel to ~30,000 K — five times hotter than the surface of the sun — expanding it explosively and producing thunder.

**Derechos and MCSs.** A **derecho** is a widespread, long-lived wind damage event produced by a mesoscale convective system — typically a bow echo (a bow-shaped squall line) — moving rapidly in the direction of the prevailing wind. Derecho winds at the surface can exceed 160 km/h (100 mph) over swaths hundreds of kilometres long and wide. Unlike tornadoes (which affect narrow paths for minutes), derechos can be as destructive as major hurricanes across broad areas and last for 6–12 hours. The June 2012 North American derecho, for example, caused widespread damage from Indiana to the Mid-Atlantic coast, killing 29 people and leaving 4 million without electricity.`,
      cards: [
        {
          name: 'CAPE, Shear, and Storm Type',
          icon: Wind,
          color: BRAND.accent,
          desc: 'CAPE: energy for updraft strength. <1000 J/kg: weak storms; 1000–2500: moderate; 2500–5000: strong; >5000: extreme. Wind shear: determines storm organisation. Low shear + high CAPE: ordinary cells (pulse storms), heavy rain. Moderate shear: multicell clusters. Strong directional shear + high CAPE: supercells (rotating, tornadoes, large hail). High shear + moderate CAPE: squall lines, derechos. CIN (Convective Inhibition): cap that prevents premature triggering; some CIN beneficial for intense storms.',
          examples: 'Tornado outbreak 3 April 1974 (Super Outbreak): 148 tornadoes, extreme CAPE + strong shear across central/eastern US · Ordinary summer afternoon storm: Florida sea breeze convergence, CAPE >2000, low shear → pulse storms, heavy rain, lightning · Derecho June 2012: fast-moving MCS, 400 km long, 100+ mph gusts from Indiana to Atlantic',
        },
        {
          name: 'Supercell Structure and Tornadoes',
          icon: Globe,
          color: BRAND.jade,
          desc: 'Supercell anatomy: flanking line (new cumulus on southern flank), wall cloud (lowered rotating cloud under mesocyclone base), hook echo (radar signature SW of main cell), forward flank precipitation, overshooting top (above anvil, marks most intense updraft). Tornado warning triggers: confirmed rotation on Doppler radar, hook echo, wall cloud sighted. EF scale: EF0 (minor damage) through EF5 (catastrophic, rare). EF5: complete destruction of well-built homes, cars thrown >100 m.',
          examples: 'Joplin, MO May 2011: EF5, 1.6 km wide, 158 deaths · El Reno, OK May 2013: widest tornado ever measured (4.2 km), EF5 vorticity · Tornado Alley (TX–KS–OK–NE): highest EF4–EF5 frequency globally due to cP/mT collision geography',
        },
        {
          name: 'Lightning and Thunder Physics',
          icon: Sun,
          color: BRAND.gold,
          desc: 'Charge separation: graupel (−) falls; ice crystals (+) rise; updraft separates them. CG (cloud-to-ground) lightning: ~30% of all lightning; stepped leader from cloud, return stroke from ground upward at ~10⁸ m/s; heats channel to 30,000 K. Thunder: explosive expansion of heated air; travels ~1 km per 3 seconds (speed of sound); audible to ~25 km. Ball lightning: rare, poorly understood. Lightning rods: Franklin (1752) established grounding principle.',
          examples: 'Global lightning rate: ~100 CG strikes/second · Keraunopathy: lightning strike injuries (cardiac arrest, neurological effects) — lightning kills ~2,000/yr globally · Lake Maracaibo, Venezuela: highest lightning flash rate on Earth (~250 flashes/km²/yr) from persistent nocturnal convection',
        },
      ],
    },
    {
      type: 'quiz',
      questions: [
        {
          q: "A weather balloon sounding on a spring afternoon over Oklahoma shows 4,000 J/kg of CAPE (very high) but also 500 J/kg of CIN (convective inhibition — the 'cap'). Meteorologists at the Storm Prediction Center issue a high-risk outlook for tornadoes. Why would high CIN coexist with a high-risk tornado outlook rather than preventing tornado development?",
          a: [
            "High CIN prevents all convection, so the high-risk outlook is an error; tornadoes cannot form when CIN is positive regardless of CAPE, and forecasters would cancel the outlook once they recognised the capping inversion",
            "High CIN is actually beneficial for severe storm potential because it prevents weak, disorganised convection from releasing CAPE prematurely; the cap allows instability to build to extreme levels; when a boundary (cold front, dryline, outflow boundary) eventually breaks the cap, the enormous stored CAPE is released explosively all at once, producing intense supercells rather than scattered ordinary storms",
            "CIN and CAPE have opposite effects that cancel; 4,000 J/kg of CAPE and 500 J/kg of CIN produce a net effective CAPE of 3,500 J/kg, which is simply used in the standard thunderstorm intensity calculation; the CIN has no qualitative effect on storm character, only on storm intensity",
            "The CIN is irrelevant once tornadoes begin forming because tornado rotation is self-sustaining; once the first tornado forms, its downdraft breaks the cap for surrounding cells, allowing rapid development of additional tornadoes regardless of the original CIN",
          ],
          correct: 1,
          explain: "High CIN absolutely does not prevent all convection in all scenarios (A) — it raises the threshold for convection initiation, but boundaries (cold fronts, drylines) provide enough forced lifting to overcome typical CIN values of 200–500 J/kg; the absence of CIN would actually lead to undesirable early pop-up convection. CIN and CAPE do not simply subtract from each other (C) — they represent different aspects of the thermodynamic profile and do not cancel in a simple arithmetic way; CIN is the energy needed to lift a parcel to its LFC, while CAPE is the energy available once the parcel is above the LFC. Tornado rotation does not break caps across broad areas for surrounding cells (D) — tornadic supercell outflow boundaries can help initiate new storms locally, but this is a secondary effect and does not explain the utility of CIN in the pre-storm environment. The correct answer is B: this is a fundamental principle of convective meteorology called the **loaded gun** sounding or **cap effect**. When CIN is present, the atmosphere is suppressed — weak surface thermals cannot break through the cap, so no ordinary convection forms, and CAPE continues to build through the afternoon as surface heating continues. Meanwhile, wind shear and other storm ingredients are also increasing. When a strong forcing mechanism (cold front, dryline) arrives and provides enough forced lifting to overcome the CIN, the stored CAPE is released all at once over a large area along the boundary. Instead of scattered ordinary pulse storms that would have popped up earlier without the cap, the result is a simultaneous explosive development of organised, severe supercells. The cap effectively concentrates the storm activity in time and space, producing the coordinated severe outbreak that forecasters recognise as a high-risk scenario.",
        },
        {
          q: "Doppler radar detects a supercell thunderstorm with a clear hook echo and a velocity couplet showing rotation in the mesocyclone at 3–8 km altitude. Fifteen minutes later, the storm produces an EF4 tornado on the ground. Explain the physical process by which the mesocyclone's rotation at altitude was extended to the surface to produce a tornado.",
          a: [
            "The tornado forms when the mesocyclone's rotating air mass descends from altitude to the surface under gravity; as the rotation descends, it accelerates by conservation of angular momentum (like a spinning skater pulling in their arms); the touchdown is complete when the rotating air column contacts the ground and raises dust and debris",
            "Tornadogenesis is driven by horizontal vorticity tilting: the rotating mesocyclone creates a pressure deficit that draws in surface air horizontally; this horizontal air stretches and tilts existing horizontal vorticity (from wind shear near the ground) into the vertical, creating a surface vortex that connects with the mesocyclone above to form the tornado",
            "The full tornadogenesis mechanism is not yet completely understood, but it appears to involve: downward extension of the rotating mesocyclone toward the surface, intensification of near-surface rotation through horizontal convergence (stretching of vertical vorticity, conserving angular momentum), and possibly the role of the rear-flank downdraft in creating a boundary of buoyant air at the surface that focuses the vorticity concentration; when this surface rotation intensifies enough to become visible, the tornado is 'born'",
            "The tornado forms by a straightforward vertical descent of the mesocyclone; the hook echo marks where the mesocyclone begins descending; the descent is driven by latent cooling from evaporation of rain in the rear-flank downdraft, which makes air dense enough to sink directly from cloud base to the surface, carrying its rotation with it",
          ],
          correct: 2,
          explain: "Option A describes a simplified version of the angular momentum argument that is partially relevant (convergence and stretching do spin up the vortex), but 'the rotating air mass descends under gravity' is an oversimplification — the mesocyclone does not simply fall to the ground like a solid object. Option B describes horizontal vorticity tilting — this is the process that creates the supercell's mesocyclone in the first place (earlier in the storm's development), not the subsequent tornadogenesis step; tornadogenesis involves vertical vorticity near the surface, not fresh tilting of horizontal vorticity. Option D is close but incomplete — the rear-flank downdraft (RFD) does appear important, but describing it as simply 'dense air sinking and carrying rotation' omits the critical convergence and vorticity stretching mechanisms. The correct answer is C: tornadogenesis is genuinely one of the less completely understood processes in meteorology. The current scientific understanding involves: (1) the mesocyclone's rotation at mid-levels (3–8 km) creates a low-pressure channel that draws near-surface air inward (convergence); (2) this convergence stretches the vertical vorticity near the surface (conservation of angular momentum: as the radius of rotation decreases, the spin rate increases, like a skater pulling in arms); (3) the rear-flank downdraft appears to play a role — perhaps by creating a boundary of buoyant air that focuses the vortex formation, or by wrapping cool air around the developing tornado; (4) when the surface spin rate becomes intense enough, the tornado becomes visible as the pressure deficit is sufficient to condense water vapour in the vortex. Multiple VORTEX field campaigns have documented that not all supercells with clear mesocyclones produce tornadoes, and the distinguishing factors are still an active research question.",
        },
        {
          q: "A squall line is producing dangerous straight-line winds of 100+ mph across a 600-km-wide swath, with no tornadoes detected. How does this derecho differ from a tornado outbreak in terms of the physical mechanism producing destructive winds, the area affected, and the warning system requirements?",
          a: [
            "A derecho and a tornado outbreak both produce winds through the same rotating mesocyclone mechanism; derechos simply have many more tornadoes than a typical outbreak, spread over a larger area; the higher wind speeds of a derecho result from the overlapping effect of multiple tornado circulations",
            "Derecho winds are straight-line (non-rotating) outflow winds produced by the cold downdraft pool of a fast-moving mesoscale convective system (bow echo); the downdraft air is accelerated by descent, evaporative cooling, and the rearward motion of the storm; destructive winds affect a broad swath (100s of km wide, 1,000s of km long) for hours; warning systems for derechos rely on radar identification of the bow echo signature and the momentum of the cold pool, not tornado rotation signatures",
            "Derechos and tornadoes produce identical wind damage because both involve rotating columns of air accelerated by angular momentum conservation; the area affected is similar, but derechos rotate more slowly and at larger scales, so the wind speed is spread over a wider area without the concentrated damage of a tornado vortex",
            "Derecho winds are produced by the jet stream temporarily descending to the surface behind the MCS; the jet stream provides an external energy source that sustains the surface winds independent of the thunderstorm dynamics; warning systems identify derechos by detecting jet stream descent on upper-air wind charts rather than radar",
          ],
          correct: 1,
          explain: "Derechos do not involve multiple tornado circulations (A) — by definition, a derecho is a straight-line wind event; tornadoes may occasionally accompany a derecho MCS but are not the primary wind-producing mechanism. Derechos do not involve rotating columns (C) — they involve horizontal, straight-line outflow; rotation (angular momentum) is specifically not the mechanism, which is what makes them different from tornadoes. Jet streams do not descend to the surface to produce derecho winds (D) — the jet is at ~10 km altitude; while the MCS is steered by the upper-level flow, the surface winds are produced by convective dynamics, not physical descent of the jet stream. The correct answer is B: a derecho is produced by the **cold pool** mechanism of a mesoscale convective system, specifically often a bow echo. As thunderstorm precipitation evaporates in the sub-cloud layer, it cools and loads the air with precipitation weight, creating a cold, dense pool of air at the surface. This cold pool spreads outward ahead of the storms like a gust front. When a line of storms organises into a bow echo (a bowed squall line moving quickly in the direction of the upper-level wind), the rear-inflow jet — a current of air flowing from behind the system at mid-levels — descends and is channelled toward the surface by the cold pool dynamics, accelerating winds along the forward edge of the bow. The result is a coherent swath of damaging straight-line winds that can span hundreds of kilometres in width and persist for 6–12 hours. Doppler radar can identify the bow echo signature and the strong front-to-rear wind shifts that indicate damaging winds, but there is no rotating vortex to detect — the warning parameters are completely different from the tornado rotation signature used in supercell warnings.",
        },
      ],
    },
  ],
}

export default thunderstorms
