import { Wind, Globe, Sun } from 'lucide-react'
import { BRAND } from '@/lib/brand'
import type { Lesson } from './types'

const precipitation: Lesson = {
  id: 'atmo-101-1-3-2',
  title: 'Precipitation: Types, Processes, and Patterns',
  track: 'atm',
  trackName: 'Meteorology',
  level: 'Beginner',
  duration: '11 min',
  xpReward: 140,
  description: "Rain, snow, sleet, hail — precipitation is the atmosphere's mechanism for returning water to the surface. The physical processes that determine what falls, where, and how much reveal the deep connections between cloud microphysics, storm dynamics, and global climate.",
  sources: [
    { org: 'NOAA',     title: 'National Weather Service — Precipitation Types',             url: 'https://www.weather.gov/jetstream/precip' },
    { org: 'NASA',     title: 'Global Precipitation Measurement Mission',                   url: 'https://gpm.nasa.gov/' },
    { org: 'OpenStax', title: 'Introduction to Atmospheric Science, Ch. 6 (CC-BY 4.0)',   url: 'https://openstax.org/books/introduction-oceanography' },
    { org: 'UCAR',     title: 'How Precipitation Forms',                                   url: 'https://scied.ucar.edu/learning-zone/atmosphere/clouds' },
    { org: 'WMO',      title: 'Global Precipitation Climatology Centre',                   url: 'https://www.dwd.de/EN/ourservices/gpcc/gpcc.html' },
  ],
  sections: [
    {
      type: 'intro',
      title: 'The water cycle made visible',
      body: `Every drop of rain, every snowflake, and every hailstone represents the end point of a chain of atmospheric processes that begins with the evaporation of water from the ocean, land, or vegetation and ends with the return of that water to the surface. This is the **hydrological cycle** — one of the most important physical cycles on Earth, distributing freshwater across the globe, moderating temperatures, and supporting the biosphere. The global average precipitation is approximately 1 metre per year, but it ranges from near-zero in the driest deserts to over 11 metres per year at the wettest tropical mountain slopes. This enormous spatial variability is determined by the same atmospheric dynamics that produce different cloud types.

Precipitation forms through two fundamentally different microphysical processes. The **coalescence process** (warm cloud precipitation) dominates in tropical and warm-season clouds where temperatures remain above freezing throughout: cloud droplets collide and merge, growing into raindrops. The **Bergeron-Findeisen-Wegener process** (cold cloud or ice-crystal process) dominates in higher-latitude and winter clouds where ice crystals and supercooled water droplets coexist: ice crystals grow rapidly at the expense of supercooled water droplets because ice is thermodynamically favoured. Understanding these two pathways to precipitation explains many features of observed precipitation: why tropical rainfall is often heavy and convective, why wintertime precipitation from stratiform clouds is often light but persistent, and why hail requires specific storm dynamics.

Precipitation type at the surface — rain, snow, sleet (ice pellets), freezing rain, or hail — depends on the temperature profile between the cloud and the surface. A parcel of precipitation that forms as a snowflake at high altitude will remain snow if the entire column is below freezing, but will melt to rain if it passes through a warm layer, and may refreeze to ice pellets (sleet) or freezing rain if it then encounters a subfreezing layer near the surface. The type of precipitation that reaches the ground is a direct readout of the atmospheric temperature profile — making precipitation type one of the most practically important forecasting problems, especially for winter storms where rain, snow, sleet, and freezing rain can occur within 100 km of each other.`,
      keyTerms: [
        { term: 'Coalescence',          def: 'The warm-cloud precipitation process in which cloud droplets collide and merge, growing from ~10 μm (cloud droplet) to ~2,000 μm (raindrop). Larger droplets fall faster and sweep up smaller droplets. Requires a spectrum of droplet sizes — initially created by CCN variability or turbulence. Dominant in tropical convective clouds and marine environments. Produces large, fast-falling raindrops.' },
        { term: 'Bergeron process',     def: 'The ice-crystal precipitation mechanism. In mixed-phase clouds (ice crystals + supercooled liquid droplets at −10 to −40°C), ice crystals grow rapidly by vapour deposition at the expense of supercooled droplets, because the vapour pressure over ice is lower than over supercooled water (ice is more thermodynamically stable). Water droplets evaporate; vapour migrates to ice crystals, which grow large enough to fall. Dominant in midlatitude and high-latitude clouds.' },
        { term: 'Supercooled water',    def: 'Liquid water that remains liquid at temperatures below 0°C, in the absence of suitable ice nuclei. Cloud droplets can remain liquid to as cold as −40°C (homogeneous nucleation temperature). Supercooled water is responsible for aircraft icing, freezing rain, and is the substrate for the Bergeron process. Impacts aviation safety and is the key ingredient in cloud seeding attempts.' },
        { term: 'Freezing rain',        def: 'Precipitation that falls as rain through a warm layer aloft (above-freezing temperature), then encounters a sub-freezing layer near the surface too thin to refreeze the drop before reaching the ground; the supercooled drop freezes on contact with below-freezing surfaces. Produces glazed ice (glaze ice) on roads, trees, power lines — extremely hazardous. Distinct from sleet (ice pellets), which refreeze in the air before reaching the surface.' },
        { term: 'Orographic precipitation', def: 'Precipitation enhanced by mountains forcing moist air to rise on the windward side. As air rises, it cools and precipitates, drying out. As air descends on the leeward side, it warms (compression) and the precipitation ceases — the **rain shadow** effect. Responsible for the wettest places on Earth (Cherrapunji, India; Mt. Waialeale, Hawaii) on windward slopes, and for extreme aridity in rain shadows (Great Basin, Atacama, Patagonian steppe).' },
      ],
    },
    {
      type: 'concept',
      title: 'Precipitation physics, types, and global distribution',
      body: `**The Bergeron process in detail.** The Bergeron-Findeisen-Wegener process operates in mixed-phase clouds — clouds that contain both ice crystals and supercooled water droplets simultaneously. This coexistence is possible because water freezes only on suitable **ice nuclei** (certain mineral dust particles, bacteria, and organic materials); in their absence, liquid droplets can persist to −40°C. The thermodynamic key is the **saturation vapour pressure difference**: at any sub-zero temperature, the saturation vapour pressure over ice is lower than over supercooled water. This means the air in the cloud can be supersaturated with respect to ice while simultaneously being undersaturated with respect to liquid. Water droplets therefore evaporate (the air is "dry" relative to the liquid surface), and ice crystals simultaneously grow (the same air is "wet" relative to the ice surface). The net result is a transfer of mass from liquid droplets to ice crystals. Ice crystals grow quickly — a single ice crystal can aggregate multiple snowflakes and grow to precipitable size in minutes — while the original water droplets shrink and may disappear.

**Hail formation.** Hail is produced only in thunderstorms with sufficiently strong updrafts to loft growing ice particles above the freezing level repeatedly. A hailstone begins as a frozen droplet or snowflake that is carried upward into the supercooled water region of the thunderstorm. It collects supercooled water droplets that freeze on contact — **accretion** (the freezing of supercooled water droplets on contact with an ice particle, adding mass layer by layer) — building up concentric shells. If the updraft is strong enough, the hailstone remains aloft long enough to grow to dangerous sizes. When the updraft can no longer support the hailstone's weight, it falls. Cutting a large hailstone in half reveals concentric rings of clear ice (from time spent in the liquid water-rich part of the cloud) and opaque ice (from time spent in the ice-crystal region where growth was dry accretion); these rings record the hailstone's history within the storm.

The size of a hailstone is a direct measure of updraft strength — a stone must remain suspended while it grows, so larger stones demand faster updrafts. The largest hailstone ever recorded in the US fell in Vivian, South Dakota on July 23, 2010: 20.3 cm (8 inches) diameter, 878 grams (1.94 lbs). The updraft that produced it was estimated at over 160 km/h — strong enough to hold a stone nearly the size of a volleyball aloft inside the storm.

**Precipitation types and the temperature profile.** The four main precipitation types — rain, snow, sleet (ice pellets), and freezing rain — reflect the temperature profile between the cloud and the surface. A particle falling from a cloud above the freezing level: (1) if the entire column is below 0°C → **snow**; (2) if there is a warm layer above 0°C in mid-levels that completely melts it, followed by a shallow sub-zero layer near the surface through which it passes quickly → **freezing rain** (falls as rain, freezes on contact with frozen surfaces); (3) if the sub-zero near-surface layer is deep enough to refreeze the melted drop → **sleet** (ice pellets, semi-translucent small hard spheres); (4) if temperatures throughout are above 0°C → **rain**. Mixed precipitation events (where rain, snow, sleet, and freezing rain fall simultaneously or within kilometres of each other) occur when the temperature transition regions are sharp and the warm layer is shallow — among the most complex and consequential winter weather forecasting challenges.

**Global precipitation distribution.** Precipitation is not evenly distributed. The **intertropical convergence zone (ITCZ)** — the belt of low pressure where trade winds from both hemispheres converge near the equator — produces the highest average annual precipitation on Earth (>3,000 mm/yr). Midlatitude regions receive precipitation from the passage of midlatitude cyclones: 500–1,500 mm/yr on windward coasts, less in continental interiors. Subtropical regions dominated by the descending limb of the Hadley cell — including the Sahara, Arabian Peninsula, Australian interior, and Atacama — are the world's driest regions: <100 mm/yr. Polar regions are also dry: <300 mm/yr on average (but cold, so even this limited snowfall accumulates). The wettest place on Earth: Mawsynram and Cherrapunji, India (both Meghalaya, Bengal Hills windward slope of Himalayas) receive ~11,000–12,000 mm/yr from orographic enhancement of the Indian summer monsoon.`,
      cards: [
        {
          name: 'Coalescence vs. Bergeron Process',
          icon: Sun,
          color: BRAND.gold,
          desc: 'Coalescence (warm cloud, >0°C): cloud droplets collide and merge; larger drops fall faster, sweeping up smaller ones; effective in tropical convective clouds, marine environments; produces large raindrops. Bergeron-Findeisen-Wegener (mixed phase, −10 to −40°C): ice crystal grows by vapour deposition at expense of evaporating supercooled water droplets; dominant in midlatitude stratus and stratiform precipitation; produces snowflakes that may melt to rain at surface.',
          examples: 'Tropical shower: warm cloud coalescence → large drops, intense brief rain · Winter stratus precipitation: Bergeron process → light snow or drizzle · Cloud seeding: inject silver iodide (ice nuclei) into supercooled clouds to trigger Bergeron process and enhance precipitation',
        },
        {
          name: 'Precipitation Types',
          icon: Wind,
          color: BRAND.accent,
          desc: 'Rain: entirely above-freezing column, drops 0.5–5 mm. Snow: entire column below freezing, ice crystal aggregates (snowflakes). Sleet: snow forms → melts in warm mid-level layer → refreezes in near-surface cold layer → ice pellets reach ground. Freezing rain: melted droplet passes through shallow near-surface cold layer too quickly to refreeze → freezes on contact with frozen surfaces → glaze ice. Hail: only in thunderstorms with strong updrafts; concentric growth layers record storm history.',
          examples: 'Ice storm (freezing rain): 1998 North American ice storm — 80–100 mm equivalent liquid, 3–10 cm ice accumulation, 35 deaths, $5 billion damage · Hail diameter world record: 20.3 cm, Vivian SD, 2010 · Virga: precipitation that evaporates before reaching the surface; common in dry climates',
        },
        {
          name: 'Global Distribution and Orographic Effects',
          icon: Globe,
          color: BRAND.jade,
          desc: 'ITCZ: highest precipitation (3,000–5,000+ mm/yr), tropical convection. Midlatitude W coasts: 800–3,000 mm, cyclonic and orographic. Subtropical deserts: Hadley descending branch, <100 mm. Rain shadow (leeward): Atacama (driest non-polar desert, <10 mm/yr), Great Basin, Patagonian Steppe. Orographic maxima: Cherrapunji/Mawsynram 12,000 mm/yr (Himalayas windward), Mt. Waialeale 11,500 mm/yr (Hawaii). Polar: dry but cold → ice accumulates.',
          examples: 'Atacama Desert (Chile): can go years with no rain — some weather stations have never recorded rain · Amazon basin: 2,000–3,000 mm/yr from ITCZ + recycled evapotranspiration (50% of Amazon rainfall is from the forest itself) · Monsoon: 75% of Indian annual precipitation in 4-month summer monsoon season',
        },
      ],
    },
    {
      type: 'quiz',
      questions: [
        {
          q: "A winter storm forecasting dilemma: a warm air mass at 850 hPa is bringing above-freezing temperatures to a region, while the surface temperature remains −2°C. Forecasters must determine whether residents will experience freezing rain (glaze ice) or sleet (ice pellets). What determines which of these two outcomes occurs, and why does it matter to road safety planning?",
          a: [
            "The distinction depends on the humidity of the warm air mass: humid warm air produces freezing rain because water vapour prevents the droplets from refreezing; dry warm air produces sleet because the lower humidity allows radiative cooling to refreeze the falling drops; road safety planning differs because freezing rain is more dangerous due to its smooth, continuous ice coating",
            "The distinction depends on the depth and temperature of the cold surface layer: if the sub-freezing layer near the surface is shallow (a few hundred metres) and the drop falls through it quickly without refreezing in the air → freezing rain; if the cold layer is deep enough or cold enough to completely refreeze the drop before it reaches the surface → sleet (ice pellets); freezing rain is far more hazardous than sleet because it coats surfaces in smooth, nearly invisible glaze ice, while sleet is more visible and creates less friction reduction",
            "Freezing rain and sleet are produced by the same process and there is no reliable way to distinguish them in advance; both involve precipitation melting in a warm layer aloft and encountering subfreezing temperatures near the surface; road safety planning treats them identically because their surface hazard is equivalent",
            "The distinction is determined by precipitation rate: heavy precipitation rates → freezing rain (drops are large and fall fast, not allowing time to refreeze); light precipitation rates → sleet (drops are small and fall slowly, giving them time to refreeze in the cold layer); road safety planning focuses primarily on precipitation rate rather than precipitation type",
          ],
          correct: 1,
          explain: "Humidity of the warm air mass (A) does not determine whether precipitation refreezes in the cold layer — the refreezing of a falling drop depends on the thermodynamics of the cold air layer (depth and temperature), not on the humidity of the layer where melting occurred. Freezing rain and sleet are not produced by the same process in the sense that they can be reliably distinguished by temperature profile analysis (C) — this is the entire point of winter storm forecasting and why operational meteorologists spend enormous effort on the warm-layer/cold-layer structure; they are definitively not treated identically. Precipitation rate (D) does affect drop size and fall speed, but it is not the primary determinant of whether refreezing occurs; a large drop falling fast has more thermal mass and may actually be harder to refreeze in a shallow cold layer, making the rate argument partially backwards. The correct answer is B: the physical distinction is the depth and temperature of the sub-freezing surface layer. A melted raindrop falling through a shallow near-surface cold layer (perhaps 200–500 m deep, temperatures just below freezing) may not lose enough heat to the cold air to refreeze before it hits the surface — it arrives as supercooled liquid and freezes on contact with subfreezing road surfaces and vegetation, creating glaze ice (freezing rain). If the cold layer is deeper or colder, the drop has more time in contact with sub-freezing air, loses more heat, and may completely refreeze in the air, arriving as a solid ice pellet (sleet). The road safety distinction is enormous: glaze ice from freezing rain is smooth, continuous, nearly transparent, and accumulates to 10–100 mm thickness; it is one of the most dangerous natural icing conditions, causing road fatalities and infrastructure damage at far lower accumulations than snow. Sleet has some surface texture, does not coat surfaces as thoroughly, and is much less dangerous per unit of precipitation.",
        },
        {
          q: "The Bergeron-Findeisen-Wegener process explains how cloud droplets are transformed into precipitable ice crystals. What is the fundamental thermodynamic reason that ice crystals grow at the expense of supercooled liquid droplets in a mixed-phase cloud?",
          a: [
            "Ice crystals are denser than liquid water droplets, so they exert a higher vapour pressure that drives water vapour toward them; supercooled water droplets evaporate because the vapour pressure gradient points away from the droplets toward the ice crystals",
            "Ice is thermodynamically more stable than supercooled liquid water below 0°C, and the saturation vapour pressure over an ice surface is lower than over a supercooled liquid surface at the same temperature; the cloud air is simultaneously supersaturated with respect to ice (causing ice growth by deposition) and subsaturated with respect to supercooled water (causing droplet evaporation); the net effect transfers mass from liquid to solid phase without any droplets and crystals needing to contact each other",
            "Ice crystals grow by directly absorbing liquid water molecules from cloud droplets through electrostatic attraction; the permanent dipole of water molecules is attracted more strongly to the ordered crystal lattice of ice than to other liquid water molecules, so molecules spontaneously migrate from the droplet surface to the ice crystal surface",
            "In mixed-phase clouds, ice crystals are warmer than supercooled water droplets because crystallisation releases latent heat; this temperature difference creates a heat gradient; warmer ice crystals draw water vapour from cooler droplets through thermophoresis, the migration of particles from colder to warmer regions",
          ],
          correct: 1,
          explain: "Ice is not denser in a way that increases vapour pressure (A) — density and vapour pressure have an inverse relationship (denser materials generally have lower vapour pressure, not higher); also, the vapour pressure gradient runs from higher over liquid water toward lower over ice, which is opposite to what A states. The electrostatic dipole attraction mechanism (C) is not the process — the Bergeron process operates through the vapour phase, not through direct molecular transfer between droplet and crystal surfaces; there is no short-range electrostatic mechanism that transfers molecules across the gap between a droplet and a crystal micrometres away. The thermophoresis argument (D) has causality backwards — crystallisation does release latent heat (warming the crystal slightly relative to the vapour), but this effect does not drive the vapour transfer in the direction described; ice crystals are in general not warmer than the surrounding air in a mixed-phase cloud. The correct answer is B: the key thermodynamic fact is that the **saturation vapour pressure over ice** (the vapour pressure at which air is in equilibrium with an ice surface) is **lower** than the **saturation vapour pressure over supercooled water** at the same temperature. This asymmetry exists because supercooled water is a metastable phase (higher free energy than ice below 0°C), so its molecules exert higher vapour pressure to escape to the gas phase. The consequence is that in a mixed-phase cloud, the air between the ice crystals and supercooled droplets is simultaneously: (1) slightly supersaturated with respect to ice → water vapour deposits on ice crystals, growing them; and (2) slightly subsaturated with respect to supercooled water → supercooled droplets evaporate. Mass moves from the liquid to the solid phase through the vapour medium, without the particles needing to contact each other.",
        },
        {
          q: "Cherrapunji and Mawsynram in the Meghalaya hills of India receive approximately 12,000 mm of precipitation per year, making them among the wettest places on Earth. Yet the Atacama Desert on the windward face of the Andes in South America receives less than 10 mm per year. Both locations are influenced by mountains. What different orographic processes explain these extreme contrasts?",
          a: [
            "Cherrapunji receives high precipitation because it is in the tropics with warm, moist air from the Bay of Bengal forced upward by the Meghalaya hills; the orographic lifting of this moisture-laden air produces intense precipitation on the windward (southern) slope. The Atacama is dry not because of orographic effects but because it is under the subtropical high-pressure belt; mountains are not relevant to its aridity",
            "Cherrapunji receives extreme precipitation from orographic lifting of Bay of Bengal air masses forced up the southern slopes of the Meghalaya hills (windward side), releasing enormous latent heat and precipitation; the Atacama is in the rain shadow of the Andes — moist Pacific air is forced upward on the Andes' western slopes, precipitating out, then descends as dry, compressed (warmed) air on the eastern (windward?) side; compounding this, cold Humboldt Current upwelling cools the coastal air, stabilising it and suppressing precipitation even at the coast",
            "Cherrapunji's high precipitation reflects its location directly under the ITCZ year-round, which provides 12,000 mm regardless of topography; the Meghalaya hills simply concentrate the rainfall spatially. The Atacama is dry because it is in the Southern Hemisphere's polar desert region, far from any moisture source",
            "Both locations demonstrate the same orographic principle but with opposite geography: Cherrapunji is on the windward side of a mountain barrier (precipitation maximum) while the Atacama is on the leeward side (rain shadow); the key difference is simply which side of the mountain they are on relative to the prevailing wind",
          ],
          correct: 1,
          explain: "The claim that mountains are not relevant to Atacama's aridity (A) is incorrect — the Andes are a major factor; the rain shadow effect of the Andes is compounded by the cold Humboldt Current, but the mountains play a direct role in blocking Pacific moisture from reaching the Atacama from the west. Cherrapunji is not under the ITCZ year-round (C) — it is at ~25°N latitude, well north of the ITCZ; its extreme rainfall comes specifically from the Indian summer monsoon (June–October), where the southwesterly monsoon flow forces Bay of Bengal air into the hills. The Atacama is not in a polar desert region (C) — it is at 20–30°S latitude in the subtropics. Option D gets the basic principle right but is incomplete — it doesn't explain why the Atacama is not just moderately dry (like any normal rain shadow) but extraordinarily arid. The correct answer is B: Cherrapunji and Mawsynram are on the windward (southern) face of the Meghalaya hills, directly in the path of the summer monsoon flow from the Bay of Bengal. Moist, warm monsoon air is forced up the steep escarpment, cooling and precipitating extremely rapidly; the geography concentrates an already moisture-rich air stream through orographic amplification. The Atacama, by contrast, has multiple compounding dryness mechanisms: (1) rain shadow — the Andes on the east block moisture from the Amazon Basin from reaching the western slope; (2) subsiding Hadley cell air from the subtropical high — the Pacific Anticyclone produces persistent subsidence that inhibits convection at the regional scale; (3) cold Humboldt Current — cold Pacific water (~15°C) cools the overlying coastal air from below, creating a temperature inversion that strongly suppresses convection and prevents cloud development near the coast even on the windward (western) side. Together, these three factors produce the most extreme non-polar aridity on Earth.",
        },
        {
          q: "Global precipitation is dominated by two dynamically distinct regimes: the convective-dominated tropics (especially the ITCZ) and the frontal/cyclonic precipitation of the midlatitudes. Why do these two regimes produce fundamentally different precipitation characteristics in terms of intensity, spatial extent, and seasonal distribution?",
          a: [
            "Tropical and midlatitude precipitation differ because the tropics receive more solar energy, which simply evaporates more water, and all of this extra evaporated water precipitates locally; midlatitude precipitation is less intense only because less water is evaporated from cooler ocean surfaces; the dynamical mechanisms of precipitation formation are identical in both regions",
            "Tropical precipitation (ITCZ) is driven by thermally-direct convection: intense surface heating and convergence of trade winds cause moist surface air to rise buoyantly to the tropopause in cumulonimbus towers, releasing enormous latent heat in localised, intense bursts (100–300 mm/day possible in storms) that are spatially patchy and triggered by diurnal heating; midlatitude precipitation is driven by synoptic-scale frontal dynamics — large-scale forced ascent of warm air over cold air or by cold air undercutting warm air — producing widespread but less intense precipitation (10–50 mm/day) organised over hundreds of kilometres for days; the midlatitude regime peaks in winter when frontal contrasts are strongest, while the ITCZ regime follows the seasonal migration of maximum solar heating",
            "Tropical and midlatitude precipitation are actually similar in intensity and spatial extent; the apparent differences reflect the fact that tropical precipitation is poorly measured because most rain gauges are on land, while tropical rainfall predominantly falls over ocean; better measurement would show the two regimes are equivalent in all characteristics",
            "Tropical precipitation is more spatially uniform than midlatitude precipitation because the ITCZ is a continuous band of clouds circling the globe at constant latitude year-round; midlatitude precipitation is patchier because it occurs only in discrete storm systems; the ITCZ's spatial uniformity produces steady drizzle over the entire tropical belt rather than intense convective bursts",
          ],
          correct: 1,
          explain: "The claim that precipitation formation mechanisms are identical (A) is incorrect — tropical precipitation primarily uses the warm-cloud coalescence process in deep convective towers, while midlatitude stratiform precipitation predominantly uses the Bergeron-Findeisen process in mixed-phase clouds; the energy source also differs (surface thermal instability vs. baroclinic frontal lifting), producing fundamentally different storm morphologies. Measurement gaps do not equalise the two regimes (C) — satellite and ocean-based rain gauge networks have confirmed for decades that tropical convective precipitation is genuinely more intense per storm event, even if total annual accumulation varies by region; the dynamical and physical differences are real and well-documented. The ITCZ is not spatially uniform nor does it produce steady drizzle (D) — it is a zone of deep convective activity with highly variable, patchy precipitation organised into individual cumulonimbus cells, mesoscale convective systems, and squall lines; it migrates seasonally following the thermal equator (northward in boreal summer, southward in austral summer), not remaining at constant latitude. The correct answer is B: the two precipitation regimes reflect fundamentally different atmospheric dynamics. Tropical (ITCZ) precipitation is thermally direct: solar heating of the ocean surface produces strong convective instability; the trade winds converge moisture from both hemispheres into the ITCZ; the resulting deep cumulonimbus convection releases latent heat explosively, generating intense but patchy rain events that are strongly modulated by the diurnal cycle (peak in late afternoon over land, late night over ocean). Midlatitude precipitation is dynamically driven: frontal systems lift air through large-scale convergence and forced ascent over hundreds of kilometres, producing widespread stratiform precipitation from nimbostratus clouds; rain rates are lower but spatially more continuous and temporally persistent. The midlatitude regime depends on the frontal contrasts between warm and cold air masses, which are most pronounced in winter, while the ITCZ follows the sun — this explains why monsoonal regions experience a pronounced wet season when the ITCZ shifts overhead, and why midlatitude regions have peak precipitation seasons tied to cyclone frequency.",
        },
      ],
    },
  ],
}

export default precipitation
