import { Wind, Globe, Sun } from 'lucide-react'
import { BRAND } from '@/lib/brand'
import type { Lesson } from './types'

const cloudFormation: Lesson = {
  id: 'atmo-101-1-3-1',
  title: 'Cloud Formation and Classification',
  track: 'atm',
  trackName: 'Meteorology',
  level: 'Beginner',
  duration: '11 min',
  xpReward: 140,
  description: "Clouds are the atmosphere's visible autobiography — each type a record of the temperature, humidity, and motion of the air in which it formed. Learning to read clouds is one of the oldest and most powerful forms of weather observation.",
  sources: [
    { org: 'NOAA',     title: 'Cloud Classification — National Weather Service',            url: 'https://www.weather.gov/jetstream/clouds' },
    { org: 'WMO',      title: 'International Cloud Atlas — World Meteorological Organization', url: 'https://cloudatlas.wmo.int/' },
    { org: 'OpenStax', title: 'Introduction to Atmospheric Science, Ch. 5 (CC-BY 4.0)',   url: 'https://openstax.org/books/introduction-oceanography' },
    { org: 'UCAR',     title: 'Clouds and Precipitation',                                  url: 'https://scied.ucar.edu/learning-zone/atmosphere/clouds' },
    { org: 'NASA',     title: 'MODIS Cloud Products',                                      url: 'https://modis.gsfc.nasa.gov/' },
  ],
  sections: [
    {
      type: 'intro',
      title: 'Reading the sky',
      body: `Clouds have been read as weather signs for thousands of years. Sailors watched the development of towering cumulonimbus with apprehension; farmers looked for the high, thin cirrus that preceded warm front rain. This empirical tradition was systematised in 1803, when British chemist Luke Howard published a cloud classification that gave Latin names to the major cloud types — names that remain in use today. The World Meteorological Organization's International Cloud Atlas, first published in 1896 and still updated, contains detailed descriptions and photographs of cloud genera, species, varieties, and supplementary features that together constitute a comprehensive descriptive taxonomy of the visible atmosphere.

A **cloud** is a visible collection of water droplets or ice crystals suspended in the atmosphere. Clouds form when moist air rises, expands, cools, and eventually reaches the **dew point** — the temperature at which the air is saturated and condensation begins. The altitude at which this occurs — the **lifting condensation level (LCL)** — is the base of the cloud. The LCL altitude depends on the surface temperature and moisture: dry, hot air has a high LCL (high cloud base); cool, moist air has a low LCL (low cloud base). This is why cumulus cloud bases on a hot summer afternoon are flat and at the same altitude — they all mark the LCL for the relatively uniform surface air.

The appearance and behaviour of clouds encode the state of the atmosphere above us. High, wispy cirrus indicate a high-altitude ice-crystal environment and often herald the approach of a warm front. Flat, layered stratus indicate stable, slowly sinking air. Towering, rapidly growing cumulonimbus indicate explosive atmospheric instability. The shape, height, texture, and evolution of clouds all provide direct information about temperature, moisture, stability, and wind shear at altitudes from 0 to 12 km — information that before the radiosonde (weather balloon) era was available only by looking up.`,
      keyTerms: [
        { term: 'Lifting condensation level (LCL)', def: 'The altitude at which an air parcel lifted dry-adiabatically reaches saturation (dew point = air temperature) and condensation begins — the base of convective clouds. LCL altitude can be estimated from surface temperature and dew point: LCL (m) ≈ 125 × (T − Td), where T is temperature in °C and Td is dew point temperature in °C. Low surface dew point depression = low cloud bases.' },
        { term: 'Cloud genera',      def: 'The ten internationally recognised cloud types, classified by altitude and form. By altitude: high (cirrus, cirrocumulus, cirrostratus; base >6 km, ice crystals); middle (altocumulus, altostratus; 2–6 km, water droplets or mixed); low (stratus, stratocumulus, nimbostratus; <2 km, water droplets). Vertical extent clouds: cumulus, cumulonimbus (extend through multiple levels).' },
        { term: 'Cumuliform',        def: 'Cloud type with a heaped, lumpy, or cauliflower-like appearance, indicating vertical (convective) motion in the atmosphere. Range from fair-weather cumulus humilis (small, shallow, no precipitation) to cumulonimbus (thunderstorm cloud extending to the tropopause). Cumuliform clouds indicate instability: rising parcels are warmer than surroundings.' },
        { term: 'Stratiform',        def: 'Cloud type with a layered, sheet-like appearance, indicating horizontal (laminar) airflow rather than vigorous vertical motion. Types: stratus (low, foglike, drizzle), stratocumulus (low, lumpy layers), altostratus (middle, grey/blue layer), nimbostratus (thick, dark, persistent rain). Stable air inhibits vertical motion, producing horizontal layering.' },
        { term: 'Cloud condensation nuclei (CCN)', def: 'Tiny particles on which water vapour condenses to form cloud droplets. Without CCN, supersaturation of >300% would be needed to form droplets spontaneously; with CCN, condensation occurs at near-100% relative humidity. CCN include sea salt, dust, sulfate aerosols, and industrial pollution. Maritime air has fewer, larger CCN → fewer, larger cloud droplets; polluted continental air has more, smaller droplets.' },
      ],
    },
    {
      type: 'concept',
      title: 'Cloud types, formation mechanisms, and climate significance',
      body: `**Cloud formation mechanisms.** All clouds form through the same basic process: moist air rises, expands adiabatically (without exchanging heat with the surroundings), cools at the dry adiabatic lapse rate (DALR) of ~10°C per km until it reaches the LCL, then continues to cool at the slower **moist adiabatic lapse rate (MALR)** (~6°C per km on average) as latent heat released by condensation slows the cooling. The mechanism of uplift distinguishes cloud types: **convective uplift** (surface heating, frontal convergence, mechanical forcing over terrain) produces cumuliform clouds; **frontal uplift** (warm front overriding cold air) produces the classic warm-front cloud sequence; **orographic uplift** (air forced over mountains) produces cap clouds, lenticular clouds, and persistent precipitation on windward slopes; **radiative cooling** (clear nights) can cool the surface air to its dew point, producing radiation fog and stratus.

**The ten cloud genera.** The WMO classifies clouds into ten genera. **High-level clouds** (base >6 km, ice crystals): *Cirrus* (Ci): detached wisps or streaks of white ice crystals, often showing the characteristic "mare's tails" appearance from wind shear; they do not produce precipitation at the surface but are a classic warm-front precursor. *Cirrocumulus* (Cc): small white tufts or waves arranged in rows ("mackerel sky"); thin enough to be nearly transparent. *Cirrostratus* (Cs): thin, transparent ice-crystal sheet producing haloes around the sun and moon; classic warm-front cloud. **Middle-level clouds** (2–6 km, water or mixed): *Altocumulus* (Ac): grey or white patches in rounded masses, larger than cirrocumulus; middle-altitude unstable air. *Altostratus* (As): grey or blue-grey fibrous layer through which the sun appears as if through ground glass; warm front progression. **Low-level clouds** (<2 km): *Stratus* (St): low, grey, uniform layer producing drizzle; stable, slowly subsiding air. *Stratocumulus* (Sc): the most common cloud type globally; lumpy grey-white sheet, not precipitating significantly. *Nimbostratus* (Ns): thick, dark, diffuse, precipitating layer. **Vertical extent clouds**: *Cumulus* (Cu): heaped, flat base, cauliflower top; fair weather (humilis) to precipitating (congestus). *Cumulonimbus* (Cb): the thunderstorm cloud; extends from near the surface to the tropopause; produces lightning, heavy rain, hail, and tornadoes.

**Why cloud bases are flat.** The fact that cumulus clouds have uniformly flat bases on a given afternoon is one of the most instructive features of cloud meteorology. All the surface air being heated by the sun has approximately the same temperature and dew point, so it all reaches saturation at the same altitude — the LCL. This altitude depends only on the surface temperature-dew point depression: LCL ≈ 125 × (T − Td) in metres. If surface temperature is 30°C and dew point is 20°C (depression = 10°C), cloud bases form at ~1,250 m. On a drier day (depression 15°C), bases would be at ~1,875 m. The LCL is why you can see a field of cumulus clouds all starting at exactly the same altitude — each one rising from a different surface thermal but all reaching saturation at the same height.

**Clouds and Earth's energy balance.** Clouds are among the largest sources of uncertainty in climate projections because they have opposing effects on the energy budget. **Low clouds** (stratus, stratocumulus) have high albedo and reflect solar radiation back to space (cooling effect) but are at low, warm altitude so they trap relatively little additional infrared radiation (weak greenhouse effect). Their net effect is strongly cooling. **High clouds** (cirrus, cirrostratus) are thin and have low albedo (little solar reflection) but are at cold high altitude, so they effectively trap infrared radiation (strong greenhouse effect). Their net effect can be warming. The sign and magnitude of the cloud feedback — how cloud cover and properties change as climate warms — is the largest single source of uncertainty in equilibrium climate sensitivity estimates.`,
      cards: [
        {
          name: 'Cloud Types by Altitude',
          icon: Wind,
          color: BRAND.accent,
          desc: `High (>6 km, ice): Cirrus (wisps, mare\'s tails, warm front precursor), Cirrocumulus (mackerel sky), Cirrostratus (halo-producing sheet). Mid (2–6 km, mixed): Altocumulus (grey puffs, instability), Altostratus (sun-through-glass, warm front). Low (<2 km, water): Stratus (fog-like, drizzle), Stratocumulus (most common globally, lumpy), Nimbostratus (thick dark precipitating). Vertical: Cumulus (heaped, flat base), Cumulonimbus (Cb; full-troposphere, lightning, hail).`,
          examples: `Contrails: artificial cirrus from jet exhaust (ice nucleation on soot) · "Mackerel sky" cirrocumulus: sailors\' traditional rain warning · Kelvin-Helmholtz waves (billows): instability waves in altostratus, resemble breaking ocean waves`,
        },
        {
          name: 'Formation Mechanisms',
          icon: Globe,
          color: BRAND.jade,
          desc: 'Convective uplift: surface heating → thermals → cumulus formation on humid days. Frontal uplift: warm front (Ci→Cs→As→Ns sequence) or cold front (narrow Cb band). Orographic uplift: mountains force air upward → windward cloud/precipitation; lenticular clouds (Ac lent) in stable air over mountains. Radiative cooling: clear sky, surface cools below dew point → radiation fog or stratus. LCL = 125 × (T − Td) metres, flat cloud bases.',
          examples: 'Cap cloud: stationary lenticular cloud over mountain summit (orographic) · Fog burn-off: stratus dissipates as solar heating raises surface above dew point · Marine layer: stratus over cold ocean upwelling off California coast, typical summer morning fog',
        },
        {
          name: 'Clouds and Climate',
          icon: Sun,
          color: BRAND.gold,
          desc: 'Low clouds (Sc, St): high albedo (0.6–0.7) → cool climate. Thin, low → weak IR trapping. Net effect: strong cooling. High clouds (Ci, Cs): low albedo → little solar reflection. Cold, high → effective IR trap. Net effect: slight warming. Cloud feedback: largest uncertainty in climate sensitivity. If warming increases low cloud cover → negative feedback (cools). If warming reduces low cloud cover → positive feedback (amplifies warming). Current evidence: low cloud likely decreases slightly with warming → positive feedback.',
          examples: 'Stratocumulus off W coasts: major cooling influence on climate; if these clouds disappear under warming, +8°C possible from modeling studies · Cirrus seeding geoengineering: proposed deliberate thinning of cirrus to reduce warming effect · CERES satellite: directly measures global cloud radiative effect (+30 W m⁻² from high clouds, −50 W m⁻² from low clouds)',
        },
      ],
    },
    {
      type: 'quiz',
      questions: [
        {
          q: "On a summer afternoon, a meteorologist observes cumulus clouds with flat bases at approximately 1,500 m. She measures a surface temperature of 32°C. What is the approximate surface dew point temperature, and what does this value tell her about the atmospheric moisture content?",
          a: [
            "The dew point temperature is approximately 20°C; the dew point depression of 12°C means the surface air contains a moderate amount of moisture — enough to support cloud formation at 1,500 m but not so humid as to produce very low cloud bases; this is consistent with moderate severe weather potential in the afternoon",
            "The dew point temperature is approximately 20°C; the surface air is quite dry — a 12°C depression means that most of the sun's energy goes into sensible heating (raising temperature) rather than evaporation; at this dew point, afternoon thunderstorm development would require significant forcing from a boundary",
            "The dew point temperature is approximately 20°C; this value indicates the air is nearly saturated (dew point close to temperature), suggesting fog is likely and afternoon convection would be suppressed because there is insufficient solar heating to destabilise the atmosphere",
            "The dew point temperature cannot be determined from cloud base height and surface temperature alone; dew point depends on the vertical moisture profile through the troposphere, which requires a weather balloon sounding",
          ],
          correct: 0,
          explain: "All three options that attempt to calculate the dew point correctly use the LCL formula: LCL ≈ 125 × (T − Td) → 1,500 m ≈ 125 × (32 − Td) → (32 − Td) = 12 → Td ≈ 20°C. The calculation is correct in A, B, and the rejected premise of C. The question is therefore which interpretation is most accurate. Option C states that a dew point of 20°C with T = 32°C means the air is 'nearly saturated' — this is incorrect; a 12°C depression (relative humidity ~54%) is moderate, not near-saturated. Option B says the air is 'quite dry' and afternoon thunderstorms would require significant forcing — this is closer but slightly overstated; 20°C dew points in the central US in summer are considered 'comfortable' moisture, not particularly dry. Option D is technically true in the most general case, but the LCL formula gives a good first approximation of dew point from observable cloud base alone. The correct answer is A: the dew point ≈ 20°C (calculated from LCL formula), and the 12°C dew point depression is consistent with moderate moisture — sufficient for cloud formation at 1,500 m, with conditional severe weather potential depending on shear, CAPE, and whether boundaries are present. This is the most accurate and complete interpretation. The LCL formula is a practical meteorological tool used exactly for this purpose — estimating surface dew point from observed cloud base altitude.",
        },
        {
          q: "A region of the subtropical ocean is persistently covered by a thick deck of stratocumulus clouds. Climate scientists are particularly concerned about what happens to these clouds in a warmer world. Why are subtropical marine stratocumulus decks considered especially important for global climate?",
          a: [
            "Subtropical marine stratocumulus are important because they are the primary source of global precipitation; they cover vast ocean areas and provide most of the freshwater that eventually falls over continents via the global water cycle; their disappearance would cause widespread drought",
            "Subtropical marine stratocumulus cover about 20–25% of the ocean surface and have high albedo (~0.6–0.7), reflecting large amounts of solar radiation back to space; they exist because cold upwelling ocean water stabilises the overlying air, producing a strong temperature inversion that caps any convection; if warming reduces this inversion or warms the underlying ocean, the cloud deck could thin or break up, exposing dark ocean (low albedo), absorbing much more solar energy and potentially causing a powerful positive climate feedback amplifying further warming",
            "Subtropical marine stratocumulus are important primarily because they contain large quantities of liquid water that store heat; their high heat capacity buffers regional temperature changes over the ocean; if they disappear, the buffering effect is lost and ocean temperatures become more volatile",
            "These clouds are important because they are at the boundary between the Hadley cell's descending branch and the ITCZ's rising branch; if stratocumulus decks weaken, the ITCZ shifts and global precipitation patterns are radically disrupted independently of any albedo changes",
          ],
          correct: 1,
          explain: "Subtropical marine stratocumulus are not a major source of global precipitation (A) — they produce primarily drizzle; most continental precipitation comes from midlatitude weather systems and tropical convection, not from subtropical stratocumulus. Heat storage in liquid water (C) is not the primary climate importance of these clouds; their heat capacity does not buffer regional temperatures in a way that is climatically significant compared to the underlying ocean. The ITCZ boundary role (D) is a geographical simplification; stratocumulus are found at the eastern margins of subtropical ocean basins, which are indeed at the poleward edge of the Hadley cell, but their climate importance is primarily the albedo effect, not their interaction with the ITCZ boundary. The correct answer is B: the climate significance of subtropical marine stratocumulus comes from two factors working together. First, their **spatial extent**: stratocumulus cover approximately 20–25% of the global ocean surface, concentrated off the western coasts of continents in the subtropics (Californian, Peruvian, Namibian, Canarian, Australian stratocumulus regions). Second, their **high albedo**: their reflectivity of 60–70% means that the solar energy reflected by these clouds is enormous — removing them from the climate system would expose dark ocean (albedo ~0.06) to full insolation, adding a huge amount of solar energy to the climate system. A modelling study (Schneider et al., 2019) estimated that if CO₂ reached ~1,200 ppm, subtropical stratocumulus might break up abruptly, triggering an additional 8°C of global warming as a tipping point — making this one of the most consequential cloud feedbacks in climate science.",
        },
        {
          q: "The warm-front cloud sequence progresses from cirrus to cirrostratus to altostratus to nimbostratus as a front approaches. What atmospheric process produces this characteristic sequence, and why do the clouds appear in this specific order from highest to lowest?",
          a: [
            "The sequence reflects the vertical structure of the approaching warm air mass itself: the top of the warm air mass reaches the observing location first (appearing as high cirrus), followed by progressively lower layers of the warm air mass as the front approaches; the clouds appear highest first because the top of the warm air has already travelled farthest from the original frontal zone",
            "The warm front slopes gently upward from the surface position (1:200–1:300); the distant observer is initially positioned beneath the highest, most distal part of the frontal slope, where only high ice-crystal clouds exist; as the front advances, progressively lower parts of the frontal cloud system pass overhead, so clouds lower from cirrus (at the remote leading edge) through altostratus to nimbostratus at the surface front; the sequence from highest to lowest mirrors the slope of the frontal surface from most-distant to closest",
            "The cloud sequence is driven by temperature: warm air first produces high cirrus because high altitudes are coldest and ice nucleation occurs there first; as the air mass warms progressively from above, clouds form at progressively lower levels because the temperature is finally cold enough for condensation at those altitudes; nimbostratus forms last when the warmest (lowest) air finally cools enough to condense",
            "The sequence from high to low clouds is produced by sedimentation: ice crystals from cirrus fall through successively lower layers, collecting water droplets as they descend and progressively transforming into lower, denser cloud types; by the time the particles reach low levels, they have grown into raindrops and the cloud is classified as nimbostratus",
          ],
          correct: 1,
          explain: "Option A reverses the geometry — the 'top' of the warm air mass reaching the observer first would mean the observer sees the high clouds because they are overhead at the leading edge of the front, but the explanation conflates the vertical and horizontal dimensions. Option C has the causality backwards — temperature does decrease with altitude, but cloud formation at different levels is driven by the dynamic lifting process, not by temperature progressively 'allowing' condensation from the top down. Ice clouds do appear at altitude because temperatures there are below freezing, but this is a property of the height, not a sequential process. Sedimentation (D) does not transform cloud types — ice crystals falling from cirrus do not collect water droplets and become nimbostratus through sedimentation; the different cloud types are present simultaneously at different altitudes in the frontal cloud shield, not sequentially formed by falling particles. The correct answer is B: the warm front is a gently sloping surface (approximately 1 m of rise per 200–300 m of horizontal distance). The leading edge of the warm air mass at altitude is hundreds of kilometres ahead of the surface front position. An observer standing beneath this leading edge — 500–1,000 km ahead of the surface front — is under the highest, thinnest, most distal part of the frontal slope: cirrus or cirrostratus. As the surface front approaches, the frontal slope overhead lowers, bringing progressively thicker and lower cloud: altostratus then nimbostratus. The sequence from highest to lowest is literally the observer seeing sequentially lower parts of the same sloping frontal cloud system as the front moves overhead from its distant leading edge to its surface position.",
        },
        {
          q: "Cloud condensation nuclei (CCN) are essential for cloud droplet formation at near-normal atmospheric humidity. Maritime clouds (forming over the open ocean) typically have fewer but larger cloud droplets compared to clouds forming over polluted continental areas, which have more but smaller droplets. What physical and optical consequences does this difference in droplet size distribution have for cloud behaviour, and why does it represent a significant climate feedback from anthropogenic pollution?",
          a: [
            "Maritime clouds have larger droplets because ocean water contains dissolved salts that cause droplets to grow by hygroscopic swelling; continental clouds have smaller droplets because continental air lacks salt particles; the optical difference is negligible because the total liquid water content is the same; the climate implication is that maritime clouds are slightly greyer because large droplets absorb more light",
            "The Twomey effect: more CCN from pollution produces more cloud droplets of smaller size for the same amount of liquid water; smaller droplets reflect more solar radiation (higher cloud albedo) because total droplet surface area increases with number concentration when mass is held constant; additionally, smaller droplets inhibit coalescence and precipitation formation, potentially increasing cloud lifetime and liquid water path; both effects increase cloud reflectivity and constitute a negative radiative forcing (cooling) that partially offsets greenhouse gas warming, but its magnitude is among the most uncertain quantities in climate science",
            "Continental clouds with smaller droplets precipitate more efficiently than maritime clouds because small droplets are lighter and remain in the cloud longer, colliding more frequently and forming larger raindrops; this means polluted continental regions receive more rainfall than clean maritime regions, creating a precipitation imbalance that affects global water distribution",
            "The droplet size difference between maritime and continental clouds has no climate significance because both cloud types have approximately the same cloud top temperature and therefore emit the same amount of infrared radiation; since cloud climate effects are dominated by their IR emission, not their albedo, the CCN-driven difference in droplet size is climatically irrelevant",
          ],
          correct: 1,
          explain: "Hygroscopic swelling from dissolved sea salt (A) does contribute to initial droplet activation and growth in maritime clouds, but the primary reason maritime clouds have fewer, larger droplets is not salt swelling — it is the lower number concentration of CCN in clean maritime air; with fewer nuclei competing for the same amount of condensable water, each droplet grows larger. The optical difference is not negligible — it is the foundation of a measurable climate forcing. Smaller continental droplets do not precipitate more efficiently than larger maritime droplets (C) — in fact, the opposite is true: the coalescence process (collision and merging of droplets) is more efficient when droplets are large and have a broader size distribution; smaller, more uniform droplets in polluted continental clouds are less efficient at coalescing into precipitable raindrops, making heavily polluted clouds more precipitation-suppressed, not more precipitation-efficient. Cloud climate effects are not dominated solely by IR emission (D) — low clouds in particular are powerful primarily because of their albedo (solar reflection) effect, not their IR trapping; stratus and stratocumulus clouds at low altitude are nearly as warm as the surface, so they emit nearly as much IR as the surface they replace; their net climate effect is strongly cooling, driven by reflection. The correct answer is B: this is the Twomey effect (also called the first aerosol indirect effect). Mathematically, for a fixed liquid water content, the total droplet surface area scales as N^(1/3), where N is droplet number concentration; more, smaller droplets have higher total cross-section, reflecting more sunlight per unit cloud. The second indirect effect (Albrecht effect) notes that smaller droplets suppress precipitation (they coalesce less efficiently), allowing clouds to persist longer and potentially thicken — further increasing albedo. The total aerosol indirect forcing is estimated at approximately −0.5 to −2.0 W m⁻² (cooling, partially offsetting the +3.0 W m⁻² anthropogenic warming forcing), but the wide range makes it the largest single uncertainty in total anthropogenic forcing — a direct consequence of the difficulty in measuring droplet number concentrations and cloud properties globally.",
        },
      ],
    },
  ],
}

export default cloudFormation
