import { Wind, Globe, Sun } from 'lucide-react'
import { BRAND } from '@/lib/brand'
import type { Lesson } from './types'

const midLatitudeCyclone: Lesson = {
  id: 'atmo-101-1-2-2',
  title: 'The Mid-Latitude Cyclone',
  track: 'atm',
  trackName: 'Meteorology',
  level: 'Beginner',
  duration: '12 min',
  xpReward: 140,
  description: "The mid-latitude cyclone — a rotating low-pressure system thousands of kilometres wide — is the primary weather engine of the middle latitudes, delivering rain, snow, and strong winds to continents and driving the poleward transport of heat that moderates global climate.",
  sources: [
    { org: 'NOAA',     title: 'National Weather Service — Midlatitude Cyclones',            url: 'https://www.weather.gov/jetstream/cyclone' },
    { org: 'UCAR',     title: 'Life Cycle of a Midlatitude Cyclone',                       url: 'https://scied.ucar.edu/learning-zone/weather' },
    { org: 'OpenStax', title: 'Introduction to Atmospheric Science, Ch. 8 (CC-BY 4.0)',   url: 'https://openstax.org/books/introduction-oceanography' },
    { org: 'NOAA',     title: 'JetStream — Understanding Weather',                         url: 'https://www.weather.gov/jetstream/' },
    { org: 'AMS',      title: 'Glossary of Meteorology',                                   url: 'https://glossary.ametsoc.org/' },
  ],
  sections: [
    {
      type: 'intro',
      title: 'The spinning engine of midlatitude weather',
      body: `If you look at a satellite image of a large midlatitude storm — the kind that brings multiple days of cloud, wind, and rain to Europe, or dumps a metre of snow across the northeastern United States — you will see a distinctive pattern: a vast spiral of cloud thousands of kilometres wide, rotating counterclockwise in the Northern Hemisphere (clockwise in the Southern Hemisphere) around a central area of low pressure. This is the **mid-latitude cyclone** (also called an extratropical cyclone or depression), and it is the primary weather-producing machine of the middle latitudes.

Mid-latitude cyclones form through a process called **cyclogenesis** — typically along the polar front, where the sharp temperature contrast between cold polar air and warm tropical air provides the potential energy that the storm system taps. The Norwegian meteorologists who first systematically studied these storms in the early 20th century developed the **Norwegian Cyclone Model** — a conceptual model of cyclone structure and evolution that remains one of the most successful frameworks in meteorological science, still used in modified form in operational weather forecasting. They identified the warm and cold fronts, the warm sector, and the characteristic pattern of clouds and weather associated with each stage of the cyclone's life.

Understanding mid-latitude cyclones is essential not only for weather forecasting but for understanding Earth's energy balance: these storms are the primary mechanism by which the midlatitude atmosphere transports heat from the tropics toward the poles in the form of warm air moving poleward in the warm sector and cold air flowing equatorward behind the cold front. Without this heat transport, the tropics would be far hotter and the poles far colder. Every storm represents the atmosphere trying to equalise a temperature difference that solar geometry continuously recreates.`,
      keyTerms: [
        { term: 'Mid-latitude cyclone',    def: 'A large (1,000–3,000 km) low-pressure weather system that forms along the polar front in the middle latitudes (30°–70°). Rotates counterclockwise in the NH (clockwise in SH) due to the Coriolis effect. Associated with warm and cold fronts, extensive cloud, precipitation, and strong winds. Moves generally eastward, steered by the jet stream.' },
        { term: 'Cyclogenesis',            def: 'The formation and intensification of a cyclone. Most commonly occurs along the polar front where horizontal temperature gradients are strong, and is triggered by upper-level divergence (jet stream dynamics) that reduces surface pressure. "Bomb cyclogenesis" (bombogenesis): extremely rapid deepening, defined as surface pressure falling ≥24 hPa in 24 hours.' },
        { term: 'Warm sector',             def: 'The triangular region of warm, moist air between the warm front (ahead) and cold front (behind) of a mature mid-latitude cyclone. Conditions: mild temperatures, high humidity, southerly winds (in NH), often cloudy with drizzle or fog. After the cold front passes and the warm sector is lifted, the cyclone begins to occlude.' },
        { term: 'Coriolis effect',         def: "The apparent deflection of moving objects on Earth's rotating surface — deflected to the right in the Northern Hemisphere, to the left in the Southern Hemisphere. Causes converging surface air in a low-pressure system to rotate: counterclockwise in the NH (cyclonic), clockwise in the SH. Does not cause rotation in systems smaller than ~100 km (no Coriolis-induced rotation in bathtubs or tornadoes to an appreciable degree)." },
        { term: 'Occlusion',               def: 'The stage in a midlatitude cyclone\'s life cycle when the faster-moving cold front catches up to the warm front, lifting the warm sector completely off the surface. The resulting occluded front is associated with a weakening storm. A cold-type occlusion (cold air behind cold front colder than air ahead of warm front) is most common over continents; a warm-type occlusion is common over oceans.' },
      ],
    },
    {
      type: 'concept',
      title: 'Life cycle, structure, and dynamics of the mid-latitude cyclone',
      body: `**Stage 1 — The polar front and initial wave.** Mid-latitude cyclones typically begin as a small disturbance (wave) along the polar front — the boundary between cold polar air to the north and warm tropical air to the south. The polar front is not always smooth; small perturbations (often triggered by upper-level jet stream dynamics) can grow into organised cyclones. The development begins when upper-level divergence (air spreading apart aloft) reduces the weight of the air column, lowering surface pressure. Air near the surface converges toward this area of low pressure, and the Coriolis effect deflects this converging air, causing the entire system to begin rotating counterclockwise (in the NH). A warm front develops on the eastern side (where warm air overrides retreating cold air) and a cold front develops on the western side (where cold air undercuts the retreating warm air).

**Stage 2 — The mature cyclone.** In the mature stage, the cyclone has a fully developed low-pressure centre, a comma-shaped cloud pattern visible on satellite images, and a warm sector between the warm and cold fronts. The warm sector is bounded ahead by the warm front (with its long bands of stratiform cloud and steady precipitation) and behind by the cold front (with its narrow band of convective, often intense precipitation). In the Northern Hemisphere, winds near the centre rotate counterclockwise: southerly winds in the warm sector, westerly to northwesterly winds behind the cold front, and easterly winds north of the centre. The central pressure of a mature cyclone can be 980–1,000 hPa (compared to the standard atmosphere of 1,013.25 hPa), with the most intense systems reaching 940–960 hPa. Cyclone intensity is often measured by central pressure: deeper = stronger.

**Stage 3 — Occlusion and decay.** The cold front moves faster than the warm front (cold fronts typically move at 40–80 km/h, warm fronts at 15–30 km/h). Eventually the cold front overtakes the warm front, lifting the warm sector air completely off the surface. This process, called **occlusion**, produces an **occluded front** — a composite boundary at the surface. Once the warm sector has been lifted off the surface, the temperature contrast driving the storm weakens (the storm has consumed its energy source), and the cyclone begins to decay, its central pressure rising and its winds diminishing over 12–72 hours. The decaying system may persist as a remnant low for days before fully dissipating.

**Bomb cyclogenesis.** Occasionally, cyclones undergo extremely rapid deepening — a process called **bomb cyclogenesis** or "bombogenesis" — defined as a drop in central pressure of ≥24 hPa in 24 hours (equivalent to ≥1 hPa per hour). This occurs when all ingredients for rapid development coincide: strong upper-level jet stream dynamics, high atmospheric instability, abundant moisture from a warm ocean surface, and a very sharp temperature gradient. Bomb cyclones most commonly form over the western North Atlantic and North Pacific in winter, where cold continental air meets warm ocean currents (Gulf Stream, Kuroshio). These storms can develop from modest beginnings to hurricane-force winds within 24 hours, catching mariners and forecasters off guard in the pre-satellite era.

**Pressure, winds, and the pressure gradient force.** The fundamental driver of wind in a cyclone is the **pressure gradient force** — air moves from high pressure toward low pressure, and the steeper the pressure gradient (closer the isobars), the stronger the wind. In a cyclone, the air converging toward the low-pressure centre is deflected by the Coriolis effect into circular motion around the low. At the surface, friction slows this circular motion and allows some inward spiral into the low; aloft (in the free atmosphere, above the friction layer), winds closely follow the isobars. This balance between pressure gradient force, Coriolis force, and centrifugal force produces the **gradient wind** — the theoretical wind speed along curved isobars — and the closely related **geostrophic wind** along straight isobars. Meteorologists use these relationships to read wind speed and direction directly from surface pressure maps.`,
      cards: [
        {
          name: 'Cyclone Life Cycle',
          icon: Wind,
          color: BRAND.accent,
          desc: 'Stage 1 (Incipient): polar front perturbation, upper-level divergence lowers surface pressure, rotation begins. Stage 2 (Mature): fully developed warm/cold fronts, comma cloud, central pressure 980–1000 hPa, warm sector intact. Stage 3 (Occlusion): cold front overtakes warm front, warm sector lifted off surface, temperature contrast weakens. Stage 4 (Decay): pressure rises, winds diminish, system dissipates 12–72 hours after occlusion.',
          examples: 'January 2018 "Bomb cyclone": NE US coast, central pressure dropped 59 hPa in 24 hours · Great Storm of 1987: UK, 15 million trees felled, 987 hPa centre · 1993 "Storm of the Century": US, 280 fatalities, 1 million evacuated, 40-state impact',
        },
        {
          name: 'Structure: Fronts, Clouds, and Precipitation',
          icon: Globe,
          color: BRAND.jade,
          desc: 'North of centre: cold air, overcast, light precipitation. Warm sector: warm/moist, often low cloud, fog, drizzle. Ahead of warm front (E of centre): Ci→Cs→As→Ns cloud sequence, steady rain/snow over 500–1000 km. At/behind cold front (W of centre): squall line or broken convective showers, rapid clearing. Comma cloud pattern visible from satellite: the cloud wraps counterclockwise around the low centre.',
          examples: `Nor\'easter: strong mP cyclone tracking up US East Coast, nor\'easterly winds at coast, heavy snow inland · European depression: steered by Atlantic jet stream, typically tracks from Atlantic into UK/Norway · "Miller B" cyclone: forms over Gulf of Mexico, tracks NE — classic US Southeast snowstorm track`,
        },
        {
          name: 'Pressure, Winds, and Coriolis',
          icon: Sun,
          color: BRAND.gold,
          desc: 'Pressure gradient force: from high to low pressure, proportional to isobar spacing. Coriolis: deflects NH winds to the right, SH to left. Geostrophic wind: balance of PGF and Coriolis → parallel to isobars (above friction layer). Gradient wind: adds centrifugal force for curved flow. Surface friction: causes inward spiral into low (convergence), lifting air. Cyclonic rotation = counterclockwise in NH. Anticyclone (high pressure) = clockwise NH = divergence at surface.',
          examples: 'Reading a surface map: closely spaced isobars → strong winds; widely spaced → light winds · Cyclone intensification: warming SST increases surface heat and moisture flux → deepens low · Southern hemisphere cyclone: same physics, clockwise rotation instead',
        },
      ],
    },
    {
      type: 'quiz',
      questions: [
        {
          q: "A satellite image shows a large comma-shaped cloud system over the North Atlantic. The leading edge (east/northeast of the cloud head) shows a long broad band of clouds, while the trailing edge (southwest) shows a narrow arc of convective cloud. An observer in a ship beneath the 'head' of the comma cloud is in the warm sector of the storm. Describe the weather sequence the ship will experience as the storm's cold front passes over it.",
          a: [
            "The ship will experience a gradual, multi-day improvement as the cold front slowly approaches, eventually bringing a period of high cirrus clouds before the front arrives as a gentle band of light drizzle; temperatures will cool slowly over several days",
            "As the cold front approaches, the ship will experience increasing southerly winds and rising temperatures in the warm sector; when the cold front passes, there will be a sharp wind shift (e.g., from southwesterly to northwesterly), a sudden temperature drop, rapidly rising atmospheric pressure, and brief but intense precipitation (squalls or thunderstorms) at the front, followed by clearing skies and drier air",
            "Cold fronts do not affect ships at sea because the marine surface layer absorbs the temperature contrast between air masses; the only significant weather change at sea is an increase in swell height due to the pressure gradient, not any frontal precipitation or temperature change",
            "The ship will experience the cold front as a long period of steady precipitation lasting 24–48 hours as the front slowly passes; the temperature change will be gradual (over 2–3 days) and the wind will shift only after the precipitation has ended",
          ],
          correct: 1,
          explain: "A slow multi-day approach with gentle drizzle (A) describes a warm front, not a cold front — warm fronts have gradual cloud sequences and gentle precipitation; cold fronts are rapid and intense. Cold fronts absolutely affect ships at sea (C) — some of the most violent frontal passages occur over oceans where there is no surface friction to slow wind speeds; the temperature contrast between tropical and polar air is sharp even at sea, and cold front squalls at sea are among the most dangerous conditions for mariners. A 24–48-hour slow passage (D) again describes warm front characteristics; cold fronts typically pass a given point in less than 1–6 hours. The correct answer is B: in the warm sector (between warm and cold fronts), the ship is experiencing mild, moist southwesterly winds. The cold front to the southwest is approaching at 40–80 km/h. As it arrives, the front undercuts the warm sector air in hours. The sequence of events at a classic cold front passage: (1) pressure trough deepens → winds back slightly and increase; (2) squall line or thunderstorms erupt as the warm moist air is forced abruptly upward; (3) front passes — winds shift from SW to NW (a clockwise veer in the NH), temperature drops sharply (may be 5–15°C within an hour), pressure rises rapidly (1–3 hPa/hr), precipitation intensity peaks then stops; (4) within hours, skies clear from the west, visibility improves dramatically, and fresh cold air replaces the humid warm sector air.",
        },
        {
          q: "In January 2018, a storm over the western North Atlantic deepened from 990 hPa to 931 hPa in 24 hours — a drop of 59 hPa, qualifying as a 'bomb cyclone' by a large margin. What physical conditions enabled such rapid intensification, and why are bomb cyclones most common over warm ocean currents in winter?",
          a: [
            "Bomb cyclones form when the pressure gradient force exceeds the Coriolis force by more than normal; this occurs in winter when the Coriolis parameter is at its annual minimum due to Earth's orbital position; the warm ocean is incidental — any strong surface temperature gradient could trigger the same process",
            "Rapid intensification (bomb cyclogenesis) requires the combination of: strong upper-level jet stream dynamics (jet streak divergence) reducing surface pressure rapidly; a large horizontal temperature gradient providing the thermodynamic energy; and a warm ocean surface supplying sensible and latent heat to the developing storm; winter western ocean margins (Gulf Stream, Kuroshio) provide all three ingredients simultaneously — cold air from the continent meets warm water, creating extreme air-sea temperature contrasts and abundant moisture for latent heat release",
            "Bomb cyclones are products of internal atmospheric resonance — standing waves between the tropopause and the surface amplify under specific geometric conditions; the warm ocean current keeps the atmosphere from reaching the resonant state until winter, when increased atmospheric stability triggers the resonance; once triggered, pressure drops at a rate limited only by the speed of sound waves in the troposphere",
            "The primary driver of bomb cyclogenesis is ocean current speed — faster currents like the Gulf Stream inject kinetic energy into the overlying atmosphere through surface friction; this mechanical energy input directly spins up the developing cyclone; the warm temperature of the Gulf Stream is secondary to its velocity in driving rapid cyclone development",
          ],
          correct: 1,
          explain: "The Coriolis parameter does not vary with Earth's orbital position (A) — it varies with latitude (f = 2Ω sinφ), not with season; Earth's orbital position (perihelion in January, aphelion in July) has negligible effect on the Coriolis parameter. Atmospheric resonance (C) is not a recognised mechanism of bomb cyclogenesis; standing wave resonance between tropopause and surface is not how operational meteorology explains rapid deepening. Ocean current kinetic energy (D) is negligible relative to thermodynamic energy in driving cyclogenesis; ocean currents flow at 0.5–2 m/s, while atmospheric processes are driven by temperature and moisture fluxes orders of magnitude more energetic than mechanical friction from slow ocean flow. The correct answer is B: bomb cyclogenesis requires the simultaneous presence of three factors. First, jet stream dynamics: a jet streak (region of maximum wind in the jet stream) produces strong upper-level divergence on its left exit side or right entrance side; this divergence reduces the weight of the air column, rapidly lowering surface pressure. Second, baroclinic instability: a strong horizontal temperature gradient (e.g., cold −20°C continental air adjacent to +20°C Gulf Stream water) provides the available potential energy for rapid cyclone growth through baroclinic instability theory. Third, oceanic heat and moisture flux: cold air flowing over warm ocean is heated and humidified rapidly; the latent heat released when this moisture condenses in the developing storm further reduces the storm's central pressure through warming of the air column (warm air is less dense = lower surface pressure). Winter western ocean boundaries (Gulf Stream, Kuroshio) concentrate all three: the strongest continental cold air outbreaks, the warmest nearby SST, and the most active jet stream.",
        },
        {
          q: "Mid-latitude cyclones carry warm air poleward and cold air equatorward simultaneously. Why is this exchange fundamental to Earth's climate system, and what would happen to global temperatures if midlatitude cyclones suddenly ceased to form?",
          a: [
            "Mid-latitude cyclones carry heat poleward and cold air equatorward purely as a mechanical effect of their rotation; the climate importance is primarily regional — cyclones keep midlatitude regions from drying out by delivering precipitation; without cyclones, precipitation would decrease in the midlatitudes but global temperature gradients would be largely unchanged",
            "Mid-latitude cyclones are the primary mechanism for poleward atmospheric heat transport at midlatitudes; they carry warm, moist air poleward in their warm sectors and cold, dry air equatorward behind their cold fronts; if cyclones ceased, the poleward heat transport would collapse, the tropics would become significantly warmer, the poles far colder, and the equator-to-pole temperature gradient would increase dramatically — which would ironically tend to regenerate cyclones through baroclinic instability",
            "Mid-latitude cyclones do not transport significant heat poleward; the main heat transport mechanism at all latitudes is ocean currents, which carry warm water from the tropics toward the poles continuously; mid-latitude atmospheric cyclones are local weather features that redistribute heat regionally but make no net contribution to the global poleward heat flux",
            "Mid-latitude cyclones cool the tropics by drawing warm air away from lower latitudes and cool the poles by mixing polar air with warmer air from below; if they ceased, both the tropics and poles would reach temperatures closer to their solar equilibrium, but the change would be modest because most of Earth's heat transport occurs in the stratosphere, not the troposphere",
          ],
          correct: 1,
          explain: "Cyclones do transport precipitation-producing systems to midlatitudes (A) but the mechanism and climate significance are far broader than regional precipitation distribution; the global temperature gradient argument in A is incorrect. Oceans do transport heat poleward (~2 PW out of ~7 PW total), but atmospheric transport, dominated by midlatitude weather systems (transient eddies, including cyclones), carries ~5 PW — significantly more; the claim that ocean currents dominate all latitudes (C) is inaccurate, especially in the midlatitudes where atmospheric eddy transport is dominant. Heat transport is primarily in the troposphere, not the stratosphere (D) — the stratosphere has much lower density and different dynamics; stratospheric heat transport is secondary. The correct answer is B: this is the thermodynamic core of why midlatitude cyclones exist. Earth continuously produces a large equator-to-pole temperature contrast (tropical regions in energy surplus, polar regions in energy deficit). The atmosphere must transport this energy poleward. At low latitudes, the Hadley circulation (organized direct overturning) carries most of the heat. At midlatitudes, the Hadley cell breaks down and the heat transport is carried by transient eddies — cyclones and anticyclones — which carry warm air poleward in their warm sectors and cold air equatorward in their cold sectors. If these cyclones suddenly ceased, atmospheric poleward heat transport at midlatitudes would nearly stop: the poles would cool dramatically (perhaps 20–30°C colder than today), the tropics would warm significantly. The increased temperature gradient would then increase baroclinic instability and the tendency to form cyclones — a negative feedback that would eventually restore cyclone activity. This self-regulating cycle is part of what determines the actual climate state of the midlatitudes.",
        },
        {
          q: "The Norwegian Cyclone Model describes an idealised life cycle for midlatitude cyclones, yet forecasters routinely encounter storms that deviate substantially from this model. Why does the Norwegian Cyclone Model remain a foundational tool in meteorology despite these deviations, and what environmental factor most commonly causes real cyclones to diverge from the model's predicted structure?",
          a: [
            "The Norwegian Cyclone Model remains useful because it is mathematically exact; real cyclones deviate only when data collection errors corrupt the initial analysis; with perfect observations, every midlatitude storm would precisely follow the model's predicted sequence of stages from incipient wave to occlusion",
            "The Norwegian Cyclone Model provides an indispensable conceptual framework — a idealised template of frontal structure, cloud patterns, and pressure evolution — against which forecasters can compare observations to identify where actual storms are in their life cycle and what weather hazards are imminent; real storms deviate primarily because vertical wind shear in the jet stream tilts the upper-level trough away from the surface low, altering the coupling between upper-level dynamics and surface development and sometimes producing asymmetric or elongated frontal structures rather than the textbook comma shape",
            "The Norwegian Cyclone Model is no longer considered useful in modern meteorology; it has been entirely replaced by numerical weather prediction models, which make the conceptual model obsolete; forecasters today never refer to it; its only remaining role is historical, as a reminder of how primitive pre-computer forecasting was",
            "The Norwegian Cyclone Model remains relevant because it accurately describes tropical cyclones, which always follow the model precisely; midlatitude cyclones deviate from it frequently, but since midlatitude weather is inherently chaotic and unpredictable, the deviations are irrelevant; forecasters only apply the model to tropical systems",
          ],
          correct: 1,
          explain: "The Norwegian Cyclone Model is not mathematically exact nor based on perfect-observation assumptions (A) — it is a conceptual physical model derived from observational synthesis, not from exact mathematical solutions; real atmospheres always have heterogeneous air masses, variable terrain, and complex upper-level flow patterns that the idealised model cannot fully capture. The model is absolutely still used in modern meteorology (C) — operational forecasters in every national weather service use it as a diagnostic tool alongside NWP output; it is taught in every introductory meteorology course and provides essential physical reasoning for interpreting model guidance and satellite imagery. The Norwegian Cyclone Model was specifically developed for midlatitude (extratropical) cyclones, not tropical cyclones (D) — tropical cyclones have a completely different structure and energy source (latent heat from ocean evaporation rather than baroclinic temperature contrasts) and are described by entirely different conceptual models. The correct answer is B: the Norwegian Cyclone Model — developed by Vilhelm Bjerknes and colleagues in the 1910s–1920s — provides an invaluable conceptual skeleton: the warm front to the northeast, cold front to the southwest, warm sector between them, comma cloud pattern, characteristic cloud sequences, and pressure pattern all give forecasters a reference structure for interpreting observations. Real storms deviate most significantly when the upper-level jet stream is tilted or when the trough-low vertical relationship is unfavourable — for example, when a negatively tilted trough (tilted from SW to NE) creates an asymmetric forcing pattern, or when the surface low forms on the forward flank of the jet rather than in the classical position. Ocean surface temperature variability, terrain effects (especially mountain ranges), and the specific properties of the colliding air masses also produce systematic deviations. Despite these deviations, the model's conceptual anatomy helps forecasters identify which frontal features are present, which are absent, and what that implies for local weather hazards.",
        },
      ],
    },
  ],
}

export default midLatitudeCyclone
