import { Wind, Globe, Sun } from 'lucide-react'
import { BRAND } from '@/lib/brand'
import type { Lesson } from './types'

const tropicalCyclones: Lesson = {
  id: 'atmo-101-1-2-4',
  title: 'Tropical Cyclones: Hurricanes and Typhoons',
  track: 'atm',
  trackName: 'Meteorology',
  level: 'Beginner',
  duration: '12 min',
  xpReward: 140,
  description: "Tropical cyclones are the most powerful storms on Earth — self-organized heat engines that extract energy from warm ocean water and convert it into the most destructive wind and rain events in the natural world.",
  sources: [
    { org: 'NOAA',     title: 'National Hurricane Center',                                 url: 'https://www.nhc.noaa.gov/' },
    { org: 'NOAA',     title: 'Atlantic Oceanographic and Meteorological Laboratory — Hurricanes', url: 'https://www.aoml.noaa.gov/hurricane-research/' },
    { org: 'OpenStax', title: 'Introduction to Atmospheric Science, Ch. 10 (CC-BY 4.0)',  url: 'https://openstax.org/books/introduction-oceanography' },
    { org: 'UCAR',     title: 'Hurricanes — Structure and Formation',                     url: 'https://scied.ucar.edu/learning-zone/storms/hurricanes' },
    { org: 'AMS',      title: 'Glossary of Meteorology',                                  url: 'https://glossary.ametsoc.org/' },
  ],
  sections: [
    {
      type: 'intro',
      title: 'Oceans of energy',
      body: `In the summer of 1992, Hurricane Andrew crossed the Bahamas and made landfall south of Miami, Florida as a Category 5 storm. Its eyewall winds exceeded 265 km/h (165 mph), its storm surge reached 5 metres (16 feet) above sea level in some locations, and within hours it had caused $27 billion (1992 dollars) in damage and left 175,000 people homeless. Andrew remains one of the most destructive natural disasters in US history. In 2005, Hurricane Katrina — also a major hurricane — killed over 1,800 people and caused $125 billion in damage primarily through catastrophic storm surge flooding of New Orleans. These are not geological events measured in millennia; they are single atmospheric storms, lasting days, with effects comparable to some of the most violent events in Earth's history.

A **tropical cyclone** is a warm-core, non-frontal low-pressure system that draws its energy from the thermodynamic gradient between a warm tropical ocean and the cold upper troposphere. Unlike mid-latitude cyclones, which derive their energy from horizontal temperature contrasts between air masses (baroclinic instability), tropical cyclones are driven by the release of latent heat from water vapour evaporating from a warm ocean. They are called **hurricanes** in the North Atlantic and eastern North Pacific, **typhoons** in the western North Pacific, **cyclones** in the Indian Ocean and South Pacific, and **tropical cyclones** generically. All are the same meteorological phenomenon.

Tropical cyclones are a marvel of atmospheric self-organisation. An initially weak tropical disturbance, under the right conditions, can develop into a storm with an organised eye, eyewall, spiral rain bands, and sustained winds exceeding 280 km/h in extraordinary cases — all without the frontal structure that organises midlatitude storms. Understanding how this self-organisation occurs, what limits hurricane intensity, and how storms cause their most devastating impacts (not always the wind) is one of the most active areas of operational and research meteorology, with direct life-safety implications for hundreds of millions of people in coastal and island communities.`,
      keyTerms: [
        { term: 'Tropical cyclone',       def: 'A warm-core, non-frontal low-pressure system originating over tropical or subtropical waters, organised around a center of low pressure, with sustained surface winds ≥63 km/h (tropical storm) or ≥119 km/h (hurricane/typhoon/cyclone). Fuelled by latent heat released when ocean-evaporated water vapour condenses. Requires: warm ocean (≥26°C to ≥50 m depth), atmospheric instability, sufficient Coriolis effect (≥5° latitude), low vertical wind shear.' },
        { term: 'Eye',                    def: 'The calm, partially clear centre of a mature tropical cyclone, typically 30–65 km in diameter. Characterised by descending air (sinking motion), light winds, warm temperatures, and relatively clear skies. Surrounded by the eyewall. During eye passage, a brief period of calm may occur before the eyewall on the far side arrives. Smaller eyes are often associated with more intense storms.' },
        { term: 'Eyewall',               def: 'The ring of deep convective cumulonimbus clouds surrounding the eye of a tropical cyclone. The eyewall is the most intense part of the storm: maximum winds, heaviest precipitation, and strongest updrafts all occur here. Updraft speeds in the eyewall can exceed 50 m/s. Eyewall replacement cycles — when an outer eyewall contracts inward, displacing the inner eyewall — cause temporary intensity fluctuations.' },
        { term: 'Saffir-Simpson scale',   def: 'The Saffir-Simpson Hurricane Wind Scale (SSHWS), classifying tropical cyclones by sustained wind speed: Cat 1 (74–95 mph/119–153 km/h), Cat 2 (96–110 mph), Cat 3 (111–129 mph, "major hurricane"), Cat 4 (130–156 mph), Cat 5 (≥157 mph/252 km/h). Category does not account for storm surge, rainfall, or storm size — all of which can be independently deadly.' },
        { term: 'Storm surge',            def: 'The abnormal rise of ocean water above normal tide level caused by a tropical cyclone. The primary cause of tropical cyclone deaths. Produced by wind stress pushing water onshore and by the low-pressure centre raising sea level. Surges of 5–9 metres have been recorded in intense storms making landfall at low tide. Height depends on storm intensity, size, angle of approach, speed, and coastal bathymetry.' },
      ],
    },
    {
      type: 'concept',
      title: 'Formation, structure, intensity, and hazards',
      body: `**Formation requirements and the Carnot engine analogy.** Tropical cyclone formation (tropical cyclogenesis) requires four key ingredients: (1) a warm ocean surface of ≥26°C extending to at least 50 m depth (so that storm-induced upwelling doesn't rapidly cool the surface); (2) atmospheric instability to support deep convection; (3) sufficient **Coriolis force** (at least ~5° from the equator) to impart rotation to converging surface air; and (4) low **vertical wind shear** (the change in wind speed/direction with altitude) so that the developing warm core is not tilted and torn apart by upper-level winds. This last condition explains why tropical cyclones rarely survive over land (where shear often increases), during El Niño years in the Atlantic (when upper-level westerlies strengthen), or when they encounter cold upwelled water.

The classic thermodynamic model of a tropical cyclone treats it as a Carnot heat engine. Warm, moist air near the ocean surface is the "fuel": it evaporates ocean water (gaining latent heat), flows inward at the surface toward the low-pressure centre, ascends in the eyewall, releases latent heat (warming the storm), and flows outward at high altitude in the storm's outflow layer, cooling and losing heat to space. The temperature difference between the warm ocean surface (~28°C) and the cold upper troposphere (−70°C) is the thermodynamic driver of the engine. The **maximum potential intensity (MPI)** — the theoretical upper limit of storm intensity — is determined primarily by this temperature difference and the thermodynamic properties of the atmosphere. Actual storms rarely reach their MPI due to wind shear, dry air entrainment, and ocean cooling.

**Eye and eyewall dynamics.** The eye of a tropical cyclone is produced by subsiding air at the centre of the rotation. As the storm's inflow spirals toward the centre, the strong centrifugal force (associated with rapid rotation) eventually prevents air from reaching the very centre. Air that overshoots the centre must subside, producing the warm, clear eye. The **eyewall** is a ring of intense convection just outside the eye — the steeply sloping inner boundary of the eyewall is sometimes called the "coliseum" and can tower 12–15 km above the sea surface. Temperatures inside the eye at the upper levels can be 10–15°C warmer than the surrounding storm at the same altitude, and this warm core aloft is the thermodynamic signature of a tropical cyclone that distinguishes it from a mid-latitude low.

**Eyewall replacement cycles (ERCs) and intensity fluctuations.** Intense tropical cyclones (typically Category 4–5) frequently undergo **eyewall replacement cycles**: an outer ring of convection forms at a radius of 50–100 km from the centre, outside the original eyewall. This outer eyewall contracts inward, absorbing the inflow that would otherwise sustain the original inner eyewall. The inner eyewall dissipates, and the outer eyewall becomes the new, broader eyewall. During an ERC, the storm's winds temporarily decrease as the original eyewall weakens, then often re-intensify as the new, contracting outer eyewall spins up. ERCs are a major challenge to intensity forecasting and explain the intensity fluctuations observed in major hurricanes like Katrina (2005), Patricia (2015), and Dorian (2019).

**Hazards: wind, surge, rain, and the inland threat.** The **Saffir-Simpson scale** classifies tropical cyclone intensity by maximum sustained wind, but wind is often not the primary killer. In the United States, **storm surge** — the wall of ocean water pushed ashore by the storm — has historically caused the majority of tropical cyclone fatalities. The infamous Galveston Hurricane of 1900 killed 6,000–12,000 people primarily through storm surge, making it the deadliest natural disaster in US history. Hurricane Katrina's storm surge exceeded 8 metres in parts of Mississippi. **Freshwater flooding from rainfall** is the second leading cause of tropical cyclone fatalities: slow-moving storms can dump 1,000–1,500 mm of rainfall over days, causing catastrophic inland flooding far from the coast. Hurricane Harvey (2017) produced the highest rainfall totals ever measured in a US tropical system (~1,320 mm/52 inches in parts of Texas), flooding thousands of homes 100+ km inland.`,
      cards: [
        {
          name: 'Formation: The Four Requirements',
          icon: Sun,
          color: BRAND.gold,
          desc: 'Warm ocean ≥26°C to ≥50 m depth: provides latent heat fuel. Atmospheric instability: allows deep convection. Coriolis force (≥5° lat): imparts rotation. Low vertical wind shear (<10–15 m/s through troposphere): allows warm core to remain vertically stacked. El Niño suppresses Atlantic TC activity (increased shear). La Niña enhances Atlantic activity. Seasonal peak: late Aug–Oct in NH Atlantic (peak warm SST + low shear).',
          examples: 'TC formation zones: NW Pacific (most active basin, typhoons), NE Pacific, N Atlantic (hurricane season Jun 1–Nov 30), N Indian, SW Indian, SE Pacific. Rare Atlantic storms: Tropical Storm Peter (2021), 18°N — documented within typical formation zone · Hurricane Eta (2020): rapid intensification over warm Caribbean; Cat 4 at landfall Honduras',
        },
        {
          name: 'Eye, Eyewall, and Eyewall Replacement',
          icon: Globe,
          color: BRAND.jade,
          desc: 'Eye: 30–65 km diameter, descending air, calm (0–15 km/h), warm upper levels, partial clearing. Eyewall: ring of Cb, max winds, heavy rain, 50 m/s updrafts. Eyewall replacement cycle (ERC): outer rainband contracts inward → inner eyewall replaced by larger-diameter outer eyewall → temporary weakening then re-intensification → broader wind field. Rapid intensification: ≥35 mph increase/24 hr. Patricia 2015: lowest Atlantic/Pacific pressure ever recorded (872 hPa), 200 mph sustained.',
          examples: 'Hurricane Katrina 2005: Cat 5 in Gulf (902 hPa), landfall Cat 3 after weakening during ERC · Typhoon Haiyan 2013: 315 km/h gusts (all-time record gust), 6,300 deaths Philippines · Hurricane Dorian 2019: stalled Cat 5 over Bahamas 24+ hours, catastrophic surge + wind destruction',
        },
        {
          name: 'Storm Surge, Rain Flooding, and Wind Damage',
          icon: Wind,
          color: BRAND.accent,
          desc: 'Storm surge: #1 killer in US TCs historically; 5–9 m possible for intense landfalling Cat 4–5; depends on storm size, angle, speed, bathymetry. Rain flooding: slow-moving storms; Harvey 2017: 1,320 mm/52 inches SE Texas, >$125 billion damage. Wind damage: Cat 3+ destroys unreinforced masonry; Cat 5 destroys most structures. Inland flooding kills hundreds of km from coast. NHC now issues Potential Storm Surge Flooding maps separate from Saffir-Simpson category.',
          examples: 'Galveston 1900: Cat 4, 6,000–12,000 deaths from surge — deadliest US natural disaster · Katrina 2005: 8 m surge Mississippi coast, levee failure floods New Orleans, 1,800+ deaths · Harvey 2017: nearly stationary Cat 4 landfall, catastrophic rain flooding, 103 deaths, $125 billion',
        },
      ],
    },
    {
      type: 'quiz',
      questions: [
        {
          q: "A Category 5 hurricane makes landfall on a densely populated coastline. Emergency managers announce a mandatory evacuation for coastal zones. Some residents refuse to leave, citing their experience surviving previous Category 1 and 2 hurricanes at the same location. What specific physical hazard of major hurricanes most likely to kill people who survived weaker storms in the same area, and why is it particularly difficult for people without prior experience to appreciate?",
          a: [
            "The primary additional hazard in a Category 5 compared to Category 1 is wind speed; Category 5 winds (>157 mph) are capable of structurally destroying well-built homes in ways that Category 1 winds (74–95 mph) cannot; experienced survivors of weaker storms simply underestimate how different the wind damage will be",
            "The primary killer of residents who refuse to evacuate a Category 5 is storm surge — a wall of ocean water that inundates the coast to 5–9 metres above sea level; Category 1 storms typically produce surges of only 1–2 metres; a Category 5 surge can arrive as a rapidly rising flood of ocean water that traps people in structures that previously served them safely, drowning them in their own homes; the surge is invisible until it arrives and cannot be survived without prior evacuation",
            "The primary additional hazard is rainfall flooding; Category 5 hurricanes produce twice as much rain as Category 1 storms because the stronger eyewall forces more moisture upward; the flooding arrives 24 hours after the storm centre, giving people time to evacuate after deciding whether the storm was bad enough",
            "The primary killer is wind-driven debris; while Category 1 storms produce flying debris (branches, signs), Category 5 winds are capable of launching vehicles and structural materials at ballistic speeds; people who survived previous storms in their homes are not aware that their same structures will become death traps from debris penetration at Category 5 winds",
          ],
          correct: 1,
          explain: "Wind damage (A) is a real hazard that scales dramatically with category, but the survival risk from wind failure of structures is lower than storm surge for people who stay in well-built homes — even Cat 5 winds do not kill as many people as the surge when the surge is substantial. Rainfall flooding (C) can occur 24+ hours after landfall for slow storms, but for a typical fast-moving Cat 5 at the coast, storm surge arrives simultaneously with the storm; the claim that rainfall arrives 24 hours later and always provides evacuation time is incorrect — Harvey (2017) is an exception where the slow movement allowed this, but it is not the rule. Wind-driven debris (D) is a genuine hazard, but historically, storm surge has caused far more fatalities than debris in major US hurricane events. The correct answer is B: storm surge is consistently the dominant killer in major US hurricane events, yet it is psychologically the most underappreciated hazard because it is not directly visible during evacuation decision-making. In a Category 1 hurricane, surge is typically 1–2 metres — unpleasant but often survivable at upper floors. A Category 5 hurricane can produce surges of 5–9 metres in appropriate coastal geometries, arriving as rapidly rising seawater that fills a building from the bottom up within minutes. Unlike wind (which pushes objects horizontally), surge traps people who cannot escape upward fast enough. The 1900 Galveston hurricane, the deadliest US natural disaster, killed 6,000–12,000 people primarily through 3–6 metre surge on an island with a maximum elevation of 2.7 metres. The Saffir-Simpson category scale uses only wind speed and does not convey surge potential — which is why NOAA now provides separate Potential Storm Surge Flooding maps for every threatening storm.",
        },
        {
          q: "A tropical cyclone undergoing rapid intensification in the Gulf of Mexico suddenly weakens by 25 mph in a 6-hour period, puzzling forecasters who expected continued intensification over the warm waters. Satellite images show an outer band of convection has formed at a radius of 100 km from the centre. What is likely occurring, and what will happen to the storm over the next 24–36 hours?",
          a: [
            "An eyewall replacement cycle (ERC) has begun: an outer eyewall has formed and is competing with the original inner eyewall for inflow moisture; the inner eyewall will weaken as its inflow is cut off; after the inner eyewall dissipates, the outer eyewall will contract, spin up, and often re-intensify the storm, but with a larger-diameter eyewall and therefore a broader wind field",
            "The storm is encountering vertical wind shear from an approaching upper-level trough; shear is displacing the warm core aloft away from the low-pressure centre, weakening the storm's organised convection; the outer convective band is an artefact of the shear-induced asymmetry; the storm will likely weaken steadily and dissipate over the next 24 hours",
            "The outer convective band indicates the storm has made landfall on an uncharted shallow bank, which has cooled the sea surface through upwelling; the resulting cool water prevents ocean-atmosphere heat exchange, causing the storm to weaken; the outer band is rain from the storm spreading over the land surface",
            "The weakening is a normal diurnal signal — tropical cyclones are universally observed to weaken by 20–30 mph during daytime hours because solar radiation heats the upper troposphere and reduces the temperature contrast driving the storm; the outer band indicates normal afternoon convective activity; the storm will re-intensify after sunset",
          ],
          correct: 0,
          explain: "Wind shear (B) is a plausible weakening mechanism and the diagnosis is physically reasonable, but the specific observation — an outer band of convection at 100 km from the centre — is not characteristic of shear-induced weakening; shear typically displaces the deep convection to one side of the centre, not symmetrically at a fixed radius. An uncharted shallow bank (C) is not a realistic diagnosis for an open-ocean Gulf scenario; moreover, storms do not produce outer rainbands by spreading over land — the outer band is at sea, not over land. Diurnal intensity oscillation (D) is observed in some tropical cyclones, but the magnitude (20–30 mph in 6 hours) and the specific pattern of an outer rainband at fixed radius are not consistent with a simple diurnal signal, which is typically ≤10 mph. The correct answer is A: an eyewall replacement cycle (ERC) is the most consistent explanation for the described pattern — temporary weakening of the inner eyewall coinciding with the formation of an outer rainband at 50–100+ km from the centre. In an ERC, the outer rainband organises into a coherent convective ring that contracts inward, competing with the original eyewall for the storm's inflow (moisture and energy from the warm ocean surface). As the outer eyewall strengthens, it cuts off the inflow to the inner eyewall, which weakens and eventually dissipates. The outer eyewall then becomes the new primary eyewall. During this transition, wind speeds at the radius of maximum winds (RMW) decrease because the new, larger-radius eyewall has higher angular momentum requirements, but total wind field expands. After the ERC completes (typically 12–48 hours), storms often re-intensify — sometimes to or beyond their previous intensity. ERCs are the primary source of difficulty in intensity forecasting for major tropical cyclones.",
        },
        {
          q: "Tropical cyclone tracks are controlled by large-scale steering flows, and climate models project changes in these steering flows as greenhouse gas concentrations increase. Beyond track changes, what physical characteristics of tropical cyclones are projected to change as the climate warms, and why?",
          a: [
            "Climate warming will increase the number of tropical cyclones globally because warmer ocean temperatures provide more energy for storm formation; the total count of named storms per season will approximately double by 2100, and all storms will be more intense on average",
            "Climate warming is projected to: increase the maximum potential intensity of the strongest storms (because a warmer ocean provides more fuel and the thermodynamic efficiency of the heat engine increases with greater ocean-atmosphere temperature contrast); increase rainfall rates within tropical cyclones (because warmer air holds ~7% more water vapour per degree C — Clausius-Clapeyron); increase the geographic range of tropical cyclones poleward (as suitable warm SST extends to higher latitudes); and potentially increase the proportion of storms that reach major intensity, though the total number of storms may not increase and might even decrease",
            "Climate warming will have no effect on tropical cyclone characteristics because tropical cyclone intensity is limited by the Coriolis effect, which does not change with temperature; the only projected change is a slight poleward shift in tracks as the subtropical high-pressure belt expands",
            "Warmer oceans will weaken tropical cyclones by increasing vertical wind shear globally; the increased SST leads to stronger upper-level winds via the thermal wind relationship, which destroys the organised convection needed for tropical cyclones; future tropical cyclone seasons will have fewer intense storms as a result of this shear increase",
          ],
          correct: 1,
          explain: "The total global count of tropical cyclones increasing approximately linearly with warming (A) is not supported by research; most modelling studies project that the total frequency of tropical cyclones may remain stable or even decrease as warming increases atmospheric stability (through warming aloft), while the proportion of storms reaching major intensity increases. Tropical cyclone intensity is not limited by the Coriolis effect (C) — it is limited by ocean temperature, atmospheric thermodynamics, and wind shear; Coriolis effect controls the rotation and development threshold (explaining why TCs don't form at the equator) but not the upper bound on intensity. Increased SST does not universally increase wind shear globally (D) — regional shear changes are complex and model-dependent; in the Atlantic, some models do project increased shear during El Niño-like patterns, but this is not a universal global signal from warming alone. The correct answer is B: this represents the current scientific consensus from IPCC reports and the World Meteorological Organization. Three changes are most robustly projected: (1) Increased maximum intensity of the strongest storms — the theoretical maximum potential intensity (MPI) is proportional to the thermodynamic disequilibrium between the warm ocean and cold upper troposphere; as SST warms faster than the upper troposphere, MPI increases; (2) Increased rainfall rates — the Clausius-Clapeyron relationship dictates that saturation vapour pressure increases ~7% per °C; warmer tropical cyclones produce ~10–20% more rainfall per storm; (3) Poleward expansion of TC activity — as warm SST (≥26°C) extends to higher latitudes, TCs can form and sustain at higher latitudes than historically observed.",
        },
        {
          q: "Tropical cyclones cannot form within approximately 5° of the equator, even when all other conditions (warm SST, atmospheric instability, low wind shear, moisture) are met. What physical force is absent at the equator that prevents cyclone development, and why does this same force become essential once a tropical disturbance is displaced to higher latitudes?",
          a: [
            "Tropical cyclones cannot form at the equator because solar insolation is too intense directly overhead, destabilising the atmosphere too rapidly and preventing the organised convection needed for tropical cyclogenesis; at higher latitudes, the oblique sun angle provides a more moderate energy input that allows organised storm development",
            "The Coriolis force — which deflects moving air to the right in the Northern Hemisphere and to the left in the Southern Hemisphere — is zero at the equator and increases with latitude; without Coriolis deflection, surface air converging toward a low-pressure centre flows straight inward and fills the low rather than being deflected into circular rotation; at ≥5° latitude, the Coriolis force is sufficient to deflect converging inflow into cyclonic rotation around the low, allowing the pressure deficit to be maintained as the storm organises and intensifies",
            "The equator lacks the horizontal temperature contrasts that power tropical cyclones; because the sun heats the equatorial region uniformly from above year-round, there are no temperature gradients to drive the pressure differences needed for cyclone formation; at higher latitudes, seasonal temperature variations create the gradients necessary for storm development",
            "Tropical cyclones are prevented from forming at the equator by the ITCZ, which occupies the equatorial band year-round and creates excessive atmospheric convergence that prevents the upper-level outflow needed for a developing cyclone; at 5° or more away from the ITCZ, upper-level divergence is sufficient to allow storm development",
          ],
          correct: 1,
          explain: "Solar insolation intensity at the equator (A) does not prevent organised convection — the tropics including the equatorial belt have some of the most vigorous convection on Earth (the ITCZ is directly on or near the equator); intense solar heating is, if anything, a prerequisite for tropical convection, not an obstacle. Horizontal temperature contrasts (C) describe the energy source for midlatitude baroclinic cyclones, not tropical cyclones — tropical cyclones are driven by the vertical temperature contrast between the warm ocean and the cold upper troposphere (a warm-core, non-baroclinic mechanism); horizontal temperature gradients are not required for tropical cyclogenesis. The ITCZ (D) is itself a zone of active convective development — it does not prevent tropical cyclones from forming and is in fact a common region of tropical disturbance initiation; the ITCZ constraint conflates the ITCZ's geographic relationship with the equator with the Coriolis constraint, and the ITCZ moves seasonally rather than being permanently equatorial. The correct answer is B: the Coriolis force arises from Earth's rotation and acts perpendicular to the velocity of any moving fluid on Earth's surface. It equals 2Ω sinφ × v, where Ω is Earth's rotation rate, φ is latitude, and v is the wind speed. At φ = 0 (the equator), sinφ = 0 and the Coriolis force vanishes entirely. Without this force, surface air converging inward toward a low-pressure centre has no deflecting force to redirect it into circular orbit around the low — instead it flows straight to the centre and fills the low, preventing a self-sustaining circulation from developing. At ~5° latitude, the Coriolis force is just barely sufficient (given typical tropical wind speeds) to deflect converging inflow into cyclonic rotation; the minimum latitude threshold of ~5° is therefore a fundamental requirement, not a statistical observation. As the disturbance organises and moves poleward, the increasing Coriolis force tightens the rotation and allows the storm to develop a well-defined low-pressure centre with sustained circular winds — the hallmark of a tropical cyclone.",
        },
      ],
    },
  ],
}

export default tropicalCyclones
