import { Thermometer, Sun, Wind, Activity, ArrowUp } from 'lucide-react'
import { BRAND } from '@/lib/brand'
import type { Lesson } from './types'

const heatWavesDroughtBlocking: Lesson = {
  id: 'atmo-101-1-4-3',
  title: 'Heat Waves, Drought, and Atmospheric Blocking',
  track: 'atm',
  trackName: 'Meteorology',
  level: 'Beginner',
  duration: '14 min',
  xpReward: 150,
  description: 'Heat waves kill more people annually in developed nations than any other weather hazard, yet they arrive silently and build gradually — lacking the obvious violence of tornadoes or hurricanes. Understanding how a sluggish feature of the upper atmosphere called a blocking high can park scorching conditions over a continent for weeks, and how soil moisture feedbacks amplify drought into catastrophe, reveals the most dangerous aspects of "quiet" extreme weather.',
  sources: [
    { org: 'WMO',     title: 'WMO Statement on the State of the Global Climate 2023',          url: 'https://public.wmo.int/en/our-mandate/climate/wmo-statement-state-of-global-climate' },
    { org: 'NOAA',    title: 'Heat Wave Climatology — Climate.gov',                           url: 'https://www.climate.gov/news-features/understanding-climate/heat-waves-climatology' },
    { org: 'ECMWF',   title: 'Atmospheric Blocking — ECMWF Research',                        url: 'https://www.ecmwf.int/' },
    { org: 'UCAR',    title: 'Drought — UCAR Center for Science Education',                   url: 'https://scied.ucar.edu/learning-zone/weather/drought' },
    { org: 'AMS',     title: 'AMS Glossary — Heat Wave, Blocking, Drought',                   url: 'https://glossary.ametsoc.org/' },
  ],
  sections: [
    {
      type: 'intro',
      title: 'The silent killer overhead',
      body: `In August 2003, a heat wave settled over western Europe and refused to leave for two weeks. In France alone, 14,800 people died — mostly elderly who lived alone in poorly-ventilated urban apartments. Across Europe, the death toll reached approximately 70,000, making it the deadliest weather disaster in European recorded history. Paris recorded its all-time temperature record: 40.4°C (104.7°F). Yet there were no gale-force winds, no flooding, no dramatic radar signatures. The atmosphere was, in one sense, remarkably quiet — too quiet. A massive dome of high pressure had settled over western Europe and stalled, blocking the normal westerly flow and creating a heat engine that ran uninterrupted for 14 days.

A **heat wave** is a prolonged period of excessively hot weather, often accompanied by high humidity. Unlike other extreme weather events, heat waves are defined relative to what is climatologically expected for a given location — a temperature of 40°C (104°F) is unremarkable in Phoenix, Arizona but catastrophic in London. The most dangerous heat waves combine three factors: daytime high temperatures well above the climatological average, nighttime temperatures that remain elevated (preventing human physiological recovery), and high humidity that limits evaporative cooling of the skin. The **wet-bulb globe temperature (WBGT)** is the most relevant physiological heat stress index, combining temperature, humidity, solar radiation, and wind to describe the actual cooling capacity of the environment.

The atmospheric mechanism behind most major heat waves is **atmospheric blocking**: the establishment of a persistent, quasi-stationary high-pressure ridge in the upper atmosphere that deflects the normal westerly flow around it. Blocking patterns can persist for days to weeks — extraordinarily long for atmospheric phenomena — because they represent a class of steady or slowly-evolving nonlinear wave states of the mid-latitude circulation. Understanding blocking is essential not just for predicting heat waves but for understanding why forecasting at the 7–14 day range remains difficult: models can struggle to predict the onset and especially the demise of blocking events.`,
      keyTerms: [
        { term: 'Atmospheric blocking', def: 'A large-scale, quasi-stationary mid-tropospheric ridge (or dipole) that persists for 5 or more days, deflecting the normal westerly flow around it. Blocking prevents the usual progression of weather systems from west to east, trapping air masses and extreme conditions beneath the ridge. Most common in the North Atlantic, North Pacific, and Russian sectors. Classified as Omega blocks (a ridge flanked by two troughs, resembling the Greek letter Ω) or Rex blocks (a high directly poleward of a low).' },
        { term: 'Heat wave',           def: 'A prolonged period of unusually high temperatures relative to local climatology, typically lasting 3 or more days. Various definitions exist: NOAA defines a heat wave as ≥2 days of maximum temperature >32°C (90°F); WMO as ≥5 consecutive days exceeding the 90th percentile of maximum temperature. The most dangerous heat waves combine: high daytime maxima, high nighttime minima (no nocturnal recovery), high humidity (limiting sweat evaporation), and calm winds (reducing convective cooling).' },
        { term: 'Drought',             def: 'A sustained period of below-normal precipitation resulting in water deficits relative to the normal demand for water. Types: meteorological drought (precipitation deficit alone); agricultural drought (soil moisture insufficient for crops); hydrological drought (reduced streamflow and groundwater); socioeconomic drought (water supply fails to meet demand). The US Drought Monitor classifies drought from D0 (abnormally dry) to D4 (exceptional) based on multiple indicators including SPI, PDSI, soil moisture, and streamflow.' },
        { term: 'Rossby waves',        def: 'Large planetary-scale waves in the mid-latitude westerly jet stream, driven by the latitudinal gradient of the Coriolis parameter (beta effect) and by orographic and thermal forcing. Rossby waves have wavelengths of 3,000–10,000 km (1864–6214 mi) and propagate westward relative to the mean flow (but are often advected eastward by the jet). Stationary Rossby waves arise when the wave phase speed equals the eastward mean flow speed. Blocking occurs when a Rossby wave amplitude grows large enough to form a closed circulation (cut-off high or dipole block).' },
        { term: 'Soil moisture feedback', def: 'A positive feedback between drought and temperature in which dry soils shift the surface energy balance from latent heat flux (evaporation, which cools) to sensible heat flux (direct heating of the air above). Dry soils: less evapotranspiration → more solar energy heats the air directly → higher temperatures → more plant water stress → further reduced evapotranspiration. This feedback can amplify an initial meteorological drought into an extreme heat wave and can extend drought conditions beyond what the synoptic forcing alone would produce.' },
        { term: 'Wet-bulb temperature', def: 'The temperature to which air can be cooled by evaporating water into it at constant pressure. The wet-bulb temperature is the lowest temperature achievable by sweat evaporation and is therefore the physiologically relevant measure of heat stress. A wet-bulb temperature of 35°C (95°F) is considered the theoretical upper limit of human survivability (even in shade, with unlimited water) for 6+ hours because at this condition, the human body cannot transfer heat to the environment even through sweating.' },
      ],
    },
    {
      type: 'concept',
      title: 'Blocking highs, Rossby waves, and heat wave mechanics',
      body: `**The atmospheric dynamics of blocking.** The mid-latitude westerly jet stream does not flow in a straight zonal (east-west) band; it meanders in large **Rossby waves** — planetary-scale undulations with amplitudes of hundreds to thousands of kilometres. In the normal course of mid-latitude weather, these Rossby waves propagate eastward, bringing alternating ridges (high pressure, warm, anticyclonic flow) and troughs (low pressure, cool, cyclonic flow) to any fixed location over a period of days to weeks. Weather systems progress, and no single air mass dominates for long. **Blocking** occurs when a Rossby wave amplitude grows so large that the wave breaks — a process analogous to an ocean wave breaking on a beach — and a closed, isolated high-pressure cell is cut off from the westerly flow. This cut-off high can persist for 5–30+ days because it is topologically isolated from the upstream flow; the normal mechanisms that would translate it eastward (Rossby wave phase propagation) no longer apply.

**Heat accumulation under a blocking high.** Beneath a blocking anticyclone, the air is subject to adiabatic compression warming (subsidence): air sinking from the upper troposphere warms at the dry adiabatic lapse rate (~10°C/km (18.0°F/1,000 ft)). A blocking high that maintains persistent 10 hPa of subsidence per day effectively imports warm air from aloft and continuously reheats the surface boundary layer. Additionally, clear skies under the high allow maximum solar insolation to heat the surface, while suppressed cloud cover prevents the normal cooling from outgoing longwave radiation at night. The combination — subsidence warming during the day, reduced cloud cover overnight — progressively increases the heat content of the boundary layer over the lifetime of the block. In the 2003 European heat wave, blocking maintained temperatures 10–15°C (50–59°F) above the seasonal average for two weeks; soil and building fabric stored heat accumulated over days, so nighttime temperatures remained high throughout.

**The soil moisture feedback.** A critical amplifier of heat wave intensity, particularly during sustained blocking, is the **soil moisture-temperature feedback**. Under normal (moist) conditions, much of the solar energy absorbed at the surface goes into evapotranspiration — converting liquid water to vapour, a process that absorbs ~2.5 MJ per kilogram of water evaporated. This latent heat flux cools the surface and humidifies the lower atmosphere. When soils are dry (from prior drought or simply from the accumulated evaporative demand of the heat wave itself), the latent heat flux is suppressed — evaporation cannot occur because there is no water available. The same solar energy that would have driven evapotranspiration instead goes directly into sensible heat — raising the temperature of the soil and the overlying air. Studies of the 2003 European heat wave estimated that this soil moisture feedback amplified peak temperatures by 3–8°C (37–46°F) beyond what the blocking alone would have produced. The feedback is self-reinforcing: the **Clausius-Clapeyron relation**, a thermodynamic law, predicts that warmer air can hold approximately 7% more water vapour per 1°C of warming — which means the atmosphere's capacity for moisture rises with temperature, amplifying soil drying and drought severity in a warming climate.

**Health impacts of heat waves: the physiological mechanisms.** Heat causes death through two primary mechanisms: **heat stroke** (failure of thermoregulation when core body temperature exceeds ~40°C (104°F)) and the **exacerbation of cardiovascular and respiratory disease** (heat stress increases heart rate, blood viscosity, and respiratory inflammation). The urban heat island (UHI) effect amplifies heat wave impacts in cities: concrete and asphalt store and slowly release heat, nighttime UHI temperatures can be 5–8°C (41–46°F) warmer than surrounding rural areas, trapping urban dwellers in a heat bubble. Vulnerability is highest in the elderly (reduced sweating capacity, comorbidities), urban residents without air conditioning, outdoor workers, and those with no social contact (who die alone without intervention). The Paris 2003 event struck particularly hard because the August holiday period left elderly residents without their usual social support networks.`,
      cards: [
        {
          name: 'Blocking Patterns',
          icon: Wind,
          color: BRAND.accent,
          desc: 'Omega block: mid-tropospheric (500 hPa) pattern resembling Ω — high flanked by two cut-off lows; extremely persistent (10–30 days). Rex block: high directly north of a low; less persistent. European blocking: most common over North Atlantic and European Russia. Blocking index (Tibaldi-Molteni): identifies blocking by reversal of 500 hPa height gradient. Frequency varies with the North Atlantic Oscillation (NAO) and Arctic Oscillation (AO). Climate change may be altering blocking frequency by changing Arctic-midlatitude temperature gradients — active research area.',
          examples: '2003 European heat wave: 14-day Omega block over western Europe; Paris 40.4°C (105°F), 70,000 excess deaths · 2010 Russian heat wave: 45-day blocking event; Moscow 38.2°C (101°F), 55,000 excess deaths, $15B crop losses · 2021 Pacific Northwest heat dome: record-breaking 500 hPa ridge; Portland, OR reached 46.7°C (116°F) — previously unthinkable; 1,400+ deaths in Canada and northwestern US',
        },
        {
          name: 'Drought Intensification',
          icon: Sun,
          color: BRAND.gold,
          desc: 'US Drought Monitor (USDM): weekly product since 2000; combines SPI (Standardised Precipitation Index, which measures precipitation deficit over multiple timescales), PDSI (Palmer Drought Severity Index, which incorporates temperature and potential evapotranspiration), soil moisture, streamflow, and expert assessment. Drought feedbacks: dry soil → less evapotranspiration → more surface heating → higher temperatures → more drought. Flash drought: rapid onset (weeks) driven by anomalous evaporative demand, not just precipitation deficit; increasingly common with warming. Major US droughts: Dust Bowl 1930s, 1988, 2012 (worst since 1930s).',
          examples: '2012 US drought: affected 65% of lower-48 states; corn crop losses 40%; cost >$30B; Great Plains saw D4 conditions for months · Dust Bowl 1930s: drought + poor farming practices removed vegetative cover → feedback loops → repeated crop failures; 3.5 million people displaced · Australia 2019 Millennium Drought: decade-long drought preceded catastrophic "Black Summer" fires',
        },
        {
          name: 'Wet-Bulb Limits and Human Physiology',
          icon: Thermometer,
          color: BRAND.ruby,
          desc: 'Wet-bulb temperature (Tw) = temperature after evaporative cooling; determines maximum heat loss from sweating. Tw 26–28°C (79–82°F): heat stress begins (athletic performance impaired). Tw 31°C (88°F): dangerous for outdoor workers. Tw 35°C (95°F): theoretical survivability limit — even a healthy person in shade with unlimited water cannot cool themselves; metabolic heat cannot be shed. Tw 35°C (95°F) corresponds to roughly 46°C (115°F) at 50% humidity or 35°C (95°F) at 100% humidity. Tw >35°C (95°F) has been observed post-2000 in Persian Gulf, South Asia. By 2100, large areas of tropics/subtropics may regularly exceed Tw 35°C (95°F) if high-emission scenarios continue.',
          examples: 'India/Pakistan heat waves 2015–2022: wet-bulb temperatures approaching 33–34°C (91–93°F) in Jacobabad, Pakistan — among the highest ever measured; July 2021 event saw Tw = 33.6°C (92°F) · Persian Gulf: Tw >35°C (95°F) briefly observed in 2015 at Bandar Mahshahr, Iran: 46°C (115°F) with 50% humidity · Heat-related mortality US: >1,300 deaths/year on average; 2021 Pacific Northwest heat dome killed 1,400+ in one week',
        },
      ],
    },
    {
      type: 'visualization',
      title: 'Heat wave development: from blocking onset to surface impact',
      body: 'How an atmospheric blocking pattern translates into sustained surface heat and amplified drought conditions through interlocked physical feedbacks.',
      interaction: {
        type: 'flow-simulator' as const,
        description: 'From blocking high to heat wave to drought amplification',
        nodes: [
          { id: 'block_onset',  label: 'Blocking Onset',           description: 'A large-amplitude Rossby wave in the upper-level (500 hPa) westerly flow breaks and forms a cut-off or quasi-stationary anticyclone. The normal eastward progression of weather systems is halted. Synoptic models may forecast the onset 5–10 days in advance but struggle to predict the duration — blocking termination remains one of the hardest forecasting problems.', color: BRAND.accent },
          { id: 'subsidence',   label: 'Subsidence Warming',       description: 'Under the blocking high, air sinks from the upper troposphere. Descending air warms adiabatically at ~10°C/km (18.0°F/1,000 ft) of descent. The subsidence suppresses cloud formation (clear skies) and creates a strong temperature inversion that caps any convective cooling. Boundary layer temperatures rise progressively each day the block persists.', color: BRAND.gold },
          { id: 'clear_sky',    label: 'Maximum Solar Heating',    description: 'Clear skies beneath the anticyclone allow peak solar radiation to reach the surface. Without cloud cover, daytime temperatures can exceed climatological records. The lack of overnight cloud cover also allows outgoing longwave radiation (cooling) but the accumulated heat in soil and urban fabric limits nocturnal recovery — nighttime temperatures stay elevated.', color: BRAND.coral },
          { id: 'soil_dry',     label: 'Soil Drying Feedback',     description: 'As surface temperatures rise, evaporative demand (potential evapotranspiration) increases dramatically — Clausius-Clapeyron scaling predicts ~7% more demand per 1°C (34°F). Soils dry rapidly; plants wilt and reduce transpiration. Once soils dry below the wilting point, all incoming solar radiation heats the air directly (sensible heat) rather than driving evaporation (latent heat) — amplifying temperatures by an additional 3–8°C (37–46°F).', color: BRAND.ruby },
          { id: 'heat_peak',    label: 'Peak Heat Wave Conditions', description: 'Temperatures may reach 10–20°C (50–68°F) above the seasonal average. Nighttime minimum temperatures remain high. High humidity (if present from prior moist soils) dramatically increases physiological heat stress. Urban areas add 5–8°C (41–46°F) from the urban heat island effect. Mortality rates rise sharply — cardiovascular and respiratory disease exacerbated; heat stroke occurs in vulnerable populations.', color: BRAND.amethyst },
        ],
        edges: [
          { from: 'block_onset', to: 'subsidence',  label: 'anticyclone creates sinking air' },
          { from: 'subsidence',  to: 'clear_sky',   label: 'suppresses cloud formation' },
          { from: 'clear_sky',   to: 'soil_dry',    label: 'max insolation + drying demand' },
          { from: 'soil_dry',    to: 'heat_peak',   label: 'sensible > latent heating' },
          { from: 'heat_peak',   to: 'soil_dry',    label: 'temperature feedback dries further' },
        ],
      },
    },
    {
      type: 'quiz',
      questions: [
        {
          q: 'The 2021 Pacific Northwest heat dome produced record temperatures of 46.7°C (116°F) in Portland, Oregon and 49.6°C (121°F) in Lytton, British Columbia — exceeding all previous records by 5°C (41°F) or more. Attribution science attributed this event to climate change. What specific atmospheric mechanism created the extreme temperatures, and why did the event break records by such an unprecedented margin?',
          a: [
            'The Pacific Northwest heat dome was driven by an unusually intense tropical cyclone off the coast of California that pushed warm oceanic air inland; climate change warmed Pacific sea surface temperatures, intensifying the cyclone and increasing the moisture and heat transported inland; the 5°C (41°F) record-breaking margin resulted from the higher SSTs',
            'A rare, extremely amplified upper-level ridge (blocking high) built over the Pacific Northwest — a 500 hPa geopotential height anomaly that was statistically nearly impossible in the pre-industrial climate. Subsidence warming under the ridge, combined with near-zero soil moisture (the region had experienced a dry spring) that eliminated latent heat cooling, produced temperatures far above anything previously recorded; attribution studies found that human-caused climate change made the event at least 150 times more likely and its peak intensity about 2°C (36°F) warmer than in a pre-industrial climate',
            'The 2021 Pacific Northwest event was caused by a La Niña pattern that had persisted since late 2020, which systematically redirected warm air masses from the tropics into the mid-latitudes of the Pacific coast; La Niña-associated teleconnections have always caused warm summers in this region, and the record temperatures resulted from an unusually strong La Niña episode combined with ongoing warming trend',
            'The extreme temperatures resulted from a methane release event in the Arctic permafrost, which dramatically increased the local greenhouse effect over the Pacific and Northwest; while climate change was a factor through permafrost destabilisation, the immediate cause was a short-term methane pulse that temporarily increased local radiative forcing to double its normal value',
          ],
          correct: 1,
          explain: 'A misidentifies the mechanism — tropical cyclones off California are rare and do not produce inland heat events of this type; the Pacific Northwest heat dome was an upper-level ridge event, not a tropical cyclone moisture transport. C partially explains background conditions (La Niña did likely prime the region for drought, reducing soil moisture) but cannot explain why temperatures exceeded all prior records by 5°C (41°F); La Niña teleconnections have operated throughout the instrumental record without producing comparable extremes. D is factually incorrect — while Arctic methane releases are a concern on longer timescales, there was no identified methane pulse event in June 2021 that could explain a local temperature extreme; this mechanism has no scientific support for this event. The correct answer is B: the Pacific Northwest event illustrates the co-occurrence of two mutually reinforcing mechanisms. The primary mechanism was the **ridging event** — a 500 hPa height anomaly of +600 m (1969 ft) above the climatological average, one of the most extreme upper-level height anomalies ever recorded in that region. The ridge caused intense subsidence (sinking) of air, which warmed adiabatically. The secondary mechanism was the **soil moisture feedback**: the 2020–2021 winter and spring were exceptionally dry in the Pacific Northwest, leaving soils at near-record low moisture content. When the sun shone through clear skies under the ridge, there was essentially no water in the soil to evaporate — all the solar energy went directly into heating the air. Attribution scientists (Otto et al., 2021, World Weather Attribution) estimated this event was approximately 2°C (36°F) more intense than it would have been without human-caused climate change, and that climate change had made it at least 150 times more likely. The study noted that events of this magnitude are still rare even in the current climate, but will become substantially more common if warming continues.',
        },
        {
          q: 'European heat waves typically cause the most deaths in France, Portugal, and the United Kingdom — countries that are not the hottest in Europe. Spain and Greece, which regularly experience 40°C (104°F)+ temperatures, typically have lower per-capita heat mortality. What physiological, social, and architectural factors explain this paradox?',
          a: [
            'The paradox does not exist; Spain and Greece do have higher per-capita heat mortality than France and the UK; the statistics cited are incorrect and reflect undercounting in southern European countries due to lower healthcare system capacity',
            'Northern and western European populations, buildings, and infrastructure are adapted to cool, temperate climates; homes typically lack air conditioning, have no architectural shading features, and are designed to retain heat; populations in the UK and France lack physiological and behavioural acclimatisation to extreme heat; when a heat wave 10–15°C (50–59°F) above the normal summer temperature arrives, it vastly exceeds the population\'s adaptive capacity; in Spain and Greece, the same temperature may be 3–5°C (37–41°F) above the normal summer temperature, buildings have traditional heat-mitigation architecture (thick walls, shutters, shaded courtyards), and the population has both physiological acclimatisation (higher sweat rates, lower heat stroke threshold) and cultural adaptation (siesta, evening activity)',
            'The difference is entirely explained by age structure — Spain and Greece have younger populations with lower proportions of elderly residents, who are most vulnerable to heat; France and the UK have older populations; the architectural and social factors are secondary',
            'France and the UK experience higher humidity during heat waves (being more maritime) while Spain and Greece have dry heat; high humidity dramatically increases physiological heat stress even at lower temperatures; Spanish 40°C (104°F) heat is dry and tolerable while French 35°C (95°F) heat with high humidity is lethal',
          ],
          correct: 1,
          explain: 'A is factually incorrect — the vulnerability paradox is well-documented in the peer-reviewed public health literature; Spain and southern European countries do have considerably lower per-capita heat mortality than France and the UK during comparable anomalies. C is partially true (age structure matters — the elderly are most vulnerable) but cannot explain the full paradox; France and the UK do not have dramatically older populations than Spain, and the architectural and acclimatisation factors are well-documented in heat mortality research. D is partially true for some events (the UK does get humid heat) but humidity alone cannot explain the systematic pattern across all heat waves and both France (drier) and the UK (more maritime). The correct answer is B: the paradox is explained by the concept of **anomaly relative to climatology** combined with adaptation. A temperature of 40°C (104°F) in Seville in July is roughly 5°C above the average July maximum — an unusual but not unprecedented event. The same temperature in Paris is 15°C above the average July maximum — an event that the city\'s physical infrastructure and population were entirely unprepared for. Specifically: (1) Buildings in northern Europe are designed to retain heat (thick insulation, triple-glazing) to cope with cold winters — they are heat traps in extreme summer events. Air conditioning rates in France and the UK are far lower than in the US, Australia, or southern Europe. (2) Traditional Mediterranean architecture (thick stone walls with high thermal mass, deep overhanging roofs, interior courtyards, external shutters) passively maintains cooler indoor temperatures; UK Victorian terraced housing has none of these features. (3) Physiological and behavioural adaptation: people who regularly experience extreme heat develop higher sweat rates and shifted heat stroke thresholds; they also adapt culturally (avoiding outdoor activity in the hottest hours, siesta culture, spending time in cool spaces). The combination of these factors means that a "moderate" heat event in London can overwhelm the population\'s adaptive capacity while a more intense event in Seville does not, because the Sevillian population, buildings, and culture were adapted to it.',
        },
        {
          q: 'Meteorologists distinguish between "meteorological drought" (precipitation deficit) and "flash drought" — a newer concept defined by rapid intensification of drought conditions over days to weeks driven primarily by anomalous evaporative demand. Under a warming climate, which type of drought is expected to become more frequent and more severe, and what atmospheric mechanism drives flash drought?',
          a: [
            'Meteorological drought (precipitation deficit) will become more frequent because climate change is shifting rainfall patterns globally, creating more permanent dry zones; flash drought is a minor phenomenon that will become less important because warmer temperatures increase evaporation from the ocean, providing more precipitation that recharges soil moisture rapidly',
            'Both types of drought are expected to increase, but flash drought is projected to intensify more rapidly under warming because its primary driver — atmospheric evaporative demand — scales nonlinearly with temperature; in a warmer atmosphere, longer dry spells between rain events combined with dramatically higher temperatures can deplete soil moisture to critical levels within 2–4 weeks even without a major precipitation deficit; the Clausius-Clapeyron relation predicts 7% higher vapour pressure deficit per 1°C (34°F) warming, increasing the atmosphere\'s ability to extract moisture from soil and vegetation',
            'Flash drought will become less common because climate change is increasing the frequency and intensity of precipitation events; while individual dry spells may be warmer, they will be shorter because the increased moisture in the atmosphere ensures that rain events occur more frequently; the net effect is that soils never dry long enough for flash drought to develop',
            'Flash drought intensity is primarily controlled by soil type, not by atmospheric conditions; sandy soils drain quickly and are always vulnerable regardless of temperature; clay soils retain moisture and are immune to flash drought; climate change\'s effect on flash drought is therefore entirely mediated by land use change and soil degradation, not by atmospheric warming',
          ],
          correct: 1,
          explain: 'A is incorrect that meteorological drought (precipitation deficit) is the primary increasing hazard; while precipitation patterns do shift with climate change, the more robust projection is for increasing evaporative demand even where precipitation doesn\'t decrease, driving agricultural and flash drought independent of rainfall anomalies. C is partially correct that precipitation extremes are increasing with warming (consistent with Clausius-Clapeyron scaling: a warmer atmosphere holds more moisture and can produce more intense rain events), but "more frequent rainfall events" is not a consistent global projection; in many regions, dry spell length is increasing between more intense but less frequent rain events. D incorrectly makes soil type the primary control on flash drought; while soil texture affects water holding capacity, the rate of drying is controlled by the atmospheric demand for moisture (evapotranspiration), which is governed by temperature, humidity, and wind, not soil type alone. The correct answer is B: flash drought represents a distinct mechanism from conventional meteorological drought. Conventional drought develops over months to years as precipitation deficits accumulate, gradually depleting soil moisture and groundwater. Flash drought can develop in 2–6 weeks through a different pathway: anomalously high temperatures, low humidity, and strong wind increase potential evapotranspiration (PET) dramatically, extracting water from soils and vegetation even during periods of near-normal or only slightly below-normal precipitation. The **vapour pressure deficit (VPD)** — the difference between how much moisture the atmosphere could hold at the current temperature and how much it actually holds — drives the evaporative demand; VPD increases roughly exponentially with temperature (Clausius-Clapeyron), meaning even modest warming can dramatically amplify evaporative demand. Under high-emission warming scenarios, VPD over the continental US interior is projected to increase 40–60% by 2100, creating conditions where flash drought can develop in a matter of days once a dry, warm atmospheric pattern is established. The 2012 US drought, one of the worst in decades, had flash drought characteristics in several regions — soil moisture fell from normal to D3 (extreme) in parts of the Midwest in less than 6 weeks during an anomalously hot, dry May–June.',
        },
        {
          q: 'The wet-bulb temperature (Tw) threshold of 35°C (95°F) is described as the theoretical upper limit of human survival for extended periods. Why does this specific threshold represent an absolute physiological limit, and under what conditions might humans exceed it temporarily?',
          a: [
            'A wet-bulb temperature of 35°C (95°F) is lethal because it equals normal human core body temperature; at this condition, the body cannot radiate heat because the environment is as warm as the body; radiation is the primary mechanism of human heat loss in hot weather, so radiative equilibrium with the environment prevents any cooling',
            'At a wet-bulb temperature of 35°C (95°F), the human body\'s core heat production (metabolic rate of ~80 W/m² at rest) cannot be shed to the environment through any available mechanism; sweat evaporation — the primary cooling mechanism in heat — requires that the wet-bulb temperature of the skin surface be higher than the ambient wet-bulb temperature; when Tw_ambient = 35°C (95°F), the skin must be at ≥35°C (95°F) to drive evaporation, meaning the body must be at the physiological limit of heat stroke before any evaporative cooling can occur; even at rest in shade with unlimited water, a healthy adult cannot maintain thermal equilibrium',
            'The 35°C (95°F) wet-bulb limit exists because high humidity at this temperature causes swelling of the lung tissue (pulmonary oedema), preventing adequate gas exchange; the limit is primarily a respiratory constraint, not a thermoregulatory one; below this threshold, the respiratory system can compensate for heat stress, but above it, breathing becomes fatally impaired',
            'The 35°C (95°F) wet-bulb limit is based on the boiling point of sweat — at 35°C (95°F) wet-bulb temperature, sweat on the skin immediately boils into steam rather than evaporating normally; the phase change from liquid to gas at this temperature is too rapid to provide controlled cooling, and the rapid evaporation causes skin damage analogous to a steam burn',
          ],
          correct: 1,
          explain: 'A incorrectly identifies radiation as the primary heat loss mechanism in hot environments; radiation from skin does dissipate heat, but it becomes ineffective when the environment is at skin temperature (~33–35°C (91–95°F)); more importantly, radiation is not the primary mechanism during sweating — evaporative cooling dominates. Furthermore, normal human core temperature is ~37°C (99°F), not 35°C (95°F) wet-bulb, so the "radiative equilibrium" argument is misframed. C describes a real phenomenon (high temperature and humidity do stress the respiratory system) but pulmonary oedema is not the mechanism of Tw 35°C (95°F) lethality; respiratory limitations in heat stress are secondary to thermoregulatory failure. D is completely incorrect — sweat does not boil at 35°C (95°F) wet-bulb temperature; boiling would require 100°C (212°F) at standard atmospheric pressure, and the relevant physics of evaporative cooling involves vapour pressure gradients at temperatures far below boiling. The correct answer is B: the 35°C (95°F) wet-bulb temperature limit is a fundamental thermodynamic constraint. The human body continuously produces metabolic heat — about 80 W/m² at complete rest. This heat must be shed to the environment, primarily through evaporative cooling (sweating). Evaporative cooling works by transferring latent heat: water molecules in sweat absorb ~2,440 J/g of energy to evaporate, cooling the skin. But evaporation requires a vapour pressure gradient — the partial pressure of water vapour at the skin surface must be higher than in the ambient air. The ambient vapour pressure is determined by the ambient wet-bulb temperature. When the ambient Tw approaches 35°C (95°F), the skin (at ~35°C (95°F)) must be at a wet-bulb temperature equal to the ambient just to drive any evaporation at all — meaning the body is already at incipient heat stroke before any cooling can begin. In practice, a skin temperature of 35°C (95°F) means the core is approaching 38–39°C (early heat stroke territory). The 35°C (95°F) Tw limit was quantified in research by Sherwood and Huber (2010), who estimated that sustained Tw > 35°C (95°F) is incompatible with survival for 6+ hours even for young, healthy, unclothed adults with unlimited water — because the physics of evaporative heat loss simply cannot balance metabolic heat production under these conditions. Humans can survive brief (minutes to an hour) exposures at Tw > 35°C (95°F) due to the thermal mass of the body and transient adaptations, but not sustained exposures.',
        },
      ],
    },
  ],
}

export default heatWavesDroughtBlocking
