import { Thermometer, Globe, Wind } from 'lucide-react'
import { BRAND } from '@/lib/brand'
import type { Lesson } from './types'

const atmosphericCirculation: Lesson = {
  id: 'clim-101-1-1-2',
  title: 'Atmospheric Circulation and the Ocean Heat Engine',
  track: 'cli',
  trackName: 'Climate Science',
  level: 'Beginner',
  duration: '11 min',
  xpReward: 140,
  description: "The global atmospheric and oceanic circulation systems are Earth's planetary heat redistributors — carrying excess tropical solar energy to energy-deficient polar regions and moderating the temperature extremes that would otherwise make much of Earth's surface uninhabitable. Understanding the Hadley cell, jet streams, thermohaline circulation, and El Niño is foundational to understanding regional climate patterns and how they may shift under climate change.",
  sources: [
    { org: 'NOAA',     title: 'NOAA Climate — Atmospheric Circulation Patterns',                     url: 'https://www.climate.gov/teaching' },
    { org: 'NASA',     title: 'NASA Ocean Motion — Thermohaline Circulation and Climate',            url: 'https://oceanmotion.nasa.gov' },
    { org: 'OpenStax', title: 'Environmental Science — Ocean and Atmosphere Circulation (CC-BY 4.0)', url: 'https://openstax.org/books/environmental-science-ap' },
    { org: 'NOAA',     title: 'NOAA ENSO Blog — El Niño-Southern Oscillation Science',               url: 'https://www.climate.gov/enso' },
    { org: 'AGI',      title: 'Glossary of Geology — General Circulation and Thermohaline',         url: 'https://www.americangeosciences.org/' },
  ],
  sections: [
    {
      type: 'intro',
      title: 'Moving heat across a spinning planet',
      body: `The Sun does not heat Earth's surface uniformly. The tropics receive nearly twice as much solar radiation per unit area as the poles (because of the lower angle of incidence at high latitudes and the greater atmospheric path length that solar radiation traverses). If no heat transport occurred, the tropics would warm until they radiated as much energy as they received — reaching temperatures above the boiling point of water — while the poles would cool toward the temperature of outer space (~-270°C). The reason Earth's temperature gradient from equator to poles is only about 60°C (rather than hundreds of degrees) is that the atmosphere and ocean act as a global heat engine, transporting approximately 5 petawatts (5×10¹⁵ W) of thermal energy from the tropics to the poles at any given moment.

The **general circulation** of the atmosphere — the systematic, planet-scale wind patterns driven by differential solar heating and modified by Earth's rotation (Coriolis effect) — is the primary mechanism of this heat transport. The Hadley cell, the most energetically powerful atmospheric circulation, drives the trade winds, the Intertropical Convergence Zone (ITCZ), and the subtropical dry belts that govern the location of Earth's major deserts. Jet streams — fast-flowing air currents in the upper troposphere — steer weather systems at mid-latitudes and have been observed to weaken and meander more broadly as the Arctic warms and the equator-to-pole temperature gradient decreases.

The **ocean** transports approximately 40% of the total equator-to-pole heat flux (the atmosphere carries the remaining 60%). The thermohaline circulation — the global overturning circulation driven by density differences in seawater — acts as a planetary conveyor belt that transports warm, shallow water to high latitudes and returns cold, dense water to depth. Changes in thermohaline circulation, which may occur as freshwater from melting ice sheets enters the North Atlantic and reduces surface water density, could substantially alter regional climate patterns in Europe, North America, and the tropical Atlantic — and represent one of the major potential tipping elements in the climate system.`,
      keyTerms: [
        { term: 'Hadley cell', def: "A large atmospheric circulation cell between the equator and ~30° latitude. Hot, moist air rises at the ITCZ (Intertropical Convergence Zone) near the equator, diverges poleward at high altitude, cools and descends at ~30° latitude (creating subtropical high-pressure zones and major desert belts — Sahara, Arabian Peninsula, Australian interior, Atacama), and returns to the equator as the trade winds (northeast trades in the Northern Hemisphere, southeast trades in the Southern Hemisphere). The Hadley cell is the single most energetically important atmospheric circulation cell." },
        { term: 'Jet stream', def: 'Fast-flowing (100–300 km/h), narrow bands of air in the upper troposphere (8–13 km altitude) at the boundaries between warm tropical and cool polar air masses. Two main jet streams per hemisphere: (1) subtropical jet (~30°) at the poleward edge of the Hadley cell; (2) polar front jet (~60°) at the boundary between Ferrel and Polar cells. Jet streams steer mid-latitude weather systems, direct storm tracks, and form the boundaries of major climate zones. Weakening of the polar front jet due to Arctic amplification may cause more frequent blocking events and meandering Rossby waves.' },
        { term: 'Thermohaline circulation (THC)', def: 'The global ocean overturning circulation driven by density differences in seawater (thermo = temperature, haline = salinity). Dense, cold, salty water sinks in the North Atlantic (Labrador and Greenland Seas) and Antarctic (Weddell Sea), driving a slow global circulation that transports heat, carbon, and nutrients around the globe on timescales of ~1,000 years. The North Atlantic component (AMOC — Atlantic Meridional Overturning Circulation) warms Northern Europe by ~5–8°C relative to a world without THC. Evidence suggests AMOC has weakened ~15% since the mid-20th century.' },
        { term: 'Intertropical Convergence Zone (ITCZ)', def: 'The belt of intense convection and rainfall that occurs where the northeast and southeast trade winds converge near the equator. The ITCZ migrates seasonally following the thermal equator (zone of maximum solar heating), reaching its northernmost position (~10°N) in Northern Hemisphere summer and its southernmost position in Northern Hemisphere winter. It produces the monsoon rainfall patterns of South and Southeast Asia, West Africa, and Central America. Climate change may shift the ITCZ position, altering monsoon rainfall patterns for billions of people.' },
        { term: 'ENSO (El Niño-Southern Oscillation)', def: 'The largest source of interannual climate variability on Earth — a coupled ocean-atmosphere oscillation in the tropical Pacific. In El Niño phases, weakened trade winds allow warm water to accumulate in the eastern tropical Pacific, raising SSTs and shifting rainfall eastward, causing droughts in Australia/SE Asia and flooding in Peru/Ecuador. In La Niña phases, strengthened trades push warm water westward, cooling the eastern Pacific. ENSO cycles every 3–7 years and affects temperature and precipitation patterns globally.' },
      ],
    },
    {
      type: 'concept',
      title: 'The general circulation, thermohaline conveyor, and ENSO',
      body: `**The three-cell atmospheric circulation model.** The global atmospheric circulation is classically described by a three-cell model per hemisphere. The **Hadley cell** (equator to ~30°) is the most energetic: rising moist air at the ITCZ releases enormous quantities of latent heat (the tropics receive ~40% of global solar radiation and account for ~60% of global evaporation), driving a vigorous overturning. The descending branch at ~30° creates the subtropical high-pressure zones that are associated with the world's major hot deserts (Sahara, Arabian Desert, Sonoran Desert, Atacama, Namib, Australian desert) — because the subsiding dry air suppresses convection and precipitation. The **Ferrel cell** (30° to ~60°) is thermodynamically indirect (mechanically driven by Hadley and Polar cells) and transports heat poleward through the baroclinic eddies (mid-latitude cyclones) that dominate mid-latitude weather. The **Polar cell** (60° to poles) is a small, direct cell with cold surface air flowing equatorward and warmer air aloft. The boundaries between cells are marked by the subtropical and polar front jet streams.

**The thermohaline circulation: Earth's planetary conveyor.** The thermohaline circulation (THC) operates through a simple density principle: cold, salty water is denser than warm, fresh water and sinks. The most important sinking region in the North Atlantic is the Labrador Sea and Greenland-Iceland-Norwegian Seas, where wintertime cooling of warm, salty Gulf Stream water makes it dense enough to sink to 2–4 km depth and flow southward as North Atlantic Deep Water (NADW). This sinking is compensated by the northward flow of warm surface water — the Atlantic Meridional Overturning Circulation (AMOC), which carries ~1.3 petawatts of heat to the North Atlantic and gives Northwest Europe its anomalously mild climate (London, at the latitude of Calgary, experiences milder winters than most of inland North America at the same latitude). In the Southern Ocean, Antarctic Bottom Water (AABW) forms in the Weddell Sea and spreads across the global ocean floor. The complete global overturning circulation takes ~1,000 years for water to complete one circuit, making it a critical buffer that distributes heat and carbon across the globe on millennial timescales.

**AMOC vulnerability and the potential tipping point.** Paleoclimate records from ice cores and ocean sediments reveal that AMOC has collapsed abruptly (within decades) during past climate transitions. During the Younger Dryas (12,900–11,700 years ago), the rapid freshwater input to the North Atlantic from the collapse of the Laurentide Ice Sheet suppressed AMOC, causing temperatures in Europe and the North Atlantic region to plunge ~10°C within decades — even while the rest of the world continued gradual post-glacial warming. Current observations (fingerprint analysis of AMOC weakening from sea surface temperature patterns, direct measurements from the RAPID array since 2004) indicate that AMOC has weakened by approximately 15% since the mid-20th century, possibly approaching a tipping point beyond which it could collapse abruptly. Models disagree substantially on when or whether this might occur — estimates range from unlikely this century to possible within 50–100 years.

**ENSO teleconnections and global climate impacts.** ENSO is not merely a tropical phenomenon — its effects propagate globally through atmospheric teleconnections (Rossby waves triggered by tropical heating anomalies that alter the jet stream and regional pressure patterns). During El Niño events: California and the US Southwest experience wetter-than-normal winters; the US Southeast experiences warmer-than-normal winters; drought intensifies in Australia, Indonesia, and the Philippines; East Africa experiences above-normal rainfall; the Atlantic hurricane season is suppressed (increased wind shear from El Niño conditions disrupts tropical cyclone development). During La Niña events, the opposite patterns generally apply, and the Atlantic hurricane season becomes more active. ENSO also modulates global mean temperature — 2016 was the warmest year on record in part because a strong El Niño added ~0.15°C to the forced warming trend.`,
      cards: [
        {
          name: 'General Atmospheric Circulation',
          icon: Wind,
          color: BRAND.jade,
          desc: 'Hadley cell (0–30°): rising ITCZ → subtropical desert descending branch → trade winds returning equatorward. Creates tropical rainfall belt and subtropical desert belt (Sahara, Atacama, Namib, Arabian, Australian). Ferrel cell (30–60°): indirect, eddy-driven; mid-latitude weather systems dominate. Polar cell (60°–poles): direct, small. Jet streams: subtropical (30°) and polar front (~60°); steer mid-latitude weather. Arctic amplification weakens polar front jet → more meandering → prolonged blocking events (heat domes, cold outbreaks). ITCZ migration → monsoons.',
          examples: 'Sahara Desert at 15–30°N: directly under Hadley descending branch · Sahel drought: ITCZ migration variability · 2021 Pacific Northwest heat dome: amplified Rossby wave, 50°C temperatures; linked to weakened jet stream · Monsoon Asia: ITCZ seasonal migration drives Jun–Sep rainfall',
        },
        {
          name: 'Thermohaline Circulation and AMOC',
          icon: Globe,
          color: BRAND.jade,
          desc: 'THC: density-driven global ocean overturning. AMOC: North Atlantic component; transports ~1.3 PW heat to North Atlantic; warms Europe 5–8°C. Sinking: Labrador Sea + GIN Seas (cold + salty → dense). Rising: upwelling in Southern Ocean and Indian Ocean. NADW, AABW (Antarctic Bottom Water). Circuit time: ~1,000 years. AMOC weakening: ~15% since mid-20th century (RAPID array + fingerprinting). Tipping risk: freshwater input from Greenland Ice Sheet melt reduces salinity → AMOC slowdown → potential collapse within 50–200 years (model range). Younger Dryas: AMOC collapse, Europe cooled 10°C in decades.',
          examples: 'London (51°N): warmer winters than Calgary (51°N) by ~15°C due to AMOC heat transport · Younger Dryas (12,900–11,700 BP): abrupt AMOC collapse from Laurentide meltwater; Europe 10°C cooler for 1,200 years · RAPID array: direct AMOC monitoring since 2004; confirms recent weakening',
        },
        {
          name: 'ENSO: Ocean-Atmosphere Coupling',
          icon: Thermometer,
          color: BRAND.jade,
          desc: 'El Niño: weakened trade winds → warm water pools in eastern Pacific → Walker Circulation slows → shifts rainfall east. Teleconnections: western US wetter; Australia/SE Asia drought; Atlantic hurricane season suppressed (wind shear); East Africa wetter. Global T anomaly: +0.1–0.2°C during strong El Niño. La Niña: opposite; active Atlantic hurricane season; drought in southern US. Neutral: balanced state. IOD (Indian Ocean Dipole): similar coupled mode in Indian Ocean; amplifies/reduces El Niño impacts on Australia and East Africa. Predict 6–9 months in advance.',
          examples: '1997–98 El Niño: strongest pre-2015; California floods, Indonesia forest fires (smoke blanketed SE Asia), Peru floods · 2015–16 El Niño: strongest recorded; 2016 hottest year on record partly attributable · 2020–22 triple La Niña: 3 consecutive La Niña winters; global T temporarily suppressed despite continued CO₂ rise',
        },
      ],
    },
    {
      type: 'quiz',
      questions: [
        {
          q: "The Sahara Desert is located between approximately 15° and 30° north latitude — a location that receives substantial solar radiation (more than many tropical rainforests) yet experiences almost no precipitation (<25 mm/year in many areas). What atmospheric circulation mechanism explains this extreme aridity, and why are the world's major hot deserts concentrated at 15–30° latitude in both hemispheres?",
          a: [
            "The Sahara is arid because it is far from the ocean — the continental interior receives little moisture from marine air masses; the 15–30° latitude band is where most of the world's large continental interiors are located; coastal desert regions like the Atacama are explained by cold upwelling ocean currents that stabilise the adjacent air, preventing rainfall; both mechanisms (continentality and cold ocean currents) explain most hot deserts",
            "The Sahara is arid because the descending branch of the Hadley cell creates a subtropical high-pressure zone at 15–30° latitude; as air sinks in these zones, it compresses and warms adiabatically, increasing its capacity to hold water vapour (lowering relative humidity) and suppressing convection; this dynamically forced subsidence prevents the rising motion necessary for precipitation; the same mechanism operates in both hemispheres, creating the subtropical desert belts on both sides of the equatorial rainforest zone",
            "The Sahara receives high solar radiation but reflects most of it because of its high surface albedo (light-coloured sand: albedo ~0.35–0.45); the high reflected solar radiation cools the surface relative to vegetated regions; this surface cooling drives subsiding air that suppresses precipitation; aridity therefore maintains itself through a sand-albedo feedback loop, making the Sahara self-sustaining once established",
            "The Sahara's aridity is caused by the orographic shadow of the Atlas Mountains (northern Africa) and the Ethiopian Highlands (eastern Africa), which block moisture from reaching the Saharan interior; without these mountain ranges, the Sahara would receive significant rainfall; the same orographic effect explains deserts at 15–30° in other regions (Atacama behind the Andes, Australian interior behind the Great Dividing Range)",
          ],
          correct: 1,
          explain: "Continentality does contribute to interior aridity, but many desert regions (Namib in coastal Namibia, Atacama in coastal Chile) are coastal or semi-coastal yet extremely arid; and the Sahara extends from the Atlantic coast to the Red Sea — the Atlantic coast of the Sahara (Mauritania) is extremely arid despite being at the ocean margin; continentality alone cannot explain the Sahara's extent or location (A understates the role of atmospheric dynamics). The albedo-feedback mechanism described in C does play a role in maintaining and expanding the Sahara (the Saharan pump model — higher albedo → cooler surface → less convection → less rainfall → maintained desert), but this is a feedback that sustains an existing desert, not the primary mechanism that creates the subtropical desert belt; the fundamental cause is the atmospheric circulation (B). Orographic shadowing explains specific deserts like the Gobi (in the rain shadow of the Himalayas) and parts of the Atacama (behind the Andes), but the Sahara is not in the orographic shadow of the Atlas Mountains (which are at 30–35°N, north of most of the Sahara); the primary explanation for the 15–30° desert belt is atmospheric dynamics, not orography (D misidentifies the primary mechanism). The correct answer is B: the world's major subtropical deserts are located at 15–30° latitude because this is where the descending branch of the Hadley cell produces persistent subtropical high-pressure. In these zones, air subsides from the upper troposphere, is compressed by increasing pressure as it descends, and warms adiabatically (approximately 10°C per km of descent). This warming dramatically reduces relative humidity (since warm air can hold much more water vapour than cool air) and makes the descending air a 'moisture sponge' rather than a moisture source. The subsidence also creates a dynamically stable atmosphere — it strongly suppresses the rising motion that triggers convective precipitation. The result is persistent, extreme aridity — regardless of whether the desert is coastal or continental. Both hemispheres have this subtropical desert belt: Northern Hemisphere (Sahara, Arabian, Sonoran); Southern Hemisphere (Atacama, Namib, Australian interior, Kalahari).",
        },
        {
          q: "The Atlantic Meridional Overturning Circulation (AMOC) is sometimes described as a potential 'tipping point' in the climate system — a threshold beyond which AMOC might weaken or collapse abruptly, regardless of subsequent changes in forcing. What physical mechanism could cause such an abrupt transition, and what would be the regional and global climate consequences of AMOC collapse?",
          a: [
            "AMOC is vulnerable to abrupt collapse because it depends on the temperature difference between the tropics and poles — if global warming reduces this temperature gradient below a critical threshold, AMOC loses the driving force for overturning; once the gradient is too small, AMOC stops completely and can only restart when the gradient is restored by natural cooling; this threshold is expected to be crossed when global temperatures rise 2°C above pre-industrial levels",
            "AMOC could collapse abruptly through a freshwater-driven salinity feedback: AMOC depends on the sinking of dense (cold and salty) water in the North Atlantic; as Greenland Ice Sheet melting and increased precipitation at high northern latitudes inputs freshwater to the North Atlantic, surface salinity decreases; less salty water is less dense and does not sink as readily, reducing AMOC strength; a positive feedback operates because weaker AMOC brings less salty tropical water northward, further reducing North Atlantic salinity; if this feedback exceeds a critical threshold, AMOC transitions abruptly from a strong mode to a weak or collapsed mode, a genuinely irreversible transition on human timescales",
            "AMOC cannot collapse abruptly — it is a continuously variable circulation that responds proportionally to freshwater input; the abrupt collapses seen in paleoclimate records (Younger Dryas) were caused by catastrophic drainage events of glacial lakes (e.g., Lake Agassiz draining through the St. Lawrence) that added enormous freshwater pulses in short periods; in a modern warming world, freshwater addition from Greenland melt is gradual and AMOC would weaken proportionally over centuries, not collapse suddenly",
            "AMOC collapse would primarily affect ocean chemistry rather than regional climate — the circulation is important for distributing dissolved oxygen to the deep ocean and for transporting nutrients to surface waters that support marine productivity; the main consequence of AMOC collapse would be widespread ocean anoxia and collapse of Atlantic fisheries, not significant changes in atmospheric temperature patterns",
          ],
          correct: 1,
          explain: "The temperature gradient is a contributing factor to AMOC strength, but the primary mechanism is salinity-driven density — not temperature gradient per se; moreover, the 2°C threshold for AMOC collapse is not a well-established scientific consensus and misrepresents the highly uncertain and model-dependent nature of AMOC tipping point estimates (A misidentifies the mechanism and provides a false precision threshold). While it is true that catastrophic glacial lake drainage events drove the most abrupt Younger Dryas-scale AMOC collapses, palaeoclimate evidence also shows that more gradual freshwater forcing has caused significant AMOC reductions; the claim that AMOC 'cannot collapse abruptly' in a modern warming scenario is not consistent with the most recent IPCC assessment, which assigns non-trivial probability to abrupt weakening; the response is not necessarily proportional (C is too reassuring). Ocean anoxia and fisheries impacts would indeed be consequences of AMOC collapse, but they are secondary to the dramatic regional climate changes that would result; dismissing the atmospheric and temperature consequences is incorrect (D identifies real secondary consequences but misses the primary ones). The correct answer is B: the potential AMOC tipping point operates through a salt-advection feedback identified by the theoretical work of Stommel (1961) and extensively studied since. AMOC maintains itself in part because it advects salty tropical water northward; this salt input helps maintain the high North Atlantic salinity that enables the dense sinking water that drives AMOC. If freshwater input to the North Atlantic (from Greenland melt, increased Arctic precipitation, or river discharge) reduces surface salinity, AMOC weakens; weaker AMOC advects less tropical salt northward, further reducing salinity; this positive feedback can create a bistable system with two possible equilibrium states (strong and weak AMOC) — and a threshold between them where a small additional freshwater input causes a rapid transition from strong to weak. Regional consequences of AMOC collapse would include: European cooling of 5–10°C relative to the AMOC-present state; disruption of monsoon patterns in West Africa and South Asia; sea level rise along eastern North America coastlines (Gulf Stream suppression reduces the sea surface slope that currently draws water away from the US East Coast); and potentially paradoxical regional cooling in some areas even as global mean temperature continues rising.",
        },
        {
          q: "During a strong El Niño event, Australia experiences severe drought while Peru experiences severe flooding. Meanwhile, the Atlantic hurricane season is unusually quiet and parts of California receive above-average winter rainfall. How does a change in sea surface temperatures in the tropical Pacific — thousands of kilometres away — produce these simultaneous, coordinated climate anomalies across multiple ocean basins?",
          a: [
            "The simultaneous climate anomalies reflect coincidence rather than causal connection — Australia's drought, Peru's flooding, Atlantic hurricane suppression, and California's rain all occur in some years regardless of ENSO; during El Niño years, each of these anomalies independently happens to occur for unrelated reasons; the statistical correlation with El Niño reflects confirmation bias in reporting unusual weather events during El Niño years",
            "El Niño climate anomalies propagate through atmospheric teleconnections: the anomalously warm eastern Pacific SST during El Niño forces anomalous deep convection (intense thunderstorm activity) over the central-eastern Pacific; this heating source drives Rossby wave trains that propagate poleward and eastward through the upper troposphere, creating a characteristic pattern of high and low pressure anomalies across the globe; this atmospheric wave pattern shifts the jet stream, alters storm tracks, changes wind shear over the Atlantic (suppressing hurricane development), and modifies precipitation patterns in each affected region simultaneously through their shared atmospheric connection to the Pacific heating anomaly",
            "El Niño drives simultaneous global anomalies through changes in ocean surface currents — warm Pacific water transported northward by the California Current warms the US West Coast; the change in Pacific current patterns diverts the tropical Atlantic warm water that normally flows toward Europe, leaving the Gulf of Mexico cooler and suppressing hurricane formation; changes in Indian Ocean circulation explain the Australian drought; all effects are ocean-current-driven rather than atmosphere-driven",
            "The simultaneous climate anomalies are produced by the disruption of the global thermohaline circulation — when El Niño warms the tropical Pacific, it reduces the salinity gradient between the Pacific and Atlantic that drives global ocean overturning; this THC disruption propagates simultaneously to all ocean basins through the global conveyor belt, changing SSTs and evaporation patterns globally within months; ENSO teleconnections are fundamentally an ocean phenomenon, not an atmospheric one",
          ],
          correct: 1,
          explain: "The simultaneous, repeatable, physically consistent pattern of El Niño teleconnections across multiple ocean basins has been established by decades of observational analysis, mechanistic physical modelling, and seasonal forecasting that demonstrably performs better than climatology — this is not confirmation bias (A is incorrect and dismisses a robust scientific understanding). Ocean currents do change during ENSO events, but the primary teleconnection mechanism is atmospheric, not oceanic — ocean current adjustments to ENSO-induced wind changes take months to propagate, while the atmospheric Rossby wave teleconnections propagate within 1–2 weeks across hemispheres; the California Current mechanism described is physically wrong (the California Current flows southward along the coast, not northward) (C incorrectly identifies the mechanism and contains factual errors about ocean currents). Thermohaline circulation changes are NOT the mechanism of ENSO teleconnections — the THC operates on timescales of decades to millennia, far too slow to produce the simultaneous global responses within months of an El Niño onset; ENSO teleconnections are fundamentally atmospheric wave dynamics (D incorrectly attributes the mechanism to THC). The correct answer is B: El Niño teleconnections operate through the excitation of atmospheric Rossby waves by the anomalous tropical heating. When the eastern tropical Pacific SST rises during El Niño, the enhanced convection (deep cumulus towers) creates an anomalous heat source in the tropical upper troposphere. This heating forces Rossby wave trains — large-scale atmospheric waves that propagate meridionally (poleward) and zonally (eastward) through the upper troposphere on paths determined by the background atmospheric flow (Snell's Law for Rossby waves). These waves create a characteristic pattern of pressure anomalies: in the Northern Hemisphere winter, El Niño typically creates a deep trough (low pressure) over the eastern Pacific and a ridge over the western US, shifting the Pacific jet stream southward and directing enhanced storm tracks into California and the Gulf States. The enhanced upper-level westerly winds over the Caribbean and tropical Atlantic increase vertical wind shear — hostile to hurricane development. Over Australia, El Niño creates an upper-level ridge and suppresses the monsoon convection that brings summer rainfall. All these effects occur simultaneously because they are driven by the same wave pattern originating from the same tropical heating anomaly.",
        },
      ],
    },
  ],
}

export default atmosphericCirculation
