import { Thermometer, Globe, Wind } from 'lucide-react'
import { BRAND } from '@/lib/brand'
import type { Lesson } from './types'

const extremeWeatherClimate: Lesson = {
  id: 'clim-101-1-1-4',
  title: 'Climate Extremes: Heat Waves, Floods, and Attribution Science',
  track: 'cli',
  trackName: 'Climate Science',
  level: 'Beginner',
  duration: '11 min',
  xpReward: 140,
  description: "The impacts of climate change are felt most acutely through changes in extreme weather events — heat waves, floods, droughts, and wildfires. Attribution science has emerged as a powerful tool for quantifying how much climate change has altered the probability and severity of specific extreme events, connecting the abstract physics of greenhouse warming to real-world disasters.",
  sources: [
    { org: 'NOAA',     title: 'NOAA Climate — Weather Extremes and Climate Change',                  url: 'https://www.climate.gov/teaching/resources/weather-extremes-and-climate-change' },
    { org: 'NASA',     title: 'NASA Global Climate Change — Extreme Events',                         url: 'https://climate.nasa.gov/effects' },
    { org: 'OpenStax', title: 'Environmental Science — Climate Change Impacts (CC-BY 4.0)',          url: 'https://openstax.org/books/environmental-science-ap' },
    { org: 'NOAA',     title: 'NOAA Bulletin of the American Meteorological Society — Annual Extremes Attribution Reports', url: 'https://www.ametsoc.org/ams' },
    { org: 'AGI',      title: 'Glossary of Geology — Climate Extremes and Probability Distributions', url: 'https://www.americangeosciences.org/' },
  ],
  sections: [
    {
      type: 'intro',
      title: 'When the tail wags the dog',
      body: `Climate change is often described in terms of global mean temperature — a warming of 1.5°C or 2°C above pre-industrial levels. But the impacts of climate change on human society and natural ecosystems are felt primarily through the tails of the weather distribution: the extreme events that occur infrequently but cause disproportionate harm. A warming of 1.5°C in the global mean temperature corresponds to a much larger shift in the frequency and intensity of extreme heat events, because even a small shift in the mean of a distribution moves the tail dramatically. An event that occurred once every 50 years in a pre-industrial climate may occur once every 10 years at 1.5°C of warming, and once every 5 years at 2°C.

**Attribution science** — also called **extreme event attribution** — is a rapidly developing field that quantifies how much climate change has altered the probability and severity of specific extreme events. Using large ensembles of climate model simulations (comparing thousands of simulations with observed greenhouse gas concentrations to thousands of simulations without anthropogenic forcing), attribution scientists can calculate quantities like: "The probability of a heat wave of this magnitude was increased by a factor of X by climate change" or "Climate change made this rainfall event Y% more intense." The 2021 Pacific Northwest heat dome (which killed ~1,000 people in Oregon, Washington, and British Columbia and caused temperatures of 49.6°C in Lytton, British Columbia) was analysed within a week of its occurrence; the attribution study found that this event was "virtually impossible" without climate change — a probability increase of more than 150 times.

Understanding attribution science is important not just for academic understanding but for practical decision-making: it informs insurance markets (which calculate risk premiums based on event probability), infrastructure design standards (which specify the severity of events that must be designed against), and climate litigation (in which attribution studies are increasingly being introduced as evidence of causation).`,
      keyTerms: [
        { term: 'Extreme event attribution', def: 'The scientific discipline that quantifies the contribution of anthropogenic climate change to the probability or magnitude of specific extreme weather events. Uses large model ensembles comparing "factual" world (with observed greenhouse gases) to "counterfactual" world (without anthropogenic forcing). Key outputs: probability ratio (how many times more likely was the event?) and magnitude change (how much more intense?). Pioneered by Pardeep Pall, Myles Allen, Peter Stott and others; published rapidly in near-real-time for major events by World Weather Attribution (WWA) collaboration.' },
        { term: 'Probability ratio (PR)', def: 'The ratio of the probability of a given extreme event in the current climate to its probability in a pre-industrial or counterfactual climate. PR = 1: no change in probability. PR = 5: five times more likely. PR = 150+: effectively impossible without climate change. The 2021 Pacific Northwest heat dome had PR > 150 (virtually impossible without climate change). The 2022 Pakistan floods had PR ~7–8 (7–8 times more likely with climate change). Computing PR requires large model ensembles because very rare events have high statistical uncertainty from small numbers of occurrences.' },
        { term: 'Heat wave', def: 'A period of abnormally high temperatures (relative to local climatological normal) persisting for at least 2–3 consecutive days. Operational definitions vary by country and agency: typically defined as temperatures exceeding a high percentile (e.g., 90th or 95th) of the local distribution for multiple consecutive days. Heat waves are the deadliest weather phenomenon in many regions — the 2003 European heat wave killed ~70,000 people; the 2010 Russia heat wave killed ~55,000. Humid heat (high wet-bulb temperature) is more lethal than dry heat because it prevents effective evaporative cooling through sweating.' },
        { term: 'Clausius-Clapeyron relationship', def: 'The thermodynamic relationship stating that the water-holding capacity of the atmosphere increases by approximately 7% per degree Celsius of warming. As temperatures increase, the atmosphere can hold more moisture (following the Clausius-Clapeyron equation: dP/dT = L·P/(R·T²), where P is saturation vapour pressure, T is temperature, L is latent heat, R is gas constant). This means that when precipitation occurs, more water falls — making heavy precipitation events more intense. Observed precipitation extremes have increased by ~7% per degree of warming, consistent with the Clausius-Clapeyron relationship, confirming the theoretical prediction.' },
        { term: 'Wet-bulb temperature', def: 'The temperature measured by a thermometer wrapped in a wet cloth, representing the lowest temperature achievable by evaporative cooling. At high wet-bulb temperatures (> ~35°C), the human body cannot cool itself through sweating even at 100% humidity — core body temperature rises irreversibly, leading to heat stroke and death within hours even for fit young adults at rest in the shade. A 35°C wet-bulb temperature corresponds to roughly 46°C at 50% humidity or 32°C at 100% humidity. Several regions of South Asia and the Persian Gulf have already briefly exceeded the 35°C wet-bulb threshold in recent heat events, conditions likely to become more frequent under continued warming.' },
      ],
      interaction: {
        type: 'scientific-diagram' as const,
        id: 'co2-temperature-record',
        caption: 'CO₂ and Antarctic temperature anomaly from ice cores (Vostok/EPICA) over 420,000 years. Current CO₂ (~422 ppm) exceeds the natural range by ~50%; the two variables co-vary through all glacial-interglacial cycles.',
        credit: 'Petit et al. (1999) · Siegenthaler et al. (2005) · NOAA GML',
      },
    },
    {
      type: 'concept',
      title: 'The physics of climate extremes, attribution methods, and real-world examples',
      body: `**Why a shift in the mean shifts the tail disproportionately.** The connection between mean climate change and extreme event frequency is best understood through the lens of probability distributions. Weather follows roughly normal (Gaussian) distributions around seasonal mean values; the tails of these distributions correspond to rare extreme events. When the mean temperature shifts by 1°C (typical of the current warming), rare hot events become common: an event at the 95th percentile (occurring 5% of the time) moves to a new threshold that may correspond to the 80th or 85th percentile — much more frequent. An event previously at the 99.9th percentile may move to the 99th percentile — a 10× increase in frequency. This mathematical amplification of tail risk is why climate scientists say that even modest mean warming translates to dramatic increases in extreme heat event frequency. It is also why the difference between 1.5°C and 2°C of global warming — only 0.5°C — corresponds to approximately a 2× increase in the frequency of extreme heat events and a substantial increase in the area of the world that experiences potentially lethal wet-bulb temperatures regularly.

**Clausius-Clapeyron and precipitation extremes.** While heat waves are the most directly connected to warming, precipitation extremes also intensify with warming through the Clausius-Clapeyron relationship. A warmer atmosphere holds more water vapour (~7% more per °C of warming), meaning that when atmospheric conditions trigger precipitation, more moisture is available to fall. This mechanism is now robustly observed in global precipitation datasets: the intensity of the heaviest rainfall events (those at the 99th percentile of daily precipitation) has increased at a rate broadly consistent with 7% per °C of warming. The 2021 European floods (the Ahr Valley flood in Germany in July 2021 killed ~184 people and caused €30 billion in damage) were made 1.2–9 times more likely by climate change; the 2022 Pakistan monsoon floods — which covered one-third of Pakistan under water and affected 33 million people — were made 7–8 times more likely.

**Drought and fire: the amplified drying.** The relationship between climate change and drought is more complex than for heat or precipitation extremes because drought depends on both precipitation (input) and evapotranspiration (output). Even where precipitation does not significantly change, warming increases evapotranspiration (the rate at which water evaporates from soil and transpires from vegetation), drying soils and increasing fire risk. The US Southwest has experienced a **megadrought** since 2000 — the driest 22-year period in at least 1,200 years (as revealed by tree-ring reconstructions) — with attribution studies showing that climate change has contributed approximately 42% of the drought's severity. The ongoing megadrought has driven Lake Mead and Lake Powell (the two largest US reservoirs, supplying water to 40 million people) to record low levels. The 2020 California wildfire season burned >4 million acres — the largest in state history — partly driven by extreme heat and drought conditions that were made substantially more likely by climate change.

**The attribution pipeline: from event to legal accountability.** Attribution science has matured rapidly from a purely academic discipline to one with direct policy and legal relevance. The World Weather Attribution (WWA) collaboration, founded in 2014, produces rapid attribution analyses of major extreme events — typically within days to weeks of an event's occurrence. These analyses use a combination of observational data, climate model ensembles, and statistical methods to estimate probability ratios. The scientific consensus is that attribution for heat events is typically most robust (physical mechanisms well-understood, many models agree), while precipitation attribution has higher uncertainty (models disagree more on regional precipitation responses), and drought attribution is most complex (multiple mechanisms, regional variation). Attribution studies have been introduced as evidence in climate litigation in multiple jurisdictions — including Urgenda v. Netherlands (the first successful climate litigation based in part on attribution science) and a growing number of cases against fossil fuel companies in the United States and Europe.`,
      cards: [
        {
          name: 'Heat Waves: Shifting the Distribution Tail',
          icon: Thermometer,
          color: BRAND.accent,
          desc: '1°C mean warming → large increase in extreme heat frequency. Example: event at 99.9th percentile (once per 1,000 days) → moves to 99.5th percentile (once per 200 days) → 5× more frequent. Wet-bulb temperature > 35°C: human cooling impossible; fatal within hours. 1.5°C warming: extreme heat events 4.1× more frequent than pre-industrial. 2°C: 5.6× more frequent. 4°C: 9.4× more frequent. 2003 European heat wave: 70,000 deaths, made ~4× more likely by climate change. 2021 Pacific Northwest: 49.6°C in Lytton, BC; >150× more likely; virtually impossible without climate change. 2010 Russia heat wave: 55,000 deaths.',
          examples: 'Pacific Northwest 2021: unprecedented 49.6°C, Lytton, BC; 1,000 excess deaths in Oregon and BC · European 2003 heat wave: 70,000 deaths; France alone 15,000; triggered mandatory heat emergency protocols · South Asian humid heat: several Wet Bulb Temperature exceedances of 31–33°C already recorded in Pakistan/India',
        },
        {
          name: 'Precipitation Extremes and Clausius-Clapeyron',
          icon: Wind,
          color: BRAND.jade,
          desc: 'Clausius-Clapeyron: 7% more atmospheric water per °C. Heavy rain events more intense. Observed: global 99th percentile rain intensity increased ~7%/°C (consistent with CC). Flood risk: event probability ratio varies by region and event type. 2021 Germany (Ahr Valley): PR 1.2–9×, €30B damage, 184 deaths. 2022 Pakistan monsoon: PR 7–8×, 1,700 deaths, 33 million affected, 1/3 Pakistan flooded. Compound events: simultaneous hot+dry (fire) or simultaneous flood+heat. Tropical cyclone rainfall: +10–15% for same storm intensity. Atmospheric rivers: more extreme as tropics expand.',
          examples: '2022 Pakistan: record monsoon rainfall; floods covered 1/3 country; 1,700 deaths; $30B damage; climate change made 7× more likely · 2021 Ahr Valley (Germany): 1-in-400-year flood, 184 deaths, despite warnings; climate change increased probability 1.2–9× · Harvey 2017 (Houston): 3-day precipitation record by 38%; rainfall made 3× more likely by climate change',
        },
        {
          name: 'Drought, Fire, and Attribution Science',
          icon: Globe,
          color: BRAND.gold,
          desc: 'Drought: reduced precipitation AND/OR increased evapotranspiration (ET). Warming increases ET even without precipitation change. SW USA megadrought (2000–present): driest 22-year period in 1,200 years; climate change contributed ~42% of severity (tree-ring + model attribution). Lake Mead/Powell: record lows, supply for 40M people at risk. Wildfire: drought + heat + wind → fire weather conditions increasingly frequent. 2020 California: 4M+ acres, largest in history. Attribution: heat extreme events → highest confidence; precipitation → moderate; drought → lower (complex). WWA: rapid attribution in days–weeks post-event; legal relevance growing.',
          examples: 'SW US megadrought: attributable 42% to climate change; Lake Mead at 27% capacity (2022) · Australia Black Summer 2019–20: 18M hectares; 3B animals killed or displaced; climate change made occurrence 4–5× more likely · California 2020 fires: 4M acres; 31 deaths; fire weather driven by record heat and drought',
        },
      ],
    },
    {
      type: 'quiz',
      questions: [
        {
          q: "During the July 2021 Pacific Northwest heat wave, the town of Lytton, British Columbia recorded a temperature of 49.6°C — nearly 5°C above Canada's previous all-time temperature record. Attribution scientists published a rapid analysis within 10 days, concluding that this event was 'virtually impossible' without climate change (probability increased by a factor > 150). How is it scientifically possible to determine that a specific event was 'virtually impossible' without climate change, given that heat waves occur naturally?",
          a: [
            "Attribution scientists can only determine the average change in temperature over decades — they cannot determine the probability of specific events; the statement that the heat wave was 'virtually impossible' without climate change is scientifically overconfident and reflects advocacy rather than rigorous science; attribution science provides long-term trends but cannot speak to individual events",
            "Attribution scientists compare the probability of the observed event magnitude in large ensembles of climate model simulations run with observed greenhouse gas concentrations (the 'factual' world) versus model runs without anthropogenic forcing (the 'counterfactual' world); if a temperature of 49.6°C occurs in, say, 1 out of 10,000 factual simulations but in 0 out of 100,000+ counterfactual simulations, the event is estimated as >100× more likely with climate change; the confidence comes from both the large model ensembles and the physical mechanisms: a 49.6°C temperature in an area where pre-industrial conditions had never reached above ~38°C represents such an extreme departure that it falls completely outside the range of natural variability in model simulations",
            "The attribution science for this event was impossible to validate because the 2021 Pacific Northwest heat wave was unprecedented — no similar event has ever occurred before, so there is no observational baseline for comparison; attribution studies can only be conducted for events that have occurred multiple times in the observational record so that statistical frequencies can be empirically estimated",
            "Attribution scientists can determine the fossil fuel company responsible for specific emissions that caused the heat wave; they can trace the specific CO₂ molecules from a particular company's emissions to the temperature increase over the Pacific Northwest; the 'virtually impossible without climate change' statement refers to the emissions of the top 20 fossil fuel companies being necessary to produce the observed temperature",
          ],
          correct: 1,
          explain: "Extreme event attribution is a well-established scientific methodology that addresses specific events — not just long-term trends; the IPCC AR6 WG1 Chapter 11 (on extreme events) includes attribution results for dozens of specific events; the accusation that it 'reflects advocacy' is a mischaracterisation of peer-reviewed, methodologically transparent science (A is incorrect about the methodology and the scientific status of attribution). Attribution of unprecedented events uses model ensembles — not only historical observational statistics — specifically because some events are too extreme to have appeared in the short observational record; the Lytton event occurred zero times in tens of thousands of counterfactual model-years, making the probability estimate of 'virtually impossible' statistical rather than dependent on observational frequency (C incorrectly claims attribution requires multiple historical occurrences). Attribution science does not trace individual CO₂ molecules from specific companies to specific temperature anomalies — that level of causal tracing is not the methodology; attribution studies assess changes in large-scale forcing, not the emissions of specific entities (D mischaracterises the methodology). The correct answer is B: attribution science for extreme events uses large model ensembles — typically thousands of simulations — divided into 'factual' (with observed 20th–21st century greenhouse gas concentrations) and 'counterfactual' (with pre-industrial or no anthropogenic forcing) categories. The probability of the observed event magnitude is estimated from the frequency of occurrence in each ensemble. For the Lytton event, the observed temperature was so extreme (4.9°C above Canada's previous record) that it did not occur in any of the thousands of counterfactual simulation years examined — while it occurred rarely in factual simulations. This is not 'overconfident' — it reflects the statistical reality that a 4.9°C record breach in a region that had never approached such temperatures is an extremely low-probability event without the enhanced greenhouse effect, and a still-rare but detectably more probable event with it. The physical understanding supports this conclusion: the jet stream pattern that produced the heat dome was consistent with patterns that are theorised to become more frequent as the equator-to-pole temperature gradient decreases due to Arctic amplification.",
        },
        {
          q: "The Clausius-Clapeyron relationship predicts that atmospheric water-holding capacity increases by approximately 7% per degree of warming. If this relationship holds universally, one might expect all regions to experience both more intense rainfall and more severe droughts simultaneously as the planet warms. Is this physically consistent, and how does climate change actually alter the global precipitation distribution?",
          a: [
            "The apparent paradox is not real — Clausius-Clapeyron applies only to regions where precipitation is increasing; in regions where precipitation is decreasing due to circulation shifts, the Clausius-Clapeyron relationship does not apply because the physical premise (more water vapour being available to precipitate) requires precipitation to be occurring",
            "The apparent paradox is real but unresolvable — it reveals a fundamental inconsistency in climate science; if warming makes the atmosphere hold more water (requiring more precipitation to remove it), then regions cannot simultaneously get drier; the existence of increased drought alongside increased flooding in climate projections indicates a flaw in the physical models",
            "Both intensification of extreme precipitation AND increased drought are physically consistent consequences of warming, because they operate through different mechanisms: Clausius-Clapeyron increases the intensity of precipitation events when they do occur, but circulation changes can reduce the frequency of precipitation events in subtropical and mid-continental regions; a region can receive the same or less total annual precipitation but have it delivered in fewer, more intense events separated by longer dry intervals; the dry intervals — combined with increased evapotranspiration from warming — intensify droughts even as the rare precipitation events produce more extreme floods",
            "The relationship between warming and precipitation follows a simple geographic rule: regions that are currently wet (tropical rainforests, monsoon regions) will get wetter under climate change, and regions that are currently dry (subtropical deserts, continental interiors) will get drier; this 'wet gets wetter, dry gets drier' rule is the complete explanation for the global precipitation response to warming; no region currently receiving significant precipitation will experience drought under climate change",
          ],
          correct: 2,
          explain: "Clausius-Clapeyron applies to all atmospheric air regardless of whether a region is currently wet or dry — the water vapour content of the atmosphere in any region increases with temperature; in drying regions, the increase in water vapour holding capacity means more of the water that does precipitate comes in intense events, while between events the atmosphere continues to evaporate water from soils and vegetation; A fundamentally mischaracterises the applicability of Clausius-Clapeyron. The apparently contradictory predictions of more flooding AND more drought do not reveal an inconsistency — they reflect genuinely different physical mechanisms operating in different parts of the climate system (B incorrectly concludes that the co-occurrence is a model flaw rather than a real physical prediction). The 'wet gets wetter, dry gets drier' rule is a useful first approximation of the global precipitation response to warming, but it is too simple — many currently wet regions (the UK, parts of the US Northeast) are experiencing increased drought in some seasons despite increased total annual precipitation; some currently dry regions (parts of the Sahel) have received increased rainfall from poleward expansion of monsoon systems in recent decades; the 'rule' is a tendency, not a universal law (D overstates its completeness). The correct answer is C: the apparent paradox dissolves when you distinguish between precipitation intensity and precipitation frequency. Clausius-Clapeyron applies to intensity — when air rises and cools to its dew point, the amount of moisture that condenses (and falls as rain) is greater in a warmer, wetter atmosphere. But circulation changes can reduce precipitation frequency — how often air masses rise and trigger precipitation. In the subtropical regions and mid-continent areas, climate change (through expansion of the Hadley cell and reduced uplift) reduces the frequency of precipitation events. The result: more intense rain when it does rain, but longer dry periods between events. Combined with enhanced evapotranspiration during warm, dry periods (which is also amplified by warming), this produces soil moisture deficits — drought — even in regions where total annual precipitation changes little. This explains the consistent observation that both extreme precipitation events and drought frequency are increasing in many regions simultaneously.",
        },
        {
          q: "Climate attribution science has increasingly been used in legal proceedings. In the Urgenda v. Netherlands case (2019), the Dutch Supreme Court upheld an order requiring the Dutch government to reduce greenhouse gas emissions by 25% by 2020, partly on the basis that climate change poses a serious risk to human rights protected under Dutch and European law. What scientific evidence would attribution science provide to support such a legal argument, and what are the legitimate limitations of using attribution science in legal contexts?",
          a: [
            "Attribution science cannot be used in legal contexts because it produces probabilistic statements ('X times more likely') rather than deterministic causal statements ('climate change caused this event'); legal standards of causation require proof of specific causation, not statistical probabilities; therefore attribution studies are inadmissible as causal evidence in any legal proceeding involving climate change",
            "Attribution science provides legally relevant evidence about the changed risk landscape from climate change: studies showing that heat waves, floods, and other extreme events are more frequent and more severe as a result of anthropogenic forcing can establish that current greenhouse gas levels impose quantifiable additional risk of harm; legitimate limitations include: (a) probabilistic rather than specific causation; (b) uncertainty ranges that vary by event type (heat wave attribution more robust than drought attribution); (c) difficulty establishing which specific emissions created the risk; (d) the counterfactual comparison (no anthropogenic forcing) requires model simulations that have inherent uncertainty; courts and policymakers must weigh these limitations when using attribution science, but probabilistic risk evidence is routinely accepted in other legal contexts (product liability, public health)",
            "Attribution science provides perfect causal evidence for legal proceedings — the probability ratios calculated by attribution studies (e.g., a 7× increase in flood probability) meet the legal standard of 'beyond reasonable doubt' for any event with PR > 2, because it is more likely than not that climate change was the decisive cause; all damages from extreme events with PR > 2 are therefore attributable to greenhouse gas emitters and should be legally compensable",
            "Attribution science is only applicable to legal cases against government defendants (as in Urgenda) and cannot be used against fossil fuel companies, because governments have the legal obligation to protect citizens from climate harm, while fossil fuel companies are merely producers of a legal product; the legal theory of corporate liability for climate damages requires entirely different types of evidence than attribution science",
          ],
          correct: 1,
          explain: "Probabilistic evidence is routinely accepted in legal proceedings across multiple jurisdictions — in product liability cases (epidemiological relative risk statistics are used to establish that a drug or substance caused harm even without demonstrating individual causation), public health cases, and environmental law; the claim that only deterministic causation is legally relevant is incorrect as a matter of legal practice (A incorrectly states the legal standard for causation). The claim that PR > 2 automatically meets 'beyond reasonable doubt' is incorrect — legal standards of causation are complex and jurisdiction-dependent; even in civil cases, PR > 2 (more likely than not) is sometimes used as a threshold for causation but this is contested in climate law; 'beyond reasonable doubt' is the criminal standard which is very different from civil causation; attribution science does not by itself establish legal liability (C overstates the legal implications of PR values). The claim that attribution science cannot be used against fossil fuel companies is incorrect as a matter of developing climate law — multiple lawsuits against oil companies in the US and EU are specifically using attribution science; the legal theory of 'market share liability' (developed in DES pharmaceutical cases) has been proposed as a framework; attribution science is directly relevant to establishing causation in these cases (D incorrectly constrains the legal applicability of attribution science). The correct answer is B: attribution science provides scientifically rigorous, peer-reviewed probabilistic evidence that is legally relevant even though it is not deterministically specific. The value of attribution studies for legal proceedings is: they quantify how much climate change has altered the risk of harm (as in Urgenda, where courts accepted that anthropogenic climate change creates a serious risk of rights violations for Dutch citizens); they have been peer-reviewed and published in leading scientific journals; they use methods that are transparent and replicable. The legitimate limitations — probabilistic rather than deterministic, uncertainty ranges, model-dependence, difficulty assigning specific emissions to specific emitters — are genuine scientific constraints that courts must weigh. These limitations do not make attribution science inadmissible; they are analogous to the probabilistic evidence routinely used in tort law (e.g., epidemiological studies in asbestos litigation, relative risk calculations in pharmaceutical liability cases).",
        },
      ],
    },
  ],
}

export default extremeWeatherClimate
