import { Globe, BarChart, Layers, Activity } from 'lucide-react'
import { BRAND } from '@/lib/brand'
import type { Lesson } from './types'

const multiProxySynthesis: Lesson = {
  id: 'clim-201-1-4-4',
  title: 'Multi-Proxy Synthesis and Model-Data Comparison',
  track: 'cli',
  trackName: 'Paleoclimatology',
  level: 'Intermediate',
  duration: '16 min',
  xpReward: 200,
  description: `No single proxy can reconstruct Earth\'s climate history on its own — each archive has gaps, biases, and regional perspectives that require integration with hundreds of other records. The PAGES 2k Consortium\'s synthesis of 692 proxy records across seven continental regions, compared against climate model simulations from PMIP, has transformed paleoclimatology from a collection of case studies into a quantitative science capable of constraining climate sensitivity, testing model physics, and contextualising twenty-first-century warming within the full range of natural variability.`,
  sources: [
    { org: 'PAGES2k Consortium', title: 'PAGES 2k Consortium — Consistent multidecadal variability in global temperature reconstructions (Nature Geoscience, 2019)', url: 'https://www.nature.com/articles/s41561-019-0400-0' },
    { org: 'PAGES2k Consortium', title: 'PAGES 2k Consortium — Proxy-based reconstructions of hemispheric and global surface temperature variations over the past two millennia (Science, 2013)', url: 'https://www.science.org/doi/10.1126/science.1228026' },
    { org: 'Nature', title: 'Tierney et al. — Glacial cooling and climate sensitivity revisited (Nature, 2020)', url: 'https://www.nature.com/articles/s41586-020-2617-x' },
    { org: 'Science', title: 'Shakun et al. — Global warming preceded by increasing carbon dioxide concentrations during the last deglaciation (Nature, 2012)', url: 'https://www.nature.com/articles/nature10915' },
    { org: 'NOAA NCEI', title: 'PMIP4 — Paleoclimate Modelling Intercomparison Project Phase 4', url: 'https://pmip4.lsce.ipsl.fr/' },
  ],
  sections: [
    {
      type: 'intro',
      title: 'Unifying 692 proxy records into a coherent picture of the last 2,000 years',
      body: `Every proxy archive discussed in this chapter — tree rings, ice cores, corals, speleothems, pollen, varved sediments, marine sediment cores — records climate from a particular place, through a particular biological or physical mechanism, with particular temporal resolution and age uncertainty. No single record is sufficient to characterise global mean surface temperature (GMST) change. The challenge of **multi-proxy synthesis** is to combine records with incommensurable resolution, dating uncertainty, seasonal bias, and geographic coverage into a coherent, quantified, globally representative reconstruction — and to propagate the uncertainties from each source through to the final product honestly.

The **PAGES 2k Consortium** (PAGES: Past Global Changes) was established precisely to meet this challenge. Beginning with a landmark 2013 paper in *Science* and culminating in the comprehensive 2017–2019 database and analysis, the consortium assembled a quality-controlled database of 692 proxy records from seven continental and ocean regions (Arctic, Asia, Australasia, Europe, North America, South America, and the Antarctic), spanning the Common Era (last 2,000 years) with at least decadal resolution. Records were screened for chronological reliability, significant climate correlation, and representativeness. The resulting **2k database** has been used to produce multiple independent temperature reconstructions using different statistical methods — RegEM, principal components, composite-plus-scale — all showing consistent patterns: a Medieval Climate Anomaly (MCA, broadly 950–1250 CE) averaging ~0.3°C above the 1961–1990 reference period in some regions, a Little Ice Age (LIA, broadly 1450–1850 CE) averaging ~−0.3°C, and an unambiguous late-20th and 21st century warming exceeding any multi-decadal period in the 2,000-year record.

**Proxy screening and uncertainty quantification** are the methodological backbone of modern multi-proxy synthesis. Records are accepted into a synthesis database only if they meet criteria for temporal resolution (at least decadal), chronological control (age model uncertainty <200 years for the last 2,000 years in most protocols), and a statistically significant correlation with a climate variable during the calibration period. Uncertainty in the final reconstruction enters from four main sources: (1) proxy measurement uncertainty; (2) age model uncertainty (particularly the ±50–200 year uncertainty in radiocarbon-dated records); (3) calibration uncertainty (the regression coefficient relating the proxy to climate); and (4) **pseudoproxy experiments** — tests using climate model output as synthetic proxy data to evaluate reconstruction method performance before applying to real data.

**Model-data comparison** closes the loop between paleoclimate observations and climate models. The **Paleoclimate Modelling Intercomparison Project (PMIP)**, coordinated alongside CMIP, defines standardised boundary conditions and experiments for simulating key past climate states: the Last Glacial Maximum (LGM, 21 ka), the mid-Holocene (6 ka), the Last Interglacial (LIG, 127 ka), and the Last Millennium (850–1850 CE). Models are evaluated by comparing their simulated spatial patterns and amplitudes of climate change against proxy reconstructions. When models systematically disagree with proxy data — e.g., underestimating LGM tropical cooling relative to UK'₃₇ and Mg/Ca data — this signals either a systematic model bias or a misinterpretation of proxy data, driving iterative improvement of both. The LGM remains the primary target for constraining **equilibrium climate sensitivity (ECS)**: the global mean cooling of ~6°C (relative to pre-industrial) in response to radiative forcing from lower CO₂ (~190 ppm), ice sheet albedo, and other glacial boundary conditions, when inverted using energy balance or model-data approaches, yields ECS estimates of ~2.5–4.0°C per CO₂ doubling — exactly consistent with the IPCC AR6 likely range.`,
      keyTerms: [
        {
          term: 'PAGES 2k Consortium',
          def: 'A working group of the Past Global Changes (PAGES) programme that coordinates the assembly, quality control, and scientific analysis of proxy climate records spanning the Common Era (last 2,000 years). The flagship dataset (v3.0, 2017) comprises 692 proxy records from seven regional working groups — Arctic, Asia, Australasia, Europe, North America, South America, and Antarctica. Records include tree rings (~45%), lake and marine sediment records (~30%), ice cores (~15%), corals (~5%), and speleothems (~5%). The PAGES 2k database underpins the IPCC AR6 assessment of Common Era temperature variability and is freely available via the NOAA Paleoclimatology archive.',
        },
        {
          term: 'Medieval Climate Anomaly (MCA)',
          def: 'A period of anomalously warm climate in portions of the Northern Hemisphere, broadly dated to 950–1250 CE, documented in multiple proxy archives including tree rings, ice cores, corals, and lake sediments. The MCA is best expressed regionally rather than globally — it is most pronounced in the North Atlantic and western Europe, less coherent in the tropics and Southern Hemisphere. PAGES 2k reconstructions indicate Northern Hemisphere MCA temperatures were ~0.1–0.3°C above the 1961–1990 reference period at decadal timescales in multi-proxy composites — significantly below the approximately 1.2°C warming observed by the late 20th century. The MCA was likely driven by a combination of positive solar forcing (slightly higher solar irradiance), reduced volcanic activity, and internal variability.',
        },
        {
          term: 'Little Ice Age (LIA)',
          def: 'A period of cooler-than-average conditions documented globally but most prominently in Europe and the North Atlantic, broadly dated to 1450–1850 CE. The LIA is characterised in multi-proxy reconstructions by Northern Hemisphere temperatures approximately 0.2–0.5°C below the 1961–1990 reference period at multi-decadal timescales. The LIA was not a uniform cold period — it included warmer decades punctuated by periods of intense cold. Volcanic forcing (a cluster of large eruptions from 1250–1300 CE likely triggered the LIA onset) combined with low solar activity (Maunder Minimum, 1645–1715 CE) and ocean circulation changes (possible AMOC weakening) drove the cooling. The LIA serves as the most recent analogue for volcanically forced climate cooling and is a key validation target for last-millennium climate model simulations.',
        },
        {
          term: 'PMIP (Paleoclimate Modelling Intercomparison Project)',
          def: 'An international coordinated programme that defines standardised experiments, boundary conditions, and output protocols for simulating key past climate states with climate models, enabling systematic comparison of model results with paleoclimate proxy data. PMIP experiments include the Last Glacial Maximum (21 ka: lower CO₂, large ice sheets, altered sea level), mid-Holocene (6 ka: altered orbital forcing), Last Interglacial (127 ka: higher Northern Hemisphere summer insolation, warmer Arctic), deglaciation (21–0 ka), and Last Millennium (850–1850 CE: realistic volcanic, solar, and land-use forcing). PMIP operates within the CMIP framework, with PMIP4 contributing to IPCC AR6 assessments. Model-data comparisons within PMIP are the primary method for evaluating model physics at high climate-forcing amplitudes relevant to future climate change.',
        },
        {
          term: 'equilibrium climate sensitivity (ECS)',
          def: 'The equilibrium change in global mean surface temperature resulting from a sustained doubling of atmospheric CO₂ concentration relative to pre-industrial levels, after the climate system has reached a new energy balance (typically defined as the response after several thousand years of integration). ECS is the canonical measure of the long-term strength of the greenhouse effect amplified by all climate feedbacks (water vapour, lapse rate, surface albedo, clouds). The IPCC AR6 assessed ECS likely range is 2.5–4.0°C, with a best estimate of 3.0°C, based on a synthesis of evidence from paleoclimate, instrumental observations, and process understanding. Paleoclimate estimates from the LGM and Pliocene contribute the most constraining upper bound, ruling out ECS values above ~5°C.',
        },
        {
          term: 'pseudoproxy experiment',
          def: `A method for testing the performance of paleoclimate reconstruction techniques before applying them to real proxy data. In a pseudoproxy experiment, the output of a climate model simulation is used as a synthetic "truth" — temperature fields are extracted at proxy locations, corrupted with realistic noise levels representing proxy measurement uncertainty and age model uncertainty, and then fed into the reconstruction method. The method\'s output (the reconstructed temperature history) is then compared against the known model truth. Pseudoproxy experiments evaluate whether a reconstruction method correctly recovers the amplitude of centennial variability, regional patterns, and extreme periods, or whether it systematically underestimates variance — a finding that has important implications for assessing MCA and LIA amplitudes in real reconstructions.`,
        },
      ],
    },
    {
      type: 'concept',
      title: 'Building the PAGES 2k reconstruction: screening, synthesis, and uncertainty',
      body: `Multi-proxy synthesis is not simply averaging available records together — it requires deliberate methodological choices about which records to include, how to weight them, and how to propagate uncertainties. The PAGES 2k process established systematic screening protocols, multiple independent reconstruction methods, and a transparent uncertainty framework that has substantially improved the credibility and reproducibility of Common Era temperature reconstructions compared with earlier ad-hoc studies.`,
      cards: [
        {
          name: 'Proxy Screening and Quality Control',
          icon: Layers,
          color: BRAND.accent,
          desc: 'Records in the PAGES 2k database pass a multi-stage screening: (1) Temporal coverage: at least decadal resolution with >50% of the last 2,000 years covered; (2) Chronological control: age model uncertainty characterised, with <200-year age uncertainty for most of the record; (3) Climate correlation: significant correlation (p < 0.05) between the proxy and a target climate variable during the instrumental calibration period; (4) Metadata completeness: geographic coordinates, proxy type, archive type, and calibration season documented. Passing proxies are assigned a primary climate variable (temperature, precipitation, pressure) and a primary season (annual, summer, winter, growing season) based on the documented relationship.',
          examples: 'PAGES 2k v3.0: 692 records from 648 locations — started from ~2,000 candidate records, ~65% passed screening · Archive types: 261 tree-ring, 197 lake/marine sediment, 58 ice core, 59 coral, 29 speleothem, 6 documentary, 82 other · Screening failure modes: age model gaps >200 years (most common), insufficient calibration period overlap with instrumental data, geographic co-location ambiguity · Regional density contrast: Europe and North America densely covered; tropical Africa, central Asia, and Southern Ocean sparsely covered — creates spatial sampling bias in global mean estimates',
        },
        {
          name: 'Reconstruction Methods and Robustness Testing',
          icon: BarChart,
          color: BRAND.jade,
          desc: 'PAGES 2k applies multiple reconstruction methods to the same screened database to test robustness: composite-plus-scale (CPS: area-weight proxies, normalise, scale to instrumental mean and variance), Principal Component Regression (PCR: regress leading principal components on instrumental temperature field), RegEM (regularised expectation-maximisation: infills missing values and calibrates simultaneously), and Bayesian hierarchical modelling. Consistency across methods increases confidence in reconstructed features; disagreement identifies sensitive methodological choices. Pseudoproxy experiments on PMIP last-millennium simulations are used to quantify systematic biases in each method.',
          examples: 'PAGES 2k 2019 (Nature Geoscience): 7 reconstruction methods applied to same database — all 7 show coherent 20th–21st century warming exceeding any multi-decadal period in the 2k record · LIA signal: amplitude ranges from −0.2°C to −0.5°C across methods depending on standardisation — largest spread source · RegEM amplitude recovery in pseudoproxy tests: ~70–85% of true amplitude recovered depending on proxy noise level — systematic amplitude underestimation must be accounted for in LIA/MCA comparisons · Bayesian hierarchical model (PAGES 2k BACONR): propagates age model uncertainty through to final temperature estimate — increases 2σ uncertainty band by ~30% vs. median age model',
        },
        {
          name: 'Key Patterns: MCA, LIA, and Industrial Warming',
          icon: Activity,
          color: BRAND.coral,
          desc: 'The PAGES 2k reconstructions consistently show three features across all methods and proxy subsets: a Medieval warm episode (950–1250 CE) of ~0.1–0.3°C above the 1961–1990 baseline at global/hemispheric scale; a Little Ice Age cooling of ~0.2–0.5°C; and a late 20th–21st century warming that is unambiguously the warmest multi-decadal period of the past 2,000 years at global scale and by a wide margin. The industrial warming exceeds the peak MCA temperatures by ~0.8–1.2°C in multi-method ensemble means.',
          examples: 'PAGES 2k 2019 NH median reconstruction: MCA peak (950–1050 CE decadal mean) ~+0.2°C relative to 1961–1990; 2000–2009 decade ~+0.77°C — a difference of ~0.6°C · LIA coldest decade (1600s in most reconstructions): −0.4 to −0.5°C relative to 1961–1990 in most methods · Antarctica exception: the Antarctic PAGES 2k record shows warming in the Medieval period but with high regional variability — the global mean MCA pattern is dominated by NH records · 20th century trend in PAGES 2k: 1.0–1.2°C warming from the LIA minimum to 2000 CE in NH mean — consistent with instrumental records and CMIP6 historical simulations',
        },
      ],
    },
    {
      type: 'concept',
      title: 'Model-data comparison and paleoclimate constraints on climate sensitivity',
      body: `Comparing climate model simulations against proxy reconstructions tests whether models correctly capture the physics of climate on timescales and forcing amplitudes that far exceed the instrumental record. The LGM is the most constrained past climate state for estimating equilibrium climate sensitivity, while PMIP last-millennium simulations provide a high-resolution benchmark for evaluating forced climate variability, natural climate modes, and the transition from pre-industrial to industrial climate.`,
      cards: [
        {
          name: 'The LGM as a Climate Sensitivity Benchmark',
          icon: Globe,
          color: BRAND.amethyst,
          desc: 'The Last Glacial Maximum (21 ka) represents a well-characterised past state with ~90 ppm less CO₂ than pre-industrial (185 vs. 280 ppm), large ice sheets adding ~3.2 W/m² of albedo forcing, and a resulting global mean cooling of ~5.5–7°C (MARGO and Tierney et al. 2020 synthesis). Inverting the radiative forcing for these boundary conditions using energy balance relationships yields an ECS of 2.5–4.0°C per doubling — providing the most robust independent constraint on ECS from the paleoclimate record.',
          examples: 'Tierney et al. (2020, Nature): Bayesian assimilation of 539 LGM proxy records with energy balance model — ECS 2.6–3.9°C (66% range) · MARGO Project Members (2009): multi-proxy SST synthesis — tropical cooling ~1.7°C, extratropical cooling ~3–4°C, polar amplification factor ~2 · CMIP6 high-ECS models (>4.5°C) produce LGM cooling inconsistent with proxy data — eliminates ~20% of CMIP6 ensemble as implausible · Abe-Ouchi et al. (2013, Nature): PMIP3 models systematically underestimate Arctic summer warming in the LIG (127 ka) — implies model sea-ice feedbacks too weak',
        },
        {
          name: 'PMIP Last Millennium and ENSO Variability',
          icon: BarChart,
          color: BRAND.gold,
          desc: 'PMIP last-millennium simulations (850–1850 CE) use reconstructed volcanic, solar, and land-use forcing to simulate the MCA and LIA — providing direct tests of how well models reproduce forced centennial variability. Coral and speleothem networks reveal that ENSO variability was suppressed during the mid-Holocene (when orbitally forced Northern Hemisphere summer insolation was higher) and enhanced during the LIA, consistent with some but not all PMIP models. This tests whether CMIP6 models correctly simulate future ENSO behaviour under greenhouse gas forcing.',
          examples: 'Masson-Delmotte et al. PMIP4 last-millennium ensemble: volcanic forcing dominates NH temperature variance in the 850–1850 CE period; solar forcing 30–50% smaller effect · LIA onset timing in models vs. proxies: most PMIP models place LIA onset correctly (1250–1350 CE) following the 1257 Samalas eruption — validates volcanic forcing reconstructions · Holocene ENSO in coral proxy network: ENSO amplitude ~50% of modern values at 6 ka in Pacific coral records — CMIP6 models reproduce this suppression in ~60% of ensemble members · Medieval ENSO in Palmyra coral δ¹⁸O: comparable to modern amplitude, consistent with PMIP3 simulations showing little MCA–modern ENSO difference',
        },
        {
          name: 'Climate Field Reconstruction and CMIP6 Validation',
          icon: Activity,
          color: BRAND.ruby,
          desc: 'Climate field reconstruction (CFR) recovers the full spatial temperature field from spatially sparse proxy networks using statistical relationships between local proxy records and large-scale temperature patterns (teleconnections). CFR allows direct comparison between the spatial pattern of past climate anomalies and climate model output at the same spatial scale, going beyond global or hemispheric means. Emerging comparisons of PAGES 2k CFR outputs against CMIP6 historical simulations and PMIP last-millennium runs are testing model-simulated internal variability patterns, forced response structures, and regional climate sensitivities.',
          examples: 'Mann et al. (2009, Science): CFR of MCA and LIA using 1,209 proxy records — identifies MCA warming pattern with La Niña-like tropical Pacific SST pattern and LIA with El Niño-like pattern, suggesting ENSO played a role in driving regional MCA–LIA contrasts · PAGES 2k volcanic response test: proxy reconstruction volcanic cooling amplitudes compared to PMIP4 large-ensemble simulations — models correctly reproduce ~0.3–0.5°C NH cooling after major eruptions at decadal timescales · Data assimilation approach (PNAS 2018): Last Glacial Maximum temperature field reconstructed by assimilating 473 proxy records into CCSM4 model framework — provides spatially complete view consistent with both models and observations · CESM2 Last Millennium Ensemble (100 members): compared with PAGES 2k by region to quantify signal-to-noise ratio and validate model internal variability patterns in each of the 7 continental domains',
        },
      ],
    },
    {
      type: 'visualization',
      title: 'From individual proxy archives to a global climate reconstruction: the PAGES 2k to PMIP pipeline',
      body: 'Trace how individual proxy records from diverse archives and geographic regions are assembled, screened, combined into regional and global reconstructions, compared against climate model simulations, and ultimately used to constrain climate sensitivity — illustrating the full pathway from raw palaeoclimate data to quantitative climate science.',
      interaction: {
        type: 'flow-simulator' as const,
        description: 'showing the complete workflow from individual proxy records through PAGES 2k database screening and multi-method reconstruction to PMIP model-data comparison and climate sensitivity constraint, illustrating how paleoclimate data transforms into quantitative climate science',
        nodes: [
          {
            id: 'proxy-collection',
            label: 'Diverse Proxy Archives',
            description: 'Thousands of proxy climate records exist in various forms: tree-ring width and density chronologies from 60+ countries deposited in the ITRDB; ice core stable isotope and gas records from Greenland and Antarctica archived at NOAA Paleoclimatology; speleothem δ¹⁸O records with U-Th age models from cave sites across five continents; coral skeletal δ¹⁸O and Sr/Ca records from tropical reefs; pollen percentage diagrams from Neotoma database; varved lake sediment records; and ocean sediment cores from IODP/ODP drilling programmes. Each record has different temporal resolution (annual to centennial), age uncertainty (±1 year for cross-dated tree rings to ±500 years for some radiocarbon-dated sediments), and climate sensitivity (seasonal vs. annual; temperature vs. precipitation).',
            color: BRAND.jade,
          },
          {
            id: 'pages-screening',
            label: 'PAGES 2k Screening and Metadata',
            description: 'Each submitted record is evaluated against PAGES 2k criteria: (1) Temporal coverage: ≥50% of the last 2,000 years at decadal or better resolution; (2) Chronological control: documented age model with uncertainties; (3) Climate signal: demonstrated significant correlation with a climate variable in the instrumental calibration period (1850–present); (4) Metadata: archive type, proxy type, primary climate variable, seasonality, geographic location. Records failing any criterion are excluded. The screening process reduces the pool from ~2,000 candidate records to 692 accepted records. Passing records are assigned seasonal and climate variable metadata and compiled into the versioned PAGES 2k LiPD (Linked Paleo Data) database.',
            color: BRAND.accent,
          },
          {
            id: 'regional-composites',
            label: 'Regional Composites (7 Regions)',
            description: 'Screened records are divided into seven geographic regions: Arctic, Europe, Asia, North America, South America, Australasia, and Antarctica. Within each region, records are combined using area-weighted compositing or covariance-based methods to produce a regional temperature reconstruction with regional uncertainty. Regional composites capture the spatial heterogeneity of climate — the MCA and LIA are not synchronous globally; the Arctic MCA is most prominent before 1100 CE while the NH continental MCA peaks 1000–1200 CE. Regional reconstructions are the primary product used in climate attribution studies and model comparison.',
            color: BRAND.gold,
          },
          {
            id: 'global-reconstruction',
            label: 'Global Reconstruction (Multiple Methods)',
            description: 'Regional composites are combined into global or hemispheric mean surface temperature reconstructions using multiple independent statistical approaches — composite-plus-scale (CPS), principal component regression (PCR), regularised expectation-maximisation (RegEM), Gaussian process regression, and Bayesian hierarchical modelling. Running all seven methods on the same database and comparing results tests reconstruction robustness: where methods agree, the result is robust; where they diverge, the source of discrepancy (standardisation, infilling, variance scaling) is investigated. Uncertainty intervals on the global reconstruction reflect propagated proxy, age model, and calibration uncertainty, quantified using pseudoproxy experiments on PMIP last-millennium simulations.',
            color: BRAND.amethyst,
          },
          {
            id: 'pmip-comparison',
            label: 'PMIP Model-Data Comparison',
            description: 'PMIP climate models — CESM2, IPSL-CM6A-LR, MPI-ESM, and others — are run with standardised boundary conditions for key past states: Last Millennium (volcanic, solar, land-use forcing 850–1850 CE), mid-Holocene (6 ka: orbital forcing only), and Last Glacial Maximum (21 ka: lower CO₂, large ice sheets). Model output is compared with proxy reconstructions at both regional and global scales. Comparisons evaluate: (1) mean state accuracy; (2) forced variability amplitude (e.g., volcanic cooling after 1257 Samalas); (3) internal variability patterns (multidecadal oscillations); (4) spatial pattern of anomalies. Models that produce reconstructed temperature patterns inconsistent with proxy evidence are identified for investigation.',
            color: BRAND.ruby,
          },
          {
            id: 'ecs-constraint',
            label: 'Climate Sensitivity Constraint',
            description: 'Model-data comparison across multiple climate states — particularly the well-constrained LGM cooling of ~6°C in response to known radiative forcing from lower CO₂ and ice sheet albedo — allows paleoclimate-based estimates of equilibrium climate sensitivity (ECS). Bayesian frameworks (Tierney et al. 2020; Sherwood et al. 2020) combine LGM proxy data with energy balance models and process understanding to yield ECS estimates of 2.6–3.9°C (66% range) — ruling out both very low ECS (<2°C) and very high ECS (>5°C) values. These paleoclimate constraints, combined with instrumental-period observations and process-based estimates, define the IPCC AR6 likely ECS range of 2.5–4.0°C with a best estimate of 3.0°C.',
            color: BRAND.accentHot,
          },
        ],
        edges: [
          { from: 'proxy-collection',    to: 'pages-screening',     label: 'Records submitted with metadata; screened for temporal coverage, age control, and climate signal' },
          { from: 'pages-screening',     to: 'regional-composites', label: '692 accepted records divided into 7 geographic regions and area-weighted composited' },
          { from: 'regional-composites', to: 'global-reconstruction', label: '7 regional reconstructions combined using CPS, PCR, RegEM, and Bayesian methods' },
          { from: 'global-reconstruction', to: 'pmip-comparison',   label: 'PAGES 2k reconstruction compared against PMIP last-millennium and LGM model ensembles' },
          { from: 'pmip-comparison',     to: 'ecs-constraint',      label: 'LGM model-data comparison used in Bayesian energy balance inversion to constrain ECS' },
          { from: 'ecs-constraint',      to: 'pmip-comparison',     label: 'ECS constraints feed back to identify implausible CMIP6 models, refining model evaluation' },
        ],
      },
    },
    {
      type: 'quiz',
      questions: [
        {
          q: 'The PAGES 2k Consortium assembled 692 proxy records for its Common Era temperature reconstruction. What is the primary reason for using multiple independent proxy types and reconstruction methods, rather than relying on the largest single proxy dataset?',
          a: [
            'Multiple proxy types are used because regulatory guidelines for IPCC assessments require a minimum of five proxy types; using a single proxy type would fail to meet scientific review standards regardless of the statistical power of the dataset',
            'Multiple proxy types are required because individual proxy archives record different climate variables in different seasons and at different spatial scales — combining diverse proxies reduces systematic biases unique to each archive type, extends geographic coverage to regions where any single archive type is sparse, and allows internal consistency checks; running multiple independent reconstruction methods tests robustness by identifying features that are stable across methodological choices versus features that appear only in specific statistical frameworks',
            'Multiple proxies are needed because tree rings — the largest single archive — are known to be unreliable for the medieval period due to widespread divergence problems that predate the post-1980 divergence; mixing tree rings with non-tree-ring records corrects for medieval divergence bias through statistical averaging',
            'Using multiple reconstruction methods is required to average out the age model uncertainties in individual records: since each method uses a different approach to handling radiocarbon age uncertainty, the mean of all methods produces a reconstruction with zero net age model error, eliminating the need for individual age model corrections',
          ],
          correct: 1,
          explain: 'The use of multiple proxy types in PAGES 2k addresses several fundamental limitations of individual archives. Tree rings provide excellent annual resolution but are absent from tropical regions, most of the ocean, and the polar zones; they may record only summer temperatures and are subject to the divergence problem after ~1980. Ice cores provide outstanding temporal continuity but are geographically restricted to polar and high-altitude regions. Corals are limited to tropical marine environments and rarely extend beyond 500 years continuously. Speleothems require specific cave environments and are most sensitive to monsoon variability. Marine sediment cores lack annual resolution in most settings. Each archive type therefore has geographic blind spots, seasonal biases, and resolution limitations. By combining all types — weighted by their individual quality metrics and geographic coverage — the multi-proxy synthesis achieves broader and more representative geographic coverage, reduces the influence of proxy-specific seasonal biases on the global mean estimate, and allows cross-validation: if a climate event appears in tree rings, corals, ice cores, and speleothems simultaneously, it is far more likely to be a genuine climate signal than an artefact of one archive type. Running multiple reconstruction methods (CPS, PCR, RegEM, Bayesian) on the same screened database further tests robustness: features that appear in all methods are robust; features that appear in only one method reflect methodological sensitivity that must be investigated. Answer A is incorrect — no IPCC regulatory minimum specifies five proxy types; the scientific rationale drives proxy diversity, not procedural requirements. Answer C is incorrect — medieval divergence is not an established, well-documented phenomenon separate from the post-1980 divergence; the post-1980 divergence is the well-documented issue, and mixing proxy types does not "correct" for tree ring biases through averaging. Answer D is incorrect — different reconstruction methods do not average out radiocarbon age uncertainties to zero; age uncertainty is a physical property of individual records that must be propagated through any method, not cancelled by averaging across methodological approaches.',
        },
        {
          q: 'PAGES 2k reconstructions show that Northern Hemisphere temperatures during the Medieval Climate Anomaly (MCA, ~950–1250 CE) were approximately 0.1–0.3°C above the 1961–1990 reference period, while the 2000s decade was approximately 0.77°C above the same reference. What does this comparison reveal about the causes of the current warming?',
          a: [
            'The comparison proves that current warming is entirely within the range of natural variability because the MCA temperatures — driven by natural solar and volcanic forcing — were comparable to or exceeded current temperatures in some regional records; this demonstrates that no human forcing is needed to explain modern warming',
            'The comparison reveals that current global mean warming substantially exceeds the peak of the MCA, and since the MCA was driven by natural forcing (modestly higher solar activity and reduced volcanic forcing), the additional ~0.5–0.6°C of warming beyond the MCA peak requires an explanation beyond natural variability — provided by the greenhouse gas forcing of the industrial era; this is consistent with attribution studies showing that natural forcing alone cannot explain the post-1950 warming trend',
            'The MCA–modern comparison is not meaningful for attribution purposes because the MCA was a regional phenomenon (primarily Europe and the North Atlantic) while current warming is global; regional MCA temperatures did exceed modern levels in some areas, demonstrating that local warming today is not unprecedented in those regions even if the global mean is higher',
            'The comparison shows that climate models overestimate 20th-century warming: PMIP simulations reproduce the MCA amplitude of ~0.2–0.3°C correctly, but CMIP6 historical simulations produce 20th-century warming of ~1.0°C — far more than the MCA amplitude — suggesting the greenhouse gas forcing in CMIP6 models is too strong by a factor of ~3–4',
          ],
          correct: 1,
          explain: 'The PAGES 2k MCA–modern comparison is one of the most important pieces of evidence for the unprecedented nature of current anthropogenic warming. The key logic is as follows: (1) The MCA represents the warmest natural multi-decadal period of the Common Era, driven by slightly elevated solar irradiance (~0.1–0.3 W/m² above the reference period according to solar reconstructions), reduced volcanic activity, and positive phases of internal climate modes (AMO, PDO). Despite these favourable natural conditions, the global mean MCA warming was only ~0.1–0.3°C above the 1961–1990 baseline in PAGES 2k multi-method reconstructions. (2) The 2000–2009 decade was ~0.77°C above the same 1961–1990 baseline in PAGES 2k. (3) The difference (~0.5–0.6°C between MCA peak and modern) cannot be explained by natural forcing: solar irradiance is not significantly higher today than during the MCA, and there has been no reduction in volcanic activity. The additional warming requires an external forcing that was absent or weaker during the MCA — specifically, the radiative forcing from industrially emitted greenhouse gases (~2.7 W/m² by 2019). This is fully consistent with climate model attribution studies (comparing all-forcing vs. natural-only CMIP6 simulations) that show natural forcing alone cannot account for the post-1950 warming trend. Answer A misrepresents the MCA amplitude — even the highest regional MCA estimates in tree ring records rarely exceed 0.5°C above 1961–1990, well below the ~1.2°C current global mean anomaly relative to pre-industrial. Answer C is partially correct that the MCA had regional asymmetry, but this does not invalidate the global comparison — the PAGES 2k reconstruction explicitly addresses this by using globally distributed records. Answer D mischaracterises the PMIP–CMIP6 relationship: PMIP models do not systematically over-produce 20th-century warming; the CMIP6 historical warming of ~1.0°C is consistent with the observed instrumental warming and does not conflict with the correctly reconstructed MCA amplitude.',
        },
        {
          q: 'How does the Last Glacial Maximum (LGM) serve as an independent constraint on equilibrium climate sensitivity (ECS), and what specific data and methods are used to extract an ECS estimate from the LGM?',
          a: [
            'The LGM constrains ECS by providing a period when CO₂ was doubled relative to pre-industrial; dividing the observed LGM warming by 2 gives the ECS directly. LGM CO₂ was ~560 ppm compared to pre-industrial ~280 ppm, and the LGM was ~3°C warmer than pre-industrial, giving ECS = 3°C',
            'The LGM provides an ECS constraint through the observation that no northern hemisphere ice sheets existed at LGM, allowing scientists to calculate the radiative forcing from the absence of ice sheet albedo; dividing the LGM warming by this forcing gives ECS without needing to know past CO₂ concentrations',
            'The LGM provides a climate sensitivity constraint because it represents a well-characterised cooler equilibrium state: lower CO₂ (~190 ppm vs. ~280 ppm pre-industrial), large ice sheets (~3.2 W/m² albedo forcing), and a reconstructed global mean cooling of ~5.5–7°C from multi-proxy synthesis; inverting the total radiative forcing from all LGM boundary conditions using energy balance or Bayesian methods yields ECS of ~2.5–4.0°C per CO₂ doubling — constraining both the lower bound (ruling out very low ECS) and upper bound (ruling out models producing too little cooling)',
            'The LGM constrains ECS through carbon isotope records (δ¹³C in benthic foraminifera) that directly measure past radiative forcing from greenhouse gases; the sensitivity is calculated as the ratio of observed δ¹³C change to the δ¹³C equivalent forcing, giving a proxy-based ECS independent of climate model assumptions',
          ],
          correct: 2,
          explain: 'Using the LGM to constrain ECS is one of the most powerful applications of paleoclimate data to future climate projections, and the methodology deserves careful attention. The LGM (21,000 years ago) represents an equilibrium or near-equilibrium climate state with well-characterised boundary conditions that can be used as known forcings in an energy balance calculation. The key inputs are: (1) Lower CO₂: ice core records (Vostok, EPICA Dome C) show atmospheric CO₂ was ~185–190 ppm at the LGM vs. ~280 ppm pre-industrial — a forcing of approximately −2.8 W/m² relative to pre-industrial. (2) Continental ice sheets: the Laurentide, Fennoscandian, and other ice sheets covered ~30 million km² of land, increasing planetary albedo; PMIP estimates this ice sheet albedo forcing at approximately −3.2 W/m². (3) Other forcing: lower sea level exposed continental shelves (vegetation/albedo changes), dust aerosols were higher (~2× pre-industrial), and methane was lower (~350 ppb vs. ~715 ppb pre-industrial). Total estimated LGM radiative forcing relative to pre-industrial is approximately −7 to −9 W/m² (depending on how dust and vegetation are treated). (4) LGM cooling: multi-proxy synthesis (MARGO, Tierney et al. 2020) gives a global mean surface cooling of ~5.5–7°C. Dividing the cooling by the forcing and scaling to a CO₂ doubling (3.7 W/m²) gives ECS ≈ ΔT / ΔF × 3.7 = ~6°C × 3.7/8 W/m² ≈ 2.8°C. The Bayesian approach of Tierney et al. (2020) yields a 66% range of 2.6–3.9°C, consistent with IPCC AR6. Answer A is completely incorrect about the LGM CO₂ concentration — LGM CO₂ was ~190 ppm, lower than pre-industrial, not doubled; the LGM was cooler, not warmer. Answer B is incorrect on two grounds: northern hemisphere ice sheets did exist at the LGM (that is precisely the boundary condition), and CO₂ concentrations are central to the forcing calculation. Answer D is incorrect — δ¹³C in benthic foraminifera records ocean nutrient cycling and deep-water ventilation, not radiative forcing from greenhouse gases; it cannot be used as described to calculate ECS.',
        },
        {
          q: 'What is a pseudoproxy experiment, and what has it revealed about the accuracy of Common Era temperature reconstructions?',
          a: [
            'A pseudoproxy experiment is a laboratory replication study in which the same tree ring or sediment record is independently measured by two different research groups without sharing data; pseudoproxy experiments have revealed that measurement uncertainty (±0.001 mm in ring width) is the dominant source of error in temperature reconstructions',
            'A pseudoproxy experiment uses output from a climate model simulation as synthetic "truth," creates artificial proxy records by sampling the model temperature field at real proxy locations and adding realistic noise, then tests whether the reconstruction method correctly recovers the known model temperature history; pseudoproxy experiments have revealed that most reconstruction methods underestimate the amplitude of centennial variability by 15–30%, implying that MCA and LIA amplitudes may be systematically underestimated in real reconstructions',
            'A pseudoproxy experiment is a numerical study in which a climate model is run twice — once with realistic proxy-to-temperature calibrations and once with random proxy assignments — to test whether the climate signal is significantly larger than what would be obtained by chance; these experiments have confirmed that the PAGES 2k proxy network contains statistically significant climate information in all 7 regional domains',
            'Pseudoproxy experiments are conducted by deliberately withholding the most recent 30 years of proxy data from the calibration process and testing whether the reconstruction correctly predicts the withheld period; they have revealed that reconstructions are skillful for the last 30 years but completely lose skill for periods older than 500 years due to the diminishing number of proxy records',
          ],
          correct: 1,
          explain: 'Pseudoproxy experiments are a methodological self-assessment tool that addresses a fundamental challenge in paleoclimate reconstruction: we cannot directly evaluate how accurately a reconstruction method performs on actual past climate because the "true" past climate is unknown. Pseudoproxy experiments solve this by using a known quantity — climate model output — as a stand-in for truth. The procedure is: (1) Take a climate model simulation of the past millennium (e.g., CESM1 or MPI-ESM last millennium); (2) Extract the simulated temperature at the geographic locations of real proxy records; (3) Add noise to the synthetic temperatures, calibrated to represent the measurement uncertainty and signal-to-noise ratio documented for each real proxy type (e.g., tree rings have lower noise than poorly preserved lake sediment records); (4) Apply the reconstruction method (CPS, RegEM, PCR) to the synthetic proxy data exactly as it would be applied to real data; (5) Compare the reconstruction output against the known model temperature history. This comparison reveals systematic biases: whether the method correctly recovers the amplitude of warm (MCA) and cold (LIA) periods, whether it underestimates or overestimates trends, and how reconstruction uncertainty scales with the number of contributing records. A consistent finding from pseudoproxy experiments across multiple reconstruction methods and model outputs is that most methods underestimate the amplitude of low-frequency (centennial-scale) variability by approximately 15–35% under realistic noise levels. This is caused by the regression toward the mean inherent in any calibration approach, combined with the finite signal-to-noise ratio of individual proxy records. The implication is important: if real MCA and LIA amplitudes are reconstructed as ~0.2°C and −0.3°C respectively, the true amplitudes may be ~0.25–0.4°C — still substantially below modern warming. Answer A describes an inter-laboratory reproducibility study (a different type of quality control) — pseudoproxy experiments do not involve parallel measurements of the same record. Answer C describes a permutation test for statistical significance of the proxy-climate correlation — a related but distinct methodological test. Answer D incorrectly describes the approach as a prediction-interval verification test (which is actually called "verification" in paleoclimate and does involve withholding data, but is distinct from pseudoproxy experiments in that it tests real proxy data rather than synthetic model output).',
        },
        {
          q: 'The PMIP4 last-millennium simulations show that volcanic forcing is the dominant driver of decadal temperature variability during 850–1850 CE. How does this finding connect to the use of paleoclimate records for constraining future climate projections, and what does it reveal about model performance?',
          a: [
            'The dominance of volcanic forcing in PMIP simulations contradicts proxy reconstructions, which show that solar forcing is the primary driver of the MCA–LIA contrast; this discrepancy suggests that either the PMIP volcanic forcing reconstructions are too strong or that CMIP6 models have an incorrect aerosol optical depth parameterisation for stratospheric volcanoes',
            'If models correctly simulate the cooling response to past volcanic eruptions (as constrained by proxy data), it demonstrates that their treatment of stratospheric aerosol forcing and climate feedbacks is physically realistic; this validates the same climate feedback parameters responsible for the greenhouse gas response, increasing confidence that model-projected warming under future CO₂ scenarios is reliable; proxy reconstructions showing that PMIP models somewhat underestimate multi-decadal internal variability relative to PAGES 2k reconstructions identifies remaining model limitations in internal variability simulation',
            'The primacy of volcanic forcing in PMIP models is only relevant for the pre-industrial period and has no implications for future climate projections, since no volcanic eruptions are expected in the 21st century; the models correctly separate volcanic and greenhouse gas signals, so their future projections are unaffected by how well they simulate past volcanic cooling',
            'The PMIP last-millennium volcanic dominance result proves that the Little Ice Age was entirely caused by volcanism with no contribution from solar variability or internal ocean variability; this means future cooling from volcanic eruptions alone could be large enough to counteract the projected greenhouse gas warming of 2–4°C — making emissions mitigation unnecessary if sufficient volcanic activity occurs',
          ],
          correct: 1,
          explain: `The connection between past volcanic forcing and future climate projections operates through the shared climate physics that governs both. Climate models simulate temperature responses to radiative forcing — whether from volcanic aerosols reducing incoming solar radiation or from greenhouse gases reducing outgoing longwave radiation — through the same set of physical feedbacks: the Planck response, water vapour feedback, lapse rate feedback, surface albedo feedback, and cloud feedbacks. When PMIP models correctly simulate the magnitude and duration of cooling after major volcanic eruptions such as the 1257 Samalas (the largest of the Common Era), the 1815 Tambora, and the 1991 Pinatubo eruption — as constrained by the PAGES 2k proxy network and the instrumental record — this demonstrates that the model\'s treatment of radiative forcing, the climate feedback parameter (λ), and the ocean heat uptake efficiency are collectively calibrated correctly. The same feedback parameter governs the warming response to CO₂ forcing. A model with an incorrect feedback parameter would reproduce the volcanic cooling incorrectly. Conversely, if models are validated against volcanic responses and found to be accurate, this increases confidence in their greenhouse gas warming projections. The additional finding that PMIP models somewhat underestimate the amplitude of multi-decadal internal variability relative to PAGES 2k reconstructions (approximately 20–40% underestimation in most studies) identifies a specific deficiency — likely in the simulation of ocean heat content variability and ocean-atmosphere coupling — that should be investigated and addressed. Answer A incorrectly states that proxy reconstructions show solar forcing is the primary MCA–LIA driver — the current scientific consensus (including PMIP4 assessments) is that volcanic forcing is the dominant driver of decadal temperature variability in the last millennium, with solar forcing as a secondary contributor; the solar contribution to the MCA is estimated at 0.1–0.3 W/m² vs. volcanic forcing exceeding 1–2 W/m² in some decades. Answer C is incorrect — the physical realism test provided by PMIP volcanic responses is directly relevant to greenhouse gas projections through the shared feedback parameter. Answer D draws an incorrect conclusion from PMIP results — identifying volcanic forcing as dominant for last-millennium variability does not imply it could offset multi-degree greenhouse warming; the volcanic forcing from even the largest Holocene eruptions produces cooling of <1°C for <10 years, far less than the committed warming under high-emissions scenarios.`,
        },
      ],
    },
  ],
}

export default multiProxySynthesis
