import { Sun, Shield, AlertTriangle, Globe, TrendingDown } from 'lucide-react'
import { BRAND } from '@/lib/brand'
import type { Lesson } from './types'

const solarGeoengineering: Lesson = {
  id: 'clim-101-1-4-4',
  title: 'Solar Geoengineering: Risks and Governance',
  track: 'cli',
  trackName: 'Climate Science',
  level: 'Beginner',
  duration: '14 min',
  xpReward: 150,
  description: 'Solar geoengineering — deliberately reducing Earth\'s solar radiation to offset warming — is among the most controversial proposals in climate science. It could theoretically lower global temperatures within years at relatively low cost, but carries profound risks of regional climate disruption, geopolitical conflict, and could undermine the drive to cut emissions. This lesson examines the physics, the evidence, and the governance dilemmas.',
  sources: [
    { org: 'IPCC',          title: 'IPCC AR6 WGI — Chapter 4: Future Global Climate; Section 4.6 Solar Radiation Modification (2021)',      url: 'https://www.ipcc.ch/report/ar6/wg1/' },
    { org: 'Nature',        title: 'Robock et al. — 20 Reasons Why Geoengineering May Be a Bad Idea, Bulletin of the Atomic Scientists', url: 'https://www.tandfonline.com/doi/full/10.1080/00963402.2008.11461140' },
    { org: 'Nature',        title: 'Irvine et al. — Halving Warming with Idealized Solar Geoengineering Moderates Key Climate Hazards, Nature Climate Change (2019)', url: 'https://www.nature.com/articles/s41558-019-0398-8' },
    { org: 'Oxford NET Zero', title: 'Oxford Geoengineering Programme — Research and Governance',                                           url: 'https://www.geoengineering.ox.ac.uk/' },
    { org: 'Carbon Brief',  title: 'Carbon Brief — Solar Geoengineering: The Science, Risks and Governance',                               url: 'https://www.carbonbrief.org/solar-geoengineering-what-you-need-to-know/' },
  ],
  sections: [
    {
      type: 'intro',
      title: 'The most dangerous idea in climate science?',
      body: `In 1815, Mount Tambora in Indonesia erupted — the largest volcanic eruption in recorded history. It injected ~60 million tonnes of sulfur dioxide into the stratosphere. In 1816, much of the Northern Hemisphere experienced the "Year Without a Summer": crop failures, famine, and temperature anomalies of -0.5 to -1.5 °C across vast regions. This volcanic "natural experiment" is the closest analogue to what **stratospheric aerosol injection (SAI)** — the most discussed solar geoengineering technique — would deliberately attempt on an ongoing basis.

Solar geoengineering, more formally called **solar radiation modification (SRM)**, refers to a set of proposed interventions that would reduce the amount of solar energy absorbed by Earth, cooling the climate without removing the underlying CO₂ that caused the warming. Unlike carbon dioxide removal, which addresses the root cause of climate change, SRM is a symptom-treatment — it masks warming without reducing atmospheric CO₂ concentrations, meaning ocean acidification would continue and the "termination shock" — rapid rebound warming if SRM were abruptly stopped — would remain a permanent risk as long as elevated CO₂ persists.

The physics is well-established: injecting reflective aerosols into the stratosphere, or brightening marine clouds to reflect more sunlight, would cool Earth. IPCC AR6 assessed with "high confidence" that SRM could reduce global mean surface temperature. The questions that remain fiercely debated are not primarily about whether it could work, but about **who should decide**, **what the regional effects would be**, **whether the governance frameworks necessary for responsible deployment could be built**, and whether the mere existence of a temperature "thermostat" would reduce political pressure to cut emissions — the **moral hazard** problem.

Several factors make solar geoengineering one of the most consequential scientific and ethical frontiers of the coming decades. It could theoretically reduce global warming rapidly (within 1–2 years of deployment), at astonishingly low cost compared to mitigation ($1–10 billion per year for stratospheric aerosol injection at scale — less than some small nations' military budgets). This creates what some call the "free-rider problem": any nation, or even a non-state actor with sufficient resources, could unilaterally deploy SRM, imposing its climate effects on the rest of the world without consent. The governance of a technology that is cheap, technically accessible, and globally consequential has no precedent in international law.`,
      keyTerms: [
        {
          term: 'Solar radiation modification (SRM)',
          def: 'A category of deliberate climate interventions that reduce the amount of solar radiation absorbed by Earth, thereby cooling the climate without addressing atmospheric CO₂ concentrations. Primary proposed methods: (1) stratospheric aerosol injection (SAI) — releasing reflective sulfate or calcium carbonate particles into the stratosphere at ~20 km altitude where they can reflect 1–2 % of incoming solar radiation; (2) marine cloud brightening (MCB) — spraying fine sea salt particles into low marine clouds to increase their droplet number, whitening them and increasing reflectivity; (3) cirrus cloud thinning (CCT) — seeding high ice clouds to reduce their thickness, allowing more longwave radiation to escape to space; (4) space-based reflectors — placing mirrors or dust clouds at the L1 Lagrange point to reduce incoming solar radiation. SRM is distinct from CDR (which removes CO₂ from the atmosphere) and from geoengineering more broadly.',
        },
        {
          term: 'Stratospheric aerosol injection (SAI)',
          def: 'The most technically studied SRM approach, which involves releasing sulfate particles (or potentially calcium carbonate, titanium dioxide, or other materials) into the stratosphere at altitudes of 18–25 km, where they have a residence time of 1–3 years and reflect a portion of incoming solar radiation back to space. The natural analogue is major volcanic eruptions: Pinatubo (1991) cooled global temperatures by approximately 0.5 °C for 2 years. Climate model simulations suggest that injecting ~1–5 Tg of SO₂/yr into the stratosphere could reduce global mean surface temperature by 0.5–2 °C. Potential adverse effects: stratospheric ozone depletion (ozone chemistry is modified on aerosol surfaces), altered precipitation patterns, whitening of the sky, reduced direct solar radiation (affecting solar panels and plant growth), and the termination shock risk.',
        },
        {
          term: 'Termination shock',
          def: 'The rapid rebound warming that would occur if solar geoengineering were abruptly discontinued after sustained deployment while atmospheric CO₂ remained elevated. Because SAI or MCB masks warming without removing the forcing agent (CO₂), all the warming suppressed during the deployment period would be "released" over the following decades if deployment stopped suddenly. The rate of warming following termination could be 2–4× the historical rate — potentially +0.5 to 1.5 °C within a decade — which would be far more disruptive to ecosystems and infrastructure than the gradual warming that geoengineering had been suppressing. Termination shock creates a lock-in dynamic: once SRM is deployed at scale, stopping it becomes extremely dangerous, creating political and technical dependency that persists as long as atmospheric CO₂ remains elevated.',
        },
        {
          term: 'Marine cloud brightening (MCB)',
          def: 'An SRM approach that would spray fine sea salt (or other hygroscopic aerosol) particles into low-altitude marine stratocumulus clouds, increasing the number of cloud condensation nuclei. More, smaller droplets reflect more solar radiation (the Twomey effect). MCB would be deployed regionally — targeting specific ocean regions with persistent low cloud cover — and could in principle be switched on or off within days (unlike SAI which persists for 1–3 years). This regional controllability is both an advantage (more precise targeting) and a governance challenge (any nation or coalition could deploy it over international waters). MCB was proposed as a potential emergency intervention to protect coral reefs during bleaching events. Remaining scientific uncertainties: feedbacks between increased droplet number and cloud lifetime, precipitation effects downwind, and whether marine clouds will respond as models predict.',
        },
        {
          term: 'Moral hazard in geoengineering',
          def: 'The concern that the availability of solar geoengineering as a potential "quick fix" for warming would reduce political and economic pressure to cut greenhouse gas emissions, leading to higher atmospheric CO₂ concentrations and greater long-term risk. If governments and corporations believe that SRM will manage temperatures, they may invest less in the difficult and expensive work of decarbonization. Moral hazard in geoengineering is analogous to fire suppression moral hazard: the knowledge that forest fires will be suppressed may encourage more flammable building in forested areas. Empirical evidence on whether research or discussion of SRM actually reduces mitigation effort is mixed — some studies find increased risk perception upon learning about SRM, others find reduced ambition. The concern is large enough that many climate scientists and ethicists argue that SRM should not be discussed publicly until strong governance frameworks are in place.',
        },
      ],
    },
    {
      type: 'concept',
      title: 'The physics and the evidence: what do models and analogues tell us?',
      body: `**The volcanic analogue.** The best empirical evidence for large-scale SRM effects comes from major volcanic eruptions. Mount Pinatubo (Philippines, June 1991) injected approximately 20 Tg of SO₂ into the stratosphere — the largest volcanic aerosol perturbation since Krakatau (1883). Global mean surface temperature fell by approximately **0.5 °C** in the year following the eruption, recovering over the subsequent 2 years as aerosols settled. This ~0.5 °C cooling is consistent with climate model predictions for the same aerosol loading. Pinatubo also caused regional climate changes: reduced global precipitation (by about 3 %), altered monsoon patterns (reduced Sahel rainfall, weakened Asian monsoon), and temporary ozone depletion. The **Year Without a Summer** (1816, following the 1815 Tambora eruption) demonstrated the agricultural catastrophe that large-scale stratospheric cooling can cause: widespread crop failures across Europe, North America, and Asia, contributing to the worst famine of the 19th century. These analogues confirm that stratospheric aerosol injection would cool the climate — but they also reveal the significant risks of precipitation disruption.

**Climate model results: promise and trade-offs.** IPCC AR6 assessed with "high confidence" that stratospheric aerosol injection would be effective in reducing global mean temperature, but noted that it would also alter precipitation and atmospheric circulation patterns, and would not restore the pre-industrial climate even if it successfully reduced global mean temperature. The fundamental problem is that CO₂-induced warming and SRM-induced cooling have **different spatial patterns**: CO₂ warms polar regions more than the tropics (polar amplification); SRM reduces solar radiation more at the tropics than the poles (because more solar radiation arrives at low latitudes). Superimposing SAI cooling on CO₂ warming cannot produce the pre-industrial climate pattern — some regions would be over-cooled and others under-cooled. An influential 2019 Nature Climate Change study (Irvine et al.) modelled "half-measure" SAI — applying only enough SAI to halve global warming rather than fully offsetting it — and found that this approach could reduce climate risks (fewer people exposed to extreme heat, less sea level rise) compared to full warming, with fewer regional disruptions than full SAI. This suggests that modest partial geoengineering might represent a lower-risk option than either full geoengineering or no geoengineering at all — but the governance and moral hazard challenges remain.

**Marine cloud brightening: regional and reversible.** MCB is often discussed as a more controllable alternative to SAI because: its effects are regional (targeting specific ocean areas) rather than global; it is reversible within days (unlike SAI which persists for 1–3 years after release); it does not deplete stratospheric ozone; and it could potentially be deployed as an emergency intervention to protect specific ecosystems (such as the Great Barrier Reef during bleaching events). The University of Washington's Marine Cloud Brightening Project and other research groups have been conducting small-scale field experiments. However, MCB faces deep scientific uncertainty: whether marine cloud droplet number can be reliably increased by salt spraying at regional scales, whether increased droplets extend cloud lifetime or reduce it (conflicting effects), and what precipitation effects would be experienced downwind of brightened cloud regions. A 2024 experiment in California (run by the Coastal Atmospheric Aerosol Research and Engagement program) generated significant public controversy and was subsequently paused, illustrating the governance sensitivities even at research scales.`,
      cards: [
        {
          name: 'Stratospheric Aerosol Injection: Physics and Effects',
          icon: Sun,
          color: BRAND.gold,
          desc: 'SAI injects reflective particles (SO₂ → sulfate aerosols; or CaCO₃) into stratosphere at 18–25 km altitude. Residence time: 1–3 years. Natural analogue: Pinatubo 1991 (20 Tg SO₂ → ~0.5 °C global cooling for 2 years). Modelled SAI for 1–2 °C cooling: ~1–5 Tg SO₂/yr. Costs: $1–10B/yr at scale (IEA estimate) — tiny vs. mitigation costs but reflects symptom treatment, not cure. Known adverse effects: stratospheric ozone depletion (30–100 % increase in ozone loss chemistry on aerosol surfaces at high loadings); sky whitening; reduced direct solar radiation (affects solar PV and plant photosynthesis); weakened monsoons and reduced global precipitation. Termination shock: abrupt stop at elevated CO₂ → 2–4× normal warming rate.',
          examples: 'Pinatubo 1991: 0.5 °C cooling; 3 % global precipitation reduction; reduced Asian and African monsoon rainfall. Year Without a Summer 1816 (Tambora 1815): harvest failures in Ireland, Switzerland, China, New England; famine mortality 100,000+. SCoPEx (Harvard, Keith & Dykema): small-scale stratospheric particle experiment; cancelled after objections from Sámi Council (indigenous reindeer herders) citing lack of consent for atmospheric experiments affecting their territory. IPCC AR6: high confidence SAI would reduce global mean T; high confidence it would not restore pre-industrial regional climate patterns.',
        },
        {
          name: 'Marine Cloud Brightening: Regional and Reversible',
          icon: TrendingDown,
          color: BRAND.accent,
          desc: 'MCB sprays fine sea salt particles into marine stratocumulus clouds → more cloud condensation nuclei → smaller, more numerous droplets → higher cloud albedo (Twomey effect). Typical regional cooling: 0.5–2 °C over treated areas. Advantages over SAI: reversible within days; regional (targeted, not global); no stratospheric ozone impact. Uncertainties: cloud lifetime feedbacks (more droplets may suppress or enhance precipitation, changing cloud lifetime unpredictably); downwind precipitation effects; whether effect is stable across seasons and conditions. Proposed emergency use: cooling Great Barrier Reef during bleaching events by brightening nearby clouds. Governance challenge: can be deployed from ships in international waters by any actor — lower barrier to unilateral action than SAI.',
          examples: 'University of Washington MCB Project: research fleet for Pacific trials; early results show measurable cloud brightening in small-scale tests. CAARE experiment (California coast, 2024): cloud-seeding from decommissioned aircraft carrier USS Hornet; paused after public protest and regulatory scrutiny. Oxford Martin Programme on Modelling and Predicting Climate: models suggest MCB could reduce coral bleaching risk by 50 % in moderate scenarios. GeoMIP (Geoengineering Model Intercomparison Project): coordinated model experiments across 20+ climate models; shows MCB cools tropics but has complex precipitation effects.',
        },
        {
          name: 'The Termination Shock and Moral Hazard',
          icon: AlertTriangle,
          color: BRAND.ruby,
          desc: 'Termination shock: if SAI deployed at scale then suddenly stopped while CO₂ elevated, suppressed warming "rebounds" at 2–4× historical rate — potentially +0.5–1.5 °C per decade. This rate far exceeds ecosystem and infrastructure adaptation capacity. Creates lock-in: once started, stopping becomes existential risk — political/economic dependency analogous to drug dependency. Moral hazard: does awareness of geoengineering reduce mitigation ambition? Evidence mixed but concern is significant among scientists and policymakers. "Slippery slope" concern: research → small-scale tests → larger tests → deployment, with each step normalising the next. Carbon Brief analysis: even at current (2024) CO₂ rates, termination shock from stopping a 1 °C SAI programme within 10 years would cause ~0.5 °C warming over 5 years — faster than sea walls can be built or crops adapted.',
          examples: 'Jones et al. (2013, Journal of Geophysical Research): modelled termination of 8 Tg SO₂/yr SAI; global mean warming of +0.9 °C in 10 years after termination — far faster than any adaptation scenario. IPCC SR1.5 (2018): flagged SAI termination risk as a critical knowledge gap. US National Academies (2021): Reflecting Sunlight report recommends research on termination risks as a priority. Analogy: Once a large levee system is built, the protected area develops more densely — making the consequences of levee failure more catastrophic; SAI creates the same escalating dependency.',
        },
      ],
    },
    {
      type: 'concept',
      title: 'Governance, ethics, and the geopolitics of the sky',
      body: `**The governance vacuum.** No international legal framework currently governs solar geoengineering research or deployment. The 1976 ENMOD Convention (Environmental Modification Convention) prohibits "hostile" environmental modification but does not address peaceful climate interventions. The London Protocol (governing ocean dumping) was amended in 2013 to cover some forms of ocean fertilisation, but does not address atmospheric interventions. The UN Environment Assembly has discussed SRM governance but has not reached agreement on any framework. This legal vacuum creates the dangerous "free-rider" dynamic: any sufficiently wealthy actor — a nation, a coalition, or potentially a private entity — could deploy SAI unilaterally, imposing its climate effects on the global commons without consent.

The geopolitical challenge is profound. Different regions would experience different climate outcomes from any particular SAI deployment. Simulations consistently show that SAI would reduce monsoon precipitation in some regions (particularly the Sahel, Indian subcontinent, and parts of Central America) while over-cooling others. Whose climate preferences should govern? High-income nations that could afford deployment, low-income nations most vulnerable to climate change, or some global average? There is no democratic mechanism for the "climate thermostat" decision, and the divergent interests of nations — China and India concerned about monsoon disruption, Pacific islands desperate for temperature reduction, Arctic nations fearing the loss of strategic advantage from ice-free passages — create deep disagreement about even the research agenda.

**Research governance: the outdoor experiment problem.** Unlike laboratory science, atmospheric SRM research eventually requires outdoor experiments that affect shared global commons. Small-scale experiments — like the Harvard SCoPEx project or the California MCB trials — confront the question of whether outdoor atmospheric modification, even at research scale, requires international consent or at minimum broad social licence. The cancellation of SCoPEx (after objections from the Sámi Council) and the controversy around the 2024 California MCB experiment illustrate that even research-stage activities face governance challenges that have no clear resolution. The US National Academies (2021) "Reflecting Sunlight" report recommended a structured research programme with strong governance, transparency, and public engagement — but acknowledged that the international governance framework needed to do this responsibly does not yet exist.

**The justice dimension.** Solar geoengineering concentrates decision-making power in the hands of technically capable, wealthy actors while distributing climate effects across the entire global population. Climate justice advocates argue that SRM offers wealthy nations a technological bypass around the obligation to cut their emissions — an obligation that flows from historic and ongoing responsibility for climate change. Indigenous communities (like the Sámi in the Arctic) are particularly concerned about the lack of free, prior, and informed consent for atmospheric experiments that could affect their territories and traditional practices. Climate justice organisations have argued that SRM should not be developed or deployed without mechanisms ensuring meaningful participation and consent from frontline and fenceline communities most affected by both climate change and its proposed technological responses.`,
      cards: [
        {
          name: 'The Governance Gap: Who Decides the Thermostat?',
          icon: Globe,
          color: BRAND.jade,
          desc: 'No international legal framework governs SRM research or deployment. ENMOD (1976): prohibits hostile environmental modification — not applicable to climate interventions. London Protocol: covers ocean fertilisation but not atmospheric modification. UN Environment Assembly (UNEA-5, 2022): Swiss proposal for independent expert panel on SRM governance — blocked, primarily by oil-producing states. Key governance challenge: SAI deployment cost (~$1–10B/yr) accessible to ~50+ nations; any could act unilaterally. "Free-rider" and "rogue actor" risks are genuine. Competing interests: temperature benefits global; precipitation effects regional and unequal. Sahel nations: monsoon risk. Pacific Islands: desperately want cooling. Arctic nations: interest in navigable Arctic passages. No democratic thermostat mechanism exists in international law.',
          examples: 'Sámi Council opposition to SCoPEx (2021): "experiments in the sky over our traditional territories without our consent violate our rights as indigenous peoples." Mexico banned solar geoengineering experiments (2023) after unauthorised MCB trial by Make Sunsets startup — first national ban. Make Sunsets controversy: private US startup launched sulfur-filled weather balloons in Mexico without permits; sold "cooling credits"; illustrated that private actors can already conduct low-level SAI. Carnegie Climate Governance Initiative (C2G): intergovernmental dialogue on SRM governance; no binding framework as of 2024.',
        },
        {
          name: 'Climate Justice and the SRM Dilemma',
          icon: Shield,
          color: BRAND.amethyst,
          desc: 'Justice concerns with SRM: (1) Decision-making power: technically capable wealthy nations control deployment decisions affecting all nations; (2) Benefits and burdens: temperature reduction benefits are global, precipitation disruption is regional and may fall on vulnerable nations; (3) Indigenous and frontline communities: no free, prior, informed consent mechanisms; (4) Moral hazard at global level: low-income nations benefit least from SRM "escape valve" but face largest mitigation burden pressure; (5) Intergenerational justice: locking in termination shock risk for future generations. Counter-argument: most vulnerable nations (Pacific islands, Bangladesh) may benefit most from temperature reduction even at cost of some precipitation disruption — they are not monolithic in opposition. Climate justice is not synonymous with SRM opposition; some justice advocates see it as the only near-term option for the most vulnerable.',
          examples: 'African Group of Nations (UN climate negotiations): divided on SRM — some favour exploring it for temperature benefits; others oppose due to precipitation and governance concerns. Alliance of Small Island States (AOSIS): formally called for more SRM research while emphasising need for governance and emissions reductions. Bangladesh Adaptation and Mitigation Strategies for Bangladesh project: modelling SRM effects on Bangladesh monsoon — found mixed results. Civil Society Institute for Global Governance: 70 NGOs signed letter (2023) opposing development of SAI as a climate response, citing justice and governance concerns.',
        },
      ],
    },
    {
      type: 'visualization',
      title: 'The SRM decision space: from research to deployment',
      body: `Solar geoengineering decisions involve a complex interplay between scientific understanding, governance capacity, ethical frameworks, and geopolitical interests. The flow below maps the key decision nodes — from early research through to potential deployment — highlighting where governance gaps exist, what could go wrong, and what would need to be in place for SRM to be governed responsibly.`,
      interaction: {
        type: 'flow-simulator' as const,
        description: 'Solar geoengineering governance pathway from basic research through outdoor experiments, international governance, and conditional deployment or termination',
        nodes: [
          {
            id: 'basic-research',
            label: 'Basic Research and Modelling',
            description: 'Climate model simulations and laboratory studies of SRM physics are the foundation of SRM science. The Geoengineering Model Intercomparison Project (GeoMIP) coordinates climate model experiments across 20+ global models to characterise the climate response to different SRM scenarios. This research is conducted entirely using computers and laboratory equipment and raises no governance issues specific to SRM. Key results from modelling: SAI can reduce global mean temperature; it alters precipitation patterns differently from CO₂ forcing; it would not restore the pre-industrial climate even while cooling it; and termination shock is a real risk. Basic research is broadly supported across the scientific community and is already well-funded in the US, UK, Europe, and China. This stage generates the knowledge needed to assess whether more invasive research is justified.',
            color: BRAND.accent,
          },
          {
            id: 'outdoor-experiments',
            label: 'Outdoor Experiments (Contested Governance)',
            description: 'Beyond computer modelling, understanding SRM requires field experiments that release particles into the real atmosphere or spray aerosols onto real ocean clouds. This is where governance challenges become acute. Even small-scale outdoor experiments modify shared atmospheric or ocean commons without universal consent. The Harvard SCoPEx experiment — planning to release a small calcium carbonate plume from a balloon at 20 km altitude — was cancelled after objections from the Sámi Council and other Indigenous representatives. The 2024 California MCB experiment on the USS Hornet faced public protest and regulatory scrutiny. Key governance questions: who must consent to outdoor experiments? How should the scientific community self-govern? What level of atmospheric modification crosses from acceptable to requiring international oversight? The US National Academies recommended an outdoor research programme with governance, transparency, and public engagement — but noted the governance framework does not yet exist.',
            color: BRAND.gold,
          },
          {
            id: 'governance-development',
            label: 'International Governance Development',
            description: 'Before any significant SRM deployment, most scientists and ethicists argue that an international governance framework must be established. Such a framework would need to address: decision-making authority (which body authorises deployment? UN Security Council? UNEA? New Treaty?); consent mechanisms (must all nations consent, or a qualified majority? How are indigenous and frontline community rights protected?); monitoring and transparency (who monitors atmospheric composition, regional climate effects, and compliance?); liability and compensation (who pays if SRM causes drought in a third country?); the "rogue actor" problem (how are unilateral deployments by non-signatories prevented?); and research governance (international oversight of outdoor experiments). As of 2024, no such framework exists, and the UNEA-5 proposal for even an expert assessment panel was blocked. This governance gap is arguably the most critical obstacle to responsible SRM governance.',
            color: BRAND.jade,
          },
          {
            id: 'deployment-decision',
            label: 'Conditional Deployment Decision',
            description: 'A legitimate deployment decision would require: (1) compelling scientific evidence that benefits outweigh risks in the specific deployment scenario considered; (2) a credible international governance framework with broad participation and consent; (3) evidence that moral hazard risks are manageable — that SRM deployment would not meaningfully reduce mitigation ambition; (4) robust termination risk management — including the requirement that deployment only occurs alongside aggressive emissions reductions to reduce the CO₂ stock driving termination shock risk; (5) explicit equity provisions ensuring vulnerable nations and communities have meaningful input and protection. Some researchers argue these conditions are unachievable and that the bar for deployment should be correspondingly high. The "half-measure" approach (Irvine et al., 2019) — using modest SAI to halve rather than fully offset warming — may reduce some risks while maintaining mitigation pressure, but raises the same governance questions.',
            color: BRAND.coral,
          },
          {
            id: 'ongoing-monitoring',
            label: 'Ongoing Monitoring and Governance',
            description: 'If SRM were ever deployed, continuous monitoring of its climate effects would be essential: stratospheric aerosol optical depth measurements; satellite tracking of regional precipitation changes; agricultural impact monitoring; ozone column measurements; and social and economic impact assessment in regions most affected. The governance system would need to be capable of adjusting, scaling, or terminating deployment as new evidence emerged — while managing the termination shock risk through coordinated gradual phase-down rather than abrupt stop. An analogy with pharmaceutical regulation is instructive: drugs are approved after rigorous trials, monitored post-approval for unexpected side effects, and can be withdrawn — but SRM side effects are global and some (ozone depletion, regional drought) may be irreversible. The multi-decade commitment required creates institutional challenges: governance systems must remain functional across elections, crises, and geopolitical shifts.',
            color: BRAND.amethyst,
          },
          {
            id: 'rejection-pathways',
            label: 'Rejection or Moratorium',
            description: 'Many scientists, ethicists, and governments argue that the governance challenges and risks of SRM are so severe that the technology should never be developed or deployed, and that research should be limited to computer modelling to avoid the "slippery slope" from experiments to deployment. Proposed moratoriums on outdoor experiments (similar to the 1990s nuclear test ban logic) have been discussed in the academic literature and by some civil society organisations. In 2023, Mexico issued a national ban on solar geoengineering experiments following the unauthorized Make Sunsets deployment. Arguments for moratorium or rejection: the governance framework cannot be built in time to prevent rogue deployment; the moral hazard risk is too severe; the justice issues are unresolvable; and mitigation + adaptation + CDR are sufficient responses without SRM. Counter-arguments: these other tools may be insufficient to prevent catastrophic warming this century, and banning research increases the risk of desperate unilateral deployment.',
            color: BRAND.ruby,
          },
        ],
        edges: [
          { from: 'basic-research',        to: 'outdoor-experiments',    label: 'models identify knowledge gaps that only field experiments can fill' },
          { from: 'outdoor-experiments',   to: 'governance-development', label: 'field experiment controversies drive urgency of governance development' },
          { from: 'governance-development', to: 'deployment-decision',   label: 'credible governance framework is precondition for legitimate deployment' },
          { from: 'deployment-decision',   to: 'ongoing-monitoring',     label: 'conditional deployment triggers mandatory monitoring programme' },
          { from: 'ongoing-monitoring',    to: 'deployment-decision',    label: 'evidence from monitoring informs adjustment or continuation of deployment' },
          { from: 'outdoor-experiments',   to: 'rejection-pathways',     label: 'experiment controversies may trigger moratorium or rejection of SRM' },
          { from: 'governance-development', to: 'rejection-pathways',    label: 'failure to build adequate governance leads to moratorium or ban' },
        ],
      },
    },
    {
      type: 'quiz',
      questions: [
        {
          q: 'Stratospheric aerosol injection (SAI) could reduce global mean surface temperature within 1–2 years at a cost of $1–10 billion per year. Why do many climate scientists argue this should not be deployed even if it successfully cools the planet?',
          a: [
            'SAI is too expensive to be practical; $10 billion per year exceeds the GDP of most countries and would be unaffordable; the true cost including monitoring and administration would be in the trillions; the IEA estimate of $1–10B/yr is unrealistically optimistic',
            'SAI does not address elevated CO₂ and therefore does not reduce ocean acidification or the risk of termination shock; regional climate effects (altered monsoons, reduced precipitation in vulnerable regions, stratospheric ozone depletion) would fall unequally on different populations; the moral hazard could reduce the political will to cut emissions; and no legitimate international governance framework exists to make the deployment decision — raising profound ethical and geopolitical problems that persist regardless of the temperature benefit',
            'SAI would work too well: by cooling the planet below pre-industrial temperatures, it would trigger a new ice age with devastating consequences for global agriculture; the risk of over-cooling is greater than the risk of under-cooling',
            'SAI is fundamentally different from the volcanic analogue because volcanic aerosols are naturally occurring while SAI particles are synthetic; synthetic aerosols would not reflect sunlight and would instead trap heat like greenhouse gases, making SAI completely ineffective',
          ],
          correct: 1,
          explain: 'A is factually wrong: $1–10 billion per year is well within the fiscal capacity of many nations (the US alone spends ~$800B on defence annually); the NAS (2021) estimate for a full SAI programme is in this range, and it has been independently estimated at comparable levels; the cost is not the primary objection. C is wrong: models and volcanic analogues consistently show that SAI would cool the climate, not over-cool it to ice-age temperatures; the sulfate loadings required for 1–2 °C cooling are far below those of major mass-extinction-associated eruptions; models show temperature stabilisation, not runaway cooling. D is factually incorrect: both volcanic sulfate aerosols and synthetic sulfate aerosols reflect shortwave radiation by the same physical mechanism (scattering); the chemical composition is identical (SO₄²⁻); IPCC AR6 confirms with high confidence that SAI would reduce global mean temperature. B correctly summarises the multi-dimensional objections: CO₂ remains elevated (ocean acidification continues; termination shock persists); regional precipitation effects are unequal and potentially devastating for monsoon-dependent populations; ozone chemistry is disrupted; moral hazard may reduce mitigation urgency; and the governance challenge — how humanity makes a collective decision about the planetary thermostat — has no precedent or solution in international law.',
        },
        {
          q: 'The "termination shock" is a specific risk of solar geoengineering. What is it, and why does it create a dependency problem that cannot be easily resolved even if SRM successfully reduces temperatures?',
          a: [
            'Termination shock refers to the economic shock caused when SAI deployment ends and renewable energy investors lose the subsidy that geoengineering programmes provided; it is primarily a financial risk that can be managed through investor compensation schemes',
            'Termination shock is the rapid warming rebound that would occur if SAI were abruptly discontinued while atmospheric CO₂ remained elevated: the warming suppressed during the SRM deployment period would be "released" over subsequent years at 2–4× the historical warming rate; this creates a dependency because the only safe way to stop SAI (without triggering termination shock) is to first reduce atmospheric CO₂ through aggressive emissions cuts and CDR — but if SRM deployment reduces the political pressure to do this, the conditions for safe termination may never be met',
            'Termination shock occurs when SAI aerosols accumulate in the stratosphere over many years and suddenly reflect so much sunlight that global temperatures crash to below-preindustrial levels; this is prevented by switching SAI deployment on and off in regular cycles',
            'Termination shock is a theoretical risk that has never been observed in volcanic analogues; since no volcanic eruption has ever caused temperature rebound after the eruption ended, termination shock from SAI is also unlikely to occur in practice',
          ],
          correct: 1,
          explain: 'A conflates financial economic shocks with climate termination shock — they are unrelated; SAI does not provide subsidies to renewable energy investors, and "termination shock" is a specific technical term in climate science referring to the temperature rebound effect. C incorrectly describes the mechanism: SAI aerosols settle out of the stratosphere within 1–3 years and do not permanently accumulate; the scenario described (aerosols "accumulating" and "suddenly" reflecting huge amounts) is not physically accurate; SAI can be gradually ramped up or down over years without oscillation. D misreads the volcanic analogue: after volcanic eruptions end, temperatures do return to their pre-eruption trajectory relatively quickly — this is exactly the termination shock mechanism in miniature; the difference with SAI is timescale: Pinatubo ended in months and the rebound was gradual; SAI deployed for decades and then stopped would force the same rebound but compressing decades of suppressed warming into years. B correctly describes the dependency mechanism: CO₂ remains in the atmosphere for centuries after emissions; as long as CO₂ is elevated, stopping SAI causes the suppressed warming to emerge rapidly; the only permanent exit from this dependency is aggressive emissions reductions and CDR that actually lower atmospheric CO₂ — but the very availability of SAI as a temperature management tool may reduce the political urgency of doing so, creating a circular trap.',
        },
        {
          q: 'Different nations have very different interests regarding solar geoengineering. Small island developing states facing existential sea level rise, Sahel nations dependent on monsoon rainfall, and Arctic nations with geopolitical interests in ice-free shipping lanes all have distinct and potentially conflicting interests. What fundamental challenge does this diversity of interests create for SRM governance?',
          a: [
            'Different national interests are a manageable problem because the UN Security Council can simply vote on any SRM deployment proposal; the five permanent members (US, UK, France, China, Russia) can make the decision on behalf of all nations; countries that disagree can be overruled by majority vote as in other international governance matters',
            'The diversity of interests creates a fundamental governance challenge because any particular SRM deployment scenario would produce "winners" and "losers" in terms of regional climate effects — different precipitation patterns, different temperature changes — and no international institution currently has the legitimate authority, inclusive decision-making process, or enforcement capacity to make this choice on behalf of all humanity; this challenge is qualitatively different from other international governance problems because the effects are truly global, the costs of unilateral action are low (making it hard to exclude actors), and the consequences of wrongly calibrated deployment or termination are potentially catastrophic and irreversible',
            'The governance challenge is easily solved by agreeing that each nation controls the SRM over its own territory: countries that want cooling can deploy SAI over their territory; countries that do not can simply request exclusion from the spraying pattern; this territorial approach makes international governance straightforward',
            'Different national interests are irrelevant to SRM governance because climate models show that SAI benefits are uniformly positive for all nations; all countries experience reduced extreme heat, fewer droughts, and lower sea level rise; the apparent disagreement between nations is based on misinformation rather than genuine differing interests',
          ],
          correct: 1,
          explain: 'A is wrong about the UN Security Council: the UNSC operates by veto (P5 nations can block any resolution), so consensus among the five permanent members is required, not a simple majority; more fundamentally, the UNSC was designed for peace and security decisions, not global environmental governance; its structure is widely considered illegitimate for making planetary-scale decisions on behalf of all humanity; and the nations most vulnerable to climate change (Pacific islands, Bangladesh, African nations) are not permanent members. C is physically impossible: stratospheric aerosols disperse globally within weeks and cannot be controlled to affect only specific territories; SAI over "one country\'s territory" would affect global atmospheric circulation and precipitation within months; there is no territorial boundary for atmospheric chemistry. D is factually incorrect: climate models consistently show differential regional effects from SAI — some regions receive less precipitation (Sahel, monsoon regions in some scenarios), some face different temperature changes; the differential effects are not a matter of misinformation but of well-documented physics; the Robock et al. (2009) "20 reasons why geoengineering may be a bad idea" explicitly catalogues documented differential regional effects from volcanic analogues and model simulations. B correctly identifies the structural governance challenge: the combination of (1) genuinely different regional climate outcomes; (2) no existing legitimate institution with authority to make the decision; (3) low cost enabling unilateral action; and (4) potentially catastrophic irreversible consequences creates a governance problem with no precedent in international law.',
        },
        {
          q: 'Solar geoengineering research is sometimes criticised on the grounds that even discussing it creates a "moral hazard" — reducing political pressure to cut emissions. What does the empirical evidence show about this concern, and how should it affect decisions about SRM research?',
          a: [
            'Empirical studies universally show that learning about SRM dramatically reduces people\'s support for emissions reductions by more than 50 %; the moral hazard is so large and consistent that all SRM research should be immediately stopped to preserve mitigation ambition',
            'The empirical evidence on SRM moral hazard is mixed: some social science studies find that learning about SRM slightly reduces stated willingness to support climate policy; others find no effect or even increased concern about climate risk upon learning about SRM; the moral hazard concern is real and cannot be dismissed, but the evidence does not support a claim of inevitable or catastrophically large effects; this suggests that SRM governance should include deliberate strategies to prevent moral hazard (explicit framing that SRM is a supplement to, not substitute for, mitigation) rather than treating moral hazard as a definitive argument against any research',
            'Moral hazard from SRM research is impossible because rational actors will always understand that SRM does not reduce CO₂ or ocean acidification; any emissions reductions made unnecessary by SRM would simply be offset by increased CO₂ uptake by natural sinks; therefore SRM cannot affect mitigation ambition',
            'The moral hazard concern applies only to public discussion of SRM, not to classified government research; if SRM is studied only in secret by national security agencies without public disclosure, the moral hazard problem is completely eliminated while the scientific benefits are preserved',
          ],
          correct: 1,
          explain: 'A overstates the evidence: while some experimental studies do find reduced climate policy support after SRM information is presented, the effect sizes are generally modest (not "50 % reductions") and are inconsistent across studies, populations, and framing conditions; the empirical literature does not support a conclusion of universal or catastrophically large moral hazard. C is wrong: rational actor models have limited applicability to political systems where decision-making is influenced by framing, interest groups, and policy windows; even if individuals "rationally" understand that SRM doesn\'t reduce CO₂, political actors (governments, corporations) might use the availability of SRM as justification for delayed action — this is the operationally relevant moral hazard, not individual rationality. D is ethically untenable and practically counterproductive: governance of SRM requires public deliberation and democratic input; secret government research would undermine the consent and legitimacy requirements that most governance frameworks emphasise; it would also likely be leaked, causing uncontrolled public debate without the careful framing needed to manage moral hazard. B correctly represents the state of empirical knowledge: moral hazard from SRM is a real and legitimate concern supported by some evidence, but the evidence is mixed enough that it should not by itself end all research; the appropriate response is to design research governance, framing, and communication strategies that explicitly counter moral hazard — making clear that SRM, if ever used, would be a supplement to, not a substitute for, deep and rapid emissions reductions.',
        },
        {
          q: 'In 2019, Irvine et al. (Nature Climate Change) modelled "half-measure" SAI — applying only enough stratospheric aerosol injection to halve global warming rather than fully offsetting it. They found this approach could reduce the number of people exposed to extreme heat and sea level rise compared to unmitigated warming. Does this finding resolve the governance and justice concerns about SAI?',
          a: [
            'Yes, the Irvine et al. findings resolve most concerns: since half-measure SAI produces better outcomes than no SRM for all populations globally, all nations would rationally support it; the governance challenge disappears because universal support makes consent straightforward; only a small scientific communication effort is needed to gain global buy-in',
            'No: while half-measure SAI may reduce aggregate climate risk compared to full warming, it does not resolve the fundamental governance challenges: the deployment decision still requires an authority that does not exist; some regions would still experience differential precipitation effects; termination shock risk persists (though reduced compared to full SAI); moral hazard remains; and the half-measure framing itself could normalise SRM as a response, making more aggressive deployment more politically likely over time; the Irvine et al. result is scientifically useful for understanding the risk landscape but is not a governance solution',
            'Half-measure SAI eliminates all governance concerns because it reduces risk without fully offsetting warming, meaning there is no "winner" or "loser" among nations — all experience some warming reduction from the SAI and some residual warming from CO₂; the equal distribution of both benefits and residual warming eliminates differential effects and makes consent universal',
            'The Irvine et al. study is scientifically flawed because it uses climate models that cannot simulate monsoon changes accurately; half-measure SAI would actually cause extreme monsoon disruption in India and Africa that the models missed; the real-world effect would be the opposite of what was modelled',
          ],
          correct: 1,
          explain: 'A is wrong: "half-measure" SAI still produces differential regional effects — while the Irvine et al. study found reduced aggregate risk, it also found some regions faring worse with half-measure SAI than without it; the claim of universal benefit is not supported by the paper\'s results; and rational support does not automatically follow even from universally positive outcomes in international relations where trust, power dynamics, and procedural justice all matter. C incorrectly claims that half-measure SAI eliminates differential effects: the Irvine et al. study itself documents that some regions still experience different outcomes under partial SAI than under no SAI; differential effects exist even under half-measure scenarios, just with different magnitudes and distributions than under full SAI. D mischaracterises the model performance: GeoMIP and other coordinated model experiments have specifically evaluated monsoon responses to SAI, and models do capture monsoon dynamics; while there are uncertainties, the claim that all models miss extreme monsoon disruption is not supported by the literature; some individual studies do project significant monsoon effects, but characterising all models as flawed in this way overstates the uncertainty. B correctly recognises that a favourable risk-reduction result from climate models, while scientifically valuable, does not dissolve the governance challenges: no international authority exists to authorise deployment; differential regional effects persist even at half-measure levels; termination shock risk remains as long as CO₂ is elevated; and normalisation of SRM through a "half-measure" framing could make the pathway to larger-scale deployment more likely, not less. The Irvine et al. result is one important data point in the risk-benefit analysis, but it does not substitute for the governance and ethical work required before deployment could be considered legitimate.',
        },
      ],
    },
  ],
}

export default solarGeoengineering
