import { Thermometer, Globe, Wind } from 'lucide-react'
import { BRAND } from '@/lib/brand'
import type { Lesson } from './types'

const climateSystemOverview: Lesson = {
  id: 'clim-101-1-1-1',
  title: 'The Climate System: Components and Interactions',
  track: 'cli',
  trackName: 'Climate Science',
  level: 'Beginner',
  duration: '11 min',
  xpReward: 140,
  description: "Earth's climate is not simply 'the weather' — it is a complex, coupled system of five interacting components: the atmosphere, hydrosphere, cryosphere, biosphere, and lithosphere. Understanding how energy flows between these components, what drives their natural variability, and how human activity perturbs the system is the foundation of climate science.",
  sources: [
    { org: 'NOAA',     title: 'NOAA Climate — The Climate System Components',                        url: 'https://www.climate.gov/teaching/essential-principles-climate-literacy/climate-system' },
    { org: 'NASA',     title: `NASA Global Climate Change — Earth\'s Energy Budget`,                 url: 'https://climate.nasa.gov/vital-signs/energy-budget/' },
    { org: 'OpenStax', title: `Environmental Science — Earth\'s Climate System (CC-BY 4.0)`,         url: 'https://openstax.org/books/environmental-science-ap' },
    { org: 'NOAA',     title: 'NOAA Earth System Research Lab — Climate Feedbacks',                 url: 'https://www.esrl.noaa.gov' },
    { org: 'AGI',      title: 'Glossary of Geology — Climate System and Climate Variability',       url: 'https://www.americangeosciences.org/' },
  ],
  sections: [
    {
      type: 'intro',
      title: 'More than weather',
      body: `In 1824, Joseph Fourier calculated that Earth should be far colder than it is — and realised the atmosphere must be acting like an insulating blanket. By 1896, Svante Arrhenius had computed how much warmer Earth would get if CO₂ doubled. The science of climate began not in the 21st century, but 200 years ago.\n\n**Climate** is the long-term statistical behaviour of the atmosphere and ocean system — the average weather, its variability, and the probability of extremes at a given location and time of year. **Weather** is the specific state of the atmosphere at a given moment (today's temperature, wind, and precipitation); climate is the distribution of all possible weather states over decades (the 30-year climatological normals used by meteorologists). Climate is not simply 'average weather' — it includes variance, extremes, and temporal patterns (seasonality, interannual variability, long-term trends) that cannot be captured by means alone.

Earth's climate system consists of **five coupled components** that exchange energy, water, and matter: (1) the **atmosphere** — the gaseous envelope, the most rapidly responding component, with variability on timescales of days to years; (2) the **hydrosphere** — liquid water in the ocean, lakes, and rivers; the ocean dominates, storing ~93% of Earth's surface heat and modulating climate on timescales of decades to millennia; (3) the **cryosphere** — all frozen water (sea ice, ice sheets, glaciers, permafrost, snow cover); changes in ice extent alter albedo, sea level, and ocean circulation on timescales of years to millions of years; (4) the **biosphere** — all living organisms, which modulate atmospheric CO₂, surface albedo (vegetation), and the water cycle through evapotranspiration; (5) the **lithosphere** — the solid Earth; relevant to climate through volcanic CO₂ degassing, weathering reactions that remove CO₂, and plate tectonics that repositions continents over millions of years. These five components interact through fluxes of energy and mass, forming a coupled system that exhibits internal variability (natural oscillations and chaotic dynamics) as well as responses to external forcing.

Energy from the Sun drives the climate system. The solar constant (the flux of solar radiation at Earth's mean orbital distance) is approximately 1,361 W m⁻², reduced to an effective average insolation of ~340 W m⁻² when averaged over Earth's spherical surface (dividing by 4 for geometry). Of this incoming solar radiation, approximately 30% is reflected back to space (the planetary albedo), leaving ~238 W m⁻² absorbed by the surface and atmosphere. The system is in approximate radiative equilibrium: the absorbed solar radiation is balanced by outgoing longwave (infrared) radiation to space. The greenhouse effect, surface albedo, and atmospheric circulation all modulate how this energy budget is distributed spatially and temporally.`,
      keyTerms: [
        { term: 'Climate system', def: "The coupled system of five major components — atmosphere, hydrosphere, cryosphere, biosphere, and lithosphere — that together determine Earth's climate. Each component has different response timescales (atmosphere: days–years; ocean surface: weeks–years; deep ocean: centuries–millennia; ice sheets: millennia–millions of years; lithosphere: millions–hundreds of millions of years). The climate system exchanges energy, water, and matter between components through fluxes and feedbacks." },
        { term: 'Climate forcing', def: 'An external perturbation to Earth\'s energy budget that causes the climate system to depart from its previous equilibrium state. Positive forcings add energy to the system (warming); negative forcings remove energy (cooling). Examples: changes in solar output, volcanic aerosol injection (negative, temporary), changes in greenhouse gas concentrations (positive, persistent), changes in Earth\'s orbital parameters (Milankovitch cycles). Measured in W m⁻² globally averaged. Distinguished from internal variability, which arises from within the climate system without an external trigger.' },
        { term: 'Climate feedback', def: 'A process in the climate system that amplifies (positive feedback) or dampens (negative feedback) the initial response to a forcing. The Planck (blackbody) feedback is the primary negative feedback: as the surface warms, it radiates more energy to space (Stefan-Boltzmann law), restoring equilibrium. Positive feedbacks include ice-albedo feedback (warming melts ice → lower albedo → more warming) and water vapour feedback (warming → more atmospheric H₂O → enhanced greenhouse → more warming). The net feedback determines climate sensitivity.' },
        { term: 'Climate sensitivity', def: 'The equilibrium global mean surface temperature increase expected from a doubling of atmospheric CO₂ concentration (abbreviated ECS — Equilibrium Climate Sensitivity). The IPCC Sixth Assessment Report (2021) assessed ECS as "likely" (66% probability) to be in the range 2.5–4.0°C and "very likely" (90%) in the range 2.0–5.0°C, with a best estimate of 3°C. Climate sensitivity integrates all climate feedbacks and is the key parameter linking greenhouse gas emissions to future warming.' },
        { term: 'Internal climate variability', def: 'Natural, unforced fluctuations in the climate system arising from the chaotic dynamics of the coupled atmosphere-ocean system, including: ENSO (El Niño-Southern Oscillation) — 3–7 year Pacific oscillation dominating interannual global temperature variability; PDO (Pacific Decadal Oscillation) — 20–30 year mode; AMO (Atlantic Multidecadal Oscillation) — 60–80 year mode. Internal variability can temporarily mask or amplify forced climate trends on timescales of years to decades, complicating the attribution of observed climate change to specific causes.' },
      ],
      interaction: {
        type: 'scientific-diagram' as const,
        id: 'earth-energy-budget',
        caption: "Earth's global mean energy budget. Of 340 W/m² incoming solar radiation, 30% is reflected (planetary albedo), 23% is absorbed by the atmosphere, and 48% by the surface. The greenhouse effect (back-radiation of 333 W/m²) raises the surface temperature ~33°C above what it would be without an atmosphere.",
        credit: 'Trenberth, Fasullo & Kiehl (2009) / NASA CERES EBAF',
      },
    },
    {
      type: 'callout' as const,
      variant: 'data',
      headline: 'Antarctic ice: enough to drown every coastal city',
      body: 'Antarctic ice sheets contain 26.5 million km³ of ice — enough, if melted, to raise global sea levels by approximately 58 metres and inundate every coastal city on Earth.',
    },
    {
      type: 'concept',
      title: 'Energy budget, components, feedbacks, and timescales',
      body: `**The global energy budget.** Earth's climate is fundamentally a heat engine driven by solar energy. Think of the climate system like a bathtub: the Sun fills it with energy, and outgoing infrared radiation is the drain. When you add a thicker blanket of greenhouse gases, you partially block the drain — the tub fills higher (warms) until the drain rate catches up to the fill rate at a new, warmer equilibrium. The current energy imbalance of +0.87 W m⁻² means the tub is still filling. The planet absorbs ~238 W m⁻² of shortwave solar radiation and emits approximately the same amount of longwave infrared radiation to space (when in equilibrium). The current measured **energy imbalance** — about +0.87 W m⁻² — indicates that Earth is absorbing more energy than it emits: this imbalance is the physical signature of anthropogenic climate change. Ocean heat content measurements are the most reliable way to detect this imbalance because the ocean absorbs ~93% of the excess energy; the global ocean has been warming at all depths (including the deep ocean below 2,000 m) since at least the 1950s. Energy flows within the climate system are as important as the top-of-atmosphere budget: solar radiation is absorbed primarily at the surface (especially the tropical ocean) and transported to higher latitudes and altitudes by the atmospheric general circulation (Hadley, Ferrel, and Polar cells) and ocean circulation (thermohaline circulation, wind-driven gyres).

**Ocean heat capacity and climate inertia.** The ocean's enormous heat capacity — water absorbs ~4 times more heat per gram per degree than rock, and the ocean is ~3.7 km deep on average — means that the ocean introduces massive **thermal inertia** into the climate system. Even if all greenhouse gas emissions stopped today, Earth would continue warming for decades because the current energy imbalance would persist until the ocean heated enough to re-establish radiative equilibrium. This "committed warming" (sometimes called "warming in the pipeline") is estimated at approximately 0.3–0.5°C above current temperatures, assuming immediate cessation of all anthropogenic forcing — meaning that some future warming is already locked in by past emissions regardless of what actions are taken now. The ocean also transports heat poleward through thermohaline circulation, strongly influencing the climate of high-latitude regions; shutdown of this circulation (as potentially triggered by freshwater injection from melting ice sheets) would dramatically alter regional climate in Northern Europe and eastern North America.

**Cryosphere feedbacks and ice-albedo mechanism.** The cryosphere — ice in all its forms — interacts with the climate system through the powerful **ice-albedo feedback**. Fresh snow has an albedo of 0.8–0.9 (80–90% of incoming sunlight reflected); open ocean has an albedo of only 0.06 (6% reflected). When Arctic sea ice melts due to warming, the dark ocean surface is exposed, absorbing more solar radiation and amplifying the initial warming. This feedback is primarily responsible for **polar amplification** — the observation that the Arctic has warmed approximately 3–4 times faster than the global average since 1979. The Arctic sea ice extent has declined by ~40% in summer since 1979; summer Arctic sea ice extent has declined faster than virtually all climate model projections made in the 1990s and 2000s. The West Antarctic Ice Sheet and parts of the Greenland Ice Sheet may be past tipping points beyond which their eventual disintegration — and the 5–12 metres of sea level rise they represent — is already committed.

**Biosphere-climate interactions.** The biosphere modulates climate through carbon cycling (photosynthesis removes CO₂; respiration and decomposition release it), surface albedo (forests are darker and warb than bare ground or crops; tropical forests generate their own rainfall through evapotranspiration), and atmospheric chemistry (vegetation emits volatile organic compounds that affect aerosol formation). The global carbon cycle involves rapid exchanges between the atmosphere and the land/ocean biosphere (with gross fluxes of ~120 GtC/year through photosynthesis alone), a slower ocean inorganic chemistry exchange (~90 GtC/year), and the very slow geological carbon cycle (weathering and volcanism, ~0.1 GtC/year). Human activities have disrupted the fast biological cycle (by burning fossil carbon that was sequestered over millions of years) and the land biosphere (through deforestation, which releases stored carbon and reduces carbon uptake capacity). Currently, about half of human CO₂ emissions are absorbed by the land biosphere and ocean — but this natural uptake capacity is expected to weaken as climate change progresses.`,
      cards: [
        {
          name: 'The Five Climate System Components',
          icon: Globe,
          color: BRAND.coral,
          desc: 'Atmosphere: fastest response (days–years); weather and climate variability; exchanges heat with ocean. Hydrosphere: ocean dominates, stores 93% of surface heat, 0.06 albedo open water; thermohaline circulation transports heat poleward; response timescales decades–millennia. Cryosphere: sea ice (albedo 0.5–0.7), ice sheets (albedo 0.8), glaciers, permafrost (stores 2× atmosphere carbon); sea level; response years–millions of years. Biosphere: carbon cycle modulation, albedo, evapotranspiration, aerosol chemistry. Lithosphere: volcanic CO₂, silicate weathering CO₂ drawdown; timescales millions–hundreds of millions of years.',
          examples: 'Ocean heat uptake: Argo float network (3,900+ profiling floats globally) confirmed +0.87 W/m² imbalance and documented deep-ocean warming below 2,000 m · Arctic sea ice: September 2012 record minimum of 3.41 million km², 40% below 1979–2000 average · Permafrost: Siberian thermokarst lakes releasing CH₄ visible from satellite; Yedoma permafrost stores 400–500 GtC in ice-rich loess',
        },
        {
          name: 'Energy Budget and Climate Feedbacks',
          icon: Thermometer,
          color: BRAND.gold,
          desc: 'Solar constant: 1,361 W/m². Effective insolation: 340 W/m² (÷4 for geometry). Planetary albedo: 0.30 → 100 W/m² reflected. Absorbed: ~240 W/m². Current imbalance: +0.87 W/m² (net warming). Planck feedback: primary negative — more warming → more LW emission to space. Water vapour feedback: positive — most powerful amplifier; doubles CO₂ warming. Ice-albedo: positive — ice loss → lower albedo → more warming. Cloud feedbacks: uncertain sign, largest uncertainty in climate sensitivity. Lapse rate feedback: negative (tropics), positive (polar). Net feedback = climate sensitivity; IPCC best estimate ECS = 3°C.',
          examples: `ECS 3°C: doubling CO₂ from 280→560 ppm causes 3°C equilibrium warming · Water vapour: amplifies CO₂ alone by ~2× · Polar amplification: Arctic warming ~4× global mean since 1979 · Earth\'s energy imbalance (EEI): measured by CERES satellite and Argo floats`,
        },
        {
          name: 'Internal Variability: ENSO and Decadal Modes',
          icon: Wind,
          color: BRAND.amethyst,
          desc: 'ENSO: 3–7 yr Pacific oscillation. El Niño: warm eastern Pacific → global +0.1–0.2°C anomaly. La Niña: cool → global -0.1°C. Dominates interannual climate variability. PDO (Pacific Decadal Oscillation): 20–30 yr mode; warm phase amplifies El Niño signature. AMO (Atlantic Multidecadal Oscillation): 60–80 yr mode; warm AMO phase increases Atlantic hurricane activity, drought in Sahel. NAO (North Atlantic Oscillation): determines winter climate of Europe. Internal variability can mask forced trends for 1–2 decades ("hiatus" periods). Attribution requires statistical separation of forced trend from internal variability.',
          examples: '1997–98 El Niño: strongest on record at the time; global temperature +0.2°C anomaly; drought in SE Asia, floods in Peru · 2015–16 El Niño: strongest recorded; contributed to record 2016 global temperature · 2020–22 triple La Niña: temporarily offset global mean temperature while anthropogenic warming continued',
        },
      ],
      interaction: {
        type: 'annotated-image' as const,
        src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Antarctic_iceberg.jpg/1200px-Antarctic_iceberg.jpg',
        alt: 'An Antarctic iceberg showing the exposed surface ice above the waterline and the vast submerged mass below the ocean surface',
        aspectRatio: '16/9',
        credit: 'National Science Foundation / Wikimedia Commons',
        annotations: [
          {
            id: 'ice-surface',
            x: 50,
            y: 30,
            label: 'Ice surface above water',
            description: 'Only about 10% of an iceberg\'s total volume is visible above the waterline. This exposed surface reflects most incoming solar radiation (albedo ~0.8), contributing to the cryosphere\'s role in Earth\'s energy budget.',
          },
          {
            id: 'submerged-mass',
            x: 50,
            y: 65,
            label: 'Submerged ice mass',
            description: 'Approximately 90% of the iceberg lies below the ocean surface, where it exchanges cold freshwater with the surrounding seawater as it melts. This freshwater input can reduce surface salinity and potentially affect thermohaline circulation.',
          },
          {
            id: 'meltwater-zone',
            x: 30,
            y: 45,
            label: 'Meltwater zone',
            description: 'The active melting interface at the waterline, where relatively warm ocean water contacts the ice. Melt rates are accelerating as ocean temperatures rise — the Amundsen Sea sector of West Antarctica is losing ice mass at an accelerating rate.',
          },
          {
            id: 'ocean-surface',
            x: 20,
            y: 38,
            label: 'Ocean surface',
            description: 'The boundary between the cryosphere and hydrosphere. Open ocean has an albedo of only 0.06, absorbing 94% of incident solar radiation — contrasting sharply with the high-albedo ice surface above. Ice loss exposes dark ocean, amplifying warming through the ice-albedo feedback.',
          },
          {
            id: 'blue-ice',
            x: 70,
            y: 55,
            label: 'Blue ice interior',
            description: 'The distinctive blue colour of deep glacial ice results from the absorption of red wavelengths by dense, bubble-free ice. Air bubbles trapped during snow compaction are squeezed out as ice deepens — ancient ice cores preserve 800,000 years of atmospheric composition in this form.',
          },
        ],
      },
    },
    {
      type: 'concept',
      title: 'Key takeaways',
      body: `• **The five coupled components**: The climate system is not just the atmosphere — the ocean, cryosphere, biosphere, and lithosphere each shape climate on timescales from days to millions of years, exchanging energy and matter through feedbacks that can amplify or dampen any initial perturbation.\n\n• **Earth's current energy imbalance**: The planet is absorbing ~0.87 W m⁻² more energy than it emits — the direct physical signature of human-caused warming. The ocean takes up ~93 % of this excess heat, making ocean heat content the most reliable indicator of the imbalance.\n\n• **Feedbacks determine climate sensitivity**: Small orbital or greenhouse-gas changes get amplified — or dampened — by feedbacks such as water vapour (strongest positive) and ice-albedo; together they set the equilibrium climate sensitivity at ~3 °C per CO₂ doubling, meaning the system's response is far larger than the raw forcing alone.`,
    },
    {
      type: 'quiz',
      questions: [
        {
          q: "Earth's global mean energy imbalance is currently approximately +0.87 W m⁻². This means Earth is absorbing ~0.87 W m⁻² more solar radiation than it emits as longwave radiation to space. What does this energy imbalance physically represent, and why is it a more precise indicator of human-caused climate change than global mean surface temperature alone?",
          a: [
            "The +0.87 W m⁻² imbalance represents the additional heating from greenhouse gases, but it is not more precise than surface temperature as an indicator — surface temperature is directly measured at thousands of land and ocean stations globally with a record extending back 150 years, while the energy imbalance is only estimated from satellites that have been measuring since 2002 and have large calibration uncertainties of ±4 W m⁻²; temperature is always more reliable as a climate indicator than derived radiation budget estimates",
            "The energy imbalance represents the net rate of heat accumulation in the Earth system (primarily the ocean); it directly measures the current thermodynamic state of the climate system — how much faster it is gaining energy than losing it — independently of how that energy is distributed between the ocean, atmosphere, cryosphere, and land; surface temperature can fluctuate by 0.1–0.2°C on interannual timescales due to ENSO and other internal variability without any change in forcing; the energy imbalance, integrated over the full ocean depth, is more tightly coupled to the underlying forced trend and less affected by short-term atmospheric variability",
            "The energy imbalance is larger during El Niño years because more solar radiation reaches the surface when Pacific Ocean clouds clear; the variation in energy imbalance on interannual timescales reflects primarily ENSO-driven changes in cloud cover rather than greenhouse forcing; the average of +0.87 W m⁻² includes years with +1.5 W m⁻² (El Niño) and +0.2 W m⁻² (La Niña), so the mean is not a reliable indicator of anthropogenic forcing",
            "The +0.87 W m⁻² imbalance indicates that Earth is emitting 0.87 W m⁻² more longwave radiation than it absorbs solar radiation — this is the signature of a cooling planet losing heat faster than it gains it; a positive energy imbalance means net cooling because positive longwave emission exceeds solar input",
          ],
          correct: 1,
          explain: "CERES satellite calibration uncertainty is approximately ±0.3 W m⁻² (not ±4 W m⁻²); and the energy imbalance is independently confirmed by Argo float measurements of ocean heat content (with different systematic errors), making the combination of satellite and in-situ measurements highly reliable; moreover, surface temperature does have the longer record but is subject to more short-term variability (A incorrectly characterises the measurement uncertainty and incorrectly dismisses the value of energy imbalance measurements). ENSO does affect energy imbalance (La Niña slightly increases it because cooler Pacific surface emits less LW and allows more heat to enter the ocean; El Niño slightly reduces it) but the described relationship in C is backwards and ENSO modulation is much smaller than the background +0.87 W m⁻² forced trend; ENSO is not the dominant driver of the energy imbalance. D has the sign convention completely backwards — a positive energy imbalance means more energy is coming IN than going OUT, which means net warming, not cooling. The correct answer is B: Earth's energy imbalance (EEI) is the most fundamental metric of the climate system's current state. When EEI is positive, Earth's total heat content is increasing — the planet is out of equilibrium and will continue warming until the imbalance is restored. The value of EEI over surface temperature is: (1) it integrates over the entire climate system (ocean, land, cryosphere) rather than just the thin layer of atmosphere in contact with the surface; (2) 93% of excess energy goes into the ocean, which has much lower variance than the atmosphere — making EEI less noisy; (3) it directly quantifies the forcing-response relationship without depending on how energy is partitioned between surface temperature and ocean heat content (which varies with ENSO); (4) it is the direct physical quantity that must reach zero for warming to stop. The +0.87 W m⁻² current imbalance means Earth is accumulating energy at the rate of ~440 TW — comparable to ~10,000 Hiroshima bombs of heat energy per day.",
        },
        {
          q: 'Water vapour is the most abundant greenhouse gas in the atmosphere, yet climate scientists do not list it as the primary driver of modern anthropogenic warming. What is the correct relationship between water vapour and CO₂ in the climate system, and why is this distinction scientifically important?',
          a: [
            'Water vapour is not actually a greenhouse gas — it is transparent to infrared radiation; only CO₂, methane, and nitrous oxide trap heat; the water cycle affects climate only through cloud formation and the latent heat released during condensation, not through direct infrared absorption',
            'Water vapour and CO₂ are independent greenhouse gases that each contribute equally to the greenhouse effect; scientists focus on CO₂ for policy purposes because it is easier to regulate, but water vapour is equally controllable if society chose to reduce atmospheric humidity through large-scale atmospheric drying technologies',
            'Water vapour is a powerful greenhouse gas but is a feedback rather than a forcing: its atmospheric concentration is controlled by temperature through the Clausius-Clapeyron relationship — warmer air holds more water vapour; human activities do not directly control water vapour concentrations at the global scale; CO₂ is the primary anthropogenic forcing because humans directly control its atmospheric abundance through fossil fuel combustion; CO₂ warming raises temperatures, which then increases water vapour (a positive feedback that approximately doubles the warming from CO₂ alone)',
            'Water vapour dominates the greenhouse effect so completely (~50% of total greenhouse warming) that changes in CO₂ are climatically irrelevant; even tripling CO₂ would add less than 0.1°C of warming because CO₂ absorption bands are already saturated and any additional CO₂ cannot absorb significantly more infrared radiation',
          ],
          correct: 2,
          explain: 'Water vapour is indeed a potent greenhouse gas, absorbing infrared radiation strongly across a wide spectrum — it contributes roughly 50% of the clear-sky greenhouse effect (A is factually wrong to claim it is not a greenhouse gas). Water vapour and CO₂ are not independent and equal drivers of current warming; water vapour concentration at the global scale is not an independently controllable quantity because evaporation from the ocean surface saturates the atmosphere relative to temperature; no feasible technology could globally dry the troposphere (B mischaracterises the controllability of water vapour). CO₂ absorption bands are not fully saturated — adding more CO₂ continues to absorb radiation in the wings of the absorption bands, especially in the 15 µm band; each doubling of CO₂ provides a forcing of approximately 3.7 W m⁻², as confirmed by both theoretical calculation and satellite observations; the claim in D that CO₂ changes are climatically irrelevant due to saturation is one of the oldest and most thoroughly refuted misconceptions in climate science. The correct answer is C: the distinction between forcing and feedback is central to understanding climate change. A forcing is an externally imposed perturbation to the energy budget; a feedback is a response of the climate system that amplifies or damps the initial forcing. Water vapour is a feedback because its concentration is set by the temperature of the air — at any given temperature, the atmosphere holds a relatively fixed amount of water vapour (governed by the Clausius-Clapeyron equation). Humans cannot significantly alter global atmospheric water vapour directly; it adjusts passively to temperature. CO₂, by contrast, is a non-condensing greenhouse gas whose atmospheric concentration is controlled by sources and sinks independent of temperature in the short run — making it an externally imposed forcing when humans burn fossil fuels. When CO₂ warms the planet slightly, the warmer atmosphere holds more water vapour, which provides additional greenhouse forcing, amplifying the initial warming by approximately a factor of 1.5–2. This water vapour feedback is the reason climate sensitivity (~3°C per CO₂ doubling) is much larger than the direct CO₂ forcing alone (~1.2°C) would produce.',
        },
        {
          q: "The Arctic has warmed approximately 3–4 times faster than the global average since 1979 — a phenomenon called 'polar amplification.' What combination of physical mechanisms explains why high-latitude warming is so much greater than tropical warming in response to the same global forcing?",
          a: [
            "Polar amplification is primarily caused by the direct effect of ozone depletion over the Arctic — the thinning stratospheric ozone layer allows more UV radiation to reach the Arctic surface, causing additional warming that is not experienced at lower latitudes where the ozone layer is thicker; without stratospheric ozone depletion, Arctic warming would be similar to tropical warming in percentage terms",
            "Polar amplification reflects the lower heat capacity of polar regions — the Arctic Ocean is covered by ice for most of the year, and ice has a much lower heat capacity than water; therefore the same energy input warms polar regions more than tropical oceans; this is a purely physical effect of the different heat capacities of ice versus water",
            "Multiple reinforcing mechanisms drive polar amplification: (1) ice-albedo feedback — melting of high-albedo ice and snow exposes low-albedo ocean/land, absorbing more solar radiation and amplifying warming preferentially at high latitudes; (2) lapse rate feedback — tropical warming is distributed vertically throughout a deep troposphere (reducing surface warming), while polar warming is concentrated near the surface (a shallow, stable boundary layer); (3) poleward energy transport — a warmer atmosphere exports more heat to the poles; (4) sea ice loss eliminates the 'buffer' of latent heat that previously absorbed energy during seasonal melting without raising temperature",
            "Polar amplification is caused by industrial pollution concentrated in the Arctic — black carbon (soot) from coal burning in Russia, China, and North America is transported poleward and deposited on Arctic snow and ice, lowering albedo; this soot effect, not greenhouse warming, explains why Arctic warming is faster than the tropics; cleaning up soot emissions would eliminate polar amplification",
          ],
          correct: 2,
          explain: "Antarctic ozone depletion does cause stratospheric cooling in the Southern Hemisphere, but this is not the primary driver of Arctic surface warming; Arctic ozone depletion is relatively modest and has not been identified as a major driver of Arctic amplification; UV radiation at the surface is not a primary driver of surface temperature change (A is incorrect). While ice does have lower specific heat capacity than water, this is not the primary explanation for polar amplification — if it were, the Arctic would warm faster than the tropics at any season, not specifically in the season of ice loss; moreover, the ocean under the ice has the same heat capacity whether it is ice-covered or not, and the ice loss is the cause, not the mechanism (B confuses cause and effect). Black carbon does contribute to Arctic warming (perhaps 0.2–0.4°C of Arctic warming from soot deposition) but is not the primary driver; the dominant mechanisms are greenhouse-driven; moreover, atmospheric measurements do not support soot as the dominant forcing at the magnitude needed to explain 3–4× polar amplification (D overstates soot's role and dismisses greenhouse gas forcing incorrectly). The correct answer is C: polar amplification arises from multiple reinforcing mechanisms that all operate preferentially at high latitudes: The ice-albedo feedback is the most important single mechanism — the Arctic Ocean's loss of sea ice in summer exposes a surface with albedo of ~0.06 (vs. ~0.7 for sea ice), dramatically increasing absorbed solar radiation locally. The lapse rate feedback operates differently at different latitudes: in the tropics, moist convection distributes warming throughout a deep troposphere, reducing the rate of surface warming but increasing high-altitude warming; at the poles, the atmosphere is stable and warming is trapped near the surface, producing larger surface temperature increases for the same energy input. Together with ocean heat transport and the elimination of sea ice as a latent heat buffer, these mechanisms produce the observed 3–4× amplification.",
        },
        {
          q: "The 2015–2016 El Niño event was associated with record-breaking global surface temperatures. Critics of climate change argued that the high 2016 temperature was 'just El Niño, not global warming.' Climate scientists responded that El Niño cannot explain the observed warming. What is the correct statistical framework for separating internal variability (ENSO) from the forced trend in the global temperature record?",
          a: [
            "Climate scientists are correct that El Niño cannot explain any of the warming — ENSO is a zero-sum oscillation that produces equal amounts of warming (El Niño years) and cooling (La Niña years) over time; the global average temperature contribution of ENSO integrated over decades is exactly zero; therefore all warming in the multi-decadal record must be attributed to forcing rather than ENSO",
            "Critics are correct that El Niño explains 2016's record temperature — 2016 was the hottest year on record specifically because of the 2015–16 El Niño; without El Niño, 2016 would have been roughly average within recent decades; the multi-decadal warming trend is real but individual record years (2016, 2023) are primarily attributable to El Niño events rather than the forced trend",
            "The correct approach uses statistical regression to partition observed temperature variability into: (1) the forced long-term trend (from greenhouse gases, aerosols, solar variability, and volcanic forcing), estimated using climate model ensembles or physical trend models; and (2) the internal variability component, estimated from ENSO indices and other climate modes; when ENSO and other internal modes are regressed out of the temperature record, the remaining forced trend is smooth, positive, and statistically robust; the 2016 El Niño elevated temperature ~0.1–0.15°C above the forced trend, but the forced trend itself was ~0.2°C higher in 2016 than in 2000 — internal variability modulates the trend but does not create it",
            "The debate is unresolvable — because internal variability and forced trends overlap in the observational record with no way to separate them statistically; the only reliable method would be a controlled experiment in which Earth's greenhouse gas concentrations could be randomly varied, which is impossible; therefore neither the warming trend nor the ENSO contribution can be quantified separately",
          ],
          correct: 2,
          explain: "ENSO is not exactly zero-sum on any given multidecadal period — in practice, El Niño and La Niña events have slightly different amplitudes and frequencies in different climate states, and there can be net contributions to temperature trends; however, A is approximately correct that ENSO averages near zero over climate-relevant timescales; the statement that 'all warming must be attributed to forcing' is too strong, as the phasing of ENSO can create apparent trends over shorter periods (A is partially correct but overstates certainty). The 2016 record high temperature was indeed boosted by El Niño, but the underlying forced trend had also risen substantially — had the same El Niño occurred in 2000, the global temperature would not have broken 2016's record because the baseline was lower; the characterisation in B that individual record years are 'primarily attributable' to ENSO rather than the forced trend is incorrect — the forced trend was ~0.2°C higher in 2016 than in 2000, while El Niño contributed ~0.1–0.15°C above the 2016 trend; the forced trend was the larger factor. The claim that internal variability and forced trends are inseparable (D) is factually incorrect — the statistical methods described in C are standard practice in attribution science and produce robust, peer-reviewed results; the argument in D is a mischaracterisation of the scientific challenge. The correct answer is C: the statistical separation of forced trends from internal variability is a well-developed area of climate science using multiple methodologies: (1) ENSO regression — fitting the ENSO index (e.g., Niño3.4 SST) to observed temperature and removing the ENSO-correlated component leaves the ENSO-adjusted temperature record; (2) multiple linear regression — fitting greenhouse forcing, volcanic aerosols, solar variability, and internal modes simultaneously; (3) ensemble averaging — running many climate model simulations with the same forcing but different initial conditions; the forced trend emerges from the ensemble mean while internal variability averages out. All methods produce consistent results: the forced warming trend in the global mean surface temperature record is approximately 0.18–0.20°C per decade since 1980, and individual El Niño events add ~0.1–0.15°C above the trend while La Niña events subtract similar amounts. The 2016 record was a combination of both.",
        },
      ],
    },
  ],
}

export default climateSystemOverview
