import { Mountain, Layers, Waves } from 'lucide-react'
import { BRAND } from '@/lib/brand'
import type { Lesson } from './types'

const glacialCoastalLandforms: Lesson = {
  id: 'geol-101-1-5-4',
  title: 'Glacial and Coastal Landforms',
  track: 'geo',
  trackName: 'Geology',
  level: 'Beginner',
  duration: '13 min',
  xpReward: 150,
  description: "20,000 years ago, ice sheets covered 30% of Earth's land and sea level was 120 m lower. Today, waves attack every coastline 24 hours a day. Ice and ocean are Earth's final two great sculptors — and their work is written across every high-latitude landscape and every continental margin.",
  sources: [
    { org: 'USGS',    title: 'Glaciers and Ice Sheets (Public Domain)',          url: 'https://www.usgs.gov/programs/climate-research-and-development/glaciers-ice-sheets' },
    { org: 'USGS',    title: 'Coastal and Marine Geology',                       url: 'https://www.usgs.gov/centers/whcmsc' },
    { org: 'NPS',     title: 'Geology Fieldnotes — Glacial Geology',             url: 'https://www.nps.gov/subjects/geology/glacial-landforms.htm' },
    { org: 'NPS',     title: 'Geology Fieldnotes — Coastal Geology',             url: 'https://www.nps.gov/subjects/geology/coastal-landforms.htm' },
    { org: 'OpenStax', title: 'Physical Geology, 2nd ed. (CC-BY 4.0)',           url: 'https://openstax.org/books/physical-geology-2e' },
    { org: 'UCAR Center for Science Education', title: 'Earth surface processes', url: 'https://scied.ucar.edu/learning-zone/earth' },
  ],
  sections: [
    {
      type: 'intro',
      title: 'Ice and ocean: the last great sculptors',
      body: `During the Last Glacial Maximum approximately 20,000 years ago, ice sheets covered roughly 30% of Earth's land surface — blanketing all of Canada, northern Europe, and much of northern Asia under kilometres of ice. Global sea level stood approximately 120 metres lower than today: the English Channel was dry land, Siberia and Alaska were connected by the Bering land bridge, and the shallow continental shelves now submerged beneath the North Sea were inhabited by woolly mammoths, horses, and the humans who hunted them. When you walk across the Scottish Highlands, the lake district of Finland, the fjords of Norway, or the polished granite domes of Yosemite Valley, you are reading the geological record of that vanished ice — carved, polished, and deposited by glaciers during a climate fundamentally different from the Holocene world in which human civilisation developed.

Ice sculpts landscapes at continental scales. A valley glacier flowing downhill carries an embedded cargo of rock debris that abrades and plucks the underlying bedrock with mechanical efficiency no river can match — transforming V-shaped river valleys into the characteristic U-shape of glacial troughs, carving armchair-shaped cirques at mountain headwaters, and depositing vast quantities of unsorted debris as moraines when the ice finally melts. Continental ice sheets erase entire pre-glacial landscapes under kilometres of ice, then leave behind drumlins, eskers, and kettle lakes as the ice retreats.

At every ocean margin, waves bring a different set of tools. Hydraulic action, abrasion, and dissolution act continuously along coastlines — cutting sea cliffs, carving arches and stacks from headlands, and redistributing sediment along shore via longshore drift to build beaches, spits, and barrier islands. Sea-level change — driven by the same glacial cycles that build and destroy ice sheets — controls whether coastlines are advancing inland or retreating, whether river mouths are drowned as estuaries or exposed as coastal plains. This lesson completes Chapter 5 and with it, the full landscape toolkit: volcanic construction (Lesson 1), weathering and erosion (Lesson 2), rivers (Lesson 3), and now the final sculptors — ice and sea.`,
      keyTerms: [
        {
          term: 'Glacier',
          def: 'A mass of ice that originates on land from the accumulation, compaction, and recrystallisation of snow, and that flows under its own weight. Glaciers require that more snow accumulates in winter than melts in summer. Alpine (valley) glaciers flow down mountain valleys; continental ice sheets (Antarctica, Greenland) cover entire landscapes to depths of 3–4 km.',
        },
        {
          term: 'Glacial erosion',
          def: 'Rock removal by moving ice through two mechanisms: abrasion (rock fragments embedded in the base of the glacier grind against bedrock, producing scratches called striae and smoothed, polished surfaces) and plucking/quarrying (meltwater penetrates cracks in bedrock, refreezes, and the moving ice tears blocks free, producing the jagged lee faces characteristic of glacially eroded bedrock).',
        },
        {
          term: 'Moraine',
          def: 'A ridge or mound of unsorted, unstratified glacial till (rock debris deposited directly from melting ice). Terminal moraines mark the farthest advance of a glacier; lateral moraines form along the edges of valley glaciers; medial moraines form when two glaciers merge and their lateral moraines join in the centre.',
        },
        {
          term: 'Fjord',
          def: 'A long, narrow, deep inlet of the sea occupying a glacially eroded U-shaped valley that was subsequently flooded by rising sea level during deglaciation. Fjords are characterised by very steep walls, great depth (often exceeding 1,000 m), and a shallow sill at the mouth where the glacier once entered the sea and lost erosive power. Classic fjord coastlines: Norway, New Zealand, Chile, British Columbia, Alaska.',
        },
        {
          term: 'Longshore drift',
          def: "The net transport of sediment along a coastline by wave action. Waves approaching the shore at an angle push sediment obliquely up the beach face (swash); gravity pulls it straight back down (backwash); the net result is a zigzag transport of sediment in the direction of wave approach. Longshore drift is the primary mechanism building beaches, spits, and barrier islands.",
        },
        {
          term: 'Barrier island',
          def: "A long, low-lying sand island running parallel to the mainland coast, separated from it by a shallow lagoon. Barrier islands are built and maintained by longshore drift and wave action, and are common along low-gradient coastlines with abundant sand supply (US Atlantic and Gulf coasts). They are highly dynamic and vulnerable to sea-level rise and storm overwash.",
        },
      ],
    },
    {
      type: 'concept',
      title: 'How ice and waves reshape the land',
      body: `**Glaciers as erosional machines.** Ice is not inherently hard — pure ice at 0 °C is softer than many minerals — but a glacier's erosive power comes not from the ice itself but from the rock it carries. The base of a moving glacier is laden with fragments of all sizes, from fine rock flour to boulders, embedded in the ice as it incorporates debris from the valley floor and walls. This debris acts as an abrasive tool: as the glacier flows, rock fragments grind against the bedrock beneath, producing **striae** (parallel scratches on bedrock surfaces), polishing bedrock to a mirror finish, and wearing away the rock at rates that rivers cannot match. The second mechanism, **plucking** (or quarrying), is equally important: meltwater generated by the pressure of overlying ice seeps into cracks in the bedrock, refreezes, and expands; the moving glacier then pulls these ice-locked blocks free from the bedrock floor, producing the jagged, rough surfaces on the downstream (lee) side of glacially sculpted bedrock knobs.

**Alpine glacial landforms.** Valley glaciers carve a recognisable suite of erosional features. At the head of each glacier, in the zone of maximum snow accumulation and ice formation, the glacier erodes a **cirque** — a steep-walled, armchair-shaped hollow with a flat or gently sloping floor and a sharp headwall. Cirques form by frost action and plucking at the glacier's headwall, and by abrasion at the cirque floor. Where two cirques erode toward each other from opposite sides of a ridge, the intervening rock is reduced to a sharp knife-edged ridge called an **arête**. Where three or more cirques converge, the remaining central peak is carved into a distinctive pyramidal shape called a **horn** — the Matterhorn in the Swiss-Italian Alps is the most famous example, but horns are common in all glaciated mountain ranges. The main valley glacier transforms the pre-existing river valley from its V-shaped cross-section into a **U-shaped glacial trough**: the glacier, unlike a river, erodes laterally as well as vertically, widening and deepening the valley into the characteristic parabolic U. Yosemite Valley in California is a textbook glacial trough — 1,100 m deep and nearly flat-floored, with vertical walls that plunge directly to the valley floor. Where a smaller tributary glacier joined the main glacier at a higher elevation, the tributary valley was left hanging above the main trough when the ice melted, creating a **hanging valley** from which waterfalls plunge to the main valley floor. Yosemite's Bridalveil Fall drops 189 m from a hanging valley into Yosemite Valley. **Fjords** are the most dramatic expression of glacial erosion at the coast: where a glacial trough reaches the sea, the glacier can erode well below sea level (glaciers are dense enough to erode hundreds of metres below the waterline), producing troughs that plunge 1,000 m or more below sea level; when the ice retreats and sea level rises during deglaciation, seawater floods the trough and creates the long, deep, fjord — Norway's Sognefjord is 204 km long and 1,308 m deep.

**Continental glaciation and depositional landforms.** Continental ice sheets — the Laurentide Ice Sheet over North America, the Fennoscandian Ice Sheet over Europe — operated at a different scale entirely, blanketing entire regions under ice 2–3 km thick. Their erosional legacy includes vast areas of polished, striated bedrock in the Canadian Shield, the shallow depressions now occupied by the Great Lakes, and **roches moutonnées** — asymmetric bedrock knobs with a smoothly abraded upstream (stoss) face and a jagged plucked downstream (lee) face, pointing in the direction of ice flow like compass needles of past glaciation. When ice sheets melt, they leave behind enormous quantities of glacial debris in characteristic depositional landforms. **Till** — unsorted, unstratified material ranging from clay to boulders, deposited directly from melting ice without any sorting by water — makes up terminal moraines (marking the furthest ice advance), lateral moraines, and the ground moraine beneath the glacier. **Drumlins** are streamlined, oval hills of till moulded beneath an active ice sheet: elongated parallel to ice flow, blunt at the upstream end and tapered downstream, often occurring in fields of thousands (the drumlin field of central New York was crossed by the retreating Laurentide Ice Sheet). **Outwash** — sediment sorted and stratified by meltwater streams flowing from the glacier — is deposited as broad outwash plains in front of terminal moraines; the sorting by flowing water means outwash contains layered sands and gravels, unlike the chaotic mix of till. **Eskers** are sinuous ridges of sand and gravel that were deposited by meltwater streams flowing within tunnels beneath the ice; when the ice melts away, the tunnel fill is left standing as a ridge on the landscape — sometimes tens of kilometres long. **Kettle lakes** form when large blocks of ice are buried in outwash sediment as a glacier retreats; when the ice block melts, it leaves a depression that fills with groundwater or surface runoff, creating a lake. Minnesota's famous "10,000 lakes" are predominantly kettles and other glacial depressions.

**Sea level and the ice age connection.** The volume of water locked in ice sheets directly controls global sea level. During the Last Glacial Maximum, so much water was stored in ice that sea level stood ~120 m below its present position — a drop equivalent to exposing an area of continental shelf the size of South America. As ice sheets melt, this water returns to the ocean. The 20,000-year sea-level record, reconstructed from coral reefs, submerged shorelines, and sediment cores, shows sea level rising ~120 m since the LGM at a rate that peaked around 15,000 years ago at ~40 mm per year (ten times faster than current anthropogenic rates). This sea-level rise flooded river valleys to create estuaries and rias, transformed coastal plains into continental shelves, and flooded glacial troughs to create fjords. Current sea-level rise of ~3.7 mm per year (and accelerating) is already affecting low-lying coastlines worldwide.

**Wave processes and coastal erosion.** At every ocean margin, waves deliver kinetic energy from wind to coastline continuously. Waves break when water depth falls below half the wavelength — the depth at which the circular orbital motion of water particles begins to drag on the seafloor, slowing the wave base and causing the wave to steepen and break. Breaking waves attack coastlines by three mechanisms: **hydraulic action** (the compression and sudden release of trapped air in rock cracks, which can exert pressures of hundreds of kiloPascals); **abrasion** (sediment carried by waves and currents acts as sandpaper on rock surfaces, cutting notches and platforms); and **solution** (slightly acidic seawater dissolves carbonate rocks). On rocky, high-energy coastlines, wave erosion produces a characteristic sequence: a **wave-cut notch** at the base of the cliff where abrasion is most intense; a **sea cliff** rising above; and a **wave-cut platform** extending seaward at low-tide level — a flat or gently sloping bedrock surface carved by waves as the cliff retreats. Where headlands protrude into the sea, waves attack from multiple directions: caves form on opposite sides of a headland, eventually meeting to form a **sea arch**; when the arch roof collapses, an isolated **sea stack** is left offshore. The Old Man of Hoy — a 137-m sandstone stack off Orkney, Scotland — is one of Britain's most iconic geological features, and will itself eventually collapse.

**Longshore drift and depositional coasts.** Most coastlines are not purely erosional; they are also receiving and redistributing sediment. Waves rarely arrive perfectly parallel to the shore — they approach at an angle, push sediment up the beach diagonally (swash), and gravity pulls it straight back down (backwash). The net result is a systematic transport of sediment along the coast in the direction of wave approach: **longshore drift**. Longshore drift is the dominant mechanism distributing sand and gravel along coastlines and building depositional features. A **beach** is a dynamic equilibrium between wave energy (which removes sediment) and sediment supply (from rivers, eroding cliffs, or longshore drift); beaches are not permanent features but daily-adjusted systems that constantly reconfigure their profile in response to wave energy. Where a headland interrupts the coast, longshore drift extends a **spit** — a finger of sand projecting from the headland across a bay mouth, sometimes curving at its tip as waves refract around the end. **Barrier islands** — long, narrow sand islands running parallel to the mainland — form on gently sloping coastlines with abundant sediment; they are separated from the mainland by shallow **lagoons** and connected to the open ocean through tidal inlets. The US Atlantic and Gulf coasts are almost entirely fringed by barrier islands: Miami Beach, the Outer Banks of North Carolina, and Padre Island in Texas are all barrier islands. They are among Earth's most dynamic and hazard-prone landforms — subject to overwash, migration, and eventual submergence as sea level rises.`,
      cards: [
        {
          name: 'Glacial Landforms — Erosional',
          icon: Mountain,
          color: BRAND.coral,
          desc: "Alpine glaciers: cirque (armchair hollow at glacier head), arête (knife-edge ridge between cirques), horn (pyramidal peak — Matterhorn), U-shaped valley (glacier widens V to U — Yosemite), hanging valley (tributary left high → waterfall — Bridalveil Fall), fjord (glacial trough flooded by sea — Sognefjord, 204 km long × 1,308 m deep). Continental glaciers: roches moutonnées (abraded stoss face, plucked lee face), polished/striated bedrock, Great Lakes basins.",
          examples: "Yosemite Valley: 1,100 m deep U-valley · Matterhorn: classic horn · Sognefjord: 1,308 m deep · Canadian Shield: striated bedrock",
        },
        {
          name: 'Glacial Landforms — Depositional',
          icon: Layers,
          color: BRAND.gold,
          desc: "Till (unsorted, direct from ice) vs. outwash (sorted by meltwater). Moraines: terminal (farthest advance), lateral (valley side), medial (merged glaciers). Drumlins: streamlined till hills, elongated parallel to ice flow, occur in fields. Eskers: sinuous sand/gravel ridges from subglacial meltwater tunnels. Kettle lakes: depressions from buried ice blocks (Minnesota's 10,000 lakes). Outwash plains: sorted sand/gravel fans beyond terminal moraine.",
          examples: "Central NY drumlins: field of thousands · Minnesota kettles: 10,000 lakes · Long Island: terminal moraine · Canterbury Plain NZ: glacial outwash",
        },
        {
          name: 'Coastal Landforms',
          icon: Waves,
          color: BRAND.accent,
          desc: "Erosional coasts (high energy, resistant rock): sea cliff, wave-cut notch, wave-cut platform, sea arch (cave on both sides of headland → roof erodes through), sea stack (arch collapses → isolated column — Old Man of Hoy, 137 m). Depositional coasts (abundant sediment): beach (dynamic equilibrium), spit (sand bar from headland, driven by longshore drift), barrier island (parallel offshore sand island + lagoon — US East Coast). Longshore drift: net sediment transport along shore by angled wave swash/backwash.",
          examples: "Old Man of Hoy: 137 m sea stack · Outer Banks NC: barrier island · Chesapeake Bay: drowned river mouth (ria) · Dungeness: largest spit in UK",
        },
      ],
    },
    {
      type: 'quiz',
      questions: [
        {
          q: "A valley in the Swiss Alps has steep, nearly vertical walls and a flat floor. A river now occupies the valley, but it is far too small to have carved such a large, wide trough. What carved this valley, and what would you expect to find at the head of the valley?",
          a: [
            "The valley was carved by a much larger river during a wetter Pleistocene climate; at the valley head you would expect a large river delta where the ancient river deposited its sediment load when it slowed",
            "The valley was carved by a glacier — the steep walls and flat floor are the U-shaped cross-section produced by glacial widening and deepening; at the valley head you would expect a cirque, a steep-walled armchair-shaped hollow where the glacier accumulated, possibly with an arête or horn above it",
            "The valley was carved by a fault — the flat floor and vertical walls are the product of tectonic subsidence along a graben; at the valley head you would expect a fault scarp and fractured bedrock",
            "The valley was carved by mass wasting — repeated rockfall and landslides from the steep surrounding mountains widened the valley; at the valley head you would expect a large talus cone deposited by accumulated rockfall debris",
          ],
          correct: 1,
          explain: "A river large enough to carve the valley (A) would leave a V-shaped cross-section — wider at the top, narrower at the base — not the characteristic flat-floored, steep-walled U. River deltas form where rivers meet standing water, not at valley heads. Grabens (C) produce valley floors bounded by parallel faults and are not associated with cirques or arêtes — they are tectonic, not erosional, features; faulted valleys typically have irregular, fractured floors rather than the smooth, polished surfaces produced by glacial abrasion. Mass wasting (D) does contribute debris to slopes but cannot produce a U-shaped trough or the systematic widening characteristic of glacial erosion; talus cones are depositional features that partially fill valleys, not carve them. The correct answer is B: glaciers transform V-shaped river valleys into U-shaped glacial troughs by eroding laterally as well as vertically — the ice fills the entire valley width and scours both the floor and walls, widening and deepening the valley into the parabolic U cross-section; the glacier originates at a cirque — a steep-walled, armchair-shaped hollow carved by frost action and plucking at the glacier's head where ice accumulates; above the cirque, if the glacier eroded from multiple directions, the ridges would be sharpened into arêtes and possibly horns; the valley itself may contain polished, striated bedrock and moraines from the former glacier; if the valley reaches the sea and was flooded during deglaciation, it would be a fjord.",
        },
        {
          q: "A coastal engineer surveys a beach and finds that sand is accumulating on one side of a newly built jetty (a wall projecting into the sea) and being eroded on the other side. Which process is responsible, and in which direction was sediment moving along this coastline before the jetty was built?",
          a: [
            "The accumulation is caused by tidal currents depositing sediment against the jetty; tides flow in multiple directions so the erosion on the other side is unrelated to the accumulation",
            "The accumulation is caused by longshore drift — the systematic transport of sediment along the coast by angled wave action; sediment was moving from the erosion side toward the accumulation side before the jetty intercepted it",
            "The accumulation is caused by offshore sediment being pushed onshore by wave action on the accumulation side; the erosion on the other side is caused by waves being deflected by the jetty",
            "The accumulation and erosion are both caused by storm waves that periodically rework the beach in random directions; the jetty happened to be built during a period when storms were approaching from the accumulation side",
          ],
          correct: 1,
          explain: "Tidal currents (A) do transport sediment and do flow in multiple directions, but tidal-driven deposition would not produce systematic accumulation on one side of a structure and erosion on the other; tidal transport is bidirectional and would tend to deposit sediment in slack water zones rather than strongly asymmetric patterns. Onshore wave push (C) does move sediment landward but does not explain the systematic asymmetry — both sides of the jetty are exposed to similar wave onshore transport; deflection alone cannot account for net sediment loss on one side and net gain on the other. Random storm effects (D) would not produce a systematic pattern — if storms approach from different directions, accumulation and erosion would switch sides over time, not produce persistent asymmetry. The correct answer is B: longshore drift is the net transport of sediment along a coast in the direction of wave approach; waves arriving at an angle push sediment obliquely up the beach (swash) while gravity pulls it straight back down (backwash), producing a net downcoast transport with each wave; this process moves large quantities of sand and gravel along coastlines; when a jetty interrupts the coast, it acts as a barrier to longshore drift — sediment accumulates on the upcoast side (where it was coming from) while the downcoast side is starved of its sediment supply and erodes; the asymmetry of accumulation and erosion reveals both the direction of drift and its magnitude; this is why groynes (short walls built to trap sediment and maintain beaches) must be regularly supplemented with sediment on their downcoast sides to prevent erosion of adjacent beaches.",
        },
        {
          q: "During the Last Glacial Maximum 20,000 years ago, global sea level was approximately 120 m lower than today. What caused this sea-level drop, and what does sea-level rise since the LGM tell us about the fates of ice sheets and coastlines?",
          a: [
            "Sea level dropped because the ocean basins expanded as tectonic plates spread apart during the glacial period, creating more volume for the same amount of water; the subsequent sea-level rise reflects closing of the ocean basins as spreading slowed",
            "Sea level dropped because large volumes of water were locked in continental ice sheets — water evaporated from the ocean, precipitated as snow at high latitudes, and accumulated as ice rather than returning to the ocean; as ice sheets melted since the LGM, meltwater returned to the ocean and raised sea level ~120 m, flooding continental shelves, river valleys (creating estuaries), and glacial troughs (creating fjords)",
            "Sea level dropped because polar ice caps grew thicker and denser, pushing down the seafloor through isostatic adjustment, effectively lowering the water surface; as the ice thinned, the seafloor rebounded and sea level rose",
            "Sea level dropped because global temperatures were lower, causing the ocean water itself to contract by thermal contraction; the 120 m drop reflects how much denser cold water is than warm water over the full depth of the ocean",
          ],
          correct: 1,
          explain: "Ocean basin expansion (A) does occur through seafloor spreading and does affect sea level over millions of years — when spreading rates increase, mid-ocean ridges are hotter and more buoyant, displacing water and raising sea level; but spreading-rate changes operate on millions-of-years timescales, not the 20,000-year glacial-interglacial cycle; this mechanism cannot explain the LGM sea-level drop. Isostatic adjustment (C) does occur — ice sheet weight depresses the crust, and this rebounds after deglaciation (Scandinavia is still rising at ~8 mm/yr from the last ice sheet) — but crustal depression lowers the land surface, not the ocean surface; isostasy affects relative sea level (the position of sea level relative to the land) not global (eustatic) sea level. Thermal contraction (D) does affect sea level — thermal expansion of seawater is now contributing ~40% of current sea-level rise — but even cooling the entire ocean by 5 °C would produce only ~3–5 m of sea-level drop through thermal contraction, not 120 m; this is orders of magnitude too small to explain the LGM sea-level drop. The correct answer is B: the hydrological explanation is straightforward — water evaporated from the ocean falls as snow at high latitudes; during glacial periods, more snow accumulates in winter than melts in summer, and the surplus builds up as ice; over tens of thousands of years, enormous quantities of ocean water are transferred to ice sheets (the Laurentide Ice Sheet over North America held ~25–35 million km³ of ice); this water is no longer in the ocean, so sea level drops; when ice melts, the water returns; the ~120 m sea-level rise since the LGM directly records the volume of ice that melted — primarily the Laurentide and Fennoscandian ice sheets, plus contributions from Antarctica and mountain glaciers; this sea-level rise flooded continental shelves (exposing them as land during the LGM and drowning them since), drowned river mouths to form estuaries and rias, and flooded glacial troughs to form fjords; current anthropogenic warming is melting remaining ice (Greenland, West Antarctic Ice Sheet, mountain glaciers) and thermally expanding seawater, driving sea-level rise that threatens coastal communities globally.",
        },
      ],
    },
  ],
}

export default glacialCoastalLandforms
