import type { Lesson } from './types'

const geol201Capstone: Lesson = {
  id: 'geol-201-capstone',
  title: 'Deep Time Final Exam',
  track: 'geo',
  trackName: 'Geology',
  level: 'Intermediate',
  duration: '30 min',
  xpReward: 500,
  description: 'A 10-question cumulative assessment integrating all five Deep Time chapters: geological timescale and dating (Ch. 1), stratigraphy and the rock record (Ch. 2), the fossil record (Ch. 3), major events in Earth history (Ch. 4), and field methods (Ch. 5). Each question draws on concepts from two or more chapters simultaneously.',
  sources: [
    { org: 'USGS',      title: 'Geologic Time Scale — Public Domain',                url: 'https://www.usgs.gov/media/images/geologic-time-scale' },
    { org: 'USGS',      title: 'National Geologic Map Database — Public Domain',      url: 'https://ngmdb.usgs.gov' },
    { org: 'OpenStax',  title: 'Physical Geology, 2nd ed., Ch. 1–13 (CC-BY 4.0)',    url: 'https://openstax.org/books/physical-geology-2e' },
    { org: 'PRI',       title: 'Earth@Home: Digital Encyclopedia (all sections)',     url: 'https://earthathome.org' },
    { org: 'AGI',       title: 'Glossary of Geology, 5th ed.',                       url: 'https://www.americangeosciences.org/pubs/glossary' },
    { org: 'Smithsonian', title: 'Deep Time — Hall of Fossils (educational)',        url: 'https://naturalhistory.si.edu/exhibits/david-h-koch-hall-fossils-deep-time' },
  ],
  sections: [
    {
      type: 'intro',
      title: 'Deep Time Final Exam',
      body: `A geological field campaign doesn't separate stratigraphy from palaeontology from structural geology from geochronology. You stand at an outcrop and everything arrives at once: the structural orientation of the beds, the grain size and sedimentary structures, the fossils, the contacts — and from all of it together you build the story of what happened, in what order, and why.

That synthesis is what this exam tests. Each question reaches across modules and asks you to combine what you know about time, strata, life, history, and field methods into a coherent geological interpretation. Ten questions, thirty minutes.`,
    },
    {
      type: 'quiz',
      questions: [
        // ── Q1: Modules 2.1 + 2.2 ──────────────────────────────────────────
        {
          q: 'A cliff exposure shows three rock units. Unit A (bottom) is a limestone with abundant trilobites. Unit B (middle) is a sandstone that truncates A at an irregular, incised surface. Unit C (top) is a shale with ammonites. A radiometric date from a volcanic ash layer immediately above Unit B gives 350 Ma. What is the relative age order, what type of contact separates A from B, and what geological period does 350 Ma correspond to?',
          a: [
            'A is youngest, B is middle, C is oldest; rocks are always youngest at the base of a cliff in folded terrains; the contact is a fault; 350 Ma is Devonian',
            'A is oldest, B is middle, C is youngest by the law of superposition. The contact between A and B is a disconformity (erosional unconformity) — the irregular, incised surface indicates erosion and a time gap between the two units; the beds are approximately parallel. 350 Ma falls within the Early Carboniferous (Mississippian) period (Carboniferous: 358.9–298.9 Ma)',
            'C is oldest and A is youngest because trilobites are more primitive than ammonites, and more primitive organisms are always younger in evolutionary terms; the contact is a gradational conformable boundary; 350 Ma is Silurian',
            'The relative age cannot be determined without radiometric dates for all three units; only C has a directly constrained age from the ash layer; the contact between A and B is an intrusive contact',
          ],
          correct: 1,
          explain: "Three geological principles apply here. Law of Superposition: in an undisturbed sequence, the oldest rocks are at the bottom and the youngest at the top — A is oldest, B is middle, C is youngest. The contact between A and B: the sandstone 'truncates A at an irregular, incised surface.' Truncation at an irregular surface indicates erosion of A's surface before B was deposited. The beds on either side appear approximately parallel (sandstone lying approximately horizontally on limestone). This is a disconformity — an erosional unconformity where the bounding units are approximately parallel but a measurable time gap (marked by the erosion surface) exists. If the beds were angular (A steeply tilted, B horizontal), it would be an angular unconformity. Radiometric date: 350 Ma is within the Carboniferous period, specifically the Mississippian (Early Carboniferous) epoch. The full Carboniferous spans 358.9–298.9 Ma. The Devonian immediately precedes it at 419.2–358.9 Ma; the Permian follows at 298.9–251.9 Ma. Option A inverts superposition and confuses periods. Option C applies a false evolutionary 'index of primitiveness' — fossil complexity does not determine relative age; only stratigraphic position and geochronological data do. Option D understates the power of relative dating: superposition determines A-B-C order without any radiometric dates.",
        },
        // ── Q2: Modules 2.1 + 2.3 ──────────────────────────────────────────
        {
          q: `Conodonts recovered from a limestone belong to a biozone that existed only from 443 to 419 Ma. A radiometric U-Pb date from an igneous dyke that cross-cuts the limestone gives 430 ± 5 Ma. Is the dyke older or younger than the limestone? What does the biozone constrain about the limestone\'s age? Are the two constraints consistent?`,
          a: [
            'The dyke is older than the limestone because dykes always form before the rocks they intrude; the biozone tells us the limestone is Devonian; the constraints are inconsistent — a Silurian dyke cannot intrude Devonian limestone',
            'The dyke is younger than the limestone by the cross-cutting relationships principle: a dyke that cross-cuts a rock unit must have intruded after the host rock formed. The biozone (443–419 Ma) tells us the limestone was deposited during the Silurian period, sometime between 443 and 419 Ma. The dyke date of 430 ± 5 Ma (425–435 Ma at 1σ) falls within the Silurian and within the biozone range — the dyke therefore intruded into the limestone while the limestone was Silurian in age, after the limestone formed but before or during the later part of the biozone. The two constraints are fully consistent',
            'The dyke is younger than the limestone; the biozone constrains the limestone to the Ordovician; the two constraints are inconsistent because a 430 Ma dyke cannot intrude Ordovician limestone — the dyke should predate the limestone',
            'Nothing can be concluded about relative age from a cross-cutting dyke alone; only the law of superposition determines relative age; the biozone constrains the age to exactly 443–419 Ma; the U-Pb date is irrelevant because dykes are intrusive, not sedimentary',
          ],
          correct: 1,
          explain: "Two independent dating methods converge on a consistent picture. Cross-cutting relationships: any igneous body that intrudes (cross-cuts) a pre-existing rock must be younger than that rock. The dyke cuts the limestone, so the dyke is younger. This is a basic relative dating principle that applies regardless of the rocks' absolute ages. Biostratigraphy: the conodont biozone existed only between 443 and 419 Ma. For the limestone to contain these conodonts, it must have been deposited while the organisms were alive — sometime between 443 and 419 Ma. This is the Silurian period (443.8–419.2 Ma). The limestone cannot be older than 443 Ma (the conodonts didn't exist yet) or younger than 419 Ma (they were extinct). Consistency check: the dyke date is 430 ± 5 Ma. At one sigma, this spans 425–435 Ma, fully within the biozone range of 443–419 Ma. The cross-cutting relationship says the dyke is younger than the limestone. If the limestone formed between 443 and 430 Ma and the dyke intruded at 430 Ma, this is consistent: the limestone formed during the early to middle Silurian, and the dyke intruded in the middle Silurian (still within the biozone duration). Option A inverts the cross-cutting principle. Option C misidentifies the biozone period (443–419 Ma is Silurian, not Ordovician). Option D incorrectly dismisses cross-cutting relationships and misunderstands what biozone ages constrain.",
        },
        // ── Q3: Modules 2.2 + 2.3 ──────────────────────────────────────────
        {
          q: 'A sequence from base to top shows: (i) black laminated shale with no fossils; (ii) grey shale with rare thin-shelled bivalves; (iii) limestone with diverse corals, brachiopods, and echinoderms; (iv) oolitic limestone. Is this sequence transgressive or regressive? What does the upward trend in fossil diversity tell you about water depth and oxygen availability?',
          a: [
            'This is a transgressive (deepening-upward) sequence because dark shales always represent shallow water and limestones represent deep water; the increasing fossil diversity records sea level rise; oolitic limestone at the top represents the deepest-water facies',
            'This is a shallowing-upward (regressive or progradational) sequence. The sequence records decreasing water depth from base to top: (i) black laminated shale with no fossils indicates anoxic bottom water too oxygen-depleted for benthic life — deep or restricted basin below the oxygen minimum; (ii) grey shale with rare bivalves records slightly better oxygenation — dysoxic conditions — with a few stress-tolerant species; (iii) diverse limestone fauna (corals, brachiopods, echinoderms) indicates well-oxygenated, photic-zone, normal-marine shallow water with full species diversity; (iv) oolitic limestone records very shallow (<2 m), high-energy, wave-agitated conditions required for oolite formation. The progressive fossil diversity increase from zero to maximum directly tracks improving oxygenation and shallowing water depth',
            'This is a regressive (shallowing-upward) sequence, but the fossil diversity has nothing to do with water depth or oxygen — diversity increases upward purely because older organisms are simpler and diversity increases through evolution over time; the oolitic limestone represents the deepest facies because oolites are chemical precipitates from deep basinal brine',
            'The sequence cannot be identified as transgressive or regressive without strike-and-dip measurements; fossil diversity is controlled entirely by temperature rather than oxygenation or water depth; the black shale indicates terrestrial (swamp) deposition, not marine conditions',
          ],
          correct: 1,
          explain: "Each facies in the sequence records progressively shallower water and improving oxygenation — a shallowing-upward sequence, which in sequence stratigraphy typically records regression (sea level fall) or progradation (sediment input filling the basin from deeper to shallower). Black laminated shale, no fossils: dark colour in marine shale reflects abundant organic matter — preservation of organics requires oxygen-depleted (anoxic) conditions in the bottom water, because aerobic bacteria destroy organic matter before it can be buried in well-oxygenated settings. Anoxic bottom water cannot support benthic (bottom-dwelling) metazoan life, explaining the absence of fossils. This is typically deep water (below the pycnocline) or restricted water (e.g., a stratified basin). Grey shale with rare bivalves: grey colour indicates partial oxygenation (dysoxic). Thin-shelled bivalves (epifaunal opportunists) are among the most stress-tolerant benthic organisms, able to survive dysoxic episodes that exclude corals and echinoderms. Diverse limestone fauna: corals, brachiopods, and echinoderms all require well-oxygenated, normal-salinity, photic-zone conditions — this is warm, shallow, carbonate-producing tropical/subtropical water. Ooids form only in agitated, highly oxygenated water, shallower than ~2 m, where wave energy continuously rolls carbonate grains and precipitates concentric aragonite cortices around nuclei. The upward sequence from anoxic/diverse → diverse/shallow → very shallow agitated records systematic shallowing and oxygenation increase. Option A inverts the facies: dark shale is deeper/anoxic, oolitic limestone is shallowest. Option C applies an evolutionary-time argument to a single stratigraphic section — diversity differences within one section record environment, not evolutionary time. Option D is incorrect: fossil diversity correlates strongly with oxygenation and depth in marine sequences.",
        },
        // ── Q4: Modules 2.2 + 2.5 ──────────────────────────────────────────
        {
          q: `A sandstone formation crops out in two valleys on either side of a ridge. In the south-draining valley (south flank of the ridge), the contact V\'s upstream (northward, toward the ridge). In the north-draining valley (north flank of the ridge), the contact also V\'s upstream (southward, toward the ridge). What do these V-directions tell you about the dip of the sandstone on each flank? What structural feature does this ridge most likely represent?`,
          a: [
            'Both V\'s pointing toward the ridge indicate that the beds dip away from the ridge on both flanks; this is the pattern of a syncline, with the ridge preserving the youngest rocks at the valley centre',
            'In the south-draining valley, V pointing upstream (northward, toward the ridge) indicates the beds on the south flank dip southward (away from the ridge, downstream), but the dip is gentle enough that the V still points upstream rather than reversing. In the north-draining valley, V pointing upstream (southward, toward the ridge) indicates the beds on the north flank dip northward (also away from the ridge, downstream), again gently enough to preserve the upstream V direction. Both limbs dipping gently away from the ridge is the diagnostic map pattern of an anticline. The ridge most likely represents the anticlinal axis — the oldest rocks would be exposed at the crest by erosion, and the resistant sandstone may form the topographic high',
            'Both V\'s pointing toward the ridge indicate horizontal beds, because horizontal beds always follow topographic contours and V upstream; the ridge is a simple topographic high with no structural significance',
            'The V-rule cannot be applied across two separate valleys; each valley must be interpreted in isolation and no cross-valley structural inference is valid from V-directions alone',
          ],
          correct: 1,
          explain: "The V-rule links the direction of a contact's V in a valley to the dip of the beds. When beds dip downstream (in the same direction as the river flows) but at an angle gentler than the valley walls, the contact still V's upstream — the upstream-V tendency of topographic surfaces is preserved until the dip exceeds the valley wall angle. South flank (south-draining valley): the river drains south, so upstream = north. The beds on the south flank of the anticline dip southward (away from the anticline axis, in the downstream direction). Since the dip is gentle, the contact V's upstream (northward, toward the ridge). North flank (north-draining valley): the river drains north, so upstream = south. The beds on the north flank dip northward (also away from the anticline axis, downstream in this valley). The same logic applies — gentle dip means V still points upstream (southward, toward the ridge). Crucially, BOTH V's point toward the ridge on their respective upstream sides. This means the beds on BOTH flanks are dipping AWAY from the ridge. Beds dipping away from a central axis on both sides = anticline. The ridge is the anticlinal crest. Erosion of the anticlinal hinge exposes the oldest rocks in the core; if the sandstone is resistant, it forms a topographic ridge above the surrounding terrain. Option A inverts the geometry: a syncline would have beds dipping TOWARD the axis, and the youngest rocks at the core. The V's pointing toward the axis (upstream) with beds dipping that way would be a syncline, but in this case the beds dip AWAY from the ridge (downstream) — an anticline. Option C is incorrect: the V behaviour here is explained by gently downstream-dipping beds, not horizontal beds (horizontal beds would V exactly as topographic contours, which differs from the described pattern). Option D is wrong: V-directions across multiple valleys are the standard method for identifying folds on geological maps.",
        },
        // ── Q5: Modules 2.3 + 2.4 ──────────────────────────────────────────
        {
          q: 'The Burgess Shale (508 Ma, Cambrian) and the Chengjiang Lagerstätte (518 Ma, Cambrian) preserve exceptional soft-bodied organism assemblages. Why do soft tissues preserve in these Lagerstätten but not in typical marine sedimentary sequences? What do these faunas reveal about the Cambrian Explosion?',
          a: [
            'Soft tissues in Lagerstätten were preserved by rapid mineralisation after volcanic ash burial, which happens only in active volcanic settings like those adjacent to the Cambrian arc systems; they reveal that the Cambrian Explosion was triggered by volcanic activity releasing nutrients into the ocean',
            'Soft-body preservation in Lagerstätten requires exceptional taphonomic conditions: (1) rapid burial by event sedimentation (mudflow, turbidity current) removes remains from the zone of aerobic decomposition; (2) anoxic or low-oxygen bottom waters inhibit scavenging by benthic organisms and slow microbial decay; (3) fine-grained sediment (mudstone) creates a low-permeability barrier that impedes fluid exchange and further decay. In typical marine sediments, oxic bottom water, scavengers, and slow burial allow soft tissues to decompose entirely. The Burgess and Chengjiang faunas reveal that the Cambrian Explosion produced a sudden diversification of almost all major animal body plans within ~20 Ma, including arthropods, molluscs, echinoderms, chordates, sponges, and many extinct phyla (Anomalocaris, Hallucigenia, Opabinia). This diversity was present but largely invisible in the pre-Lagerstätte record because soft-bodied animals leave no trace',
            'Lagerstätten preserve soft tissue because Cambrian ocean water had much higher silica concentrations than modern oceans, causing spontaneous silicification of soft tissue within hours of death; the faunas reveal that the Cambrian Explosion produced only arthropods and molluscs — all other phyla evolved later',
            'Soft tissues are preserved in these deposits only because the organisms had partially mineralised bodies (thin phosphatic coatings); true soft-body preservation does not occur in the geological record; the faunas are therefore a biased sample of already partially-hard-bodied organisms',
          ],
          correct: 1,
          explain: "Lagerstätten (German: storage places) are exceptional fossil sites where preservation goes far beyond the norm — recording not just hard parts (shells, bones) but soft tissues (gills, eyes, gut contents, musculature, even neural tissue in some cases). The taphonomic window that allows this requires the simultaneous inhibition of all decay pathways. Rapid burial: burial by a mudslide (Burgess Shale: interpreted as mudflow off a reef escarpment) or gravity flow removes organisms from the oxygenated seafloor surface within hours, before scavengers and aerobic bacteria can destroy soft parts. Anoxic/dysoxic bottom conditions: oxygen-depleted water prevents aerobic microbial decomposition and excludes the burrowing and scavenging bioturbators that would otherwise disturb and destroy soft tissue. Fine-grained matrix: the low-permeability mud inhibits the fluid flux that fuels decay. In typical oxic marine sediments, one or more of these conditions is absent — soft tissues rarely survive more than days to weeks. The Cambrian faunas they reveal: the Burgess Shale (508 Ma) and Chengjiang (518 Ma) document a diverse bilaterian fauna including primitive chordates (Pikaia, Myllokunmingia), arthropods (Anomalocaris, trilobites, bivalved crustaceans), lophotrochozoans, echinoderms, priapulid worms, and many problematica (Hallucigenia, Opabinia) of uncertain phylogenetic affinity. This diversity demonstrates that the Cambrian Explosion produced representatives of nearly all major animal body plans within the first ~20 Ma of the Cambrian, rather than the gradual diversification that a sparsely fossilised interval might imply. Option A: volcanic ash burial (bentonite) does produce some exceptional preservation but is not the primary mechanism at Burgess or Chengjiang, and the Cambrian Explosion was not triggered by volcanic nutrient release. Option C: elevated Cambrian silica concentrations did occur but do not explain soft preservation. Option D: Lagerstätten do preserve genuinely soft, unmineralised tissue, as evidenced by muscle fibres and neural tissue in some sites.",
        },
        // ── Q6: Modules 2.4 + 2.1 ──────────────────────────────────────────
        {
          q: 'The end-Permian mass extinction (~252 Ma) eliminated approximately 96% of marine species — the most severe biotic crisis in the history of animal life. Describe two independent geological records of this event, name the primary kill mechanism best supported by evidence, and explain why marine recovery took ~10 million years.',
          a: [
            'The two geological records are: (1) the impact ejecta layer and iridium anomaly at the Permo-Triassic boundary; (2) the disappearance of reef-building organisms from carbonate rocks. The primary mechanism is a bolide impact, identical to the K-Pg event. Recovery took 10 Ma because the impact caused a nuclear winter lasting several million years',
            'Two independent geological records: (1) The abrupt disappearance of nearly all marine invertebrate taxa (rugose and tabulate corals, most brachiopods, blastoids, most bryozoans, ~90% of marine genera) at the Permo-Triassic boundary in rock sections worldwide — one of the most dramatic biotic turnovers visible in the stratigraphic record. (2) A large negative carbon isotope excursion (δ¹³C) in carbonate rocks at the boundary — a sudden shift to lighter carbon isotopes recording a massive, rapid injection of isotopically light carbon into the ocean–atmosphere system. The primary kill mechanism: massive volcanic eruption of the Siberian Traps (~3 million km³ of flood basalt emplaced in <1 Ma), releasing enormous quantities of CO₂, SO₂, and other volatiles, causing ocean acidification, global warming, and widespread anoxia. Recovery took ~10 Ma because the kill mechanisms (anoxia, acidification, elevated temperatures) persisted long after the main extinction pulse; ecosystem engineers (reef-builders, bioturbators) had been eliminated, preventing ecosystem recovery; and repeated volcanic pulses may have disrupted early recovery attempts',
            'The two geological records are: (1) the first appearance of mammals in the Triassic immediately above the boundary, indicating rapid evolutionary replacement; (2) a positive carbon isotope excursion recording enhanced ocean productivity. The primary mechanism is sea-level fall caused by glaciation at the end of the Permian. Recovery was delayed by 10 Ma because glacial conditions persisted',
            'There is only one geological record of the end-Permian extinction: the fossil record itself. No geochemical or sedimentological evidence independent of fossils exists. The primary mechanism is unknown. Recovery took 10 Ma because mammals had to evolve from mammal-like reptiles before ecosystems could re-establish',
          ],
          correct: 1,
          explain: "The end-Permian extinction is the most severe mass extinction in the history of complex animal life, and it is documented by multiple independent geological proxies. Fossil record: the abrupt disappearance of dominant Paleozoic marine groups — rugose corals, tabulate corals, trilobites (already declining), most brachiopods, blastoids, fusulinid foraminifera, and most crinoids — is visible in carbonate sequences globally. In some sections (e.g., Meishan, China — the Global Boundary Stratotype), the extinction horizon is centimetre-scale. Carbon isotope excursion: δ¹³C in marine carbonates decreases sharply (negative excursion) by 2–8‰ at the boundary. This records rapid input of isotopically light carbon (light = low ¹³C/¹²C ratio). The carbon must have been released by the Siberian Traps volcanism: magmatic CO₂ is depleted in ¹³C relative to marine carbonates; so is thermogenic CO₂ from cooking organic-rich sediments beneath the lava flows. Other records: evidence of ocean anoxia (laminated black shales, pyrite framboids indicating euxinic conditions); evidence of ocean acidification (dissolution of carbonate); potential methanoclathrate destabilisation. Primary kill mechanism: the Siberian Traps (erupted ~252 Ma, ~3 × 10⁶ km³ of flood basalt in <1 Ma) released gigatonnes of CO₂ and SO₂, causing acidification, warming, and deoxygenation of the global ocean — conditions that directly explain both the magnitude of the marine extinction and the extended recovery interval. Slow recovery: Siberian Traps volcanism may have continued episodically for ~500,000 years, repeatedly disrupting early Triassic ecosystems; the loss of reef-building organisms (rugose corals, stromatoporoid sponges) meant the reef ecosystem took ~10 Ma to re-establish under Early Triassic biotic groups. Option A applies the bolide impact model (K-Pg mechanism) to the end-Permian — the end-Permian has no confirmed impact layer or iridium anomaly. Option C inverts the carbon isotope direction and incorrectly invokes glaciation (the end-Permian was the reverse — a warming event). Option D dismisses the geochemical record that is well-documented.",
        },
        // ── Q7: Modules 2.4 + 2.5 ──────────────────────────────────────────
        {
          q: 'A volcanic rock contains ~4 mm plagioclase and hornblende phenocrysts in a grey aphanitic groundmass, and has vesicles partially filled by calcite. It sits unconformably over folded Devonian sedimentary rocks, with the unconformity surface showing ~10 m of relief. Identify the rock, explain what the texture reveals about its eruption history, what the calcite-filled vesicles indicate, and what the unconformity records about geological history.',
          a: [
            'The rock is a granite (coarse-grained plutonic rock); the phenocrysts record slow crystallisation at depth; the calcite vesicles indicate limestone xenoliths were incorporated into the melt; the unconformity records normal stratigraphic thinning away from the sediment source',
            'The rock is a porphyritic andesite (intermediate volcanic rock). Porphyritic texture: the plagioclase and hornblende phenocrysts (~4 mm, visible to the naked eye) grew slowly in a magma chamber at depth — the first, slow stage of cooling, producing large crystals. The eruption then rapidly quenched the remaining melt to the aphanitic groundmass (microscopic crystals) — the second, fast stage. Hornblende phenocrysts indicate moderate water content in the melt, consistent with andesitic to dacitic compositions at convergent margins. The calcite-filled vesicles (amygdales): vesicles formed when dissolved volatiles (H₂O, CO₂) exsolved as pressure dropped during eruption, creating gas bubbles trapped in the rapidly-solidifying groundmass. The calcite precipitated from hydrothermal fluids circulating through the rock after eruption — a secondary mineral, not primary magmatic. The unconformity: the folded Devonian rocks record an earlier episode of deformation (Devonian or later orogeny); subsequent erosion bevelled the fold structure, producing the irregular unconformity surface (~10 m of relief); the volcanic rock then erupted onto this eroded surface — the erosion therefore post-dates the Devonian folding and pre-dates the volcanic eruption',
            'The rock is a rhyolite (felsic volcanic rock); hornblende in the phenocrysts indicates a mafic composition and rhyolite always has hornblende; vesicles filled with calcite are primary — calcite crystallised directly from the volcanic gas phase during eruption; the unconformity records a sea-level change that exposed the Devonian seafloor',
            'The rock is a basalt; the phenocrysts are olivine mistaken for hornblende because both are dark-coloured; the vesicle fill indicates serpentinisation of the basalt under high-pressure ocean floor conditions; the unconformity is a mid-ocean ridge axial fault scarp',
          ],
          correct: 1,
          explain: "This question integrates igneous petrology (Ch. 5 — Field Methods) with geological history (Ch. 4) and structural geology (Module 2.5). Rock identification: porphyritic texture (large phenocrysts in a fine-grained matrix) + plagioclase + hornblende phenocrysts + grey aphanitic groundmass = porphyritic andesite. Andesite is the fine-grained equivalent of diorite: intermediate composition (SiO₂ ~57–63%), dominated by plagioclase and hornblende. The grey colour and intermediate mineralogy distinguish it from rhyolite (pale, quartz-bearing) and basalt (very dark, pyroxene ± olivine). Porphyritic texture and cooling history: phenocrysts grew in a magma chamber at depth (slow cooling over thousands to hundreds of thousands of years). Eruption rapidly quenched the remaining melt, producing the aphanitic groundmass. This is a two-stage cooling history, common in volcanic arcs. Hornblende as a phenocryst mineral requires moderately water-rich melt — characteristic of subduction-related andesites where the subducting slab releases water into the overlying mantle wedge. Calcite amygdales: vesicles record volatile exsolution on eruption (pressure drop → gas bubble growth → trapping in rapidly-solidifying melt). Calcite filling is secondary — precipitated from circulating groundwater or hydrothermal fluids that percolated through the rock after cooling. Primary magmatic calcite is rare and not expected in andesitic compositions. The unconformity: folded Devonian rocks record an orogenic event (deformation occurred after the Devonian, most likely late Devonian or Carboniferous). Subsequent erosion removed material and created the irregular (~10 m relief) unconformity surface. The volcanic eruption occurred on this eroded surface, placing the eruption after the erosion phase. The sequence: Devonian deposition → later folding/orogeny → erosion → volcanic eruption. This is a classic angular unconformity recording multiple tectonic episodes. Option A misidentifies the rock as granite (plutonic, not volcanic; no porphyritic vs. aphanitic distinction). Option C misidentifies hornblende composition and inverts vesicle origin. Option D misidentifies phenocrysts and misapplies ocean floor geology.",
        },
        // ── Q8: Modules 2.2 + 2.5 ──────────────────────────────────────────
        {
          q: `You measure a 15 m stratigraphic section using a Jacob\'s staff. From the base upward: (i) 3 m conglomerate with sharp erosive base; (ii) 6 m of cross-bedded sandstone fining upward; (iii) 4 m of siltstone with ripple lamination; (iv) 2 m of mudstone with desiccation cracks and root traces. What is the depositional environment of each unit, what facies model does the complete section represent, and how do the contact types (erosive, gradational) support your interpretation?`,
          a: [
            'Unit i = deep-marine turbidite Ta; unit ii = Bouma Tb–Tc; unit iii = pelagic settling Td; unit iv = hemipelagic mud Te; facies model = submarine fan turbidite system; the erosive base is a submarine channel incision surface; desiccation cracks form on the seafloor during tsunamis that briefly expose it',
            'Unit i (conglomerate, erosive base): the coarsest, highest-energy deposit — channel lag or bedload of a high-energy river; the erosive (sharp, incised) base marks the channel scour surface where the river cut into older floodplain deposits during high discharge. Unit ii (cross-bedded sandstone, fining upward): dune migration in the active river channel axis; cross-bedding records unidirectional current flow; the fining-upward trend records decreasing flow velocity as the channel fill or bar migrated. Unit iii (siltstone, ripple lamination): low-energy deposit on bar margin or channel floodway; ripple cross-lamination records weaker unidirectional current; gradational contact with iv reflects gradual energy decrease. Unit iv (mudstone, desiccation cracks, root traces): floodplain — fine-grained overbank sediment from suspension settling during flood events; desiccation cracks record periodic subaerial exposure between floods; root traces record colonisation by land plants. Facies model: fluvial channel-floodplain system — the classic fining-upward fluvial cycle. The erosive base (sharp, incised) marks the beginning of a new channel-cut-and-fill cycle; gradational contacts (ii→iii, iii→iv) record progressive energy decrease as flow waned',
            'Unit i = alluvial fan conglomerate; unit ii = aeolian cross-bedded sandstone; unit iii = lacustrine siltstone; unit iv = playa lake mudstone; facies model = alluvial fan to playa lake transition; the desiccation cracks confirm arid intermontane basin; cross-bedding proves wind transport in unit ii',
            'The section records a marine transgression: conglomerate (beach gravel), sandstone (shoreface), siltstone (offshore transition), mudstone (offshore shelf); desiccation cracks and root traces in the mudstone indicate the shoreline is migrating landward over the mudstone; facies model = retrogradational (transgressive) parasequence',
          ],
          correct: 1,
          explain: "Each element of the section provides multiple overlapping indicators that all point to the same interpretation. Unit i (conglomerate, erosive base): pebble-to-cobble-grade clasts require high-energy transport. The sharp, erosive (incised) base — where the base of the conglomerate digs into underlying material — is the scour surface produced by a river channel eroding into older floodplain deposits during a flood. This base type is one of the most diagnostic features of fluvial channel sands. Unit ii (cross-bedded sandstone, fining upward): large-scale cross-bedding records unidirectional current migration of dunes in the active channel. The fining-upward trend (from coarser at the base of the sandstone to finer at the top) records the progressive decrease in current velocity during channel fill — classic point-bar or channel-fill signature. Unit iii (ripple-laminated siltstone): silt transported by weaker currents on the bar margin or as overbank sheet flow. Current-ripple cross-lamination records continued but lower-energy unidirectional flow. The gradational transition from cross-bedded sandstone (unit ii) below to ripple siltstone (iii) reflects gradually declining energy — consistent with declining flow velocity in a waning flood. Unit iv (mudstone, desiccation cracks, root traces): clay-grade sediment settled from suspension during slow overbank flooding. Desiccation cracks rule out permanent aquatic conditions — the surface dried periodically. Root traces record terrestrial plant colonisation of the stable floodplain surface between floods. These two features together are diagnostic of a floodplain environment. Facies model: the complete fining-upward sequence (conglomerate → sandstone → siltstone → mudstone with desiccation) is the canonical fluvial channel-fill cycle, produced when a river migrates away from a point, abandoning its channel: channel lag at base → active channel dunes → bar margin ripples → floodplain overbank → soil development. Contact interpretation: the erosive base of the conglomerate marks the channel incision (abrupt energy jump); the gradational contacts higher up record the progressive energy decrease as the system transitioned from active channel to floodplain — there is no catastrophic event, just gradual waning of flow. Option A (turbidite) cannot produce desiccation cracks or root traces — these require subaerial exposure, which is impossible in a deep-marine setting. Options C and D cannot explain all features simultaneously.",
        },
        // ── Q9: Modules 2.3 + 2.4 ──────────────────────────────────────────
        {
          q: 'The Permo-Triassic boundary is identified in marine sections by: (1) the mass disappearance of marine invertebrates; (2) a large negative carbon isotope excursion (δ¹³C) in carbonates; (3) the reappearance of microbial carbonates (stromatolites) that had been suppressed for hundreds of millions of years. What does each of these three signals tell you about conditions at and after the extinction, and how are they consistent with the Siberian Traps volcanism as the primary driver?',
          a: [
            'Signal 1 records the impact; signal 2 records cooling from nuclear winter (cold conditions cause δ¹³C to fall); signal 3 records the re-establishment of photosynthesis after impact winter; all consistent with a bolide impact at 252 Ma as the primary driver',
            'Signal 1 (mass extinction): the abrupt disappearance of ~96% of marine species records collapse of marine ecosystem structure. Most victims were calcifying organisms (corals, brachiopods, echinoderms) — groups particularly vulnerable to ocean acidification (CO₂ dissolves in seawater, lowering pH and reducing carbonate ion concentration, making calcification energetically costly or impossible) and to oceanic anoxia (widespread oxygen depletion that suffocates aerobic organisms). Signal 2 (negative δ¹³C excursion): a rapid shift to lighter carbon isotopes records massive injection of isotopically light carbon into the ocean–atmosphere system. Siberian Traps volcanism released CO₂ (magmatic and thermogenic) depleted in ¹³C relative to marine carbonate, and possibly destabilised seafloor methane clathrates (methane is extremely ¹³C-depleted). This carbon pulse caused both global warming and ocean acidification. Signal 3 (stromatolite reappearance): living stromatolites are suppressed in normal marine settings by grazing invertebrates and bioturbating organisms. Their reappearance after the end-Permian extinction records the collapse of the metazoan community that normally suppresses microbial mat growth — a biotic vacuum created by the extinction. All three signals are consistent with Siberian Traps volcanism releasing ~30,000–48,000 Gt of CO₂ and SO₂ over <1 Ma, causing ocean acidification, anoxia, global warming, and eradication of most marine biotic communities',
            'Signal 1 records normal stratigraphic turnover; signal 2 records a change in ocean circulation; signal 3 records the evolution of photosynthetic bacteria for the first time; they are consistent with a mid-ocean ridge volcanism event that cooled the oceans by releasing aerosols',
            'The three signals are inconsistent with each other: signal 1 requires rapid cooling (impact winter); signal 2 requires massive organic carbon burial (positive excursion would indicate warming); signal 3 records ordinary stratigraphic succession; no single mechanism can explain all three',
          ],
          correct: 1,
          explain: "The three signals provide independent but mutually reinforcing lines of evidence for the same catastrophic environmental perturbation. Signal 1 (mass extinction of marine invertebrates): the end-Permian extinction is documented by the disappearance of entire marine groups in sections worldwide. The most affected groups — reef builders (rugose corals, stromatoporoid sponges), filter feeders (brachiopods, bryozoans, crinoids), and carbonate producers (fusulinid foraminifera) — are precisely those most sensitive to acidification and low oxygen. Calcifying organisms require a minimum carbonate saturation state in seawater (Ω > 1) to secrete shells; CO₂-driven acidification reduces Ω dramatically. This is fully consistent with massive CO₂ injection. Signal 2 (negative δ¹³C excursion): the Siberian Traps emitted CO₂ both directly (magmatic degassing, δ¹³C ≈ –5‰) and indirectly by intruding through organic-rich sediments and coal measures of the Tunguska Basin, volatilising isotopically very light thermogenic CO₂ and CH₄. The result was rapid injection of light carbon into the ocean–atmosphere system, recorded as a negative δ¹³C shift in marine carbonates. The magnitude (~–2 to –8‰) and rapidity of the excursion are consistent with Siberian Traps estimates. Signal 3 (stromatolite reappearance): modern stromatolite ecosystems are virtually absent from open-marine settings because grazing gastropods, sea urchins, and fish consume the microbial mats before they can calcify. The end-Permian extinction eliminated most of these grazers and bioturbators. The resulting ecological release allowed microbial communities to build stromatolites that would have been rapidly consumed in a normal marine environment. This 'disaster fauna' indicator — like bloom-forming disaster taxa in general — records not the cause of the extinction but the ecological vacuum that followed. Together, these three signals paint a coherent picture: massive CO₂ and SO₂ injection (Siberian Traps) → ocean acidification and anoxia (kills calcifiers, depletes O₂) → collapse of normal metazoan communities (allows microbial mats) → carbon system perturbation (negative δ¹³C). Option A applies the bolide-impact model incorrectly — there is no confirmed impactor at 252 Ma. Options C and D misinterpret the geochemical signals.",
        },
        // ── Q10: Integration all modules ────────────────────────────────────
        {
          q: 'You are mapping a mountainous terrain and observe five features: (a) folded Ordovician–Silurian sedimentary rocks with well-developed axial planar cleavage; (b) an angular unconformity overlain by flat-lying Carboniferous conglomerates and sandstones; (c) a thrust fault that cuts the Carboniferous strata, placing Ordovician rocks over Carboniferous; (d) a granite pluton intruding the thrust sheet; (e) the granite gives a U-Pb zircon age of 305 Ma. Construct a complete sequence of geological events from oldest to youngest, giving one reason for each inference.',
          a: [
            'Oldest to youngest: (1) Carboniferous deposition; (2) granite intrusion at 305 Ma; (3) folding of Ordovician–Silurian rocks; (4) thrust faulting; (5) erosion and unconformity formation; because the granite intrudes the thrust, the thrust predates the granite, and folding predates thrusting',
            'Oldest to youngest: (1) Deposition of Ordovician–Silurian sediments [law of superposition — these are the oldest rocks described, and they must have been deposited before being deformed]; (2) Folding and cleavage development in the Ordovician–Silurian rocks [the folding and associated axial planar cleavage are ductile deformation structures that must post-date deposition; cleavage formed by regional metamorphism during an orogenic event, most likely late Silurian to Devonian — the Caledonian/Acadian orogeny]; (3) Erosion to form the angular unconformity surface [the angular unconformity below the Carboniferous records erosion that bevelled the tilted, folded Ordovician–Silurian rocks before Carboniferous sediment was deposited]; (4) Deposition of Carboniferous conglomerates and sandstones [these flat-lying sediments rest on the unconformity, so they are younger than the erosion event and the folding that preceded it]; (5) Thrust faulting [the thrust cuts Carboniferous strata — by cross-cutting relationships, the thrust post-dates the Carboniferous deposition]; (6) Granite intrusion at 305 Ma [the granite intrudes the thrust sheet — by cross-cutting relationships, the pluton is younger than the thrust; the U-Pb date of 305 Ma is Late Carboniferous, providing an absolute minimum age for the thrust faulting and a maximum for subsequent events]; (7) Erosion to expose the current landscape [the granite, thrust, and Carboniferous rocks are all now exposed at the surface]',
            'Oldest to youngest: (1) granite intrusion at 305 Ma; (2) folding of Ordovician–Silurian rocks caused by granite emplacement; (3) thrust faulting; (4) Ordovician–Silurian deposition; (5) Carboniferous deposition; (6) angular unconformity formation; because the granite intruded first and caused the deformation of the surrounding rocks',
            'The sequence cannot be determined because relative dating principles only apply to undeformed horizontal strata; structural geology requires absolute dates for all events and the question only provides one date',
          ],
          correct: 1,
          explain: "This is a classical geological history reconstruction problem that requires applying multiple dating principles simultaneously. Event 1 — Ordovician–Silurian deposition: these are the oldest rocks in the description. They were deposited as sediments in the Ordovician and Silurian (485–419 Ma) before any deformation affected them. Law of superposition: sediments must be deposited before they can be folded. Event 2 — Folding and cleavage development: the Ordovician–Silurian rocks are folded with axial planar cleavage. Axial planar cleavage is a ductile deformation fabric formed during regional metamorphism at depth during mountain building. The folding must post-date Ordovician–Silurian deposition (you can't fold rocks before they exist) and pre-date the unconformity (the folded rocks must be eroded before being overlain by flat Carboniferous sediments). The timing is likely late Devonian–Early Carboniferous (Caledonian/Variscan orogeny). Event 3 — Erosion producing the angular unconformity: the bevelled, irregular surface beneath the Carboniferous records a period of erosion after folding. The tilt discordance between the folded Ordovician–Silurian and the flat Carboniferous is the angular unconformity — it can only form after folding (to create the angular discordance) and before Carboniferous deposition. Event 4 — Carboniferous deposition: the flat-lying conglomerates and sandstones overlie the unconformity. By superposition, they are younger than the unconformity surface. Carboniferous = 358.9–298.9 Ma, so deposition is before 298.9 Ma. Event 5 — Thrust faulting: the thrust cuts the Carboniferous strata (cross-cutting relationships — the fault is younger than everything it cuts). The thrust places Ordovician rocks over Carboniferous — consistent with a compressional event after Carboniferous deposition. Event 6 — Granite intrusion at 305 Ma: the granite intrudes the thrust sheet (cross-cutting — younger than the thrust). The U-Pb zircon date of 305 Ma is Late Carboniferous. This provides an absolute age: the granite is 305 Ma, so the thrust must be older than 305 Ma (probably Early to mid-Carboniferous, after Carboniferous deposition began). Event 7 — Erosion to present: the current landscape exposes all these features. Options A and C violate cross-cutting principles in specific ways (A puts folding after Carboniferous deposition; C places the granite before the Ordovician rocks it intrudes through). Option D misunderstands relative dating — all the principles used here (superposition, cross-cutting, original horizontality, angular unconformity) apply fully to deformed sequences.",
        },
      ],
    },
  ],
}

export default geol201Capstone
