import { Leaf, Waves, FlaskConical, Globe } from 'lucide-react'
import { BRAND } from '@/lib/brand'
import type { Lesson } from './types'

const oceanCDR: Lesson = {
  id: 'ocea-201-1-4-3',
  title: 'Ocean-Based Carbon Dioxide Removal',
  track: 'oce',
  trackName: 'Marine Chemistry',
  level: 'Intermediate',
  duration: '16 min',
  xpReward: 200,
  description: 'The ocean already absorbs roughly 25–30% of all anthropogenic CO₂ emissions, making it the largest active carbon sink on Earth. Proposals to deliberately enhance this uptake — through iron fertilisation, ocean alkalinity enhancement, blue carbon restoration, and seaweed cultivation — promise large-scale carbon removal but face profound questions of efficacy, permanence, ecosystem risk, and governance that are only beginning to be addressed.',
  sources: [
    { org: 'IPCC',                  title: 'IPCC AR6 WG3 — Carbon Dioxide Removal',                       url: 'https://www.ipcc.ch/report/ar6/wg3/' },
    { org: 'NOAA',                  title: 'NOAA Global Ocean Carbon and Repeat Hydrography',              url: 'https://www.nodc.noaa.gov/' },
    { org: 'Nature Climate Change',  title: 'Gattuso et al. — Contrasting futures for ocean and society',  url: 'https://www.nature.com/nclimate/' },
    { org: 'Copernicus',            title: 'Copernicus Marine Service — Ocean Carbon Monitoring',           url: 'https://marine.copernicus.eu/' },
    { org: 'ICES',                  title: 'ICES Workshop on Ocean Carbon Dioxide Removal',                url: 'https://www.ices.dk/' },
  ],
  sections: [
    {
      type: 'intro',
      title: `Turning the ocean\'s natural sink into a deliberate tool`,
      body: `The global ocean currently absorbs approximately **25–30% of all anthropogenic CO₂ emissions** — roughly 2.5–3 Pg C per year — making it the planet's largest active carbon sink. This uptake occurs through two primary mechanisms: the **solubility pump** (CO₂ dissolving in cold surface water and sinking to depth as seawater circulates) and the **biological pump** (phytoplankton fixing CO₂ through photosynthesis; when they die and sink, their carbon is exported to depth, some of it sequestered for centuries). As atmospheric CO₂ continues to rise, these natural mechanisms are being overwhelmed, and the partial pressure gradient driving CO₂ into the ocean is increasing — but so are the negative consequences for the ocean itself (acidification, deoxygenation, warming). The question driving the emerging field of **ocean-based carbon dioxide removal (CDR)** is: can we deliberately and safely enhance the ocean's carbon uptake beyond what occurs naturally, and at what scale, cost, and risk?

**Iron fertilisation** is the oldest and best-studied ocean CDR approach. Large areas of the Southern Ocean, equatorial Pacific, and sub-Arctic Pacific are "high-nutrient, low-chlorophyll" (HNLC) regions where abundant macro-nutrients (nitrate, phosphate, silicate) are present but phytoplankton productivity is limited by the vanishingly small supply of **dissolved iron** — a micro-nutrient required for photosynthesis and nitrogen fixation. The "iron hypothesis," proposed by John Martin in 1990, suggested that fertilising these regions with iron dust could stimulate massive phytoplankton blooms that would fix atmospheric CO₂ and, when they sank, sequester it in the deep ocean. Thirteen open-ocean iron fertilisation experiments, from IronEx I (1993) in the equatorial Pacific to LOHAFEX (2009) in the Southern Ocean, demonstrated that iron additions do reliably produce phytoplankton blooms — but revealed profound uncertainties about the fraction of bloom carbon that sinks below the permanent thermocline and is sequestered on centennial timescales. In LOHAFEX, the bloom was rapidly grazed by copepods; very little carbon was exported. The consensus view is that iron fertilisation may sequester some carbon, but the efficiency is highly variable, difficult to verify, and potentially much lower than early estimates suggested.

**Ocean alkalinity enhancement (OAE)** is a more recently prominent CDR approach based on different chemistry. The ocean\'s capacity to absorb CO₂ is directly related to its **alkalinity** — the buffering capacity of seawater, essentially the concentration of base ions (primarily bicarbonate and carbonate) that can neutralise acid (including carbonic acid from dissolved CO₂). By adding alkaline minerals — calcium hydroxide (Ca(OH)₂, "lime"), magnesium hydroxide (Mg(OH)₂), or natural silicate rocks such as olivine (Mg₂SiO₄) — to seawater, alkalinity is raised, shifting the seawater carbonate equilibrium to favour greater CO₂ uptake from the atmosphere. Unlike iron fertilisation, OAE works through **inorganic chemistry** rather than biology, potentially offering more predictable and verifiable carbon removal. However, OAE at scale would require enormous quantities of mineral feedstock (potentially billions of tonnes per year), with uncertain ecological impacts from pH shifts, trace metal release, and changes to carbonate saturation affecting calcifying organisms.

**Coastal blue carbon ecosystems** — mangroves, seagrasses, and salt marshes — are among the most carbon-dense ecosystems on Earth, sequestering carbon in both their above-ground biomass and, critically, in the organic-rich sediments they build over millennia. These ecosystems collectively cover approximately 49 million hectares and are estimated to sequester **0.2–0.5 Pg C per year** in total. Per unit area, blue carbon ecosystems sequester carbon at rates 10–50 times greater than terrestrial forests because their anaerobic waterlogged sediments prevent microbial decomposition, allowing organic carbon to accumulate for centuries. Globally, however, they are being destroyed at alarming rates — an estimated 0.5–3% of global blue carbon ecosystems are lost annually, releasing the sequestered carbon they held and eliminating future uptake. Protecting and restoring these ecosystems is therefore both a conservation imperative and a CDR strategy with the best-understood co-benefits.

The governance landscape for ocean CDR is embryonic. The **London Protocol** (governing marine pollution) was amended in 2013 to permit legitimate scientific research into marine iron fertilisation while restricting commercial operations, but the regulatory framework for OAE, seaweed cultivation, and other approaches remains largely absent. Scientific bodies including the High Level Panel for a Sustainable Ocean Economy and the National Academies of Sciences (USA) have called for accelerated research, improved monitoring frameworks, and international governance development before large-scale deployment of any ocean CDR approach. The concern is not merely ecological risk — it is the possibility that the mere existence of large-scale ocean CDR as a policy option will reduce the urgency of emissions reductions, what the IPCC terms **moral hazard**.`,
      keyTerms: [
        {
          term: 'biological pump',
          def: 'The suite of biological processes by which dissolved inorganic carbon (CO₂) is fixed by phytoplankton into organic matter in the sunlit surface ocean, then exported to depth through sinking of dead cells, fecal pellets, and aggregates. A fraction of this exported carbon reaches depths below the permanent thermocline (>1,000 m) where it is effectively sequestered for centuries to millennia. The biological pump exports approximately 5–12 Pg C/yr to the deep ocean globally, making it a critical component of the carbon cycle.',
        },
        {
          term: 'ocean alkalinity enhancement (OAE)',
          def: `A CDR approach that adds alkaline minerals (calcium hydroxide, olivine, basalt) to seawater to raise its alkalinity (bicarbonate and carbonate ion concentrations), increasing the seawater\'s capacity to absorb CO₂ from the atmosphere through the carbonate equilibrium reaction: CO₂ + H₂O + CO₃²⁻ → 2HCO₃⁻. OAE effectively reverses ocean acidification locally while increasing CO₂ uptake capacity. Large-scale deployment would require billions of tonnes of mineral feedstock annually and carries risks of altering marine carbonate chemistry affecting calcifying organisms.`,
        },
        {
          term: 'iron fertilisation',
          def: 'A CDR approach based on adding dissolved iron to high-nutrient, low-chlorophyll (HNLC) ocean regions to stimulate phytoplankton blooms that fix CO₂; when the bloom sinks, its carbon may be sequestered in deep water. Proposed by John Martin (1990) based on observations that iron is the limiting nutrient in HNLC regions. Thirteen open-ocean experiments (IronEx, SOIREE, LOHAFEX, etc.) confirmed that iron additions produce blooms but revealed high uncertainty about the fraction of carbon that is efficiently exported and permanently sequestered.',
        },
        {
          term: 'blue carbon',
          def: 'The carbon captured and stored in coastal and marine ecosystems — primarily mangroves, seagrasses, and salt marshes. Blue carbon ecosystems sequester carbon in both biomass and, particularly, in the anaerobic sediments they build, which can accumulate organic carbon for millennia. Per unit area, blue carbon habitats sequester carbon 10–50× faster than terrestrial forests. Global blue carbon ecosystems are estimated to sequester 0.2–0.5 Pg C/yr, but 0.5–3% of global stocks are destroyed annually, converting blue carbon sinks to sources.',
        },
        {
          term: 'HNLC region',
          def: 'High-Nutrient, Low-Chlorophyll ocean region — an area where macronutrients (nitrate, phosphate, silicate) are available in abundance but phytoplankton biomass and productivity are persistently low because dissolved iron — required for key photosynthetic and nitrogen-fixing enzymes — is vanishingly scarce. HNLC regions include the Southern Ocean, the equatorial Pacific, and the sub-Arctic Pacific. Iron fertilisation CDR proposals target these regions specifically because the limiting-nutrient bottleneck theoretically allows small iron additions to unlock large phytoplankton responses.',
        },
        {
          term: 'permanence',
          def: 'In CDR accounting, the duration for which removed carbon remains out of the atmosphere. For ocean CDR, permanence depends critically on where in the ocean the carbon is sequestered: carbon dissolved as dissolved inorganic carbon (DIC) in the surface mixed layer cycles back to the atmosphere in weeks to months; carbon exported below the permanent thermocline (~1,000 m) is sequestered for centuries to millennia as deep water circulates through the global overturning circulation. True permanence requires deep sequestration, which is the major uncertainty in biological pump-based approaches like iron fertilisation.',
        },
      ],
    },
    {
      type: 'concept',
      title: 'Iron fertilisation and ocean alkalinity enhancement',
      body: `The two most extensively researched open-ocean CDR approaches — iron fertilisation and ocean alkalinity enhancement — operate through fundamentally different mechanisms and carry different risk profiles, scalability constraints, and verification challenges. Iron fertilisation works through the biology of the ocean, attempting to accelerate the biological pump by removing a nutrient bottleneck. OAE works through the chemistry, directly manipulating the carbonate equilibrium to increase CO₂ uptake capacity. Both face the fundamental challenge of **additionality**: demonstrating that the CDR achieved is genuinely additional to what would have occurred without the intervention, which is particularly difficult in the dynamic, poorly-observed open ocean. The monitoring, reporting, and verification (MRV) challenge — how to reliably quantify how much CO₂ has actually been removed and will remain sequestered — is arguably greater for ocean CDR than for any other CDR approach.`,
      cards: [
        {
          name: 'Iron Fertilisation: Experiments and Limitations',
          icon: FlaskConical,
          color: BRAND.gold,
          desc: 'Thirteen open-ocean iron fertilisation experiments (1993–2009) confirmed the iron hypothesis: adding dissolved iron to HNLC waters reliably stimulates phytoplankton blooms. But the key question — what fraction of bloom carbon sinks below the permanent thermocline? — remained largely unanswered. In LOHAFEX (2009, Southern Ocean), the bloom was almost entirely grazed by amphipods; carbon export was minimal. In SOIREE (1999, Southern Ocean), some export was detected but much less than biomass suggested. The fundamental problem is that most phytoplankton carbon cycles back to CO₂ in the surface ocean through respiration and grazing — only the small, poorly quantified fraction that sinks below ~1,000 m achieves durable sequestration.',
          examples: 'IronEx I (1993) & IronEx II (1995): equatorial Pacific; confirmed iron limitation · SOIREE (1999): Southern Ocean; chlorophyll ×14 increase; limited export detected · LOHAFEX (2009): Southern Ocean; bloom grazed by copepods; minimal carbon export · Maximum theoretical potential: ~1 Pg C/yr in Southern Ocean (highly uncertain) · Estimated actual efficiency: <10% of bloom carbon exported below 1,000 m in most experiments',
        },
        {
          name: 'Ocean Alkalinity Enhancement (OAE)',
          icon: Waves,
          color: BRAND.accent,
          desc: `OAE raises seawater alkalinity by adding calcium hydroxide (Ca(OH)₂), magnesium hydroxide, or ground silicate minerals (olivine, basalt) to the ocean, shifting the carbonate equilibrium: CO₂ + H₂O + CO₃²⁻ → 2HCO₃⁻. This reaction consumes CO₂ while producing bicarbonate, increasing the ocean\'s CO₂ uptake capacity. OAE is chemistry-driven rather than biology-dependent, offering potentially more predictable and verifiable CDR than iron fertilisation. It also counters ocean acidification locally, potentially offering co-benefits for calcifying ecosystems. The main challenges are the enormous mineral feedstock requirements (potentially Gt/yr), energy cost of mineral processing, transport logistics, and uncertain ecosystem effects of pH changes and trace metal release from olivine.`,
          examples: 'Calcium hydroxide (lime): dissolves rapidly, fast alkalinity delivery; energy-intensive to produce from limestone · Olivine (Mg₂SiO₄): slower dissolution, releases silica (potentially beneficial for diatoms) and traces of Ni; coastal spreading or ship-board dispersal proposed · Theoretical potential: 1–10 Pg C/yr (highly model-dependent) · Monitoring challenge: seawater carbonate chemistry must be measured precisely across vast areas to verify CDR · Field trials: first small-scale trials in 2021–2023 in US, UK, and European coastal waters',
        },
      ],
    },
    {
      type: 'concept',
      title: 'Blue carbon ecosystems and seaweed CDR',
      body: `While open-ocean CDR approaches require deliberate intervention in the physical and chemical dynamics of the ocean, coastal blue carbon ecosystems represent an existing, naturally operating carbon sink whose protection and restoration is one of the most cost-effective, co-benefit-rich, and immediately actionable CDR strategies available. Seaweed cultivation as a CDR approach occupies an intermediate position — it uses existing biological mechanisms (photosynthesis and carbon fixation) but requires active management and raises questions about ecosystem effects, carbon permanence, and the difficulty of sinking harvested biomass to depth for long-term sequestration.`,
      cards: [
        {
          name: 'Blue Carbon: Mangroves, Seagrasses, Salt Marshes',
          icon: Leaf,
          color: BRAND.jade,
          desc: 'Mangroves, seagrasses, and salt marshes form the "blue carbon" trinity. They sequester CO₂ in biomass but especially in sediments — the anaerobic, waterlogged conditions below these ecosystems prevent microbial decomposition of organic matter, allowing carbon to accumulate for thousands of years. Per hectare, these ecosystems sequester carbon at rates 10–50× greater than tropical forests. Global blue carbon stocks in sediments are estimated at 10–33 Pg C. Protection prevents the release of this stored carbon (a lost sink becomes a source) and restoration rebuilds this capacity over decades.',
          examples: 'Mangroves: sequester 6–8 Mg C/ha/yr (vs. tropical forests ~2–4 Mg C/ha/yr) · Seagrasses: store up to 83,000 Mg C/ha in sediments · Salt marshes: sediment carbon accumulation rates 0.4–2 Mg C/ha/yr · Global blue carbon sequestration: 0.2–0.5 Pg C/yr · Global loss rate: 0.5–3%/yr; accelerated by coastal development, aquaculture, pollution · Restored mangroves reach 80% of natural carbon sequestration within ~25 years',
        },
        {
          name: 'Seaweed Cultivation as CDR',
          icon: Globe,
          color: BRAND.amethyst,
          desc: 'Macroalgae (seaweed) grow rapidly, fixing CO₂ through photosynthesis without requiring freshwater, arable land, or added nutrients in nutrient-rich coastal and open-ocean upwelling zones. Proposals range from coastal seaweed farms (for biomass, food, or biofuel) to open-ocean seaweed cultivation with deliberate sinking of biomass to the deep ocean for sequestration. The fundamental carbon permanence challenge: unless harvested seaweed biomass reaches depths below the permanent thermocline (~1,000 m), the carbon will be remineralised and returned to the atmosphere within months to years. The ecological effects of large-scale open-ocean seaweed cultivation — on light, nutrients, dissolved oxygen, and local food webs — are poorly understood.',
          examples: 'Global seaweed aquaculture: ~34 Mt wet weight/yr (2020), mostly coastal Asia · CDR potential: modelled estimates range from negligible to 1.5 Pg C/yr (high uncertainty) · Energy cost of sinking: major logistical challenge; natural sinking unreliable · Co-benefits: nutrient extraction (reducing eutrophication), local deoxygenation, food/feed production · Governance gap: no international framework for open-ocean seaweed CDR',
        },
      ],
    },
    {
      type: 'visualization',
      title: 'Ocean CDR approaches: mechanisms, scales, and governance',
      body: `Ocean-based CDR encompasses approaches that work through very different mechanisms — from manipulating ocean chemistry (OAE) to exploiting biological nutrient bottlenecks (iron fertilisation) to protecting and expanding coastal carbon sinks (blue carbon). Each approach sits at a different point on the spectrum of scientific readiness, potential scale, ecological risk, and governance maturity. Follow the pathways to understand how each approach sequesters carbon and what barriers must be overcome before large-scale deployment.`,
      interaction: {
        type: 'flow-simulator' as const,
        description: 'Four ocean CDR pathways from mechanism to sequestration, and the cross-cutting governance and monitoring challenges',
        nodes: [
          {
            id: 'ocean-baseline',
            label: 'Ocean natural CO₂ uptake baseline',
            description: `The global ocean currently absorbs approximately 2.5–3 Pg C per year from the atmosphere — roughly 25–30% of all anthropogenic CO₂ emissions. This uptake is driven by the partial pressure gradient between the CO₂-rich atmosphere and ocean surface water: wherever atmospheric pCO₂ exceeds oceanic pCO₂, net CO₂ uptake occurs. The ocean\'s carbon uptake is distributed unevenly: cold high-latitude waters (particularly the Southern Ocean) are the dominant sinks because cold water holds more dissolved gas; tropical regions are often net CO₂ sources because warm surface water degasses. As atmospheric CO₂ rises, the driving partial pressure gradient increases, pulling more CO₂ into the ocean — but also increasing acidification. Ocean CDR aims to enhance uptake beyond this natural baseline. Demonstrating additionality — that the CDR is genuinely additional to what would occur without intervention — is the central verification challenge.`,
            color: BRAND.accent,
          },
          {
            id: 'iron-fertilisation',
            label: 'Iron fertilisation (biological pump enhancement)',
            description: 'Iron fertilisation adds dissolved iron sulfate or other iron compounds to HNLC ocean regions, removing the iron-limitation bottleneck on phytoplankton growth. The resulting phytoplankton bloom fixes CO₂ through photosynthesis (net drawdown of surface ocean pCO₂, which then draws down atmospheric CO₂ across the air-sea interface). When the bloom senesces and organisms die, their carbon-rich organic matter sinks (the biological pump). Carbon that sinks below the permanent thermocline (~1,000 m) is sequestered for centuries to millennia. Carbon remineralised above this depth returns to the surface within years to decades. The Achilles heel of iron fertilisation is that grazing by zooplankton and microbial loop recycling means that only a small fraction — often <10% — of bloom carbon is exported below the sequestration horizon. After 13 experiments spanning 1993–2009 (IronEx, LOHAFEX, SOIREE, etc.), the carbon sequestration efficiency remains highly uncertain and is likely much lower than initially hoped.',
            color: BRAND.jade,
          },
          {
            id: 'oae',
            label: 'Ocean alkalinity enhancement (carbonate chemistry)',
            description: 'OAE adds alkaline materials to seawater to increase its total alkalinity (TA) — the buffering capacity provided by bicarbonate (HCO₃⁻) and carbonate (CO₃²⁻) ions. Raising TA shifts the ocean carbonate equilibrium, enabling the ocean to absorb more CO₂ from the atmosphere while converting it to bicarbonate ions: CO₂ + H₂O + CO₃²⁻ → 2HCO₃⁻. Unlike biological pump approaches, OAE sequesters carbon as dissolved inorganic carbon (DIC) in the form of bicarbonate — a highly stable dissolved species. The added alkalinity and the CO₂ removed from the atmosphere are both proportional to the amount of alkaline material dissolved. Primary alkalinity sources under investigation include calcium hydroxide (lime — Ca(OH)₂), magnesium hydroxide, and ground silicate rocks (olivine, basalt). Key challenges: the scale of mineral feedstock required (potentially Gt/yr for Pg-scale CDR), energy costs of mining and processing, transport logistics, and potential ecological effects of localised pH increases and trace element release.',
            color: BRAND.gold,
          },
          {
            id: 'blue-carbon',
            label: 'Blue carbon: coastal ecosystem protection and restoration',
            description: 'Mangroves, seagrasses, and salt marshes are coastal wetland ecosystems that accumulate carbon in organic-rich, anaerobic sediments over millennia. Unlike most terrestrial carbon sinks, blue carbon ecosystems sequester carbon primarily in sediments rather than biomass — carbon that is protected from microbial decomposition by waterlogged, oxygen-free conditions and can persist for thousands of years. Protecting existing blue carbon ecosystems prevents the release of their stored carbon (which would otherwise be emitted within years of disturbance as CO₂ and methane) and preserves ongoing annual carbon accretion. Restoration of degraded mangrove and seagrass habitats rebuilds both the carbon sink function and associated co-benefits: fisheries nursery habitat, coastal protection, water quality improvement, and biodiversity. Global blue carbon sequestration from all coastal wetlands is estimated at 0.2–0.5 Pg C/yr. Unlike open-ocean CDR approaches, blue carbon methodologies have relatively mature monitoring frameworks (e.g., Verified Carbon Standard, Gold Standard) and can be measured at plot scale using established soil carbon sampling methods.',
            color: BRAND.coral,
          },
          {
            id: 'governance',
            label: 'Governance, monitoring, and moral hazard',
            description: 'Ocean CDR faces a governance landscape that is poorly equipped for the scale and novelty of the challenge. The London Protocol (1996, governing marine dumping) was amended in 2013 to explicitly permit legitimate scientific research on marine geoengineering (including iron fertilisation) while restricting commercial operations, but coverage of OAE, seaweed CDR, and other approaches is unclear or absent. UNCLOS (the Law of the Sea Convention) provides a broad framework for marine environmental protection but lacks specific provisions for CDR. National jurisdictions govern coastal blue carbon, but open-ocean interventions in international waters fall into regulatory grey zones. Monitoring, reporting, and verification (MRV) of ocean CDR is technically demanding: demonstrating that a pCO₂ drawdown in a treated ocean region is caused by the intervention (and not natural variability) requires sophisticated statistical designs and high-density ocean carbon measurements. The moral hazard concern — that deploying or planning large-scale ocean CDR may reduce political will to cut emissions — is frequently raised by climate ethicists and some IPCC authors, though others argue that CDR is essential alongside mitigation at the scale required to stay within 1.5–2°C targets.',
            color: BRAND.amethyst,
          },
        ],
        edges: [
          { from: 'ocean-baseline',    to: 'iron-fertilisation', label: 'fertilise HNLC regions to stimulate biological pump beyond natural rate' },
          { from: 'ocean-baseline',    to: 'oae',                label: 'add alkalinity to raise carbonate buffering and CO₂ uptake capacity' },
          { from: 'ocean-baseline',    to: 'blue-carbon',        label: 'protect and restore coastal wetlands sequestering 0.2–0.5 Pg C/yr' },
          { from: 'iron-fertilisation', to: 'governance',        label: 'London Protocol 2013 amendment governs field research; commercial restricted' },
          { from: 'oae',               to: 'governance',         label: 'no international regulatory framework; national pilot permits ad hoc' },
          { from: 'blue-carbon',       to: 'governance',         label: 'most mature governance and MRV frameworks among ocean CDR approaches' },
        ],
      },
    },
    {
      type: 'quiz',
      questions: [
        {
          q: 'What fraction of anthropogenic CO₂ emissions does the global ocean currently absorb, and through what two primary mechanisms?',
          a: [
            'The ocean absorbs approximately 5–7% of anthropogenic CO₂ emissions through the thermohaline circulation alone; the deep ocean acts as a passive reservoir that slowly fills with atmospheric CO₂ via a process called "carbon sedimentation" in which dissolved CO₂ forms carbonate minerals that sink to the seafloor',
            'The ocean absorbs approximately 50% of anthropogenic CO₂ through the combined efficiency of coral reef calcification (which incorporates CO₂ into calcium carbonate skeletons) and seagrass photosynthesis; without these biological mechanisms the ocean would not be a net carbon sink',
            'The ocean absorbs approximately 25–30% of anthropogenic CO₂ emissions through two primary mechanisms: the solubility pump (CO₂ dissolving in cold high-latitude surface water and sinking to depth as dense water masses form) and the biological pump (phytoplankton fixing CO₂ through photosynthesis, with a fraction of the resulting organic carbon exported to depth when organisms sink and die)',
            'The ocean absorbs approximately 25–30% of anthropogenic CO₂ but solely through the biological pump; the solubility pump is a theoretical construct that does not contribute significantly to real-world carbon uptake because the timescale of thermohaline circulation (>1,000 years) is too slow to respond to anthropogenic emissions occurring on decadal timescales',
          ],
          correct: 2,
          explain: 'Option A dramatically underestimates ocean uptake (5–7% vs. the well-established 25–30%) and mischaracterises the mechanism: "carbon sedimentation" as described does not occur; the ocean absorbs CO₂ as dissolved inorganic carbon, not as sinking carbonate minerals from the water column. Option B overestimates ocean uptake (50% vs. 25–30%) and misidentifies the dominant mechanisms: coral calcification actually releases CO₂ in the short term (CaCO₃ formation increases seawater acidity and outgasses CO₂), and seagrass is only a minor contributor globally. Option D correctly identifies the approximate uptake fraction but incorrectly dismisses the solubility pump; the solubility pump operates on air-sea gas exchange timescales (days to months), not thermohaline circulation timescales — it refers to the cooling and sinking of CO₂-saturated surface water in regions of deep water formation (particularly the Southern Ocean and North Atlantic), not to the millennial overturning of the deep ocean. The correct answer is C: the ocean absorbs approximately 2.5–3 Pg C/yr, representing roughly 25–30% of all anthropogenic CO₂ emissions (IPCC AR6, Global Carbon Project). The solubility pump operates through the temperature- and salinity-dependent solubility of CO₂: cold surface water (particularly in the Southern Ocean and North Atlantic) absorbs more CO₂ from the atmosphere, then sinks as dense water masses (Antarctic Bottom Water, North Atlantic Deep Water), carrying dissolved CO₂ to depth. The biological pump operates through photosynthesis: phytoplankton fix dissolved CO₂ into organic matter; when organisms die, their remains sink, exporting 5–12 Pg C/yr to depth, of which perhaps 0.1–0.5 Pg C/yr is sequestered below the permanent thermocline on century+ timescales.',
        },
        {
          q: 'What was the key finding of the LOHAFEX iron fertilisation experiment, and what does it reveal about the limitations of iron fertilisation as a CDR strategy?',
          a: [
            'LOHAFEX demonstrated that iron fertilisation in the Southern Ocean produces phytoplankton blooms that export more than 80% of bloom carbon below the permanent thermocline, confirming that iron fertilisation is an efficient and scalable CDR approach capable of sequestering 1–2 Pg C/yr if deployed across all HNLC regions',
            'LOHAFEX demonstrated that iron additions to HNLC waters do not produce phytoplankton blooms because the Southern Ocean is not actually iron-limited; the experiment found that silicate was the limiting nutrient, and that the absence of bloom formation means no carbon export occurred, entirely disproving the iron hypothesis',
            'LOHAFEX demonstrated that while iron additions did stimulate a phytoplankton bloom, the bloom was almost entirely grazed by mesozooplankton (amphipods), resulting in minimal carbon export to depth; this highlighted the fundamental problem that the efficiency of biological pump carbon export is controlled by the food web structure, not just nutrient availability',
            'LOHAFEX found that iron fertilisation warms the ocean surface because the increased phytoplankton biomass absorbs more solar radiation, creating a positive feedback that outweighs any CDR benefit; the experiment was terminated early because of regulatory concerns about oceanic warming in the Southern Ocean',
          ],
          correct: 2,
          explain: 'Option A overstates the export efficiency dramatically — no iron fertilisation experiment has demonstrated >80% export efficiency; the consistent finding across all 13 experiments is that the fraction of bloom carbon exported below the permanent thermocline is highly variable and generally small. Option B mischaracterises LOHAFEX: the experiment did produce a phytoplankton bloom — it did not fail to stimulate growth — and it did not disprove the iron hypothesis; the iron hypothesis (that iron is the limiting nutrient in HNLC waters) was confirmed by the bloom itself. The experiment operated in a silicate-limited region where diatoms were disadvantaged, which influenced the grazing dynamics. Option D is factually incorrect — iron fertilisation experiments do not significantly warm the surface ocean through phytoplankton light absorption; this was not a finding or concern of LOHAFEX. The correct answer is C: LOHAFEX (2009) was a joint German-Indian experiment that fertilised a 300 km² patch of the Southern Ocean with iron sulfate. A phytoplankton bloom was confirmed to develop, but monitoring of the carbon export using sediment traps and particle flux measurements showed minimal export of bloom carbon to depth. The bloom was grazed almost entirely by amphipods (crustacean zooplankton) before the biomass could sink; the carbon was recycled within the surface ocean rather than exported. This highlighted the central limitation of iron fertilisation as CDR: even when blooms are successfully stimulated, the food web determines whether bloom carbon is exported (through the biological pump) or recycled (by the microbial loop and grazing). In diatom-dominated blooms (which produce silica frustules that ballast sinking), export efficiency is higher; in flagellate-dominated blooms (favoured in low-silicate conditions), grazing dominates. The fraction of bloom carbon that achieves permanent (>centuries) sequestration by sinking below the permanent thermocline is the critical and uncertain quantity.',
        },
        {
          q: `How does ocean alkalinity enhancement (OAE) increase the ocean\'s CO₂ uptake capacity through carbonate chemistry?`,
          a: [
            'OAE increases CO₂ uptake by adding dissolved iron to seawater, which catalyses the conversion of CO₂ to bicarbonate ions through a Fenton reaction; the produced bicarbonate then sinks to form carbonate minerals on the seafloor, permanently sequestering the carbon removed from the atmosphere',
            'OAE works by adding acidic compounds to reduce seawater pH, which shifts the carbonate equilibrium to favour greater CO₂ dissolution from the atmosphere; as CO₂ dissolves, it forms carbonic acid, which is then neutralised by the added acid in a two-step process that permanently removes CO₂ from both the atmosphere and the seawater',
            'OAE increases the ocean\'s CO₂ uptake capacity by adding alkaline materials (e.g., calcium hydroxide, olivine) to seawater, raising its total alkalinity (bicarbonate and carbonate ion concentration); the higher alkalinity shifts the carbonate equilibrium (CO₂ + H₂O + CO₃²⁻ → 2HCO₃⁻), enabling more CO₂ from the atmosphere to dissolve and be stored as bicarbonate ions — a stable dissolved form that does not readily return to the atmosphere',
            'OAE adds calcium hydroxide to seawater, which reacts directly with dissolved CO₂ to form calcium carbonate (limestone) particles that immediately precipitate out of the water column and sink to the seafloor; the CO₂ is permanently sequestered by this rapid precipitation reaction, which also whitens the ocean surface and increases its albedo, providing additional cooling',
          ],
          correct: 2,
          explain: 'Option A describes iron fertilisation (through a different and incorrect chemical mechanism) rather than OAE; dissolved iron does not catalyse CO₂ to bicarbonate conversion through Fenton reactions. Option B is chemically incorrect: OAE works by raising pH (adding alkalinity), not by lowering it; CO₂ dissolution in seawater forms carbonic acid (H₂CO₃), which dissociates to produce H⁺ ions — adding acid would not increase CO₂ uptake, it would reduce alkalinity and actually decrease uptake capacity. Option D partially describes the correct reactants but misrepresents the product and mechanism: adding Ca(OH)₂ to seawater raises pH and alkalinity; at typical ocean pH (7.9–8.1), calcium carbonate (CaCO₃) precipitation is possible in very high alkalinity scenarios but is not the primary CDR mechanism, and spontaneous precipitation would actually consume alkalinity and reduce the CDR effect. The correct answer is C: OAE is based on well-established carbonate chemistry. Seawater alkalinity is the capacity to buffer against acidification, dominated by bicarbonate (HCO₃⁻) and carbonate (CO₃²⁻) ions. When alkaline materials are added and dissolve, they increase the concentration of these base ions, raising the pH and alkalinity of seawater. This shifts the carbonate equilibrium: the reaction CO₂ + H₂O + CO₃²⁻ → 2HCO₃⁻ is driven to the right, consuming CO₂ and producing bicarbonate. As dissolved CO₂ (pCO₂) in the surface water decreases below atmospheric levels, the ocean draws down more CO₂ from the atmosphere across the sea-air interface, restoring the equilibrium. The net effect is that for each mole of alkalinity added, approximately 0.8 moles of CO₂ are drawn from the atmosphere and stored as bicarbonate — a stable dissolved species with an effective sequestration timescale matching the residence time of deep ocean water masses (centuries to millennia if the alkalinity-enhanced water subducts).',
        },
        {
          q: 'Why are mangroves, seagrasses, and salt marshes considered particularly effective carbon sinks, and what is the primary threat to their CDR function?',
          a: [
            'Blue carbon ecosystems are effective carbon sinks because they produce high volumes of carbonate shells through calcification; shells sink to the seafloor and form limestone deposits that sequester carbon for geological timescales; the primary threat is ocean acidification, which dissolves these carbonate structures and releases the stored CO₂',
            'Blue carbon ecosystems sequester carbon primarily in their above-ground biomass (leaves, stems, roots), which is exceptionally resistant to decomposition because of high lignin and cellulose content; per unit area, they sequester more carbon than tropical forests because mangrove trees grow faster than any other woody plant; the primary threat is timber harvesting for construction',
            'Blue carbon ecosystems are highly effective carbon sinks because they accumulate organic carbon in anaerobic, waterlogged sediments where microbial decomposition is severely limited by the absence of oxygen; sediment carbon can accumulate for millennia at rates 10–50× greater than terrestrial forests per unit area; the primary threat is coastal development, drainage, aquaculture conversion, and pollution that destroys the anaerobic sediment environment and triggers rapid oxidation and release of stored carbon',
            'Blue carbon ecosystems are effective sinks because the deep root systems of mangroves pump dissolved CO₂ from the water column directly into the ground where it reacts with iron compounds in the sediment to form siderite (FeCO₃) minerals; sequestration is permanent and independent of water table conditions; the primary threat is mangrove wood harvesting for charcoal production',
          ],
          correct: 2,
          explain: 'Option A incorrectly attributes blue carbon sequestration to carbonate shell formation; blue carbon ecosystems (mangroves, seagrasses, salt marshes) are not calcifying organisms, and their carbon sink function operates through organic carbon accumulation in sediments, not inorganic carbonate production. Option B is factually incorrect in describing above-ground biomass as the primary carbon store — in blue carbon ecosystems, sediment organic carbon dwarfs above-ground biomass carbon by an order of magnitude or more. Mangrove biomass carbon is significant, but it is the sediment carbon stock that makes blue carbon globally important. Additionally, mangroves do not grow faster than all other woody plants (tropical tree plantations can grow faster), and the primary threat is not timber harvesting per se. Option D invents a non-existent mechanism: mangrove roots do not pump dissolved CO₂ into the ground to form siderite minerals; this is not a known process in mangrove or seagrass ecosystems. The correct answer is C: the exceptional CDR effectiveness of blue carbon ecosystems derives from the convergence of high organic matter production (driven by abundant sunlight, nutrients, and CO₂ at the land-sea interface) with anaerobic sediment conditions that prevent its decomposition. Waterlogged coastal sediments are depleted of oxygen within millimetres of the surface; in the absence of O₂, microbial decomposition of organic matter is greatly slowed, allowing carbon to accumulate over decades to millennia. Sediment carbon densities in mangroves can exceed 1,000 Mg C/ha, compared with ~150–200 Mg C/ha in most tropical forests. Per unit area, blue carbon sequestration rates are 10–50× higher than terrestrial forests. The primary threat is the destruction of the wetland ecosystem itself: when mangroves are cleared for aquaculture (the dominant driver of mangrove loss globally), drained, or degraded, the anaerobic sediment environment is disrupted. Exposure to oxygen triggers rapid aerobic decomposition of millennia of stored organic carbon, converting these ecosystems from long-term sinks to intense sources of CO₂ and methane. Global estimates suggest that mangrove deforestation releases 0.04–0.2 Pg C/yr in addition to eliminating future sequestration.',
        },
        {
          q: 'What is the "moral hazard" concern in the context of large-scale ocean CDR deployment?',
          a: [
            'The moral hazard of ocean CDR refers to the legal liability risk for governments and corporations that deploy CDR interventions in international waters; if an intervention causes ecological harm to another nation\'s fisheries or ecosystems, the deploying party faces legal action under UNCLOS, creating a financial moral hazard that will deter investment in CDR',
            'Moral hazard in ocean CDR refers to the risk that, if CDR technologies are proven to remove CO₂ efficiently, they will be weaponised by adversarial nations to deliberately manipulate global climate in their favour; the risk of strategic climate manipulation is the primary governance concern driving the London Protocol restrictions on iron fertilisation',
            'Moral hazard in ocean CDR is the concern that the existence or prospect of large-scale CDR options — the narrative that "we can remove CO₂ later" — will reduce the political will and urgency to cut fossil fuel emissions now; if policymakers and the public perceive CDR as a reliable backstop, emissions reductions may be delayed in ways that ultimately lead to greater total warming and more difficult CDR challenges',
            'Moral hazard in ocean CDR refers specifically to the risk that the CDR operations will generate carbon credits that are sold in voluntary carbon markets without adequate verification, defrauding investors and buyers; it is a purely financial term with no relevance to climate policy or emissions reductions urgency',
          ],
          correct: 2,
          explain: 'Option A describes a real legal and governance challenge (liability under UNCLOS) but conflates "moral hazard" with liability risk; moral hazard is a specific term from economics and ethics referring to the change in behaviour that arises when one party is insulated from the consequences of risk-taking. Option B describes the concern about weaponisation of climate manipulation (a legitimate governance concern sometimes called "climate conflict" or "geopolitical risk"), but this is not what the term "moral hazard" refers to in the ocean CDR literature; the London Protocol restrictions on iron fertilisation are primarily about ecological risk and governance gaps, not weaponisation prevention. Option D describes a real concern about carbon market integrity (sometimes called "carbon credit fraud" or "additionality failure" in carbon markets), but this is a narrower financial term that is not the primary moral hazard concern raised in the IPCC and climate policy literature regarding CDR. The correct answer is C: in the ocean CDR literature (and CDR literature more broadly), "moral hazard" refers to the risk that the promise of future carbon removal creates a justification for delaying present emissions reductions. The term comes from insurance economics: when someone is insured against a risk, they may take more risks than they otherwise would. Applied to CDR: if there is a belief — even if premature or overconfident — that large-scale CDR will be available to compensate for continued emissions, the political pressure to decarbonise rapidly may be reduced. IPCC AR6 explicitly flags this concern: CDR is considered essential in most scenarios to stay within 1.5–2°C, but overreliance on speculative future CDR in integrated assessment models can allow scenarios to show excessive near-term emissions followed by heavy CDR drawdown — a "bet" on technologies that may not be available at scale. Peer-reviewed literature on ocean CDR governance (including papers by Gattuso, Boyd, and Strong) consistently identifies moral hazard as one of the primary ethical and policy concerns alongside ecological risk.',
        },
      ],
    },
  ],
}

export default oceanCDR
