import { Thermometer, Globe, TrendingUp, AlertTriangle } from 'lucide-react'
import { BRAND } from '@/lib/brand'
import type { Lesson } from './types'

const futureOceanProjections: Lesson = {
  id: 'ocea-201-1-4-4',
  title: 'Future Ocean Projections',
  track: 'oce',
  trackName: 'Marine Chemistry',
  level: 'Intermediate',
  duration: '16 min',
  xpReward: 200,
  description: 'IPCC AR6 projects an ocean that is hotter, more acidic, higher, and lower in oxygen by 2100 — with the magnitude of each change scaling steeply with the emissions pathway chosen. From tipping points in coral reef systems and the Atlantic Meridional Overturning Circulation to the simultaneous "triple threat" of marine heat waves, deoxygenation, and acidification hitting the same ecosystem, the future ocean is being shaped by decisions made in the present decade.',
  sources: [
    { org: 'IPCC',                  title: 'IPCC AR6 WGI Chapter 9 — Ocean, Cryosphere and Sea Level', url: 'https://www.ipcc.ch/report/ar6/wg1/' },
    { org: 'Copernicus',            title: 'Copernicus C3S — Global Ocean Heat Content and Sea Level',   url: 'https://climate.copernicus.eu/' },
    { org: 'NOAA',                  title: 'NOAA Ocean Climate Laboratory — Future Projections',         url: 'https://www.ncei.noaa.gov/' },
    { org: 'Nature Climate Change',  title: 'Bindoff et al. — Changing Ocean, Marine Ecosystems',        url: 'https://www.nature.com/nclimate/' },
    { org: 'NASA',                  title: 'NASA Sea Level Change Portal — Projections and Observations', url: 'https://sealevel.nasa.gov/' },
  ],
  sections: [
    {
      type: 'intro',
      title: 'The ocean in 2100 — a portrait of diverging futures',
      body: `The future of the ocean is not singular — it branches sharply depending on the trajectory of greenhouse gas emissions over the coming decades. IPCC AR6 (2021) organises these trajectories through **Shared Socioeconomic Pathways (SSPs)**: from SSP1-1.9 and SSP1-2.6 (strong mitigation, limiting warming to ~1.5–2°C by 2100) through SSP2-4.5 (intermediate) to SSP3-7.0 and SSP5-8.5 (high emissions, warming reaching 3–5°C by 2100). For every key ocean variable — temperature, pH, dissolved oxygen, sea level, and extreme event frequency — the spread between low- and high-emissions futures is enormous. The choices made in the 2020s and 2030s will determine whether the ocean in 2100 is damaged but recoverable or fundamentally restructured for millennia.

**Ocean temperature** projections for the upper 100 m show global mean warming of approximately **1.5°C under SSP1-2.6** and **3°C or more under SSP5-8.5** relative to the 1995–2014 baseline, with high regional variability. The Arctic Ocean warms 2–4 times faster than the global mean — Arctic amplification from sea ice loss — while the Southern Ocean warms more slowly due to its deep mixing. The warming penetrates progressively deeper into the water column over the century, increasing total ocean heat content and modifying the thermohaline properties of water masses that drive global ocean circulation. Critically, **ocean warming is irreversible on human timescales** even if CO₂ emissions stop: heat already committed to the ocean will continue distributing through the water column for centuries.

**Ocean acidification** trajectories follow atmospheric CO₂ closely. Surface ocean pH, which has already declined from pre-industrial ~8.2 to the current ~8.1 (a 26% increase in hydrogen ion concentration), is projected to reach approximately **7.95–8.00 under SSP1-2.6** or **7.70–7.75 under SSP5-8.5** by 2100. The lower value represents a total change of ~0.5 pH units from pre-industrial — more than double the change already observed, and unprecedented in at least **300 million years** of ocean history at the rate it is occurring. The aragonite saturation state (Ωarag), the parameter most critical for coral reef calcification, is projected to fall below 1.0 (dissolution threshold) in Arctic surface waters under SSP5-8.5 by mid-century, and aragonite-undersaturated water will expand substantially in the Southern Ocean and parts of the tropical Atlantic.

**Global mean sea level rise** projections from IPCC AR6 span approximately **0.3–0.6 m by 2100 under SSP1-2.6** and **0.6–1.0 m under SSP5-8.5** (likely range), with tails extending considerably higher — up to ~2 m under high-end ice sheet scenarios. The dominant contributions are thermal expansion of the warming ocean (~30–35% of total) and the accelerating melting of the Greenland and Antarctic ice sheets (~50% combined). Sea level rise is highly non-uniform: regional patterns reflect gravitational effects of ice mass redistribution, land subsidence, changes in ocean circulation, and atmospheric forcing. Some regions (northeastern North America, Southeast Asia) will experience sea level rise substantially above the global mean; others (near current ice sheets) may see initial sea level fall as gravitational attraction diminishes before ice loss dominates.

The concept of **compound extremes** captures perhaps the most ecologically threatening aspect of 21st-century ocean change: the simultaneous occurrence of multiple stressors in the same location at the same time. A coral reef experiencing a marine heat wave (above bleaching threshold), ocean acidification (reduced carbonate saturation impairing calcification and reef accretion), and oxygen depletion (hypoxia from warm, stratified water) simultaneously faces a "triple threat" that is qualitatively different from any single stressor. These compound events are projected to become more common as individual stressors intensify — the joint probability of extreme ocean temperature, low pH, and low oxygen co-occurring increases non-linearly as each individual stressor's baseline worsens. Understanding compound extremes is an emerging research frontier with direct implications for how ecosystem risk is assessed and communicated.`,
      keyTerms: [
        {
          term: 'Shared Socioeconomic Pathway (SSP)',
          def: 'The scenario framework used in IPCC AR6 to describe alternative future trajectories of greenhouse gas emissions, land use, and socioeconomic development. SSP1-2.6 represents a low-emissions, sustainable development pathway limiting warming to ~2°C; SSP2-4.5 is an intermediate scenario; SSP5-8.5 is a fossil-fuel-intensive high-emissions pathway leading to ~4–5°C of warming by 2100. SSPs replace the earlier Representative Concentration Pathways (RCPs) used in IPCC AR5.',
        },
        {
          term: 'sea level rise (SLR)',
          def: 'The long-term increase in global mean ocean water level, driven by two primary processes: thermal expansion (warmer water occupies greater volume) and mass addition (meltwater from glaciers and ice sheets). IPCC AR6 projects likely global mean SLR of 0.3–0.6 m by 2100 under SSP1-2.6 and 0.6–1.0 m under SSP5-8.5, with low-probability high-end scenarios reaching ~2 m if ice sheet dynamics are more sensitive than currently modelled. Regional SLR varies substantially from the global mean due to gravitational, rotational, and deformational effects.',
        },
        {
          term: 'aragonite saturation state (Ωarag)',
          def: 'A measure of whether seawater is thermodynamically favourable for the precipitation (Ω > 1) or dissolution (Ω < 1) of aragonite — the calcium carbonate polymorph used by corals, pteropods, and many other calcifying marine organisms to build their skeletons and shells. Ocean acidification reduces Ωarag by increasing [H⁺], which reacts with carbonate ions (CO₃²⁻): H⁺ + CO₃²⁻ → HCO₃⁻, lowering the carbonate ion concentration. When Ωarag falls below 1, aragonite structures dissolve passively in seawater; even above 1, reduced Ωarag increases the energy cost of calcification.',
        },
        {
          term: 'compound extreme',
          def: 'The simultaneous or sequential occurrence of multiple environmental stressors (e.g., marine heat wave + ocean acidification + deoxygenation) in the same location, producing impacts that are greater than the sum of individual stressors acting alone. Compound ocean extremes are projected to increase in frequency as climate change intensifies each individual stressor, raising the probability of their co-occurrence. The "triple threat" to coral reefs (heat, acidification, deoxygenation simultaneously) is a key example of a compound marine extreme.',
        },
        {
          term: 'tipping point',
          def: 'A threshold in the Earth system beyond which a change in state becomes self-reinforcing and potentially irreversible on human timescales, even if the original forcing is reduced. Ocean and climate tipping points relevant to the 21st century include: coral reef functional collapse (once bleaching recurrence prevents recovery, reef-building capacity cannot be maintained); AMOC slowdown or collapse (as freshwater from Greenland melt reduces the density-driven sinking that powers the Atlantic overturning); and Arctic summer sea ice loss (albedo feedback makes ice-free summers self-sustaining once the threshold is crossed).',
        },
        {
          term: 'AMOC (Atlantic Meridional Overturning Circulation)',
          def: 'The large-scale system of ocean currents in the Atlantic Ocean that transports warm, salty surface water northward and returns cold, dense deep water southward, acting as a major heat distribution system — responsible for the relatively mild climate of northwestern Europe. AMOC is driven by the formation of North Atlantic Deep Water (NADW) in the Labrador Sea and Nordic Seas; increasing freshwater input from Greenland meltwater is weakening this density-driven sinking. Observational data (RAPID array, 2004–present) show AMOC weakening of ~3 Sv. IPCC AR6 projects very likely weakening and low-confidence possible collapse this century under high emissions.',
        },
      ],
    },
    {
      type: 'concept',
      title: 'Temperature, acidification, and sea level projections under SSP scenarios',
      body: `The divergence between SSP scenarios becomes most stark when ocean projections are placed side by side. Under SSP1-2.6, warming peaks and begins to plateau by mid-century; under SSP5-8.5, it accelerates through 2100 and beyond. The difference in cumulative atmospheric CO₂ between these scenarios — roughly 450 ppm vs. 1,000+ ppm at 2100 — translates directly into dramatically different ocean chemistry. Similarly, the ice sheet contributions to sea level rise — which depend on long-term warming trends and ice sheet stability — diverge dramatically between scenarios. The most important insight from IPCC AR6 projections is that the benefits of strong mitigation are large, robust, and achievable: every tenth of a degree of avoided warming substantially reduces marine ecosystem risk, sea level impacts, and acidification severity.`,
      cards: [
        {
          name: 'Ocean Temperature Projections',
          icon: Thermometer,
          color: BRAND.accentHot,
          desc: 'Upper ocean (0–100 m) warming is projected at ~1.5°C (SSP1-2.6) to ~3°C (SSP5-8.5) above the 1995–2014 baseline by 2100. The Arctic warms 2–4× faster than the global mean. Deeper ocean layers warm more slowly but will continue warming for centuries after surface temperatures stabilise. Marine heat waves (MHWs) are projected to increase 16× (1.5°C) to 23× (2°C) in frequency over pre-industrial. Under SSP5-8.5, current 1-in-50-year MHW events recur annually by 2100, with the "extreme" becoming the new baseline.',
          examples: 'SSP1-2.6 upper ocean warming by 2100: ~1.5°C global mean · SSP5-8.5: ~3°C global mean, up to ~8°C in the Arctic · Deep ocean (below 2,000 m): +0.1–0.3°C by 2100 but committed to centuries more · MHW annual days: ~30/yr today → 220–250/yr under SSP5-8.5 by 2100 · Southern Ocean warming: slower due to deep mixing and heat uptake by AABW',
        },
        {
          name: 'Ocean Acidification Trajectories',
          icon: TrendingUp,
          color: BRAND.ruby,
          desc: 'Surface ocean pH has fallen from pre-industrial ~8.2 to current ~8.1 (26% increase in H⁺). Under SSP1-2.6, pH stabilises at ~8.0 by 2100; under SSP5-8.5 it falls to ~7.7–7.75, representing a total change of ~0.5 pH units from pre-industrial — a 3× increase in H⁺ concentration, unprecedented in rate for at least 300 million years. Arctic and Southern Ocean surface waters are projected to become aragonite-undersaturated seasonally under SSP5-8.5 by 2050–2100. Aragonite saturation in tropical surface waters remains above 1.0 but declines to levels where coral calcification rates are significantly impaired.',
          examples: 'Pre-industrial ocean pH: ~8.2 · Current (2020s): ~8.1 · SSP1-2.6 (2100): ~7.95–8.00 · SSP5-8.5 (2100): ~7.70–7.75 · Arctic Ωarag < 1.0 seasonally: SSP5-8.5 by ~2060 · Tropical coral calcification impaired (Ωarag < 2.0): widespread under SSP5-8.5 by 2050s · Southern Ocean aragonite undersaturation: expanding ~2030–2100',
        },
        {
          name: 'Sea Level Rise Projections',
          icon: Globe,
          color: BRAND.accent,
          desc: 'IPCC AR6 likely-range global mean SLR: 0.3–0.6 m (SSP1-2.6) and 0.6–1.0 m (SSP5-8.5) by 2100. Thermal expansion contributes ~30–35%; Greenland ~20–25%; Antarctica ~15–20%; glaciers ~15–20%. High-end scenarios (ice sheet instability) allow >2 m by 2100. Regional SLR is non-uniform: gravitational effects of Greenland ice loss produce above-average SLR along the US East Coast and Southeast Asia. Committed SLR — from CO₂ already emitted — is ~0.5 m by 2300 even at 1.5°C warming, with multi-metre rise committed over centuries at higher temperatures.',
          examples: 'Thermal expansion contribution: ~0.1–0.3 m by 2100 · Greenland contribution: ~0.06–0.27 m (SSP5-8.5) · Antarctica contribution: 0.03–0.34 m (SSP5-8.5, likely) · High-end low-probability estimate: ~2 m by 2100 · Sea level at 2°C committed by 2300: ~0.3–3 m depending on ice sheet stability · Pacific island nations (e.g., Tuvalu, Kiribati): face most severe proportional SLR',
        },
      ],
    },
    {
      type: 'concept',
      title: 'Tipping points, compound extremes, and observing system needs',
      body: `Beyond the "expected value" projections of ocean temperature, pH, and sea level lie the potentially irreversible changes associated with tipping points and the increasingly severe compound events that arise as multiple stressors intensify simultaneously. Tipping points in the ocean system — particularly coral reef functional collapse and AMOC slowdown — represent qualitative changes in ocean-climate state that could occur abruptly and persist for centuries regardless of subsequent emissions reductions. The compound extreme perspective, examining simultaneous stressor co-occurrence rather than treating each variable in isolation, increasingly defines how ocean risk is assessed by ecologists, managers, and insurers. Underpinning all projections is a sustained observing system need: the ocean is vast, poorly sampled, and continues to hold major uncertainties that only long-term investment in observations can reduce.`,
      cards: [
        {
          name: 'Coral Reef Functional Collapse and AMOC Slowdown',
          icon: AlertTriangle,
          color: BRAND.coral,
          desc: 'At ~1.5°C of global warming, coral reefs are projected to decline by 70–90%; at 2°C, by >99% — effectively a global functional collapse of reef-building coral ecosystems. Recurring bleaching events (currently once every 5–6 years on the Great Barrier Reef, projected to become annual under 2°C) prevent recovery between events. AMOC slowdown is very likely this century under all scenarios (IPCC AR6, high confidence); AMOC collapse within this century is assessed as "low confidence" but with high consequences — a ~3–4°C cooling of Northwestern Europe, altered rainfall patterns, and accelerated sea level rise along the US East Coast.',
          examples: '1.5°C warming: 70–90% coral reef decline (IPCC SR1.5) · 2°C: >99% decline — functional collapse · GBR bleaching recurrence interval: ~27 years pre-1980 → 5–6 years post-2010 → <1 year by ~2°C · AMOC slowdown: RAPID array measured ~3 Sv weakening since 2004 · AMOC collapse: IPCC AR6 "low confidence" for this century but high consequence · AMOC collapse projected sea level rise NE North America: additional +0.2–1.0 m',
        },
        {
          name: 'Triple Threat: Compound Ocean Extremes',
          icon: TrendingUp,
          color: BRAND.amethyst,
          desc: 'As individual ocean stressors intensify under warming, their probability of simultaneous co-occurrence increases non-linearly. A location already experiencing baseline ocean acidification stress (reduced Ωarag), a trend toward lower dissolved oxygen (deoxygenation), and increased MHW frequency simultaneously faces the "triple threat" — all three stressors peaking together during a compound extreme event. Tropical coral reefs, Eastern Pacific cold-water upwelling ecosystems, and polar marine ecosystems are assessed as most vulnerable to compound extremes. The joint probability of exceeding all three stressor thresholds simultaneously is projected to increase by orders of magnitude by 2100 under high-emissions scenarios.',
          examples: 'Eastern Boundary Upwelling Systems (California, Humboldt, Benguela): already experience episodic triple threat from upwelling of warm, acidic, low-O₂ water · Coral reefs: simultaneous bleaching (heat) + dissolution stress (acidification) + hypoxia documented in Arabian Sea and Caribbean · Joint probability of three simultaneous stressors: increases ~20–50× under SSP5-8.5 vs. pre-industrial (model estimates) · Observed compound events: 2015–2016 combined El Niño MHW + acidification stress across much of the Pacific',
        },
        {
          name: 'Observing System Needs and Monitoring Gaps',
          icon: Globe,
          color: BRAND.jade,
          desc: 'The projections in IPCC AR6 are limited by observational gaps that constrain model calibration and validation. Key priorities identified by the ocean science community include: expansion of the BGC-Argo float network (adding oxygen, pH, nitrate, and chlorophyll sensors to the existing Argo temperature-salinity array); sustained deep-ocean hydrographic sections (GO-SHIP) to track changes below 2,000 m; sustained mooring arrays for AMOC monitoring (RAPID, OSNAP); expanded coral reef monitoring networks; and improved satellite ocean colour and sea surface height observations. Each of these observing system components provides data that directly reduces uncertainty in key ocean projection variables.',
          examples: 'Argo float network: ~4,000 floats globally (T/S only); BGC-Argo: ~1,000 floats with biogeochemical sensors (target: 1,000→4,000) · GO-SHIP repeat hydrography: ~30-year sections providing decadal ocean interior change record · RAPID AMOC array (26°N): continuous monitoring since 2004, detected ~3 Sv weakening · NOAA CRW global coral bleaching monitoring: daily 5km SST coverage · Copernicus CMEMS: near-real-time global ocean state monitoring platform',
        },
      ],
    },
    {
      type: 'visualization',
      title: 'Diverging ocean futures: from SSP choice to 2100 ocean state',
      body: `The ocean in 2100 will be shaped by the cumulative emissions choices of the present generation. Follow the branching pathways from the SSP scenarios chosen in the near term through the physical and chemical changes they drive, to the ecosystem and societal consequences that differentiate a manageable future from a fundamentally transformed ocean.`,
      interaction: {
        type: 'flow-simulator' as const,
        description: 'Branching pathways from emissions scenario choice through physical ocean changes to ecosystem and societal outcomes in 2100',
        nodes: [
          {
            id: 'emissions-choice',
            label: 'Emissions pathway choice (SSP scenario)',
            description: 'The Shared Socioeconomic Pathways define alternative futures based on different emissions trajectories. SSP1-2.6 represents aggressive mitigation: net-zero CO₂ by ~2050, negative emissions in the second half of the century, with radiative forcing peaking at ~2.6 W/m² and warming stabilising at ~1.7–2.0°C by 2100. SSP5-8.5 represents a fossil-fuel-intensive high-end scenario: CO₂ emissions roughly doubling by 2100, atmospheric CO₂ reaching ~1,100 ppm, and global mean warming of ~3.3–5.7°C by 2100 (likely range). Between these end-members, SSP2-4.5 (intermediate) and SSP3-7.0 (high emissions) represent plausible scenarios where current policies are either modestly strengthened or not substantially changed. The difference in cumulative CO₂ between SSP1-2.6 and SSP5-8.5 through 2100 is approximately 2,000 Pg CO₂ — the scale of irreversible change to the ocean is directly proportional to this cumulative forcing.',
            color: BRAND.accent,
          },
          {
            id: 'physical-ocean-change',
            label: 'Physical ocean changes: heat, sea level, circulation',
            description: 'Atmospheric CO₂ and the resulting greenhouse forcing drive heat accumulation in the ocean, which is the largest heat reservoir in the climate system. Under SSP1-2.6, ocean warming in the upper 100 m reaches ~1.5°C globally by 2100; under SSP5-8.5, ~3°C globally with Arctic warming of ~8°C and near-complete summer sea ice loss. Ocean heat content changes drive thermal expansion (contributing 0.1–0.3 m to sea level rise by 2100) and modify the thermohaline properties of water masses. Greenland and Antarctic ice sheet mass loss — accelerated by atmospheric and ocean warming — add 0.3–0.7 m more (under high emissions). AMOC, driven by the density contrast between warm surface and cold deep water, weakens progressively under all scenarios as freshwater input from Greenland melt reduces surface water density. Under SSP5-8.5, AMOC is projected to weaken by 24–39% relative to 1995–2014, with low-probability collapse scenarios having consequences lasting centuries.',
            color: BRAND.gold,
          },
          {
            id: 'ocean-chemistry',
            label: 'Ocean chemistry changes: acidification and deoxygenation',
            description: 'Ocean acidification tracks atmospheric CO₂ almost linearly: higher CO₂ concentrations produce lower pH and reduced carbonate saturation states. Under SSP1-2.6, surface ocean pH stabilises at ~8.0 by 2100 — a change of 0.1 units from today, 0.2 units from pre-industrial. Under SSP5-8.5, pH falls to ~7.7–7.75 — a total change of 0.45–0.5 pH units, representing a tripling of hydrogen ion concentration from pre-industrial. Arctic and Antarctic surface waters approach aragonite undersaturation (Ωarag < 1) seasonally under SSP5-8.5 by 2050–2100, threatening pteropods, cold-water corals, and other high-latitude calcifiers. Ocean deoxygenation continues under all scenarios, with the global oxygen inventory projected to decline 3–4% further under SSP5-8.5 by 2100, with OMZs continuing to expand. The combination of warming, acidification, and deoxygenation co-occurs across the same ocean regions, intensifying compound exposure.',
            color: BRAND.amethyst,
          },
          {
            id: 'compound-extremes',
            label: 'Compound extreme events: the triple threat',
            description: 'As each individual ocean stressor (heat, acidification, deoxygenation) intensifies, their joint probability of simultaneous co-occurrence increases non-linearly. A coral reef or kelp forest exposed to MHW conditions (SST > bleaching threshold), reduced aragonite saturation (carbonate dissolution stress on calcifying organisms), and low dissolved oxygen (physiological stress reducing immune function and metabolic capacity) simultaneously faces a "triple threat" that is qualitatively more damaging than any single stressor and has been demonstrated to cause mortality in laboratory and field settings even at sub-lethal individual stressor levels. Eastern Boundary Upwelling Systems — particularly the California Current and Humboldt Current — already experience episodic compound exposure as upwelling brings warm, low-O₂, high-CO₂ deep water to the surface during anomalous conditions. Climate projections show the frequency of compound triple-threat events increasing 20–50× under SSP5-8.5 relative to pre-industrial by 2100.',
            color: BRAND.coral,
          },
          {
            id: 'tipping-points',
            label: 'Tipping points: coral collapse and AMOC slowdown',
            description: 'Ocean tipping points represent thresholds beyond which a change in state becomes self-reinforcing and may be irreversible on human timescales. For coral reefs, IPCC AR6 and IPCC SR1.5 (2018) project that at 1.5°C of global warming, 70–90% of coral reefs are at high risk; at 2°C, functional collapse of reef-building capacity in virtually all tropical reef systems is projected. Recurring bleaching events prevent recovery between events; once the interval between bleaching drops below the recovery time (~10–15 years), reef frameworks erode faster than they accrete, triggering irreversible collapse. For AMOC, IPCC AR6 assesses "very likely weakening" over the 21st century with high confidence, and "low confidence" but "not impossible" collapse within this century under high emissions. AMOC collapse would dramatically cool Northwestern Europe, displace rainfall patterns across the tropics and subtropics, raise sea level further along the US East Coast by 0.2–1.0 m, and alter Southern Ocean carbon uptake — a cascade with global consequences.',
            color: BRAND.ruby,
          },
          {
            id: 'observational-imperative',
            label: 'Observing systems and reducing projection uncertainty',
            description: 'Ocean projections carry substantial uncertainty that only sustained observations can reduce. The largest uncertainties in IPCC AR6 ocean projections are in: (1) ice sheet dynamics (particularly the marine-based West Antarctic Ice Sheet, where ice cliff instability and marine ice sheet instability mechanisms could produce SLR dramatically above the likely range); (2) AMOC behaviour and its sensitivity to freshwater forcing; (3) biological pump efficiency changes (affecting how much carbon the ocean sequesters biologically); and (4) ocean carbon sink saturation (whether warming and acidification are reducing the efficiency of both the solubility and biological pumps). The BGC-Argo programme, GO-SHIP hydrographic sections, the RAPID AMOC monitoring array, and NOAA/ESA satellite missions (TOPEX/POSEIDON successors, SWOT) are the primary observing systems providing the data to constrain these uncertainties. Sustained investment in ocean observations is a prerequisite for confident projection of and adaptation to future ocean change.',
            color: BRAND.jade,
          },
        ],
        edges: [
          { from: 'emissions-choice',     to: 'physical-ocean-change', label: 'cumulative CO₂ forcing drives ocean heat accumulation and ice sheet loss' },
          { from: 'emissions-choice',     to: 'ocean-chemistry',        label: 'atmospheric CO₂ concentration determines acidification severity' },
          { from: 'physical-ocean-change', to: 'compound-extremes',    label: 'warming increases MHW frequency; circulation changes alter stressor co-occurrence' },
          { from: 'ocean-chemistry',      to: 'compound-extremes',      label: 'acidification and deoxygenation add to MHW thermal stress in compound events' },
          { from: 'compound-extremes',    to: 'tipping-points',         label: 'repeated compound extremes push ecosystems past recovery thresholds' },
          { from: 'tipping-points',       to: 'observational-imperative', label: 'observing systems required to detect tipping point proximity and constrain projections' },
        ],
      },
    },
    {
      type: 'quiz',
      questions: [
        {
          q: 'Under the SSP5-8.5 high-emissions scenario, approximately what surface ocean pH is projected by 2100, and how does this compare to pre-industrial values?',
          a: [
            'Under SSP5-8.5, surface ocean pH is projected to rise to approximately 8.4 by 2100 because increased photosynthesis by phytoplankton in a warmer, more productive ocean consumes dissolved CO₂ faster than the atmosphere supplies it, raising pH above the pre-industrial value of ~8.2',
            'Under SSP5-8.5, surface ocean pH is projected to stabilise at approximately 8.1 — essentially unchanged from today — because the ocean\'s large buffering capacity (bicarbonate and carbonate ions) is sufficient to neutralise all additional CO₂ from fossil fuel emissions without a measurable pH change',
            'Under SSP5-8.5, surface ocean pH is projected to decline to approximately 7.70–7.75 by 2100, compared to a pre-industrial value of ~8.2; this represents a change of ~0.45–0.5 pH units — a tripling of hydrogen ion concentration relative to pre-industrial, unprecedented in rate for at least 300 million years of ocean history',
            'Under SSP5-8.5, surface ocean pH is projected to decline to approximately 6.5 by 2100, which would make surface seawater slightly acidic (pH < 7) and cause all calcium carbonate marine structures to dissolve immediately; this crossing of pH 7.0 is considered the key tipping point for marine carbonate ecosystems',
          ],
          correct: 2,
          explain: 'Option A is incorrect: warmer water reduces CO₂ solubility and increases thermal stratification, which reduces biological productivity in many regions — these effects do not overwhelm the pH-lowering effect of continued CO₂ absorption; furthermore, increased photosynthesis without corresponding export (the biological pump) does not produce a net long-term pH increase. Option B is incorrect: while the ocean does have substantial buffering capacity (the bicarbonate-carbonate system), this capacity is finite and is already being exceeded — the observed 0.1 pH unit decline since pre-industrial is empirical evidence that the buffering capacity cannot neutralise current anthropogenic CO₂ additions without measurable pH change. Option D greatly overestimates the acidification: a 0.5 pH unit decline from 8.2 gives 7.7, not 6.5; reaching pH 6.5 would require an ocean CO₂ concentration increase many times greater than projected. Surface seawater will not approach pH 7.0 this century under any plausible emissions scenario. The correct answer is C: pre-industrial surface ocean pH was approximately 8.2. By 2024, it has declined to approximately 8.1 — a change of 0.1 pH units representing a 26% increase in hydrogen ion concentration ([H⁺]). Under SSP5-8.5, with atmospheric CO₂ reaching ~1,100 ppm by 2100, the equilibrium surface ocean pH is projected to decline to approximately 7.70–7.75 — a total change of ~0.45–0.5 pH units from pre-industrial. Because pH is a logarithmic scale, 0.5 units represents a tripling of [H⁺]. The rate of this change is without precedent in the geological record of ocean chemistry for at least 300 million years — even the end-Permian ocean acidification (associated with massive volcanism ~252 Ma) occurred over thousands of years, not centuries. Under SSP1-2.6, pH stabilises at ~8.0 by 2100 — still a significant change, but dramatically less severe.',
        },
        {
          q: 'What are the primary contributions to global mean sea level rise, and what are the IPCC AR6 likely-range projections for 2100 under SSP1-2.6 and SSP5-8.5?',
          a: [
            'Sea level rise is driven entirely by thermal expansion of the warming ocean; ice sheet and glacier melt do not contribute significantly because the weight of ice presses sea ice and glacial ice below sea level, and the Archimedes principle prevents their melting from raising ocean levels; IPCC AR6 projects 0.1 m rise under all scenarios by 2100',
            'Sea level rise is caused primarily by the gravitational pull of the Moon increasing as tidal cycles change under altered ocean temperatures; IPCC AR6 projects 0.5 m under SSP1-2.6 and 2.0 m under SSP5-8.5, both driven entirely by tidal amplification of warm ocean water',
            'Global mean sea level rise is driven by thermal expansion (~30–35%), Greenland ice sheet mass loss (~20–25%), Antarctic ice sheet mass loss (~15–20%), and glacier mass loss (~15–20%); IPCC AR6 likely-range projections are approximately 0.3–0.6 m under SSP1-2.6 and 0.6–1.0 m under SSP5-8.5 by 2100, with low-probability high-end scenarios reaching ~2 m under high-emissions ice instability cases',
            'Sea level rise is projected to be identical under all SSP scenarios (0.25–0.30 m by 2100) because thermal expansion and ice melt cancel each other out in high-emissions scenarios — warmer temperatures accelerate ice melt but also increase evaporation, removing water from the ocean; only under low-emissions scenarios does ice melt dominate and produce higher sea level',
          ],
          correct: 2,
          explain: 'Option A confuses sea ice (which is already floating and follows Archimedes principle — its melting does not change sea level) with land-based glaciers and ice sheets (which are above sea level and add water to the ocean when they melt). Thermal expansion is real and significant but not the sole contributor. The projection of 0.1 m under all scenarios is dramatically inconsistent with IPCC AR6 findings. Option B invents a tidal amplification mechanism that does not exist — ocean temperatures do not change the gravitational pull of the Moon, and tidal cycles are not a driver of long-term sea level rise on the scales discussed. Option D incorrectly asserts identical projections across SSP scenarios — this is strongly contradicted by IPCC AR6, which shows clear scenario dependence in SLR; it also incorrectly describes an evaporation cancellation mechanism that does not operate on the relevant timescales. The correct answer is C: IPCC AR6 Chapter 9 and the Sea Level chapter identify four primary contributions to global mean SLR. (1) Thermal expansion (~30–35%): as the ocean warms, seawater density decreases and volume expands. (2) Greenland ice sheet (~20–25%): surface melt and outlet glacier dynamics are both accelerating. (3) Antarctic ice sheet (~15–20%): marine glaciers including Thwaites and Pine Island are losing mass, contributing with growing uncertainty. (4) Glaciers outside the ice sheets (~15–20%): mountain glaciers globally are retreating. The IPCC AR6 likely-range projections are 0.3–0.6 m by 2100 under SSP1-2.6 (low emissions) and 0.6–1.0 m under SSP5-8.5 (high emissions). The high-end, low-probability estimate for SSP5-8.5 — incorporating possible ice sheet instability mechanisms (Marine Ice Sheet Instability, MISI; Marine Ice Cliff Instability, MICI) — reaches approximately 2 m by 2100. SLR is committed for centuries even if emissions stop; sea levels at 2°C warming are projected to continue rising for centuries.',
        },
        {
          q: 'What is the significance of the AMOC (Atlantic Meridional Overturning Circulation) for regional climate, and what does IPCC AR6 project for its future?',
          a: [
            'AMOC is a deep-ocean circulation pattern confined to below 2,000 m that has no significant influence on surface climate or sea level; its potential weakening is of interest only to deep-sea biologists studying abyssal ecosystems, and IPCC AR6 projects no change in AMOC strength under any scenario this century because deep ocean circulation is insensitive to surface warming',
            'AMOC transports warm, salty surface water northward in the Atlantic and returns cold, dense deep water southward, moderating climate in Northwestern Europe (adding ~5–10°C compared to the same latitudes in the North Pacific), and contributing to rainfall patterns in the Sahel, monsoon regions, and South America; IPCC AR6 projects AMOC weakening is very likely over the 21st century under all scenarios, with low-confidence but possible collapse under high emissions, which would cause cooling of Northwestern Europe, disrupted precipitation, and additional sea level rise along the US East Coast',
            'AMOC is the primary mechanism by which the Atlantic Ocean absorbs anthropogenic CO₂ from the atmosphere; a weakening AMOC would reduce ocean CO₂ uptake by 80% and cause atmospheric CO₂ to rise by 200–300 ppm within decades; IPCC AR6 projects AMOC collapse as a near-certainty under SSP5-8.5 by 2060, triggering the most severe chain of events in IPCC\'s assessed scenarios',
            'AMOC\'s primary relevance for future ocean projections is its role in transporting nutrients from the deep Atlantic to the surface ocean; weakening AMOC would increase phytoplankton productivity by 50% because deep nutrient-rich water would be diverted to the surface; IPCC AR6 projects AMOC strengthening under SSP5-8.5 as higher temperatures increase the density gradient between the tropics and poles, driving faster circulation',
          ],
          correct: 1,
          explain: 'Option A is incorrect on multiple counts: AMOC is a full-depth circulation system with a major surface component (the Gulf Stream and North Atlantic Current); it has enormous climate influence at the surface, including the moderation of European temperatures; IPCC AR6 explicitly projects AMOC weakening with high confidence. Option C overstates both the CO₂ mechanism (AMOC is not the primary CO₂ uptake mechanism; gas exchange and biological pump dominate) and the probability of collapse (IPCC AR6 assesses collapse this century as "low confidence," not "near-certainty"). Option D is incorrect: AMOC weakening would reduce nutrient supply to the North Atlantic surface (reducing productivity, not increasing it); the mechanism described (higher temperatures increasing the tropics-poles density gradient) is wrong — higher temperatures reduce the density contrast by warming both regions (with polar regions warming faster), which is exactly what is driving projected AMOC weakening, not strengthening. The correct answer is B: AMOC is a pivotal feature of the global ocean and climate system. It transports approximately 1.3 × 10¹⁵ W of heat northward in the North Atlantic — equivalent to roughly 100,000 nuclear power plants. This heat transport moderates the climate of Northwestern Europe, keeping temperatures in the UK, Ireland, and Scandinavia ~5–10°C warmer than equivalent latitudes in the North Pacific. AMOC drives by the sinking of dense, cold, salty water in the Labrador Sea and Nordic Seas (North Atlantic Deep Water formation), which in turn is sustained by the poleward transport of warm, salty surface water. As Greenland ice sheet melt accelerates, fresh, buoyant meltwater reduces the density of North Atlantic surface water, inhibiting the sinking that drives AMOC. The RAPID mooring array at 26°N (operational since 2004) has measured AMOC strength continuously and detected a weakening of approximately 3 Sv (~15% of mean transport). IPCC AR6 assesses it as "very likely" that AMOC will weaken further over the 21st century, and as "low confidence" but not excluded that AMOC could collapse this century under SSP5-8.5 — with consequences including cooling of Northwestern Europe by several degrees, southward displacement of the Intertropical Convergence Zone (affecting Sahel and Amazon rainfall), additional sea level rise of 0.2–1.0 m along the US East Coast (from loss of the low sea level maintained by the geostrophic slope of AMOC), and altered North Atlantic biological productivity.',
        },
        {
          q: 'What is the projected fate of tropical coral reef ecosystems under 1.5°C vs. 2°C of global warming, and why does the half-degree difference matter so profoundly?',
          a: [
            'At both 1.5°C and 2°C of global warming, tropical coral reefs are projected to increase in extent and biodiversity because warmer ocean waters allow coral-building species from lower latitudes to colonise previously marginal reefs at higher latitudes; the net gain of new coral habitat exceeds the loss of bleached tropical reefs at both temperature levels',
            'At 1.5°C of warming, coral reefs decline by 70–90% globally; at 2°C, coral reef functional collapse (>99% decline) is projected for virtually all tropical reef systems; the half-degree difference is critical because it determines whether bleaching recurrence intervals shorten to less than the 10–15-year recovery time needed for reefs to maintain net positive calcification — once bleaching becomes near-annual, reefs erode faster than they accrete, triggering irreversible collapse of the reef framework',
            'At 1.5°C and 2°C, the difference in coral reef outcomes is negligible — both temperatures produce approximately 50% coral cover decline globally; the 70–90% figure cited in IPCC reports refers only to the most vulnerable individual reef structures in the Persian Gulf, not to global reef systems; globally, most reefs are projected to survive 2°C with modest intervention',
            'Coral reefs are resilient to temperature increases up to 3°C because corals can rapidly adapt through symbiont shuffling (replacing heat-sensitive symbionts with heat-tolerant ones) on timescales of 10–20 years; both 1.5°C and 2°C are within the adaptive capacity of most reef systems, and substantial coral reef loss is only projected above 2.5–3°C of warming',
          ],
          correct: 1,
          explain: 'Option A is incorrect: while poleward range expansion of some warm-water coral species has been documented in response to warming (e.g., Acropora expansion southward in Japan), these range-expanding communities are not replacing tropical reef ecosystems in diversity or structural complexity — they are sparse warm-affinity coral communities colonising rocky substrate, not full reef ecosystems. Net global coral reef area and biodiversity are unambiguously declining, not increasing. Option C dramatically understates the projected decline and misrepresents the geographic scope: the 70–90% figure at 1.5°C applies globally across all tropical reef systems, based on IPCC SR1.5 (2018) which drew on multiple coral reef models and observational records. Option D overestimates adaptive capacity: while thermally tolerant symbiont shuffling does occur in some coral species on some reefs, the pace of thermal stress in current and projected climate change exceeds the rate of adaptation by most reef communities; moreover, coral bleaching also impairs the very process of symbiont acquisition, making adaptation during bleaching events physiologically difficult. IPCC SR1.5 explicitly states that 3°C would result in complete loss of tropical reef systems. The correct answer is B: IPCC SR1.5 (2018) published one of the most consequential ocean projections in climate assessment history: under 1.5°C of global warming, tropical coral reefs are projected to decline by 70–90% relative to today; under 2°C, the decline exceeds 99% — effectively the global functional collapse of reef-building coral ecosystems as they are currently known. The half-degree difference matters because it determines whether bleaching recurrence intervals shorten below the ~10–15 years needed for coral recovery. The Great Barrier Reef experienced mass bleaching in 1998, 2002, 2016, 2017, 2020, 2022, and 2024 — already below the recovery threshold in many reef areas. At ~1.5°C, bleaching events occur every 5–6 years on average; at 2°C, they are projected to occur annually or biannually. Once bleaching is annual, the biological calcification that builds reef framework cannot keep pace with physical and chemical erosion, and the reef structure itself begins to dissolve — a tipping point from net accretion to net erosion that is self-reinforcing and will persist even if temperatures stabilise.',
        },
        {
          q: 'What does the term "compound marine extreme" mean, and why are these events considered particularly threatening to ocean ecosystems under climate change projections?',
          a: [
            'A compound marine extreme refers to a single very severe marine heat wave that simultaneously affects all ocean basins; these events are threatening because they occur faster than ecosystem monitoring systems can detect them, making early warning impossible and preventing any adaptive management response',
            'A compound marine extreme is the co-occurrence of two or more ocean stressors — such as simultaneous marine heat wave (elevated SST), ocean acidification (low pH/Ωarag), and deoxygenation (low O₂) — in the same location at the same time; these events are particularly threatening because the combined impact on organisms and ecosystems is greater than the sum of individual stressors, and their joint probability is projected to increase non-linearly as each individual stressor intensifies under warming',
            'Compound marine extremes are defined as the co-occurrence of ocean and atmospheric extreme events — specifically, a category 5 hurricane passing over an area experiencing a marine heat wave; they are considered threatening solely because the combination increases wave energy and coastal flooding risk, not because of any direct biological stress',
            'A compound marine extreme refers to a single stressor that affects multiple ocean properties simultaneously through one chemical reaction — for example, the dissolution of CO₂ in seawater that simultaneously lowers pH, raises temperature through infrared absorption by carbonic acid, and consumes dissolved oxygen through the reaction CO₂ + O₂ → CO₃; this co-occurrence of multiple changes from a single reaction is why ocean acidification is considered a compound threat',
          ],
          correct: 1,
          explain: 'Option A misdefines the term — a compound extreme is not a single severe event affecting all basins; it is the simultaneous co-occurrence of multiple distinct stressors. Option C conflates a "compound extreme" with a specific event type (hurricane + MHW), which is a valid concern for coastal flooding and infrastructure but is not the primary marine biology context in which the term is used; it also incorrectly restricts the biological threat to wave energy and flooding rather than physiological stressor interactions. Option D is chemically incorrect: CO₂ dissolution does not raise temperature (carbonic acid does not absorb significant infrared radiation at ocean concentrations), and the reaction CO₂ + O₂ → CO₃ is not a real chemical equation in ocean chemistry contexts. The correct answer is B: compound marine extremes (also called "compound ocean hazards") refer to the simultaneous or near-simultaneous co-occurrence of multiple distinct ocean stressors at the same location. The most frequently discussed combination is the "triple threat": elevated sea surface temperatures (marine heat wave conditions), reduced pH and aragonite saturation state (ocean acidification), and reduced dissolved oxygen (deoxygenation). These three stressors are mechanistically linked to the same driver (greenhouse gas warming) but affect organisms through distinct physiological pathways: heat stress disrupts enzyme function and expels coral symbionts; low carbonate saturation impairs calcification and shell/skeleton integrity; low oxygen induces aerobic stress, reduces metabolic capacity, and impairs immune function. Laboratory experiments show that the combined effect of all three stressors acting simultaneously produces mortality or sublethal damage at individual stressor concentrations that would be tolerated separately — synergistic rather than merely additive effects. Under climate projections, the joint probability of all three thresholds being exceeded simultaneously increases non-linearly, because each stressor\'s baseline is worsening concurrently: MHW intensity is increasing, pH baseline is declining, and oxygen baseline is declining — so the probability of all three simultaneously exceeding critical thresholds at the same location grows by orders of magnitude under high-emissions scenarios.',
        },
      ],
    },
  ],
}

export default futureOceanProjections
