import { Globe, Layers, ArrowDown, Activity, Zap } from 'lucide-react'
import { BRAND } from '@/lib/brand'
import type { Lesson } from './types'

const seismicWavePropagation: Lesson = {
  id: 'seis-101-1-1-2',
  title: 'How Seismic Waves Travel Through the Earth',
  track: 'geo',
  trackName: 'Seismology',
  level: 'Beginner',
  duration: '12 min',
  xpReward: 120,
  description: `Seismic waves bend, reflect, and shadow as they travel through Earth\'s layered interior — and every deviation from a straight path carries information about the composition, temperature, and physical state of the deep Earth.`,
  sources: [
    { org: 'USGS',        title: 'USGS Earthquake Hazards — Inside the Earth',                       url: 'https://earthquake.usgs.gov/learn/topics/seismology/seismicwaves.php' },
    { org: 'EarthScope',  title: 'EarthScope Consortium — Seismology and Earth Structure',           url: 'https://www.earthscope.org/education/' },
    { org: 'Lay & Wallace', title: 'Modern Global Seismology — Cambridge University Press',          url: 'https://www.cambridge.org/' },
    { org: 'AGI',         title: 'AGI Glossary of Geology',                                          url: 'https://www.americangeosciences.org/' },
  ],
  sections: [
    {
      type: 'intro',
      title: `Bending, bouncing, and shadowing: how seismic rays map the Earth\'s interior`,
      body: `When seismic waves travel through Earth, they do not move in straight lines. Like light rays entering a glass lens, seismic waves bend (refract) whenever they cross a boundary where velocity changes, and reflect whenever the velocity contrast is sharp enough. Because seismic velocity generally increases with depth in the mantle — pressure increases K and μ faster than ρ — wave paths curve continuously, bending away from the vertical and eventually turning back toward the surface. This continuous refraction creates curved ray paths that were first analysed mathematically by Karl Zoeppritz and Beno Gutenberg in the early twentieth century.

The most important velocity boundaries in Earth are the Mohorovičić discontinuity (Moho), the 410 km and 660 km transition zone discontinuities, and the core-mantle boundary (CMB) at 2,891 km depth. At the Moho, P-wave velocity jumps abruptly from ~6.5 km/s (continental crust) to ~8.0 km/s (uppermost mantle), first detected by Croatian seismologist Andrija Mohorovičić in 1909 by analysing a local Croatian earthquake: at stations close to the earthquake, direct crustal P-waves arrived first; at greater distances, waves that had refracted along the top of the faster mantle ("head waves") overtook them and arrived first, revealing the faster layer below. The crossover distance (where head waves overtake direct waves) gave Mohorovičić the depth to his discontinuity — about 54 km beneath Croatia — and the principle he established is now used globally.

The shadow zones are perhaps the most dramatic demonstration of seismic wave bending. P-waves traveling toward Earth\'s opposite side reach a region called the P-wave shadow zone between 105° and 140° of angular distance from the earthquake — no direct P-waves arrive there because the core-mantle boundary refracts the waves sharply downward (the P-wave velocity drops from ~13.7 km/s in the base of the lower mantle to ~8.1 km/s in the outer core — a large velocity decrease that bends waves toward the core\'s centre rather than through the shadow zone). S-waves cannot penetrate the liquid outer core at all, creating an even larger S-wave shadow zone beyond 105° from the earthquake. Within the P-wave shadow zone at 105°-140°, very weak P-wave arrivals called PKP phases can still be detected — these are waves that entered and exited the outer core but took more complex curved paths. Richard Dixon Oldham first recognised these shadow zones in 1906, proving Earth had a distinct core.

The inner core adds another layer of seismic complexity. P-waves that travel all the way through the inner core (PKIKP phases) arrive within the shadow zone at distances beyond 150°. The inner core\'s P-wave velocity (~11 km/s, higher than the outer core\'s ~10 km/s) and the detection of weak S-waves (PKJKP phases) transmitted through the inner core confirm it is solid. Danish seismologist Inge Lehmann discovered the inner core in 1936 from careful analysis of PKIKP arrivals. Furthermore, the inner core appears to be seismically anisotropic — P-waves traveling parallel to Earth\'s rotation axis are ~3-4% faster than those traveling through the equatorial plane — probably because iron crystals in the inner core are aligned by the magnetic field or by slow differential rotation (~0.3-0.5°/yr faster than the mantle).`,
      keyTerms: [
        {
          term: 'Snell\'s Law (seismic)',
          def: `The fundamental rule governing refraction at seismic velocity boundaries, expressed as sin(i₁)/v₁ = sin(i₂)/v₂ where i₁ and i₂ are the angles of incidence and refraction measured from the vertical and v₁, v₂ are the wave velocities in each layer. It causes waves to bend away from regions of low velocity toward regions of high velocity. In Earth\'s mantle, where velocity increases continuously with depth, Snell\'s law produces concave-upward ray arcs that curve progressively away from vertical until they turn back toward the surface, allowing body waves from a single earthquake to return to the surface at a range of epicentral distances.`,
        },
        {
          term: 'Mohorovičić discontinuity (Moho)',
          def: `The seismic and chemical boundary between Earth\'s crust and mantle, where P-wave velocity jumps abruptly from ~6.5 km/s to ~8.0 km/s. Depth varies: ~7 km beneath oceanic crust and ~35-70 km beneath continents (global average ~35 km). Discovered in 1909 by Croatian seismologist Andrija Mohorovičić, who identified the velocity jump from the crossover distance at which mantle head waves overtook direct crustal P-waves in travel-time records from a local earthquake. The Moho defines the base of the crust both chemically (change from felsic/mafic crustal rock to ultramafic peridotite) and seismically.`,
        },
        {
          term: 'P-wave shadow zone',
          def: `A region at 105°-140° of angular distance from an earthquake where direct P-waves do not arrive at the surface. The shadow zone is caused by refraction at the core-mantle boundary: as P-wave velocity drops sharply from ~13.7 km/s at the base of the lower mantle to ~8.1 km/s in the outer core, Snell\'s law bends incoming rays steeply downward, deflecting them away from the 105°-140° angular range. Waves arriving shallower than the critical angle return to the surface at less than 105°; waves entering the core emerge beyond 140°. First identified by Richard Dixon Oldham in 1906, the shadow zone was the original proof that Earth has a distinct core.`,
        },
        {
          term: 'PKIKP wave',
          def: 'A seismic phase in which a P-wave travels down through the mantle (P), refracts into the liquid outer core (K), transmits through the solid inner core (I), exits the inner core back into the outer core (K again), and returns through the mantle to the surface (P). PKIKP phases arrive within the P-wave shadow zone at distances of 150°-180° from the source. The velocity increase encountered in the inner core (~11 km/s vs. ~10 km/s in the outer core) causes inner-core-crossing rays to be focused back toward the surface, producing real arrivals where the simple outer-core model predicts silence. Inge Lehmann used these anomalous arrivals in 1936 to discover the inner core.',
        },
        {
          term: 'Seismic anisotropy',
          def: `A property of a material or region in which the velocity of seismic waves varies depending on the direction of propagation or polarisation. In Earth\'s inner core, P-waves traveling parallel to the rotation axis are ~3-4% faster than those traveling through the equatorial plane, probably due to preferential alignment of hexagonal close-packed iron (hcp ε-iron) crystals. The crust and upper mantle also exhibit anisotropy from aligned olivine crystals or fluid-filled fractures, which seismologists use to infer past strain history and present-day mantle flow directions.`,
        },
      ],
    },
    {
      type: 'concept',
      title: `Ray paths, shadow zones, and Earth\'s layered structure`,
      body: `Snell\'s law governs every refraction event a seismic ray experiences. In its seismic form — sin(i₁)/v₁ = sin(i₂)/v₂ — it dictates that a ray bends toward the vertical when it enters a slower medium and away from the vertical when it enters a faster medium. Because velocity in the mantle increases nearly continuously with depth (driven by rising pressure that stiffens K and μ faster than ρ grows), rays do not refract at discrete steps but curve smoothly. Starting from a steep near-vertical path at the surface, a ray arcs progressively away from vertical as it descends into faster rock, eventually reaching a turning point where the ray is horizontal, after which it curves back upward toward the surface. The result is a family of concave-upward arc paths: shallow rays return to the surface at short epicentral distances, and progressively steeper rays penetrate deeper and emerge at greater distances. Reflected phases — PcP, ScS, and others — bounce off the sharp CMB like light off a mirror, while transmitted phases refract across it according to Snell\'s law.

The shadow zones and different seismic phases encode the structure of Earth\'s core with extraordinary precision. At the CMB, P-wave velocity drops from ~13.7 km/s in the lowermost mantle to ~8.1 km/s in the outer core — a large velocity decrease that deflects all incoming rays sharply downward. Rays that approach the CMB at angles shallower than a critical angle graze it and return to the surface at ~105°; steeper rays enter the outer core and, bent sharply inward by the velocity decrease, emerge only beyond ~140°. The gap between 105° and 140° receives neither direct mantle P-waves nor core-penetrating P-waves — the P-wave shadow zone. S-waves cannot enter the liquid outer core at all (μ = 0 means no shear modulus, no S-wave transmission), so the S-wave shadow zone extends all the way from 105° to 180°, confirming the outer core is liquid iron alloy. Inside the outer core, some PKP rays penetrate into the solid inner core and become PKIKP. The velocity increase in the inner core (~11 km/s vs. ~10 km/s) refracts PKIKP rays back toward the surface, producing weak but real arrivals within the shadow zone at 150°-180°. The ~2-second travel-time difference between PKIKP waves that traverse the inner core along polar vs. equatorial paths is direct evidence of inner-core anisotropy — the seismic fingerprint of aligned iron crystals at Earth\'s very centre.`,
      cards: [
        {
          name: 'Ray Bending and Head Waves in the Mantle',
          icon: Layers,
          color: BRAND.coral,
          desc: 'Continuous velocity increase with depth bends seismic rays into smooth concave-upward arcs that return to the surface at distances of 10°-100°. At sharp velocity interfaces, critically refracted head waves travel along the boundary at the faster velocity, continuously shedding energy back into the upper layer at the critical angle; beyond a crossover distance (~3-5× the depth to the interface), head waves arrive before direct waves. Mohorovičić used this crossover distance principle in 1909 to determine the Moho depth beneath Croatia. Reflected phases (PcP, ScS) bounce off the CMB. Seismic refraction surveys exploiting the same head-wave principle are routine in oil and gas exploration and groundwater mapping.',
          examples: 'Moho at 35 km depth: crossover distance ~100 km; head-wave velocity ~8.0 km/s. Mantle rays from deep earthquakes emerge at the antipode after arcing through the entire mantle. PcP (P reflected off CMB): provides sharp bounce-point constraint used to map CMB topography. Seismic refraction survey in sedimentary basin: 50 m depth to water table detected by head-wave crossover at ~200 m offset. Subducting slab: anomalously fast ray paths through cold slab detected as early arrivals.',
        },
        {
          name: 'Shadow Zones and the Discovery of Earth\'s Core',
          icon: Globe,
          color: BRAND.amethyst,
          desc: 'The P-wave shadow zone from 105°-140° proved Earth has a core: the velocity DROP at the CMB from ~13.7 to ~8.1 km/s refracts waves steeply downward, emptying the shadow zone of direct arrivals. The S-wave shadow beyond 105° to 180° proved the outer core is liquid (μ = 0). Oldham identified both shadow zones in 1906; Gutenberg placed the CMB at 2,900 km depth in 1914. Lehmann discovered the inner core in 1936 from PKIKP arrivals inside the shadow zone. PKP phases arrive weakly in the shadow zone via complex outer-core paths. PKIKP arrives ~2 seconds earlier along the polar path than the equatorial path — the seismic signature of inner-core anisotropy.',
          examples: `P-wave shadow zone: 105°-140° from epicentre receives no direct P; only weak diffracted Pdiff (along CMB) and PKP phases. S-wave shadow: 105°-180°; absence of S arrivals = direct proof of liquid outer core. CMB depth: 2,891 km (modern value); Gutenberg 1914 estimated 2,900 km from P travel times. Lehmann 1936 "P\'" paper: proposed solid inner core from PKIKP arrivals in shadow zone. Inner-core anisotropy: ~2 s polar-equatorial PKIKP travel-time anomaly first measured by Poupinet et al. (1983).`,
        },
        {
          name: 'Seismic Tomography — Imaging Earth\'s Interior',
          icon: Activity,
          color: BRAND.jade,
          desc: 'Seismic tomography maps three-dimensional velocity anomalies in the mantle by inverting thousands of travel-time residuals — the difference between observed and predicted arrival times. Waves that arrive early passed through anomalously fast (cold) material; waves arriving late passed through slow (hot) material. Like a medical CT scan that uses X-rays from many angles to reconstruct a 3D image, tomography uses earthquake sources and seismograph stations distributed globally to reconstruct velocity structure at ~100 km lateral resolution. Slow anomalies reveal hot upwellings under mid-ocean ridges and hotspots; fast anomalies image cold subducting slabs penetrating deep into the mantle.',
          examples: 'Farallon Plate: fast anomaly beneath eastern North America at 500-1,000 km depth — the ghost of a plate subducted 50-80 Ma ago, still cold enough to be visible. Hawaii hotspot: slow anomaly (hot plume) extending ~2,000 km into lower mantle. Subducting Pacific slab under Japan: fast anomaly tracking slab geometry to ~660 km, then flattening at transition zone. Global tomography models: PREM (Dziewoński & Anderson 1981), S40RTS, TX2005 — constrain mantle temperature and flow. Resolution: ~100 km laterally in well-sampled regions, ~200-300 km in oceanic regions.',
        },
      ],
    },
    {
      type: 'visualization',
      title: 'From earthquake source to antipodal station: seismic ray paths through Earth',
      body: `A single earthquake simultaneously launches seismic energy along every possible downward ray angle. Shallow rays curve through the crust and uppermost mantle, returning to the surface at nearby stations and revealing the Moho. Steeper rays arc through progressively deeper mantle, sampling the transition zone and the base of the lower mantle before emerging at 10°-100° from the epicentre. The steepest rays hit the core-mantle boundary and either reflect (PcP, ScS) or refract into the outer core, emerging beyond 140° as PKP phases. A fraction of PKP waves penetrate the solid inner core as PKIKP and resurface within the shadow zone at 150°-180°. Each path segment samples a different depth and temperature, and the sum of all travel-time records — from thousands of global stations for thousands of earthquakes — is the dataset that seismic tomography inverts to produce three-dimensional maps of Earth\'s interior.`,
      interaction: {
        type: 'flow-simulator' as const,
        description: `tracing seismic ray paths from earthquake source through Earth\'s crust, mantle, core, and inner core to receiving stations at different angular distances`,
        nodes: [
          {
            id: 'earthquake-source',
            label: 'Earthquake Source (Hypocenter)',
            description: 'Elastic rebound along a fault releases strain energy accumulated over years or decades, launching seismic waves simultaneously in all downward directions. The angular distance to any receiving station is measured in degrees from the epicentre (the point on the surface directly above the hypocenter). Each ray angle corresponds to a different angular distance at the surface, with shallower rays returning nearby and steeper rays traveling deeper and further.',
            color: BRAND.ruby,
          },
          {
            id: 'crustal-path',
            label: 'Crustal P Waves (0°-10°)',
            description: 'Direct P-waves travel through the crust at ~6.5 km/s and arrive first at stations within a few hundred kilometres. Beyond a crossover distance of roughly 3-5 times the crustal thickness (~100 km for 35 km crust), head waves critically refracted along the Moho at ~8.0 km/s overtake the direct wave. This is exactly the crossover that Mohorovičić measured in 1909, calculating the Moho depth from the crossover distance and the two wave velocities.',
            color: BRAND.coral,
          },
          {
            id: 'mantle-path',
            label: 'Mantle-Refracted Waves (10°-100°)',
            description: `Rays entering the mantle are bent into smooth concave-upward arcs by the continuous velocity increase from ~8 km/s in the uppermost mantle to ~13.7 km/s just above the CMB. These rays carry the primary direct P and S arrivals at stations 10°-100° away, accounting for most of the world\'s seismograph stations. Travel-time curves for these phases are the primary dataset for constructing reference Earth velocity models such as PREM.`,
            color: BRAND.gold,
          },
          {
            id: 'shadow-zone',
            label: 'P-Wave Shadow Zone (105°-140°)',
            description: 'No direct P-waves arrive at stations 105°-140° from the earthquake. Rays that would have reached this zone are refracted steeply downward at the CMB by the velocity drop from ~13.7 km/s (lower mantle) to ~8.1 km/s (outer core), deflecting them into the core rather than toward the shadow zone. Only very weak diffracted Pdiff waves creeping along the CMB and complex PKP phases arrive here. The shadow zone was the first seismic proof of a distinct, liquid outer core.',
            color: BRAND.amethyst,
          },
          {
            id: 'outer-core-path',
            label: 'Core-Penetrating Waves (PKP, SKS)',
            description: `P-waves entering the outer core at angles steeper than the critical angle are refracted toward Earth\'s centre by the initial velocity drop at the CMB, then bent back outward as velocity rises to ~10.4 km/s at the base of the outer core, eventually emerging at distances beyond 140°. SKS phases involve an S-wave converted to P at the CMB, traveling through the outer core as P, then converting back to S on exit — a powerful tool for measuring upper-mantle anisotropy.`,
            color: BRAND.accent,
          },
          {
            id: 'inner-core-path',
            label: 'Inner Core Waves (PKIKP, 150°-180°)',
            description: 'Some PKP rays penetrate the solid inner core boundary and travel as PKIKP through iron at ~11 km/s, faster than the ~10 km/s outer core velocity. This velocity increase focuses PKIKP back toward the surface, producing arrivals inside the shadow zone at 150°-180°. The ~2 s travel-time difference between polar and equatorial PKIKP paths directly measures inner-core anisotropy. Inge Lehmann identified these unexpected arrivals in 1936 and correctly inferred a solid inner core.',
            color: BRAND.jade,
          },
        ],
        edges: [
          { from: 'earthquake-source', to: 'crustal-path',    label: 'direct P and S waves through 35-70 km crust; head waves critically refract along Moho at ~8 km/s' },
          { from: 'earthquake-source', to: 'mantle-path',     label: 'waves refract into faster mantle; continuous velocity gradient curves paths back to surface at 10°-100°' },
          { from: 'mantle-path',       to: 'shadow-zone',     label: 'waves approaching shadow zone are bent downward by velocity drop at CMB; region between 105°-140° receives no direct arrivals' },
          { from: 'mantle-path',       to: 'outer-core-path', label: 'waves steeper than critical angle enter outer core; velocity drops to ~8.1 km/s; refracted toward Earth\'s centre then back out' },
          { from: 'outer-core-path',   to: 'inner-core-path', label: 'some PKP waves penetrate inner core; velocity rises in solid inner core (~11 km/s); emerge in shadow zone region at 150°-180°' },
          { from: 'inner-core-path',   to: 'shadow-zone',     label: 'PKIKP waves arrive inside shadow zone; time anomaly between polar and equatorial paths reveals inner core anisotropy' },
        ],
      },
    },
    {
      type: 'quiz',
      questions: [
        {
          q: 'Andrija Mohorovičić discovered the Moho in 1909 by analysing travel times of waves from a Croatian earthquake. Stations close to the earthquake received direct crustal waves first, but distant stations received waves from the Moho first. What seismic principle explains this crossover, and what is it called?',
          a: [
            'This is the seismic head-wave (or refraction) principle: when a wave encounters a faster layer below, waves hitting the boundary at the critical angle travel along the boundary as "head waves" at the faster velocity of the lower layer, continuously radiating energy back up into the upper layer at the critical angle; beyond the crossover distance (~3-5× the depth to the interface), head waves arrive before direct waves because they travel the extra horizontal distance at the higher velocity; Mohorovičić used this crossover distance and the velocity of the head wave (v₂ ≈ 8.0 km/s) along with the time intercept to calculate the depth and velocity of the mantle',
            'This is total internal reflection: waves traveling in the faster lower layer are reflected back upward by the slower crust above, creating a guided wave that accumulates energy along the Moho and then leaks upward at all distances equally; Mohorovičić measured the amplitude of these reflected waves rather than their travel times to determine the Moho depth; the principle is the same as optical fibre transmission',
            'This is the S-P time principle applied to reflected phases: Mohorovičić observed that PmP reflections (P-waves reflected off the Moho) arrived before direct P-waves at all stations, and used the ratio of PmP to direct P amplitudes to calculate the impedance contrast at the Moho; the crossover refers to where PmP amplitude exceeds direct P amplitude',
            'This is dispersion: longer-wavelength waves penetrate deeper into the mantle and travel faster than shorter-wavelength direct crustal waves; Mohorovičić measured the frequency content of arrivals at each station and used the dispersion curve to infer the velocity jump at depth; the crossover distance is where long-wavelength mantle waves arrive before short-wavelength crustal waves',
          ],
          correct: 0,
          explain: 'Option A correctly describes the head-wave (seismic refraction) principle. When a seismic wave hits a boundary at exactly the critical angle i_c = arcsin(v₁/v₂), it travels along the boundary at the faster velocity v₂, continuously re-radiating energy upward at the critical angle. At short distances from the source, direct waves through the upper layer (at v₁) win because the head wave must travel extra horizontal distance to the boundary and back. Beyond the crossover distance x_cross ≈ 2d√((v₂+v₁)/(v₂-v₁)) — where d is the depth to the interface — the faster velocity v₂ of the head wave more than compensates for the longer path, and the head wave arrives first. The crossover distance formula (equivalently, d ≈ (x_cross/2)√((v₂-v₁)/(v₂+v₁))) is what Mohorovičić used to calculate the ~54 km depth beneath Croatia. The same principle is used globally today in seismic refraction surveys for mineral exploration (detecting ore bodies), groundwater mapping (finding the water table), and engineering site investigations (detecting bedrock depth). Option B confuses head waves with total internal reflection, which operates in the opposite direction (faster medium below cannot totally internally reflect into a slower medium above). Option C invents an amplitude-based method that Mohorovičić did not use. Option D confuses body-wave refraction with surface-wave dispersion, a completely different phenomenon.',
        },
        {
          q: 'The P-wave shadow zone exists between 105° and 140° from an earthquake. Why does the boundary of this zone occur at exactly 105° rather than at a different angle?',
          a: [
            'The 105° boundary corresponds to the angular distance at which P-waves traveling at the steepest possible angle through the mantle just graze the core-mantle boundary; rays shallower than this critical trajectory curve through the mantle and emerge at <105°; rays steeper penetrate into the outer core and are refracted so sharply (due to the velocity drop from ~13.7 to ~8.1 km/s) that they emerge only beyond ~140°; the gap from 105° to 140° thus receives neither direct mantle P nor core-penetrating P waves; the exact angles depend on the velocity profile through the mantle, which is why detailed shadow zone mapping is used to infer the velocity structure at the base of the mantle',
            'The 105° boundary is set by the S-wave critical angle at the CMB: because S-waves convert to P-waves at the core boundary, the combined S-to-P phase arrives at exactly 105° and its arrival masks any P-wave shadow beginning at that distance; 105° is therefore where the S-to-P converted phase and the direct P phase have identical travel times, not the geometric edge of the shadow zone',
            'The 105° limit is a fixed geometric property of a spherical Earth regardless of velocity structure: any sphere with uniform interior velocity would produce a shadow zone beginning at 105° because that is the angle at which rays tangent to the core intersect the surface; the observed velocity drop at the CMB is irrelevant to the shadow zone boundary location',
            'The 105° boundary occurs because the mantle P-velocity profile has a low-velocity zone near 105 km depth that acts as a waveguide; rays trapped in this waveguide travel horizontally and re-emerge at 105° epicentral distance; beyond that distance the waveguide is broken by the CMB and no further rays can reach the surface by this mechanism',
          ],
          correct: 0,
          explain: `Option A correctly identifies the geometric and physical cause of the 105° boundary. The mantle velocity profile produces a specific family of curved ray paths; the shallowest ray that just grazes the CMB returns to the surface at approximately 105°. Rays that would arrive between 105° and 140° would require paths that penetrate the CMB but exit at those intermediate distances — which is impossible because the velocity DROP at the CMB (from ~13.7 to ~8.1 km/s) causes Snell\'s law to bend all entering rays sharply downward, focusing them away from the 105°-140° range and toward 140°+. This is the opposite of total internal reflection in optics: in optics a velocity decrease (denser medium) also bends rays toward the normal (vertical), but it does not create a shadow zone; here the global spherical geometry combined with the large velocity drop conspires to create a gap. Weak Pdiff waves do arrive in the shadow zone — these are waves that diffract along the CMB rather than reflecting or transmitting, analogous to light bending around an opaque edge. Option B incorrectly invokes S-to-P conversion as the controlling mechanism. Option C is wrong: a sphere with uniform interior velocity would produce no shadow zone at all (all rays would converge at the antipode). Option D confuses the CMB shadow zone with the low-velocity zone in the upper mantle, which is a different and much shallower feature.`,
        },
        {
          q: 'Inge Lehmann discovered the inner core in 1936 by analysing arrivals in the P-wave shadow zone. What did she observe that required an inner core to explain?',
          a: [
            'Lehmann noticed that seismic stations within the P-wave shadow zone (105°-140°) were recording weak but real P-wave arrivals that existing models without an inner core could not explain; the existing model with only a liquid outer core predicted no P-wave arrivals at those distances; Lehmann proposed that a solid inner core with higher P-wave velocity (~11 km/s vs. ~10 km/s in the outer core) would refract waves back toward the surface, producing arrivals within the shadow zone; this PKIKP wave path was the signature she identified; her 1936 paper "P\'" was one of the most significant seismological discoveries of the twentieth century',
            'Lehmann observed that S-waves were arriving inside the shadow zone with a small but detectable amplitude, which required a zone of solid material inside the liquid outer core to convert S-waves into P-waves and refract them into the shadow zone; the S-wave arrivals could not be explained by any model with a uniform liquid core and their polarisation direction pointed directly to an inner solid boundary',
            'Lehmann measured anomalously high amplitudes of surface waves at stations in the shadow zone and correctly inferred that a high-velocity inner core was focusing Love and Rayleigh waves toward those stations via an internal lens effect; the amplitude anomaly was the diagnostic measurement, and her model was subsequently confirmed by travel-time analysis',
            'Lehmann detected a second P-wave arrival ~30 seconds after the expected PKP arrival at shadow zone stations; she interpreted this late arrival as a P-wave reflected from a solid boundary inside the outer core, and the reflection coefficient and timing together gave the inner core radius and velocity; prior to her work the secondary arrival had been dismissed as instrument noise',
          ],
          correct: 0,
          explain: `Option A correctly describes Lehmann\'s discovery. By 1936 the accepted model of Earth\'s interior included a liquid outer core (proven by the S-wave shadow zone) but no inner structure. At stations 105°-140° from large earthquakes — the P-wave shadow zone — existing theory predicted silence for direct P-waves. Lehmann, working with hand-calculated travel times from European seismograph records, noticed weak but consistent P-wave arrivals arriving at times that no then-existing model could explain. She systematically tested the hypothesis that a solid sphere inside the outer core, with a velocity slightly higher than the surrounding liquid, would refract P-waves (now called PKIKP) back toward the surface inside the shadow zone. Her 1936 paper "P\'" (the phase name she used) contained minimal mathematics but rigorous observational evidence — all computed manually, decades before digital seismology or computers. The discovery is doubly remarkable for its era: Lehmann was a woman working in the 1930s with primitive instrumentation and no computing tools. The inner core radius (~1,220 km) she inferred has been refined but not substantially revised. Option B is wrong — PKJKP (inner-core S-wave) arrivals were not what Lehmann detected; they were identified much later and are extremely weak. Options C and D describe physically plausible but historically inaccurate mechanisms; surface-wave focusing and double-bounce reflections were not Lehmann\'s observations.`,
        },
        {
          q: 'Seismic tomography reveals that P-wave velocities beneath subducting oceanic slabs are ~1-2% higher than the surrounding mantle. What does this velocity anomaly indicate, and why does cold lithosphere produce faster seismic waves?',
          a: [
            'Higher velocity in subducted slabs indicates they are colder than the surrounding mantle; temperature decreases the elastic moduli K and μ, so cold slabs at the same depth have higher K and μ relative to warmer ambient mantle, yielding higher v_P = √((K + 4μ/3)/ρ); additionally, subducted oceanic basaltic crust transforms to eclogite at high pressure, a mineralogy with intrinsically high P-wave velocity; together the thermal and mineralogical effects account for the observed 1-2% fast anomaly',
            'Higher velocity in subducted slabs indicates they contain more water than the surrounding mantle; fluids released from the slab during subduction temporarily increase the bulk modulus of the surrounding mantle rock, and the slab itself retains residual pore-fluid pressure that stiffens the rock; water-saturated rock has higher v_P than dry rock at the same temperature and pressure, which explains the fast anomaly',
            'Higher velocity in subducted slabs reflects their higher density rather than their temperature; denser rock transmits compressional waves faster because the increased mass per unit volume reduces the wavelength at constant frequency; the slab\'s density anomaly from iron-rich mineralogy increases v_P independently of temperature effects, which are secondary',
            'Higher velocity in subducted slabs occurs because slabs were heated at mid-ocean ridge spreading centres and carry anomalously high retained heat into the mantle; hotter rock at depth has higher seismic velocity because thermal expansion increases the spacing between crystal lattice planes, reducing phonon scattering and increasing elastic wave speed; the fast anomaly therefore marks the hottest rather than the coldest parts of the mantle',
          ],
          correct: 0,
          explain: 'Option A correctly identifies both the thermal and mineralogical causes of fast velocity in subducting slabs. Temperature reduces the elastic moduli of rock: hotter atoms vibrate with larger amplitude, making it easier to compress or shear the crystal lattice (lower K and μ). Subducted oceanic lithosphere may be 600-800 K colder than the ambient mantle at the same depth for tens of millions of years after subduction, because the thermal diffusivity of rock is very low (~10⁻⁶ m²/s) and the mantle is a poor thermal conductor. This temperature deficit raises K and μ relative to the surrounding mantle, increasing v_P by roughly 0.3-0.5% per 100 K temperature decrease — enough to account for a significant fraction of the observed 1-2% anomaly. The second factor is eclogite mineralogy: subducted oceanic basalt (originally ~7 km thick) transforms under pressure to eclogite, a dense garnet-clinopyroxene rock with v_P of ~8.5-9.0 km/s — faster than the surrounding peridotite mantle at the same pressure and temperature. The Farallon Plate subducted beneath North America from ~200 Ma to ~30 Ma and is now imaged as a fast anomaly at 500-1,000 km depth beneath the eastern United States — a slab graveyard visible in global tomography models. Option B is wrong: water generally decreases seismic velocity (it reduces the shear modulus and can weaken grain boundaries); fluids in pore spaces decrease v_P in the crust. Option C is wrong: higher density alone DECREASES velocity for the same moduli (v_P = √((K+4μ/3)/ρ) — ρ is in the denominator). Option D inverts the temperature-velocity relationship: higher temperature decreases seismic velocity, not increases it.',
        },
        {
          q: `The inner core is seismically anisotropic: P-waves traveling parallel to Earth\'s rotation axis are ~3-4% faster than those traveling through the equatorial plane. What does this anisotropy reveal about the inner core\'s physical state, and what are the proposed mechanisms?`,
          a: [
            'Anisotropy implies the inner core has a preferentially aligned crystal structure rather than randomly oriented crystals; iron in the inner core at those conditions (hexagonal close-packed, hcp ε-iron) has intrinsic directional seismic properties because its non-cubic crystal structure transmits elastic waves faster along certain crystal axes; if hcp iron crystals are preferentially aligned with their fast axis parallel to Earth\'s rotation axis — whether from solidification in a rotation-aligned magnetic field, slow convection within the inner core, or differential inner-core rotation of ~0.3-0.5°/yr faster than the mantle — the bulk P-wave anisotropy emerges as observed',
            'Anisotropy in the inner core is caused by density layering: the inner core solidified in concentric shells of progressively different iron alloy composition, with each shell having a slightly different bulk modulus; waves traveling along the rotation axis cross more shell boundaries than equatorial waves and experience more reflections, making them appear to travel faster; the anisotropy therefore reflects compositional layering rather than crystal alignment',
            'The inner-core anisotropy indicates the inner core is partially molten: a mushy zone of solid iron dendrites interspersed with liquid iron channels produces fast wave propagation along the rotation axis because convective liquid flow is driven by Earth\'s rotation and preferentially aligns the liquid channels parallel to the spin axis, creating a channeled-flow waveguide effect; the ~3-4% speed difference measures the fraction of liquid iron in the mushy zone',
            'Inner-core anisotropy is produced by the geomagnetic field: the Lorentz force on electrons in the highly conducting inner-core iron creates an effective elastic anisotropy at seismic frequencies; P-waves parallel to the magnetic dipole axis (which aligns closely with the rotation axis) experience constructive interference from Lorentz-force electron oscillations, whereas equatorial waves experience destructive interference; the anisotropy magnitude directly measures the inner-core magnetic field strength',
          ],
          correct: 0,
          explain: `Option A correctly identifies both the physical mechanism (crystal alignment) and the leading proposed causes. Hexagonal close-packed iron (hcp ε-iron, stable at the inner core\'s extreme pressure of ~360 GPa and temperature of ~5,000-6,000 K) is inherently anisotropic because its hexagonal crystal structure has a c-axis along which P-waves travel ~4-5% faster than perpendicular to it. If hcp iron crystals throughout the inner core are randomly oriented, the aggregate bulk anisotropy cancels to zero. The observed ~3-4% bulk anisotropy therefore requires preferential alignment of crystal c-axes roughly parallel to Earth\'s rotation axis. Three proposed mechanisms generate this alignment: (1) Solidification texturing — as the inner core grows by freezing from the outer core, crystals may preferentially align their fast axis parallel to the rotation axis if the magnetic field or thermal gradient guides crystal nucleation. (2) Inner-core convection — slow solid-state convection within the inner core, driven by internal heat and the outer-core boundary conditions, could align crystals by deformation analogous to olivine alignment in the mantle. (3) Differential rotation — the inner core appears to rotate ~0.3-0.5°/yr faster than the mantle (constrained by tracking PKIKP travel-time anomalies over decades), implying ongoing dynamic coupling between inner core and outer core that could maintain crystal alignment. Option B is wrong: compositional layering creates velocity discontinuities, not the smooth directional anisotropy observed for PKIKP. Option C invents a mushy-zone channeled-flow mechanism that has no observational support and misattributes the fast direction to liquid flow rather than crystal alignment. Option D is physically incorrect: the Lorentz force on electrons operates at electromagnetic frequencies (GHz), not seismic frequencies (0.001-1 Hz), and cannot produce measurable elastic anisotropy at seismic wavelengths.`,
        },
      ],
    },
  ],
}

export default seismicWavePropagation
