import { Flame, Globe, Mountain } from 'lucide-react'
import { BRAND } from '@/lib/brand'
import type { Lesson } from './types'

const eruptionClassification: Lesson = {
  id: 'volc-101-1-2-1',
  title: 'Eruption Classification: VEI and Eruption Styles',
  track: 'vol',
  trackName: 'Volcanology',
  level: 'Beginner',
  duration: '11 min',
  xpReward: 140,
  description: "Volcanic eruptions range from the gentle outpouring of lava at Kīlauea to the apocalyptic explosions of Tambora and Toba. A systematic classification of eruption styles — and the Volcanic Explosivity Index — allows volcanologists to compare eruptions across time and space and communicate hazard levels to the public.",
  sources: [
    { org: 'USGS',     title: 'Volcano Hazards — Eruption Styles',                         url: 'https://volcanoes.usgs.gov/vhp/types_eruptions.html' },
    { org: 'SI-GVP',   title: 'Smithsonian GVP — Eruption Catalog',                       url: 'https://volcano.si.edu/search_eruption.cfm' },
    { org: 'OpenStax', title: 'Physical Geology — Volcanic Eruption Types (CC-BY 4.0)',   url: 'https://openstax.org/books/physical-geology-2e' },
    { org: 'USGS',     title: 'Volcanic Explosivity Index — Overview',                     url: 'https://volcanoes.usgs.gov/vhp/about_volcanoes.html' },
    { org: 'AGI',      title: 'Glossary of Geology — Eruption Types',                     url: 'https://www.americangeosciences.org/' },
  ],
  sections: [
    {
      type: 'intro',
      title: 'Putting eruptions on a scale',
      body: `Every volcanic eruption is unique — but volcanologists have developed a systematic classification of eruption types that organises their variety into meaningful categories based on the physical behaviour of the erupting magma, the height and character of the eruption column, and the types of volcanic products deposited. These classifications carry names that often commemorate famous historical examples: **Strombolian** (after the island of Stromboli, which has erupted almost continuously for 2,000 years), **Plinian** (after Pliny the Elder, who died observing the 79 CE eruption of Vesuvius, and Pliny the Younger, whose eyewitness letters describe the event in detail), **Hawaiian** (after Kīlauea's characteristically effusive eruptions), and **Vulcanian** (after Vulcano island, near Sicily).

The **Volcanic Explosivity Index (VEI)**, developed by volcanologists Chris Newhall and Steve Self in 1982, provides a single logarithmic scale (0 to 8+) that quantifies eruption size based on the volume of erupted material and the height of the eruption column. Like the Richter scale for earthquakes (or the decibel scale for sound), each unit on the VEI scale represents a tenfold increase in erupted volume. A VEI 2 eruption (like most of Stromboli's bursts) involves <10⁷ m³ of material; a VEI 8 (supervolcanic, like the Toba eruption of ~74,000 years ago) involves >10¹² m³ — a million times more material. The VEI is particularly valuable for historical and prehistoric eruptions where direct measurements are impossible — geologists can estimate VEI from the thickness and extent of ash deposits.

Together, the named eruption styles and the VEI allow volcanologists to communicate both the qualitative character (what the eruption looks like, what products it generates, what hazards it poses) and the quantitative scale (how much material was erupted, how high the column reached) of any volcanic event past or present.`,
      keyTerms: [
        { term: 'Volcanic Explosivity Index (VEI)', def: 'A logarithmic scale (0–8+) measuring eruption size based primarily on the volume of erupted tephra and the height of the eruption column. Each VEI unit = ~10× increase in volume. VEI 0–1: gentle effusive; VEI 2–3: moderate explosive; VEI 4: major (Eyjafjallajökull 2010); VEI 5: Plinian (Mt. St. Helens 1980); VEI 6: colossal (Pinatubo 1991); VEI 7: super-colossal (Tambora 1815, 71,000 deaths); VEI 8: mega-colossal (Toba 74 ka, 2,800 km³).' },
        { term: 'Hawaiian eruption',    def: 'Effusive eruption of very fluid basaltic lava from a central vent, lava lake, or fissure. Generates lava fountains (50–500 m height), lava flows, and small amounts of spatter. Low VEI (0–1). Very little explosive activity; gases escape easily. Named after Kīlauea and Mauna Loa eruption style. The "safest" volcanic eruption type from the perspective of immediate explosive hazard.' },
        { term: 'Strombolian eruption', def: 'Rhythmic, discrete explosive bursts from a basaltic or basaltic andesitic vent, producing incandescent volcanic bombs, scoria, and ash to heights of 100–200 m. VEI 1–3. Named after Stromboli (Italy), the "Lighthouse of the Mediterranean," active almost continuously for >2,000 years. Explosions result from large gas slugs rising and bursting through partially solidified melt.' },
        { term: 'Plinian eruption',     def: 'The most intense sustained explosive eruption type; produces a high-rising, gas-thrust convective column of ash and pumice reaching 25–45 km altitude (into the stratosphere). VEI 5–7. Named after the 79 CE Vesuvius eruption. Driven by continuous fragmentation of highly volatile-rich, viscous silicic magma. Column collapse produces devastating pyroclastic density currents.' },
        { term: 'Vulcanian eruption',   def: 'Short-duration (minutes to hours), discrete, moderately explosive eruptions producing ash clouds, ballistic bombs, and lahars. VEI 2–3. Caused by sealing of the conduit by a lava cap or degassed magma plug, building pressure until violent rupture. Can transition to Plinian activity if the plug is completely destroyed and fresh volatile-rich magma reaches the surface.' },
      ],
    },
    {
      type: 'concept',
      title: 'Eruption style spectrum, VEI, and historical examples',
      body: `**The effusive to explosive spectrum.** All volcanic eruptions can be placed on a spectrum from purely effusive (all lava, no fragmentation) to purely explosive (all tephra, no coherent lava flows). This spectrum is controlled by three interacting factors: (1) magma viscosity (which controls how easily gas bubbles can escape); (2) the dissolved volatile content (primarily water); and (3) the rate at which magma rises through the conduit (which controls how much time bubbles have to escape before the magma reaches the surface). At one extreme: low-viscosity basaltic Hawaiian magma with low volatile content and slow ascent → entirely effusive. At the other extreme: high-viscosity rhyolitic magma with high dissolved water content and rapid ascent → catastrophically explosive Plinian or Phreatoplinian eruption. The intermediate cases are complex: basaltic magmas can be surprisingly explosive under conditions of rapid ascent or high volatile content (e.g., the 2021 Geldingadalir eruption in Iceland, which produced spectacular lava fountains from basaltic magma that degassed relatively slowly).

**Hawaiian and Fissure eruptions (VEI 0–1).** Hawaiian eruptions erupt basaltic lava at rates of 10–1,000 m³/s from central vents or along fissures. They produce lava fountains (maintained by exsolving CO₂ and SO₂ that jet the liquid lava upward) and fluid lava flows that can travel tens of kilometres. The 2018 Kīlauea LERZ (Lower East Rift Zone) eruption was a protracted Hawaiian-type fissure eruption that produced ~1.0–1.2 km³ of lava over 4 months, inundating the Leilani Estates community. Iceland's fissure eruptions (e.g., Laki 1783–84, which released 15 km³ of basalt and 122 Mt of SO₂, causing famine in Iceland and weather disruption across Europe) are the most voluminous examples of effusive basaltic eruption in recorded history.

**Strombolian eruptions (VEI 1–3).** Stromboli's characteristic explosions are produced by large gas slugs (primarily CO₂) that accumulate at the top of the lava column in the conduit. When a gas slug reaches the surface, it bursts open, throwing glowing scoria and bombs to heights of 100–200 m every 10–20 minutes. This cyclic behaviour is remarkably persistent — Stromboli has behaved this way for at least 2,000 years. Larger Strombolian bursts (paroxysmal events) occasionally send bombs and pyroclastic flows toward the inhabited southern sector of the island, killing tourists and damaging structures.

**Vulcanian eruptions (VEI 2–3).** Vulcanian eruptions are among the most hazardous in the immediate vicinity of the vent because they produce ballistic bombs that can be thrown kilometres from the vent and lateral blasts. They occur when the vent is sealed by a solidified lava cap or degassed magma plug. Volcanic gases accumulating below the cap eventually rupture it, producing a cannon-like explosion that can eject large blocks (metres in diameter) to distances of several kilometres. Vulcanian explosions at Sakurajima (Japan) — one of the world's most active volcanoes — occur dozens to hundreds of times per day, and the city of Kagoshima (population 600,000) 10 km away manages a permanent state of volcanic alert with evacuation drills, ash masks, and roof-reinforced schools.

**Plinian eruptions (VEI 5–7) and column collapse.** Plinian eruptions represent the most powerful sustained explosive eruptions. The eruption column — a vertically rising jet of ash, pumice, and hot gas — can reach 25–45 km altitude, penetrating the stratosphere. The column is initially supported by gas thrust (the kinetic energy of the erupting mixture); at higher altitudes, the hot volcanic material heats and entrained air expands, making the column buoyant enough to continue rising. The column is typically stable for minutes to hours — then, if magma supply wanes, the column collapses catastrophically. Collapse of a Plinian column produces **pyroclastic density currents (PDCs)**: fast-moving, ground-hugging avalanches of hot gas, ash, and pumice that travel at 100–700 km/h and can blanket tens of thousands of square kilometres. The 79 CE Vesuvius eruption killed Pompeii's remaining population not through ashfall but through the thermal shock and suffocation of pyroclastic surges that followed the collapse of the Plinian column. The 1991 Pinatubo VEI 6 eruption produced PDCs that travelled 15–18 km from the vent, and if not for the successful evacuation of 58,000 residents beforehand, would have killed tens of thousands.`,
      cards: [
        {
          name: 'Eruption Style Spectrum',
          icon: Flame,
          color: BRAND.ruby,
          desc: 'Hawaiian (VEI 0–1): effusive basalt, lava fountains, fluid flows. Fissure: linear vents, flood basalts. Strombolian (VEI 1–3): rhythmic gas-slug bursts, bombs/scoria, 100–200 m. Vulcanian (VEI 2–3): conduit-plug rupture, ballistic bombs, ash clouds. Peléan (VEI 3–4): dome collapse, block-and-ash flows. Plinian (VEI 5–7): towering ash column 25–45 km, column collapse → PDC. Sub-Plinian: similar but shorter column. Ultra-Plinian/Phreatoplinian: extreme Plinian enhanced by water interaction.',
          examples: 'Hawaiian: Kīlauea 2018 LERZ · Strombolian: Stromboli ongoing, Etna 2013–present · Vulcanian: Sakurajima daily, Montserrat 1995–2010 · Plinian: Vesuvius 79 CE (VEI 5), Pinatubo 1991 (VEI 6), Tambora 1815 (VEI 7)',
        },
        {
          name: 'Volcanic Explosivity Index (VEI)',
          icon: Mountain,
          color: BRAND.coral,
          desc: 'Logarithmic scale 0–8+. Each step = ~10× erupted volume. VEI 0: <10,000 m³, non-explosive. VEI 2: Eyjafjallajökull 2010 (0.25 km³ tephra). VEI 4: Ruapehu 1996. VEI 5: Mt. St. Helens 1980 (1.2 km³). VEI 6: Pinatubo 1991 (5 km³). VEI 7: Tambora 1815 (50 km³, 71,000 deaths, "Year Without a Summer"). VEI 8: Toba ~74 ka (2,800 km³). Frequency inversely proportional to size: VEI 7 ~ once per century, VEI 8 ~ once per 100,000 years.',
          examples: 'Eyjafjallajökull 2010: VEI 4, caused 20+ days of European aviation disruption despite modest eruptive volume · Tambora 1815: so much aerosol injected that 1816 was "Year Without a Summer" in Europe and North America · Toba 74 ka: possibly contributed to human population bottleneck (10,000–50,000 survivors)',
        },
        {
          name: 'Plinian Column and Pyroclastic Density Currents',
          icon: Globe,
          color: BRAND.jade,
          desc: 'Plinian column: gas-thrust (lower) + convective (upper) → 25–45 km. Stable for minutes to hours. Column collapse → pyroclastic density currents (PDCs): 100–700 km/h, 300–800°C, kill by thermal shock + asphyxiation. Types of PDC: pyroclastic flows (dense, valley-following), pyroclastic surges (dilute, can overtop ridges), block-and-ash flows (dome collapse). Ignimbrite: the rock deposited by a large PDC. Can reach 15–100 km from vent.',
          examples: 'Vesuvius 79 CE: surges killed Pompeii after column collapsed (surges overwash ridges, explain buried city) · Pinatubo 1991: PDCs reached 18 km, covered 400 km² · Mt. Pelée 1902: nuée ardente (pyroclastic surge) killed 30,000 in St. Pierre, Martinique in minutes',
        },
      ],
    },
    {
      type: 'quiz',
      questions: [
        {
          q: "The 2010 eruption of Eyjafjallajökull volcano in Iceland (VEI 4) caused 20 consecutive days of aviation disruption across Europe, grounding 100,000 flights and affecting 10 million passengers. The 1991 eruption of Mt. Pinatubo in the Philippines (VEI 6) was 100 times larger by eruptive volume. Yet Eyjafjallajökull caused far more economic disruption to aviation. What factors explain this seeming paradox?",
          a: [
            "Pinatubo's eruption was larger but shorter in duration; the ash cloud dispersed within 24 hours because of the high VEI column that injected material directly into the jet stream where it was rapidly diluted; Eyjafjallajökull's lower VEI column kept ash in the troposphere where it lingered for weeks",
            "Eyjafjallajökull's eruption was phreatomagmatic — involving glacial ice water interacting with the magma — which produced a particularly fine-grained, abrasive ash that persisted as a coherent aerosol cloud for weeks; combined with the volcano's unfortunate location beneath the main transatlantic and European air traffic corridors at altitudes of 7–12 km, the ash cloud shut down European airspace for weeks; Pinatubo's VEI 6 column injected most ash into the stratosphere (>20 km), above aircraft cruise altitude",
            "Pinatubo was in the Philippines, far from major aviation hubs; even a VEI 8 eruption in the Philippines would have less impact on aviation than a VEI 3 eruption in Iceland, which sits beneath the busiest air traffic corridor in the world; the paradox is entirely geographical",
            "European governments overreacted to Eyjafjallajökull due to poor understanding of volcanic ash hazards; the ash concentration was actually too low to damage aircraft engines, and the prolonged closure was a policy failure rather than a genuine hazard; Pinatubo caused less aviation disruption because Asian regulators had more experience with volcanic ash",
          ],
          correct: 1,
          explain: "The claim that Pinatubo's column dispersed in 24 hours (A) is incorrect — Pinatubo's stratospheric injection of sulfate aerosols persisted for ~2 years and caused measurable global cooling; and the jet stream at cruise altitude dispersed Eyjafjallajökull's ash continuously across Europe, it did not reduce the aviation impact. Geographical location alone (C) does not fully explain the paradox — while Iceland's location is important, it doesn't explain why the ash cloud was so persistent and extensive; the ash cloud covered Europe to the Urals and lasted weeks due to specific atmospheric dynamics. Policy overreaction (D) misrepresents the hazard — volcanic ash genuinely destroys jet engines by melting in turbine hot sections (>1,000°C) and re-solidifying on turbine blades; the aviation industry had real historical precedent (British Airways Flight 9 lost all four engines in 1982 flying through Galunggung ash over Indonesia). The correct answer is B: two factors combined to make Eyjafjallajökull disproportionately disruptive. First, the eruption was phreatomagmatic — the erupting basaltic andesite interacted with the ~200 m thick Eyjafjallajökull ice cap, producing extremely fine-grained glassy ash particles that are particularly dangerous to jet engines (finer particles stay airborne longer and penetrate turbine compressors more easily). Second, the eruption column height (~9 km, in the upper troposphere) placed ash directly into the principal European air traffic corridors at cruise altitude (8–12 km). Pinatubo's VEI 6 column rose to ~35 km altitude, injecting most material well into the stratosphere — above aircraft cruise altitude; the aviation impact of Pinatubo was primarily from surface ashfall, not from an ash cloud at cruise altitude.",
        },
        {
          q: "Stromboli's eruptions have occurred almost continuously for 2,000+ years with a characteristic rhythm of explosive bursts every 10–20 minutes. What mechanism drives this rhythmic Strombolian activity, and why does this eruption style produce incandescent bombs but not a sustained explosive column like a Plinian eruption?",
          a: [
            "Stromboli's rhythmic explosions are driven by tidal forces — the gravitational pull of the Moon and Sun creates pressure fluctuations in the magma column every ~15 minutes that trigger degassing and explosion; the regularity of Strombolian activity is tied to tidal cycles rather than internal magma dynamics",
            "Stromboli erupts basaltic magma with low enough viscosity that most gas (primarily CO₂) escapes gradually; occasionally, a large CO₂-rich gas slug accumulates in the upper conduit; when this slug reaches the surface and ruptures through the low-viscosity basaltic lava cap, it throws incandescent lava fragments upward in a burst; the low magma viscosity means the explosion is brief (the slug bursts and is gone), not sustained; without a high-viscosity melt that traps continuous gas fragmentation, no Plinian column develops",
            "Stromboli's eruptions are not truly cyclic — they appear rhythmic because only explosive events are reported; between explosions, Stromboli erupts continuously but the lava flows are submarine and not observable from land; the reported 10–20 minute rhythm corresponds to the interval between large enough explosions to be noted by observers",
            "Stromboli maintains Plinian-scale eruptions at depth — the 10–20 minute rhythm corresponds to the time needed for a Plinian column to collapse, quench, and rebuild; the fact that Stromboli appears to have only modest Strombolian surface activity is because the main Plinian column is directed laterally into the ocean rather than vertically",
          ],
          correct: 1,
          explain: "Tidal forcing (A) has been investigated as a possible modulator of volcanic activity and does show some statistical correlation with eruption timing at some volcanoes, but it is not the primary mechanism of Stromboli's Strombolian bursts — the gas slug model (B) better explains the observed behaviour. Between-explosion submarine eruptions (C) are not the explanation — Stromboli's active craters are at ~750 m altitude on the subaerial portion of the volcano; the 10–20 minute burst interval is documented by continuous monitoring, not just by intermittent observation. Lateral Plinian columns (D) are not a real phenomenon — Plinian columns are vertical due to the buoyancy dynamics of hot gas-solid mixtures. The correct answer is B: the Strombolian mechanism is driven by large gas slugs rising through a low-viscosity basaltic melt. CO₂, SO₂, and H₂O exsolve from the basaltic magma as it rises in the conduit; because the viscosity is low, large bubbles can form and rise through the melt faster than the melt itself ascends (slug flow regime). These large gas slugs (typically 1–10 m in diameter) accumulate and coalesce in the upper conduit. When a slug reaches the magma surface in the crater, it ruptures the thin solidified lava crust or the surface of the lava lake, throwing glowing lava fragments (bombs, scoria) upward. The explosion is brief — the slug is gone in seconds. The next burst occurs when another slug has risen through the melt — typically 10–20 minutes. The entire process requires low viscosity (allowing slug rise) and a persistent lava column in the conduit (providing material to fragment). Plinian eruptions require the opposite: high viscosity that traps gas throughout the entire melt column, sustained rapid decompression that continuously fragments the entire melt, not just occasional gas slug ruptures.",
        },
        {
          q: "The 1902 eruption of Mt. Pelée, Martinique resulted in one of the deadliest volcanic disasters in history when a pyroclastic surge (nuée ardente) destroyed the town of St. Pierre and killed approximately 30,000 people in minutes. The eruption had been building for weeks with warning signs including increasing fumarolic activity and phreatic explosions. Why were the warnings not acted upon, and what physical properties of the pyroclastic surge made it so lethal?",
          a: [
            "The warnings were recognised but dismissed because Martinique's governor was conducting an election campaign in St. Pierre and ordered residents to stay; the pyroclastic surge's lethality came from its unusually high lava temperature — the surge was essentially a fountain of liquid basaltic lava at 1,200°C that directly incinerated everything in its path",
            "Political factors delayed evacuation — the governor and local authorities downplayed the hazard for political reasons; the pyroclastic surge's lethality derived from its combination of extreme speed (100–300+ km/h), high temperature (300–700°C), and mobility — as a dilute, turbulent suspension of hot gas and fine ash, it was not constrained by topography, flowed around buildings, and killed by thermal shock and asphyxiation simultaneously; no basement or shelter provided protection",
            "The warnings were not available — 1902 predates modern volcano monitoring; no seismometers or gas sensors existed; the only warning was the eruption itself on the morning of May 8, which produced the surge without any prior significant unrest; modern monitoring would have provided days of warning",
            "Most residents survived in basements and reinforced buildings; the reported 30,000 deaths were mostly from a secondary tsunami triggered by the eruption and the collapse of the coastal cliffs into the sea; the pyroclastic surge itself was survivable with adequate shelter",
          ],
          correct: 1,
          explain: "The pyroclastic surge at Pelée was not liquid lava (A) — it was a dilute suspension of hot gas and fine volcanic ash and fragments; basaltic lava is not involved in the Pelée case (Pelée's magma was andesitic). Montserrat's pyroclastic flows destroyed Plymouth in 1997, but liquid lava was not the killing mechanism — thermal shock and asphyxiation from hot ash and gas were. Mt. Pelée had significant unrest for weeks before the climactic eruption (C is factually incorrect) — there were fumaroles, phreatic explosions, and ash falls; the local meteorological station reported ash accumulation; there was indeed warning, but it was misinterpreted and the response was inadequate. Basements and reinforced buildings provided some protection in some 79 CE Pompeii-style surge events, but at Pelée the surge temperature was high enough (300–700°C) to kill even protected individuals through hyperthermia and inhaled hot gas; the one survivor in the condemned cells jail (Auguste Cyparis, who had a thick stone cell with only a small ventilation hole) is the exception that proves the rule. The tsunami claim (D) is not a significant factor in Pelée's death toll. The correct answer is B: the Pelée disaster is a textbook case of the interaction between political decision-making and volcanic hazards. Governor Louis Mouttet and the scientific committee he assembled did minimise the hazard publicly to prevent voters from leaving St. Pierre before the May 11, 1902 election. The geologist who was sent to assess the volcano, Professor Gaston Landes, returned to St. Pierre (despite privately advising his wife to leave). The pyroclastic surge's specific physical properties made it uniquely lethal: unlike lava flows (which can be outrun) or ash falls (which can be sheltered from), pyroclastic surges are dilute turbulent hot gas-ash clouds that travel faster than any vehicle (100–300 km/h), have temperatures of 300–700°C, and are not constrained by topography — they flow around buildings, through windows, and into cellars. Death occurs within seconds from thermal shock and respiratory failure from inhaling hot gases and ash that vitrify in lung tissue.",
        },
        {
          q: 'The April 1815 eruption of Tambora (Indonesia) is assigned VEI 7, while the June 1991 eruption of Pinatubo (Philippines) is assigned VEI 6. The VEI scale is logarithmic, meaning each step represents approximately a tenfold increase in erupted volume. What does this difference in VEI imply about the comparative scale of these two eruptions, and what eruption parameter other than volume is required to fully describe Tambora\'s greater global climatic impact?',
          a: [
            'VEI 7 is only one unit higher than VEI 6, so Tambora was only about 10% larger than Pinatubo in terms of erupted volume; the difference is relatively minor; Tambora\'s greater climatic impact was entirely due to its location at a lower latitude, which placed its eruption column directly in the intertropical convergence zone, spreading aerosols more efficiently around the globe',
            'Tambora (VEI 7) erupted approximately 10 times more material than Pinatubo (VEI 6) — roughly 50 km³ vs. ~5 km³ of dense rock equivalent; however, erupted volume alone does not determine climatic impact; the stratospheric SO₂ injection — which determines how much sulfate aerosol enters the long-residence stratosphere — is the critical additional parameter; Tambora injected an estimated 60 Mt of SO₂ into the stratosphere compared with ~20 Mt for Pinatubo, producing a proportionally larger and longer-lasting aerosol veil and the more severe climate forcing that caused the 1816 "Year Without a Summer"',
            'The VEI scale measures eruption column height, not erupted volume, so VEI 7 means Tambora\'s column was 10 times taller than Pinatubo\'s; a taller column injects ash into a higher altitude in the atmosphere, where it can remain for longer; Tambora\'s greater climatic impact is therefore entirely explained by its taller eruption column',
            'Tambora and Pinatubo had similar climatic impacts — both caused approximately 0.5°C of global cooling for 1–2 years; the one-unit VEI difference reflects only a modest difference in erupted volume and does not correspond to any significant difference in climate forcing; VEI differences of a single unit are within the uncertainty of the scale and should not be interpreted as indicating meaningful differences in eruption size',
          ],
          correct: 1,
          explain: 'A one-unit VEI difference represents approximately a tenfold (not 10%) increase in erupted volume — the scale is logarithmic, not linear (A incorrectly characterises the magnitude of the difference; 10 times larger is the correct implication of a one-unit VEI step). The VEI scale is based primarily on erupted volume (tephra volume), not eruption column height — column height is a secondary parameter that correlates with VEI but is not its definition (C misidentifies what VEI measures). Tambora and Pinatubo did not have similar climatic impacts — Tambora caused ~0.4–0.7°C global cooling and the documented agricultural disaster of 1816, while Pinatubo caused ~0.5°C cooling for 2 years; the Tambora event was measurably more severe and longer-lasting, consistent with its larger SO₂ injection (D contradicts the historical and instrumental record). The correct answer is B: the VEI difference correctly implies Tambora erupted roughly 10 times more material than Pinatubo (~50 km³ vs ~5 km³ DRE). But volume alone is an incomplete descriptor of climatic impact because what matters for cooling is the amount of SO₂ injected into the stratosphere, not the total magma volume. SO₂ per unit volume of magma varies with magma composition and pre-eruptive volatile content — a volatile-rich magma erupts more SO₂ per cubic kilometre than a volatile-poor one. Tambora's magma carried exceptionally high sulfur contents, releasing an estimated 60 Mt SO₂ — about 3 times more than Pinatubo's 20 Mt despite being only ~10 times larger in volume. This disproportionately large SO₂ injection, combined with the greater total volume, produced a more persistent and optically thicker stratospheric aerosol layer, driving the severe multi-year climate anomaly of 1816. The ratio of SO₂ to erupted volume (the "yield" of SO₂) is therefore a critical parameter for assessing the climatic significance of historical and prehistoric eruptions.',
        },
      ],
    },
  ],
}

export default eruptionClassification
