import { Activity, Gauge, AlertTriangle, Globe, TrendingUp } from 'lucide-react'
import { BRAND } from '@/lib/brand'
import type { Lesson } from './types'

const monitoringVolcanoes: Lesson = {
  id: 'volc-101-1-4-4',
  title: 'Monitoring Volcanoes and Forecasting Eruptions',
  track: 'vol',
  trackName: 'Volcanology',
  level: 'Beginner',
  duration: '14 min',
  xpReward: 150,
  description: `Forecasting volcanic eruptions is one of the most demanding scientific challenges in natural hazards: the stakes are measured in lives, the signals are often ambiguous, and the decision to evacuate hundreds of thousands of people is both scientifically and politically fraught. Modern volcano observatories integrate seismology, geodesy, gas geochemistry, satellite remote sensing, and probabilistic modelling to detect the subtle precursors of impending eruptions — sometimes giving days to weeks of warning, sometimes none at all. The discipline has saved hundreds of thousands of lives; it has also failed catastrophically.`,
  sources: [
    { org: 'USGS', title: 'USGS Volcano Hazards Program — Monitoring Methods', url: 'https://volcanoes.usgs.gov/vhp/monitoring.html' },
    { org: 'USGS', title: 'USGS Volcano Disaster Assistance Program (VDAP)', url: 'https://www.usgs.gov/programs/VHP/volcano-disaster-assistance-program' },
    { org: 'SI-GVP', title: 'Smithsonian GVP — Global Volcanism Monitoring Catalogue', url: 'https://volcano.si.edu' },
    { org: 'OpenStax', title: 'Physical Geology — Volcanic Monitoring and Prediction (CC-BY 4.0)', url: 'https://openstax.org/books/physical-geology-2e' },
    { org: 'IAVCEI', title: 'IAVCEI — Probabilistic Volcanic Hazard Assessment Protocols', url: 'https://www.iavcei.org' },
  ],
  sections: [
    {
      type: 'intro',
      title: 'The science and art of eruption forecasting',
      body: `On June 12, 1991, the Philippine Institute of Volcanology and Seismology (PHIVOLCS) raised the alert level at Mt. Pinatubo to Level 5 — "eruption in progress" — and ordered the evacuation of all residents within 30 km (19 mi). Approximately 58,000 people left. Three days later, on June 15, one of the largest eruptions of the 20th century tore open a new 2.5 km (1.6 mi)-wide caldera and sent a 35 km (22 mi) eruption column into the stratosphere. The evacuation saved an estimated 5,000–20,000 lives. It is the defining success story of applied volcanology — a demonstration of what becomes possible when scientific monitoring, expert interpretation, institutional authority, and community trust all work together.

But the Pinatubo success did not come easily, and it does not represent the norm. Pinatubo had not erupted for approximately 500 years; the monitoring network was hastily deployed in April 1991, just weeks before the catastrophic eruption. The scientists working the crisis made correct interpretations from limited data under enormous time pressure. Other crises have not ended so well: the 1985 Armero disaster (23,000 dead despite a hazard map existing and warnings being issued); the 2019 Whakaari eruption (22 killed on a commercial volcano tour with no precursory seismic warning). Eruption forecasting is simultaneously capable of astonishing achievements and humbling failures.

Modern volcano monitoring integrates five primary data streams: **seismicity** (earthquake patterns that track magma movement), **ground deformation** (inflation and deflation of volcanic edifices from magma intrusion), **gas geochemistry** (volcanic gas emissions that directly sample the degassing magma), **thermal monitoring** (infrared imaging of erupting lava and hydrothermal systems), and **satellite remote sensing** (InSAR ground deformation, SO₂ monitoring, thermal anomalies from orbit). No single data stream is diagnostic of impending eruption; it is the convergence of multiple lines of evidence — and the expert integration of their patterns over time — that allows eruption forecasting. The challenge is not only scientific but also communicative: translating probabilistic scientific assessments into actionable decisions for civil protection authorities and ultimately for the public.`,
      keyTerms: [
        { term: 'Seismic monitoring', def: 'The use of networks of seismometers deployed around a volcano to detect and classify volcanic earthquakes. Key earthquake types: volcano-tectonic (VT) earthquakes — high-frequency (5–15 Hz) events caused by brittle fracture of rock as magma intrudes; long-period (LP) earthquakes — low-frequency (0.5–5 Hz) events caused by resonance of fluid-filled cracks or conduits; harmonic tremor — sustained, near-continuous low-frequency vibration indicating persistent magmatic fluid flow; hybrid earthquakes — mixed high-low frequency events. Increasing frequency, upward migration of hypocentres, and transition from VT to LP/tremor are classic pre-eruptive signals. The USGS Hawaiian Volcano Observatory has operated the world\'s longest continuous volcanic seismic record since 1912.' },
        { term: 'Ground deformation monitoring', def: 'Measurement of the inflation (uplift) or deflation (subsidence) of a volcanic edifice caused by movement of magma at depth. Techniques: GPS networks (millimetre-precision; continuous real-time telemetry); InSAR (Interferometric Synthetic Aperture Radar — satellite-based, centimetre-scale deformation measured over areas of thousands of km²); tiltmeters (electronic sensors detecting micro-radians of inclination change on volcanic flanks); EDM (Electronic Distance Measurement) and levelling surveys (episodic, high-precision). Ground inflation from magma intrusion is a primary eruption precursor; deflation during or after eruption tracks magma withdrawal. InSAR from Sentinel-1, ALOS-2, and NISAR satellites enables monitoring of all Earth\'s volcanoes from orbit.' },
        { term: 'Volcanic gas monitoring', def: 'The measurement of gas emissions from volcanic vents and fumaroles to characterise degassing of the underlying magma. Key gas species: SO₂ (sulphur dioxide — a magmatic volatile that does not dissolve in groundwater; its presence indicates degassing magma at shallow depth); CO₂ (carbon dioxide — less soluble in magma, exsolves at greater depth; CO₂:SO₂ ratio indicates magma depth); H₂S; HCl; HF. Measurement methods: DOAS (Differential Optical Absorption Spectroscopy — SO₂ flux from UV light absorption), COSPEC (older SO₂ flux instrument), MultiGAS (in-situ multi-species sensor), soil CO₂ flux measurements, satellite TROPOMI (global SO₂ detection from orbit). SO₂ flux increasing from near-zero to hundreds of tonnes/day is a primary indicator of fresh magma entering the shallow system.' },
        { term: 'Volcanic alert level', def: 'A standardised scale communicating the current state of volcanic unrest and eruption probability to emergency managers, the public, and aviation. Systems vary: USGS uses Normal → Advisory → Watch → Warning for ground hazards plus Green → Yellow → Orange → Red colour codes for aviation; Philippines (PHIVOLCS) uses Level 0 (quiet) → Level 5 (eruption underway); New Zealand (GeoNet) uses 0–5; many countries use 4-level systems. Each level triggers pre-planned protective actions under civil protection protocols. Alert levels are not purely scientific statements — they are communication tools that must balance scientific uncertainty with the practical requirements of emergency management, public communication, and institutional decision-making.' },
        { term: 'Probabilistic eruption forecasting', def: 'A formal framework for estimating the probability of specific eruption scenarios and their consequences within a defined time window, using Bayesian methods and event tree analysis. Event trees assign probabilities to sequential decision nodes (e.g., probability of eruption within 30 days given current unrest; probability that eruption will be VEI ≥4; probability that a PDC will reach a specific community). The Bayesian Event Tree for Eruption Forecasting (BET_EF) framework, developed after the 1994 Merapi eruption and refined by researchers including Warner Marzocchi, is now used operationally at several high-risk volcanoes. Explicitly communicating probability estimates — including uncertainty ranges — to civil protection authorities is essential for informed decision-making.' },
      ],
    },
    {
      type: 'concept',
      title: 'The five data streams of volcano monitoring and how they are integrated',
      body: `**Multi-parameter monitoring: why no single signal is sufficient.** Modern volcano observatories do not rely on any single type of measurement to assess eruption likelihood. This is not a limitation but a recognition that volcanic systems are complex and that no single physical signal is uniquely diagnostic of impending eruption: earthquake swarms occur without eruptions; ground inflation can reflect hydrothermal pressure rather than magma intrusion; SO₂ flux increases can result from shallow degassing without connection to a new magma batch. The power of modern monitoring lies in the **convergence** of multiple independent lines of evidence. A volcano showing increasing seismicity, simultaneously inflating ground surface, rising SO₂ flux, and upward migration of earthquake hypocentres is exhibiting a multi-parameter convergence that provides far stronger grounds for eruption forecasting than any one signal alone.

**Seismicity patterns and their interpretation.** Volcanic seismicity is one of the most sensitive indicators of subsurface magmatic activity, with modern seismometers capable of detecting earthquakes as small as M-1.0 at distances of tens of kilometres. The key interpretive framework is the **seismicity sequence**: (1) Initial VT earthquake swarms at 5–15 km (9.3 mi) depth indicate brittle fracture of rock as magma intrudes; (2) VT seismicity migrating upward (from 10 km (6.2 mi) to 5 km (3.1 mi) to 2 km (1.2 mi) depth) tracks the ascent of magma; (3) Transition from VT to LP earthquakes (in the 0.5–5 Hz frequency band) indicates a change from brittle fracture to fluid-resonance mechanisms — magma or gas is now moving through a conduit; (4) Onset of harmonic tremor (sustained low-frequency vibration, often sounding like a musical tone on a seismogram) indicates continuous fluid flow through the conduit system and is frequently the most direct seismic precursor of actual eruption onset. The 57-day precursory seismic sequence at Pinatubo moved through all four of these stages between April 2 and June 15, 1991.

**Gas geochemistry: sampling the magma from the surface.** Volcanic gas measurements provide a direct chemical "window" into the state of the underlying magmatic system. **SO₂** is particularly diagnostic: it is a volatile that is highly soluble in magma at depth (kept in solution by pressure) but exsolves readily as magma rises and pressure drops. At a volcano that normally shows near-zero SO₂, the sudden appearance of significant SO₂ flux (hundreds to thousands of tonnes per day) is a reliable indicator that fresh, volatile-rich magma has entered the shallow system. At Pinatubo, SO₂ flux of 500 tonnes (551.0 tons)/day measured on May 13, 1991 was the first clear chemical signal that a new magma batch was degassing — a key data point in the decision to escalate monitoring. By June 12–13, SO₂ flux had risen to 13,000 tonnes (14326.0 tons)/day, confirming rapidly increasing magma flux to the shallow system just before the climactic eruption. The **CO₂:SO₂ ratio** is a complementary indicator: CO₂ exsolves from magma at greater depth than SO₂; a high CO₂:SO₂ ratio indicates a magma source at greater depth, while a low ratio indicates shallow degassing. This ratio can track the ascent of magma toward the surface over weeks to months.

**Satellite remote sensing: a global monitoring network.** Over the past two decades, satellite-based instruments have transformed volcanic monitoring, particularly for the ~1,400+ historically active volcanoes that have limited or no ground-based monitoring. The Sentinel-1 SAR satellites (ESA) provide repeat-pass InSAR coverage of all Earth's volcanoes every 6–12 days, allowing detection of centimetre-scale ground deformation at monitored and unmonitored volcanoes globally. The TROPOMI instrument on Sentinel-5P measures SO₂ from the full globe daily, detecting volcanic SO₂ plumes from eruptions above ~1,000 tonnes (1102.0 tons)/day. The MODVOLC and MIROVA thermal monitoring systems detect elevated surface temperatures from erupting lava or intensifying hydrothermal activity at night. Together, these satellite systems constitute a de facto global volcano monitoring network that can detect unrest at remote, unmonitored volcanoes before ground-based monitoring is deployed.`,
      cards: [
        {
          name: 'Seismicity: VT, LP, and Harmonic Tremor',
          icon: Activity,
          color: BRAND.ruby,
          desc: 'VT (volcano-tectonic) earthquakes: 5–15 Hz; brittle fracture of rock by magma intrusion; initial stage of unrest. LP (long-period) earthquakes: 0.5–5 Hz; resonance of fluid-filled cracks; indicates magmatic fluid moving through conduit. Harmonic tremor: sustained, near-continuous vibration; conduit flow established; most direct eruptive precursor. Hybrid events: mixed VT/LP; transition state. Seismicity migration: upward migration of hypocentres (from 10 km (6.2 mi) to 2 km (1.2 mi)) tracks magma ascent. Classic sequence: VT swarms → LP transition → tremor onset → eruption. Pinatubo 1991: full VT→LP→tremor sequence over 57 days. Seismometer network density: 10–30 stations for major observatory; real-time telemetry via satellite.',
          examples: 'Pinatubo April 7 (first seismometer deployed) → May 13 (LP earthquakes begin) → June 7 (dome breaks surface) → June 12 (tremor onset, Level 5) → June 15 (climactic eruption) · Kīlauea 2018: seismic sequence tracked magma migration 35 km (22 mi) from summit to lower East Rift Zone in 3 weeks · Unzen 1991 (Japan): LP tremor began Feb 11, dome appeared Feb 12 — 1-day warning · Whakaari 2019: zero precursory seismicity before phreatic explosion — demonstrating limits of seismic monitoring for hydrothermal events',
        },
        {
          name: 'Ground Deformation: GPS, InSAR, and Tiltmeters',
          icon: Gauge,
          color: BRAND.gold,
          desc: 'GPS: mm-precision, real-time continuous. Detects magma intrusion as dome-shaped uplift pattern (Mogi model: single spherical source at depth). InSAR: Sentinel-1 SAR, 6–12 day repeat, cm-precision, covers 1,000s km². Tiltmeters: µrad precision, sensitive to near-surface magma movements. EDM/levelling: high-precision episodic surveys. Deflation: magma withdrawal or eruption. Inflation: magma intrusion or volatile accumulation. Source depth estimation: GPS network + Mogi model inversion gives source depth, volume change. Yellowstone 2004–06: 70 cm (27.6 in) uplift in 2 years (largest recorded) → attributed to sill intrusion at ~15 km (9.3 mi). Campi Flegrei: 3+ m cumulative uplift 2005–present (bradyseism).',
          examples: 'InSAR detected Bardarbunga (Iceland) dyke intrusion 48 km (30 mi) laterally in 2 weeks before 2014–15 fissure eruption → 2 weeks advance warning · Pinatubo: no GPS in 1991; EDM surveys showed minimal deformation before eruption (shallow source, fast ascent) — illustrating that absence of deformation ≠ no risk · Kīlauea 2018: summit GPS showed 0.5 m (2 ft) subsidence in 3 months as magma drained to LERZ · Long Valley: 75 cm (29.5 in) resurgent dome uplift since 1980 — ongoing without eruption',
        },
        {
          name: 'Gas Monitoring and Satellite Surveillance',
          icon: TrendingUp,
          color: BRAND.amethyst,
          desc: 'SO₂ flux (DOAS/COSPEC): tonnes/day; increases from near-zero signal fresh magma. CO₂:SO₂ ratio: high = deep source; low = shallow degassing; ratio decreasing = magma ascending. TROPOMI (Sentinel-5P): global SO₂ detection daily, detects any eruption >1,000 t/day SO₂. MODVOLC/MIROVA: thermal anomaly detection from MODIS/VIIRS. Sentinel-1 InSAR: global deformation, 6–12 days. Advantage of satellites: monitors all ~1,400+ Holocene active volcanoes regardless of ground network; can detect unrest at unmonitored volcanoes before crisis begins. Pinatubo SO₂: 500 t/day (May 13) → 13,000 t/day (June 12–13) → eruption June 15. SO₂ increase was key decision point for escalating alert.',
          examples: 'TROPOMI detected Raikoke (Kuril Islands, Russia) SO₂ plume June 21, 2019 from an unmonitored volcano — detected hours after eruption began · Sentinel-1 InSAR: detected Kilauea LERZ ground subsidence before 2018 eruption, tracked fissure zone daily · Ongoing unrest detected by InSAR at >30 volcanoes simultaneously by automated algorithms (COMET/Volcano Observatory Notifications) · VDAP rapid deployment can supplement satellite data with ground network within days of unrest onset at unmonitored volcanoes',
        },
      ],
    },
    {
      type: 'concept',
      title: 'Probabilistic forecasting, alert levels, and the false alarm problem',
      body: `**Probabilistic eruption forecasting and event trees.** Because volcanic eruptions cannot be predicted with certainty, modern volcanology has moved toward **probabilistic forecasting** — formally expressing eruption likelihood as a probability (e.g., "40% chance of eruption within the next 7 days given current unrest") with explicitly stated uncertainty. The primary tool is the **event tree**: a branching diagram that assigns probabilities to sequential decision nodes, starting with broad conditions (probability of continued unrest) and narrowing to specific outcomes (probability of eruption occurring, given unrest; probability of eruption being VEI ≥4, given eruption; probability that a PDC reaches community X, given a VEI 4 eruption). The **BET_EF** (Bayesian Event Tree for Eruption Forecasting) framework operationalises this approach, combining long-term eruption frequency statistics with short-term monitoring data through Bayesian updating. A key feature of the Bayesian approach is that as new monitoring data arrives, probabilities are updated continuously — the forecast improves as the crisis develops.

**Alert levels: science, communication, and governance.** Volcanic alert levels are the primary tool for translating scientific assessments into protective actions. In most national systems, each alert level is linked to pre-planned protective actions: Normal/Green: routine monitoring; Advisory/Yellow: enhanced monitoring, public information; Watch/Orange: evacuation of high-hazard zones, standby for broader evacuation; Warning/Red: full evacuation, emergency response. These levels must balance two competing risks: **false alarms** (evacuating when no eruption follows — causing economic disruption, social stress, and erosion of public trust in future warnings) versus **missed eruptions** (failing to issue timely warnings — causing preventable deaths). The asymmetry between these costs makes alert level decisions one of the most challenging judgment calls in applied science: the societal cost of a missed eruption (hundreds to thousands of deaths, as at Armero 1985) is catastrophically higher than the cost of a false alarm, but repeated false alarms make communities less likely to respond to genuine future warnings.

**The Pinatubo success and the Armero tragedy: contrasting outcomes.** The contrast between Pinatubo 1991 and Armero 1985 defines the spectrum of volcanic crisis outcomes. At Pinatubo: monitoring network deployed within weeks of first unrest; PHIVOLCS worked closely with the USGS VDAP team; multiple monitoring parameters converged on the same conclusion; alert levels were escalated progressively; the government issued evacuation orders that were obeyed; 58,000 people left before the climactic eruption. At Armero: the hazard was known (a hazard map showing Armero in a lahar zone had been published months before the eruption); the eruption scenario (ice-cap melt, lahar down the Lagunillas River) had been predicted by volcanologists; the eruption began at 9 PM local time (most residents asleep); sirens activated 30 minutes before the lahar arrived; the Catholic Church broadcast reassuring messages over the radio; civil defence officials gave contradictory guidance. Of ~29,000 residents, >23,000 died. The contrast is not primarily scientific — it is about the chain of communication from scientific assessment through institutional authority to individual protective action.

**Phreatic explosions: the limits of current forecasting.** The most serious current limitation of volcanic monitoring is the inability to forecast **phreatic explosions** — sudden, violent eruptions driven by the flash conversion of groundwater or hydrothermal fluid to steam, without any involvement of fresh magma. Because phreatic explosions are not driven by magma intrusion, they do not generate the standard precursory signals (seismicity migration, ground deformation, SO₂ rise). The September 27, 2014 explosion at Mt. Ontake (Japan) — which killed 63 hikers with no warning — showed no detectable precursory seismicity in the minutes before the explosion (though a small earthquake swarm had occurred 10 days prior). The December 9, 2019 explosion at Whakaari/White Island (New Zealand) — which killed 22 commercial tourists — also occurred without standard precursory signals. These events have forced a fundamental reassessment of the safety protocols for human access to active volcanic environments, even at volcanoes with established monitoring networks.`,
      cards: [
        {
          name: 'Probabilistic Forecasting and Event Trees',
          icon: Gauge,
          color: BRAND.coral,
          desc: 'Probabilistic eruption forecast: formal probability estimate with uncertainty range for specific eruption scenarios within defined time window. Event tree: decision-node diagram assigning probabilities at each branch (unrest → eruption → magnitude → hazard impact). BET_EF framework: Bayesian updating as new data arrives. Key advantage: explicitly communicates uncertainty to decision-makers rather than false certainty. Long-term eruption frequency: e.g., "erupts on average once per 100 years" → baseline annual probability 1%. Monitoring data: Bayesian updating raises probability during unrest episode. ~50% of significant volcanic unrest episodes globally do not result in eruption — the base rate for "false alarms" is high.',
          examples: 'Pinatubo: no formal probabilistic framework in 1991 — scientists used expert judgment; PHIVOLCS decision to issue Level 5 was based on multi-parameter convergence judged by experienced volcanologists · Merapi 2010: BET_EF applied; probability of PDC reaching specific communities updated daily; informed evacuation zone boundaries · Campi Flegrei: formal probabilistic hazard assessment published by INGV; updated as unrest evolves · Etna: Monte Carlo simulations of lava flow paths; eruption frequency statistics inform aviation warning thresholds',
        },
        {
          name: 'Alert Levels: The False Alarm Problem',
          icon: AlertTriangle,
          color: BRAND.jade,
          desc: 'False alarm costs: economic disruption (evacuees lose income, businesses close); social stress; erosion of public trust ("cry wolf" effect reduces future compliance). Missed eruption costs: preventable deaths, infrastructure destruction. The asymmetry: one missed eruption (Armero: 23,000 dead) vs. many false alarms. Alert level frameworks: USGS 4-level; PHIVOLCS 0–5; GeoNet 0–5. Pre-planned actions at each level must be agreed before crisis. Community drills and education: essential for compliance when alarms are issued. Communication chain failures (Armero): scientists → government → media → public each link can fail. Volcanologist\'s obligation: communicate assessment, including uncertainty, clearly; not make the evacuation decision.',
          examples: 'Mammoth Lakes CA (Long Valley) 1982: USGS hazard notice → economic damage ~$700 million; no eruption; mayor filed lawsuit against USGS · Merapi 2010: 400,000 evacuated, 367 died (mostly those who returned early against instructions) · Rabaul 1994: 11 years unrest → Sept 19 eruption; 75,000 evacuated same day; 5 died (remarkable success given short warning) · Agung (Bali) 2017: 100,000 evacuated twice over 3 months before major eruption; compliance high due to community education',
        },
        {
          name: 'Phreatic Explosions: The Unforecastable Hazard',
          icon: Globe,
          color: BRAND.accent,
          desc: 'Phreatic explosion: driven by steam from superheated groundwater; no juvenile magma. Hazard: ballistic projectiles (boulders ejected 3–5 km (3.1 mi)), pyroclastic surge, burial. Forecasting problem: no standard seismic/deformation/gas precursors; hydrothermal systems fluctuate continuously; specific explosion threshold cannot be predicted. Ontake 2014: 63 dead on hiking trail; 10-day-prior small seismic swarm not acted upon (ambiguous signal). Whakaari 2019: 22 dead on commercial tour; zero precursory signals; commercial operators had open access under low alert level. Response: post-Ontake Japan significantly restricted crater access; post-Whakaari NZ reformed tourism risk management. Research direction: borehole strainmeters, fluid pressure sensors may provide minutes of warning.',
          examples: 'Ontake 2014: Saturday midday in hiking season; 63 dead, ~69 injured; all deaths from ballistic impacts and surge burial within 500 m (1640 ft) of crater; no magmatic material in deposits · Whakaari 2019: 22 of 47 visitors killed; New Zealand WorkSafe prosecutions of tour operators and Whakaari Management Ltd; NZ court found GNS Science not liable · Ruapehu 1995/1996: phreatic eruptions with ~45 sec precursory tremor detected — LAHAR early warning system gave 30 min warning of resulting lahar · Post-Whakaari: NZ review led to risk assessment framework requiring explicit calculation of visitor risk thresholds',
        },
      ],
    },
    {
      type: 'visualization',
      title: 'The eruption forecasting decision chain: from monitoring to protective action',
      body: `This flow traces the path from multi-parameter monitoring data through scientific interpretation, probabilistic assessment, and institutional alert level decisions to community protective action — the complete chain that determines whether monitoring data translates into lives saved.`,
      interaction: {
        type: 'flow-simulator' as const,
        description: 'The complete eruption forecasting decision chain from monitoring data acquisition to community protective action, showing where the chain can succeed or fail',
        nodes: [
          { id: 'n1', label: 'Multi-Parameter Monitoring', description: 'Real-time data streams from seismometer networks (VT, LP earthquakes, tremor), GPS and tiltmeters (ground deformation), DOAS spectrometers (SO₂ flux), InSAR satellites (broad deformation), MODVOLC (thermal), and fumarole geochemistry (CO₂:SO₂ ratio). Data telemetered continuously to volcano observatory. Baseline characterisation: background activity must be known to identify anomalies — years of pre-crisis data are invaluable.', color: BRAND.accent },
          { id: 'n2', label: 'Scientific Interpretation', description: 'Volcanologists at the observatory review multi-parameter data streams, identify anomalies and trends, and integrate them within a physical model of the volcano\'s magmatic system. Key questions: Is seismicity increasing? Is it migrating upward? Has SO₂ flux risen? Is the ground inflating at a single coherent source? Do multiple independent parameters point in the same direction? Expert judgment remains essential — no algorithm fully replaces this integration.', color: BRAND.coral },
          { id: 'n3', label: 'Probabilistic Assessment', description: 'Scientists estimate the probability of eruption within defined time windows (24 hours, 7 days, 30 days) using Bayesian event tree methods. Uncertainty ranges are explicitly quantified. Assessment considers: long-term eruption frequency (base rate), current monitoring anomalies (likelihood ratio), magmatic system state (melt fraction, volatile saturation, stress conditions). Assessment is communicated to civil protection authorities with uncertainty clearly stated.', color: BRAND.gold },
          { id: 'n4', label: 'Alert Level Decision', description: 'Civil protection authorities, in consultation with scientists, assign the current alert level. This is a joint scientific-governance decision: scientists provide the hazard assessment; authorities make the protective action decision considering societal factors (population, economy, political context). Pre-established protocols link each alert level to specific mandatory protective actions. Alert level changes are communicated publicly and to aviation authorities.', color: BRAND.ruby },
          { id: 'n5', label: 'Communication to Public', description: 'Alert level and its meaning is communicated to the public through: official government statements, media briefings, social media, local emergency sirens, and community radio. The communication chain from observatory to individual citizen must be clear, fast, and trusted. Pre-crisis community education is critical — populations who understand volcanic hazards comply better with evacuation orders. Ambiguous or contradictory messages (as at Armero 1985) can cause fatal hesitation.', color: BRAND.amethyst },
          { id: 'n6', label: 'Community Protective Action', description: 'Individuals and communities respond to the alert through evacuation, sheltering, or remaining in place depending on their zone designation. Success depends on: prior drills (populations know where to go), infrastructure (roads passable, evacuation vehicles available), trust in authorities (built over years, not days), and social factors (property concerns, cultural attachment to land). The Pinatubo 1991 evacuation succeeded because PHIVOLCS had community trust and pre-planned protocols. The Armero 1985 failure occurred despite correct scientific warnings.', color: BRAND.jade },
        ],
        edges: [
          { from: 'n1', to: 'n2', label: 'real-time data' },
          { from: 'n2', to: 'n3', label: 'anomaly detection' },
          { from: 'n3', to: 'n4', label: 'probability estimate' },
          { from: 'n4', to: 'n5', label: 'public alert' },
          { from: 'n5', to: 'n6', label: 'protective action' },
        ],
      },
    },
    {
      type: 'quiz',
      questions: [
        {
          q: 'A seismic network at a stratovolcano records the following pattern over 14 days: Days 1–4: background seismicity (3–8 VT earthquakes/day at 8–12 km (7.5 mi) depth). Days 5–9: seismicity increases to 50–80 VT/day; hypocentres at 5–8 km (5.0 mi) depth; SO₂ flux rises from ~0 to 200 t/day. Days 10–12: seismicity transitions to 40% LP earthquakes; hypocentres at 2–4 km (2.5 mi) depth; SO₂ increases to 1,200 t/day; GPS shows 4 cm (1.6 in) summit inflation. Days 13–14: harmonic tremor detected; SO₂ at 5,000 t/day; GPS shows 7 cm (2.8 in) total inflation; small ash emission from summit. What is the most defensible interpretation of this sequence and recommended alert level action?',
          a: [
            'The sequence is ambiguous — the increase in seismicity could reflect tectonic rather than volcanic activity; SO₂ increases are common near industrial facilities and do not necessarily indicate magmatic degassing; GPS inflation could result from hydrothermal thermal expansion; the alert level should remain at Normal while additional data collection continues over the next 2–4 weeks before any protective action is taken',
            'This sequence represents a textbook multi-parameter convergence toward imminent eruptive activity: Days 5–9 show a VT swarm with upward hypocentre migration and SO₂ appearance — consistent with magma ascending and degassing in the shallow system; Days 10–12 show transition to LP-dominated seismicity, continued upward migration, inflating ground surface, and significant SO₂ flux — consistent with magma establishing a conduit to shallow depths; Days 13–14 show harmonic tremor (continuous conduit flow established), very high SO₂ flux indicating rapidly degassing fresh magma, continued ground inflation, and ash emission confirming surface activity; the multi-parameter convergence is unambiguous; alert should be escalated to Watch or Warning, with immediate evacuation of proximal hazard zones and preparation for rapid escalation to full Warning if activity intensifies',
            'The sequence indicates a phreatic eruption sequence rather than a magmatic eruption — the LP earthquakes and harmonic tremor are characteristic of hydrothermal steam systems rather than magma movement; the SO₂ could be from oxidation of hydrothermal H₂S; no juvenile magmatic material has been confirmed in the ash; alert level should be raised to Advisory to warn hikers of possible steam explosion, but no community evacuation is warranted',
            'The harmonic tremor on Days 13–14 is the only truly diagnostic signal — all earlier signals are too common at volcanoes to be diagnostic; seismicity increases, SO₂ increases, and ground inflation occur frequently without eruption; only once harmonic tremor is sustained for >48 hours should protective actions be escalated; the current 14-day sequence is insufficiently advanced to justify evacuation',
          ],
          correct: 1,
          explain: 'Dismissing SO₂ flux of 1,200–5,000 t/day as potentially industrial is not tenable at a stratovolcano in a volcanic monitoring context; industrial SO₂ sources near a remote stratovolcano are implausible; hydrothermal thermal expansion does produce some ground deformation, but 7 cm (2.8 in) of inflation at the summit is far above what thermal expansion alone can explain; delaying protective action for 2–4 more weeks while activity accelerates (ash emission has already begun) would be dangerously conservative (A misapplies uncertainty as a reason for inaction). Phreatic eruptions do not produce sustained SO₂ flux of 5,000 t/day — that level of SO₂ requires juvenile magma degassing; LP earthquakes occur in both hydrothermal and magmatic systems but combined with 5,000 t/day SO₂, 7 cm (2.8 in) GPS inflation, and harmonic tremor, the magmatic interpretation is overwhelmingly more supported (C misapplies the phreatic alternative). Waiting for 48 hours of sustained harmonic tremor before escalating is inconsistent with the principle of precautionary escalation; harmonic tremor combined with ash emission, 5,000 t/day SO₂, and 7 cm (2.8 in) inflation is not an "insufficiently advanced" signal — it is an indication that eruption is in progress or imminent; waiting for further confirmation in this scenario risks lives (D applies an unreasonably high confirmation threshold). The correct answer is B: this sequence represents a classic multi-parameter precursory escalation. Each parameter independently indicates increasing magmatic activity; together, they form a convergent case that any experienced volcanologist would regard as requiring immediate escalation to Watch or Warning level. The multi-parameter convergence is the key feature: ascending seismicity, SO₂ appearance and rapid increase, GPS inflation, LP transition, harmonic tremor, and now ash — all pointing in the same direction, all accelerating. Pinatubo 1991 followed a similar but slower sequence; the appropriate response is rapid alert level escalation and proximal zone evacuation.',
        },
        {
          q: 'The 1985 Armero disaster (23,000 dead) occurred despite the following: (1) volcanologists had published a hazard map two months before the eruption showing Armero in a high-risk lahar zone; (2) the eruption scenario (summit pyroclastic flows melting the ice cap, lahar down the Lagunillas River) had been explicitly predicted; (3) volcanic activity had been escalating for months; (4) a national volcanic alert was in effect. What does this disaster reveal about the difference between scientific knowledge of volcanic hazard and actual community protection?',
          a: [
            'The Armero disaster reveals that scientific hazard maps are fundamentally useless for volcanic risk management because the public cannot interpret them; the solution is to replace scientific hazard mapping with simple binary warnings ("volcano will erupt" or "volcano will not erupt") that the public can immediately understand and act on without scientific training',
            'The Armero disaster occurred because Colombian volcanologists made an incorrect scientific prediction about the eruption timing; the eruption was smaller and faster than modelled, and the lahar traveled faster than predicted; the lesson is that volcanologists need better eruption simulation models before issuing hazard maps that influence government protective actions',
            'The Armero disaster reveals that scientific knowledge of hazard is necessary but not sufficient for community protection; the chain from scientific knowledge to life safety requires: clear, timely, and authoritative communication of risk to emergency managers; political will to issue and enforce evacuation orders; effective communication chains to the public that function at night; absence of competing reassuring messages from other authorities; and prior community education so residents understand the hazard and trust warnings; every link in this chain failed at Armero despite correct scientific knowledge at the source',
            'The Armero disaster proves that hazard maps should only be used by professional emergency managers and should not be shared with the public or the media; public access to hazard information creates panic and contradictory unofficial interpretations that undermined the official warnings at Armero',
          ],
          correct: 2,
          explain: 'Replacing detailed hazard maps with binary warnings would reduce the information available for evidence-based emergency planning; binary warnings ("will erupt / won\'t erupt") cannot capture the spatial and probabilistic nature of volcanic hazard; moreover, the failure at Armero was not that the public misread a hazard map — it was that the map\'s implications were not translated into evacuation orders that were then communicated and enforced (A misdiagnoses the problem). The Armero eruption was not incorrectly modelled — it was a VEI 3 event, smaller than some that have occurred before without generating catastrophic lahars; the lahar formed rapidly when pyroclastic surges melted the summit ice cap; volcanologists had predicted this exact scenario; the failure was not scientific miscalculation (B misattributes the cause to scientific error). Restricting hazard maps from the public and media removes transparency about risk and makes community preparedness harder, not easier; public access to hazard information, combined with explanation of its meaning, is a best practice in disaster risk reduction; withholding hazard information does not improve the communication chain — it degrades it (D proposes an approach contrary to international best practice). The correct answer is C: the Armero disaster is the textbook example of how correct scientific knowledge can fail to protect a community when the communication chain is broken. Every stage of the chain failed: (1) Scientists had issued the warning but lacked direct communication authority; (2) The civil protection director believed the eruption posed no immediate threat and delayed evacuation; (3) A local official and Catholic Church officials broadcast reassuring messages over the radio; (4) Sirens activated only 30 minutes before the lahar arrived — insufficient time at night; (5) Many residents had received conflicting messages and decided to stay. This disaster fundamentally changed how volcanology thinks about risk communication and led directly to the development of improved scientist-civil protection-public communication protocols that were applied effectively at Pinatubo six years later.',
        },
        {
          q: 'The USGS Volcano Disaster Assistance Program (VDAP) can deploy a complete volcanic monitoring network within days of unrest at any volcano in the world, providing monitoring capability where none previously existed. After a developing country requests VDAP assistance at a volcano with no prior monitoring history, the VDAP team installs seismometers, GPS, and gas sensors within 5 days of arriving. Ten days later, they observe an escalating seismic and gas signal. A critic argues: "You have no baseline data — you cannot know if this is abnormal activity." How should scientists respond to this critique?',
          a: [
            'The critic is correct — without at least 5 years of baseline monitoring data, no meaningful eruption forecast is possible; VDAP should acknowledge this limitation and provide only general hazard information without making specific eruption probability estimates; any forecast made without a baseline is irresponsible and could trigger an unnecessary evacuation',
            'The baseline argument is partially valid but does not prevent meaningful scientific assessment; many volcanic signals are diagnostic even without a pre-crisis baseline: SO₂ appearing from zero at a volcano with no previous SO₂ record is a significant anomaly regardless of baseline; VT seismicity migrating from 10 km (6.2 mi) to 2 km (1.2 mi) depth over 10 days is an anomalous pattern regardless of baseline; LP earthquakes transitioning from VT domination is a well-understood change in process that does not require comparison to historical data; some uncertainty exists, but meaningful probability estimates can be made from the monitoring data alone, combined with knowledge of eruptive behavior at similar volcanoes; a 10-day rapidly escalating signal warrants precautionary escalation regardless of baseline availability',
            'The baseline argument is irrelevant — monitoring data from any instrument is always useful, and more data is always better than less data; scientists should immediately issue a maximum-level warning and begin full evacuation based on any data showing increased activity, regardless of whether it can be compared to a baseline',
            'VDAP should not issue any eruption probability estimates at all — only PHIVOLCS or the host country national volcano observatory has the authority and responsibility to interpret monitoring data; VDAP\'s role is purely technical (installing instruments); all scientific interpretation must come from the host country agency',
          ],
          correct: 1,
          explain: 'Requiring 5 years of baseline data before any meaningful forecast is possible would make rapid-response monitoring essentially useless for acute crises; many volcanic precursory signals are recognisable from their physical character regardless of baseline; the Pinatubo VDAP deployment began in April 1991 — weeks before the June 15 eruption — and provided interpretable data immediately; waiting for years of baseline before interpreting signals is not defensible given the life-safety stakes (A overestimates the baseline requirement). Issuing maximum-level warnings based on any increased activity without baseline comparison would produce unacceptably high false alarm rates and erode public trust in all future warnings; the principle is not "more data → escalate faster" but "multi-parameter convergence toward escalation" — and that principle requires interpretation, not automatic escalation (C is poorly calibrated and would cause false alarm problems). VDAP does not merely install instruments — its scientific team actively interprets data and works collaboratively with the host country observatory; VDAP has provided real-time scientific interpretation at every major deployment, including Pinatubo, Nyiragongo, and Merapi; characterising VDAP as purely technical is inaccurate (D mischaracterises VDAP\'s operational role). The correct answer is B: the baseline critique has some validity but is not disabling. Certain volcanic signals are physically interpretable without comparison to historical baseline: an SO₂ flux of 2,000 t/day at a previously non-emitting volcano is anomalous by definition; rapidly ascending earthquake hypocentres over 10 days have a clear physical interpretation (magma ascent) regardless of prior data; LP/tremor earthquakes at a system that had only showed tectonic seismicity are a recognisable change in process. The VDAP and Pinatubo experience directly demonstrates this: the monitoring network deployed in April 1991 had no prior baseline data for Pinatubo, yet within weeks it detected the escalating precursory sequence that allowed a life-saving evacuation. The uncertainty from lack of baseline is real but must be weighed against the cost of inaction.',
        },
        {
          q: 'Ontake 2014 and Whakaari 2019 are both examples of deadly volcanic events with minimal or no precursory signals. Both occurred at volcanoes with established monitoring networks. What fundamental physical reason explains why these phreatic events were not preceded by the monitoring signals that typically precede magmatic eruptions?',
          a: [
            'Phreatic explosions were not preceded by monitoring signals because the monitoring instruments at Ontake and Whakaari were malfunctioning; properly maintained monitoring networks always detect precursory signals before any volcanic explosion, phreatic or magmatic; the lesson is that monitoring network maintenance and quality control must be improved',
            'Phreatic explosions occur at greater depths than magmatic eruptions, so their seismic signals are too deep to be detected by near-surface seismometers; the solution is to install borehole seismometers at depths of 5–10 km (6.2 mi), which would detect the signals that surface seismometers missed at Ontake and Whakaari',
            'Phreatic explosions are not preceded by standard monitoring signals because they are driven by the sudden phase transition of hydrothermal fluid to steam rather than by magma intrusion; magmatic eruptions produce VT seismicity, LP earthquakes, ground deformation, and SO₂ because magma is physically moving through rock (causing fracture and deformation) and chemically degassing; phreatic explosions are driven by fluid pressure build-up in the existing hydrothermal system, which can reach critical pressure and rupture rapidly, without the weeks-long sequence of magma ascent signals that allow forecasting of magmatic eruptions; hydrothermal systems are continuously under pressure, and the specific conditions that trigger rupture cannot be reliably monitored with current technology',
            'Phreatic explosions are always preceded by ground subsidence rather than uplift; monitoring networks at Ontake and Whakaari were designed to detect uplift (inflation) but missed the subsidence signals that precede steam-driven explosions; redesigning monitoring networks to emphasise subsidence detection would resolve the forecasting gap for phreatic events',
          ],
          correct: 2,
          explain: 'Characterising instrument malfunction as the cause overstates the reliability of monitoring networks and misattributes the failure; both Ontake and Whakaari had functioning monitoring networks that genuinely did not detect significant precursory signals; the problem is physical — the processes driving phreatic explosions do not generate the same signals as magmatic processes (A misidentifies the cause). Phreatic explosions do not occur at greater depth than magmatic eruptions — they occur at shallow depths within the hydrothermal system, which is typically the uppermost few hundred metres to a few kilometres of the volcano; the issue is not sensor depth but signal character (B misidentifies both the depth and the solution). Phreatic explosions are not systematically preceded by ground subsidence — they can occur without significant deformation in either direction; hydrothermal pressure build-up can occur in confined, small-volume fracture systems that do not produce measurable surface deformation (D is incorrect about the precursory deformation pattern). The correct answer is C: the fundamental physical reason is the difference in driving mechanism. Magmatic eruptions require: (1) magma moving physically through rock → seismicity (VT earthquakes); (2) magma intruding into shallow crust → ground deformation; (3) magma degassing SO₂ as it ascends → gas signal; these processes take weeks and produce detectable precursors. Phreatic explosions require only: pressurised hydrothermal fluid exceeding the strength of the overlying rock cap → explosive decompression. This can happen without any new magma input, without significant ground deformation, and without SO₂ emission. Hydrothermal systems fluctuate continuously in pressure and temperature; the specific fracture threshold that triggers an explosion cannot currently be predicted from surface observations. The best current approaches — borehole fluid pressure sensors, acoustic monitoring — provide at most minutes of warning, not hours or days.',
        },
        {
          q: 'A volcanic alert system that produces too many false alarms (eruption warnings followed by no eruption) risks "crying wolf" — eroding public trust so that future, genuine warnings are ignored. Yet being too conservative (not issuing warnings until eruption is certain) causes preventable deaths. How should volcanologists and civil protection authorities calibrate this trade-off, and what evidence shows that communities can maintain trust through multiple alert level cycles?',
          a: [
            'The solution is to stop using formal alert levels entirely and replace them with simple social media updates from volcanologists; alert level systems are bureaucratic and inflexible; informal real-time communication from scientists directly to the public via Twitter/X and Instagram would be more trusted and more responsive than formal government alert systems',
            'The false alarm problem is best solved by requiring 100% scientific certainty before issuing any alert above the lowest level; probabilistic uncertainty should never be communicated to the public because it confuses rather than informs; only when eruption is confirmed should alerts be issued; the Armero disaster would have been worse if an uncertain warning had been issued earlier because residents would have dismissed the later, more urgent warning',
            'The trade-off must be calibrated through ongoing community education, transparent communication of uncertainty, pre-established protocols that communities understand in advance, and building trust through the track record of the monitoring agency; evidence from Bali (Agung 2017: 100,000 evacuated twice over 3 months before major eruption with high compliance), Merapi (repeated evacuations with declining rates of non-compliance over time), and Rabaul (11 years of unrest followed by successful evacuation on eruption day) shows that trust can be maintained across multiple alert cycles when communities understand the hazard, the science, and the uncertainty; false alarms are not free — their costs must be managed — but they can be communicated as precautionary actions rather than failed predictions',
            'The false alarm problem can be solved through better monitoring technology alone; with sufficient monitoring density and artificial intelligence analysis of multi-parameter data, the percentage of correct eruption forecasts will approach 100% within the next decade, eliminating the need to communicate uncertainty; the problem is technological, not sociological',
          ],
          correct: 2,
          explain: 'Replacing formal alert systems with social media communication from individual scientists is not a realistic or reliable improvement; social media is not universally accessible (particularly in developing countries), is unverifiable, can spread misinformation, lacks the legal authority to order evacuation, and does not integrate with pre-planned emergency management protocols (A proposes an unworkable alternative). Requiring 100% certainty before issuing warnings is not scientifically achievable; eruption forecasting will always involve probability, not certainty; the Armero disaster did not occur because an uncertain warning was issued too early — it occurred because a correct (certain) warning was issued and the communication chain from scientist to community failed; waiting for absolute certainty before issuing warnings would cause far more preventable deaths (B misdiagnoses the Armero failure). Artificial intelligence and improved monitoring will improve eruption forecasting but will not approach 100% accuracy; phreatic explosions will remain difficult to forecast regardless of monitoring density; the communication and governance problems highlighted by Armero are not primarily technological problems (D overstates what technology can solve). The correct answer is C: the false alarm problem is fundamentally a trust-management and communication problem, not primarily a scientific problem. The evidence from Agung 2017 (Bali) is particularly instructive: the volcano was placed on alert and 100,000 people evacuated in September 2017; activity decreased and many returned; alert was raised again in November 2017 and another mass evacuation occurred; the volcano erupted in November–December; compliance with the second evacuation remained high because Balinese communities trusted PVMBG (Indonesia\'s geological agency), had been educated about the hazard, and understood that precautionary evacuation is not a failed prediction but a protective action taken under uncertainty. This matches the theoretical framework: false alarms are not "cries of wolf" if they are communicated honestly as precautionary actions under scientific uncertainty, supported by community education, and followed up with transparent explanations of why the eruption did not occur.',
        },
      ],
    },
  ],
}

export default monitoringVolcanoes
