import { Mountain, Layers, Zap, AlertTriangle, Globe } from 'lucide-react'
import { BRAND } from '@/lib/brand'
import type { Lesson } from './types'

const supervolcanoesAndCalderas: Lesson = {
  id: 'volc-101-1-4-2',
  title: 'Supervolcanoes and Calderas',
  track: 'vol',
  trackName: 'Volcanology',
  level: 'Beginner',
  duration: '14 min',
  xpReward: 150,
  description: `Supervolcanoes are the most powerful volcanic systems on Earth — capable of erupting hundreds to thousands of cubic kilometres of magma in events that dwarf anything in recorded human history. Understanding how calderas form, what supervolcanic systems look like today, and how scientists assess the risk they pose is essential for separating evidence-based hazard assessment from science fiction. The Yellowstone, Campi Flegrei, and Taupo systems are among the most closely monitored geological features on the planet.`,
  sources: [
    { org: 'USGS', title: 'Yellowstone Volcano Observatory — Yellowstone Caldera Monitoring', url: 'https://www.usgs.gov/observatories/yvo' },
    { org: 'SI-GVP', title: 'Smithsonian GVP — Yellowstone, Taupo, and Campi Flegrei Eruption Records', url: 'https://volcano.si.edu' },
    { org: 'USGS', title: 'USGS Volcano Hazards Program — Caldera-Forming Eruptions', url: 'https://volcanoes.usgs.gov/vhp/calderas.html' },
    { org: 'OpenStax', title: 'Physical Geology — Calderas and Supervolcanoes (CC-BY 4.0)', url: 'https://openstax.org/books/physical-geology-2e' },
    { org: 'IAVCEI', title: 'IAVCEI — Large Caldera Systems: Monitoring and Hazard Assessment', url: 'https://www.iavcei.org' },
  ],
  sections: [
    {
      type: 'intro',
      title: 'The volcanoes that reshape continents',
      body: `The word "supervolcano" does not appear in any formal volcanological classification — it is a popular term, not a scientific one. What it describes is a **caldera-forming eruption** of magnitude VEI 8 or greater, producing more than 1,000 km³ (240 cu mi) of erupted material. These events are geologically rare (occurring roughly once per 100,000 years globally) but their consequences are continental in scale: Yellowstone's last super-eruption 631,000 years ago deposited ash detectable across most of North America; the Toba eruption (~74,000 years ago) blanketed the entire Indian subcontinent in metres of volcanic ash and may have bottlenecked the human population. Understanding these systems requires understanding what a **caldera** is — not just a large crater, but the surface expression of a magmatic system that has partially evacuated its shallow magma reservoir.

A caldera forms when a volcanic eruption withdraws magma from a shallow chamber so rapidly that the overlying roof collapses. The result is a broad, flat-floored depression — typically 5–100 km (62 mi) in diameter — that bears no resemblance to the conical stratovolcano most people envision when they hear "volcano." Calderas are not primarily erosional features (like a volcanic crater widened by weathering) but structural collapses — block faulting of the roof into the emptied magma chamber. Yellowstone caldera is 45 × 85 km (53 mi); Taupo caldera is ~35 km (22 mi) across; Long Valley caldera (California) is 17 × 32 km (20 mi). None of these looks from the ground like a volcano — they are flat valleys, lakes, or broad basins that only reveal their true nature from aerial or satellite views and through geophysical investigation.

The global distribution of caldera systems and their monitoring reveals a sobering truth: most of the world's largest volcanic systems are not erupting, but they are not dead. Yellowstone has seen three super-eruptions in the past 2.1 million years (the most recent 631,000 years ago) and remains a geothermally active, seismically restless system with a large, partially molten magma body beneath it. Campi Flegrei, the caldera beneath the western suburbs of Naples (population ~3 million), has been in a state of unrest since the 1950s, with significant ground uplift episodes in 1970–72, 1982–84, and 2005–present. Understanding when caldera unrest indicates a building eruption versus long-term background activity is one of the most challenging problems in volcanology.`,
      keyTerms: [
        { term: 'Caldera', def: 'A large volcanic depression formed by the collapse of the roof of a magma chamber after a major eruption rapidly withdraws magma. Calderas differ from craters (formed by explosion or erosion) in their origin as structural collapses. They range from a few kilometres to over 100 km (62 mi) in diameter and can host lakes, geothermal fields, and subsequent eruptions of smaller scale. The term comes from the Spanish word for "cooking pot." Famous examples: Yellowstone (45 × 85 km (53 mi)), Taupo (35 km (22 mi)), Long Valley (17 × 32 km (20 mi)), Campi Flegrei (~13 km (8.1 mi)), Santorini (~12 km (7.5 mi)).' },
        { term: 'Ignimbrite', def: 'A volcanic rock formed by the deposition and welding of pyroclastic density current (ignimbrite-forming flow) material — the product of a large explosive eruption. During caldera-forming eruptions, enormous volumes of hot ash and pumice fragments cascade down the volcano\'s flanks and across the surrounding landscape, covering areas of thousands to tens of thousands of square kilometres. When deposited hot enough, the fragments weld together into a solid, glassy rock (welded ignimbrite or welded tuff). The Fish Canyon Tuff (Colorado, 27.8 Ma) is among the largest known ignimbrites, covering ~12,000 km² (4633 sq mi) to depths of >400 m (1312 ft).' },
        { term: 'Resurgent dome', def: 'An uplifted central area within a caldera formed by the re-inflation of the magma body following caldera collapse. As new magma intrudes or the remaining magma partially crystallises and exsolves gases, the caldera floor is pushed upward, creating a central dome or ring of uplift within the larger caldera depression. Resurgent domes indicate an active, recharging magmatic system. Yellowstone\'s Sour Creek and Mallard Lake domes are resurgent features; Long Valley\'s resurgent dome has uplifted ~75 cm (29.5 in) since the 1980 unrest episode.' },
        { term: 'Supervolcano (VEI 8)', def: 'An informal term for a volcanic system capable of producing eruptions of >1,000 km³ (240 cu mi) of erupted material (VEI 8 on the Volcanic Explosivity Index). Such eruptions are the largest volcanic events known on Earth outside of flood basalt provinces. Supervolcanic eruptions produce continental-scale ignimbrite sheets, global stratospheric aerosol veils (climate forcing of 5–15°C (27°F) cooling for years), and deposition of tephra (volcanic ash) detectable thousands of kilometres from the source. Identified supervolcano systems include Yellowstone (Wyoming), Toba (Sumatra), Taupo (New Zealand), Long Valley (California), and Campi Flegrei (Italy).' },
        { term: 'Caldera unrest', def: 'Episodes of seismicity, ground deformation (uplift or subsidence), and increased hydrothermal activity at a caldera system that do not necessarily lead to eruption. Caldera unrest is common at many large caldera systems and reflects the continuous dynamic interaction between magma intrusion, hydrothermal fluid circulation, and tectonic stress. The key challenge for volcanologists is distinguishing unrest driven by non-eruptive processes (hydrothermal pressure pulses, small intrusions) from unrest driven by magmatic recharge that could culminate in eruption. At Campi Flegrei, ground has uplifted more than 3 m (10 ft) since the 1950s with associated seismicity but no eruption; at Yellowstone, repeated uplift and subsidence cycles of 5–25 cm/year have been measured since the 1970s.' },
        { term: 'Ring fault', def: 'A near-vertical fault system that delimits the margins of a caldera, formed as the roof of the magma chamber collapses inward along the outline of the underlying void. Ring faults are the structural boundaries of calderas and are often expressed at the surface as concentric fault scarps or ring-shaped valleys. Post-collapse, ring faults serve as pathways for hydrothermal fluid circulation and may localise subsequent eruptive activity along the caldera rim. The ring fault system of the Aira caldera (southern Japan) is well-mapped from geophysical surveys and is associated with the still-active Sakurajima volcano erupting on the caldera rim.' },
      ],
    },
    {
      type: 'concept',
      title: 'Caldera formation mechanics and the anatomy of supervolcanic systems',
      body: `**How a caldera forms.** The mechanics of caldera collapse can be understood as a structural engineering problem: a roof — the crust overlying a large, shallow magma chamber — loses its support when the chamber below is rapidly evacuated. During a large Plinian eruption, magma is withdrawn from the chamber at rates of thousands of cubic metres per second; at some point, the magma column can no longer support the overlying rock and the roof fails along **ring faults** — near-vertical fractures that outline the margin of the chamber. The roof collapses in segments (either piecemeal block faulting or piston-like collapse of a single block), and the inward-collapsing walls feed additional material into the eruption, creating a feedback loop that dramatically intensifies the eruption rate. This collapse is not a single event but a process that may take hours to days. The subsidence can exceed 1–5 km (3.1 mi) vertically. The resulting depression, if it later fills with water, becomes a caldera lake (Crater Lake/Mt. Mazama, Oregon; Lake Taupo, New Zealand).

**The Yellowstone system: structure, history, and current monitoring.** Yellowstone is the most studied and publicly prominent supervolcano system on Earth. It sits above the Yellowstone hotspot — a mantle plume — and has produced three caldera-forming super-eruptions in the past 2.1 million years: the Huckleberry Ridge eruption (~2.1 Ma, ~2,450 km³ (588 cu mi) VEI 8), the Mesa Falls eruption (~1.3 Ma, ~280 km³ (67 cu mi) VEI 7), and the Lava Creek eruption (631,000 years ago, ~1,000 km³ (240 cu mi) VEI 8). The current Yellowstone caldera is the scar of the Lava Creek eruption — a 45 × 85 km (53 mi) depression now occupied by much of Yellowstone National Park. Geophysical imaging beneath the caldera reveals a two-tier magmatic system: a shallow (5–16 km (9.9 mi) deep) magma body with an estimated ~5–15% melt fraction (mostly crystalline mush, partially molten), underlain by a larger, deeper (20–50 km (31 mi)) basaltic magma body. The shallow mush is not a liquid magma pool — it contains too little melt to erupt. Current monitoring by the Yellowstone Volcano Observatory (YVO) records routine seismicity (earthquake swarms), ground deformation (currently ~2–3 cm/year subsidence in most areas with occasional uplift), and hydrothermal activity (Old Faithful and ~10,000 thermal features). The probability of a Yellowstone super-eruption in any given year is estimated at approximately 1 in 730,000 — far lower than the probability of a civilisation-disrupting asteroid impact.

**Campi Flegrei: unrest in a European metropolis.** While Yellowstone captures popular attention, the more immediately concerning caldera system — in terms of nearterm eruption risk and exposed population — is Campi Flegrei (literally "burning fields") in the Bay of Pozzuoli, west of Naples, Italy. The caldera hosts ~3 million people in the Naples metropolitan area; it last erupted in 1538 (Monte Nuovo, a small phreatomagmatic event). Since the 1950s, the caldera floor has experienced **bradyseism** — slow uplift and subsidence. Major uplift episodes occurred in 1970–72 (+1.7 m (6 ft)) and 1982–84 (+1.8 m (6 ft), accompanied by M4+ earthquakes and partial evacuation of Pozzuoli). Since 2005, a sustained, accelerating uplift episode has raised the caldera floor by >3 m (10 ft) total (as of 2024), accompanied by intensifying seismicity. Geochemical analyses show increasing magmatic gas contributions in hydrothermal fluids, consistent with fresh magma degassing. This does not mean eruption is imminent — Campi Flegrei has experienced many unrest episodes without erupting — but the accelerating trend has prompted Italian authorities to raise the alert level to Yellow (second of four levels) and develop evacuation plans for the Campi Flegrei "red zone" (approximately 500,000 people in the highest-hazard area).`,
      cards: [
        {
          name: 'Caldera Collapse Mechanics',
          icon: Mountain,
          color: BRAND.ruby,
          desc: 'Caldera formation requires: (1) large shallow magma chamber (volume 50–10,000+ km (6214+ mi)³); (2) very rapid magma withdrawal rate during eruption exceeding roof rock strength; (3) ring fault failure as chamber roof loses support. Collapse creates subsidence of 1–5 km (3.1 mi). Two main collapse styles: piecemeal (block faulting, irregular geometry) and piston (single coherent block, more symmetric). Collapse feeds eruption — collapsing walls displace additional magma, intensifying eruptive rate. Post-collapse: caldera floor may rebound (resurgent dome) as magma re-intrudes. Caldera diameter scales with magma chamber volume. Crater Lake (Oregon): 10 km (6.2 mi) diameter, 3,700 BP, ~50 km³ (12 cu mi) VEI 7. Yellowstone: 45 × 85 km (53 mi), 631 ka, ~1,000 km³ (240 cu mi) VEI 8.',
          examples: 'Crater Lake/Mt. Mazama: ~3,700 BP, VEI 7, ~50 km³ (12 cu mi), 10 km (6.2 mi) diameter caldera now Lake Crater Lake (depth 594 m (1949 ft)) · Pinatubo 1991: formed 2.5 km (1.6 mi) caldera in one day during June 15 climactic eruption · Santorini (Thera) ~1620 BCE: collapse may have contributed to Minoan civilisation disruption · Kilauea 2018: small caldera collapse (0.1 km³ (0.024 cu mi)), floor dropped ~500 m (1640 ft) during LERZ eruption',
        },
        {
          name: 'Yellowstone: Structure and Monitoring',
          icon: Layers,
          color: BRAND.gold,
          desc: 'Three super-eruptions: 2.1 Ma (2,450 km³ (588 cu mi)), 1.3 Ma (280 km³ (67 cu mi)), 631 ka (1,000 km³ (240 cu mi)). Caldera: 45 × 85 km (53 mi), contains most of Yellowstone NP. Magmatic system: shallow mush body 5–16 km (9.9 mi) depth (~5–15% melt), deeper basaltic reservoir 20–50 km (31 mi). ~10,000 geothermal features (geysers, hot springs, mud pots). YVO monitoring: seismic network, GPS, tiltmeters, gas sensors, InSAR (Interferometric Synthetic Aperture Radar, which detects millimetre-scale ground deformation from satellite). Routine seismicity: 1,000–3,000 earthquakes/year (mostly M<2). Ground deformation: cyclical inflation/deflation, typically 2–7 cm/year. Current eruption probability: ~1/730,000 per year. Next most likely Yellowstone event: hydrothermal explosion (like 13,800 BP Mary Bay explosion, which created a 2.6 km (1.6 mi) crater).',
          examples: '2004–2006 uplift episode: 70 cm (27.6 in) uplift in 2 years (GPS) — largest in Yellowstone history; attributed to magma intrusion at 15 km (9.3 mi) depth · 2008 earthquake swarm: >900 earthquakes in 1 week; no eruption followed · Old Faithful: erupts every 60–110 minutes; interval predicted within ±10 min from duration of previous eruption · Hydrothermal explosions: occur without warning, most recent significant one at Biscuit Basin 2024 (no injuries); far more probable than volcanic eruption',
        },
        {
          name: 'Campi Flegrei: Bradyseism and Urban Volcano Risk',
          icon: AlertTriangle,
          color: BRAND.coral,
          desc: 'Caldera: ~13 km (8.1 mi) diameter, Bay of Pozzuoli, west of Naples. Population in high-hazard zone: ~500,000; greater Naples metropolitan area: ~3 million. Bradyseism: slow uplift and subsidence from magma intrusion and hydrothermal pressure changes. Major uplift: 1970–72 (+1.7 m (6 ft)), 1982–84 (+1.8 m (6 ft), partial Pozzuoli evacuation, M4.2 earthquakes), 2005–present (+3.0+ m total, ongoing). Geochemical evidence: increasing magmatic CO₂:H₂O ratio in fumaroles, higher fumarole temperatures → fresh magma degassing. Current alert level: Yellow (gialla). Last eruption: 1538 (Monte Nuovo, phreatomagmatic, VEI 2). Magma body: ~8 km (5.0 mi) depth, partially molten rhyolitic-phonolitic composition. Pre-eruption scenario: widespread ashfall over Naples, PDCs from caldera rim vents, lahar risk.',
          examples: 'Pozzuoli archaeological record: Roman fish market (Macellum) columns preserve shoreline at different heights over 2,000 years — visual record of bradyseism · 1982–84 unrest: 40,000 residents evacuated from Pozzuoli waterfront; total uplift 1.8 m (6 ft); seismicity continued for 2 years; no eruption · 2023–24: seismicity at highest rate since 1984; including M4.2 on September 27, 2023 — felt across Naples; authorities reviewing evacuation plans · Alert level history: Green (pre-2012) → Yellow (2012–present); Orange and Red levels exist but not yet reached',
        },
      ],
    },
    {
      type: 'concept',
      title: 'Taupo, Long Valley, and distinguishing dangerous unrest from background noise',
      body: `**The Taupo volcanic zone: Earth's most productive rhyolite system.** Lake Taupo in the central North Island of New Zealand occupies a caldera formed by one of the most powerful eruptions in the past 5,000 years — the Taupo eruption of approximately 232 CE, which ejected ~35 km³ (8.4 cu mi) of material (VEI 7) in an event that devastated New Zealand's North Island and was recorded as atmospheric anomalies in Chinese and Roman historical sources. But Taupo's modern caldera is merely the latest surface expression of a volcanic system that has been active for over 300,000 years and has produced eruptions totalling ~16,000 km³ (3838 cu mi) of rhyolite over that time — more than any comparable system on Earth. The Taupo Volcanic Zone currently hosts ~18 active geothermal fields, the world's largest geothermal electricity generation infrastructure (Wairakei, Rotokawa, Ngatamariki power stations), and the Whakaari (White Island) and Ruapehu stratovolcanoes. The caldera beneath Lake Taupo shows ongoing unrest: lake level changes, GPS deformation, and occasional earthquake swarms indicate a dynamically active magmatic system below. New Zealand's GeoNet monitoring network tracks these signals in real time.

**Long Valley caldera: 40+ years of unrest management.** Long Valley caldera in eastern California (adjacent to Mammoth Lakes ski resort and town) last had a major eruption 767,000 years ago (the Bishop Tuff, ~600 km³ (144 cu mi), VEI 7) and has experienced lower-level eruptive activity as recently as ~50,000 years ago (the Inyo Craters). In 1980, a M6.0 earthquake swarm beneath the caldera, accompanied by measurable ground uplift of the resurgent dome, prompted USGS to issue a hazard watch notice that caused significant economic disruption to the Mammoth Lakes tourism economy. The unrest continued intermittently for over 40 years — ground has uplifted ~75 cm (29.5 in) at the resurgent dome since 1980, earthquake swarms recur periodically, and CO₂ degassing from the caldera floor has killed trees in Horseshoe Lake and other areas. Yet the caldera has not erupted. Long Valley is a textbook example of the "false alarm problem" in caldera monitoring: the symptoms of unrest are real, the monitoring data are accurately recorded, but the ultimate outcome (eruption vs. continued unrest without eruption) remains unpredictable over decadal timescales.

**Distinguishing magmatic recharge from non-eruptive unrest.** The central challenge of caldera monitoring is that many of the signals associated with unrest — ground deformation, earthquake swarms, gas emission increases — can be produced by both eruptive and non-eruptive processes. **Hydrothermal pressure pulses** (the heating and expansion of water in the geothermal system by deeper heat sources, without fresh magma involvement) can cause ground uplift and seismicity indistinguishable from magma intrusion signals in short-duration monitoring records. Magmatic intrusions that do not reach the surface (dyke injections that stall at depth) also produce these signals without leading to eruption. The key discriminators that volcanologists use to assess whether unrest represents escalating magmatic recharge include: (1) **geochemical change** — increasing magmatic gas ratios (CO₂:SO₂, He-3:He-4) indicate fresh magma contribution; (2) **seismicity character** — volcanic tremor and LP earthquakes are more directly associated with magmatic fluid movement; (3) **deformation geometry** — GPS and InSAR patterns that match inflation of a single deep source are more consistent with magma intrusion than distributed hydrothermal signals; (4) **acceleration** — sustained, accelerating uplift rates (rather than cyclical ups-and-downs) are more concerning than episodic unrest.`,
      cards: [
        {
          name: 'Taupo: World\'s Most Productive Rhyolite System',
          icon: Globe,
          color: BRAND.amethyst,
          desc: 'Location: Central North Island, New Zealand; 232 CE Taupo eruption (~35 km³ (8.4 cu mi), VEI 7) formed the modern Lake Taupo caldera. Total Taupo system output: ~16,000 km³ (3838 cu mi) rhyolite in 300,000 years — highest rhyolite flux anywhere. Adjacent TVZ (Taupo Volcanic Zone) geothermal fields power ~25% of New Zealand\'s electricity (Wairakei, Rotokawa). Ongoing monitoring: lake level changes ±1 m (3 ft) recorded, GPS deformation, seismic network. The 232 CE eruption: column reached ~50 km (31 mi), devastated ~20,000 km² (7722 sq mi) of North Island; ash detected in Chinese chronicles as "sky turning red" and in Roman records. Recovery of ecosystem took ~200 years. Current repose time: ~1,800 years.',
          examples: 'Taupo 232 CE: fastest recorded eruption rate in geological record (~3 km³ (0.72 cu mi)/minute during peak phase); pyroclastic current traveled 80 km (50 mi) from vent · Lake Taupo: 616 km² (238 sq mi) lake, up to 186 m (610 ft) deep, sitting atop still-hot magmatic system · Wairakei: first geothermal power station in the world (1958); still operating at 125 MW · GeoNet: continuous real-time monitoring of Lake Taupo deformation; any eruption forerunner would trigger immediate Civil Defence alert',
        },
        {
          name: 'Distinguishing Eruptive from Non-Eruptive Unrest',
          icon: Zap,
          color: BRAND.accent,
          desc: 'Non-eruptive unrest drivers: hydrothermal pressure pulses (no new magma), tectonic stress changes, non-eruptive dyke intrusions that stall at depth. Discriminators for magmatic recharge: (1) Geochemical: increasing He-3:He-4 ratio (mantle source), CO₂:SO₂ > 10 (magmatic signature), rising SO₂ flux from previously low-SO₂ system. (2) Seismic: sustained LP earthquake frequency, harmonic tremor, upward seismicity migration. (3) Deformation: accelerating inflation at single deep source (Mogi model fit), sustained trend vs. cyclical fluctuation. (4) Thermal: new fumarole fields, increasing spring temperatures beyond normal seasonal variation. At Campi Flegrei, geochemical and seismic changes since ~2020 are trending toward more magmatic signatures — ongoing active debate in the scientific community.',
          examples: 'Long Valley 1980–present: 75 cm (29.5 in) cumulative uplift, recurrent swarms, CO₂ killing trees → no eruption in 44 years · Campi Flegrei 1982–84: major uplift + seismicity → no eruption; 2005–present episode larger and longer than 1982–84 · Yellowstone 2004–06: 70 cm (27.6 in) uplift in 2 years → no eruption; attributed to sill intrusion at 15 km (9.3 mi) depth · Rabaul 1983–94: 11 years of continuous caldera uplift → September 19, 1994 twin eruptions at Tavurvur and Vulcan vents; 75,000 evacuated before climactic phase',
        },
      ],
    },
    {
      type: 'visualization',
      title: 'The caldera formation cycle: from magma accumulation to collapse and recovery',
      body: `This flow traces the geological lifecycle of a caldera system — from magma chamber growth through the catastrophic super-eruption and caldera collapse, to the post-collapse resurgence and eventual potential for repeat eruption.`,
      interaction: {
        type: 'flow-simulator' as const,
        description: 'The complete lifecycle of a caldera-forming volcanic system, from deep magma accumulation to catastrophic eruption, caldera collapse, and post-collapse resurgence',
        nodes: [
          { id: 'n1', label: 'Magma Accumulation', description: 'A mantle plume or subduction-related magma supply delivers basaltic melt to the lower crust. Over thousands to millions of years, a large shallow magma body (mush zone) grows at 5–15 km (9.3 mi) depth. Partially molten rhyolitic melt accumulates; dissolved volatiles (H₂O, CO₂, SO₂) increase as crystallisation proceeds. Magma body volume may exceed 1,000 km³ (240 cu mi) before eruption.', color: BRAND.ruby },
          { id: 'n2', label: 'Roof Doming and Unrest', description: 'As the magma body inflates, overlying rock is pushed upward — creating a broad topographic dome over the caldera precursor. Ground deformation (GPS uplift), seismicity, and increased fumarolic activity signal magmatic recharge. This phase may last thousands of years. Caldera unrest episodes (bradyseism at Campi Flegrei, resurgent dome uplift at Yellowstone) represent this stage without necessarily leading to eruption.', color: BRAND.coral },
          { id: 'n3', label: 'Ring Fault Failure', description: 'When the eruption withdraws magma rapidly enough, the roof of the magma chamber loses structural support. Near-vertical ring faults propagate from the chamber margin to the surface, outlining the future caldera. The roof fails in segments or as a coherent block, subsiding 1–5 km (3.1 mi) into the chamber. This collapse may take hours to days and dramatically intensifies the eruption rate by feeding fresh magma to the vent.', color: BRAND.gold },
          { id: 'n4', label: 'Super-Eruption / Ignimbrite Emplacement', description: 'Ash-and-pumice pyroclastic density currents (ignimbrites) surge outward from the vent at 200–300 km/h (186 mph), covering thousands to tens of thousands of km² to depths of tens to hundreds of metres. The eruption column may reach 30–50 km (31 mi) altitude. SO₂ injection into the stratosphere causes global climate forcing (cooling). Ash fall detectable thousands of km from source. Total erupted volume: >1,000 km³ (240 cu mi) for a VEI 8 event.', color: BRAND.amethyst },
          { id: 'n5', label: 'Caldera Formation', description: 'The collapsed roof creates a broad, flat-floored depression 10–100 km (62 mi) across and 1–5 km (3.1 mi) deep. If collapse occurs on a volcanic edifice above sea level, a caldera lake may fill the depression (Crater Lake, Lake Taupo). The caldera is bounded by ring fault scarps. Immediate post-collapse: hydrothermal activity intensifies as ground water contacts still-hot residual magma; phreatic explosions are common.', color: BRAND.jade },
          { id: 'n6', label: 'Resurgence and Recharge', description: 'Over thousands to millions of years, new magma intrudes into the now-partly-evacuated chamber, inflating the caldera floor and creating a resurgent dome. Smaller eruptions may occur along the caldera ring faults or from central vents (e.g., post-caldera lava domes, cinder cones). The system recharges toward the next potential major eruption. The Snake River Plain records the Yellowstone hotspot track as successive calderas formed and were resurgently uplifted, then buried by later basaltic lavas.', color: BRAND.accent },
        ],
        edges: [
          { from: 'n1', to: 'n2', label: 'decades to millennia' },
          { from: 'n2', to: 'n3', label: 'eruption onset' },
          { from: 'n3', to: 'n4', label: 'hours to days' },
          { from: 'n4', to: 'n5', label: 'concurrent process' },
          { from: 'n5', to: 'n6', label: 'thousands of years' },
          { from: 'n6', to: 'n1', label: 'millions of years later' },
        ],
      },
    },
    {
      type: 'quiz',
      questions: [
        {
          q: 'Yellowstone\'s last super-eruption was approximately 631,000 years ago. Some media reports claim that Yellowstone is "overdue" for another super-eruption based on the average interval between Yellowstone\'s three major eruptions (~700,000 years). Is this assessment scientifically justified, and what does modern monitoring data actually tell us about Yellowstone\'s current eruption potential?',
          a: [
            'The "overdue" assessment is scientifically justified — volcanic systems follow regular recurrence intervals, like geological clocks; since the average interval between Yellowstone super-eruptions is ~700,000 years and 631,000 years have elapsed since the last one, the probability of eruption in the next century is significantly elevated above background rates; this is why the YVO monitoring the system with such intensity',
            'The "overdue" concept is scientifically unjustified because volcanic eruptions do not follow regular clocks — recurrence intervals at caldera systems are highly variable and depend on magmatic recharge rates, tectonic stress, and volatile accumulation, none of which necessarily produce regular periodicity; Yellowstone\'s three super-eruptions occurred at 2.1 Ma, 1.3 Ma, and 0.631 Ma — intervals of 800,000 and 669,000 years — insufficient data to establish a regular period; current monitoring data show a magmatic mush body with only 5–15% melt fraction, far below the threshold needed to mobilise for a super-eruption; the probability of a Yellowstone super-eruption in any given year is approximately 1 in 730,000',
            'Yellowstone is not actually a volcanic system and poses no eruption risk — the hydrothermal features (geysers, hot springs) are heated by residual heat from the last eruption, not by active magma; the seismicity is purely tectonic; the 1 in 730,000 annual probability overstates the risk by conflating geothermal activity with volcanic hazard',
            'The "overdue" assessment correctly identifies that Yellowstone should have erupted by now, but the actual risk to populated areas is minimal because the proposed eruption would be a small hydrothermal explosion, not a VEI 8 super-eruption; all three previous Yellowstone super-eruptions have been downgraded by recent research to VEI 6 events, comparable in scale to Pinatubo',
          ],
          correct: 1,
          explain: 'Treating volcanic recurrence intervals as regular clocks (A) is a fundamental misapplication of statistics; volcanic systems do not produce eruptions on fixed schedules; only two inter-eruption intervals at Yellowstone are known (800,000 and 669,000 years), which is insufficient to establish periodicity, and the variation between them (131,000 years) is itself large; additionally, the current state of the magmatic system (5–15% melt fraction, no evidence of rapid recharge) provides much more relevant information than a two-point average recurrence interval. Yellowstone is manifestly an active volcanic system — geophysical imaging confirms a large, partially molten magma body, seismicity is clearly volcanic in character (including volcanic tremor), and the hydrothermal system is directly connected to this magmatic heat source; dismissing it as non-volcanic is incorrect (C). The three Yellowstone super-eruptions have not been downgraded to VEI 6 — the Lava Creek Tuff (631 ka) is confirmed at approximately 1,000 km³ (240 cu mi), firmly VEI 8; VEI 6 is the scale of Pinatubo (5–10 km³ (2.4 cu mi)), two orders of magnitude smaller (D is factually incorrect about the eruption volumes). The correct answer is B: the "overdue" framing is a journalistic construct with no scientific validity. Recurrence intervals at caldera systems are controlled by the rate of magmatic recharge, volatile accumulation, and tectonic stress — not by a geological clock. The relevant evidence for Yellowstone\'s near-term hazard is not a two-point recurrence interval but the current state of the magmatic system: geophysical imaging shows a crystal-rich mush zone with only 5–15% melt fraction (at least 50% melt is thought to be required to mobilise for a large eruption), no evidence of rapid recharge, and routine earthquake swarms and deformation that are consistent with the normal behaviour of a geothermally active caldera system.',
        },
        {
          q: 'Campi Flegrei caldera (Naples, Italy) has experienced more than 3 metres of ground uplift since 2005 — the largest and longest-duration unrest episode since the major 1982–84 crisis. Geochemical data show increasing magmatic gas signatures in fumarolic emissions. Italian authorities have maintained the alert level at Yellow (second of four levels). A scientist proposes raising the alert level to Orange (third level), which would trigger partial evacuation of 500,000 people from the caldera\'s red zone. What scientific evidence would most compellingly support or oppose such a decision?',
          a: [
            'The decision should be based solely on the total amount of ground uplift; since the 2005–present episode has already exceeded the 1982–84 episode in total uplift (3+ m vs 1.8 m (6 ft)) without eruption, and since the 1982–84 episode also did not erupt, the current episode is similarly non-eruptive; therefore raising the alert level is unjustified regardless of other data',
            'The decision should be based on the rate of change and geochemical trends rather than absolute uplift values; compelling evidence for raising the alert level would include: sustained acceleration in uplift rate (not just total cumulative uplift); transition from cyclical inflation-deflation to monotonic inflation; shift in fumarolic geochemistry toward magmatic end-members (increasing SO₂:H₂O, rising He-3:He-4, elevated temperature); onset of shallow seismicity indicating fracturing near the surface above the magma body; any combination of these signals accelerating together would be more scientifically compelling than total uplift alone; opposing evidence would include stable or decelerating uplift rates, no geochemical change, and absence of shallow seismicity',
            'The decision should be based primarily on the historical eruption record at Campi Flegrei; since the last eruption (Monte Nuovo, 1538) was preceded by visible ground deformation and phreatic activity that is not yet observed, the current unrest does not meet the threshold for Orange alert; no eruption has occurred despite major uplift in the past, and the historical record shows that only visible ground fracturing and phreatic explosions precede Campi Flegrei eruptions',
            'The decision should be left entirely to civil protection authorities rather than scientists; scientists can provide monitoring data but cannot make risk decisions that involve evacuation of 500,000 people; scientists who advocate for raising alert levels are overstepping their role and could trigger unnecessary economic disruption and loss of public trust in future warnings',
          ],
          correct: 1,
          explain: 'Total cumulative uplift alone is a poor indicator of eruption proximity because the same total uplift can be reached through different rates and trajectories; a caldera that inflated 3 m (10 ft) rapidly over 6 months would be far more concerning than the same 3 m (10 ft) reached over 19 years with fluctuating rates; the argument that because 1.8 m (6 ft) of uplift in 1982–84 produced no eruption, more uplift is safe is a logical non-sequitur — each unrest episode has a different internal structure (A applies a misleading comparison). Alert level decisions are properly a joint responsibility of scientists and civil protection authorities — scientists provide the hazard assessment and communicate uncertainty; civil protection authorities make the evacuation decision considering societal factors (economic disruption, public trust, governance capacity); characterising scientist advocacy for alert level changes as overstepping is incorrect — scientists have a professional obligation to communicate their hazard assessments, including recommended alert level changes (D mischaracterises the scientist-governance interface). The historical record at Campi Flegrei is important context but cannot be the primary basis for alert level decisions: the 1538 Monte Nuovo eruption is the only historical eruption, providing very limited sample size; precursory observations from 1538 are poorly documented; and Campi Flegrei\'s prehistorical eruption record includes events with quite different precursory sequences (C overweights sparse historical data). The correct answer is B: alert level decisions at caldera systems should be based on the rate and character of change in multiple parameters rather than absolute cumulative values. The key scientific questions are: Is the system accelerating? Are multiple independent lines of evidence converging? Are geochemical signatures shifting toward magmatic end-members, which would indicate fresh magma rather than hydrothermal fluid as the driver? A sustained, accelerating, multi-parameter convergence — particularly if shallow seismicity (indicating rock fracturing near the surface) accompanies geochemical and deformation signals — would provide more compelling justification for Orange alert than total cumulative uplift alone.',
        },
        {
          q: 'A VEI 8 super-eruption at Yellowstone would eject approximately 1,000 km³ (240 cu mi) of material and deposit ash across most of North America. However, the largest historical caldera-forming eruption in the past 500 years — the 1815 Tambora eruption (VEI 7, ~150 km³ (36 cu mi)) — was dramatically smaller. What would be the key differences in local, regional, and global impacts between a Tambora-scale VEI 7 event and a Yellowstone-scale VEI 8 event?',
          a: [
            'There would be no meaningful difference in global impacts because VEI is a logarithmic scale; VEI 7 and VEI 8 differ by only one scale unit, representing a factor of ten in erupted volume; since Tambora (VEI 7) caused the Year Without a Summer with 0.5°C (1°F) global cooling, a Yellowstone VEI 8 would cause approximately 1°C (2°F) of global cooling — significant but manageable with modern agricultural technology and international food aid',
            'A Yellowstone VEI 8 would produce catastrophic local and regional destruction (ash depths of centimetres to metres across most of North America, immediate agricultural collapse in the US, collapse of infrastructure across thousands of kilometres) combined with global climate forcing 5–10 times more severe than Tambora (3–7°C (5–13°F) global cooling persisting for 5–10 years); the scale difference between a VEI 7 and VEI 8 (a factor of 10 in volume) translates to proportionally greater SO₂ injection, ignimbrite coverage, and stratospheric aerosol loading; unlike Tambora (which affected an island in Indonesia), Yellowstone sits on a continent and would bury the agricultural heartland of North America under ash',
            'A Yellowstone VEI 8 would primarily cause regional devastation within 100 km (62 mi) of the caldera but would have minimal global effects because the ash and gases would remain in the troposphere due to the continental location of Yellowstone (lower eruption column than island volcanoes); global climate forcing requires stratospheric injection, which is more efficient for island volcanoes like Tambora surrounded by ocean',
            'VEI 8 eruptions do not produce more SO₂ than VEI 7 eruptions because SO₂ emission is controlled by magma sulfur content, not eruption volume; since Yellowstone rhyolite is sulfur-poor compared to Tambora\'s trachyandesite, a Yellowstone super-eruption might actually produce less stratospheric SO₂ than Tambora despite erupting ten times more material',
          ],
          correct: 1,
          explain: 'A VEI 7-to-VEI 8 difference of "only one scale unit" is not negligible — VEI is logarithmic, so this is a factor of ten in erupted volume; Tambora\'s global cooling was approximately 0.4–0.7°C (1°F); scaling linearly by ×10 SO₂ injection would suggest 4–7°C (45°F) cooling, not the "manageable 1°C (2°F)" described; and volcanic cooling does not scale linearly with SO₂ because of aerosol microphysics — the relationship is complex and nonlinear (A drastically underestimates the difference). Large continental eruptions can and do produce stratospheric eruption columns — Yellowstone\'s previous eruptions are estimated to have produced columns reaching 30–50 km (31 mi) altitude; continental location does not prevent stratospheric injection, which depends on eruption intensity rather than geographic setting (C is incorrect about the continental eruption column argument). While it is true that rhyolitic magmas can be sulfur-poor, Yellowstone\'s voluminous past eruptions did produce significant sulfate deposits globally — the Huckleberry Ridge and Lava Creek Tuffs left sulfate signals in ice cores; and a tenfold greater volume of magma would produce substantial SO₂ even from a relatively sulfur-poor melt (D overstates the sulfur-content argument to the point of incorrectness). The correct answer is B: the difference between a Tambora-scale VEI 7 and a Yellowstone VEI 8 is not merely quantitative but qualitative. Key differences: (1) Local/regional devastation — Tambora is an island in the Banda Sea; within 100 km (62 mi) there is relatively sparse population; a Yellowstone eruption would bury portions of Wyoming, Montana, Idaho, and neighbouring states under metres of ignimbrite, and deposit centimetres to metres of ash across the agricultural Midwest, destroying crops and disrupting infrastructure for years. (2) SO₂ injection — roughly tenfold greater than Tambora, leading to global aerosol forcing of potentially 3–7°C (5–13°F) for multiple years. (3) Duration — a multi-year volcanic winter rather than the ~1-year Tambora cooling. (4) Food system vulnerability — modern agriculture is globally connected; a Yellowstone super-eruption would devastate North American food exports, affecting global food security.',
        },
        {
          q: 'Caldera unrest at Campi Flegrei, Long Valley, and Yellowstone has lasted decades without producing an eruption. What does this tell us about the ratio of unrest episodes to eruptions at caldera systems globally, and why is this ratio important for volcanic risk communication?',
          a: [
            'The long-duration unrest without eruption at these systems proves that caldera monitoring is essentially useless for eruption forecasting because the systems are permanently restless; monitoring should be redirected to stratovolcanoes, which produce the clearest eruption precursors',
            'Long-duration caldera unrest without eruption is the exception rather than the rule; most caldera unrest episodes worldwide do culminate in eruption within months; the three examples cited (Campi Flegrei, Long Valley, Yellowstone) are anomalously quiescent and are not representative of caldera systems globally',
            'The fact that multiple major caldera systems have experienced decades of unrest without eruption reflects the fundamental asymmetry of caldera hazard communication: caldera systems generate many more unrest episodes than eruptions; globally, it is estimated that the ratio of significant caldera unrest episodes to eruptions is approximately 100:1 or higher; this means that even correct scientific identification of genuine magmatic recharge often leads to decades of elevated alert without eruption; risk communication must convey this uncertainty honestly — the goal of monitoring is to detect the rare transition from unrest to pre-eruptive state, not to guarantee eruption prediction',
            'Long-duration unrest without eruption only occurs at caldera systems where the monitoring network is inadequate; if Campi Flegrei, Long Valley, and Yellowstone had dense borehole strainmeter arrays, continuous GPS, and real-time geochemical monitoring as standard, the distinction between eruptive and non-eruptive unrest would be straightforward and decades-long ambiguity would not occur',
          ],
          correct: 2,
          explain: 'Long-duration caldera unrest without eruption does not prove monitoring is useless; it demonstrates the complexity of caldera systems and the importance of sustained monitoring; moreover, the alternative — not monitoring and missing a genuine pre-eruptive sequence — would be catastrophic given the populations exposed (A draws the wrong conclusion). Long-duration caldera unrest without eruption is not exceptional — it is the statistical norm; globally, unrest episodes at calderas vastly outnumber eruptions; the Campi Flegrei 1982–84 episode, Long Valley since 1980, and Yellowstone recurrent swarms are well within the normal distribution of non-eruptive caldera behaviour (B has the statistical relationship backwards). While better monitoring does improve discrimination between eruptive and non-eruptive unrest, it does not make the distinction "straightforward" — even dense borehole strainmeter arrays cannot reliably predict decades in advance whether a caldera\'s unrest will culminate in eruption; the nonlinearity and complexity of magmatic systems impose fundamental limits on predictability (D overclaims what monitoring technology can achieve). The correct answer is C: globally, caldera systems produce many more significant unrest episodes than eruptions — the ratio is estimated at roughly 100:1 or higher based on historical records. This has profound implications for risk communication. The challenge is not merely scientific (distinguishing magmatic recharge from non-eruptive unrest) but also social: authorities and communities must be prepared for decades-long states of elevated awareness without certainty about outcome. The Campi Flegrei situation is the clearest current example: sustained, accelerating unrest since 2005, geochemical shifts toward magmatic signatures, increasing seismicity — and the scientific community genuinely uncertain about whether this represents a slow build toward eruption or another long non-eruptive unrest cycle. Honest communication of this uncertainty, including the known base rate (most unrest episodes do not erupt), is essential for maintaining public trust across potentially decades of elevated alert.',
        },
      ],
    },
  ],
}

export default supervolcanoesAndCalderas
