import { Flame, Globe, Mountain } from 'lucide-react'
import { BRAND } from '@/lib/brand'
import type { Lesson } from './types'

const volcanicGases: Lesson = {
  id: 'volc-101-1-2-4',
  title: 'Volcanic Gases, Degassing, and the Atmosphere',
  track: 'vol',
  trackName: 'Volcanology',
  level: 'Beginner',
  duration: '11 min',
  xpReward: 140,
  description: "Volcanoes are Earth's primary geological connection between the deep interior and the atmosphere. The gases they emit — water vapour, carbon dioxide, sulfur dioxide, and others — have shaped the composition of the atmosphere over billions of years, driven mass extinctions, triggered short-term climate cooling, and provide some of the most reliable early-warning signals of impending eruptions.",
  sources: [
    { org: 'USGS',     title: 'Volcano Hazards — Volcanic Gases',                                   url: 'https://volcanoes.usgs.gov/vhp/gas.html' },
    { org: 'NOAA',     title: 'NOAA Earth System Research Lab — Volcanic Forcing of Climate',        url: 'https://gml.noaa.gov/grad/mloapt.html' },
    { org: 'OpenStax', title: 'Physical Geology — Volcanic Emissions and the Atmosphere (CC-BY 4.0)', url: 'https://openstax.org/books/physical-geology-2e' },
    { org: 'NASA',     title: 'NASA — Pinatubo Aerosol Effects on Global Climate',                  url: 'https://earthobservatory.nasa.gov' },
    { org: 'SI-GVP',   title: 'Smithsonian GVP — Volcanic Emissions Monitoring',                    url: 'https://volcano.si.edu' },
  ],
  sections: [
    {
      type: 'intro',
      title: 'From the deep Earth to the atmosphere',
      body: `Every molecule of water in Earth's oceans, every molecule of nitrogen in the atmosphere, and a significant fraction of the atmospheric CO₂ was originally released from the Earth's interior by volcanism — a process called **volcanic outgassing** or **degassing**. Over the 4.5 billion years of Earth's history, the cumulative output of volcanic gases has constructed the atmosphere, filled the oceans, and enabled the chemical conditions that made life possible. The geological record of volcanic degassing is written in ancient atmospheric gases trapped in ice cores, in the chemical signals of mass extinction events, and in the geochemistry of ancient volcanic rocks.

On shorter timescales, volcanic emissions play a more ambiguous and complex role in climate. The sulfur dioxide (SO₂) released by large eruptions — especially those that inject gas directly into the stratosphere — rapidly oxidises to form sulfate aerosol droplets that scatter incoming solar radiation, temporarily cooling Earth's surface. The 1991 eruption of Pinatubo injected ~20 million tonnes of SO₂ into the stratosphere; within a year, the global mean temperature had dropped ~0.5°C, and the effects were measurable for 2–3 years. This short-term volcanic cooling is well-documented and relatively well understood. Carbon dioxide (CO₂), also released by volcanoes, is a greenhouse gas — but on human timescales, volcanic CO₂ emissions are dwarfed by fossil fuel combustion by approximately 150:1 (volcanoes emit ~0.26 Gt CO₂/year; human emissions exceed 37 Gt CO₂/year).

The gases that magma releases are not just a byproduct of eruption — they are the driving force behind it. The buoyancy of magma rising through the crust, the violence of eruption, and even the style of eruptive activity are ultimately controlled by the dissolved volatile content of the magma and the rate at which volatiles exsolve as pressure decreases. Monitoring volcanic gas emissions — their composition, quantity, and isotopic signatures — has become one of the most powerful tools for forecasting eruptions weeks to months in advance.`,
      keyTerms: [
        { term: 'Volcanic degassing', def: 'The release of dissolved volatile compounds (primarily H₂O, CO₂, SO₂, HCl, HF, H₂S) from magma as it ascends and depressurises. Degassing drives eruptive activity — volatiles exsolving from magma create gas bubbles that lower magma density (promoting rise) and, if the melt is viscous enough to prevent bubble escape, build pressure that fragments the magma explosively. Passive degassing from volcanic vents and fumaroles occurs between eruptions and provides continuous monitoring data.' },
        { term: 'Sulfate aerosol', def: 'Tiny droplets of sulfuric acid (H₂SO₄) formed in the stratosphere when volcanic SO₂ reacts with water vapour and hydroxyl radicals: SO₂ + OH → HSO₃ → H₂SO₄. These aerosol droplets scatter and absorb incoming solar radiation (shortwave), reducing the amount reaching Earth\'s surface. Radiative forcing from stratospheric volcanic aerosols is negative (cooling). Aerosol particles have an atmospheric residence time of 1–3 years before gravitational settling removes them.' },
        { term: 'Volcanic forcing', def: 'The temporary perturbation to Earth\'s radiation balance caused by volcanic aerosol injection into the stratosphere. Expressed in W m⁻² (negative = cooling). The 1991 Pinatubo eruption produced a peak forcing of approximately -3 to -4 W m⁻², causing ~0.5°C global cooling; the 1815 Tambora eruption (VEI 7) produced a forcing of approximately -5 to -7 W m⁻², causing the "Year Without a Summer" (1816). Volcanic forcing is the primary natural driver of interannual-to-decadal climate variability in the absence of ENSO.' },
        { term: 'SO₂ flux', def: 'The rate at which sulfur dioxide gas is emitted from a volcano, typically measured in tonnes per day (t/day) by remote sensing instruments (DOAS — Differential Optical Absorption Spectroscopy; COSPEC — Correlation Spectrometry; TROPOMI satellite sensor). A sharp increase in SO₂ flux at a quiescent volcano indicates new magma approaching the surface, making SO₂ flux one of the most reliable precursors of explosive eruptions. Pinatubo\'s SO₂ output increased from near zero to 500 t/day weeks before the June 15, 1991 climactic eruption.' },
        { term: 'Volcanic winter', def: 'A period of global or hemispheric cooling caused by stratospheric sulfate aerosol injection from a very large volcanic eruption (VEI 7–8). The aerosol veil reduces insolation sufficiently to cause crop failure, famine, and social disruption. Documented volcanic winters: 536 CE (unknown eruption) caused 1–2°C cooling and famine across Europe, the Byzantine Empire, and China; 1816 ("Year Without a Summer") followed Tambora 1815; 74 ka Toba eruption may have caused a prolonged volcanic winter that contributed to a human population bottleneck.' },
      ],
    },
    {
      type: 'concept',
      title: 'Gas species, climate forcing, and eruption forecasting',
      body: `**Volcanic gas species and their sources.** The dominant volatile in magma is water (H₂O), which typically constitutes 1–6 wt% of silicic magmas at depth. Other important species include CO₂ (0.01–0.6 wt%), SO₂ (0.01–0.3 wt%), HCl (0.01–0.2 wt%), HF (0.01–0.1 wt%), H₂S, and various metal vapours. The relative proportions depend on magma composition, pressure, and temperature. CO₂ is less soluble in magma than H₂O and SO₂ — it exsolves from melts at much greater depth (often >10 km). This means that CO₂ degasses from magma long before it is close enough to the surface to cause detectable SO₂ emission or seismicity. The ratio of CO₂:SO₂ in volcanic gases is therefore a powerful depth indicator: a rising ratio indicates that the CO₂-rich deep component is entering the shallow system, potentially signalling magma intrusion weeks before other signs appear. This was used successfully to provide 2+ weeks of warning before the 2018 Kīlauea eruption and was a key parameter monitored before the 2014–2015 eruption at Bárðarbunga, Iceland.

**Stratospheric injection and climate cooling.** Not all volcanic eruptions affect global climate equally. What matters is not simply the total volume of SO₂ emitted but whether that SO₂ reaches the stratosphere — above the tropopause at ~10–17 km altitude. Eruption columns that penetrate the stratosphere deliver SO₂ above the altitude where precipitation and weather systems can wash it out. In the troposphere, SO₂ has a residence time of days to weeks; in the stratosphere, sulfate aerosol has a residence time of 1–3 years, spreading globally and causing measurable cooling. A moderate eruption at a tropical location can have greater global climate impact than a larger eruption at high latitudes, because aerosols injected in the tropics are efficiently transported by the Brewer-Dobson circulation to both hemispheres, while high-latitude stratospheric injections tend to remain in the hemisphere of injection. The 1783 Laki eruption (Iceland, VEI ~6) emitted more SO₂ than Pinatubo but had primarily a Northern Hemisphere tropospheric effect rather than a stratospheric global effect, because the eruption column was ~12 km tall — just at the tropopause — rather than penetrating deeply into the stratosphere. As a result, Laki's cooling was primarily regional (Europe and North America experienced cold winters and cool summers in 1783–84) rather than global.

**The Pinatubo eruption as a natural climate experiment.** The June 15, 1991 eruption of Mt. Pinatubo in the Philippines was the largest stratospheric eruption of the 20th century. It injected approximately 20 Mt of SO₂ into the stratosphere at 25–35 km altitude. The resulting sulfate aerosol cloud spread globally within 2–3 months, reducing mean global solar radiation by ~2.5 W m⁻². Global mean surface temperature cooled by ~0.5°C in 1992, masking the underlying warming trend from greenhouse gases, and confounding climate models that had not incorporated the volcanic forcing. This serendipitously provided a powerful natural experiment: climate models that correctly incorporated the Pinatubo aerosol forcing accurately predicted the subsequent cooling, greatly increasing scientific confidence in the physical mechanisms of the greenhouse effect and climate sensitivity. The stratospheric ozone layer was also temporarily depleted by 2–3% globally because sulfate aerosol surfaces catalyse heterogeneous chemical reactions that convert reservoir halogen species to active ozone-destroying forms.

**Gas monitoring and eruption forecasting.** The recognition that volcanic gas composition and flux precede and predict eruptions has transformed modern volcanology from a primarily geological to a multi-parameter geophysical and geochemical discipline. Before major eruptions, characteristic gas signatures emerge: (1) CO₂ rises first, as deep magma intrudes and exsolves CO₂ at depth; (2) SO₂ increases as magma rises into the shallow (< 5 km) zone; (3) HCl and HF increase in the final days to hours before eruption, as the very highest-pressure phases exsolve. Seismicity, ground deformation (measured by GPS and tiltmeters), and gas flux together form the standard multi-parameter monitoring package at high-risk volcanoes worldwide. The successful evacuation of 58,000 people before the 1991 Pinatubo eruption — preventing an estimated 20,000 deaths — was directly enabled by SO₂ flux monitoring, which showed SO₂ increasing from near zero to 500 t/day over 2 months. When SO₂ suddenly dropped in early June 1991, volcanologists interpreted it as the conduit being sealed by a lava dome — and immediately raised the alert level, triggering the final evacuation of the Clark Air Base area before the climactic eruption on June 15.`,
      cards: [
        {
          name: 'Volcanic Gas Species and Sources',
          icon: Flame,
          color: BRAND.ruby,
          desc: 'H₂O: dominant volatile (1–6 wt%); exsolves at <5 km depth; drives explosive eruptions. CO₂: exsolves at depth >10 km; first to degas; CO₂:SO₂ ratio = depth indicator. SO₂: exsolves at 1–5 km depth; monitored as eruption precursor; oxidises to stratospheric sulfate aerosol. HCl and HF: late-stage volatiles; HF extremely toxic; causes acid rain. H₂S: hazardous near vents; heavier than air; pools in depressions. Fumaroles: vents emitting volcanic gas between eruptions. Passive degassing: ongoing gas release without eruption (Kīlauea SO₂ ~500–1,000 t/day normal).',
          examples: 'Kīlauea SO₂: up to 2,000 t/day during high eruptive periods — causes \'vog\' (volcanic smog) affecting downwind communities · Lake Nyos (Cameroon) 1986: CO₂ eruption (limnic eruption from CO₂-saturated lake) released 1.6 Mt CO₂, killed 1,800 people in minutes by asphyxiation in CO₂ cloud flowing downhill · Masaya (Nicaragua): persistent passive SO₂ emitter, 1,000+ t/day, acid rain damages crops 30 km downwind',
        },
        {
          name: 'Stratospheric Aerosols and Climate Forcing',
          icon: Mountain,
          color: BRAND.coral,
          desc: 'Stratospheric SO₂ → H₂SO₄ aerosol → 1–3 year residence time → global dispersal. Aerosol scatters shortwave radiation → negative radiative forcing (cooling). Tropospheric SO₂: washed out in days–weeks, only regional effect. Tropical injections: dispersed to both hemispheres via Brewer-Dobson circulation. Pinatubo 1991: 20 Mt SO₂, -3 to -4 W/m², -0.5°C global for 2 years. Tambora 1815: estimated -5 to -7 W/m², 1816 "Year Without a Summer." Volcanic winter (VEI 7–8): crop failures, famine, social disruption.',
          examples: 'Pinatubo 1991: global cooling -0.5°C, stratospheric ozone depleted -2–3%, 1992–93 winter warming anomaly from aerosol IR trapping in Arctic · Tambora 1815: snow in New England in July 1816, crop failure across Europe and North America, possibly 90,000+ deaths from famine · 536 CE eruption: caused 18-month cooling, documented by tree rings and ice cores globally; associated with the Late Antique Little Ice Age',
        },
        {
          name: 'Gas Monitoring and Eruption Forecasting',
          icon: Globe,
          color: BRAND.jade,
          desc: 'CO₂:SO₂ ratio: rises as deep magma intrudes, weeks before eruption. SO₂ flux: increases as magma approaches surface (<5 km); DOAS/COSPEC/TROPOMI satellite. Precursor sequence: CO₂ rise → SO₂ increase → seismicity increase → ground inflation → HCl/HF → eruption. Gas flux drop can indicate conduit sealing (pressure build-up → danger). Multi-parameter monitoring: gas + seismicity + deformation = best forecast. VAAC (Volcanic Ash Advisory Centres): issue volcanic ash warnings to aviation. TROPOMI satellite: detects SO₂ from space in near-real-time, monitors 1,500+ volcanoes globally.',
          examples: 'Pinatubo 1991: SO₂ monitoring drove evacuation of 58,000 people, saved ~20,000 lives · Kīlauea 2018: CO₂:SO₂ ratio increase weeks before LERZ eruption · Redoubt 1989 (Alaska): SO₂ monitoring gave 1–2 weeks warning · Ruapehu (NZ): gas monitoring standard; school groups now trained in lahar evacuation routes',
        },
      ],
    },
    {
      type: 'quiz',
      questions: [
        {
          q: "Climate scientists monitoring the global temperature record note that 1992 showed an anomalous cooling of ~0.5°C relative to the underlying warming trend, followed by a return to trend warming by 1994. They attribute this cooling to the 1991 Pinatubo eruption. A commentator argues: 'But volcanoes release CO₂, a greenhouse gas — so volcanoes should cause warming, not cooling.' How would you explain why the Pinatubo eruption caused short-term cooling despite CO₂ emissions?",
          a: [
            "The commentator is correct that volcanic CO₂ causes long-term warming, but the cooling seen in 1992 was caused by ash particles from the eruption blocking sunlight; as the ash settled over 6–12 months, the cooling ended; Pinatubo's CO₂ continued to cause warming for decades after the eruption, contributing to the overall greenhouse warming trend",
            "Pinatubo caused cooling because it erupted at high latitude (Philippines at 15°N is close enough to the poles) where solar radiation is already weak; the slight additional reduction from volcanic aerosols had a disproportionate effect on global temperature compared with tropical forcing",
            "Pinatubo emitted ~20 million tonnes of SO₂ along with CO₂; the SO₂ rapidly converted to sulfate aerosol in the stratosphere, which has a residence time of 1–3 years and reflects/scatters incoming solar radiation (shortwave), reducing the amount reaching Earth's surface — a large, immediate cooling effect of -3 to -4 W m⁻²; Pinatubo emitted only ~50 million tonnes of CO₂ (about 0.14% of annual human CO₂ emissions), producing a negligible positive forcing of ~0.001 W m⁻² by comparison; the SO₂ aerosol cooling overwhelmingly dominated the CO₂ warming on this timescale",
            "The cooling was not caused by the eruption directly but by the global economic recession of 1991–93, which reduced industrial activity and greenhouse gas emissions sufficiently to cause measurable cooling; this is a coincidence that commentators have misattributed to volcanic forcing",
          ],
          correct: 2,
          explain: "Volcanic ash (A) does cause some short-term cooling but ash particles are much larger than stratospheric sulfate aerosol and settle out of the atmosphere within weeks to months; the key climate-forcing agent of Pinatubo was the SO₂-derived sulfate aerosol, not the tephra; furthermore, CO₂ from individual eruptions is too small relative to the atmospheric CO₂ pool to create measurable warming. The Philippines at 15°N is unambiguously a tropical location, not high-latitude (B); the efficiency of tropical stratospheric injections in reaching both hemispheres via the Brewer-Dobson circulation makes tropical eruptions MORE effective at global cooling than high-latitude ones, not less. The economic recession explanation (D) is incorrect and not supported by the data — industrial emissions changes of the magnitude seen in 1991–93 recessions are not large enough to cause detectable year-scale global temperature changes; the causal attribution to Pinatubo is supported by climate model simulations that reproduce the 1992 cooling only when volcanic aerosol forcing is included. The correct answer is C: the critical distinction is between volcanic SO₂ and volcanic CO₂ as climate forcings. Pinatubo injected ~20 Mt SO₂ into the stratosphere, where it converted to sulfate aerosol (H₂SO₄ droplets) over ~3 weeks. These aerosol particles are highly effective scatterers of solar shortwave radiation (peak scattering at ~0.5 μm wavelength) and have a stratospheric residence time of 1–3 years — long enough to produce a sustained global cooling. The radiative forcing was -3 to -4 W m⁻², causing ~0.5°C global cooling at its peak in 1992. By contrast, Pinatubo's ~50 Mt CO₂ emission was a tiny perturbation to the 3,170,000 Mt CO₂ already in the atmosphere (0.0016% increase), producing a warming forcing of ~0.001 W m⁻² — 3,000 times smaller than the aerosol cooling. The aerosol effect dominates completely on the 1–3 year timescale of a single large eruption.",
        },
        {
          q: "A monitoring network at a composite volcano in the Andes detects the following changes over a 3-month period: GPS stations show ground inflation of 15 cm over the summit; seismicity increases from background (~10 earthquakes/day) to 300 earthquakes/day, transitioning from high-frequency (tectonic) to low-frequency (fluid/magma) events; CO₂ flux doubles while SO₂ flux remains near-zero throughout. What does this pattern indicate, and what does the persistently near-zero SO₂ specifically imply about the volcanic hazard?",
          a: [
            "The pattern indicates a non-volcanic hydrothermal system reactivation — the CO₂ is biogenic (from microbial activity in heated soil), the seismicity reflects hydrothermal fluid movement, and the inflation reflects steam pressure; the absence of SO₂ confirms no magma is involved; the hazard is limited to hydrothermal explosions, not magmatic eruptions",
            "The pattern indicates magma intrusion at depth: ground inflation and increasing seismicity (especially low-frequency events) reflect magma ascending into the shallow crust; CO₂ rising while SO₂ remains near-zero indicates the magma is still at depth (>5 km), where only CO₂ exsolves at those pressures; SO₂ near-zero is significant because it means magma has NOT yet reached the shallow zone (<5 km) where SO₂ would exsolve; the hazard is elevated but the absence of SO₂ provides some lead time before explosive eruption is imminent — the key trigger for maximum-alert evacuation would be a sharp rise in SO₂ flux",
            "The near-zero SO₂ is the key indicator of safety — volcanic SO₂ is always the first gas to appear before an eruption, so its absence proves that no eruption is imminent; the CO₂ increase is normal seasonal variation in volcanic systems; the inflation and seismicity are caused by tectonic stress accumulation rather than magma, and the volcano can be safely re-opened for tourism",
            "The pattern is ambiguous and no conclusions can be drawn without lava samples from the summit crater; remote gas monitoring is insufficient to distinguish magmatic from non-magmatic sources; the appropriate response is to send a volcanologist to collect lava samples from the summit before any evacuation decision is made",
          ],
          correct: 1,
          explain: "While hydrothermal systems can produce CO₂ and seismicity, the combination of 15 cm of ground inflation (a large deformation signal indicating significant mass addition at depth), the transition from high-frequency to low-frequency seismicity (specifically indicating fluid or melt movement rather than rock fracture), and doubled CO₂ flux is inconsistent with a purely hydrothermal interpretation — hydrothermal systems do not typically inflate volcanoes by 15 cm or produce the LP/VLP seismicity signature of magma movement (A is incorrect). SO₂ is NOT always the first volcanic gas to appear — CO₂ exsolves from magma at greater depth (>10 km) than SO₂ (<5 km); the interpretation that SO₂ absence means no eruption is imminent inverts the correct understanding of degassing depth relationships and could lead to dangerously overconfident hazard assessments (C is incorrect and potentially dangerous). While lava sampling provides additional petrological information, the claim that no conclusions can be drawn from multi-parameter monitoring is incorrect — the described data are highly diagnostic and remote monitoring is standard practice at dangerous volcanoes where summit access is restricted during unrest (D understates the interpretive power of modern monitoring). The correct answer is B: the described monitoring pattern is a textbook example of deep magma intrusion. Ground inflation of 15 cm indicates significant volume increase at depth (Mogi source modelling would allow estimation of the intrusion volume and depth). The seismicity transition from high-frequency (brittle fracture of cold rock) to low-frequency (fluid movement, magma cracking) is a standard precursor that indicates a change from tectonic to magmatic origin. The CO₂ doubling while SO₂ remains near-zero is the critical geochemical clue: CO₂ has a much lower solubility in silicate melt than SO₂ and H₂O, so it exsolves from magma at much greater depth (>5–10 km). SO₂ only exsolves significantly in the uppermost few kilometres of the conduit. Therefore, a CO₂-dominant, SO₂-poor gas signature indicates magma at depth — potentially intrusing but not yet in the zone where imminent eruption is likely. The SO₂ absence is NOT reassuring — it is an indicator of early-stage intrusion. The key surveillance target is SO₂: when it begins to rise, magma has reached shallow depth and eruption risk escalates to critical.",
        },
        {
          q: "A geology student claims: 'Volcanic CO₂ emissions are the main driver of modern climate change — volcanoes emit enormous amounts of CO₂ continuously, and the current warming is just part of a natural volcanic cycle.' What is wrong with this claim, and what does the geological record actually tell us about the relationship between volcanic CO₂ and long-term climate?",
          a: [
            "The student is largely correct — volcanic CO₂ drives both short-term and long-term climate change; the difference between modern warming and past volcanic periods is only in the rate, not the mechanism; human CO₂ emissions are actually less important than volcanic CO₂ because volcanoes operate continuously while human emissions have only been occurring for 200 years",
            "The claim is incorrect on two counts: (1) measured volcanic CO₂ emissions (~0.26 Gt CO₂/year from all volcanoes) are approximately 150 times smaller than current human fossil fuel emissions (~37 Gt CO₂/year); the geological record does support volcanic CO₂ as a driver of long-term (million-year) climate change through continental drift, mountain building, and LIP events — but on timescales of millions of years, not decades; (2) the modern warming trend since 1750 correlates precisely with the industrial-era rise in atmospheric CO₂ documented by the Keeling Curve (Mauna Loa) and ice cores, and the isotopic fingerprint of atmospheric CO₂ (depleted ¹³C and ¹⁴C) identifies fossil fuel combustion, not volcanic emission, as the source",
            "The claim is incorrect only because volcanoes have been declining in activity since the Cretaceous; during the Cretaceous volcanic maximum, volcanic CO₂ did drive warming, but modern volcanoes are too few and too small to have any climate effect; the real drivers of modern climate are ocean circulation changes and solar variability",
            "The claim is incorrect because volcanic CO₂ actually causes cooling rather than warming — SO₂ aerosols always accompany volcanic CO₂ and overpower the greenhouse warming; the student has confused the signs of the two forcings; any volcanic warming effect from CO₂ is always cancelled by the simultaneous cooling from sulfate aerosols",
          ],
          correct: 1,
          explain: "Volcanic CO₂ is definitively NOT the dominant driver of modern climate change — the measured flux (~0.26 Gt/year) is ~150 times smaller than human emissions (~37 Gt/year), and the atmospheric CO₂ isotopic signature rules out volcanic origin (A is incorrect and perpetuates a common climate misinformation claim). Modern volcanoes are still active and their CO₂ emissions are measurable and significant geochemically — the claim that modern volcanoes are too few and too small is incorrect (C); furthermore, ocean circulation and solar variability cannot account for the observed post-1975 warming pattern. The claim that volcanic CO₂ always causes cooling (D) confuses the timescale issue — SO₂ aerosol cooling lasts 1–3 years and is unambiguously negative (cooling); CO₂ from the same eruption remains in the atmosphere for centuries to millennia, but the forcing is so small per eruption that it is negligible; on geological timescales with large LIP events and sustained high CO₂ release, volcanic CO₂ can cause warming — the Cretaceous greenhouse climate is partly attributed to high volcanic CO₂. The correct answer is B: the student's claim fails on two independent grounds. First, the quantitative comparison is decisive: current human CO₂ emissions (~37 Gt/year) dwarf all volcanic emissions (~0.26 Gt/year) by a factor of ~150. This is not a modelling result — it is a direct measurement from networks of gas sensors, satellite instruments (TROPOMI), and airborne sampling campaigns. The geological record does show volcanic CO₂ driving climate change, but only through Large Igneous Province events (Siberian Traps, Deccan Traps) that sustained eruptions over millions of years, releasing hundreds of millions of tonnes of CO₂. Second, the isotopic fingerprint is decisive: as humans burn fossil fuels (ancient organic carbon), the proportion of ¹³C in atmospheric CO₂ decreases (the Suess effect, measured since the 1950s); the proportion of radioactive ¹⁴C also decreases (fossil carbon is millions of years old and has no remaining ¹⁴C). Volcanic CO₂ from mantle-derived magma has a distinct isotopic signature that does not match the observed atmospheric trend. The combination of flux measurements and isotopic analysis definitively identifies human emissions, not volcanism, as the source of the observed atmospheric CO₂ increase.",
        },
      ],
    },
  ],
}

export default volcanicGases
