import { Layers, TrendingUp, Thermometer, Globe, Zap } from 'lucide-react'
import { BRAND } from '@/lib/brand'
import type { Lesson } from './types'

const volcanicResources: Lesson = {
  id: 'volc-101-1-4-3',
  title: 'Volcanic Soils, Geothermal Energy, and Mineral Resources',
  track: 'vol',
  trackName: 'Volcanology',
  level: 'Beginner',
  duration: '14 min',
  xpReward: 150,
  description: `Volcanoes are not only agents of destruction — they are also the source of some of the world's most fertile soils, vast reserves of clean geothermal energy, and economically critical mineral deposits. The same hydrothermal systems that pose hazards around active volcanoes also concentrate gold, copper, silver, and lithium into ore deposits that underpin modern industry. Understanding the beneficial legacy of volcanism is essential for appreciating why so many of the world's most densely populated regions sit on volcanic terrain.`,
  sources: [
    { org: 'USGS', title: 'USGS Mineral Resources Program — Volcanogenic Massive Sulfide Deposits', url: 'https://minerals.usgs.gov' },
    { org: 'USGS', title: 'Volcano Hazards Program — Geothermal Energy and Volcanic Soils', url: 'https://volcanoes.usgs.gov/vhp/geothermal.html' },
    { org: 'OpenStax', title: 'Physical Geology — Volcanic Soils and Mineral Resources (CC-BY 4.0)', url: 'https://openstax.org/books/physical-geology-2e' },
    { org: 'SI-GVP', title: 'Smithsonian GVP — Volcanic Resources and Human Settlement Patterns', url: 'https://volcano.si.edu' },
    { org: 'IAVCEI', title: 'IAVCEI — Volcanic Resources: Geothermal, Mineral, and Agricultural', url: 'https://www.iavcei.org' },
  ],
  sections: [
    {
      type: 'intro',
      title: 'Why people live on volcanoes',
      body: `The slopes of Mt. Etna in Sicily have been farmed for 2,500 years. The island of Java — home to 145 million people, one of the most densely populated places on Earth — sits along one of the world's most active volcanic arcs. The volcanic highlands of Guatemala, Ethiopia, and Central Java support densities exceeding 1,000 people per square kilometre. These are not coincidences: volcanic soils are among the most fertile agricultural substrates on Earth, and the economic pull of highly productive land has drawn human populations to volcanic terrain throughout history, despite the hazard.

The productivity of volcanic soils reflects the chemistry of volcanic rock. Basalts and andesites contain high concentrations of **plant macronutrients** — calcium, magnesium, potassium, and phosphorus — locked in crystalline form. As volcanic rock weathers under rainfall and biological activity, these nutrients are progressively released into the soil. The result is **andosols** and **inceptisols** — young, nutrient-rich soils that, in tropical climates with high rainfall and temperature, can support extraordinary biomass and agricultural yields. Hawaiian soils developed on 10,000-year-old lava flows produce some of the most productive tropical agricultural land in the world; Javanese volcanic soils support two to three rice harvests per year.

Beyond agriculture, volcanic systems concentrate economic wealth in two other forms: **geothermal energy** — the heat stored in volcanic hydrothermal systems, accessible by drilling and convertible to electricity — and **hydrothermal ore deposits** — concentrations of metals (copper, gold, silver, zinc, lead, lithium, molybdenum) precipitated from hot volcanic fluids percolating through rock. Iceland derives 100% of its heating and ~35% of its electricity from geothermal sources; the geothermal industry generates $5 billion/year globally. The world's largest copper mines — in the Andes of Chile and Peru — are products of Cenozoic arc volcanism. The economic legacy of volcanism extends far beyond any single eruption.`,
      keyTerms: [
        { term: 'Andosol', def: 'A volcanic soil (from the Japanese words "an" = dark, "do" = soil) characterised by high organic matter content, high porosity, very high water retention capacity, and exceptional nutrient availability. Andosols develop from the weathering of volcanic ash and tephra and are found in tropical and temperate volcanic regions worldwide. They constitute only ~1% of global soil area but support approximately 10% of the world\'s population due to their exceptional agricultural productivity. Java, Japan, Central America, the Andes foothills, and parts of eastern Africa are dominated by andosols. Key limitation: andosols often have high phosphate fixation (aluminium and iron ions bind phosphate), which can limit phosphorus availability without fertilisation.' },
        { term: 'Geothermal energy', def: 'Energy derived from the natural heat of the Earth\'s interior, extracted at sites where volcanic or tectonic activity brings this heat close to the surface. At high-enthalpy hydrothermal systems (temperatures >150°C (302°F) at accessible depths), hot water and steam can be extracted by drilling and used to generate electricity via steam turbines. At lower temperatures (<150°C (302°F)), geothermal fluid is used directly for heating (district heating, greenhouses, industrial processes). Global geothermal electricity capacity: approximately 16 GW; total direct-use heating: ~100 GW thermal. Primary geothermal countries: Iceland, Kenya, New Zealand, Philippines, Indonesia, the United States (The Geysers, California).' },
        { term: 'Porphyry copper deposit', def: 'A large, low-grade ore deposit formed by the circulation of hot fluids (magmatic-hydrothermal fluids) through fractured porphyritic intrusive rocks associated with arc volcanism. Porphyry deposits contain 0.1–2% copper by weight distributed through billions of tonnes of rock, making them the world\'s most important source of copper (~80% of global copper supply) despite low grade. They typically also contain gold, molybdenum, and silver as by-products. Formation requires: hot, oxidised, volatile-rich (SO₂, H₂S, HCl) magmatic fluids exsolving from crystallising magma and migrating upward through fracture networks; metals precipitate as temperature and pressure drop. Examples: El Teniente and Escondida (Chile), Grasberg (Indonesia).' },
        { term: 'Volcanogenic massive sulfide (VMS) deposit', def: 'A sediment-hosted ore deposit formed by hot hydrothermal vent fluids (black smokers) at mid-ocean ridges or volcanic arcs, precipitating sulfide minerals rich in copper, zinc, lead, gold, and silver directly onto the seafloor or into sub-seafloor fractures. VMS deposits form when superheated (~350°C (662°F)) seawater-derived hydrothermal fluids, rich in dissolved metals leached from volcanic rock, mix with cold seawater and precipitate metal sulfides (chalcopyrite, sphalerite, galena, pyrite). When ancient ocean floors are subducted and accreted onto continents, VMS deposits may be preserved in ophiolite sequences on land. Examples: Cyprus (Troodos ophiolite), Iberian Pyrite Belt (Spain and Portugal).' },
        { term: 'Hydrothermal alteration', def: 'The chemical modification of volcanic rock by hot water (hydrothermal fluid) percolating through fractures, replacing original minerals with secondary alteration minerals (clay minerals, silica, carbonates, sulfides). Hydrothermal alteration both destroys rock strength (creating hazardous mechanically weak zones, as at Mt. Rainier) and concentrates valuable metals. The alteration mineral assemblage records the temperature and chemistry of the fluid: propylitic alteration (chlorite, epidote, calcite) at lower temperatures peripherally; phyllic alteration (quartz, sericite, pyrite) at moderate temperatures; potassic alteration (K-feldspar, biotite, magnetite) at highest temperatures near the heat source.' },
      ],
    },
    {
      type: 'concept',
      title: 'Volcanic soils and why they draw populations to hazardous terrain',
      body: `**The fertility paradox: why live on a volcano?** From a purely rational risk-benefit perspective, living on the flanks of an active volcano appears irrational. Yet the demographic evidence is unambiguous: volcanic terrain worldwide supports higher agricultural population densities than comparable non-volcanic landscapes. The explanation lies in the exceptional nutrient density of volcanic soils and the rapidity with which they develop. On relatively young (10,000–100,000 year) basaltic lava flows in tropical climates, weathering and biological activity can generate highly productive **andosols** within a few thousand years. The nutrients locked in mafic volcanic minerals (Ca, Mg, K, P, Fe) are released by chemical weathering reactions involving rainfall, carbonic acid from organic matter decay, and mycorrhizal fungi. The result is soil that produces crop yields comparable to fertilised agricultural land without synthetic inputs.

**The Java example: 145 million people on volcanic soil.** Java — the most densely populated island of comparable size on Earth — sits above the Sunda subduction zone, with 45 active volcanoes along its length. The island's volcanic soils (predominantly andosols derived from andesitic and basaltic tephra) sustain irrigated rice agriculture at yields of 4–6 tonnes (6.6 tons)/hectare without chemical fertilisation — among the highest in the non-industrialised agricultural world. Merapi, Semeru, Bromo, and other Javanese volcanoes have erupted dozens to hundreds of times in recorded history, killing thousands and displacing millions. Yet population density on Javanese volcanic slopes exceeds 1,000 people per km² — higher than the non-volcanic western Java lowlands. Studies of Javanese farming communities show that farmers are well aware of the hazard and consciously accept it in exchange for the agricultural productivity of volcanic soil. This is not naivety but a rational, if tragic, cost-benefit calculation that has been made by agricultural societies for millennia.

**Rates of soil development and fertility gradients.** The fertility of volcanic soil is time-dependent: freshly erupted lava is nearly sterile (no organic matter, limited weathered mineral surface area). But the progression from bare lava to productive agricultural soil can be surprisingly rapid in tropical conditions. Hawaii provides a natural gradient experiment: lava flows of known ages (from recent Kīlauea flows to ~150,000-year-old Kohala flows) show measurable soil nutrient accumulation within centuries and agriculturally productive soils within 5,000–20,000 years. The pattern is not linear — an initial period of nitrogen limitation (colonisation by nitrogen-fixing plants like Myrica faya and native shrubs) is followed by a period of high productivity as nitrogen accumulates, then a transition to phosphorus limitation on old (>100,000 year) weathered soils. This **Walker-Syers pedogenic sequence** has been documented along the Hawaiian chronosequence and is a model for understanding volcanic soil development globally.`,
      cards: [
        {
          name: 'Andosols: Chemistry, Productivity, and Distribution',
          icon: Layers,
          color: BRAND.jade,
          desc: 'High organic matter: 4–10% (vs. 1–3% in typical soils). Very high water retention: 100–200% by weight. Exceptional cation exchange capacity: releases Ca²⁺, Mg²⁺, K⁺, Fe²⁺, PO₄³⁻. Formed from: tephra and volcanic ash weathering (plagioclase, pyroxene, olivine → amorphous allophane, imogolite, ferrihydrite). Limitation: high phosphate fixation by Al/Fe compounds. Geographic distribution: Indonesia, Japan, Central America, Ethiopia Highlands, New Zealand, Andes foothills. ~1% of global land area; supports ~10% of world population. Development time: 500–20,000 years in tropical climates.',
          examples: 'Java: 145M people on volcanic soil, rice yields 4–6 t/ha without synthetic fertiliser · Hawaii chronosequence: 300-year-old lava → early soil; 5,000-year lava → agriculturally productive andosol · Ethiopian Highlands: andosol-supported Teff cultivation sustains 110M people · Guatemala volcanic highlands: intensive Maya agriculture 2,000+ years on andosols; modern maize yields among highest in subsistence farming · Philippines: ~30% of agricultural land on volcanic soil',
        },
        {
          name: 'Risk-Benefit Trade-off: Population and Volcano Proximity',
          icon: TrendingUp,
          color: BRAND.coral,
          desc: 'Global pattern: population density higher within 100 km (62 mi) of volcanoes than comparable non-volcanic terrain. ~800 million people live within 100 km (62 mi) of a historically active volcano (Smithsonian GVP analysis). At high hazard volcanoes: Merapi (Indonesia) slopes 1,000+ people/km²; Vesuvius (Italy) 3 million in red zone; Popocatépetl (Mexico) 25 million within 70 km (43 mi). Economic drivers: volcanic soil productivity, geothermal energy, tourism, mining of volcanic mineral resources. Historical depth: Pompeii was rebuilt on Vesuvius slopes repeatedly post-eruption. Cultural factors: spiritual attachment to volcanic landscapes; ancestral land tenure; limited mobility for subsistence farmers. Risk-mitigation response: evacuation plans, early warning systems, land-use zoning.',
          examples: 'Merapi: 400,000 evacuated 2010; most returned within weeks to farm the volcanic slopes · Vesuvius: Naples population doubled despite 1631 eruption killing 4,000+ because volcanic soil productivity outweighed perceived risk · Popocatépetl 2000: 50,000 evacuated; many refused citing crop loss · Java rice: 2–3 harvests/year on volcanic soil vs 1 harvest/year on non-volcanic soils in same climate zone — quantifiable fertility premium',
        },
      ],
    },
    {
      type: 'concept',
      title: 'Geothermal energy and volcanic mineral deposits',
      body: `**Geothermal energy: tapping volcanic heat.** Geothermal energy extraction exploits the fact that volcanic and tectonically active regions maintain anomalously high heat flow in the crust — heat that, in hydrothermal systems, is already concentrated in hot fluid (water and steam) circulating through fractures. Drilling into these systems accesses fluid at temperatures of 150–350°C (662°F) under pressure; when brought to the surface, this fluid flashes to steam and drives turbines to generate electricity. Geothermal power is **baseload** — unlike solar and wind, it operates 24 hours a day independent of weather, with capacity factors of 85–95%. Iceland is the world's showcase: the country sits on the Mid-Atlantic Ridge (a divergent plate boundary), giving it extraordinary geothermal potential; 100% of Iceland's domestic heating and ~35% of its electricity comes from geothermal and hydropower combined, making it one of the lowest per-capita carbon emitters in the world despite high energy consumption. Kenya's Olkaria geothermal field in the East African Rift generates over 800 MW, accounting for ~50% of Kenya's electricity and providing clean power at costs competitive with coal.

**Porphyry copper and arc volcanism: the Chilean copper belt.** The Andes of Chile and Peru are underlain by one of the world's most concentrated accumulations of porphyry copper deposits — the product of ~100 million years of subduction beneath South America. As hydrous, volatile-rich magmas generated by slab dehydration ascend through the crust, they crystallise at shallow depths and exsolve metal-rich, sulfurous hydrothermal fluids. These fluids migrate upward through fracture networks, and as temperature and pressure drop, they precipitate copper, gold, and molybdenum sulfide minerals in a diffuse but enormous volume of fractured rock. Chile's Escondida mine (the world's largest copper mine, ~1.2 billion tonnes of ore at 1% Cu) is a porphyry deposit formed during Eocene subduction magmatism. The Atacama Desert — the driest non-polar desert on Earth, underlain by Andean volcanic and intrusive rocks — also contains the world's largest lithium reserves (in salar evaporite brines enriched by volcanic springs), making Chile a critical supply node for the global electric vehicle battery industry.

**Seafloor hydrothermal vents and VMS deposits.** At mid-ocean ridges, superheated seawater (heated to ~350–400°C (752°F) by contact with cooling magma) circulates through oceanic crust, leaches metals from basalt, and discharges as **black smokers** — columns of dark, metal-sulfide-rich fluid that precipitate polymetallic chimneys on the seafloor. These active deposits are forming VMS ores in real time. When ancient oceanic crust is preserved as **ophiolites** (sections of ocean floor thrust onto continental margins), ancient VMS deposits become accessible on land. The Iberian Pyrite Belt (Spain and Portugal) is the largest known accumulation of VMS deposits, containing >1.7 billion tonnes of massive sulfide with significant Cu, Zn, Pb, Ag, and Au. Mining the Iberian Pyrite Belt has driven economy in southern Spain and Portugal for 5,000 years — the Romans intensively mined it at Río Tinto; the mine is still active today.`,
      cards: [
        {
          name: 'Geothermal Energy: Iceland and Kenya',
          icon: Thermometer,
          color: BRAND.amethyst,
          desc: 'High-enthalpy systems (>150°C (302°F)): flash steam or binary cycle power generation. Capacity factors: 85–95% (vs 25–35% for solar/wind). Iceland: sits on MAR + Greenland plume; 100% of district heating geothermal; ~35% electricity; geothermal equivalent of ~20 million barrels of oil/year. Kenya Olkaria (East African Rift): 800+ MW installed, ~50% of national electricity; competitive with coal at $0.07/kWh. Global installed capacity: ~16 GW electricity + ~100 GW thermal. US: The Geysers (California), 725 MW — world\'s largest single geothermal complex; steam directly from dry steam field. Philippines: ~2,000 MW from 8 geothermal plants (Tiwi, MAKBAN, Leyte); ~25% national electricity. New Zealand Wairakei: operating since 1958; 385 MW.',
          examples: 'Iceland: Reykjavik 99% geothermally heated; population never saw coal or oil heating · Kenya Olkaria expansion: 2,000 MW target by 2030; World Bank funded; lower carbon intensity than any fossil alternative · Larderello (Italy): world\'s first geothermal electricity plant (1904); still operating; produces >600 MW · Enhanced geothermal systems (EGS): drilling into hot dry rock, fracturing, circulating water — expands geothermal to non-volcanic regions',
        },
        {
          name: 'Porphyry Copper Deposits: Arc Volcanism and Critical Metals',
          icon: Zap,
          color: BRAND.gold,
          desc: 'Formation: magmatic-hydrothermal fluids exsolve from crystallising arc magma; fluids migrate up fracture network; Cu, Au, Mo sulfides precipitate as T/P drops. Grade: 0.1–2% Cu; typically 0.3–1% economically. Volume: billions of tonnes of ore. World copper supply: ~80% from porphyry deposits. Chilean examples: Escondida (1.2 Bt at 1% Cu), El Teniente (world\'s largest underground mine), Collahuasi, Chuquicamata. Atacama lithium brines: volcanic springs enrich Atacama salar with Li; Chile holds ~60% of world\'s known lithium reserves. Grasberg (Indonesia): world\'s largest gold and 3rd-largest copper deposit in an arc porphyry. Formation age: most Chilean porphyries Eocene-Miocene (50–10 Ma), linked to flat-slab subduction.',
          examples: 'Escondida: opened 1990; produces ~1.2 Mt Cu/year (5% of world supply); operated by BHP · El Teniente: ~6,000 m (19686 ft) of underground tunnels; 14,000 workers; 462,000 t Cu/year · Atacama Li: SQM and Albemarle brine extraction from Salar de Atacama; ~140,000 t Li/year (2023); feeds global EV battery supply chain · Grasberg (Papua, Indonesia): 86 Mt Cu + 2,500 t Au reserves; Freeport-McMoRan; most controversial mining project in the Pacific',
        },
        {
          name: 'VMS Deposits, Black Smokers, and Seafloor Ores',
          icon: Globe,
          color: BRAND.ruby,
          desc: 'VMS (Volcanogenic Massive Sulfide): Cu-Zn-Pb-Ag-Au deposits formed at seafloor hydrothermal vents. Black smokers: 350–400°C (752°F) fluid vents on mid-ocean ridges; precipitate chalcopyrite, sphalerite, galena, pyrite chimneys. Metal source: leached from basaltic oceanic crust by circulating seawater. Preservation: VMS deposits formed at ancient ridges preserved in ophiolites accreted to continents. Iberian Pyrite Belt (Spain/Portugal): >1.7 Bt massive sulfide; Rio Tinto mine (oldest continuously operated mine, 5,000 years). Cyprus (Troodos ophiolite): "cuprum" = copper of Cyprus, named by Romans for Troodos VMS deposits. Active seafloor VMS: TAG mound (Mid-Atlantic Ridge), active formation of Cu-Zn ore at 3,670 m (12041 ft) depth. Deep-sea mining: proposed for SMS (seafloor massive sulfide) deposits; regulatory debate ongoing.',
          examples: 'Rio Tinto (Spain): Romans extracted ~90 Mt ore over 400 years; still active; drainage water so acidic (pH 2) it resembles Mars surface water analogue · Troodos ophiolite (Cyprus): source of the word "copper" (cuprum); Roman-era mines still visible · TAG hydrothermal field: 200 m (656 ft) tall sulfide mound, 1.8 Mt Cu; only discovered 1985 · ISA (International Seabed Authority): regulates deep-sea mining exploration claims; 31 exploration contracts issued as of 2024; no commercial extraction yet',
        },
      ],
    },
    {
      type: 'visualization',
      title: 'The hydrothermal system: from volcanic heat to mineral deposits and geothermal energy',
      body: `This flow traces how volcanic heat drives hydrothermal circulation, concentrating metals into ore deposits and delivering energy to the surface — connecting volcanic hazard and volcanic resource in a single system.`,
      interaction: {
        type: 'flow-simulator' as const,
        description: 'The hydrothermal cycle driven by volcanic heat — from magma emplacement through fluid circulation to mineral precipitation and surface discharge as geothermal features',
        nodes: [
          { id: 'n1', label: 'Magma Intrusion', description: 'Hot magma (700–1,200°C (2192°F)) intrudes into the shallow crust, providing a sustained heat source. As the magma crystallises, it exsolves volatile-rich fluids (H₂O, CO₂, SO₂, HCl, metals in solution). Porphyry copper systems: magmatic fluids carry Cu, Au, Mo in solution at high temperature and pressure.', color: BRAND.ruby },
          { id: 'n2', label: 'Fluid Heating and Metal Leaching', description: 'Surface water and groundwater percolate down through fractured rock toward the heat source. As fluid heats to 200–400°C (752°F), it dissolves metals (Cu, Zn, Pb, Au, Ag) from volcanic rock. At mid-ocean ridges, seawater is the fluid source; in continental arc systems, meteoric water dominates. Metal-rich fluid becomes buoyant and rises.', color: BRAND.coral },
          { id: 'n3', label: 'Metal Transport in Solution', description: 'Hot, acidic, metal-rich fluid migrates upward through fractures and permeable zones. Metals are transported as chloride complexes (CuCl₂⁻, ZnCl₄²⁻) at high temperature. Temperature, pressure, and salinity control metal solubility — hotter, saltier, more acidic conditions keep more metal in solution. High-grade ore systems require focused fluid flow through fracture networks.', color: BRAND.gold },
          { id: 'n4', label: 'Ore Mineral Precipitation', description: 'As fluid cools, pressure drops, or encounters different chemistry (e.g., mixing with cooler groundwater), metals exceed solubility and precipitate as sulfide minerals: chalcopyrite (CuFeS₂), sphalerite (ZnS), galena (PbS), pyrite (FeS₂), native gold. In porphyry systems, precipitation occurs in fracture halos around the intrusion. In VMS systems, precipitation occurs at the seafloor contact with cold seawater.', color: BRAND.amethyst },
          { id: 'n5', label: 'Geothermal Surface Expression', description: 'Hot fluid that reaches the surface without depositing all its heat creates geothermal features: geysers (steam-heated water erupting periodically), fumaroles (steam and gas vents), hot springs (boiling or near-boiling groundwater), mud pots (acidic hot springs dissolving clay). These surface expressions mark the top of the hydrothermal system and are the target for geothermal energy drilling.', color: BRAND.jade },
          { id: 'n6', label: 'Geothermal Energy Extraction', description: 'Drilling 1–4 km (2.5 mi) into the hydrothermal system accesses steam or superheated water at 150–350°C (662°F). Flash steam or binary cycle turbines convert thermal energy to electricity. Production wells draw hot fluid; injection wells return cooled fluid to maintain reservoir. A single geothermal well can produce 5–50 MW of electricity; a field of 20–50 wells constitutes a power plant. The hydrothermal system is sustained by the underlying magmatic heat source.', color: BRAND.accent },
        ],
        edges: [
          { from: 'n1', to: 'n2', label: 'conducts/convects heat' },
          { from: 'n2', to: 'n3', label: 'buoyant ascent' },
          { from: 'n3', to: 'n4', label: 'cooling/mixing' },
          { from: 'n3', to: 'n5', label: 'surface discharge' },
          { from: 'n5', to: 'n6', label: 'drilling intercepts' },
        ],
      },
    },
    {
      type: 'quiz',
      questions: [
        {
          q: 'Java (Indonesia) has one of the highest agricultural population densities in the world — exceeding 1,000 people per km² in volcanic highland areas — despite being underlain by one of the most seismically and volcanically active subduction zones on Earth. Farmers on the slopes of Mt. Merapi continue farming even after repeated devastating eruptions. What economic and agricultural factors explain this pattern, and why is it not simply ignorance of volcanic hazard?',
          a: [
            'The high population density on Javanese volcanic terrain reflects historical patterns of forced labour under Dutch colonial plantation agriculture; during the colonial era, people were forcibly settled on volcanic slopes to work coffee and sugar plantations; the current population distribution reflects this colonial legacy rather than any current agricultural rationality',
            'Javanese volcanic soils (andosols) produce rice yields of 4–6 tonnes (6.6 tons)/hectare without synthetic fertilisation, supporting 2–3 harvests per year — productivity that is not available on comparable non-volcanic soils in the same climatic zone; studies of Javanese farming communities show farmers are well aware of volcanic hazard but make a rational cost-benefit decision: the agricultural value of volcanic soil over a lifetime of farming typically exceeds the expected cost of periodic eruption disruption; this is not ignorance but a calculated trade-off that agricultural communities worldwide have made for millennia on volcanic terrain',
            'Javanese volcanic soils are not actually more fertile than non-volcanic soils in the same region; the high population density on volcanic terrain is explained by Java\'s cultural and religious traditions — volcanic mountains are considered sacred in Javanese Hindu-Buddhist cosmology, and farming on sacred slopes is considered spiritually meritorious regardless of productivity; the agricultural output is the same as non-volcanic farmland',
            'The population density pattern is explained by government policy: Indonesian law requires all agricultural land above 500 m (1640 ft) elevation to be farmed continuously to prevent erosion; since most land above 500 m (1640 ft) in Java is volcanic, this creates high population density on volcanic terrain regardless of market incentives',
          ],
          correct: 1,
          explain: 'While colonial plantation agriculture did shape aspects of Javanese land use, the current population distribution on volcanic slopes reflects ongoing agricultural productivity that long predates Dutch colonialism — Javanese volcanic agriculture is documented for over 2,000 years (Borobudur reliefs show rice terracing on volcanic slopes in the 9th century CE); blaming the entire pattern on colonial legacy is historically incomplete (A overstates the colonial factor). The claim that Javanese volcanic soils are not more fertile than non-volcanic soils is contradicted by extensive agronomic data; andosol rice yields of 4–6 t/ha compare to 2–3 t/ha on non-volcanic soils in comparable climatic zones; cultural and religious factors do contribute to settlement patterns but are not the primary explanation for the quantifiable fertility premium (C misidentifies the primary driver). No such Indonesian law requiring continuous cultivation above 500 m (1640 ft) exists; government policy in Indonesia has generally tried to resettle people away from high-hazard volcanic zones, not force them onto them (D is factually invented). The correct answer is B: the Javanese volcanic farming pattern is a rational response to a real agricultural productivity premium. Andosols on young volcanic deposits are among the world\'s most productive soils for tropical staple crops. Studies of Merapi farming communities post-eruption (notably by anthropologist Turgo Emrus and volcanology-sociology researchers) consistently find that farmers perceive the hazard clearly but weigh it against land value, yields, and the impossibility of accessing equivalent-quality land elsewhere in a densely populated island. The tragic outcome of eruptions like Merapi 1994 and 2010 does not make this calculation irrational — it reflects a genuine resource scarcity in which volcanic terrain is the most productive agricultural land available.',
        },
        {
          q: 'Iceland generates 100% of its domestic space heating and approximately 35% of its electricity from geothermal and hydropower sources combined. The country sits on the Mid-Atlantic Ridge, where the North American and Eurasian plates are diverging. What specific aspects of Iceland\'s tectonic setting create the geothermal resources that make this energy system possible, and could this model be replicated in non-volcanic countries?',
          a: [
            'Iceland\'s geothermal resources arise entirely from the Mid-Atlantic Ridge divergence; all countries with mid-ocean ridge segments would have identical geothermal potential, and Iceland\'s energy system could be directly replicated in any country adjacent to a divergent plate boundary',
            'Iceland\'s geothermal resources arise from the combination of two geological features: the Mid-Atlantic Ridge (providing high heat flow, rifting, and magmatic activity from mantle upwelling) and the Iceland mantle plume (anomalously hot mantle material rising beneath Iceland, making heat flow significantly higher than elsewhere along the ridge); this dual source explains why Iceland has extraordinary geothermal potential compared to other ridge segments; the Iceland model can be replicated in other high-heat-flow volcanic and rift regions (East African Rift, Taupo Volcanic Zone, Cascades) but not in continental interiors where heat flow is low; enhanced geothermal systems (EGS) technology aims to extend geothermal access to non-volcanic regions by drilling into hot dry rock and creating artificial hydrothermal fracture networks',
            'Iceland\'s geothermal resources arise from nuclear fission reactions in the crust below Iceland; the elevated heat flow reflects concentrations of radioactive uranium and thorium in Icelandic basement rocks that are significantly higher than the global average; since Iceland sits on young oceanic crust (not old continental crust), these radioactive elements are unusually abundant',
            'Iceland\'s geothermal success is primarily a result of government investment and political will, not geology; any country with sufficient drilling technology and government support could achieve equivalent geothermal energy penetration regardless of its tectonic setting; the geological factors are secondary to the policy and investment factors',
          ],
          correct: 1,
          explain: 'Not all mid-ocean ridge segments have Iceland\'s level of geothermal resources; Iceland is exceptional because it sits above both the ridge AND a mantle plume (the Iceland hotspot); other ridge segments on the seafloor are inaccessible for drilling and have heat flow, while elevated relative to continental interiors, that is significantly lower than Iceland\'s dual-source system (A overgeneralises the ridge-only explanation). Heat flow in Iceland is not caused by unusually radioactive crustal rocks; Iceland sits on young oceanic basaltic crust which is actually relatively low in radioactive elements compared to old continental granitic crust; the heat is magmatic in origin, not radiogenic (C is factually wrong about the heat source). While policy and investment are important enabling factors, they cannot substitute for the fundamental physics: drilling into cold rock (low heat flow) cannot produce geothermal energy regardless of drilling depth and government investment; countries like Denmark and Germany with low geothermal heat flow have invested heavily but produce minimal geothermal energy (D overstates the role of policy relative to geology). The correct answer is B: Iceland\'s extraordinary geothermal endowment arises from two simultaneous geological advantages — the Mid-Atlantic Ridge provides continuous magmatic heat from mantle upwelling along a rifting plate boundary, and the Iceland mantle plume delivers anomalously hot mantle material directly beneath Iceland, elevating heat flow well above any other accessible ridge segment. The combination produces temperatures of 200–350°C (662°F) at only 1–2 km (1.2 mi) depth in many parts of Iceland. This model is directly replicable in other high-heat-flow volcanic regions: Kenya\'s East African Rift, New Zealand\'s Taupo Volcanic Zone, Indonesia, the Philippines, and parts of the western United States all have active geothermal programmes. EGS technology aims to extend geothermal to non-volcanic regions by hydraulically fracturing hot dry rock at 3–5 km (3.1 mi) depth.',
        },
        {
          q: 'Porphyry copper deposits — formed by volcanic arc magmatism — account for approximately 80% of the world\'s copper supply. Chile\'s Atacama region contains some of the world\'s largest porphyry copper deposits as well as massive lithium brine reserves. What is the geological relationship between arc volcanism and the formation of these ore deposits, and why are they concentrated in the Atacama specifically?',
          a: [
            'Porphyry copper deposits form because copper is more abundant in the oceanic crust being subducted beneath the Andes than in continental crust; as the oceanic plate melts, copper is released and rises with the magma; it concentrates at the surface because the Atacama\'s extreme aridity has prevented erosion from removing the surficial ore',
            'Arc volcanism generates porphyry copper deposits through the following mechanism: subducting oceanic crust releases volatile-rich fluids (H₂O, SO₂, HCl, CO₂) into the mantle wedge, triggering flux melting; the resulting oxidised, volatile-rich, silicic arc magmas ascend into the crust; as these magmas crystallise at 2–10 km (6.2 mi) depth, they exsolve metal-bearing hydrothermal fluids (carrying Cu, Au, Mo as chloride complexes); these fluids migrate outward through fracture networks in the host rock; as temperature and pressure decrease, metal sulfide minerals precipitate (chalcopyrite, bornite, molybdenite); in the Atacama specifically, the combination of multiple periods of Cenozoic subduction magmatism (Eocene to Miocene, 50–10 Ma), subsequent deep erosion that removed the volcanic cap and exposed the ore, and the hyper-arid Atacama climate that slowed chemical weathering and preserved the ore have created the world\'s richest copper province',
            'Porphyry copper deposits in the Atacama form through metamorphic reactions: the pressure of the overlying Andes on pre-existing copper-bearing rock concentrates copper into economic deposits; the volcanic activity is coincidental rather than genetically related to the ore formation; the Atacama is rich in copper because Andean mountain building compressed existing copper-bearing strata into concentrated ore zones',
            'Porphyry copper deposits form at the same time as arc volcanoes erupt at the surface; the ore is found directly beneath volcanoes; to locate Atacama copper deposits, geologists simply drill beneath the largest ancient volcanic cones; the copper is a by-product of the same process that produces the surface lava flows',
          ],
          correct: 1,
          explain: 'The oceanic crust being subducted is not the primary source of the copper in porphyry deposits; the copper primarily derives from partial melting of the mantle wedge and from incorporation of crustal material into the arc magma system; subducted oceanic crust carries some metals but its melting at depth is not the main copper-enrichment mechanism; moreover, the aridity explanation for preservation is incomplete without explaining the genetic link (A misidentifies the copper source). Metamorphic compression does not produce porphyry ore deposits; metamorphism of copper-bearing rock produces different mineralization styles (copper skarns, for instance); porphyry deposits require specific fluid chemistry from magmatic-hydrothermal processes, not compressive metamorphism (C describes a non-existent ore-forming mechanism). While porphyry deposits do form beneath the volcanic edifice, they are not found directly beneath volcanic cones in a simple vertical relationship; the ore-forming intrusions are typically somewhat offset from the volcanic centres and emplaced at 2–10 km (6.2 mi) depth during crystallisation of the intrusive (plutonic) equivalents of the volcanic rocks; drilling directly beneath volcanic cones is not the standard exploration approach (D oversimplifies the spatial relationship). The correct answer is B: porphyry copper formation is a two-stage process. First, arc magmatism generates oxidised, volatile-rich magmas from flux melting of the mantle wedge. Second, as these magmas crystallise at shallow crustal depths, volatile-rich fluids exsolve — a process called second boiling — carrying metals in solution as chloride complexes. These fluids migrate through fractures in the crystallising intrusion and surrounding rock, precipitating metal sulfide minerals as they cool. The Atacama\'s exceptional copper wealth reflects the coincidence of multiple Cenozoic magmatic events (particularly the Eocene-Oligocene magmatic flare-up), subsequent erosion to productive crustal depths, and hyperarid preservation.',
        },
        {
          q: 'Black smoker hydrothermal vents at mid-ocean ridges actively precipitate copper, zinc, gold, and silver sulfide minerals onto the seafloor — forming seafloor massive sulfide (SMS) deposits. Several companies are pursuing commercial extraction of these deposits from the seafloor at depths of 1,000–3,500 metres. What are the key scientific arguments for and against deep-sea mining of SMS deposits, compared to mining the equivalent VMS deposits that have been exposed on land?',
          a: [
            'Deep-sea SMS mining is scientifically superior to land-based VMS mining in every respect: the ore grades are higher (pure sulfide mineral mounds vs. disseminated land VMS), there are no human populations to displace, the environmental footprint is entirely contained within the deep sea (which has no economic value), and robotic mining technology eliminates worker safety risks; land-based VMS mining should be phased out in favour of SMS deposits as soon as technically feasible',
            'The scientific arguments for SMS mining include: (1) high ore grades (SMS mounds can be 5–20% Cu, compared to 1–3% for land-based VMS and 0.3–1% for porphyry); (2) no requirements for terrestrial land clearing, community displacement, or freshwater use; (3) potentially lower overburden removal requirements. Scientific arguments against include: (1) deep-sea hydrothermal vent ecosystems are among the most unusual and poorly understood on Earth, hosting chemosynthetic food webs that do not depend on sunlight; many species are endemic to single vent sites and would be permanently destroyed by mining; (2) deep-sea sediment plumes from mining operations could travel thousands of kilometres, affecting filter-feeding organisms in the water column; (3) recovery rates of benthic ecosystems after disturbance are measured in decades to centuries; (4) the deep ocean is not economically valueless — it provides ecosystem services (carbon cycling, fisheries support) and is the frontier of biological discovery',
            'Deep-sea SMS deposits do not contain economically significant copper or gold; the metals are highly diluted by seawater and form very low-grade deposits that cannot be processed economically; the black smoker "deposits" are visual curiosities rather than viable ore deposits; SMS mining is technically impossible at existing depths',
            'The primary scientific argument against SMS mining is that removing metal from the deep ocean would disrupt ocean chemistry and trigger global ocean acidification; copper and zinc sulfides dissolve slowly into seawater and help buffer its pH; removing these deposits would alter ocean metal chemistry in ways that could harm marine organisms globally',
          ],
          correct: 1,
          explain: 'The claim that the deep sea has "no economic value" is incorrect — the deep ocean provides critical ecosystem services including carbon sequestration, nutrient cycling, and the biological foundation of open-ocean fisheries; additionally, claiming SMS mining is superior "in every respect" ignores documented scientific concerns about biodiversity impacts (A presents an incomplete and advocacy-oriented view). SMS deposits do contain economically significant copper, zinc, gold, and silver at high grades (5–20% Cu has been measured at TAG and Solwara 1 prospects); the assertion that they are not viable ore deposits is contradicted by multiple resource evaluations; Nautilus Minerals evaluated the Solwara 1 deposit in Papua New Guinea at grades exceeding 7% Cu before the company went bankrupt; D\'s claim that sulfides buffer ocean pH is not scientifically supported — sulfide oxidation in seawater produces acidic conditions, not buffering (C and D both contain factual errors). The correct answer is B: SMS deposits represent genuinely high-grade ore targets, but deep-sea mining raises serious documented environmental concerns. Hydrothermal vent ecosystems are the only large ecosystems on Earth not ultimately dependent on solar energy — they run on chemical energy from volcanic fluids (chemosynthesis by sulfur-oxidising and methane-oxidising bacteria). These ecosystems are biologically extraordinary: they were only discovered in 1977 and contain species not found anywhere else. Mining a vent system would permanently destroy an irreplaceable ecosystem. Sediment plumes from seafloor mining are a documented concern from manganese nodule mining experiments — the 1970s IOM plume experiment in the Pacific showed sediment clouds persisting for months and settling over areas 100× the size of the mining footprint. The ISA has issued exploration permits but faces a governance challenge: the international community has not agreed on adequate environmental protection frameworks before permitting commercial extraction.',
        },
        {
          q: 'Hydrothermal alteration — the chemical modification of volcanic rock by hot acidic fluids — both creates valuable ore deposits and weakens the structural integrity of volcanic edifices. Mt. Rainier\'s interior is extensively hydrothermally altered, creating a lahar hazard even without eruption. The same process that creates weakness at Rainier creates copper and gold ore at Escondida. What determines whether hydrothermal alteration produces dangerous rock weakness versus economic mineral concentration, and can both occur in the same system?',
          a: [
            'Hydrothermal alteration cannot produce both ore deposits and rock weakness in the same volcanic system; ore-forming alteration occurs at high temperatures (>300°C (572°F)) in deep, stable intrusions, while weakness-forming alteration occurs at low temperatures (<100°C (212°F)) near the surface; the two processes are spatially and thermally separated and do not co-occur in the same volcanic edifice',
            'Both outcomes — ore concentration and rock weakening — commonly occur in the same hydrothermal system at different spatial positions and fluid conditions; the zonation of alteration types reflects fluid temperature and chemistry gradients: deep, hot (>300°C (572°F)), potassium-rich fluids near the intrusion produce potassic alteration (K-feldspar, biotite, magnetite) — stable, strong minerals; intermediate-temperature (200–300°C (360–540°F)) zones produce phyllic alteration (quartz-sericite-pyrite) with ore mineral concentration; shallow, low-temperature (<150°C (302°F)) acidic fluids near the surface produce argillic alteration (smectite, kaolinite, halloysite) — weak clay minerals that reduce rock mass strength; at Mt. Rainier, millennia of volcanic gas circulation through groundwater has created extensive near-surface argillic alteration zones making the edifice prone to gravitational collapse; at Escondida, the economically valuable ore is in the deeper phyllic and potassic alteration zones while the surface expression is also clay-rich and mechanically weak',
            'The difference between ore formation and rock weakening is entirely determined by fluid chemistry: sulfuric acid produces ore minerals while carbonic acid produces clay minerals; since different volcanic systems emit different gas mixtures (some rich in SO₂, others in CO₂), the type of alteration is fixed by volcano chemistry and is constant throughout the system; no single volcano can produce both ore and weakening simultaneously',
            'Hydrothermal alteration only weakens rock if the volcano is currently active; ancient, extinct volcanic systems develop ore deposits while active volcanic systems develop dangerous clay-rich zones; since Mt. Rainier is still volcanically active and Escondida formed in ancient Eocene volcanic rocks, the difference is simply the age of the hydrothermal system, not its spatial structure or fluid conditions',
          ],
          correct: 1,
          explain: 'High-temperature ore-forming alteration and low-temperature weakness-forming alteration do not occur in completely separate systems — they occur in vertical zones of the same system; the argillic clays that make Mt. Rainier\'s interior weak are part of the same hydrothermal system (the volcano\'s active geothermal system) that, deeper, would produce propylitic and potentially ore-bearing alteration (A incorrectly states they cannot co-occur in the same edifice). The distinction between alteration outcomes is not simply SO₂ vs. CO₂ acid source — both sulfuric and carbonic acid can produce clay minerals at low temperatures; the primary control on alteration mineralogy is temperature and pressure, not simply which acid is present; both SO₂ and CO₂-dominated systems can produce weak clay zones near the surface (C is oversimplified). The age of the volcanic system is not the primary determinant — both active and ancient systems have near-surface clay alteration (weak) and deeper ore-bearing alteration (potentially valuable); some very old ancient volcanic systems have been completely eroded to expose the ore-bearing roots; some very old systems have been so thoroughly weathered that both ore and structural integrity are compromised (D misattributes the control to age). The correct answer is B: the hydrothermal alteration zone in a volcanic system is internally differentiated by temperature and fluid chemistry gradients into concentric alteration halos. The key insight is that ore minerals (copper sulfides, gold) precipitate at intermediate to high temperatures where pH and redox conditions favour sulfide stability — typically in the phyllic and potassic zones at hundreds to thousands of metres depth in the active system. The weak clay minerals (smectite, kaolinite, halloysite) that reduce rock mass strength form at shallow levels where fluids have cooled and become highly acidic, attacking the aluminium silicate minerals of volcanic rock. This means that the surface of a hydrothermally active volcano (like Rainier or Campi Flegrei or Ruapehu) is simultaneously the zone of greatest mechanical weakness AND the zone of most intense chemical alteration — while potentially ore-bearing zones lie deeper, accessible only by drilling or where erosion has stripped the overburden.',
        },
      ],
    },
  ],
}

export default volcanicResources
