import { Flame, Globe, Mountain } from 'lucide-react'
import { BRAND } from '@/lib/brand'
import type { Lesson } from './types'

const volcanicMonitoring: Lesson = {
  id: 'volc-101-1-3-4',
  title: 'Volcanic Monitoring, Risk Assessment, and Early Warning',
  track: 'vol',
  trackName: 'Volcanology',
  level: 'Beginner',
  duration: '12 min',
  xpReward: 140,
  description: "Modern volcanic risk management integrates seismology, geodesy, gas geochemistry, satellite remote sensing, and probabilistic hazard assessment to forecast eruptions and protect communities. The discipline has matured from post-disaster reconstruction to proactive risk reduction — as demonstrated by the successful evacuation of hundreds of thousands of people before the 1991 Pinatubo eruption. Understanding monitoring methods and their limitations is essential for evaluating volcanic hazard information.",
  sources: [
    { org: 'USGS',     title: 'Volcano Hazards — Monitoring Methods at US Volcanoes',               url: 'https://volcanoes.usgs.gov/vhp/monitoring.html' },
    { org: 'USGS',     title: 'USGS Volcano Observatories — HVO, CVO, AVO, YVO, MVO',             url: 'https://www.usgs.gov/programs/VHP' },
    { org: 'OpenStax', title: 'Physical Geology — Volcanic Monitoring and Prediction (CC-BY 4.0)', url: 'https://openstax.org/books/physical-geology-2e' },
    { org: 'SI-GVP',   title: 'Smithsonian GVP — Global Volcanism Monitoring Network',            url: 'https://volcano.si.edu' },
    { org: 'AGI',      title: 'Glossary of Geology — Volcanic Monitoring and Alert Systems',       url: 'https://www.americangeosciences.org/' },
  ],
  sections: [
    {
      type: 'intro',
      title: 'From observation to early warning',
      body: `Modern volcanology has transformed over the past 50 years from a primarily observational and post-eruption science into a quantitative, multi-parameter monitoring discipline capable — in favourable circumstances — of providing days to weeks of warning before major eruptions. This transformation has saved hundreds of thousands of lives. The successful evacuation of 58,000 people from the vicinity of Mt. Pinatubo before the June 15, 1991 climactic eruption — preventing an estimated 20,000 deaths in what would otherwise have been the most lethal volcanic disaster of the 20th century — stands as the defining achievement of applied volcanology and demonstrates what is possible when monitoring data, scientific interpretation, governmental authority, and community communication work together effectively.

Volcanic monitoring is inherently a multi-parameter problem. No single measurement type is diagnostic of an impending eruption. Instead, modern volcano observatories integrate data from networks of **seismometers** (detecting magma-induced earthquakes), **GPS and tiltmeters** (measuring ground deformation from magma intrusion), **gas sensors and spectrometers** (quantifying volcanic gas emissions), **infrasound arrays** (detecting low-frequency eruption signals), and **satellite remote sensing** (measuring thermal anomalies, ground deformation with InSAR, and SO₂ emissions from space). The integration of these data streams — and the expert scientific interpretation of their significance — allows volcanologists to characterise the state of a volcanic system and identify when it is departing from background behaviour toward a pre-eruptive state.

Risk management around volcanoes, however, extends far beyond monitoring and forecasting. It requires understanding which communities are exposed to which hazards (**hazard maps**), how many people are at risk (**vulnerability assessment**), whether they have the capacity to evacuate effectively (**resilience assessment**), and whether institutional and social structures are in place to act on scientific warnings (**governance**). The tragic failures at Armero (1985), Galeras (1993), and Whakaari/White Island (2019) all occurred despite adequate scientific knowledge — they were failures of risk communication, institutional decision-making, or both.`,
      keyTerms: [
        { term: 'Seismic monitoring', def: 'The use of networks of seismometers around a volcano to detect and locate earthquakes associated with volcanic processes. Volcanic seismicity includes: (1) volcano-tectonic (VT) earthquakes — high-frequency (5–15 Hz) events caused by brittle fracture of rock as magma intrudes; (2) long-period (LP) earthquakes — low-frequency (0.5–5 Hz) events caused by fluid or magma movement in resonant conduit cavities; (3) harmonic tremor — sustained, continuous low-frequency vibration indicating persistent fluid flow through the conduit system, often a direct precursor to eruption. Swarms of increasing frequency and magnitude are a key eruption precursor.' },
        { term: 'Ground deformation monitoring', def: 'The measurement of surface deformation (inflation, deflation, tilt) caused by magma intrusion into the volcanic edifice using GPS networks, InSAR (Interferometric Synthetic Aperture Radar — satellite-based), electronic tiltmeters, and levelling surveys. Inflation (upward ground movement) indicates magma accumulating at depth; deflation indicates magma withdrawal or eruption. InSAR measures centimetre-scale ground deformation across areas of thousands of square kilometres using satellite radar, making it particularly powerful for monitoring remote volcanoes with sparse ground networks.' },
        { term: 'Probabilistic volcanic hazard assessment (PVHA)', def: 'A formal quantitative framework for estimating the probability of different volcanic scenarios and their consequences, similar to probabilistic seismic hazard assessment used in earthquake engineering. PVHA integrates eruption frequency statistics, eruption magnitude-frequency relationships, flow model simulations (PDC runout, lahar inundation), and uncertainty quantification to produce probability distributions of hazard (e.g., probability of >1 cm ashfall within 50 km within 50 years). Used to inform building codes, land-use planning, and emergency management priorities.' },
        { term: 'Volcanic alert level', def: 'A standardised scale communicating the current state of volcanic unrest and eruption probability to emergency managers, the public, and aviation. Different countries use different scales, but common frameworks include: (1) USGS/NWS: Normal → Advisory → Watch → Warning (for ground-based hazards) + Colour Code Green → Yellow → Orange → Red (for aviation ash hazard); (2) Philippines (PHIVOLCS): Level 0–5 (0 = quiet, 5 = eruption underway); (3) New Zealand: 0–5 (GeoNet). Alert levels trigger specific preparedness and evacuation actions under pre-established protocols and are not merely scientific statements.' },
        { term: 'Volcanic hazard map', def: 'A map showing the spatial distribution of different volcanic hazards (ashfall, PDC, lahar, lava flow, ballistics) and their estimated probabilities of occurrence. Used to inform land-use planning, building codes, evacuation planning, and emergency management. The quality of a hazard map depends on the completeness of the geological record of past eruptions, the accuracy of flow models, and the assumed eruption scenario. Hazard maps are probabilistic statements about future likelihood, not deterministic predictions — but their existence and communication to communities is a key factor in volcanic disaster prevention.' },
      ],
    },
    {
      type: 'concept',
      title: 'Monitoring networks, the Pinatubo success story, and the limits of forecasting',
      body: `**The multi-parameter monitoring approach.** Modern volcano observatories operate as continuous real-time monitoring centres that integrate data from multiple sensor networks and communicate their interpretation to civil authorities and the public. The five principal monitoring data streams are: (1) **Seismicity** — earthquake frequency, magnitude, depth, and wave-type characterisation; increasing shallow seismicity, transition from VT to LP earthquakes, and onset of harmonic tremor are all indicators of increasing magmatic activity. (2) **Ground deformation** — GPS networks detect millimetre-scale ground uplift from magma intrusion; InSAR can detect centimetre-scale deformation over thousands of square kilometres; tiltmeters detect very small inclinations of the volcanic edifice that precede eruptions by hours to days. (3) **Gas emissions** — SO₂ flux measured by DOAS or COSPEC; CO₂:SO₂ ratio indicating degassing depth; total CO₂ flux from soil measurements; temperature of fumarolic emissions. (4) **Thermal imaging** — infrared cameras and satellite thermal sensors detect heat anomalies from rising magma or increased fumarolic activity; lava dome growth can be tracked continuously. (5) **Acoustic/infrasound monitoring** — very low frequency (0.01–20 Hz) sound waves that travel efficiently through the atmosphere from explosive eruptions; arrays of infrasound sensors provide directional information and can detect eruptions at thousands of kilometres distance.

**The Pinatubo 1991 case study: science, governance, and communication.** The successful management of the Pinatubo crisis represents the gold standard of volcanic risk management. The Philippine Institute of Volcanology and Seismology (PHIVOLCS) and the USGS Volcano Disaster Assistance Program (VDAP) — a rapid-response team created specifically to assist countries experiencing volcanic crises — deployed a comprehensive monitoring network within days of the first signs of unrest in April 1991. Key events in the 57-day precursory period: April 2: fumaroles (steam vents) observed for the first time. April 7: first seismic network deployed. May 13: SO₂ flux measurement — 500 tonnes/day — interpreted as indicating fresh magma degassing. June 7: lava dome breaks surface — confirming magmatic eruption underway. June 12–13: escalating explosions; PHIVOLCS raised alert to Level 5; 58,000 people evacuated from the 30 km zone. June 15: climactic VEI 6 eruption at 13:42 local time; maximum column 35 km; 5 km³ erupted; coincides with Typhoon Yunya making landfall. The evacuation saved an estimated 5,000–20,000 lives. The scientific and institutional lessons from Pinatubo have become the foundation for volcanic crisis management globally.

**Probabilistic hazard assessment and scenario planning.** Volcanic eruptions do not follow a precise script — a volcano may produce a range of eruption sizes and styles, and monitoring data provide probabilistic rather than deterministic forecasts. Modern PVHA uses **event trees** — branching diagrams that assign probabilities to sequential decision nodes (e.g., probability of eruption within next 30 days given current unrest | probability that eruption is VEI ≥4 | probability that PDC reaches a given community) — to produce formal probability estimates for specific hazardous outcomes. These estimates are explicitly communicated with their uncertainties to civil protection authorities. The Bayesian Event Tree for Eruption Forecasting (BET_EF) framework, developed after the 1994 Merapi eruption, is now used operationally at several high-risk volcanoes. However, all probabilistic forecasting depends critically on the completeness and accuracy of the geological record of past eruptions — a volcano with few recorded historical eruptions (like Pinatubo, which had not erupted for 500+ years) has inherently greater uncertainty in its hazard assessment.

**Limits of forecasting and the problem of unrest without eruption.** The most challenging aspect of volcanic crisis management is the **false alarm problem**: most episodes of volcanic unrest do not culminate in eruption. A 2013 study of USGS volcano monitoring records found that ~50% of significant unrest episodes at US volcanoes did not result in eruption within two years. Issuing an evacuation for every episode of volcanic unrest would be financially, socially, and politically unsustainable — and would erode public trust in subsequent warnings. The 1984 Mammoth Mountain (California) unrest resulted in a 5.4 magnitude earthquake swarm interpreted as magma intrusion; the area was placed on alert but never erupted; the economic impact on the Mammoth Lakes tourist economy was substantial. Conversely, failing to issue timely warnings has led to catastrophic fatalities — the 1985 Galeras (Colombia) eruption killed nine scientists and tourists who had descended into the crater during a field conference, despite having been warned of increasing activity by one of the attending volcanologists (Stanley Williams, who survived severely injured). Managing the asymmetric costs of false alarms vs. missed eruptions remains the central challenge of operational volcanology.`,
      cards: [
        {
          name: 'Multi-Parameter Monitoring Networks',
          icon: Flame,
          color: BRAND.ruby,
          desc: 'Seismic: VT earthquakes (rock fracture), LP (fluid movement), harmonic tremor (continuous flow) → increasing frequency/shallowness → eruption precursor. Deformation: GPS (mm-precision), InSAR (satellite, cm-precision, 1,000s km²), tiltmeters (hourly). Gas: SO₂ flux (DOAS/COSPEC, t/day), CO₂:SO₂ ratio (depth indicator), TROPOMI satellite (global SO₂ detection). Thermal: infrared camera, MODIS/VIIRS satellite. Infrasound: eruption detection at global range. Real-time data telemetry: solar-powered seismometers in remote areas transmit to observatory via satellite. Integration: no single parameter is diagnostic; patterns across parameters.',
          examples: 'USGS VDAP: rapid-deployment monitoring team, deployed Pinatubo 1991, Nyiragongo 2002, Merapi 2010 · HVO (Hawaiian Volcano Observatory): 1912–present, oldest US volcano observatory · InSAR: detected 10 cm uplift at Yellowstone 2004–06, delineated magma intrusion depth',
        },
        {
          name: 'Alert Levels, Hazard Maps, and Evacuation',
          icon: Mountain,
          color: BRAND.coral,
          desc: 'Alert levels: 0 (quiet) → 5 (eruption/emergency), each triggers pre-planned response. Hazard maps: zone communities by hazard type/severity. Evacuation zones: concentric (proximal/medial/distal) or hazard-specific (lahar zones follow river valleys, not circles). Pre-established protocols: which agencies have authority to order evacuation; who receives what alert level. Community education: drills, signage, local knowledge of hazards. Communication: scientists → civil protection → media → public chain must be fast and clear. False alarm cost vs. missed eruption cost: asymmetric trade-off. Uncertainty communication: scientists must express probability, not false certainty.',
          examples: 'Pinatubo 1991: Level 5 issued June 12; 58,000 evacuated by June 14; eruption June 15 → 300–800 direct deaths (not 20,000+) · Merapi 2010: 400,000 evacuated, 367 deaths (mostly those who returned early) · Armero 1985: 23,000 dead despite hazard map existing — failure of communication chain',
        },
        {
          name: 'Probabilistic Forecasting and False Alarm Problem',
          icon: Globe,
          color: BRAND.jade,
          desc: 'Event tree/Bayesian forecasting: probability assigned at each decision node (unrest→eruption→VEI→impact zone). Explicitly quantifies uncertainty. ~50% of volcanic unrest episodes ≠ eruption. False alarm costs: economic disruption, evacuation stress, erosion of public trust in future warnings. Missed eruption costs: lives, infrastructure. Phreatic explosions: cannot be forecast by standard methods (no magmatic precursors). Unmonitored volcanoes: >1,400 Holocene volcanoes, <300 permanently monitored. TROPOMI satellite: monitors all volcanoes globally for SO₂, partially fills gap. VDAP rapid response: fills monitoring gap during crises at unmonitored volcanoes.',
          examples: 'Galeras 1993 (Colombia): killed 9 scientists/tourists in crater during conference, forewarned of unrest · Mammoth Mountain 1984: seismic swarm → alert → economic impact → no eruption · Kīlauea 2018: SO₂ and CO₂ monitoring provided 2+ weeks advance warning of LERZ eruption · Whakaari 2019: no precursory signals before deadly phreatic explosion',
        },
      ],
    },
    {
      type: 'quiz',
      questions: [
        {
          q: "A volcano observatory receives the following monitoring data over a 3-week period at a stratovolcano that last erupted 300 years ago: Week 1: seismicity increases from background (5/day) to 80/day, primarily volcano-tectonic earthquakes at 5–8 km depth. Week 2: seismicity continues at 100/day; GPS stations show 8 cm of ground inflation at the summit; SO₂ flux increases from near-zero to 300 tonnes/day; earthquake foci migrate from 5–8 km to 2–4 km depth. Week 3: seismicity transitions to dominantly low-frequency (LP) earthquakes at 200/day; harmonic tremor episodes detected; summit GPS shows 15 cm total inflation; a small lava dome appears at the summit vent. What interpretation does this sequence support, and what alert level decision does it call for?",
          a: [
            "The data pattern is consistent with magma intrusion and progressive approach to the surface: Week 1 VT seismicity at depth reflects magma fracturing country rock; Week 2 seismicity migration upward combined with SO₂ rise indicates magma in the shallow conduit (<5 km) degassing; Week 3 transition to LP/tremor indicates continuous magmatic fluid flow through the shallow system; dome appearance confirms magmatic eruption has begun; the cumulative deformation (15 cm) is consistent with significant volume addition at shallow depth; alert level should be escalated to Warning/Level 4–5, with immediate evacuation of proximal zones and standby for medial zones, and aviation authorities alerted for potential ash",
            "The data pattern is ambiguous — the transition from VT to LP earthquakes is normal seasonal variation in hydrothermal systems and the SO₂ increase could reflect heating of pre-existing hydrothermal fluids without fresh magma involvement; the dome appearance is concerning but could be a resurgent cryptodome from 300 years ago; the alert should remain at Advisory/Level 2 while additional data is collected over the next 2–4 weeks",
            "The seismicity increase alone (from 5 to 200/day) is sufficient to justify immediate maximum-level evacuation of all zones within 50 km; the other data (deformation, gas, dome) are secondary indicators that confirm but are not needed to justify the evacuation; any significant seismicity increase at a volcanic system should trigger immediate maximum evacuation",
            "The data pattern indicates tectonic rather than volcanic earthquake activity — the hypocentre depths (5–8 km) are too shallow for magmatic processes, which occur at >10 km depth; the LP earthquakes and tremor are artefacts of the inadequate seismometer calibration near a hydrothermally active summit; the SO₂ reflects nearby industrial sources; no volcanic alert is warranted",
          ],
          correct: 0,
          explain: "The interpretation in A correctly reads the monitoring sequence: the migration of seismicity from depth upward is a classic signal of magma ascending in the conduit; the appearance of LP earthquakes and harmonic tremor specifically indicates magma or magmatic fluid moving through a conduit resonator at shallow depth; SO₂ appearing from a previously quiet system indicates fresh magma entering the shallow zone and degassing; and lava dome appearance confirms that magmatic eruption has begun. The alert escalation to Warning/Level 4–5 is appropriate. LP earthquake transitions are not normal seasonal hydrothermal variation — seasonal hydrothermal fluctuations produce gradual, cyclic changes, not the sustained upward migration of earthquake foci combined with dome growth described in the scenario; B dangerously understates the urgency and could lead to inadequate protective actions (B is incorrect and potentially lethal advice in this scenario). Seismicity increase alone is not sufficient to justify maximum evacuation — that would be the approach most likely to produce false alarms and erode public trust; the full multi-parameter picture described in A is the appropriate basis for alert escalation (C is poorly calibrated). Hypocentre depths of 5–8 km are entirely consistent with volcanic earthquake generation by magma intrusion — volcanic earthquakes are not restricted to depths >10 km; LP earthquakes are specifically associated with fluid or magma movement and are not artefacts of instrument calibration errors; the described data pattern is unambiguously volcanic in character (D is factually incorrect on the seismology).",
        },
        {
          q: "The USGS Volcano Disaster Assistance Program (VDAP) was established in 1986 specifically to respond rapidly to developing volcanic crises in countries that lack adequate monitoring infrastructure. When a major volcano begins erupting in a developing country, VDAP can deploy a complete monitoring network (seismometers, GPS, gas sensors) and scientific team within days. What is the scientific and ethical rationale for this international response capability, and what limitations does it face?",
          a: [
            "VDAP exists primarily to protect US military and economic interests in developing countries — most US-assisted volcanic crises have been at volcanoes near US military bases (Pinatubo) or near US-owned mining or agricultural operations; the humanitarian framing is secondary to geopolitical motivations; developing countries should build their own monitoring infrastructure rather than depending on US rapid-response teams",
            "The scientific rationale is that volcanic crises rarely allow months for instrument procurement and installation; a crisis monitoring network must be operational within days to provide meaningful precursory data before the most dangerous eruptive phase; VDAP fills this gap for the ~1,200 historically active volcanoes in low-resource countries that have no permanent monitoring infrastructure; the ethical rationale is that the capacity to prevent mass volcanic fatalities exists and should be deployed where risk is highest, not only where resources are greatest; limitations include: data from a rapidly deployed network may have calibration uncertainties; cultural and linguistic barriers to communication; political complications when evacuation decisions require government authority; and the fundamental challenge that some eruption types (phreatic) cannot be forecast even with optimal monitoring",
            "VDAP has no scientific justification — monitoring data from a 2-week-old network cannot provide reliable eruption forecasts because there is no baseline to compare against; reliable volcanic monitoring requires years of background data collection before the network can identify anomalous signals; emergency deployment networks provide false scientific confidence without actual forecasting capability",
            "The primary limitation of VDAP deployments is that they require the consent of the host country government, which is always withheld because developing countries view volcanic monitoring assistance as an expression of scientific imperialism; in practice VDAP has never successfully deployed to a country outside of those with pre-existing agreements with the US State Department",
          ],
          correct: 1,
          explain: "While geopolitical factors do influence which countries receive international assistance, the characterisation of VDAP as primarily serving US military/economic interests is an unfair and incomplete representation of an agency that has also responded to crises in Montserrat, Nicaragua, Ecuador, Indonesia, and Democratic Republic of Congo — not merely at volcanoes near US assets; and the argument that developing countries 'should build their own infrastructure' ignores the acute time-critical nature of volcanic crises (A mischaracterises VDAP's purpose and provides no constructive alternative for the immediate problem). A 2-week-old monitoring network does lack years of baseline data, but this limitation is less severe than A implies — volcanic precursors (SO₂ flux starting from zero, earthquakes at a previously quiet volcano, ground deformation) are often diagnostic even without a pre-crisis baseline; the Pinatubo network was deployed in early April 1991 and provided critical precursory data within weeks; C overstates the baseline requirement and understates what emergency networks can achieve. VDAP has successfully deployed to multiple countries outside pre-existing US State Department agreements — the Nyiragongo 2002 eruption (DRC), Merapi 2010 (Indonesia), and others; consent is always sought and usually granted because host country agencies want the monitoring capability; D is factually incorrect about VDAP's operational history. The correct answer is B: the VDAP model reflects the recognition that monitoring infrastructure and scientific expertise are unevenly distributed globally while volcanic risk is concentrated in rapidly developing countries near active volcanic arcs (particularly the Pacific Ring of Fire and the Mediterranean). The ~1,200 historically active volcanoes outside the US, Europe, Japan, and New Zealand include many with populations of hundreds of thousands in high-hazard zones and zero permanent monitoring. VDAP's rapid-deployment capability allows scientific monitoring to begin within the first days of a crisis — when precursory data is most valuable for forecasting the climactic event. The ethical argument is straightforward: the capacity to prevent mass fatalities exists and should be deployed where need is greatest, not restricted by national boundaries or resource availability. The real limitations are those described in B: calibration uncertainties of a new network, communication barriers, political constraints on evacuation authority, and the inherent limits of monitoring science for certain eruption types.",
        },
        {
          q: "In 1993, nine people — including several volcanologists attending an international volcano conference — were killed inside the summit crater of Galeras volcano (Colombia) when a sudden explosion occurred. One volcanologist, Stanley Williams (who survived but was severely injured), had reportedly warned conference attendees that monitoring data suggested increased volcanic activity and that descending into the crater was dangerous. Yet the group descended. What does this event reveal about the human factors in volcanic risk management, and how have protocols changed to reduce similar incidents?",
          a: [
            "The Galeras disaster reveals that volcanologists are uniquely qualified to make their own safety decisions in volcanic environments; the deaths occurred because the scientists ignored clear danger — had they followed Williams's warning, they would have survived; the lesson is that in high-risk scientific environments, the most experienced voice must be obeyed, even if they are not the formal leader of the expedition",
            "The Galeras disaster reveals that scientific authority does not automatically translate into safety-critical decision-making authority: even within a group of experts, group dynamics, peer pressure, the prestige of being 'the person who went to the top,' and optimism bias can override individual concerns; the scientists who descended likely did not believe they were in imminent danger — each individual's subjective risk assessment was lower than the available monitoring data warranted; post-Galeras, volcanic field work has incorporated formal safety management systems (including written risk assessments, escalation protocols, designated safety officers, and prohibition on crater entry above specified alert levels) modelled on industrial safety frameworks, moving away from sole reliance on individual expert judgment",
            "The Galeras disaster is primarily a failure of monitoring technology — had the observatory been properly equipped with real-time seismic and gas monitoring, the explosion would have been predicted hours or days in advance, and the scientists would not have been in the crater; the human factors are secondary to the technological failure; the lesson is that more monitoring investment, not safety culture change, is the primary response",
            "The Galeras disaster demonstrates that volcanic eruptions are fundamentally unpredictable and that even the best-equipped monitoring networks provide no meaningful warning for violent explosive events; therefore volcanologists must accept a high personal risk of death as an inherent professional hazard, and accident prevention is not a meaningful goal in the field",
          ],
          correct: 1,
          explain: "The lesson of Galeras is not simply 'obey the most experienced voice' — the social dynamics are more complex; Williams's warning was not universally accepted in the group, and the decision to descend reflected a collective judgment by multiple experienced scientists who weighed the risks differently; formal authority hierarchies are part of the solution (B's safety management systems) but not the complete solution described in A. Monitoring technology at Galeras was not completely absent — there was a monitoring network, and Williams was aware of the data suggesting increasing activity; the problem was how the data was interpreted and communicated, and how the group made a collective safety decision (C overstates the technology failure and understates the cultural factors). The claim that volcanic eruptions are fundamentally unpredictable and that accident prevention is not a meaningful goal directly contradicts the evidence from Pinatubo 1991 (58,000 evacuated, ~20,000 lives saved by monitoring and forecasting) and the subsequent improvement in volcanic field safety practices (D is both factually wrong and ethically problematic as a professional standard). The correct answer is B: the Galeras disaster is now studied as a case study in both volcanic crisis management and occupational safety psychology. The group of distinguished scientists had individual expert knowledge, but the group dynamic — the social pressure to participate in the crater descent at a prestigious conference, the optimism bias of experienced professionals who had survived previous field work, the absence of a formal authority structure to stop the descent — produced a collective decision that individual members might not have made alone. Post-Galeras changes in professional practice include: (1) formal written risk assessments required before any crater entry; (2) designated safety officers with authority to halt field work independently of scientific leaders; (3) alert-level-based prohibition on crater access (no crater entry above Level 2 at most observatories); (4) personal protective equipment requirements; (5) communication with observatory before descent. These changes reflect the adoption of industrial safety management frameworks (as used in mining, offshore drilling, aviation) into volcanological field practice — recognising that expert knowledge alone is insufficient to manage safety in high-consequence environments.",
        },
      ],
    },
  ],
}

export default volcanicMonitoring
